// Test: 28. Find The Index Of The First Occurrence In A String
// 144 test cases from LeetCodeDataset
// Run: node test.js

const { strStr } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n28. Find The Index Of The First Occurrence In A String\n");

test(strStr("ababcabcabababd", "ababd"), 10, 'Test 1');
test(strStr("abcde", "f"), -1, 'Test 2');
test(strStr("mississippi", "issi"), 1, 'Test 3');
test(strStr("sadbutsad", "sad"), 0, 'Test 4');
test(strStr("abababa", "aba"), 0, 'Test 5');
test(strStr("abcdefgh", "efg"), 4, 'Test 6');
test(strStr("abc", "c"), 2, 'Test 7');
test(strStr("aaaaa", "bba"), -1, 'Test 8');
test(strStr("mississippi", "issip"), 4, 'Test 9');
test(strStr("abc", "d"), -1, 'Test 10');
test(strStr("a", "a"), 0, 'Test 11');
test(strStr("hello", "ll"), 2, 'Test 12');
test(strStr("leetcode", "leeto"), -1, 'Test 13');
test(strStr("ababababab", "aba"), 0, 'Test 14');
test(strStr("randomrandomrandom", "random"), 0, 'Test 15');
test(strStr("abcdefgabcdefgabcdefg", "efg"), 4, 'Test 16');
test(strStr("abcdefg", ""), 0, 'Test 17');
test(strStr("a quick brown fox jumps over the lazy dog", "quack"), -1, 'Test 18');
test(strStr("abracadabra", "cad"), 4, 'Test 19');
test(strStr("aaaaaaabc", "aaaaaab"), 1, 'Test 20');
test(strStr("level", "eve"), 1, 'Test 21');
test(strStr("aaaaaa", "aaa"), 0, 'Test 22');
test(strStr("abababab", "aba"), 0, 'Test 23');
test(strStr("abcde", ""), 0, 'Test 24');
test(strStr("xylophone", "phone"), 4, 'Test 25');
test(strStr("abcdeabcdeabcde", "deabc"), 3, 'Test 26');
test(strStr("quickbrownfox", "quick"), 0, 'Test 27');
test(strStr("repeatedstringrepeatedstring", "string"), 8, 'Test 28');
test(strStr("abcde", "abcde"), 0, 'Test 29');
test(strStr("noinneedlehere", "needle"), 4, 'Test 30');
test(strStr("banana", "ana"), 1, 'Test 31');
test(strStr("abcdefghijklmnopqrstuvwxyz", "mnop"), 12, 'Test 32');
test(strStr("abcabcabcabcabcabc", "abcabc"), 0, 'Test 33');
test(strStr("boundarycase", "boundarycase"), 0, 'Test 34');
test(strStr("abcabcabcabc", "bcabc"), 1, 'Test 35');
test(strStr("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "mnopqrstuv"), -1, 'Test 36');
test(strStr("sequence", "qu"), 2, 'Test 37');
test(strStr("bananananana", "nan"), 2, 'Test 38');
test(strStr("aaaaaaaaaaaaaaaaaa", "aaaaaaaaaa"), 0, 'Test 39');
test(strStr("abcdefghij", "jihgfedcba"), -1, 'Test 40');
test(strStr("abcdefghij", "abcdefghij"), 0, 'Test 41');
test(strStr("thisisaverylongstringwithsomecharacters", "characters"), 29, 'Test 42');
test(strStr("thisisaverylongstringwithsomerepeatingpatterns", "patterns"), 38, 'Test 43');
test(strStr("thesamethesame", "thesame"), 0, 'Test 44');
test(strStr("noon", "noon"), 0, 'Test 45');
test(strStr("hellohellohellohellohello", "hellohello"), 0, 'Test 46');
test(strStr("nnnnnnnnnn", "nnnn"), 0, 'Test 47');
test(strStr("12345678901234567890", "56789012"), 4, 'Test 48');
test(strStr("12345678901234567890", "56789"), 4, 'Test 49');
test(strStr("abcabcabcabcabc", "cab"), 2, 'Test 50');
test(strStr("thisisaverylonghaystack", "averylong"), 6, 'Test 51');
test(strStr("hellohellohello", "hellohello"), 0, 'Test 52');
test(strStr("singleletter", "a"), -1, 'Test 53');
test(strStr("oneonetwoonethreeonethreeone", "three"), 12, 'Test 54');
test(strStr("abcabcabcabcabcabc", "cab"), 2, 'Test 55');
test(strStr("pythonprogrammingpython", "thonpro"), 2, 'Test 56');
test(strStr("repeatedcharactersequenceeeeeeeeeeeeeee", "eeeeeeee"), 24, 'Test 57');
test(strStr("abcdabcyabcdabc", "abcdabc"), 0, 'Test 58');
test(strStr("mississippi", "issipp"), 4, 'Test 59');
test(strStr("aaaaabaaaabaaaaabaaaabaaaaabaaaabaaaaabaaaab", "baaab"), -1, 'Test 60');
test(strStr("aaaaaa", "aaaaaaa"), -1, 'Test 61');
test(strStr("abcdefghijklmnopqrstuvwxyz", "xyz"), 23, 'Test 62');
test(strStr("overlaplaplaplaplap", "lap"), 4, 'Test 63');
test(strStr("aaaaabaaaaaa", "aaaaab"), 0, 'Test 64');
test(strStr("helloworldhelloworld", "worldhello"), 5, 'Test 65');
test(strStr("abracadabra", "abra"), 0, 'Test 66');
test(strStr("abababababababababab", "ababab"), 0, 'Test 67');
test(strStr("aabbccddeeffgghhiijjkk", "eeffgg"), 8, 'Test 68');
test(strStr("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "mnop"), -1, 'Test 69');
test(strStr("mississippiissippi", "issip"), 4, 'Test 70');
test(strStr("aquickbrownfoxjumpsoverthelazydog", "dog"), 30, 'Test 71');
test(strStr("abababababababab", "ababab"), 0, 'Test 72');
test(strStr("almostsameprefixalmost", "almost"), 0, 'Test 73');
test(strStr("qwertyuiopasdfghjklzxcvbnm", "qwertyuiop"), 0, 'Test 74');
test(strStr("ananananananan", "anana"), 0, 'Test 75');
test(strStr("averylongstringwithrepeatedcharactersaaaaaaaaa", "aaaaaaaa"), 37, 'Test 76');
test(strStr("", ""), 0, 'Test 77');
test(strStr("findinganoccurrenceinanarray", "anoccurrence"), 7, 'Test 78');
test(strStr("repeatedrepeatedrepeated", "repeated"), 0, 'Test 79');
test(strStr("pythonprogramming", "programming"), 6, 'Test 80');
test(strStr("palindrome", "alin"), 1, 'Test 81');
test(strStr("singleletter", "s"), 0, 'Test 82');
test(strStr("aaaaaabaaaaaab", "aaaaaab"), 0, 'Test 83');
test(strStr("thisisaverylongstringthatwilltestouralgorithm", "longstring"), 11, 'Test 84');
test(strStr("this is a simple test", "simple"), 10, 'Test 85');
test(strStr("aaaaabaaaabaaaaabaaaab", "aaaab"), 1, 'Test 86');
test(strStr("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzz"), 0, 'Test 87');
test(strStr("repeatedrepeatedrepeated", "repeatedre"), 0, 'Test 88');
test(strStr("thelastwordisneedle", "needle"), 13, 'Test 89');
test(strStr("hellohellohello", "lohe"), 3, 'Test 90');
test(strStr("abababababab", "ababab"), 0, 'Test 91');
test(strStr("abababababab", "bababa"), 1, 'Test 92');
test(strStr("thisisaverylongstringforatest", "avery"), 6, 'Test 93');
test(strStr("overlappingoverlap", "lapping"), 4, 'Test 94');
test(strStr("findthehiddenpattern", "hidden"), 7, 'Test 95');
test(strStr("ababababab", "abab"), 0, 'Test 96');
test(strStr("asubstringrightattheend", "end"), 20, 'Test 97');
test(strStr("longstringthatcontainsavarietyofcharacters", "characters"), 32, 'Test 98');
test(strStr("bananaanabanana", "anaban"), 6, 'Test 99');
test(strStr("racecar", "race"), 0, 'Test 100');
test(strStr("longstringwithnokeyword", "keyword"), 16, 'Test 101');
test(strStr("abcdefghij", "gh"), 6, 'Test 102');
test(strStr("mississippi", "pi"), 9, 'Test 103');
test(strStr("verylonghaystackwithrepeatingcharactersaaaaaaaaaaa", "aaaaa"), 39, 'Test 104');
test(strStr("", "a"), -1, 'Test 105');
test(strStr("a", ""), 0, 'Test 106');
test(strStr("09876543210987654321", "654321"), 4, 'Test 107');
test(strStr("hellohellohello", "hello"), 0, 'Test 108');
test(strStr("aaaaaaaaaaa", "aaaaaa"), 0, 'Test 109');
test(strStr("thisisaverylongstringthatcontainsmultiplesubstrings", "substring"), 41, 'Test 110');
test(strStr("uniquecharacters", "characters"), 6, 'Test 111');
test(strStr("aaaaaaab", "aaaab"), 3, 'Test 112');
test(strStr("almosttherealmost", "almostthere"), 0, 'Test 113');
test(strStr("aaaaaaaaaab", "aaaaaab"), 4, 'Test 114');
test(strStr("aaaaabaaaaabaaaaab", "aaaaab"), 0, 'Test 115');
test(strStr("a quick brown fox jumps over the lazy dog", "quick"), 2, 'Test 116');
test(strStr("thisisaverylongstringwithrepeatedpatterns", "repeated"), 25, 'Test 117');
test(strStr("thisisaverylonghaystackthatcontainsavariablesubstring", "substring"), 44, 'Test 118');
test(strStr("xxyyzzxxyyzzxxyyzz", "xxyyzz"), 0, 'Test 119');
test(strStr("aaaaa", "aa"), 0, 'Test 120');
test(strStr("ababababababababa", "abab"), 0, 'Test 121');
test(strStr("a quick brown fox jumps over the lazy dog", "lazy"), 33, 'Test 122');
test(strStr("needleinthestack", "needle"), 0, 'Test 123');
test(strStr("aaaaaaaaaaaaaaaaaaaa", "aaaaaaaaa"), 0, 'Test 124');
test(strStr("aaaaaaab", "aaaaaab"), 1, 'Test 125');
test(strStr("aaaa", "aaaaa"), -1, 'Test 126');
test(strStr("substring", "string"), 3, 'Test 127');
test(strStr("xyzxyzxyzxyz", "zyx"), -1, 'Test 128');
test(strStr("abababababababababab", "abab"), 0, 'Test 129');
test(strStr("oneonetwoonetwothree", "twone"), -1, 'Test 130');
test(strStr("bananananana", "anan"), 1, 'Test 131');
test(strStr("xyxxyxyxyxyxyxyx", "xyxyx"), 3, 'Test 132');
test(strStr("aaaaabaaaa", "aaab"), 2, 'Test 133');
test(strStr("abcdefghij", "efgh"), 4, 'Test 134');
test(strStr("overlaplaplaplap", "laplap"), 4, 'Test 135');
test(strStr("thisisaverylongstringforsearching", "searching"), 24, 'Test 136');
test(strStr("bananabananabanana", "nan"), 2, 'Test 137');
test(strStr("longhaystackwithaveryspecificsubstring", "averyspecific"), 16, 'Test 138');
test(strStr("aaaaaaa", "aaaaaa"), 0, 'Test 139');
test(strStr("abcdefabcdefabcdefabcdef", "cdef"), 2, 'Test 140');
test(strStr("aaaaabaaaaabaaaaabaaaaab", "aaaab"), 1, 'Test 141');
test(strStr("hellohellohello", "lohel"), 3, 'Test 142');
test(strStr("abcdabcdabcd", "cdab"), 2, 'Test 143');
test(strStr("banana", "na"), 2, 'Test 144');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

