// Test: 1332. Remove Palindromic Subsequences
// 172 test cases from LeetCodeDataset
// Run: node test.js

const { removePalindromeSub } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1332. Remove Palindromic Subsequences\n");

test(removePalindromeSub("b"), 1, 'Test 1');
test(removePalindromeSub("aabbab"), 2, 'Test 2');
test(removePalindromeSub("baba"), 2, 'Test 3');
test(removePalindromeSub("aababb"), 2, 'Test 4');
test(removePalindromeSub("abbaab"), 2, 'Test 5');
test(removePalindromeSub("ab"), 2, 'Test 6');
test(removePalindromeSub("a"), 1, 'Test 7');
test(removePalindromeSub("ababa"), 1, 'Test 8');
test(removePalindromeSub("bbaabaaa"), 2, 'Test 9');
test(removePalindromeSub("aabbaa"), 1, 'Test 10');
test(removePalindromeSub(""), 1, 'Test 11');
test(removePalindromeSub("abb"), 2, 'Test 12');
test(removePalindromeSub("baabb"), 2, 'Test 13');
test(removePalindromeSub("aaaa"), 1, 'Test 14');
test(removePalindromeSub("bbbb"), 1, 'Test 15');
test(removePalindromeSub("abab"), 2, 'Test 16');
test(removePalindromeSub("baaaabb"), 2, 'Test 17');
test(removePalindromeSub("aaaaaaaaaabbbbbbbbbb"), 2, 'Test 18');
test(removePalindromeSub("babbabbbaba"), 2, 'Test 19');
test(removePalindromeSub("baabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabba"), 2, 'Test 20');
test(removePalindromeSub("bababababababababa"), 2, 'Test 21');
test(removePalindromeSub("bbaabbababb"), 2, 'Test 22');
test(removePalindromeSub("baaabaaaaaabbaaab"), 2, 'Test 23');
test(removePalindromeSub("aabbaabbaabb"), 2, 'Test 24');
test(removePalindromeSub("baabbaab"), 1, 'Test 25');
test(removePalindromeSub("baaababbabaababbabaababbabaababbabaababbabaababbabaababbabaababbabaababbabaababbabaababbabaababb"), 2, 'Test 26');
test(removePalindromeSub("abaababaababaababa"), 2, 'Test 27');
test(removePalindromeSub("aaabbaabbaabbaabba"), 2, 'Test 28');
test(removePalindromeSub("aabaaaab"), 2, 'Test 29');
test(removePalindromeSub("bbaaabbaaabbaaabbaa"), 2, 'Test 30');
test(removePalindromeSub("aabbabbaa"), 1, 'Test 31');
test(removePalindromeSub("bababa"), 2, 'Test 32');
test(removePalindromeSub("aaaaaaaabbaaaaaaa"), 2, 'Test 33');
test(removePalindromeSub("aaabbbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbbabbaabbbb"), 2, 'Test 34');
test(removePalindromeSub("aabbbbbaaa"), 2, 'Test 35');
test(removePalindromeSub("abbbabbbabbb"), 2, 'Test 36');
test(removePalindromeSub("abbaababbababbab"), 2, 'Test 37');
test(removePalindromeSub("aabbaabbabbaabbaabbabbaabbabbaabbaabbabbaabbabbaabbaabbabbaabbaabbabbaabbaabbabbaabbaabbabbaabbaabb"), 2, 'Test 38');
test(removePalindromeSub("baabbaabbbaaba"), 2, 'Test 39');
test(removePalindromeSub("bbbbbaaaaaaaaabbbb"), 2, 'Test 40');
test(removePalindromeSub("abbaabbbaabbaabbba"), 2, 'Test 41');
test(removePalindromeSub("aaabbbabaabbaa"), 2, 'Test 42');
test(removePalindromeSub("aaabbbbaaaaabbbbaa"), 2, 'Test 43');
test(removePalindromeSub("bbbbbaaaaa"), 2, 'Test 44');
test(removePalindromeSub("aabbbaaabbbaa"), 1, 'Test 45');
test(removePalindromeSub("bbbbbaaabbbbbaaabbbb"), 2, 'Test 46');
test(removePalindromeSub("baababababababababab"), 2, 'Test 47');
test(removePalindromeSub("bbbaabbaabbaabbaabbb"), 1, 'Test 48');
test(removePalindromeSub("bbbbbbbbbba"), 2, 'Test 49');
test(removePalindromeSub("bbaabbaabbaabbaab"), 2, 'Test 50');
test(removePalindromeSub("abbbabbbabbbbaba"), 2, 'Test 51');
test(removePalindromeSub("babbabbabbabbabbab"), 1, 'Test 52');
test(removePalindromeSub("abaaabbaaabbbaaaab"), 2, 'Test 53');
test(removePalindromeSub("aabbaabbaab"), 2, 'Test 54');
test(removePalindromeSub("aabbaabbbaabbaabbba"), 2, 'Test 55');
test(removePalindromeSub("bbaabbaab"), 2, 'Test 56');
test(removePalindromeSub("bbaabbbaaabb"), 2, 'Test 57');
test(removePalindromeSub("bbbbbbbbbbb"), 1, 'Test 58');
test(removePalindromeSub("abbaaabaaa"), 2, 'Test 59');
test(removePalindromeSub("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), 1, 'Test 60');
test(removePalindromeSub("ababbbababbbabaabb"), 2, 'Test 61');
test(removePalindromeSub("abbaabbaabbaabba"), 1, 'Test 62');
test(removePalindromeSub("aabbbbaaabaaaabbbb"), 2, 'Test 63');
test(removePalindromeSub("abbbabbbabbbabbbabbb"), 2, 'Test 64');
test(removePalindromeSub("babababababababab"), 1, 'Test 65');
test(removePalindromeSub("abbaabbbaabbaabbaa"), 2, 'Test 66');
test(removePalindromeSub("bbaabaaaabb"), 2, 'Test 67');
test(removePalindromeSub("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"), 1, 'Test 68');
test(removePalindromeSub("bababababa"), 2, 'Test 69');
test(removePalindromeSub("aaabbbaaabbbbaaa"), 2, 'Test 70');
test(removePalindromeSub("aaaaaaaaaabbbbbbbb"), 2, 'Test 71');
test(removePalindromeSub("aabbaaabbbaaabbaaa"), 2, 'Test 72');
test(removePalindromeSub("ababababababab"), 2, 'Test 73');
test(removePalindromeSub("aaaaaa"), 1, 'Test 74');
test(removePalindromeSub("abababababa"), 1, 'Test 75');
test(removePalindromeSub("abababababababab"), 2, 'Test 76');
test(removePalindromeSub("aaaaaaaaaabbbbbbbbbbaaaaaaaaaaabbbbbbbbbbaaaaaaaaaaabbbbbbbbbbaaaaaaaaaaabbbbbbbbbbaaaaaaaaaa"), 1, 'Test 77');
test(removePalindromeSub("baaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaa"), 2, 'Test 78');
test(removePalindromeSub("abababababab"), 2, 'Test 79');
test(removePalindromeSub("ababababababababab"), 2, 'Test 80');
test(removePalindromeSub("aabaaabbaaaab"), 2, 'Test 81');
test(removePalindromeSub("abababbabababababab"), 2, 'Test 82');
test(removePalindromeSub("baaaabbbaabb"), 2, 'Test 83');
test(removePalindromeSub("bbbbbbbbaaaaaabbbbbbbbaaaaaabbbbbbbbaaaaaabbbbbbbbaaaaaabbbbbbbbaaaaaabbbbbbbbaaaaaabbbbbbbbaaaaaa"), 2, 'Test 84');
test(removePalindromeSub("aaaaaaaaaaaaaaaaaa"), 1, 'Test 85');
test(removePalindromeSub("bbbababaabbabababb"), 2, 'Test 86');
test(removePalindromeSub("bbbbabbbbb"), 2, 'Test 87');
test(removePalindromeSub("aaaaaaabbbbb"), 2, 'Test 88');
test(removePalindromeSub("bbaabbbaa"), 2, 'Test 89');
test(removePalindromeSub("baabbaaabbbaabbaab"), 2, 'Test 90');
test(removePalindromeSub("abbbbbba"), 1, 'Test 91');
test(removePalindromeSub("bbbbbbbbbbbbbbbbbbb"), 1, 'Test 92');
test(removePalindromeSub("babbbbabbbbabbbbab"), 1, 'Test 93');
test(removePalindromeSub("abababababababababababababab"), 2, 'Test 94');
test(removePalindromeSub("aabbbaaaabbbbaa"), 2, 'Test 95');
test(removePalindromeSub("abaabaabaabaabaaba"), 1, 'Test 96');
test(removePalindromeSub("aabbaabbbaaabbbaab"), 2, 'Test 97');
test(removePalindromeSub("aabababababa"), 2, 'Test 98');
test(removePalindromeSub("aaaabbbb"), 2, 'Test 99');
test(removePalindromeSub("abbaabbbaabbaa"), 2, 'Test 100');
test(removePalindromeSub("ababababababababababab"), 2, 'Test 101');
test(removePalindromeSub("baabbaabbaabbaab"), 1, 'Test 102');
test(removePalindromeSub("ababbababbab"), 2, 'Test 103');
test(removePalindromeSub("abababababababababab"), 2, 'Test 104');
test(removePalindromeSub("abaabaabaabaabaabaa"), 2, 'Test 105');
test(removePalindromeSub("abababab"), 2, 'Test 106');
test(removePalindromeSub("bbbbbaaabbbbabab"), 2, 'Test 107');
test(removePalindromeSub("bababababababa"), 2, 'Test 108');
test(removePalindromeSub("babababab"), 1, 'Test 109');
test(removePalindromeSub("aabbabbbabaabbabbb"), 2, 'Test 110');
test(removePalindromeSub("abababa"), 1, 'Test 111');
test(removePalindromeSub("aabbbbbaa"), 1, 'Test 112');
test(removePalindromeSub("bbbaaaabbbbbaaaabb"), 2, 'Test 113');
test(removePalindromeSub("aabbaabbaabbaabbaabbaab"), 2, 'Test 114');
test(removePalindromeSub("ababbbabaabab"), 2, 'Test 115');
test(removePalindromeSub("aaaaaaaaaabbbaaaaaaaaaaabbbaaaaaaaaaaabbbaaaaaaaaaaabbbaaaaaaaaaaabbbaaaaaaaaaaabbbaaaaaaaaaaa"), 2, 'Test 116');
test(removePalindromeSub("babab"), 1, 'Test 117');
test(removePalindromeSub("abababababababababababa"), 1, 'Test 118');
test(removePalindromeSub("aabbaabbbaa"), 2, 'Test 119');
test(removePalindromeSub("babababababababababa"), 2, 'Test 120');
test(removePalindromeSub("abbabbabb"), 2, 'Test 121');
test(removePalindromeSub("bbbbbaaaabaaaabbbb"), 2, 'Test 122');
test(removePalindromeSub("bbbbbbbbbaaaaaaaaaa"), 2, 'Test 123');
test(removePalindromeSub("ababababbababa"), 2, 'Test 124');
test(removePalindromeSub("ababbbaba"), 1, 'Test 125');
test(removePalindromeSub("abababaabbabababab"), 2, 'Test 126');
test(removePalindromeSub("bbbbbbbbbbbbbbbbbb"), 1, 'Test 127');
test(removePalindromeSub("aabbaabbaabbaabbaa"), 1, 'Test 128');
test(removePalindromeSub("aaaaabbbbbaaaa"), 2, 'Test 129');
test(removePalindromeSub("aaaaaaaaaabbbbbbbbbbbaaaaaaaaa"), 2, 'Test 130');
test(removePalindromeSub("aabbaabbabbaaabb"), 2, 'Test 131');
test(removePalindromeSub("bbaabbaabbaa"), 2, 'Test 132');
test(removePalindromeSub("aabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabb"), 2, 'Test 133');
test(removePalindromeSub("bababbbabababbbaba"), 2, 'Test 134');
test(removePalindromeSub("baabbaabbaabba"), 2, 'Test 135');
test(removePalindromeSub("ababab"), 2, 'Test 136');
test(removePalindromeSub("aabbabba"), 2, 'Test 137');
test(removePalindromeSub("ababbbbaababbbbaabab"), 2, 'Test 138');
test(removePalindromeSub("bbaaabaaabaaaaabbb"), 2, 'Test 139');
test(removePalindromeSub("bababababab"), 1, 'Test 140');
test(removePalindromeSub("bababababababab"), 1, 'Test 141');
test(removePalindromeSub("bbaaaabbbbaaa"), 2, 'Test 142');
test(removePalindromeSub("bbbaabbbbabbbabbbba"), 2, 'Test 143');
test(removePalindromeSub("abbaabbaabba"), 1, 'Test 144');
test(removePalindromeSub("bbaabbaabbaabbaabbaabbaab"), 2, 'Test 145');
test(removePalindromeSub("abaababa"), 2, 'Test 146');
test(removePalindromeSub("ababbbababbbababbbab"), 2, 'Test 147');
test(removePalindromeSub("ababbababbabab"), 2, 'Test 148');
test(removePalindromeSub("baaaaab"), 1, 'Test 149');
test(removePalindromeSub("aababbabaab"), 2, 'Test 150');
test(removePalindromeSub("aabbaaabbaa"), 1, 'Test 151');
test(removePalindromeSub("abababababababababa"), 1, 'Test 152');
test(removePalindromeSub("aaaaaaaaabbbbbbbbb"), 2, 'Test 153');
test(removePalindromeSub("bbbaaabbbbaaaabbba"), 2, 'Test 154');
test(removePalindromeSub("bbaaaaabbbbba"), 2, 'Test 155');
test(removePalindromeSub("abbbbaaaaabbba"), 2, 'Test 156');
test(removePalindromeSub("abbaabba"), 1, 'Test 157');
test(removePalindromeSub("aaaaaaaaaaaaaaaaaaa"), 1, 'Test 158');
test(removePalindromeSub("aabbaaaabbbbaaabbbbaaaabbbaaabbbbaaaabbbaaabbbbaaaabbbaaabbbbaaaabbbaaabbbbaaaabbbaaabbbbaaaabbbbaaaabb"), 2, 'Test 159');
test(removePalindromeSub("abbbbabbbbabbbbabbbb"), 2, 'Test 160');
test(removePalindromeSub("ababababa"), 1, 'Test 161');
test(removePalindromeSub("abababbabaabbababbab"), 2, 'Test 162');
test(removePalindromeSub("babbbbbbbabbbbbbb"), 2, 'Test 163');
test(removePalindromeSub("bbaaaaaabbbaaaaaab"), 2, 'Test 164');
test(removePalindromeSub("abababababababababababababababababababababababababababababababababababababababababababababababababab"), 2, 'Test 165');
test(removePalindromeSub("bbbbbaaaaabbbbbaaaaa"), 2, 'Test 166');
test(removePalindromeSub("ababbababa"), 2, 'Test 167');
test(removePalindromeSub("babababa"), 2, 'Test 168');
test(removePalindromeSub("aababbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabbabbaabb"), 2, 'Test 169');
test(removePalindromeSub("baabbaabbaab"), 1, 'Test 170');
test(removePalindromeSub("ababbbababbbabaab"), 2, 'Test 171');
test(removePalindromeSub("ababababababababababababababababababababababababababababababababababababababababababababababababababababababababab"), 2, 'Test 172');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

