// Test: 591. Tag Validator
// 234 test cases from LeetCodeDataset
// Run: node test.js

const { isValid } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n591. Tag Validator\n");

test(isValid("<A>abc</A>"), true, 'Test 1');
test(isValid("<A><![CDATA[wahaha]]]></A>"), true, 'Test 2');
test(isValid("<A><B><![CDATA[CDATA]]></B></A>"), true, 'Test 3');
test(isValid("<A><B></C></B></A>"), false, 'Test 4');
test(isValid("This is the first line <div>""), Error: Solution.isValid[] missing 1 required positional argument: 'code', 'Test 5');
test(isValid("This is the first line <DIV></DIV>"), false, 'Test 6');
test(isValid("<![CDATA[CDATA_CONTENT]]>"), true, 'Test 7');
test(isValid("<A><B></A></B>"), false, 'Test 8');
test(isValid("<A> <B> <C></C> </B> </A>"), true, 'Test 9');
test(isValid("This is the first line <DIV> [CDATA[CDATA_CONTENT]] </DIV>"), false, 'Test 10');
test(isValid("<A></A><![CDATA[unmatched < > ]]>), Error: Solution.isValid[] missing 1 required positional argument: 'code', 'Test 11');
test(isValid(">>  ![cdata[]] <div>]>]]>>]"), false, 'Test 12');
test(isValid("<A><![CDATA[CDATA]]></A>"), true, 'Test 13');
test(isValid("This is the first line <DIV><SPAN></SPAN></DIV>"), false, 'Test 14');
test(isValid("<A></A><B></B>"), false, 'Test 15');
test(isValid("<A><A><A></A></A></A>"), true, 'Test 16');
test(isValid("<A><TAG></TAG></A>"), true, 'Test 17');
test(isValid("<A><A>456</A>  <A> 123  <B> <C>  123 </C> <B></B> </A></A>"), false, 'Test 18');
test(isValid("<![CDATA[CDATA_CONTENT]]></DIV>"), false, 'Test 19');
test(isValid("      "), false, 'Test 20');
test(isValid("<A>text <![CDATA[CDATA_CONTENT]]></A>"), true, 'Test 21');
test(isValid("<A><![CDATA[CDATA</A>"]]>"), Error: Solution.isValid[] missing 1 required positional argument: 'code', 'Test 22');
test(isValid("<A><![CDATA[unmatched < > ]]></A>"), true, 'Test 23');
test(isValid("<A>abc<![CDATA[CDATA]]>def</A>"), true, 'Test 24');
test(isValid("<A><TAG>sometext</TAG></A>"), true, 'Test 25');
test(isValid("<A></B>"), false, 'Test 26');
test(isValid("<![CDATA[<![CDATA[]]]]><TAG>sometext</TAG>"), false, 'Test 27');
test(isValid("<A><![CDATA[CDATA_CONTENT]]></A>"), true, 'Test 28');
test(isValid("<A><B><C></C></B></A>"), true, 'Test 29');
test(isValid("<A></A><A></A>"), false, 'Test 30');
test(isValid("<A><A>abc</A></A>"), true, 'Test 31');
test(isValid("<![CDATA[unmatched < > ]]><TAG></TAG>"), false, 'Test 32');
test(isValid("<![CDATA[wahaha]]]><TAG>sometext</TAG>"), false, 'Test 33');
test(isValid("<A><B></B></A><A></A>"), false, 'Test 34');
test(isValid("<A></A>"), true, 'Test 35');
test(isValid("<A><B></B></A>"), true, 'Test 36');
test(isValid("<![CDATA[CDATA_CONTENT]]></CDATA>"), false, 'Test 37');
test(isValid("<VALID><![CDATA[<INVALID></INVALID>]]></VALID>"), true, 'Test 38');
test(isValid("<A>content<![CDATA[<B>content</B>]]></A><C>content</C><![CDATA[content]]></C>"), false, 'Test 39');
test(isValid("<A><B><C><D><E><![CDATA[ignore <F> here]]></E></D></C></B></A>"), true, 'Test 40');
test(isValid("<A><B><C><D></D></C></B></A>"), true, 'Test 41');
test(isValid("<S><E><![CDATA[<INVALID></INVALID>]]></E></S>"), true, 'Test 42');
test(isValid("<NESTEDCDATA><CDATA><![CDATA[Nested CDATA]]></CDATA>]]></NESTEDCDATA>"), false, 'Test 43');
test(isValid("<A><B><C><![CDATA[unmatched <]]></C></B></A>"), true, 'Test 44');
test(isValid("<A><B><C><![CDATA[<UNBALANCED></UNBALANCED></C></B></A>"), false, 'Test 45');
test(isValid("<P><![CDATA[<P><P><P><P><P><P><P>many</P></P></P></P></P></P></P>]]></P>"), true, 'Test 46');
test(isValid("<A><B><![CDATA[abc]]></B><![CDATA[def]]></A>"), true, 'Test 47');
test(isValid("<A><B><C><D><E><F><G><H><I><J><K></K></J></I></H></G></F></E></D></C></B></A>"), true, 'Test 48');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D></C></B>></A>"), true, 'Test 49');
test(isValid("<A><B><C><D><E><F><G><H><I><![CDATA[</I></H></G></F></E></D></C></B></A>"), false, 'Test 50');
test(isValid("<A><B><C><![CDATA[TEXT]]></C></B><D><![CDATA[TEXT]]></D></A>"), true, 'Test 51');
test(isValid("<A><B><![CDATA[<B>]]></A></B>"), false, 'Test 52');
test(isValid("<A><B><![CDATA[TEXT]]></B><![CDATA[TEXT]]></B></A>"), false, 'Test 53');
test(isValid("<A><B><C><![CDATA[<]]></C></B></A>"), true, 'Test 54');
test(isValid("<A><![CDATA[ignore <B><C></C></B> here]]><B></B></A>"), true, 'Test 55');
test(isValid("<![CDATA[<A>content</A>]]><A>content</A>"), false, 'Test 56');
test(isValid("<A><![CDATA[</]]></A>"), true, 'Test 57');
test(isValid("<NINECHARS><INNER><INNERMOST></INNERMOST></INNER></NINECHARS>"), true, 'Test 58');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D></C></B></A></D>"), false, 'Test 59');
test(isValid("<A><B><![CDATA[</A><B>]]></B></A>"), true, 'Test 60');
test(isValid("<TAG><![CDATA[<TAG>data</TAG>]]></TAG>"), true, 'Test 61');
test(isValid("<![CDATA[<A>content</A>]]><B>content<![CDATA[<C>content</C>]]></B>"), false, 'Test 62');
test(isValid("<A><B><![CDATA[<A></A>]]></B></A>"), true, 'Test 63');
test(isValid("<A><B><![CDATA[<A><B></B></A>]]></B></A>"), true, 'Test 64');
test(isValid("<AA><BB><CC><DD><![CDATA[DDDD]]></DD></CC></BB></AA>"), true, 'Test 65');
test(isValid("<![CDATA[<A>content</A>]]><B><![CDATA[<C>content</C>]]></B>"), false, 'Test 66');
test(isValid("<A><B><![CDATA[TEXT]]></B><B><![CDATA[TEXT]]></B></A>"), true, 'Test 67');
test(isValid("<A><B><C><![CDATA[<D><E>deep</E></D>]]></C></B></A>"), true, 'Test 68');
test(isValid("<TAG><INNER><CDATA><TAG>invalid</TAG></CDATA></INNER></TAG>"), true, 'Test 69');
test(isValid("<![CDATA[This is a <tag> inside CDATA]]></CDATA><TAG></TAG>"), false, 'Test 70');
test(isValid("<A><B><![CDATA[<A><B></B>]]></B></A>"), true, 'Test 71');
test(isValid("<TAG>Some text <![CDATA[<TAG>more text</TAG>]]> even more text</TAG>"), true, 'Test 72');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D></C></B></A></C>"), false, 'Test 73');
test(isValid("<A><B><C><![CDATA[wahaha]]></C></B></D>"), false, 'Test 74');
test(isValid("<![CDATA[ignore <A><B><C> here]]></A></B></C>]]>"), false, 'Test 75');
test(isValid("<A><B><C><D><E><F><G><H><I><![CDATA[CDATA]]></I></H></G></F></E></D></C></B></A>"), true, 'Test 76');
test(isValid("<A><B><![CDATA[wahaha]]></B></C></A>"), false, 'Test 77');
test(isValid("<A><B><C><![CDATA[ignore <D></D> here]]></C></B></A>"), true, 'Test 78');
test(isValid("<A><B><C><![CDATA[CDATA]]></C></B></A>"), true, 'Test 79');
test(isValid("<A><B><![CDATA[<A>]]></B></A>"), true, 'Test 80');
test(isValid("<CODE><CODE><![CDATA[CODE]]></CODE></CODE>"), true, 'Test 81');
test(isValid("<T><![CDATA[This is a ]]><![CDATA[CDATA section]]></T>"), true, 'Test 82');
test(isValid("<A>content<![CDATA[<>]]>content</A>"), true, 'Test 83');
test(isValid("<LONGTAG><SHORT><LONGER></LONGER></SHORT></LONGTAG>"), true, 'Test 84');
test(isValid("<X><Y><Z><![CDATA[X]]></Z></Y></X>"), true, 'Test 85');
test(isValid("<A><B><C><![CDATA[TEXT]]></C></B></A>"), true, 'Test 86');
test(isValid("<A><B><C><![CDATA[<D></D>]]></C></B></A>"), true, 'Test 87');
test(isValid("<A>content<![CDATA[<B>content</B>]]>content</A>"), true, 'Test 88');
test(isValid("<A><![CDATA[<B></B>]]></A>"), true, 'Test 89');
test(isValid("<WRONG><TAG></WRONG></TAG>"), false, 'Test 90');
test(isValid("<TAG><![CDATA[<TAG>content</TAG>]]></TAG>"), true, 'Test 91');
test(isValid("<A><B><C><![CDATA[<D><E>INNER</E></D>]]></C></B></A>"), true, 'Test 92');
test(isValid("<A><![CDATA[<B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D></C></B>]]></A>"), false, 'Test 93');
test(isValid("<A><B><C><D><![CDATA[<E>]]></D></C></B></A>"), true, 'Test 94');
test(isValid("<A><B><C><D><E><F><![CDATA[FGHIJKL]]></F></E></D></C></B></A>"), true, 'Test 95');
test(isValid("<MULTIPLECDATA><![CDATA[First CDATA]]></MULTIPLECDATA><![CDATA[Second CDATA]]></MULTIPLECDATA>"), false, 'Test 96');
test(isValid("<A><B><![CDATA[wahaha]]></B></A><C></C>"), false, 'Test 97');
test(isValid("<NEST><INNER1><INNER2></INNER2></INNER1></NEST>"), false, 'Test 98');
test(isValid("<XYZ><XYZ><![CDATA[XYZ]]></XYZ></XYZ>"), true, 'Test 99');
test(isValid("<A><![CDATA[<B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D></C></B]]></A>"), false, 'Test 100');
test(isValid("<A><![CDATA[<B><C><D><E><F><G><H><I></I></H></G></F></E></D></C></B>]]></A>"), true, 'Test 101');
test(isValid("<OUTER><INNER><![CDATA[<OUTER><INNER>]]></INNER></OUTER>"), true, 'Test 102');
test(isValid("<A><B><![CDATA[wahaha>]]></B></A>"), true, 'Test 103');
test(isValid("<![CDATA[<NOTATAG><INSIDECDATA>]]></NOTATAG>]<A></A>"), false, 'Test 104');
test(isValid("<A><![CDATA[>]]></A>"), true, 'Test 105');
test(isValid("<A><B></B></A><![CDATA[abc<def>ghi]]>"), false, 'Test 106');
test(isValid("<X><![CDATA[<Y><Z></Z></Y>]]></X>"), true, 'Test 107');
test(isValid("<A><B><![CDATA[CDATA]]></B></A><C><![CDATA[CDATA]]></C><D><![CDATA[CDATA]]></D><E><![CDATA[CDATA]]></E><F><![CDATA[CDATA]]></F><G><![CDATA[CDATA]]></G><H><![CDATA[CDATA]]></H><I><![CDATA[CDATA]]></I>"), false, 'Test 108');
test(isValid("<A>content<![CDATA[<B>content</B>]]></A><C><![CDATA[content]]></C>"), false, 'Test 109');
test(isValid("<X1><X2><X3></X3><X4><X5><X6></X6></X5></X4></X2></X1>"), false, 'Test 110');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D>></C></B></A>"), true, 'Test 111');
test(isValid("<INVALID><INNER></INNER></OUTER>"), false, 'Test 112');
test(isValid("<A><![CDATA[abc<def>ghi]]></A>"), true, 'Test 113');
test(isValid("<SINGLE><CDATA></CDATA></SINGLE><![CDATA[<![CDATA[<SINGLE>]]></SINGLE>]]>"), false, 'Test 114');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D></C></B></A></A>"), false, 'Test 115');
test(isValid("<A><B><![CDATA[abc]]></B><![CDATA[def]></A>"), false, 'Test 116');
test(isValid("<A><B></B><C></C><D></D><E></E></A>"), true, 'Test 117');
test(isValid("<NESTED><INSIDE><MOREINSIDE>content</MOREINSIDE></INSIDE></NESTED>"), false, 'Test 118');
test(isValid("<Z><Z></Z></Z><Z><Z></Z></Z>"), false, 'Test 119');
test(isValid("<A><B><C><![CDATA[<UNBALANCED>data</C></B></A>"), false, 'Test 120');
test(isValid("<A><B><C><![CDATA[wahaha>]]></C></B></A>"), true, 'Test 121');
test(isValid("<X><Y><Z></Z></Y></X> <![CDATA[DATA]]></X>"), false, 'Test 122');
test(isValid("<A><![CDATA[<B>![CDATA[wahaha]]]>]]></A>"), true, 'Test 123');
test(isValid("<TAG1><TAG2><![CDATA[valid CDATA]]></TAG2><TAG3>content</TAG3></TAG1>"), false, 'Test 124');
test(isValid("<A><B><![CDATA[CDATA]]></B></A><C><![CDATA[CDATA]]></C><D><![CDATA[CDATA]]></D><E><![CDATA[CDATA]]></E><F><![CDATA[CDATA]]></F>"), false, 'Test 125');
test(isValid("<A><![CDATA[<B><![CDATA[wahaha]]]]></A>"), true, 'Test 126');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha]]></G></F>></E></D></C></B></A>"), true, 'Test 127');
test(isValid("<A><![CDATA[<B><C><D><E>CDATA</E></D></C></B>]]></A>"), true, 'Test 128');
test(isValid("<A><![CDATA[ignore <B><C></C></B> here]]></A><B></B>"), false, 'Test 129');
test(isValid("<A><B><C><![CDATA[<UNBALANCED></C></B></A>"), false, 'Test 130');
test(isValid("<A><B><C><![CDATA[ignore <D> here]]></C></B></A>"), true, 'Test 131');
test(isValid("<A><![CDATA[ignore <B><C></C></B> here]]></A>"), true, 'Test 132');
test(isValid("<A><![CDATA[<A><B><C></C></B></A>]]></A>"), true, 'Test 133');
test(isValid("<TAG>some <TAG> nested <TAG></TAG> tags</TAG></TAG>"), true, 'Test 134');
test(isValid("<A><![CDATA[<B>content</B>]]></A><B>content</B><![CDATA[content]]></A>"), false, 'Test 135');
test(isValid("<MAIN><SUB1><SUB2>data</SUB2></SUB1></MAIN>"), false, 'Test 136');
test(isValid("<A><![CDATA[<B><![CDATA[<C>content</C>]]></B>]]></A>"), false, 'Test 137');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D></C>></B></A>"), true, 'Test 138');
test(isValid("<A><![CDATA[<B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D></C></B>></A>"), false, 'Test 139');
test(isValid("<VALID><INNER> <![CDATA[<INNER>CDATA_CONTENT</INNER>]]> </INNER></VALID>"), true, 'Test 140');
test(isValid("<NESTED><INNER>CONTENT</INNER></NESTED>"), true, 'Test 141');
test(isValid("<PARENT><CHILD><GRANDCHILD></GRANDCHILD></CHILD></PARENT><![CDATA[<PARENT><CHILD></CHILD></PARENT>]]></PARENT>"), false, 'Test 142');
test(isValid("<ROOT><CHILD><![CDATA[<DIV>unparsed</DIV>]]></CHILD></ROOT>"), true, 'Test 143');
test(isValid("<A><B><C><![CDATA[<D></E>]]></C></B></A>"), true, 'Test 144');
test(isValid("<A><B><![CDATA[<A></B>]]></A>"), false, 'Test 145');
test(isValid("<A><![CDATA[<B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D></C></B></A>></A>"), false, 'Test 146');
test(isValid("<X><Y><![CDATA[<Z>]]></X></Y></Z>"), false, 'Test 147');
test(isValid("<A><B><C></C></B></A><![CDATA[<D>]]></D>]><A>"), false, 'Test 148');
test(isValid("<A><B><C></C></B><![CDATA[TEXT]]></A>"), true, 'Test 149');
test(isValid("<VALID><INNER>TEXT<![CDATA[CDATA_CONTENT]]></INNER></VALID>"), true, 'Test 150');
test(isValid("<A><B><![CDATA[CDATA]]></B></A><C><D><![CDATA[CDATA]]></D></C><E><F><![CDATA[CDATA]]></F></E><G><H><![CDATA[CDATA]]></H></G><I><J><![CDATA[CDATA]]></J></I>"), false, 'Test 151');
test(isValid("<A><B><C></D></C></B></A>"), false, 'Test 152');
test(isValid("<A><![CDATA[<]]></A>"), true, 'Test 153');
test(isValid("<MAIN><SUB1><SUB2></SUB2></SUB1></MAIN>"), false, 'Test 154');
test(isValid("<A><![CDATA[content]]></A><B>content</B>"), false, 'Test 155');
test(isValid("<A><![CDATA[TEXT]]></A><![CDATA[TEXT]]></A>"), false, 'Test 156');
test(isValid("<ROOT><CHILD1><GRANDCHILD></GRANDCHILD></CHILD1><CHILD2></CHILD2></ROOT>"), false, 'Test 157');
test(isValid("<A><B><![CDATA[<C></D>]]></B></A>"), true, 'Test 158');
test(isValid("<ROOT><![CDATA[<A></A>]]></ROOT>"), true, 'Test 159');
test(isValid("<A><B><C><![CDATA[wahaha]]></C></B></A>"), true, 'Test 160');
test(isValid("<A><B><![CDATA[<C><D></C>]]></D></B></A>"), false, 'Test 161');
test(isValid("<A><![CDATA[content]]></A>"), true, 'Test 162');
test(isValid("<A><B><![CDATA[ignore <TAG> and </TAG> here]]></B></A>"), true, 'Test 163');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D></C></B></A></B>"), false, 'Test 164');
test(isValid("<P><A><![CDATA[<BR>]]></A><SPAN>text</SPAN></P>"), true, 'Test 165');
test(isValid("<A><B><C><D><E></E></D></C></B></A>"), true, 'Test 166');
test(isValid("<OUTER><MID><![CDATA[<INNER></INNER>]]></MID></OUTER>"), true, 'Test 167');
test(isValid("<TAG1><TAG2><TAG3>CONTENT</TAG3></TAG2></TAG1>"), false, 'Test 168');
test(isValid("<A><B><C><![CDATA[<D><E>CDATA</E></D>]]></C></B></A>"), true, 'Test 169');
test(isValid("<A><B><![CDATA[CDATA]]></B></A><C><![CDATA[CDATA]]></C><D><![CDATA[CDATA]]></D>"), false, 'Test 170');
test(isValid("<A><B><C><![CDATA[unmatched </]]></C></B></A>"), true, 'Test 171');
test(isValid("<A><![CDATA[<B><C><D><E><F><G><![CDATA[wahaha>]]></G></F></E></D></C></B>]]></A>"), false, 'Test 172');
test(isValid("<A><B><![CDATA[CDATA]]></B></A><C><![CDATA[CDATA]]></C><D><![CDATA[CDATA]]></D><E><![CDATA[CDATA]]></E>"), false, 'Test 173');
test(isValid("<T><T><![CDATA[<T><T>INNER</T></T>]]></T></T>"), true, 'Test 174');
test(isValid("<![CDATA[ignore <A><B><C></C></B></A> here]]>"), true, 'Test 175');
test(isValid("<TAG><![CDATA[<TAG><![CDATA[CDATA_CONTENT]]></TAG>]]></TAG>"), false, 'Test 176');
test(isValid("<HELLO><WORLD><![CDATA[<HELLO>world</WORLD>]]></HELLO>"), false, 'Test 177');
test(isValid("<A><B><![CDATA[not <CLOSING]]></B></A>"), true, 'Test 178');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E>></D></C></B></A>"), true, 'Test 179');
test(isValid("<A><B><C><![CDATA[TEXT]]></C><D><![CDATA[TEXT]]></D></B></A>"), true, 'Test 180');
test(isValid("<A><B><C><![CDATA[</]]></C></B></A>"), true, 'Test 181');
test(isValid("<A><B><C><![CDATA[<D><E><![CDATA[CONTENT]]></E></D>]]></C></B></A>"), false, 'Test 182');
test(isValid("<A><B><C><D><E><F><G></G></F></E></D></C></B></A>"), true, 'Test 183');
test(isValid("<A><![CDATA[CDATA]]></A><B><![CDATA[CDATA]]></B><C><![CDATA[CDATA]]></C><D><![CDATA[CDATA]]></D><E><![CDATA[CDATA]]></E><F><![CDATA[CDATA]]></F><G><![CDATA[CDATA]]></G>"), false, 'Test 184');
test(isValid("<A><B><C><D><E><F><G><H><I></I></H></G></F></E></D></C></B></A>"), true, 'Test 185');
test(isValid("<A><B><![CDATA[<A>]]><C></C></B></A>"), true, 'Test 186');
test(isValid("<A><B><C><D><![CDATA[<E><F></F>]]></D></C></B></A>"), true, 'Test 187');
test(isValid("<A><B><C></C></B><D><![CDATA[TEXT]]></D></A>"), true, 'Test 188');
test(isValid("<NEST><INNER><![CDATA[<NEST><INNER><![CDATA[CDATA_CONTENT]]></INNER></NEST>]]></INNER></NEST>"), false, 'Test 189');
test(isValid("<A><B><C><![CDATA[>]]></C></B></A>"), true, 'Test 190');
test(isValid("<CORRECT><INSIDE></INSIDE></CORRECT>"), true, 'Test 191');
test(isValid("<A><B><C><D><E><F><G><H><I><J><K><L><M><N><O><P><Q><R><S><T><U><V><W><X><Y><Z></Z></Y></X></W></V></U></T></S></R></Q></P></O></N></M></L></K></J></I></H></G></F></E></D></C></B></A>"), true, 'Test 192');
test(isValid("<A><B><C><![CDATA[<D><E><![CDATA[CDATA_CONTENT]]></E></D>]]></C></B></A>"), false, 'Test 193');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha]]></F></E></D></C></B></A>"), false, 'Test 194');
test(isValid("<A><B>content<![CDATA[<C>content</C>]]></B></A>"), true, 'Test 195');
test(isValid("<![CDATA[<NOTATAG>data</NOTATAG>]]><VALID></VALID>"), false, 'Test 196');
test(isValid("<LAYER1><LAYER2><LAYER3></LAYER3></LAYER2></LAYER1>"), false, 'Test 197');
test(isValid("<TAG><INNER><![CDATA[<INNER>CDATA_CONTENT</INNER>]]> <![CDATA[TEXT]]></INNER></TAG>"), true, 'Test 198');
test(isValid("<A><B><C></C><![CDATA[TEXT]]></B></A>"), true, 'Test 199');
test(isValid("<![CDATA[<Z><Z></Z></Z><Z><Z></Z></Z>]]></Z>"), false, 'Test 200');
test(isValid("<A><![CDATA[<B>content</B>]]></A><C><![CDATA[content]]></C><D>content</D>"), false, 'Test 201');
test(isValid("<OUTER><MID><INNER>TEXT</INNER> <![CDATA[TEXT]]></MID></OUTER>"), true, 'Test 202');
test(isValid("<A><B><C><D><E><![CDATA[ABCDE]]></E></D></C></B></A>"), true, 'Test 203');
test(isValid("<A><![CDATA[&]][CDATA[]]><B></B></A>"), true, 'Test 204');
test(isValid("<A><![CDATA[<B>content</B>]]></A><C><![CDATA[content]]></C>"), false, 'Test 205');
test(isValid("<A><![CDATA[content]]></A><![CDATA[morecontent]]>"), false, 'Test 206');
test(isValid("<NEST><LVL1><LVL2><LVL3><![CDATA[<NEST><LVL1>deep</LVL1></NEST>]]></LVL3></LVL2></LVL1></NEST>"), false, 'Test 207');
test(isValid("<A><B>content</B><![CDATA[content]]></A>"), true, 'Test 208');
test(isValid("<A><B><C><D><E><![CDATA[ignore <F></F> here]]></E></D></C></B></A>"), true, 'Test 209');
test(isValid("<A><B><C><![CDATA[<A><B><C>]]></C></B></A>"), true, 'Test 210');
test(isValid("<A><![CDATA[<!CDATA[CDATA_CONTENT]]]]><B></B></A>"), true, 'Test 211');
test(isValid("<A><B><![CDATA[This is a <C></C> test]]></B></A>"), true, 'Test 212');
test(isValid("<A><B><![CDATA[<C></C>]]></B></A>"), true, 'Test 213');
test(isValid("<OUTER><INNER><![CDATA[<INNER>CDATA</INNER>]]></INNER></OUTER>"), true, 'Test 214');
test(isValid("<![CDATA[ignore <TAG> tags <INSIDE> </INSIDE> </TAG> ]]>"), true, 'Test 215');
test(isValid("<A><B><C></C><D><![CDATA[TEXT]]></D></B></A>"), true, 'Test 216');
test(isValid("<A><B><C></C><D></D></B></A>"), true, 'Test 217');
test(isValid("<![CDATA[ignore <A><B><C></C></B></A> here]]><A></A>"), false, 'Test 218');
test(isValid("<A><B><![CDATA[<C><D></D></C>]]></B><C><D><![CDATA[<E><F></F></E>]]></D></C></A>"), true, 'Test 219');
test(isValid("<ALMOST><INNER><![CDATA[</INNER>]]></ALMOST>"), false, 'Test 220');
test(isValid("<A><B><C><![CDATA[unmatched ]]></C></B></A>"), true, 'Test 221');
test(isValid("<A><![CDATA[<B><![CDATA[wahaha>]]></A>"), true, 'Test 222');
test(isValid("<X><Y><![CDATA[Not a tag>]]></Y></X>"), true, 'Test 223');
test(isValid("<A><![CDATA[This is some text <B></B> with CDATA]]></A>"), true, 'Test 224');
test(isValid("<A><B><C></C></B></A><D></D>"), false, 'Test 225');
test(isValid("<A><B><![CDATA[<A></A>]]></B></A><C><D><![CDATA[<E></E>]]></D></C>"), false, 'Test 226');
test(isValid("<A><B>content<![CDATA[<C>content</C>]]></B><![CDATA[content]]></A>"), true, 'Test 227');
test(isValid("<A><![CDATA[<B>]]></A>"), true, 'Test 228');
test(isValid("<A><![CDATA[<B><C><D><E><F><G><![CDATA[wahaha]]></G></F></E></D></C></B></A>></B>"), false, 'Test 229');
test(isValid("<A><B><C><![CDATA[wahaha]]></C></D></B></A>"), false, 'Test 230');
test(isValid("<A><B><![CDATA[<B></C>]]></B></A>"), true, 'Test 231');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha]]></G>></F></E></D></C></B></A>"), true, 'Test 232');
test(isValid("<A>content<![CDATA[<B>content</B>]]></A>"), true, 'Test 233');
test(isValid("<A><B><C><D><E><F><G><![CDATA[wahaha>]]></F></E></D></C></B></A>"), false, 'Test 234');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

// Auto-mark DONE when all tests pass
if (!failed) {
  const path = require("path");
  const fs = require("fs");
  const dir = __dirname;
  const folder = path.basename(dir);
  if (!folder.startsWith("DONE-")) {
    const parent = path.dirname(dir);
    const newDir = path.join(parent, "DONE-" + folder);
    fs.renameSync(dir, newDir);
    const readme = path.join(newDir, "README.md");
    if (fs.existsSync(readme)) {
      let c = fs.readFileSync(readme, "utf-8");
      if (!c.includes("<!-- SOLVED -->")) {
        c = c.replace(/^(# .+)$/m, "$1 ✅\n<!-- SOLVED -->");
        fs.writeFileSync(readme, c);
      }
    }
    console.log("✅ DONE → " + "DONE-" + folder);
  }
}
