// Test: 955. Delete Columns To Make Sorted Ii
// 210 test cases from LeetCodeDataset
// Run: node test.js

const { minDeletionSize } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n955. Delete Columns To Make Sorted Ii\n");

test(minDeletionSize(["ppp","qqq","rrr"]), 0, 'Test 1');
test(minDeletionSize(["az","za"]), 0, 'Test 2');
test(minDeletionSize(["xc","yb","za"]), 0, 'Test 3');
test(minDeletionSize(["dog","cat","bat"]), 2, 'Test 4');
test(minDeletionSize(["abcdef","uvwxyz"]), 0, 'Test 5');
test(minDeletionSize(["abcd","abce","abcf"]), 0, 'Test 6');
test(minDeletionSize(["aaa","aaa","aaa"]), 0, 'Test 7');
test(minDeletionSize(["abc","bcd","cde"]), 0, 'Test 8');
test(minDeletionSize(["zzz","aaa","zzz"]), 3, 'Test 9');
test(minDeletionSize(["abc","acd","acc"]), 1, 'Test 10');
test(minDeletionSize(["zyx","wvu","tsr"]), 3, 'Test 11');
test(minDeletionSize(["axz","byz","cxz"]), 0, 'Test 12');
test(minDeletionSize(["abc","acd","ace"]), 0, 'Test 13');
test(minDeletionSize(["a","b","c"]), 0, 'Test 14');
test(minDeletionSize(["abc","bca","cab"]), 0, 'Test 15');
test(minDeletionSize(["zzz","zzz","zzz","zzz"]), 0, 'Test 16');
test(minDeletionSize(["dddd","ddda","dddd","dddd"]), 1, 'Test 17');
test(minDeletionSize(["aab","abc","aaa"]), 2, 'Test 18');
test(minDeletionSize(["ca","bb","ac"]), 1, 'Test 19');
test(minDeletionSize(["abcd","efgh","ijkl"]), 0, 'Test 20');
test(minDeletionSize(["az","by","cx"]), 0, 'Test 21');
test(minDeletionSize(["cba","daf","ghi"]), 0, 'Test 22');
test(minDeletionSize(["aab","aac","aba"]), 0, 'Test 23');
test(minDeletionSize(["ghi","daf","cba"]), 3, 'Test 24');
test(minDeletionSize(["abcd","efgh","ijkl","mnop"]), 0, 'Test 25');
test(minDeletionSize(["aaa","bbb","ccc"]), 0, 'Test 26');
test(minDeletionSize(["a","b","c","d"]), 0, 'Test 27');
test(minDeletionSize(["cba","bca","cab"]), 2, 'Test 28');
test(minDeletionSize(["pqrs","qrsn","rsnp","snpq"]), 0, 'Test 29');
test(minDeletionSize(["abcdef","ghijkl","mnopqr","stuvwx","yzabcd"]), 0, 'Test 30');
test(minDeletionSize(["aax","aba","aca","ada"]), 0, 'Test 31');
test(minDeletionSize(["aab","bac","aaa"]), 2, 'Test 32');
test(minDeletionSize(["xyz","yza","zab","abc","bcd"]), 3, 'Test 33');
test(minDeletionSize(["xyzz","yxzz","zxyy","zyyx"]), 0, 'Test 34');
test(minDeletionSize(["abc", "bcd", "cde", "def", "efg", "fgh", "ghi", "hij", "ijk", "jkl", "klm", "lmn", "mno", "nop", "opq", "pqr", "qrs", "rst", "stu", "tuv", "uvw", "vwx", "wxy", "xyz"]), 0, 'Test 35');
test(minDeletionSize(["abc","cab","bca","bac","acb","cba"]), 3, 'Test 36');
test(minDeletionSize(["fgh","ghi","hij","ijk","jkl"]), 0, 'Test 37');
test(minDeletionSize(["abcdef","bcdefg","cdefgh","defghi","efghij"]), 0, 'Test 38');
test(minDeletionSize(["aaaaa","aaabb","aabaa","aabbb","abaaa","ababb","abaab","ababa","abbaa","abbab","abbba","abbbb","baaaa","baaab","baaba","baabb","bbaaa","bbaab","bbaba","bbbaa","bbbb","caaaa","caaab","caaba","caabb","cbaaa","cbaab","cbaba","cbbaa","cbbbb","daaaa","daaab","daaba","daabb","dbaaa","dbaab","dbaba","dbbaa","dbbbb","eaaaa","eaab","eaaba","eaabb","ebaaa","ebaab","ebaba","ebbaa","ebbbb","faaaa","faaab","faaba","faabb","fbaaa","fbaab","fbaba","fbbaa","fbbbb"]), 2, 'Test 39');
test(minDeletionSize(["zzzzz", "zzzzx", "zzzzy", "zzzzz", "zzzzz"]), 1, 'Test 40');
test(minDeletionSize(["abcde","bcdef","cdefg","defgh","efghi"]), 0, 'Test 41');
test(minDeletionSize(["abcd","bcde","cdef","defg","efgh","fghi","ghij"]), 0, 'Test 42');
test(minDeletionSize(["aaaaa", "aaabb", "aabbb", "abbbb", "bbbbb", "baaab", "baabb", "babbb", "bbaab", "bbabb", "bbbab", "bbbb"]), Error: string index out of range, 'Test 43');
test(minDeletionSize(["abc","bac","bca","cab","cba","acb"]), 3, 'Test 44');
test(minDeletionSize(["banana","bandana","bandanna"]), 0, 'Test 45');
test(minDeletionSize(["zzzzz","zzzzz","zzzzz","zzzzz","zzzzz","zzzzz","zzzzz","zzzzz","zzzzz"]), 0, 'Test 46');
test(minDeletionSize(["qrst","prst","qrst","qrst","qrst"]), 1, 'Test 47');
test(minDeletionSize(["ghijkl","hijklm","ijklmn","jklmno","klmnop"]), 0, 'Test 48');
test(minDeletionSize(["random","ranbom","randam","randbm","randmm"]), 2, 'Test 49');
test(minDeletionSize(["lmno","mnop","opqr","pqrs","qrst"]), 0, 'Test 50');
test(minDeletionSize(["xyz","zyx","wxy","uvw"]), 3, 'Test 51');
test(minDeletionSize(["xyzz","yxzz","zxyz","zzxy","zzzx"]), 0, 'Test 52');
test(minDeletionSize(["abcd","abdc","acdb","adbc"]), 0, 'Test 53');
test(minDeletionSize(["banana","banaba","banaaa","banbaa"]), 1, 'Test 54');
test(minDeletionSize(["zzzz","zzzy","zzzx","zzxw","zzvw","zxvw","xvwu"]), 4, 'Test 55');
test(minDeletionSize(["pqrst","qrstu","rstuv","stuvw","tuvwx","uvwxy","vwxyz"]), 0, 'Test 56');
test(minDeletionSize(["abcd","dcba","abcd","dcba"]), 4, 'Test 57');
test(minDeletionSize(["mnopqr","zyxwvu","tsrqup","lkjihg","fedcba"]), 6, 'Test 58');
test(minDeletionSize(["abcde","bcdea","cdeab","deabc","eabcd"]), 0, 'Test 59');
test(minDeletionSize(["apple","apply","appla"]), 1, 'Test 60');
test(minDeletionSize(["zzzz","zzzy","zzzx","zzxw","zzvw","zzuv","zztu"]), 2, 'Test 61');
test(minDeletionSize(["abcd","acbd","adbc","dabc","bdac"]), 4, 'Test 62');
test(minDeletionSize(["xyz", "xzy", "yxz", "yzx", "zxy", "zyx"]), 0, 'Test 63');
test(minDeletionSize(["apple", "apply", "appla", "apple", "applq"]), 1, 'Test 64');
test(minDeletionSize(["nmop","mnop","mnop","mnop"]), 1, 'Test 65');
test(minDeletionSize(["xyz","xyw","xyv","xyu","xyt","xys","xyr","xyp","xyo","xyn","xym","xyl","xyk","xyj","xyi","xyh","xyg","xyf","xye","xyd","xyc","xyb","xya"]), 1, 'Test 66');
test(minDeletionSize(["abcde","abcdf","abcef","abceg","abcde"]), 2, 'Test 67');
test(minDeletionSize(["zzzz","zzzy","zzyy","zyyy","yyyy","yyyz"]), 4, 'Test 68');
test(minDeletionSize(["random","randome","randomly","randomly","randomly"]), 0, 'Test 69');
test(minDeletionSize(["mnop","lmno","opqr","pqrs","qrst"]), 4, 'Test 70');
test(minDeletionSize(["aab", "abc", "abc"]), 0, 'Test 71');
test(minDeletionSize(["qwerty","asdfgh","zxcvbn"]), 6, 'Test 72');
test(minDeletionSize(["x","y","z","w","v","u","t","s","r","q","p","o","n","m","l","k","j","i","h","g","f","e","d","c","b","a"]), 1, 'Test 73');
test(minDeletionSize(["aabbcc","aabbbc","aabccc","aabccc","aabccc"]), 1, 'Test 74');
test(minDeletionSize(["abc","bce","cae"]), 0, 'Test 75');
test(minDeletionSize(["zebra","zaxar","zecos","zabba"]), 4, 'Test 76');
test(minDeletionSize(["abcdef","bcdegh","cdefgh","defghi","efghij","fghijk"]), 0, 'Test 77');
test(minDeletionSize(["aaaa","bbbb","cccc","dddd","eeee","ffff","gggg","hhhh"]), 0, 'Test 78');
test(minDeletionSize(["apple","apply","appla","apppa"]), 1, 'Test 79');
test(minDeletionSize(["abac","acba","baca","bcaa","cab","cba"]), 0, 'Test 80');
test(minDeletionSize(["abcd","bcad","acbd"]), 1, 'Test 81');
test(minDeletionSize(["abcd","adcb","bacd"]), 0, 'Test 82');
test(minDeletionSize(["abcdabcd","bcdbcdbd","cdcddcdc","dedededc","eeedeeec"]), 0, 'Test 83');
test(minDeletionSize(["aaaa","aaab","aaba","aabb","abaa","abab","abba","abbb","baaa","baab","baba","babb","bbaa","bbab","bbba","bbbb"]), 0, 'Test 84');
test(minDeletionSize(["abcd","abdc","acdb","acbd"]), 2, 'Test 85');
test(minDeletionSize(["abcd","abdc","acbd","acdb","adbc","adcb","bacd","badc","bcad","bcda","bdac","bdca","cabd","cadb","cbad","cbda","cdab","cdba","dabc","dacb","dbac","dbca","dcab","dcba"]), 0, 'Test 86');
test(minDeletionSize(["aaaabbbb","bbbbaaaa","aabbaabb","abababab","bbaabbaa"]), 8, 'Test 87');
test(minDeletionSize(["acbac","bcbac","cbbac","dcbac","ecbac","fcbac"]), 0, 'Test 88');
test(minDeletionSize(["moon", "moan", "moon", "mane"]), 3, 'Test 89');
test(minDeletionSize(["aabbcc", "ababcc", "aaccbb"]), 2, 'Test 90');
test(minDeletionSize(["aabbcc","abacbc","abcabc","aabcbc","aacbbc"]), 4, 'Test 91');
test(minDeletionSize(["aaa","aba","aaa","aca","aaa"]), 1, 'Test 92');
test(minDeletionSize(["aa", "bb", "aa", "bb", "aa", "bb", "aa", "bb", "aa", "bb"]), 2, 'Test 93');
test(minDeletionSize(["aaaaa","aaabb","aabaa","aabab","aaced","aacef","aaceg","aaceh","aacei","aacej","aacek","aacei","aacej","aacek","aacei","aacej","aacek","aacei","aacej","aacek"]), 1, 'Test 94');
test(minDeletionSize(["aaa","aab","aac","aad","aae","aaf","aag","aah","aai","aaj","aak","aal","aam","aan","aao","aap","aaq","aar","aas","aat","aau","aav","aaw","aax","aay","aaz"]), 0, 'Test 95');
test(minDeletionSize(["abcd","efgh","ijkl","mnop","qrst","uvwx","yzab"]), 0, 'Test 96');
test(minDeletionSize(["abcdef","bcdefa","cdefab","defabc","efabcd","fabcde"]), 0, 'Test 97');
test(minDeletionSize(["abcdef","uvwxyz","ghijkl"]), 6, 'Test 98');
test(minDeletionSize(["aaaa","aaab","aaac","aaba","aabb","aabc","aaca","aacb","aacc","abaa","abab","abac","abba","abbb","abbc","abca","abcb","abcc","acaa","acab","acac","acba","acbb","acbc","acca","accb","accc","baaa","baab","baac","baba","babb","babc","baca","bacb","bacc","bbaa","bbab","bbac","bbba","bbbb","bbbc","bbca","bbcb","bbcc","bcaa","bcab","bcac","bcba","bcbb","bcbc","bccb","bccc","caaa","caab","caac","caba","cabb","cabc","caca","cacb","cacc","cbaa","cbab","cbac","cbba","cbbb","cbbc","cbca","cbcb","cbcc","ccaa","ccab","ccac","ccba","ccbb","ccbc","ccca","cccb","cccc"]), 0, 'Test 99');
test(minDeletionSize(["mnop","mnop","mnop","mnop","mnop"]), 0, 'Test 100');
test(minDeletionSize(["pqrs", "psrq", "qrst", "rpsq", "srqp", "tqrs"]), 0, 'Test 101');
test(minDeletionSize(["aabc","abac","abca","acba","acab","baca","bacb","baac","bcaa","cab","cbab","caba","cbba","cbaa"]), 3, 'Test 102');
test(minDeletionSize(["lkjihg","kjihgf","jihgfe","ihgfed","hgfedc"]), 6, 'Test 103');
test(minDeletionSize(["abcdef","bcdefa","cdefab"]), 0, 'Test 104');
test(minDeletionSize(["monotonic","monotonicity","monotone","monotonicity","monotone"]), Error: string index out of range, 'Test 105');
test(minDeletionSize(["qwe","qaz","qwr"]), 2, 'Test 106');
test(minDeletionSize(["aaa","aab","aac","aad","baa","aba","aca","ada","baa","aba","aca","ada","baa","aba","aca","ada"]), 3, 'Test 107');
test(minDeletionSize(["banana", "bandana", "bandanna", "bandanna"]), 0, 'Test 108');
test(minDeletionSize(["zzzz","zzyz","zzyy","zzyx","zzyw"]), 2, 'Test 109');
test(minDeletionSize(["qwer","qweq","qwew","qwea","qwqa","qwaq","qwaq","qwaa","qaaa","qqaa","qqqa","qqqw","qqqq","qwqw","qwwq","qwqw","qqqw"]), 3, 'Test 110');
test(minDeletionSize(["abcdefgh","hgfedcba","abcdefgh","hgfedcba"]), 8, 'Test 111');
test(minDeletionSize(["aabcc","abcab","acaba","cacab","ccaba"]), 0, 'Test 112');
test(minDeletionSize(["baab","baab","baab","baab","baab","baab","baab","baab","baab","baab","baab","baab","baab","baab","baab","baab","baab","baab","baab","baab"]), 0, 'Test 113');
test(minDeletionSize(["abcd","abdc","acdb","adbc","aebc","afdc","agdb","ahbc"]), 0, 'Test 114');
test(minDeletionSize(["abcdef","bcdegh","cdefij"]), 0, 'Test 115');
test(minDeletionSize(["abcd","abce","abcf","abcd"]), 1, 'Test 116');
test(minDeletionSize(["abcdefg","bcdefga","cdefgab"]), 0, 'Test 117');
test(minDeletionSize(["abcd","abce","abcf","abcg"]), 0, 'Test 118');
test(minDeletionSize(["xyz","xyw","xyv","xyu","xyt","xys","xyr","xqq","xpp","xoo","xnn","xmm","xll","xkk","xjj","xii","xhh","xgg","xff","xee","xed","xec","xeb","xea"]), 2, 'Test 119');
test(minDeletionSize(["abcd", "azxy", "abcy"]), 2, 'Test 120');
test(minDeletionSize(["abcd","bcde","cdef","defg","efgh"]), 0, 'Test 121');
test(minDeletionSize(["hello", "hellp", "helpp", "helpq"]), 0, 'Test 122');
test(minDeletionSize(["qpwoeiruty","asdfghjklz","xcvbnm"]), 4, 'Test 123');
test(minDeletionSize(["aabbcc","bbccdd","ccddeeff","ddeeffgg","eeffgghh","ffgghhii","gghhiijj","hhiijjkk","iijjkkll","jjkkllmm","kkllmmnn","llmmnnoo","mmnnoopq","nnoopqrs","oopqrstu","pqrstuvw","qrstuvwx","rstuvwxy","stuvwxyz"]), 0, 'Test 124');
test(minDeletionSize(["aaaa", "aaba", "aabb", "abaa", "abab", "abbb", "baaa", "baab", "baba", "babb", "bbaa", "bbab", "bbbb"]), 0, 'Test 125');
test(minDeletionSize(["abc","bca","cab","bac","acb","cba"]), 3, 'Test 126');
test(minDeletionSize(["dog", "cat", "bat"]), 2, 'Test 127');
test(minDeletionSize(["aaaa","abaa","acaa","aada","abca","abda","acba","acda","aaca","aada","aaca","aaba","abba","abca","acca","adca","aada","aaca","aaca","aaba"]), 2, 'Test 128');
test(minDeletionSize(["zebra","zorro","zebra"]), 3, 'Test 129');
test(minDeletionSize(["aaaa","bbbb","cccc","dddd","eeee"]), 0, 'Test 130');
test(minDeletionSize(["pqrs","qrst","rstu","stuv"]), 0, 'Test 131');
test(minDeletionSize(["ghi","ghi","ghi"]), 0, 'Test 132');
test(minDeletionSize(["leetcode","lintcode","testcode"]), 0, 'Test 133');
test(minDeletionSize(["abcd","abdc","acbd"]), 0, 'Test 134');
test(minDeletionSize(["abcd","bcad","cdab"]), 0, 'Test 135');
test(minDeletionSize(["abcd","abdc","abcf"]), 2, 'Test 136');
test(minDeletionSize(["hello","helps","helpp"]), 1, 'Test 137');
test(minDeletionSize(["xga","xfb","yfa"]), 1, 'Test 138');
test(minDeletionSize(["aab","aac","aba","aca","baa","bac","bba","bbc"]), 0, 'Test 139');
test(minDeletionSize(["fed","efd","eef"]), 2, 'Test 140');
test(minDeletionSize(["cba","bca","abc"]), 2, 'Test 141');
test(minDeletionSize(["abc","def","ghi"]), 0, 'Test 142');
test(minDeletionSize(["xyz","xyw","xyv"]), 1, 'Test 143');
test(minDeletionSize(["cba","bac","bca"]), 3, 'Test 144');
test(minDeletionSize(["hello","helps","heroes"]), 0, 'Test 145');
test(minDeletionSize(['zzz', 'aaa', 'zzz']), 3, 'Test 146');
test(minDeletionSize(['zyx', 'wvu', 'tsr']), 3, 'Test 147');
test(minDeletionSize(["zzz","zyz","zxz"]), 1, 'Test 148');
test(minDeletionSize(["aab","aac","abc"]), 0, 'Test 149');
test(minDeletionSize(["abcd","dcba","abdc"]), 4, 'Test 150');
test(minDeletionSize(["zzz","zyx","zyy"]), 2, 'Test 151');
test(minDeletionSize(["zzzz","zzyy","zyzy","zyyz"]), 3, 'Test 152');
test(minDeletionSize(["aab","aac","aba","aca"]), 0, 'Test 153');
test(minDeletionSize(['dog', 'cat', 'bat']), 2, 'Test 154');
test(minDeletionSize(["abcd","abdc","acdb"]), 0, 'Test 155');
test(minDeletionSize(["zyxw","zyxv","zyxu"]), 1, 'Test 156');
test(minDeletionSize(["fed","efd","gfd"]), 1, 'Test 157');
test(minDeletionSize(["a","a","a","a"]), 0, 'Test 158');
test(minDeletionSize(["ghi","jkl","mno"]), 0, 'Test 159');
test(minDeletionSize(["zzz","zyx","zyw"]), 2, 'Test 160');
test(minDeletionSize(['abc', 'acd', 'aab']), 2, 'Test 161');
test(minDeletionSize(["zzzz","zzzz","zzzz"]), 0, 'Test 162');
test(minDeletionSize(["zzzz","zzyz","zzyy","zzyx"]), 2, 'Test 163');
test(minDeletionSize(["aaa","bbb","aaa"]), 3, 'Test 164');
test(minDeletionSize(["c","b","a"]), 1, 'Test 165');
test(minDeletionSize(["abcd","dcba","abcd"]), 4, 'Test 166');
test(minDeletionSize(["e","d","c","b","a"]), 1, 'Test 167');
test(minDeletionSize(['abcd', 'abcf', 'abcg']), 0, 'Test 168');
test(minDeletionSize(["zzz","zyz","zyx"]), 2, 'Test 169');
test(minDeletionSize(["apple","apricot","banana"]), 0, 'Test 170');
test(minDeletionSize(["leetcode","leet","code"]), Error: string index out of range, 'Test 171');
test(minDeletionSize(["aabbbabbb","bbbaabaab","aabbbbaab","abbbababa","bbaaabbbb","bbabaabab","abababbaa"]), 9, 'Test 172');
test(minDeletionSize(["abcd","dcba","mnop"]), 0, 'Test 173');
test(minDeletionSize(["fed","cab","dba"]), 3, 'Test 174');
test(minDeletionSize(["abcd","abcf","abce"]), 1, 'Test 175');
test(minDeletionSize(["cba","fed","ihg"]), 0, 'Test 176');
test(minDeletionSize(["abcd","abdc","acbd","dacb"]), 0, 'Test 177');
test(minDeletionSize(["zzz","zyz","yzz"]), 2, 'Test 178');
test(minDeletionSize(['hello', 'helps', 'heaps']), 1, 'Test 179');
test(minDeletionSize(["zzz","zzz","zzz"]), 0, 'Test 180');
test(minDeletionSize(['same', 'same', 'same']), 0, 'Test 181');
test(minDeletionSize(["abc","abc","abc"]), 0, 'Test 182');
test(minDeletionSize(["xyp","ypp","xyp"]), 2, 'Test 183');
test(minDeletionSize(["aab","aac","aab"]), 1, 'Test 184');
test(minDeletionSize(["zz","zy","zx"]), 1, 'Test 185');
test(minDeletionSize(["az","za","zz","aa"]), 2, 'Test 186');
test(minDeletionSize(["abcd","acbd","dabc","dbca"]), 0, 'Test 187');
test(minDeletionSize(["aaa","aab","aac"]), 0, 'Test 188');
test(minDeletionSize(["cba","cab","bac"]), 2, 'Test 189');
test(minDeletionSize(["hello","hilll","hillo"]), 0, 'Test 190');
test(minDeletionSize(["rrjk","furt","guzm"]), 1, 'Test 191');
test(minDeletionSize(["fed","dbc","cba"]), 3, 'Test 192');
test(minDeletionSize(["a","b","c","d","e"]), 0, 'Test 193');
test(minDeletionSize(["hello","hero","herm"]), Error: string index out of range, 'Test 194');
test(minDeletionSize(["hello","helps","hero"]), 0, 'Test 195');
test(minDeletionSize(["abc","acd","aec"]), 0, 'Test 196');
test(minDeletionSize(["ghi","def","abc"]), 3, 'Test 197');
test(minDeletionSize(["fedcba","fedcba","fedcba"]), 0, 'Test 198');
test(minDeletionSize(["azx","byy","czz"]), 0, 'Test 199');
test(minDeletionSize(['xc', 'yb', 'za']), 0, 'Test 200');
test(minDeletionSize(["abcd","abcc","abcb","abca"]), 1, 'Test 201');
test(minDeletionSize(["xzxbxyzz","xzyxzzzx","xzyxzzyz","zyzzzxzx"]), 1, 'Test 202');
test(minDeletionSize(['ca', 'bb', 'ac']), 1, 'Test 203');
test(minDeletionSize(["fed","efd","efd"]), 1, 'Test 204');
test(minDeletionSize(["axb","ayb","azb"]), 0, 'Test 205');
test(minDeletionSize(["leetcode","lintcode","gcd"]), Error: string index out of range, 'Test 206');
test(minDeletionSize(["pqrs","qrst","rstu"]), 0, 'Test 207');
test(minDeletionSize(["hello","helli","hellp"]), 1, 'Test 208');
test(minDeletionSize(["abc","acd","aab"]), 2, 'Test 209');
test(minDeletionSize(['a', 'b', 'c']), 0, 'Test 210');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

