// Test: 2942. Find Words Containing Character
// 141 test cases from LeetCodeDataset
// Run: node test.js

const { findWordsContaining } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n2942. Find Words Containing Character\n");

test(findWordsContaining(["abc","bcd","aaaa","cbc"], "z"), [], 'Test 1');
test(findWordsContaining(["python","programming"], "o"), [0, 1], 'Test 2');
test(findWordsContaining(["ab","cd","ef"], "g"), [], 'Test 3');
test(findWordsContaining(["aaaaa","bbbbb","ccccc"], "a"), [0], 'Test 4');
test(findWordsContaining(["apple","banana","cherry"], "a"), [0, 1], 'Test 5');
test(findWordsContaining(["hello","world"], "l"), [0, 1], 'Test 6');
test(findWordsContaining(["hello","world"], "o"), [0, 1], 'Test 7');
test(findWordsContaining(["algorithm","data","structure"], "t"), [0, 1, 2], 'Test 8');
test(findWordsContaining(["leet","code"], "e"), [0, 1], 'Test 9');
test(findWordsContaining(["red","blue","green"], "e"), [0, 1, 2], 'Test 10');
test(findWordsContaining(["sun","moon","star"], "u"), [0], 'Test 11');
test(findWordsContaining(["test","example","input"], "t"), [0, 2], 'Test 12');
test(findWordsContaining(["abc","bcd","aaaa","cbc"], "a"), [0, 2], 'Test 13');
test(findWordsContaining(["algorithm","data","structure"], "a"), [0, 1], 'Test 14');
test(findWordsContaining(["example","test","case"], "x"), [0], 'Test 15');
test(findWordsContaining(["unique","characters"], "u"), [0], 'Test 16');
test(findWordsContaining(["a","b","c"], "d"), [], 'Test 17');
test(findWordsContaining(["hello","world","python"], "o"), [0, 1, 2], 'Test 18');
test(findWordsContaining(["one","two","three"], "t"), [1, 2], 'Test 19');
test(findWordsContaining(["meeting","event","conference"], "e"), [0, 1, 2], 'Test 20');
test(findWordsContaining(["find","words","containing"], "n"), [0, 2], 'Test 21');
test(findWordsContaining(["python","java","csharp"], "p"), [0, 2], 'Test 22');
test(findWordsContaining(["dog","cat","bird"], "d"), [0, 2], 'Test 23');
test(findWordsContaining(["one","two","three"], "e"), [0, 2], 'Test 24');
test(findWordsContaining(["algorithm","datastructure","programming","interview"], "m"), [0, 2], 'Test 25');
test(findWordsContaining(["banana","apple","orange","grape"], "o"), [2], 'Test 26');
test(findWordsContaining(["interface","function","method","parameter","argument"], "p"), [3], 'Test 27');
test(findWordsContaining(["mississippi","delaware","indiana","illinois"], "i"), [0, 2, 3], 'Test 28');
test(findWordsContaining(["repeated","character","example"], "e"), [0, 1, 2], 'Test 29');
test(findWordsContaining(["mississippi","hawaii","alaska"], "i"), [0, 1], 'Test 30');
test(findWordsContaining(["quizzing","quiz","quizzes"], "z"), [0, 1, 2], 'Test 31');
test(findWordsContaining(["sunshine","rainbow","cloud","sky","ocean","beach"], "n"), [0, 1, 4], 'Test 32');
test(findWordsContaining(["xylophone","triangle","square","rectangle","pentagon"], "p"), [0, 4], 'Test 33');
test(findWordsContaining(["repetition","repeated","repetitive","repetition"], "p"), [0, 1, 2, 3], 'Test 34');
test(findWordsContaining(["mississippi","mississippian","mississippians","mississippify"], "p"), [0, 1, 2, 3], 'Test 35');
test(findWordsContaining(["xylophone","xylography","xylophonist"], "x"), [0, 1, 2], 'Test 36');
test(findWordsContaining(["abcdefghijklmnopqrstuvwxyz","zyxwvutsrqponmlkjihgfedcba","mnopqrstuvwxyz","abcdefghijklmnopqrstuvwxyz"], "a"), [0, 1, 3], 'Test 37');
test(findWordsContaining(["mississippi","hannah","racecar","level"], "i"), [0], 'Test 38');
test(findWordsContaining(["university","college","school","institute"], "u"), [0, 3], 'Test 39');
test(findWordsContaining(["docker","kubernetes","container","orchestration","deployment"], "d"), [0, 4], 'Test 40');
test(findWordsContaining(["python","java","c","javascript"], "v"), [1, 3], 'Test 41');
test(findWordsContaining(["repetition","occurrence","continuous","discontinuous"], "o"), [0, 1, 2, 3], 'Test 42');
test(findWordsContaining(["fantastic","extraordinary","remarkable","astonishing","amazing"], "a"), [0, 1, 2, 3, 4], 'Test 43');
test(findWordsContaining(["onlyonecharacter","twochars","threechars"], "c"), [0, 1, 2], 'Test 44');
test(findWordsContaining(["zebra","elephant","giraffe","hippopotamus"], "e"), [0, 1, 2], 'Test 45');
test(findWordsContaining(["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious"], "t"), [0, 1, 2], 'Test 46');
test(findWordsContaining(["abcdefg","hijklmn","opqrstu"], "x"), [], 'Test 47');
test(findWordsContaining(["floccinaucinihilipilification","supercalifragilisticexpialidocious"], "c"), [0, 1], 'Test 48');
test(findWordsContaining(["mississippi","misterious","mismatch","misconduct"], "m"), [0, 1, 2, 3], 'Test 49');
test(findWordsContaining(["responsive","design","user","interface"], "e"), [0, 1, 2, 3], 'Test 50');
test(findWordsContaining(["same","same","same"], "a"), [0, 1, 2], 'Test 51');
test(findWordsContaining(["abcdefghij","klmnopqrstu","vwxyz"], "x"), [2], 'Test 52');
test(findWordsContaining(["angular","react","vue","ember","svelte"], "a"), [0, 1], 'Test 53');
test(findWordsContaining(["algorithm","datastructure","programming"], "a"), [0, 1, 2], 'Test 54');
test(findWordsContaining(["programming","coding","software","development"], "o"), [0, 1, 2, 3], 'Test 55');
test(findWordsContaining(["encyclopedia","dictionary","thesaurus"], "o"), [0, 1], 'Test 56');
test(findWordsContaining(["environment","environmental","environments","environmentalist"], "v"), [0, 1, 2, 3], 'Test 57');
test(findWordsContaining(["abcdefghij","jihgfedcba","abcdefgh","dcba"], "f"), [0, 1, 2], 'Test 58');
test(findWordsContaining(["sequential","search","binary","hashmap"], "h"), [1, 3], 'Test 59');
test(findWordsContaining(["multifaceted","multicolored","multifarious","multilingual"], "m"), [0, 1, 2, 3], 'Test 60');
test(findWordsContaining(["optimization","complexity","graph","matrix"], "i"), [0, 1, 3], 'Test 61');
test(findWordsContaining(["xyz","zyx","yxz","zyzxzyx"], "x"), [0, 1, 2, 3], 'Test 62');
test(findWordsContaining(["database","schema","table","column","index"], "b"), [0, 2], 'Test 63');
test(findWordsContaining(["single"], "s"), [0], 'Test 64');
test(findWordsContaining(["university","algorithm","quantum","computer"], "u"), [0, 2, 3], 'Test 65');
test(findWordsContaining(["embedded","real","time","system"], "z"), [], 'Test 66');
test(findWordsContaining(["xylophone","guitar","drum","flute"], "u"), [1, 2, 3], 'Test 67');
test(findWordsContaining(["algorithm","datastructure","code","debug"], "a"), [0, 1], 'Test 68');
test(findWordsContaining(["pneumonoultramicroscopicsilicovolcanoconiosis","super","hyper","sub"], "o"), [0], 'Test 69');
test(findWordsContaining(["unbelievable","unbelievably","unbelievable","unbelievable"], "u"), [0, 1, 2, 3], 'Test 70');
test(findWordsContaining(["interstellar","galaxy","cosmic","universe"], "i"), [0, 2, 3], 'Test 71');
test(findWordsContaining(["mississippi","massachusetts","minimum"], "i"), [0, 2], 'Test 72');
test(findWordsContaining(["unitedstates","canada","mexico","brazil"], "a"), [0, 1, 3], 'Test 73');
test(findWordsContaining(["xylophone","xylo","xy","x"], "x"), [0, 1, 2, 3], 'Test 74');
test(findWordsContaining(["congratulations","celebration","felicitation"], "t"), [0, 1, 2], 'Test 75');
test(findWordsContaining(["apple","banana","cherry","date"], "b"), [1], 'Test 76');
test(findWordsContaining(["repetition","occurrence","frequency","Infinityrequent"], "r"), [0, 1, 2, 3], 'Test 77');
test(findWordsContaining(["machine","learning","artificial","intelligence","neural"], "a"), [0, 1, 2, 4], 'Test 78');
test(findWordsContaining(["character","charts","chocolate","chartreuse"], "c"), [0, 1, 2, 3], 'Test 79');
test(findWordsContaining(["supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis"], "s"), [0, 1], 'Test 80');
test(findWordsContaining(["hello","world","python","programming"], "m"), [3], 'Test 81');
test(findWordsContaining(["complexity","analysis","optimization"], "x"), [0], 'Test 82');
test(findWordsContaining(["banana","bandana","panacea"], "a"), [0, 1, 2], 'Test 83');
test(findWordsContaining(["python","java","csharp","javascript"], "p"), [0, 2, 3], 'Test 84');
test(findWordsContaining(["compiler","interpreter","virtual","machine"], "r"), [0, 1, 2], 'Test 85');
test(findWordsContaining(["repetition","character","sequence","word","dictionary"], "e"), [0, 1, 2], 'Test 86');
test(findWordsContaining(["typescript","javascript","python","java","csharp"], "s"), [0, 1, 4], 'Test 87');
test(findWordsContaining(["network","protocol","security","encryption","decryption"], "c"), [1, 2, 3, 4], 'Test 88');
test(findWordsContaining(["rain","rainbow","raining","raincoat"], "n"), [0, 1, 2, 3], 'Test 89');
test(findWordsContaining(["abc","acb","bac","bca","cab","cba"], "b"), [0, 1, 2, 3, 4, 5], 'Test 90');
test(findWordsContaining(["xylophone","xylography","xylophone"], "x"), [0, 1, 2], 'Test 91');
test(findWordsContaining(["abcdef","ghijkl","mnopqr","stuvwx","yzabcd"], "a"), [0, 4], 'Test 92');
test(findWordsContaining(["algorithm","data","structure","programming"], "a"), [0, 1, 3], 'Test 93');
test(findWordsContaining(["qwertyuiop","asdfghjkl","zxcvbnm","qwerty"], "t"), [0, 3], 'Test 94');
test(findWordsContaining(["environment","variable","configuration","parameter","setting"], "e"), [0, 1, 3, 4], 'Test 95');
test(findWordsContaining(["internet","of","things","iot"], "t"), [0, 2, 3], 'Test 96');
test(findWordsContaining(["xyz","zyx","yxz"], "z"), [0, 1, 2], 'Test 97');
test(findWordsContaining(["repetition","recursion","iteration","permutation"], "e"), [0, 1, 2, 3], 'Test 98');
test(findWordsContaining(["zebra","xylophone","zoo","zest"], "z"), [0, 2, 3], 'Test 99');
test(findWordsContaining(["quintessential","quotation","quiver","quadrilateral"], "q"), [0, 1, 2, 3], 'Test 100');
test(findWordsContaining(["unique","united","union","unity"], "i"), [0, 1, 2, 3], 'Test 101');
test(findWordsContaining(["supercalifragilisticexpialidocious","supercalifragilisticexpialidocious","supercalifragilisticexpialidocious"], "x"), [0, 1, 2], 'Test 102');
test(findWordsContaining(["database","management","query","optimization"], "q"), [2], 'Test 103');
test(findWordsContaining(["sequence","subsequence","consequence","dessequence"], "q"), [0, 1, 2, 3], 'Test 104');
test(findWordsContaining(["programming","language","python"], "o"), [0, 2], 'Test 105');
test(findWordsContaining(["compiler","interpreter","debugger","profiler","virtual"], "o"), [0, 3], 'Test 106');
test(findWordsContaining(["fantastic","fantasy","fantastic","fantastically"], "f"), [0, 1, 2, 3], 'Test 107');
test(findWordsContaining(["interview","question","answer","example"], "i"), [0, 1], 'Test 108');
test(findWordsContaining(["responsive","layout","flexbox","grid","animation"], "n"), [0, 4], 'Test 109');
test(findWordsContaining(["quick","brown","fox","jumps","over","the","lazy","dog"], "z"), [6], 'Test 110');
test(findWordsContaining(["abcdefghijklmnopqrstuvwxyz","zyxwvutsrqponmlkjihgfedcba","mnopqrstuvwxyzabcdefghijkl"], "m"), [0, 1, 2], 'Test 111');
test(findWordsContaining(["artificial","intelligence","machine","learning"], "i"), [0, 1, 2, 3], 'Test 112');
test(findWordsContaining(["encyclopedia","encyclopedia","encyclopedia","encyclopedia"], "n"), [0, 1, 2, 3], 'Test 113');
test(findWordsContaining(["apple","banana","cherry","date","elderberry"], "a"), [0, 1, 3], 'Test 114');
test(findWordsContaining(["filesystem","directory","permission","read","write"], "r"), [1, 2, 3, 4], 'Test 115');
test(findWordsContaining(["xylophone","xylography","xylophonist","xylophone"], "x"), [0, 1, 2, 3], 'Test 116');
test(findWordsContaining(["algorithm","data","structure","programming","design"], "g"), [0, 3, 4], 'Test 117');
test(findWordsContaining(["binary","search","tree","avl","hashmap"], "h"), [1, 4], 'Test 118');
test(findWordsContaining(["abcdefghij","klmnopqr","stuvwxyz"], "z"), [2], 'Test 119');
test(findWordsContaining(["verylongwordthatcontainsmanycharacters","short","tiny"], "w"), [0], 'Test 120');
test(findWordsContaining(["abcdefghijklmnopqrstuvwxyz","zyxwvutsrqponmlkjihgfedcba","aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"], "m"), [0, 1, 2], 'Test 121');
test(findWordsContaining(["alphabet","beta","gamma","delta","epsilon"], "a"), [0, 1, 2, 3], 'Test 122');
test(findWordsContaining(["nineteen","eighteen","seventeen"], "e"), [0, 1, 2], 'Test 123');
test(findWordsContaining(["concurrent","parallel","distributed","systems"], "c"), [0], 'Test 124');
test(findWordsContaining(["banana","ananas","pineapple","mango"], "n"), [0, 1, 2, 3], 'Test 125');
test(findWordsContaining(["supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis"], "o"), [0, 1], 'Test 126');
test(findWordsContaining(["frontend","backend","database","api","client"], "d"), [0, 1, 2], 'Test 127');
test(findWordsContaining(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"], "q"), [16], 'Test 128');
test(findWordsContaining(["embedded","real","time","system"], "b"), [0], 'Test 129');
test(findWordsContaining(["unique","words","only"], "q"), [0], 'Test 130');
test(findWordsContaining(["alphabet","xylophone","encyclopedia","dictionary","glossary"], "y"), [1, 2, 3, 4], 'Test 131');
test(findWordsContaining(["repeated","characters","in","words"], "e"), [0, 1], 'Test 132');
test(findWordsContaining(["longitudinal","lateral","longest","longevity"], "o"), [0, 2, 3], 'Test 133');
test(findWordsContaining(["continuous","integration","deployment","pipeline","automation"], "n"), [0, 1, 2, 3, 4], 'Test 134');
test(findWordsContaining(["algorithm","data","structures","binary"], "a"), [0, 1, 3], 'Test 135');
test(findWordsContaining(["documentation","repository","commit","branch","merge"], "m"), [0, 2, 4], 'Test 136');
test(findWordsContaining(["programming","language","python","java"], "o"), [0, 2], 'Test 137');
test(findWordsContaining(["blockchain","cryptography","security","privacy"], "y"), [1, 2, 3], 'Test 138');
test(findWordsContaining(["complex","complicated","complexContent","compulsive"], "c"), [0, 1, 2, 3], 'Test 139');
test(findWordsContaining(["programming","language","python"], "p"), [0, 2], 'Test 140');
test(findWordsContaining(["abcdefghijklmnopqrstuvwxyz","zyxwvutsrqponmlkjihgfedcba","mnopqrstuvwxyza"], "a"), [0, 1, 2], 'Test 141');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

