// Test: 2325. Decode The Message
// 231 test cases from LeetCodeDataset
// Run: node test.js

const { decodeMessage } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n2325. Decode The Message\n");

test(decodeMessage("zyxwvutsrqponmlkjihgfedcba", "cba zyx"), xyz abc, 'Test 1');
test(decodeMessage("jump quickly on this yellow pig", "fxudyjzjw lqdj fxej nqeo fxlwlt"), Error: 'f', 'Test 2');
test(decodeMessage("a quick movement of the enemy will jeopardize five gunboats", "yfcj myj pyjl ufcj myj pyjl ufcj myj pyjl"), omer gor sorq cmer gor sorq cmer gor sorq, 'Test 3');
test(decodeMessage("the five boxing wizards jump quickly on this yellow pig", "jhxuh lqdj efxgh lpuaz fxdyjzjw"), rbisb yvpr cdikb yusnm dipzrmrl, 'Test 4');
test(decodeMessage("move forward zippy vim", "qldu bxwrdlw ecfbv"), Error: 'q', 'Test 5');
test(decodeMessage("dvhfujngcpqxlwokzriebastmy", "mwtiaz azr"), ynxsvq vqr, 'Test 6');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "xyz abc"), xyz abc, 'Test 7');
test(decodeMessage("the quick brown fox jumps over the lazy dog", "vkbs bs t suepuv"), this is a secret, 'Test 8');
test(decodeMessage("byvzkgxfnqmpalwodjtrshceui", "xsm wv zmz"), guk oc dkd, 'Test 9');
test(decodeMessage("wmtresuavhigdcbfykjqploxzn", "lfnlccyvmdg"), vpzvnnqibml, 'Test 10');
test(decodeMessage("a quick movement of the enemy will jeopardize five gunboats", "ejp mysljylc kd kxveddknmc re jsicpdrysi"), Error: 'x', 'Test 11');
test(decodeMessage("gymnymphs fly by my wyrm", "cqdutsh sth sh ct sqwu"), Error: 'c', 'Test 12');
test(decodeMessage("zabcdefghijklmnopqrstuvwxy", "sl rfc zdf"), tm sgd aeg, 'Test 13');
test(decodeMessage("zyxwvutsrqponmlkjihgfedcba", "mlkjhgfedcbazyxwvutsrqpon"), nopqstuvwxyzabcdefghijklm, 'Test 14');
test(decodeMessage("eljuxhpwnyrdgtqkviszcfmabo", "zwx hnfx lqantp mnoeius ycgk vcnjrdb"), the five boxing wizards jump quickly, 'Test 15');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "z x c v"), z x c v, 'Test 16');
test(decodeMessage("gysrnhxvaofcedwmltukipjbqz", "gigv symykgl igxvxjxg"), auah cbpbtaq uaghgwga, 'Test 17');
test(decodeMessage("sixty zippers were quickly judged faulty", "lwhuv amvhfuhw dhu hulhuqj fxufqk mncuf"), Error: 'h', 'Test 18');
test(decodeMessage("phinxajsgkrzcwvltqbdemoufy", "xvo wv pmj"), eow no avg, 'Test 19');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "zaoymnbxcqrljtheifkgdvspwu"), zaoymnbxcqrljtheifkgdvspwu, 'Test 20');
test(decodeMessage("qwertyuiopasdfghjklzxcvbnm", "gsv jfrxp yildm ulc"), olw qnduj fhsmz gsv, 'Test 21');
test(decodeMessage("the five boxing wizards jump quickly on this june day", "ymj lvfx sflhzymhs vxlw wjymjlvfx sflhzymhs"), ztr yfdi qdybmztbq fiyl lrztryfdi qdybmztbq, 'Test 22');
test(decodeMessage("zyxwvutsrqponmlkjihgfedcba", "gsvjf rxpyi ldmul cqfnk hlevi gsvoz abwlt"), thequ ickbr ownfo xjump sover thela zydog, 'Test 23');
test(decodeMessage("dfghjklwcvxziomnpqrustyabe", "kckd ykky"), fifa wffw, 'Test 24');
test(decodeMessage("mnychdpbxofl wgviakjuzterqs", "irhvmvccsjb"), pxeoaoddzsh, 'Test 25');
test(decodeMessage("pack my box with five dozen liquor jugs", "xujf qv zgy jxpx qne nfgqj sraju"), ivxn uo ryf xiai usp snyux zwbxv, 'Test 26');
test(decodeMessage("vampires love unicorns flying by my wyrm", "di vccvmr wv czebwqha wv iv lvyrj"), Error: 'd', 'Test 27');
test(decodeMessage("mwp dhxjzvcqrkbyanflstguoei", "di vccvmr wv czebwqha wv iv lvyrj"), dz ijjial bi jhynbkep bi zi siolg, 'Test 28');
test(decodeMessage("zyxwvutsrqponmlkjihgfedcba", "a b c d"), z y x w, 'Test 29');
test(decodeMessage("the five boxing wizards jump quickly", "fmwp vifd ttp xosmead"), dtlu fedp aau ihqtcnp, 'Test 30');
test(decodeMessage("vuqangfkswjpryxtdmzobhcile", "wfn yv yfcv"), jge na ngwa, 'Test 31');
test(decodeMessage("abcdefghijk lmnopqrstuvwxyz", "eiqhw fjq hwdq"), eiqhw fjq hwdq, 'Test 32');
test(decodeMessage("cipher keys are always fun to create", "xjuwao awos wlu awjwy aojxw ao qjwjqao"), Error: 'x', 'Test 33');
test(decodeMessage("a quick movement of the enemy will jeopardize five gunboats", "zruog glhvg frp fvdw zl glcgv"), vtchw wqniw mts miup vq wqewi, 'Test 34');
test(decodeMessage("thejumpsquickbrownfoxoverlazydog", "svhjyjsiqphsjudprvcbgijz"), htbdxdhjigbhdeygntkmzjdw, 'Test 35');
test(decodeMessage("ab ac ad ae af ag ah ai aj ak al am an ao ap aq ar as at au av aw ax ay az", "qz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz"), qz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz vz, 'Test 36');
test(decodeMessage("swzybfrxlnaoumdgtqivhjkpce", "flgxswdliefyirukyoaqmpjc"), fiphaboiszfdsgmwdlkrnxvy, 'Test 37');
test(decodeMessage("all animals are equal but some animals are more equal than others", "zik xkkvmsw zmj xrsui zqtk ziv zsu xkkvmsw zmj iwti xrsui zqtk ziv zik"), Error: 'z', 'Test 38');
test(decodeMessage("the quick brown fox jumps over the lazy dog", "qruqz efn nhr htyq"), djedw cnm mbj baxd, 'Test 39');
test(decodeMessage("the quick brown fox jumps over the lazy dog", "xibohu uvp xibohu"), ofikbe etr ofikbe, 'Test 40');
test(decodeMessage("abcd efgh ijkl mnop qrst uvwx yz", "vuwx yz abcd ef"), vuwx yz abcd ef, 'Test 41');
test(decodeMessage("gymnopqrstuvwxzabcdefhiljk", "xqmgq zm zmjy"), ngcag oc ocyb, 'Test 42');
test(decodeMessage("zyxwvutsrqponmlkjihgfedcba", "yxe xe xe"), bcv cv cv, 'Test 43');
test(decodeMessage("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz", "abc def abc"), abc def abc, 'Test 44');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "vxp qpy o"), vxp qpy o, 'Test 45');
test(decodeMessage("jumps over the lazy dog quick brown fox", "pvuzr cgviy ojizv bxz cfiwz nqzsx vgrb"), dgbni tqgso fasng vzn tyswn xrnez gqiv, 'Test 46');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "xqf"), odn, 'Test 47');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "gfn"), znm, 'Test 48');
test(decodeMessage("pzucfelxwyabqomtjirdnsvhgk", "kwj kwi kwv wkv"), ziq zir ziw izw, 'Test 49');
test(decodeMessage("fmwtkujhpnobxigcsqrzydalve", "fyh fyt fyv yfj"), auh aud auy uag, 'Test 50');
test(decodeMessage("abcdefghij klmnopqrstuvwxyz", "qzcfj nx ud qzcfj"), qzcfj nx ud qzcfj, 'Test 51');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "yjx x"), xpo o, 'Test 52');
test(decodeMessage("jumps over lazy dogs quick brown fox the this", "yjiwxtw vqzj spwq ovbxc yoz qjxv"), maquxyu gpla edup fgtxr mfl paxg, 'Test 53');
test(decodeMessage("jklmnopqrstuvwxyzabcdefghi", "frg fmh gfn"), wix wdy xwe, 'Test 54');
test(decodeMessage("if the army of pharaoh had followed them closely the lord would have swept them away", "tk svj fkhxjg zq xjfkfvmj xfvmtk svj gsvtqy svj ef kfvbvmb xjfv tk"), Error: 'k', 'Test 55');
test(decodeMessage("zabcdefghijklmnopqrstuvwxy", "qxy xyx yxq"), ryz yzy zyr, 'Test 56');
test(decodeMessage("the quick brown fox jumps over the lazy dog and the quick brown fox jumps over the lazy dog", "vkbs bs t suepuv"), this is a secret, 'Test 57');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "zurq zfrq zqr ku", "abcdefghijklmnopqrstuvwxyz"), Error: 'zurq zfrq zqr ku', 'Test 58');
test(decodeMessage("ekmflgdqvzntowyhxuspaibrcj", "jbs xut hig"), zws qrl pvf, 'Test 59');
test(decodeMessage("zyxwvutsrqponmlkjihgfedcba", "iyh uhy l"), rbs fsb o, 'Test 60');
test(decodeMessage("vwxymnbcdfghjklqropstuzaike", "vcp o cv vcp"), ahs r ha ahs, 'Test 61');
test(decodeMessage("ajfzldkgotmhrvwsypnqicxebu", "oxt oxi oxd xot"), iwj iwu iwf wij, 'Test 62');
test(decodeMessage("jklmnopqrstuvwxyzabcdefghi", "wfn yv yfcv"), nwe pm pwtm, 'Test 63');
test(decodeMessage("tevosjhbnyxrgqkfaumzilwpcd", "npu gpm gpy lgg"), ixr mxs mxj vmm, 'Test 64');
test(decodeMessage("mnbvcxzlkjhgfdsapoiuytrewq", "hfu q jhu"), kmt z jkt, 'Test 65');
test(decodeMessage("abcdefgijklmnopqrstuvwxyz", "hqv v yqv"), Error: 'h', 'Test 66');
test(decodeMessage("asdfghjklqwertyuiopzxcvbnm", "yqz dpy o"), ojt cso r, 'Test 67');
test(decodeMessage("qbnvgjlftscxkouwamdphzreiy", "umr urv urm pyz"), orw owd owr tzv, 'Test 68');
test(decodeMessage("qwertyuiopasdfghjklzxcvbnm", "zqj dpy o"), taq mjf i, 'Test 69');
test(decodeMessage("five boxing wizards jump quickly on this lazy dog", "qzyc yvzctv yxqjvzq yjiwxtw on qjxv yoj"), tkxu xckuyc xgtpckt xpbjgyj fh tpgc xfp, 'Test 70');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "c e"), g c, 'Test 71');
test(decodeMessage("abcdefghizjklmnopqrstuvwxy", "lii eil eil"), mii eim eim, 'Test 72');
test(decodeMessage("vxznpqjwoefkytlimrdhaguscb", "tyf iy tf"), nmk pm nk, 'Test 73');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "sw uqz"), sl edw, 'Test 74');
test(decodeMessage("jxwtrklivnpmhudsfgcayzbeoq", "kcfizgv zr ocfv"), fsqhvri ve ysqi, 'Test 75');
test(decodeMessage("lazy dogs quick brown fox jumps over the this", "vqzj spwq ovbxc yjiwxtw vqzj qjxv"), wict hvpi fwnsl dtkpsyp wict itsw, 'Test 76');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "yjx z"), xpo w, 'Test 77');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "mlml qmf lml gmgg"), mlml qmf lml gmgg, 'Test 78');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "vz"), tw, 'Test 79');
test(decodeMessage("dbrujxfgzvcotwiympnslakqhe", "kmqs ks u kqsebs"), wqxt wt d wxtzbt, 'Test 80');
test(decodeMessage("lazy dogs jump quickly on the brown fox and", "vqzj spwq yjiwxtw ovbxc yoj qjxv yoz"), Error: 'v', 'Test 81');
test(decodeMessage("the quick brown fox jumps over the lazy dog", "wqiv xi sqin sqin"), ldft of sdfm sdfm, 'Test 82');
test(decodeMessage("dtjgsvyzxpkbfqwulcmohraeni", "obr obn oti atn"), tlv tly tbz wby, 'Test 83');
test(decodeMessage("abcdefghijk lmnopqrstuvwxyz", "svil km ybgu bg ujr krkhi yjr cvvux"), svil km ybgu bg ujr krkhi yjr cvvux, 'Test 84');
test(decodeMessage("the quick brown fox jumps over lazy dogs", "mht zrs xqf ovkqvoq ngyu kgxqj bpxc"), qba wjs odn kthdtkd mzxe hzodp irog, 'Test 85');
test(decodeMessage("qwertyuiopasdfghjklzxcvbnm", "jyq zq o"), qfa ta i, 'Test 86');
test(decodeMessage("gibrfqotdhewakjyzlxmvncpus", "yxh lo loxhy"), psj rg rgsjp, 'Test 87');
test(decodeMessage("mnopqrstuvwxyzabcdefghijkl", "aov eovm eovm"), ocj scja scja, 'Test 88');
test(decodeMessage("zxvtrqponmlkjihgfedcbazyw", "ajc eajc eajc"), vmt rvmt rvmt, 'Test 89');
test(decodeMessage("rhythms can be very exciting and mysterious", "kvgzo ozx yz ovbxc yvoqzgkxq ovgx yz xebc"), Error: 'k', 'Test 90');
test(decodeMessage("gfedcbauioplkjhzyxwvtsrqmn", "ixv yxv oxv"), irt qrt jrt, 'Test 91');
test(decodeMessage("xyzabcdefghijklmnopqrstuvw", "wvf v fv"), zyi y iy, 'Test 92');
test(decodeMessage("abc def ghijk lmnop qrst uvwxyz", "nvmjy nbsytw"), nvmjy nbsytw, 'Test 93');
test(decodeMessage("eljuxhpwnyrdgtqkviszcfmabo", "ihd hsih xihw gh hsi"), rfl fsrf erfh mf fsr, 'Test 94');
test(decodeMessage("nopqrstuvwxyzabcdefghijklm", "zqv qv q"), mdi di d, 'Test 95');
test(decodeMessage("the quick brown fox jumps over the lazy dog", "qytz nwt zwt"), dxaw mla wla, 'Test 96');
test(decodeMessage("quick brown fox jumps over the lazy dog and the quick brown fox jumps", "vxw aov g pufa ohq"), qli vhq z obkv hta, 'Test 97');
test(decodeMessage("vbnmxczasdfghjklpoiuytrewq", "vkbs bs t suepuv"), aobi bi v itxqta, 'Test 98');
test(decodeMessage("zyxwvutsrqponmlkjihgfedcba", "yvc zc yz"), bex ax ba, 'Test 99');
test(decodeMessage("azbycxdwevfugthrskjqplomni", "tqppf ptd je"), ntuuk ung si, 'Test 100');
test(decodeMessage("xylophone qwertyuiop asdfghjklz cvbnm", "cvmu cvxqv"), wxzm wxaix, 'Test 101');
test(decodeMessage("qwertyuiopasdfghjklzxcvbnm", "lqtfw xtg twkxq"), saenb ueo ebrua, 'Test 102');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "yjx v"), xpo t, 'Test 103');
test(decodeMessage("nmqpviwedklxzfgrctuhyjasob", "ohc oha ohu voh"), ytq ytw yts eyt, 'Test 104');
test(decodeMessage("phinxajrhqdogesbcukmfltwyz", "zvmh ecv wvmazk wv hwvm jge wh yvmazk eg"), Error: 'v', 'Test 105');
test(decodeMessage("nopqrstuvwxyzabcdefghijklm", "izk zkh bva jnfrdq"), vmx mxu oin waseqd, 'Test 106');
test(decodeMessage("quick brown fox jumps over the lazy dog", "rwjsi exmti gsrhri zv wimtix egzewy"), gimpc rlnsc zpgtgc wq icnscl rzwrix, 'Test 107');
test(decodeMessage("lazy dogs jumps over the quick brown fox the", "vqzj yjiwxtw spwq yoj spwq ovbxc yoz"), mrci diswzpw hlwr dfi hlwr fmvzt dfc, 'Test 108');
test(decodeMessage("mnopqrstuvwxyzabcdefghijkl", "mud gct gct"), air uqh uqh, 'Test 109');
test(decodeMessage("lazy dogs jumps quickly over the brown fox and", "vqzj yjiwxtw spwq yoj ovbxc yoz"), qmci dinwztw hlwm dfi fqvzo dfc, 'Test 110');
test(decodeMessage("vzhofucmlnjqbdspartexwiykg", "dpy ld o yv"), npx in d xa, 'Test 111');
test(decodeMessage("mnbvcxzlkjhgfdsapoiuytrewq", "cv lpcv"), ed hqed, 'Test 112');
test(decodeMessage("the lazy dog jumps over the quick brown fox", "qjxv yoj vqzj spwq yjiwxtw ovbxc yvoqzgkxq"), rkzp gik prfk onwr gkswzaw ipvzt gpirfjuzr, 'Test 113');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "yjx yjx"), xpo xpo, 'Test 114');
test(decodeMessage("cvzkgbxquihmpnytjrsdawolef", "cfr cfd cfl mfl"), azr azt azx lzx, 'Test 115');
test(decodeMessage("lazy dogs jumps quickly over the brown fox the", "vqzj yjiwxtw spwq yoj ovbxc yoj"), qmci dinwztw hlwm dfi fqvzo dfi, 'Test 116');
test(decodeMessage("thezyxwvutsrqponmlkjihgfedcba", "zqv eovm ztqkofv ztqkofv"), dlh cnhp dalrnvh dalrnvh, 'Test 117');
test(decodeMessage("this is a very long key that contains all letters of the alphabet", "jktt tj x xqtj ofugj cftjkgm oayzj kgxqj kfxgy jgj"), Error: 'j', 'Test 118');
test(decodeMessage("zyxwvutsrqponmlkjihgfedcba", "evh vhe yhe"), ves esv bsv, 'Test 119');
test(decodeMessage("the quick brown fox jumps over the lazy dog", "zqf ykq fqu fqo ykt nqtk"), wdn xhd nde ndk xha mdah, 'Test 120');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "hqv v yhqf"), hqv v yhqf, 'Test 121');
test(decodeMessage("ponmlkjihgfedcbazyxwvutsrq", "jxqy xtgy efn nhr"), gszr swjr lkc ciy, 'Test 122');
test(decodeMessage("the fifth of july nineteen sixty four", "wlc vihwx zq mhqy xjwvexqv ksvj yhqw"), Error: 'w', 'Test 123');
test(decodeMessage("gymbztfkwjxehalnqosrudvpci", "nqzv nq p azdvmn"), pqew pq x nevwcp, 'Test 124');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "zcf bvg jnfrdq"), zcf bvg jnfrdq, 'Test 125');
test(decodeMessage("brown fox the quick jumps over lazy dogs and", "ovbxc yoz spwq yvoqzgkxq vqzj qjxv ovgx"), ctagn xcw srdk xtckwzogk tkwp kpgt ctzg, 'Test 126');
test(decodeMessage("qpwoeirutyalskdjfhgczxmvbn", "vcp o cv ocv"), xtb d tx dtx, 'Test 127');
test(decodeMessage("ijklmnopqrstuvwxyzabcdefgh", "wqv qv q"), oin in i, 'Test 128');
test(decodeMessage("cijqxfyvolnmtzgdwsaehrkpbu", "fnw uvf uft nwg"), fkq zhf zfm kqo, 'Test 129');
test(decodeMessage("lazy dogs jump quickly over the brown fox", "jxqy xtgy efn nhr"), izmd ztgd ryx xus, 'Test 130');
test(decodeMessage("phinxqbcdgjkamlstvrewyzouf", "thx thg lv xkqhs"), qbe qbj or elfbp, 'Test 131');
test(decodeMessage("jklmnopqrstuvwxyzabcdefghi", "dru gct gct"), uil xtk xtk, 'Test 132');
test(decodeMessage("jxqtvknpsmuhbdrgzlcewfoaiy", "dgy gch dgy"), npz psl npz, 'Test 133');
test(decodeMessage("abcdefghijklnmopqrstuvwxyz", "opq qpo qpo"), opq qpo qpo, 'Test 134');
test(decodeMessage("qwertyuiopasdfghjklzxcvbnm", "gsv htk gdv jgd"), olw per omw qom, 'Test 135');
test(decodeMessage("jzkgwvqdhnmltisrfoxcabepy", "jwpwp yv owp"), aexex yf rex, 'Test 136');
test(decodeMessage("wsgczxfltkbqpndohjuaevrmiy", "vmx gpm mvg maq"), vxf cmx xvc xtl, 'Test 137');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "xol mlu w yjx"), xol mlu w yjx, 'Test 138');
test(decodeMessage("dogs quick brown fox jumps over lazy the this", "vqzj spwq ovbxc yjiwxtw vqzj qjxv"), sewp drle bsjoh xpgloyl sewp epos, 'Test 139');
test(decodeMessage("abcdefgijklmnopqrstuvwxyz", "qcp zc y"), pco yc x, 'Test 140');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "yjx y"), xpo x, 'Test 141');
test(decodeMessage("lmnopqrstuvwxyzabcdefghijk", "vqj qjv z"), kfy fyk o, 'Test 142');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "qiy oiq z"), qiy oiq z, 'Test 143');
test(decodeMessage("and the quick brown fox jumps over lazy dogs", "ovgx yoj spwq yvoqzgkxq ovbxc yjiwxtw vqzj"), nvzq ynr utog yvngxzkqg nvlqj yrioqdo vgxr, 'Test 144');
test(decodeMessage("qwertyuioplkjhgfdsazxcvbnm", "gsvjf rxpyi ldmul cqfnk hlevi gsvoz abwlt"), orwmp dujfh kqzgk vapyl nkcwh orwit sxbke, 'Test 145');
test(decodeMessage("nopqrstuvwxyzabcdefghijklm", "zqv qv z"), mdi di m, 'Test 146');
test(decodeMessage("quick brown fox jumps over lazy dogs the this", "yvoqzgkxq ovbxc yjiwxtw vqzj qjxv spwq qjxv"), vqhauxela hqfld vmcilyi qaum amlq poia amlq, 'Test 147');
test(decodeMessage("qwertyuiopasdfghjklzxcvbnm", "oxj o j"), iuq i q, 'Test 148');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "sw yjx"), sl xpo, 'Test 149');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "v zifw ilxqfs"), t wfnl fuodns, 'Test 150');
test(decodeMessage("this is a test key for decoding messages", "k xkxv v tvk dkk"), Error: 'x', 'Test 151');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "qzcf bfgs jgcd yqcf"), qzcf bfgs jgcd yqcf, 'Test 152');
test(decodeMessage("abcdefghizjklmnopqrstuvwxy", "ulc cul cul"), vmc cvm cvm, 'Test 153');
test(decodeMessage("zyxwvutsrqponmlkjihgfedcba", "tsr rst rst"), ghi ihg ihg, 'Test 154');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "qz cf"), dw gn, 'Test 155');
test(decodeMessage("qwertyuiopasdfghjklzxcvbnm", "mfir kkfr ifxk"), znhd rrnd hnur, 'Test 156');
test(decodeMessage("fnex wpviqkdmtlugybhcarzsoj", "hcv uxl"), stg odn, 'Test 157');
test(decodeMessage("to be or not to be that is the question", "uj cf qz uqv uj cf uhvi zu ctzv"), Error: 'j', 'Test 158');
test(decodeMessage("zebra quick brown fox jumps over the lazy dog", "gqjty efn nhr htyq"), zfpux bnm mvd vuxf, 'Test 159');
test(decodeMessage("gymnymphs fly by my wyrm", "hzoitpizh gza zj nz hztpi"), Error: 'z', 'Test 160');
test(decodeMessage("nopqrstuvwxyzabcdefghijklm", "vqz zqv z"), idm mdi m, 'Test 161');
test(decodeMessage("the quick brown fox jumps over the lazy dog", "vgj ov sa jhygjmt oh rjw"), tzp kt sv pbxzpqa kb jpl, 'Test 162');
test(decodeMessage("bcadefghijklmnopqrstuvwxzy", "bdc bva jnfrdq"), adb avc jnfrdq, 'Test 163');
test(decodeMessage("asdfghjklqwertyuiopzxcvbnm", "wqv qv q"), kjw jw j, 'Test 164');
test(decodeMessage("zebra tiger quick brown fox jumps over the lazy dog", "uybvf ojizv cfiwz nqzsx vgrb cgviy ojizv bxz"), jycvp mrgav kpgna oiauq vhdc khvgy mrgav cqa, 'Test 165');
test(decodeMessage("the quick brown fox jumps over the lazy dog", "dkv v yvk"), yht t xth, 'Test 166');
test(decodeMessage("nopqrstuvwxyzabcdefghijklm", "zqv qv zc"), mdi di mp, 'Test 167');
test(decodeMessage("the brown fox jumps quickly over a lazy dog", "pjoj qvw xqt jqtqi yjiwxtw spwq jx gsvk yoj"), nkfk pvg jpa kpapq ukqgjag ongp kj zovs ufk, 'Test 168');
test(decodeMessage("this quick brown fox jumps over lazy dogs", "qjxv yvoqzgkxq ovbxc yjiwxtw spwq yoj vqzj"), epos xskewzhoe ksiog xpcloal drle xkp sewp, 'Test 169');
test(decodeMessage("jklmnopqrstuvwxyzabcdefghi", "sgtw xjxw xjxw"), jxkn oaon oaon, 'Test 170');
test(decodeMessage("a bc df egh ijkl mno pq rs tuvwxyz", "v lqyq w lwv yjx"), v lqyq w lwv yjx, 'Test 171');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "qzcfb qmgox ypgmt gsv fiu"), qzcfb qmgox ypgmt gsv fiu, 'Test 172');
test(decodeMessage("pqrkxlcdemosvahzwfygtnujib", "izv zfc yfcv"), ypm prg srgm, 'Test 173');
test(decodeMessage("lazy dogs jump over quick brown fox the", "bxz bpxc wxqgc ebcjg fcivw zqzsx ojizv"), txc tlxr uxpgr ntrig wrqmu cpchx fiqcm, 'Test 174');
test(decodeMessage("okyftdazhsxngijwumrcvqlpeb", "kqv mhg a lv vjx"), bvu rim g wu uok, 'Test 175');
test(decodeMessage("the brown fox jumps quickly over a lazy dog", "mht zrs xqf ovkqvoq ngyu a qzfe nax"), mba xeo jpi fvspvfp hzul w pxic hwj, 'Test 176');
test(decodeMessage("over lazy dogs quick brown fox jumps the this", "spwq vqzj spwq ovbxc yjiwxtw qjxv qjxv"), kxrl blgv kxrl abquo hvnruyr lvub lvub, 'Test 177');
test(decodeMessage("the brown quick fox jumps over lazy dogs", "zqft gqf vxt xec ohq oizd"), wina zin toa ocl fbi fkwy, 'Test 178');
test(decodeMessage("this is a very long key that contains all the letters of the alphabet", "slqv lv j uphb xqvo jxu qvojwv njo lvjwvq"), Error: 'q', 'Test 179');
test(decodeMessage("jump quickly on this lazy dog and the brown fox", "yjiwxtw on qjxv yoj qzyc yvzctv yxqjvzq ovgx yz"), Error: 'v', 'Test 180');
test(decodeMessage("jumped over the lazy brown fox quick", "ujxqyc efn nhr htyq"), batuow esr rki kjou, 'Test 181');
test(decodeMessage("fghijklmnopqrstuvwxyzabcde", "vrc vja vrc vja"), qmx qev qmx qev, 'Test 182');
test(decodeMessage("the quick brown fox jumps over lazy dogs and", "spwq yvoqzgkxq ovbxc yjiwxtw vqzj ovgx"), srld xtkdwzhod ktiog xpfloal tdwp ktzo, 'Test 183');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "qjvux xfgf q px"), dpteo onzn d ro, 'Test 184');
test(decodeMessage("the quick brown fox jumps over the lazy dog", "dkv v ydv"), yht t xyt, 'Test 185');
test(decodeMessage("xlsnmveizhptfjugobcdkqrway", "wcr vcv wcv xwv"), xsw fsf xsf axf, 'Test 186');
test(decodeMessage("quick brown fox jumps over lazy dog the", "fxfsr jxqfk wtf pvuzr bcgy jxqfk dvo"), klkpg mlake iyk oqbug fdxv mlake wqh, 'Test 187');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "yjx w"), xpo l, 'Test 188');
test(decodeMessage("bdfhjlnprtvxzcgikmoqsuwyae", "hc vjg cji cgy"), dn keo nep nox, 'Test 189');
test(decodeMessage("junta de los trabalhadores brasileiros", "hsvyz ys bse ksbvsvkzr yzctyvbs"), Error: 'v', 'Test 190');
test(decodeMessage("onmlkjihgfedcbazyxwvutsrqp", "ixkz znxoz kx yq"), grep pbrap er qy, 'Test 191');
test(decodeMessage("phqgiumeaylnofdxjkrcvstzwb", "ixw ikg ikg ikg"), epy erd erd erd, 'Test 192');
test(decodeMessage("the world is a stage and all the men and women merely players", "qef egvms gq xq e cqwmg ndeqq eeq egvms xq egvms bqqrfqv"), Error: 'q', 'Test 193');
test(decodeMessage("five boxing wizards jump quickly on this lazy dog", "wfkq xqfnk uveogvj pvuzr cfiwz rjgt jxqfk bxz"), javt gtahv qcdficp scqkm uabjk mpiy pgtav egk, 'Test 194');
test(decodeMessage("qwertyuiopasdfghjklzxcvbnm", "vqj qjv cv"), waq aqw vw, 'Test 195');
test(decodeMessage("abcdefghjklmnopqrstuvwxyzti", "ghw gct gct"), ghv gcs gcs, 'Test 196');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "fnbv wvxm"), nmit ltoq, 'Test 197');
test(decodeMessage("the quick brown fox jumps over the lazy dogs", "yjx"), xpo, 'Test 198');
test(decodeMessage("mnbvcxzlkjhgfdsapoiuytrewq", "qnb wql fhw fql"), zbc yzh mky mzh, 'Test 199');
test(decodeMessage("abcdefgilmhjnopkrstuvwxyz", "qcp zc y"), Error: 'q', 'Test 200');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz", "anxanq azoz anu"), anxanq azoz anu, 'Test 201');
test(decodeMessage("thequickbrownfoxjumpsoverthelazydogs", "qjvux xfgf q px"), dpteo onzn d ro, 'Test 202');
test(decodeMessage("abcdefghjklmnopqrstuvwxyzti", "jkq xjxw xjxw"), ijp wiwv wiwv, 'Test 203');
test(decodeMessage("bujgtfayrxohqzplmwdinckevs", "yzq d pyq o"), hnm s ohm k, 'Test 204');
test(decodeMessage("rjkylmfdqogavwunhixpctzesb", "tzm tmz tmh tmi"), vwf vfw vfq vfr, 'Test 205');
test(decodeMessage("the quick brown fox jumps over lazy dogs this", "spwq yvoqzgkxq ovbxc yjiwxtw vqzj qjxv"), srld xtkdwzhod ktiog xpfloal tdwp dpot, 'Test 206');
test(decodeMessage("brown fox jumps over lazy dogs the quick this", "ovbxc yjiwxtw vqzj qjxv spwq yvoqzgkxq"), cmagy rhxdgud mwqh whgm lkdw rmcwqtzgw, 'Test 207');
test(decodeMessage("a b c d e f g h i j k l m n o p q r s t u v w x y z", "z k u o c g t w"), z k u o c g t w, 'Test 208');
test(decodeMessage("zyxwvutsrqponmlkjihgfedcba", "gtgt nvo gtg mpgg"), tgtg mel tgt nktt, 'Test 209');
test(decodeMessage("ijklmnopqrstuvwxyzabcdefgh", "wqv qv qv"), oin in in, 'Test 210');
test(decodeMessage("mjw qzlnf hw uo kcf jehrv dpo osxgt cyqak", "jnjfdh frl df"), bgbhqi hof qh, 'Test 211');
test(decodeMessage("abcdefghizjklmnopqrstuvwxy", "vuvw xw yx za"), wvwx yx zy ja, 'Test 212');
test(decodeMessage("abcdefghijklnmopqrstuvwxyz", "ehu zcv i"), ehu zcv i, 'Test 213');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "ehu zcv i"), ehu zcv i, 'Test 214');
test(decodeMessage("wvutsrqponmlkjihgfedcba zyx", "zyxwvutsrqpnmolkjihgfedcba"), xyzabcdefghjkilmnopqrstuvw, 'Test 215');
test(decodeMessage("mnbvcxzlkjhgfdsapoiuytrewq", "vcp o cv v"), deq r ed d, 'Test 216');
test(decodeMessage("qwertyuiopasdfghjklzxcvbnm", "jyq zq j"), qfa ta q, 'Test 217');
test(decodeMessage("the brown fox jumps over the lazy dog quickly", "tqpp d dswcp gygij"), awnn u uogyn vtvxk, 'Test 218');
test(decodeMessage("g fmbycy fea rzvs vujx wptfk", "ceq gcf zvzfc kcz"), Error: 'q', 'Test 219');
test(decodeMessage("edcba ponmlkj ihgfedcba ponmlkj", "xgv jgv xgv jgv"), Error: 'x', 'Test 220');
test(decodeMessage("zyxwvutsrqponmlkjihgfedcba", "ixq kivk eiqb"), rcj prep vrjy, 'Test 221');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "wklv lv dq xvh hqw phvvdjh"), wklv lv dq xvh hqw phvvdjh, 'Test 222');
test(decodeMessage("nopqrstuvwxyzabcdefghijklm", "zcf jopcnboe wj jop"), mps wbcpaobr jw wbc, 'Test 223');
test(decodeMessage("xyzabcdefghijklmnopqrstuvw", "xpu xh z"), asx ak c, 'Test 224');
test(decodeMessage("quick brown fox jumps over the lazy dog", "kxvzn hqomj jxq zpsvx wbvs hq tkgx"), elqwj tahnm mla wopql ifqp ta sezl, 'Test 225');
test(decodeMessage("abcdefghijklmnopqrstuvwxyz", "ehu zcv z"), ehu zcv z, 'Test 226');
test(decodeMessage("this quick brown fox jumps over lazy dogs and", "qjxv spwq yvoqzgkxq ovbxc yjiwxtw vqzj ovgx"), epos drle xskewzhoe ksiog xpcloal sewp kszo, 'Test 227');
test(decodeMessage("abcdef ghijklmnopqrstuvwxyz", "zcf bvg jnfrdq"), zcf bvg jnfrdq, 'Test 228');
test(decodeMessage("four score and seven years ago our fathers brought forth on this continent a new nation", "svza iadzq cmz azggk ujifq zqv zmj qjgrjcz jsvvz zr svza sgvcczvqf azj xyv"), Error: 'z', 'Test 229');
test(decodeMessage("abcdefghijklnmopqrstuvwxyz", "qzdv lqaf qv yzxq"), qzdv lqaf qv yzxq, 'Test 230');
test(decodeMessage("abcdefghikjlmnopqrstuvwxyz", "hij iji iij"), hik iki iik, 'Test 231');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

