// Test: 3014. Minimum Number Of Pushes To Type Word I
// 202 test cases from LeetCodeDataset
// Run: node test.js

const { minimumPushes } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n3014. Minimum Number Of Pushes To Type Word I\n");

test(minimumPushes("ghijkl"), 6, 'Test 1');
test(minimumPushes("npqrstvwxy"), 12, 'Test 2');
test(minimumPushes("abcdefghi"), 10, 'Test 3');
test(minimumPushes("vwxyz"), 5, 'Test 4');
test(minimumPushes("abcdefghijklmnopq"), 27, 'Test 5');
test(minimumPushes("abcdefghijklmnopqrs"), 33, 'Test 6');
test(minimumPushes("abcdefghijklmnopqrstu"), 39, 'Test 7');
test(minimumPushes("pqrstu"), 6, 'Test 8');
test(minimumPushes("abcdefghijkl"), 16, 'Test 9');
test(minimumPushes("abcdefghijk"), 14, 'Test 10');
test(minimumPushes("pqrstuvw"), 8, 'Test 11');
test(minimumPushes("defghi"), 6, 'Test 12');
test(minimumPushes("abcdefghijklm"), 18, 'Test 13');
test(minimumPushes("efghijkl"), 8, 'Test 14');
test(minimumPushes("abcdef"), 6, 'Test 15');
test(minimumPushes("abcdefghijklmn"), 20, 'Test 16');
test(minimumPushes("qrstuvw"), 7, 'Test 17');
test(minimumPushes("uvwxyza"), 7, 'Test 18');
test(minimumPushes("bcdefg"), 6, 'Test 19');
test(minimumPushes("tuvwxy"), 6, 'Test 20');
test(minimumPushes("qrstuv"), 6, 'Test 21');
test(minimumPushes("tuvwxyz"), 7, 'Test 22');
test(minimumPushes("wxyzabc"), 7, 'Test 23');
test(minimumPushes("abcdefghij"), 12, 'Test 24');
test(minimumPushes("nopqrs"), 6, 'Test 25');
test(minimumPushes("nopqrst"), 7, 'Test 26');
test(minimumPushes("xycdefghij"), 12, 'Test 27');
test(minimumPushes("hijklmno"), 8, 'Test 28');
test(minimumPushes("mnopqrstu"), 10, 'Test 29');
test(minimumPushes("vwxyza"), 6, 'Test 30');
test(minimumPushes("abcdefghijklmnopqr"), 30, 'Test 31');
test(minimumPushes("abcdefghijkmnopqrstuvwxyzabc"), 64, 'Test 32');
test(minimumPushes("rstvwxy"), 7, 'Test 33');
test(minimumPushes("zabcdef"), 7, 'Test 34');
test(minimumPushes("abcdefghijklmnop"), 24, 'Test 35');
test(minimumPushes("klmnopq"), 7, 'Test 36');
test(minimumPushes("stuvwx"), 6, 'Test 37');
test(minimumPushes("mnop"), 4, 'Test 38');
test(minimumPushes("xyz"), 3, 'Test 39');
test(minimumPushes("qrstuvwx"), 8, 'Test 40');
test(minimumPushes("abcdefghijlkmnopqrstuvwxyz"), 56, 'Test 41');
test(minimumPushes("yz"), 2, 'Test 42');
test(minimumPushes("lmnopqrs"), 8, 'Test 43');
test(minimumPushes("ab"), 2, 'Test 44');
test(minimumPushes("abcde"), 5, 'Test 45');
test(minimumPushes("abcd"), 4, 'Test 46');
test(minimumPushes("abcdefg"), 7, 'Test 47');
test(minimumPushes("a"), 1, 'Test 48');
test(minimumPushes("ijklmn"), 6, 'Test 49');
test(minimumPushes("klmnop"), 6, 'Test 50');
test(minimumPushes("mnopqr"), 6, 'Test 51');
test(minimumPushes("ghijklm"), 7, 'Test 52');
test(minimumPushes("ijklmnop"), 8, 'Test 53');
test(minimumPushes("zabcde"), 6, 'Test 54');
test(minimumPushes("abcdefghijklmnopqrst"), 36, 'Test 55');
test(minimumPushes("abc"), 3, 'Test 56');
test(minimumPushes("opqrstuv"), 8, 'Test 57');
test(minimumPushes("hijklm"), 6, 'Test 58');
test(minimumPushes("abcdefghijklmnopqrstuv"), 42, 'Test 59');
test(minimumPushes("abcdefghijkmnopqrstuvwx"), 45, 'Test 60');
test(minimumPushes("defghij"), 7, 'Test 61');
test(minimumPushes("efghij"), 6, 'Test 62');
test(minimumPushes("abcdefghijklmnopqrstuvwxyz"), 56, 'Test 63');
test(minimumPushes("mnopqrstuvwxyz"), 20, 'Test 64');
test(minimumPushes("yzabcdef"), 8, 'Test 65');
test(minimumPushes("defghijkl"), 10, 'Test 66');
test(minimumPushes("jklmno"), 6, 'Test 67');
test(minimumPushes("abcdefgh"), 8, 'Test 68');
test(minimumPushes("bcdfghjkl"), 10, 'Test 69');
test(minimumPushes("bcdefghijklmnopqrstuvwxyzafe"), 64, 'Test 70');
test(minimumPushes("abcdefghijklmnopqrstuvwx"), 48, 'Test 71');
test(minimumPushes("nopqrstuvwxyz"), 18, 'Test 72');
test(minimumPushes("stuvwxyzabcdefghij"), 30, 'Test 73');
test(minimumPushes("wxyzabcdefghijklmnopqrstuv"), 56, 'Test 74');
test(minimumPushes("xyzmnopqrstuabc"), 22, 'Test 75');
test(minimumPushes("stuvwxyzabcdefghijkl"), 36, 'Test 76');
test(minimumPushes("qrstuvwxyzabcdefghij"), 36, 'Test 77');
test(minimumPushes("nopqrstuvwxyzabcdefghijk"), 48, 'Test 78');
test(minimumPushes("lmnopqrstuvwxyzabc"), 30, 'Test 79');
test(minimumPushes("opqrstuvwxyzabcde"), 27, 'Test 80');
test(minimumPushes("uvwxyzabcdefghijklmnopqrstuvwxy"), 76, 'Test 81');
test(minimumPushes("lmnopqrstuvwxyzabcdefghijk"), 56, 'Test 82');
test(minimumPushes("zxcvbnmlkjhgfedcba"), 30, 'Test 83');
test(minimumPushes("xyzabcdefghijklmnop"), 33, 'Test 84');
test(minimumPushes("qrstuvwxyzzzzz"), 20, 'Test 85');
test(minimumPushes("abcdefghijlmnopqrstuvwxyz"), 52, 'Test 86');
test(minimumPushes("jklmnopqrstuvwx"), 22, 'Test 87');
test(minimumPushes("klmnopqrstuvwxyzabcdefghij"), 56, 'Test 88');
test(minimumPushes("zxcvbnmlkjhgfdsapoiuytrewq"), 56, 'Test 89');
test(minimumPushes("nopqrstuvwxyzabcdefghijklmno"), 64, 'Test 90');
test(minimumPushes("opqrstuvwxyzabcdefghijklmnop"), 64, 'Test 91');
test(minimumPushes("nopqrstuvwxyzabcdefghijklm"), 56, 'Test 92');
test(minimumPushes("pqrstuvwxy"), 12, 'Test 93');
test(minimumPushes("efghijklmnop"), 16, 'Test 94');
test(minimumPushes("yzabcdefghijklmnopqrstuvwx"), 56, 'Test 95');
test(minimumPushes("tuvxyzabcdefghijklmnopqrs"), 52, 'Test 96');
test(minimumPushes("mnopqrstuvwxzyabc"), 27, 'Test 97');
test(minimumPushes("lmnopqrstu"), 12, 'Test 98');
test(minimumPushes("bdfhjlnprtvxz"), 18, 'Test 99');
test(minimumPushes("mnopqrstuvwxyzabc"), 27, 'Test 100');
test(minimumPushes("mnopqrst"), 8, 'Test 101');
test(minimumPushes("mnopqrstuvwxzy"), 20, 'Test 102');
test(minimumPushes("abcdpqrs"), 8, 'Test 103');
test(minimumPushes("abcdefghijklmnopqrstuvwxzy"), 56, 'Test 104');
test(minimumPushes("aeiouaeiou"), 12, 'Test 105');
test(minimumPushes("xyzabcdefghijklmnopqrstuvwx"), 60, 'Test 106');
test(minimumPushes("abcdefgxyz"), 12, 'Test 107');
test(minimumPushes("defghijklmnopqrstuvwxyzabc"), 56, 'Test 108');
test(minimumPushes("klmnopqrstuabcdefghij"), 39, 'Test 109');
test(minimumPushes("abcdefghijkmnop"), 22, 'Test 110');
test(minimumPushes("abcdefgxyzijklmnop"), 30, 'Test 111');
test(minimumPushes("stuvxyzabcdefghijklmnopqr"), 52, 'Test 112');
test(minimumPushes("ghijklmnopqrstuvwxyzabcde"), 52, 'Test 113');
test(minimumPushes("zyxcvbnm"), 8, 'Test 114');
test(minimumPushes("nopqrstuvwxyzabcdefghijkl"), 52, 'Test 115');
test(minimumPushes("abcdefghjklmno"), 20, 'Test 116');
test(minimumPushes("hijklmnopqrstuvwxyz"), 33, 'Test 117');
test(minimumPushes("vwxyzabcd"), 10, 'Test 118');
test(minimumPushes("pqrstuvwlmnoefghij"), 30, 'Test 119');
test(minimumPushes("yzabcdefghijklmnopqrstuvwxy"), 60, 'Test 120');
test(minimumPushes("zabcdefghijklmnopq"), 30, 'Test 121');
test(minimumPushes("defghijklmnopqrstuvwxyza"), 48, 'Test 122');
test(minimumPushes("opqrstuvwxyzabcdefghijklmn"), 56, 'Test 123');
test(minimumPushes("mnopqrstuvwxyzabcdefghijxyz"), 60, 'Test 124');
test(minimumPushes("mnopqrstuvwxyzaefghijkl"), 45, 'Test 125');
test(minimumPushes("wxyzabcdefghijklmnopqrstuvwxy"), 68, 'Test 126');
test(minimumPushes("abcdefghijmnopqrstuvwxyz"), 48, 'Test 127');
test(minimumPushes("bcdefghijklmnopqrstuvwxyza"), 56, 'Test 128');
test(minimumPushes("xyzabc"), 6, 'Test 129');
test(minimumPushes("poiuytrewq"), 12, 'Test 130');
test(minimumPushes("bcdfghjklmnpqrstvwxyz"), 39, 'Test 131');
test(minimumPushes("qwertyuiop"), 12, 'Test 132');
test(minimumPushes("abcdefhijklmno"), 20, 'Test 133');
test(minimumPushes("qrstuvwxyz"), 12, 'Test 134');
test(minimumPushes("uvwxyzaeiou"), 14, 'Test 135');
test(minimumPushes("abcdefghilmnopqrstuvwxyz"), 48, 'Test 136');
test(minimumPushes("abcdefghijxyzklmnopqr"), 39, 'Test 137');
test(minimumPushes("xyzdefghijklmnopqrstuvw"), 45, 'Test 138');
test(minimumPushes("abcdefghijkmnopqrst"), 33, 'Test 139');
test(minimumPushes("wxyzabcdefghijklmnopqrst"), 48, 'Test 140');
test(minimumPushes("tuvwxyzabcdefghijklmnopqrs"), 56, 'Test 141');
test(minimumPushes("qrstuvwxyzabcdefghijklmnop"), 56, 'Test 142');
test(minimumPushes("ghijklmnopqrstuvwxyzab"), 42, 'Test 143');
test(minimumPushes("nopqrstuvwxyzabc"), 24, 'Test 144');
test(minimumPushes("abcdefghiklmnopqrstuvwxyz"), 52, 'Test 145');
test(minimumPushes("yzabcd"), 6, 'Test 146');
test(minimumPushes("ghijklmnopqrstu"), 22, 'Test 147');
test(minimumPushes("vwxyzabcdefghijklmnopqrstu"), 56, 'Test 148');
test(minimumPushes("vwxyzabcdefghijklmnopq"), 42, 'Test 149');
test(minimumPushes("zabcdefghijklmnop"), 27, 'Test 150');
test(minimumPushes("ijklmnopqrstuvwxyzabcdefgh"), 56, 'Test 151');
test(minimumPushes("lkjihgfedcba"), 16, 'Test 152');
test(minimumPushes("klmno"), 5, 'Test 153');
test(minimumPushes("pqrstuvwxyzabcdefghijklmno"), 56, 'Test 154');
test(minimumPushes("stuvwxyzabcdefghijklmnopqr"), 56, 'Test 155');
test(minimumPushes("abcdefg hijklmnop qrstuv wxyz"), 68, 'Test 156');
test(minimumPushes("lmnopqrstuvwxyz"), 22, 'Test 157');
test(minimumPushes("rstuvxyzabcdefghijklmnopqrst"), 64, 'Test 158');
test(minimumPushes("qrstuvwxyza"), 14, 'Test 159');
test(minimumPushes("abcdefghilmnopqr"), 24, 'Test 160');
test(minimumPushes("yzabcdefghijklmnopqrstuvw"), 52, 'Test 161');
test(minimumPushes("xyzabcdefghijklmnopq"), 36, 'Test 162');
test(minimumPushes("bcdefghijklmnopqrstuvwx"), 45, 'Test 163');
test(minimumPushes("abcdefghijklmnopqrstuvmnop"), 56, 'Test 164');
test(minimumPushes("zxcvbnm"), 7, 'Test 165');
test(minimumPushes("xyzabcdefghijklmnopqrstuvw"), 56, 'Test 166');
test(minimumPushes("qrstuvwxyzabcdefg"), 27, 'Test 167');
test(minimumPushes("abcdefghijkmnopqrstuvwxy"), 48, 'Test 168');
test(minimumPushes("abcdefghilmnopqrstuvwxyzz"), 52, 'Test 169');
test(minimumPushes("defghijklmnopqrstu"), 30, 'Test 170');
test(minimumPushes("vwxyzabcdefghijklmno"), 36, 'Test 171');
test(minimumPushes("vwxyzabcdefghijklmnopqrstuvwx"), 68, 'Test 172');
test(minimumPushes("zxcvbnmasdfghjklqwertyuiop"), 56, 'Test 173');
test(minimumPushes("mnopqrstuv"), 12, 'Test 174');
test(minimumPushes("zabcdefghijklmnopqrstuvwxy"), 56, 'Test 175');
test(minimumPushes("defghijklmnopqrstuabcdefgh"), 56, 'Test 176');
test(minimumPushes("asdfghjkl"), 10, 'Test 177');
test(minimumPushes("abcdefghijklmno"), 22, 'Test 178');
test(minimumPushes("ghijklmnopqrstuvwxyzabcdef"), 56, 'Test 179');
test(minimumPushes("yzabcdefghijklmnop"), 30, 'Test 180');
test(minimumPushes("qrstuvwxyzabcdefghijklmnoprstuvw"), 80, 'Test 181');
test(minimumPushes("rstuvwxyzabcdefghijklmnopq"), 56, 'Test 182');
test(minimumPushes("zabcdefghijklmnopqrstuvwx"), 52, 'Test 183');
test(minimumPushes("nopqrstuvwxyzabcd"), 27, 'Test 184');
test(minimumPushes("bcdefghijkl"), 14, 'Test 185');
test(minimumPushes("nopqrstuvwxyzabcde"), 30, 'Test 186');
test(minimumPushes("abcdefhijklmnopqrstuvwxyz"), 52, 'Test 187');
test(minimumPushes("abcdefghijkmnopqrstuv"), 39, 'Test 188');
test(minimumPushes("tuvwx"), 5, 'Test 189');
test(minimumPushes("pqrstuvwxyzabcdef"), 27, 'Test 190');
test(minimumPushes("jklmnopqrst"), 14, 'Test 191');
test(minimumPushes("bcdefghijklmnopqrstvwxyz"), 48, 'Test 192');
test(minimumPushes("lkjhgfdsa"), 10, 'Test 193');
test(minimumPushes("pqrstuvwxyzabc"), 20, 'Test 194');
test(minimumPushes("jklmnopqr"), 10, 'Test 195');
test(minimumPushes("uvwxyzabcdefghijklmnopqrst"), 56, 'Test 196');
test(minimumPushes("qrstuvwlmnop"), 16, 'Test 197');
test(minimumPushes("acdegikmoqsuwy"), 20, 'Test 198');
test(minimumPushes("pqrstuvwxyza"), 16, 'Test 199');
test(minimumPushes("qrstuabcdefghijk"), 24, 'Test 200');
test(minimumPushes("mnopqrstuvwx"), 16, 'Test 201');
test(minimumPushes("hgfedcba"), 8, 'Test 202');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

