// Test: 678. Valid Parenthesis String
// 183 test cases from LeetCodeDataset
// Run: node test.js

const { checkValidString } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n678. Valid Parenthesis String\n");

test(checkValidString("[[]]*"), true, 'Test 1');
test(checkValidString("[[[[[[**]]]]]]"), true, 'Test 2');
test(checkValidString("[[]*"), true, 'Test 3');
test(checkValidString("****"), true, 'Test 4');
test(checkValidString("[[]****]"), true, 'Test 5');
test(checkValidString("*[]"), true, 'Test 6');
test(checkValidString("[[]***]"), true, 'Test 7');
test(checkValidString("[[*]*[]]"), true, 'Test 8');
test(checkValidString("[]][*"), false, 'Test 9');
test(checkValidString("[[*]]"), true, 'Test 10');
test(checkValidString("[*]*"), true, 'Test 11');
test(checkValidString("[[]]]"), false, 'Test 12');
test(checkValidString("[[][[]]]"), true, 'Test 13');
test(checkValidString("[*]]"), true, 'Test 14');
test(checkValidString("[**]"), true, 'Test 15');
test(checkValidString("[*][]"), true, 'Test 16');
test(checkValidString("[]"), true, 'Test 17');
test(checkValidString("[[[]]]"), true, 'Test 18');
test(checkValidString("[*]"), true, 'Test 19');
test(checkValidString("[[*]"), true, 'Test 20');
test(checkValidString("[][]"), true, 'Test 21');
test(checkValidString("[[]*[]]"), true, 'Test 22');
test(checkValidString("[[]]]]"), false, 'Test 23');
test(checkValidString("[***]"), true, 'Test 24');
test(checkValidString("[[]*[]*[*]*[]]"), true, 'Test 25');
test(checkValidString("[[]]*[[]]*"), true, 'Test 26');
test(checkValidString("[[**]]*[[*]]*[**]"), true, 'Test 27');
test(checkValidString("[[[[[[[]]]]]]]***"), true, 'Test 28');
test(checkValidString("[[[[]]]]*[[]]"), true, 'Test 29');
test(checkValidString("[*[[]*[[]]*]]"), true, 'Test 30');
test(checkValidString("[]***[[]][]"), true, 'Test 31');
test(checkValidString("[[**[*]]]"), true, 'Test 32');
test(checkValidString("[*]*[*][*]*[*][*]"), true, 'Test 33');
test(checkValidString("[[[[[]]]]]]]**[[][[[]]]"), false, 'Test 34');
test(checkValidString("[[][[][[][*]]]]]"), true, 'Test 35');
test(checkValidString("[*[[[[**]]]]]"), true, 'Test 36');
test(checkValidString("[[[[**]]]]*[[[**]]]]"), true, 'Test 37');
test(checkValidString("[*[*[*[*[*[*[*]]]]]****]"), true, 'Test 38');
test(checkValidString("[[[[[[]]]]]]"), true, 'Test 39');
test(checkValidString("[[[[[[[*]]]]]]"), true, 'Test 40');
test(checkValidString("[[*]*[[]]]"), true, 'Test 41');
test(checkValidString("[**[[]][*]]"), true, 'Test 42');
test(checkValidString("[[]**[**]]"), true, 'Test 43');
test(checkValidString("[[[]][[**]]]"), true, 'Test 44');
test(checkValidString("[[*]*][[**]]"), true, 'Test 45');
test(checkValidString("[*[*[***]]*]]*"), true, 'Test 46');
test(checkValidString("[[]*[[*]]]"), true, 'Test 47');
test(checkValidString("[[*]*[*[*]]]"), true, 'Test 48');
test(checkValidString("[]**[[[[]]]]****"), true, 'Test 49');
test(checkValidString("[*]**[**]"), true, 'Test 50');
test(checkValidString("[[*[**]]]*[**]"), true, 'Test 51');
test(checkValidString("[[*[**]]*]*[]"), true, 'Test 52');
test(checkValidString("[[[]]]*[[]**]**"), true, 'Test 53');
test(checkValidString("[**[[[[[[[]]]]]]]**"]), Error: Solution.checkValidString[] missing 1 required positional argument: 's', 'Test 54');
test(checkValidString("[[]]*[[]]*[[]]*[[[]]]"), true, 'Test 55');
test(checkValidString("[*[*]]**"), true, 'Test 56');
test(checkValidString("[**[**]]"), true, 'Test 57');
test(checkValidString("[[**]]"), true, 'Test 58');
test(checkValidString("[[]*[]]*[]"), true, 'Test 59');
test(checkValidString("[[*][][**]]"), true, 'Test 60');
test(checkValidString("[**[[*]*]]**"), true, 'Test 61');
test(checkValidString("[[]***[[]]*]"), true, 'Test 62');
test(checkValidString("[[*][*[*]]]"), true, 'Test 63');
test(checkValidString("[[[[]]]]*****"), true, 'Test 64');
test(checkValidString("[[*][*]][[]][[**]]"), true, 'Test 65');
test(checkValidString("[[*][*][*][*]]"), true, 'Test 66');
test(checkValidString("*[[[******]]]*"), true, 'Test 67');
test(checkValidString("[[**]*]]"), true, 'Test 68');
test(checkValidString("[][[][[][*]]]"), true, 'Test 69');
test(checkValidString("[*]*[[[**]]*]]"), true, 'Test 70');
test(checkValidString("[*[**]]*[[*]*]"), true, 'Test 71');
test(checkValidString("[][[][]]*"), true, 'Test 72');
test(checkValidString("[*[[]*[[]*]]]"), true, 'Test 73');
test(checkValidString("[[]*[[]*[[]]]]"), true, 'Test 74');
test(checkValidString("*[*[*[*]]]**"), true, 'Test 75');
test(checkValidString("[[]]*[][[]]*[]"), true, 'Test 76');
test(checkValidString("[[[[****]]]]"), true, 'Test 77');
test(checkValidString("[[[[[]]*]*]]**"), true, 'Test 78');
test(checkValidString("[[[[[[[]]]]]]]"), true, 'Test 79');
test(checkValidString("[[[[[**]]]]]"), true, 'Test 80');
test(checkValidString("[[]*[[[]]]]"), true, 'Test 81');
test(checkValidString("[[][[]]]**"), true, 'Test 82');
test(checkValidString("[[[[]**]]][[[[]**]]]"), true, 'Test 83');
test(checkValidString("[[[[]*****]****]]"), true, 'Test 84');
test(checkValidString("[**]]][**["), false, 'Test 85');
test(checkValidString("[[]][[]][[**]]"), true, 'Test 86');
test(checkValidString("[*[*[*[*[*]]]]]"), true, 'Test 87');
test(checkValidString("[[[[*]][]]*[]]"), true, 'Test 88');
test(checkValidString("[*[*[*]*]]"), true, 'Test 89');
test(checkValidString("[[[*]]][[***]]"), true, 'Test 90');
test(checkValidString("*[[]*[[]]*[[]]**]"), true, 'Test 91');
test(checkValidString("[[[***]]][[[***]]]"), true, 'Test 92');
test(checkValidString("*[]**[**][]"), true, 'Test 93');
test(checkValidString("[[*][*]]*"), true, 'Test 94');
test(checkValidString("[[[*]**]*[***]]"), true, 'Test 95');
test(checkValidString("[[[[*[[*]]]]]"), true, 'Test 96');
test(checkValidString("**[[]]]*[[***]**"), true, 'Test 97');
test(checkValidString("[[[[[]]]]*]"), true, 'Test 98');
test(checkValidString("[*]*[*]"), true, 'Test 99');
test(checkValidString("[[**][[[]]]*]**"), true, 'Test 100');
test(checkValidString("[[]*[][*[]*]*[]]"), true, 'Test 101');
test(checkValidString("[*[*]][*]"), true, 'Test 102');
test(checkValidString("[*]*[**[[]**]]"), true, 'Test 103');
test(checkValidString("[[[[**]]]]]"), true, 'Test 104');
test(checkValidString("[*[]]*[][]*[[]]*"), true, 'Test 105');
test(checkValidString("[[[]]]*[[[**]]]"), true, 'Test 106');
test(checkValidString("*[[[*]*]]"), true, 'Test 107');
test(checkValidString("[[[****]]][]"), true, 'Test 108');
test(checkValidString("[[*][*]][*]"), true, 'Test 109');
test(checkValidString("[**[]][[[]]]"), true, 'Test 110');
test(checkValidString("[[[*]]*]*[[]]]"), true, 'Test 111');
test(checkValidString("[[[[[******]]]]]"), true, 'Test 112');
test(checkValidString("[*[*[*]]]"), true, 'Test 113');
test(checkValidString("[*[[]*[]]*]"), true, 'Test 114');
test(checkValidString("[[[[[*]]]]]"), true, 'Test 115');
test(checkValidString("[***[**]]"), true, 'Test 116');
test(checkValidString("[*[*[[]]]][[[[]]]*]"), true, 'Test 117');
test(checkValidString("[[]***][[[]]]"), true, 'Test 118');
test(checkValidString("[[**[]]*[**]]"), true, 'Test 119');
test(checkValidString("[[]]**[[]]"), true, 'Test 120');
test(checkValidString("[[**]*]"), true, 'Test 121');
test(checkValidString("[[][**][]*]"), true, 'Test 122');
test(checkValidString("[[*[[]]*]*]"), true, 'Test 123');
test(checkValidString("[*[*[*[*]]]]"), true, 'Test 124');
test(checkValidString("*[*[[]]*]*"), true, 'Test 125');
test(checkValidString("[[[]]][*[*]*[]]"), true, 'Test 126');
test(checkValidString("[[*][*][*]][[*]*]"), true, 'Test 127');
test(checkValidString("[*[*[*[*[*]]]]*"), true, 'Test 128');
test(checkValidString("[[[[]]]]**[**]***"), true, 'Test 129');
test(checkValidString("[[**[[]]*[**]]]"), true, 'Test 130');
test(checkValidString("[[][*[*]*]]"), true, 'Test 131');
test(checkValidString("[[]*[[]]**[[]]*[[]]*]"), true, 'Test 132');
test(checkValidString("[*[[[[[]]]]]]"), true, 'Test 133');
test(checkValidString("*[]*[*][]"), true, 'Test 134');
test(checkValidString("[**[[[[**]]]]**"), true, 'Test 135');
test(checkValidString("[[]*[[]]]"), true, 'Test 136');
test(checkValidString("[*[[]*[[]*[[]*[]]]]*]"), true, 'Test 137');
test(checkValidString("[[***]][[***]]"), true, 'Test 138');
test(checkValidString("[[*]*[*]]"), true, 'Test 139');
test(checkValidString("[[[[*]]][[**]][[*]]*]"), true, 'Test 140');
test(checkValidString("[[[[*]]][]*]*"), true, 'Test 141');
test(checkValidString("**[[**]]**"), true, 'Test 142');
test(checkValidString("[[[[*][*][*]]]]****"), true, 'Test 143');
test(checkValidString("[]**[]][[**]]"), true, 'Test 144');
test(checkValidString("[]**[**][]"), true, 'Test 145');
test(checkValidString("[[**[]]][*[[]]]"), true, 'Test 146');
test(checkValidString("[[[[[]**]]**]]"), true, 'Test 147');
test(checkValidString("[*[*[[[]]]]**]"), true, 'Test 148');
test(checkValidString("[*[[]]]"), true, 'Test 149');
test(checkValidString("[[]*[[]**[]]]"), true, 'Test 150');
test(checkValidString("[[[[*]]]][*]"), true, 'Test 151');
test(checkValidString("[**][**][**]"), true, 'Test 152');
test(checkValidString("[[[*]]]"), true, 'Test 153');
test(checkValidString("[[]]][**["), false, 'Test 154');
test(checkValidString("[[*][[*]*]]"), true, 'Test 155');
test(checkValidString("[[*][*][*]]"), true, 'Test 156');
test(checkValidString("[*[][*]]**[[*]]**"), true, 'Test 157');
test(checkValidString("[[*][*]]"), true, 'Test 158');
test(checkValidString("[[***[****]]]"), true, 'Test 159');
test(checkValidString("[[[[]]]][*][[]]"), true, 'Test 160');
test(checkValidString("[[[[**]]]]"), true, 'Test 161');
test(checkValidString("[**[*]*[]][[]]**"), true, 'Test 162');
test(checkValidString("[***[[]]***]"), true, 'Test 163');
test(checkValidString("[[[]]*[[]]*[[]]**]"), true, 'Test 164');
test(checkValidString("[][*[*[*[]]]]"), true, 'Test 165');
test(checkValidString("[*[*]**[*]]]"), true, 'Test 166');
test(checkValidString("[[[]]]*[]**"), true, 'Test 167');
test(checkValidString("[*]*[*[*]*[*]]"), true, 'Test 168');
test(checkValidString("[[]][[[*]]]"), true, 'Test 169');
test(checkValidString("[[]*[][*]]"), true, 'Test 170');
test(checkValidString("[[]*[[]*[]**]]"), true, 'Test 171');
test(checkValidString("[*[[*]*][]**]), Error: Solution.checkValidString[] missing 1 required positional argument: 's', 'Test 172');
test(checkValidString("[[[[*]**]]***]"), true, 'Test 173');
test(checkValidString("[[[[[]]]]]"), true, 'Test 174');
test(checkValidString("*[[[****][**]]]]"), true, 'Test 175');
test(checkValidString("[[]][[[]]]**"), true, 'Test 176');
test(checkValidString("**[[[[[[[]]]]]]]**"), true, 'Test 177');
test(checkValidString("[[**[**]]**[**]]"), true, 'Test 178');
test(checkValidString("[**[*]*]"), true, 'Test 179');
test(checkValidString("[[[[*]]*]*]]]]"), true, 'Test 180');
test(checkValidString("[[]***][]"), true, 'Test 181');
test(checkValidString("[[]][[[]]]***"), true, 'Test 182');
test(checkValidString("[[[]]][*][[[***]]]*"), true, 'Test 183');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

