// Test: 332. Reconstruct Itinerary
// 81 test cases from LeetCodeDataset
// Run: node test.js

const { findItinerary } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n332. Reconstruct Itinerary\n");

test(findItinerary([["JFK","NRT"],["NRT","JFK"]]), ['JFK', 'NRT', 'JFK'], 'Test 1');
test(findItinerary([["JFK","MUC"],["MUC","LHR"],["LHR","SFO"],["SFO","SJC"]]), ['JFK', 'MUC', 'LHR', 'SFO', 'SJC'], 'Test 2');
test(findItinerary([["JFK","AXA"],["AXA","TIA"],["TIA","JFK"],["JFK","AXA"]]), ['JFK', 'AXA', 'TIA', 'JFK', 'AXA'], 'Test 3');
test(findItinerary([["EZE","TIA"],["EZE","HOU"],["AXA","TIA"],["JFK","AXA"],["ANU","JFK"],["TIA","ANU"],["JFK","TIA"]]), ['JFK', 'AXA', 'TIA', 'ANU', 'JFK', 'TIA'], 'Test 4');
test(findItinerary([["JFK","PEK"],["PEK","LAX"],["LAX","JFK"],["JFK","ORD"],["ORD","SFO"]]), ['JFK', 'PEK', 'LAX', 'JFK', 'ORD', 'SFO'], 'Test 5');
test(findItinerary([["JFK","AXA"],["AXA","TIA"],["TIA","JFK"],["JFK","TIA"],["TIA","JFK"]]), ['JFK', 'AXA', 'TIA', 'JFK', 'TIA', 'JFK'], 'Test 6');
test(findItinerary([["MUC","LHR"],["JFK","MUC"],["SFO","SJC"],["LHR","SFO"]]), ['JFK', 'MUC', 'LHR', 'SFO', 'SJC'], 'Test 7');
test(findItinerary([["JFK","KUL"],["JFK","NRT"],["NRT","JFK"]]), ['JFK', 'NRT', 'JFK', 'KUL'], 'Test 8');
test(findItinerary([["JFK","AAA"],["JFK","BBB"],["BBB","JFK"]]), ['JFK', 'BBB', 'JFK', 'AAA'], 'Test 9');
test(findItinerary([["JFK","SFO"],["JFK","ATL"],["SFO","ATL"],["ATL","JFK"],["ATL","SFO"]]), ['JFK', 'ATL', 'JFK', 'SFO', 'ATL', 'SFO'], 'Test 10');
test(findItinerary([["EZE","AXA"],["TIA","ANU"],["ANU","JFK"],["JFK","ANU"],["ANU","EZE"],["TIA","ANU"],["AXA","TIA"],["TIA","JFK"],["ANU","TIA"],["JFK","TIA"]]), ['JFK', 'ANU', 'EZE', 'AXA', 'TIA', 'ANU', 'JFK', 'TIA', 'ANU', 'TIA', 'JFK'], 'Test 11');
test(findItinerary([["EZE","AXA"],["TIA","ANU"],["ANU","JFK"],["JFK","TIA"],["ANU","EZE"],["TIA","ANU"],["AXA","TIA"],["TIA","JFK"],["ANU","TIA"],["JFK","TIA"]]), ['JFK', 'TIA', 'ANU', 'EZE', 'AXA', 'TIA', 'ANU', 'TIA', 'JFK', 'TIA', 'JFK'], 'Test 12');
test(findItinerary([["MUC","LHR"],["JFK","MUC"],["SFO","SJC"],["LHR","SFO"]]), ['JFK', 'MUC', 'LHR', 'SFO', 'SJC'], 'Test 13');
test(findItinerary([["JFK","SFO"],["JFK","ATL"],["SFO","ATL"],["ATL","JFK"],["ATL","SFO"]]), ['JFK', 'ATL', 'JFK', 'SFO', 'ATL', 'SFO'], 'Test 14');
test(findItinerary([["EZE","AXA"],["TIA","ANU"],["ANU","JFK"],["JFK","TIA"],["AXA","TIA"],["TIA","ANU"],["AXA","EZE"],["EZE","ANU"],["AXA","TIA"],["ANU","JFK"],["JFK","TIA"],["JFK","ANU"],["ANU","EZE"],["TIA","JFK"],["EZE","TIA"],["EZE","AXA"],["AXA","TIA"],["AXA","EZE"],["TIA","AXA"],["JFK","AXA"],["AXA","TIA"],["TIA","JFK"],["AXA","EZE"],["EZE","ANU"],["JFK","TIA"],["JFK","ANU"],["ANU","JFK"],["TIA","JFK"],["JFK","TIA"],["JFK","AXA"],["AXA","TIA"],["TIA","JFK"],["AXA","EZE"]]), ['JFK', 'ANU', 'EZE', 'ANU', 'JFK', 'ANU', 'JFK', 'AXA', 'EZE', 'ANU', 'JFK', 'AXA', 'EZE', 'AXA', 'EZE', 'AXA', 'EZE', 'TIA', 'AXA', 'TIA', 'TIA', 'TIA', 'TIA', 'TIA', 'JFK', 'TIA', 'JFK', 'TIA', 'JFK', 'TIA', 'JFK', 'TIA', 'ANU', 'ANU'], 'Test 15');
test(findItinerary([["JFK","PDX"],["PDX","JFK"],["JFK","PDX"],["PDX","LAX"],["LAX","PDX"],["PDX","JFK"],["JFK","PDX"],["PDX","LAX"]]), ['JFK', 'PDX', 'JFK', 'PDX', 'JFK', 'PDX', 'LAX', 'PDX', 'LAX'], 'Test 16');
test(findItinerary([["JFK","BKK"],["BKK","LAX"],["LAX","BKK"],["BKK","SFO"],["SFO","BKK"],["BKK","JFK"],["JFK","LAX"],["LAX","JFK"],["JFK","BKK"],["BKK","LAX"],["LAX","BKK"],["BKK","SFO"],["SFO","BKK"],["BKK","LAX"],["LAX","BKK"],["BKK","SFO"],["SFO","BKK"],["BKK","LAX"],["LAX","BKK"],["BKK","SFO"],["SFO","BKK"],["BKK","LAX"],["LAX","BKK"],["BKK","SFO"],["SFO","BKK"],["BKK","LAX"],["LAX","BKK"],["BKK","SFO"],["SFO","BKK"],["BKK","LAX"],["LAX","BKK"],["BKK","SFO"],["SFO","BKK"]]), ['JFK', 'BKK', 'JFK', 'BKK', 'LAX', 'BKK', 'LAX', 'BKK', 'LAX', 'BKK', 'LAX', 'BKK', 'LAX', 'BKK', 'LAX', 'BKK', 'LAX', 'JFK', 'LAX', 'BKK', 'SFO', 'BKK', 'SFO', 'BKK', 'SFO', 'BKK', 'SFO', 'BKK', 'SFO', 'BKK', 'SFO', 'BKK', 'SFO', 'BKK'], 'Test 17');
test(findItinerary([["JFK","LHR"],["LHR","DEL"],["DEL","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DEL"],["DEL","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DEL"],["DEL","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DEL"],["DEL","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DEL"],["DEL","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DEL"],["DEL","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DEL"],["DEL","DXB"],["DXB","JFK"]]), ['JFK', 'LHR', 'DEL', 'DXB', 'JFK', 'LHR', 'DEL', 'DXB', 'JFK', 'LHR', 'DEL', 'DXB', 'JFK', 'LHR', 'DEL', 'DXB', 'JFK', 'LHR', 'DEL', 'DXB', 'JFK', 'LHR', 'DEL', 'DXB', 'JFK', 'LHR', 'DEL', 'DXB', 'JFK'], 'Test 18');
test(findItinerary([["JFK","HOU"],["HOU","DEN"],["DEN","JFK"],["JFK","SFO"],["SFO","HOU"],["HOU","DEN"],["DEN","SFO"],["SFO","JFK"],["JFK","DEN"],["DEN","HOU"],["HOU","SFO"],["SFO","DEN"],["DEN","JFK"],["JFK","HOU"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 19');
test(findItinerary([["JFK","BKK"],["BKK","LHR"],["LHR","AMS"],["AMS","JFK"],["JFK","DXB"],["DXB","LAX"],["LAX","BKK"],["BKK","JFK"]]), ['JFK', 'BKK', 'JFK', 'DXB', 'LAX', 'BKK', 'LHR', 'AMS', 'JFK'], 'Test 20');
test(findItinerary([["JFK","IST"],["IST","JFK"],["JFK","IST"],["IST","SAW"],["SAW","IST"],["IST","JFK"],["JFK","SAW"],["SAW","JFK"],["JFK","IST"],["IST","SAW"],["SAW","IST"],["IST","JFK"],["JFK","SAW"],["SAW","JFK"],["JFK","IST"],["IST","SAW"],["SAW","IST"],["IST","JFK"],["JFK","SAW"],["SAW","JFK"],["JFK","IST"],["IST","SAW"],["SAW","IST"],["IST","JFK"],["JFK","SAW"],["SAW","JFK"],["JFK","IST"],["IST","SAW"],["SAW","IST"],["IST","JFK"],["JFK","SAW"],["SAW","JFK"],["JFK","IST"],["IST","SAW"],["SAW","IST"],["IST","JFK"],["JFK","SAW"],["SAW","JFK"],["JFK","IST"],["IST","SAW"],["SAW","IST"],["IST","JFK"],["JFK","SAW"],["SAW","JFK"],["JFK","IST"],["IST","SAW"],["SAW","IST"],["IST","JFK"],["JFK","SAW"],["SAW","JFK"],["JFK","IST"],["IST","SAW"],["SAW","IST"],["IST","JFK"],["JFK","SAW"],["SAW","JFK"],["JFK","IST"],["IST","SAW"],["SAW","IST"],["IST","JFK"],["JFK","SAW"],["SAW","JFK"]]), ['JFK', 'IST', 'JFK', 'IST', 'JFK', 'IST', 'JFK', 'IST', 'JFK', 'IST', 'JFK', 'IST', 'JFK', 'IST', 'JFK', 'IST', 'JFK', 'IST', 'JFK', 'IST', 'JFK', 'IST', 'JFK', 'SAW', 'IST', 'SAW', 'IST', 'SAW', 'IST', 'SAW', 'IST', 'SAW', 'IST', 'SAW', 'IST', 'SAW', 'IST', 'SAW', 'IST', 'SAW', 'IST', 'SAW', 'IST', 'SAW', 'JFK', 'SAW', 'JFK', 'SAW', 'JFK', 'SAW', 'JFK', 'SAW', 'JFK', 'SAW', 'JFK', 'SAW', 'JFK', 'SAW', 'JFK', 'SAW', 'JFK', 'SAW', 'JFK'], 'Test 21');
test(findItinerary([["JFK","HOU"],["HOU","SLC"],["SLC","JFK"],["JFK","HOU"],["HOU","ORD"],["ORD","JFK"],["JFK","ORD"],["ORD","SLC"],["SLC","HOU"]]), ['JFK', 'HOU', 'ORD', 'JFK', 'HOU', 'SLC', 'JFK', 'ORD', 'SLC', 'HOU'], 'Test 22');
test(findItinerary([["JFK","DEL"],["DEL","BOM"],["BOM","DXB"],["DXB","JFK"],["JFK","LAX"],["LAX","HOU"],["HOU","SFO"],["SFO","ORD"],["ORD","JFK"],["JFK","LAX"],["LAX","JFK"]]), ['JFK', 'DEL', 'BOM', 'DXB', 'JFK', 'LAX', 'HOU', 'SFO', 'ORD', 'JFK', 'LAX', 'JFK'], 'Test 23');
test(findItinerary([["JFK","A"],["A","B"],["B","C"],["C","D"],["D","A"],["A","JFK"],["JFK","C"]]), ['JFK', 'A', 'B', 'C', 'D', 'A', 'JFK', 'C'], 'Test 24');
test(findItinerary([["JFK","A"],["A","B"],["B","C"],["C","A"],["A","D"],["D","E"],["E","F"],["F","G"],["G","F"],["F","E"],["E","D"],["D","C"],["C","B"],["B","A"],["A","JFK"],["JFK","H"],["H","I"],["I","J"],["J","H"],["H","JFK"],["JFK","K"],["K","L"],["L","M"],["M","N"],["N","O"],["O","P"],["P","Q"],["Q","R"],["R","S"],["S","T"],["T","U"],["U","V"],["V","W"],["W","X"],["X","Y"],["Y","Z"],["Z","W"],["W","V"],["V","U"],["U","T"],["T","S"],["S","R"],["R","Q"],["Q","P"],["P","O"],["O","N"],["N","M"],["M","L"],["L","K"],["K","JFK"],["JFK","G"],["G","F"],["F","E"],["E","D"],["D","C"],["C","B"],["B","A"],["A","JFK"]]), ['JFK', 'A', 'B', 'A', 'D', 'C', 'A', 'JFK', 'G', 'F', 'E', 'D', 'E', 'F', 'G', 'F', 'E', 'D', 'C', 'B', 'C', 'B', 'A', 'JFK', 'H', 'I', 'J', 'H', 'JFK', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'JFK'], 'Test 25');
test(findItinerary([["JFK","CDG"],["CDG","MIA"],["MIA","LAX"],["LAX","HOU"],["HOU","SFO"],["SFO","HOU"],["HOU","LAX"],["LAX","MIA"],["MIA","CDG"],["CDG","JFK"]]), ['JFK', 'CDG', 'MIA', 'LAX', 'HOU', 'SFO', 'HOU', 'LAX', 'MIA', 'CDG', 'JFK'], 'Test 26');
test(findItinerary([["JFK","NRT"],["NRT","JFK"],["JFK","KUL"],["KUL","NRT"],["NRT","KUL"],["KUL","JFK"]]), ['JFK', 'KUL', 'JFK', 'NRT', 'KUL', 'NRT', 'JFK'], 'Test 27');
test(findItinerary([["JFK","NRT"],["NRT","JFK"],["JFK","KUL"],["KUL","LAX"],["LAX","JFK"],["JFK","SFO"],["SFO","ORD"],["ORD","JFK"],["JFK","SFO"],["SFO","NRT"],["NRT","KUL"],["KUL","JFK"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 28');
test(findItinerary([["JFK","KUL"],["KUL","LAX"],["LAX","KUL"],["KUL","SFO"],["SFO","JFK"],["JFK","ORD"],["ORD","SFO"],["SFO","ORD"],["ORD","JFK"],["JFK","SFO"]]), ['JFK', 'KUL', 'LAX', 'KUL', 'SFO', 'JFK', 'ORD', 'JFK', 'SFO', 'ORD', 'SFO'], 'Test 29');
test(findItinerary([["JFK","NRT"],["NRT","JFK"],["JFK","KUL"],["KUL","LAX"],["LAX","JFK"],["JFK","SFO"],["SFO","ORD"],["ORD","JFK"],["JFK","SFO"],["SFO","NRT"],["NRT","KUL"],["KUL","JFK"],["JFK","ORD"],["ORD","SFO"],["SFO","KUL"],["KUL","NRT"],["NRT","SFO"],["SFO","ORD"],["ORD","JFK"],["JFK","SFO"],["SFO","NRT"],["NRT","KUL"],["KUL","JFK"],["JFK","ORD"],["ORD","SFO"],["SFO","KUL"],["KUL","NRT"],["NRT","SFO"],["SFO","ORD"],["ORD","JFK"],["JFK","SFO"],["SFO","NRT"],["NRT","KUL"],["KUL","JFK"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 30');
test(findItinerary([["JFK","NRT"],["NRT","JFK"],["JFK","KUL"],["KUL","LAX"],["LAX","JFK"],["JFK","SFO"],["SFO","ORD"],["ORD","JFK"],["JFK","SFO"],["SFO","NRT"],["NRT","KUL"],["KUL","JFK"],["JFK","ORD"],["ORD","SFO"],["SFO","KUL"],["KUL","NRT"],["NRT","SFO"],["SFO","ORD"],["ORD","JFK"],["JFK","SFO"],["SFO","NRT"],["NRT","KUL"],["KUL","JFK"],["JFK","ORD"],["ORD","SFO"],["SFO","KUL"],["KUL","NRT"],["NRT","SFO"],["SFO","ORD"],["ORD","JFK"],["JFK","SFO"],["SFO","NRT"],["NRT","KUL"],["KUL","JFK"],["JFK","ORD"],["ORD","SFO"],["SFO","KUL"],["KUL","NRT"],["NRT","SFO"],["SFO","ORD"],["ORD","JFK"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 31');
test(findItinerary([["JFK","BOM"],["BOM","SIN"],["SIN","HOU"],["HOU","JFK"],["JFK","HOU"],["HOU","SIN"],["SIN","BOM"],["BOM","JFK"],["JFK","DXB"],["DXB","JFK"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 32');
test(findItinerary([["JFK","AUA"],["AUA","SYD"],["SYD","LAX"],["LAX","JFK"],["JFK","PEK"],["PEK","AUA"],["AUA","SYD"],["SYD","PEK"],["PEK","JFK"],["JFK","LAX"],["LAX","SYD"],["SYD","JFK"],["JFK","AUA"]]), ['JFK', 'AUA', 'SYD', 'JFK', 'AUA', 'SYD', 'LAX', 'JFK', 'LAX', 'SYD', 'PEK', 'JFK', 'PEK', 'AUA'], 'Test 33');
test(findItinerary([["JFK","KUL"],["KUL","LAX"],["LAX","JFK"],["JFK","HOU"],["HOU","SFO"],["SFO","JFK"],["JFK","SLC"],["SLC","HOU"],["HOU","JFK"]]), ['JFK', 'HOU', 'JFK', 'KUL', 'LAX', 'JFK', 'SLC', 'HOU', 'SFO', 'JFK'], 'Test 34');
test(findItinerary([["JFK","IAH"],["IAH","ORD"],["ORD","DEN"],["DEN","LAX"],["LAX","SFO"],["SFO","IAH"],["IAH","ORD"],["ORD","DEN"],["DEN","LAX"]]), ['JFK', 'IAH', 'ORD', 'DEN', 'LAX', 'SFO', 'IAH', 'ORD', 'DEN', 'LAX'], 'Test 35');
test(findItinerary([["JFK","LGA"],["LGA","JFK"],["JFK","LGA"],["LGA","JFK"],["JFK","LGA"],["LGA","JFK"],["JFK","LGA"],["LGA","JFK"],["JFK","LGA"],["LGA","JFK"]]), ['JFK', 'LGA', 'JFK', 'LGA', 'JFK', 'LGA', 'JFK', 'LGA', 'JFK', 'LGA', 'JFK'], 'Test 36');
test(findItinerary([["JFK","SFO"],["SFO","JFK"],["JFK","SFO"],["SFO","LAX"],["LAX","JFK"],["JFK","ORD"],["ORD","SFO"],["SFO","LAX"],["LAX","ORD"],["ORD","JFK"],["JFK","HOU"],["HOU","SFO"],["SFO","HOU"]]), ['JFK', 'HOU', 'SFO', 'JFK', 'ORD', 'JFK', 'SFO', 'LAX', 'JFK', 'SFO', 'LAX', 'ORD', 'SFO', 'HOU'], 'Test 37');
test(findItinerary([["JFK","AAA"],["AAA","BBB"],["BBB","CCC"],["CCC","DDD"],["DDD","JFK"],["JFK","EZE"],["EZE","JFK"]]), ['JFK', 'AAA', 'BBB', 'CCC', 'DDD', 'JFK', 'EZE', 'JFK'], 'Test 38');
test(findItinerary([["JFK","LAX"],["LAX","SFO"],["SFO","JFK"],["JFK","LAX"],["LAX","SFO"],["SFO","LAX"],["LAX","JFK"],["JFK","SFO"],["SFO","LAX"],["LAX","SFO"],["SFO","JFK"],["JFK","LAX"],["LAX","SFO"],["SFO","LAX"],["LAX","JFK"],["JFK","SFO"],["SFO","LAX"],["LAX","SFO"],["SFO","JFK"],["JFK","LAX"],["LAX","SFO"],["SFO","LAX"],["LAX","JFK"],["JFK","SFO"],["SFO","LAX"],["LAX","SFO"],["SFO","JFK"],["JFK","LAX"],["LAX","SFO"],["SFO","LAX"],["LAX","JFK"],["JFK","SFO"],["SFO","LAX"]]), ['JFK', 'LAX', 'JFK', 'LAX', 'JFK', 'LAX', 'JFK', 'LAX', 'JFK', 'LAX', 'SFO', 'JFK', 'SFO', 'JFK', 'SFO', 'JFK', 'SFO', 'JFK', 'SFO', 'LAX', 'SFO', 'LAX', 'SFO', 'LAX', 'SFO', 'LAX', 'SFO', 'LAX', 'SFO', 'LAX', 'SFO', 'LAX', 'SFO', 'LAX'], 'Test 39');
test(findItinerary([["JFK","KUL"],["KUL","LAX"],["LAX","JFK"],["JFK","DUB"],["DUB","ORD"],["ORD","LAX"],["LAX","HOU"],["HOU","SFO"],["SFO","JFK"]]), ['JFK', 'DUB', 'ORD', 'LAX', 'HOU', 'SFO', 'JFK', 'KUL', 'LAX', 'JFK'], 'Test 40');
test(findItinerary([["JFK","XYZ"],["XYZ","ABC"],["ABC","JKL"],["JKL","MNO"],["MNO","PQR"],["PQR","JKL"],["JKL","ABC"],["ABC","XYZ"],["XYZ","JFK"],["JFK","MNO"]]), ['JFK', 'MNO', 'PQR', 'JKL', 'ABC', 'XYZ', 'JFK', 'XYZ', 'ABC', 'JKL', 'MNO'], 'Test 41');
test(findItinerary([["JFK","XYZ"],["XYZ","ABC"],["ABC","JFK"],["JFK","XYZ"],["XYZ","DEF"],["DEF","ABC"],["ABC","XYZ"],["XYZ","DEF"],["DEF","JFK"]]), ['JFK', 'XYZ', 'ABC', 'JFK', 'XYZ', 'DEF', 'ABC', 'XYZ', 'DEF', 'JFK'], 'Test 42');
test(findItinerary([["JFK","DEL"],["DEL","JFK"],["JFK","BOM"],["BOM","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BOM"],["BOM","JFK"],["JFK","BOM"],["BOM","DEL"]]), ['JFK', 'BOM', 'DEL', 'BOM', 'DEL', 'JFK', 'BOM', 'JFK', 'DEL', 'JFK', 'DEL'], 'Test 43');
test(findItinerary([["JFK","DEL"],["DEL","BOM"],["BOM","DEL"],["DEL","LHR"],["LHR","BOM"],["BOM","SFO"],["SFO","LHR"],["LHR","SFO"],["SFO","DEL"],["DEL","JFK"],["JFK","LHR"],["LHR","DEL"],["DEL","BOM"],["BOM","SFO"],["SFO","JFK"],["JFK","BOM"],["BOM","LHR"],["LHR","JFK"],["JFK","SFO"],["SFO","BOM"]]), ['JFK', 'BOM', 'DEL', 'BOM', 'LHR', 'BOM', 'SFO', 'BOM', 'SFO', 'DEL', 'JFK', 'DEL', 'LHR', 'JFK', 'LHR', 'SFO', 'JFK', 'SFO', 'LHR', 'DEL', 'BOM'], 'Test 44');
test(findItinerary([["JFK","BCN"],["BCN","JFK"],["JFK","MIA"],["MIA","JFK"],["JFK","DXB"],["DXB","JFK"],["JFK","SFO"],["SFO","JFK"]]), ['JFK', 'BCN', 'JFK', 'DXB', 'JFK', 'MIA', 'JFK', 'SFO', 'JFK'], 'Test 45');
test(findItinerary([["JFK","DXB"],["DXB","JFK"],["JFK","DXB"],["DXB","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","LHR"],["LHR","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"],["DXB","JFK"],["JFK","LHR"],["LHR","DXB"]]), ['JFK', 'DXB', 'JFK', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'JFK', 'LHR', 'DXB', 'LHR', 'DXB', 'LHR', 'JFK', 'LHR', 'DXB'], 'Test 46');
test(findItinerary([["JFK","NRT"],["NRT","JFK"],["JFK","NRT"],["NRT","PEK"],["PEK","LAX"],["LAX","PEK"],["PEK","JFK"],["JFK","LAX"],["LAX","JFK"],["JFK","PEK"],["PEK","NRT"],["NRT","LAX"],["LAX","NRT"],["NRT","JFK"],["JFK","PEK"],["PEK","LAX"],["LAX","JFK"]]), ['JFK', 'LAX', 'JFK', 'NRT', 'JFK', 'NRT', 'JFK', 'PEK', 'JFK', 'PEK', 'LAX', 'NRT', 'LAX', 'PEK', 'NRT', 'PEK', 'LAX', 'JFK'], 'Test 47');
test(findItinerary([["JFK","FRA"],["JFK","TIA"],["FRA","JFK"],["TIA","FRA"],["FRA","TIA"],["TIA","JFK"]]), ['JFK', 'FRA', 'JFK', 'TIA', 'FRA', 'TIA', 'JFK'], 'Test 48');
test(findItinerary([["JFK","YYZ"],["YYZ","BOS"],["BOS","YYZ"],["YYZ","JFK"],["JFK","YYZ"],["YYZ","BOS"],["BOS","JFK"],["JFK","BOS"],["BOS","YYZ"],["YYZ","JFK"]]), ['JFK', 'BOS', 'JFK', 'YYZ', 'BOS', 'YYZ', 'BOS', 'YYZ', 'JFK', 'YYZ', 'JFK'], 'Test 49');
test(findItinerary([["JFK","YYZ"],["YYZ","JFK"],["JFK","YYZ"],["YYZ","LHR"],["LHR","YYZ"],["YYZ","JFK"],["JFK","LHR"],["LHR","YYZ"],["YYZ","LHR"],["LHR","JFK"],["JFK","YYZ"],["YYZ","JFK"],["JFK","LHR"],["LHR","YYZ"],["YYZ","JFK"],["JFK","LHR"],["LHR","YYZ"],["YYZ","JFK"],["JFK","LHR"],["LHR","YYZ"],["YYZ","JFK"],["JFK","LHR"],["LHR","YYZ"],["YYZ","JFK"],["JFK","LHR"],["LHR","YYZ"],["YYZ","JFK"],["JFK","LHR"]]), ['JFK', 'LHR', 'JFK', 'LHR', 'YYZ', 'JFK', 'LHR', 'YYZ', 'JFK', 'LHR', 'YYZ', 'JFK', 'LHR', 'YYZ', 'JFK', 'LHR', 'YYZ', 'JFK', 'LHR', 'YYZ', 'JFK', 'YYZ', 'JFK', 'YYZ', 'JFK', 'YYZ', 'LHR', 'YYZ', 'LHR'], 'Test 50');
test(findItinerary([["JFK","ORD"],["ORD","SFO"],["SFO","JFK"],["JFK","LAX"],["LAX","SFO"],["SFO","ORD"],["ORD","JFK"],["JFK","NRT"],["NRT","SFO"],["SFO","LAX"],["LAX","ORD"],["ORD","NRT"],["NRT","JFK"],["JFK","SFO"],["SFO","NRT"],["NRT","ORD"],["ORD","LAX"],["LAX","JFK"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 51');
test(findItinerary([["JFK","NRT"],["NRT","JFK"],["JFK","KUL"],["KUL","LAX"],["LAX","NRT"],["NRT","KUL"],["KUL","JFK"]]), ['JFK', 'KUL', 'JFK', 'NRT', 'KUL', 'LAX', 'NRT', 'JFK'], 'Test 52');
test(findItinerary([["JFK","SFO"],["SFO","LAX"],["LAX","DEN"],["DEN","LAX"],["LAX","SFO"],["SFO","JFK"],["JFK","SFO"],["SFO","LAX"],["LAX","DEN"]]), ['JFK', 'SFO', 'JFK', 'SFO', 'LAX', 'DEN', 'LAX', 'SFO', 'LAX', 'DEN'], 'Test 53');
test(findItinerary([["JFK","SFO"],["SFO","ATL"],["ATL","JFK"],["JFK","ORD"],["ORD","SFO"],["SFO","ORD"],["ORD","ATL"],["ATL","SFO"],["SFO","JFK"],["JFK","ORD"],["ORD","ATL"],["ATL","ORD"],["ORD","SFO"],["SFO","ATL"],["ATL","JFK"],["JFK","SFO"],["SFO","ORD"],["ORD","SFO"],["SFO","ATL"],["ATL","ORD"],["ORD","JFK"],["JFK","ATL"],["ATL","ORD"],["ORD","SFO"],["SFO","JFK"],["JFK","ORD"],["ORD","SFO"],["SFO","ATL"],["ATL","ORD"],["ORD","JFK"],["JFK","SFO"]]), ['JFK', 'ATL', 'JFK', 'ORD', 'ATL', 'JFK', 'ORD', 'ATL', 'ORD', 'JFK', 'ORD', 'JFK', 'SFO', 'ATL', 'ORD', 'SFO', 'ATL', 'ORD', 'SFO', 'ATL', 'ORD', 'SFO', 'ATL', 'SFO', 'JFK', 'SFO', 'JFK', 'SFO', 'ORD', 'SFO', 'ORD', 'SFO'], 'Test 54');
test(findItinerary([["JFK","ZRH"],["ZRH","HOU"],["HOU","JFK"],["JFK","LHR"],["LHR","HOU"],["HOU","LHR"],["LHR","ZRH"],["ZRH","JFK"]]), ['JFK', 'LHR', 'HOU', 'JFK', 'ZRH', 'HOU', 'LHR', 'ZRH', 'JFK'], 'Test 55');
test(findItinerary([["JFK","IST"],["IST","DXB"],["DXB","ORD"],["ORD","JFK"],["JFK","IST"],["IST","DXB"],["DXB","ORD"],["ORD","LAX"],["LAX","JFK"]]), ['JFK', 'IST', 'DXB', 'ORD', 'JFK', 'IST', 'DXB', 'ORD', 'LAX', 'JFK'], 'Test 56');
test(findItinerary([["JFK","SFO"],["SFO","ATL"],["ATL","JFK"],["JFK","SFO"],["SFO","ORD"],["ORD","SFO"],["SFO","ATL"],["ATL","SFO"],["SFO","ORD"],["ORD","JFK"]]), ['JFK', 'SFO', 'ATL', 'JFK', 'SFO', 'ATL', 'SFO', 'ORD', 'SFO', 'ORD', 'JFK'], 'Test 57');
test(findItinerary([["JFK","DXB"],["DXB","SYD"],["SYD","JFK"],["JFK","DEL"],["DEL","DXB"],["DXB","SYD"],["SYD","DEL"],["DEL","JFK"]]), ['JFK', 'DEL', 'DXB', 'SYD', 'DEL', 'JFK', 'DXB', 'SYD', 'JFK'], 'Test 58');
test(findItinerary([["JFK","DXB"],["DXB","BKK"],["BKK","DXB"],["DXB","JFK"],["JFK","DEL"],["DEL","DXB"],["DXB","DEL"],["DEL","BKK"],["BKK","DEL"],["DEL","JFK"],["JFK","BKK"],["BKK","JFK"],["JFK","DXB"]]), ['JFK', 'BKK', 'DEL', 'BKK', 'DXB', 'BKK', 'JFK', 'DEL', 'DXB', 'DEL', 'JFK', 'DXB', 'JFK', 'DXB'], 'Test 59');
test(findItinerary([["JFK","CPT"],["CPT","DEL"],["DEL","DXB"],["DXB","SFO"],["SFO","HOU"],["HOU","JFK"],["JFK","BOM"],["BOM","CPT"],["CPT","HOU"],["HOU","DXB"],["DXB","JFK"],["JFK","SFO"],["SFO","DEL"],["DEL","BOM"],["BOM","HOU"],["HOU","SFO"],["SFO","DXB"],["DXB","CPT"],["CPT","BOM"],["BOM","SFO"]]), ['JFK', 'BOM', 'CPT', 'BOM', 'HOU', 'DXB', 'CPT', 'DEL', 'BOM', 'SFO', 'DEL', 'DXB', 'JFK', 'CPT', 'HOU', 'JFK', 'SFO', 'DXB', 'SFO', 'HOU', 'SFO'], 'Test 60');
test(findItinerary([["JFK","LAX"],["LAX","SFO"],["SFO","HOU"],["HOU","LAX"],["LAX","JFK"],["JFK","ORD"],["ORD","SFO"],["SFO","HOU"],["HOU","ORD"],["ORD","JFK"]]), ['JFK', 'LAX', 'JFK', 'ORD', 'SFO', 'HOU', 'LAX', 'SFO', 'HOU', 'ORD', 'JFK'], 'Test 61');
test(findItinerary([["JFK","NRT"],["JFK","KUL"],["NRT","JFK"],["KUL","JFK"],["JFK","NRT"],["NRT","KUL"],["KUL","NRT"],["NRT","LAX"],["LAX","HOU"],["HOU","SYD"],["SYD","JFK"],["JFK","SYD"],["SYD","HOU"],["HOU","LAX"],["LAX","NRT"],["NRT","JFK"],["JFK","LAX"],["LAX","SYD"],["SYD","JFK"],["JFK","AUA"],["AUA","SYD"],["SYD","LAX"],["LAX","JFK"],["JFK","PEK"],["PEK","AUA"],["AUA","SYD"],["SYD","PEK"],["PEK","JFK"]]), ['JFK', 'AUA', 'SYD', 'HOU', 'LAX', 'HOU', 'SYD', 'JFK', 'KUL', 'JFK', 'LAX', 'JFK', 'NRT', 'JFK', 'NRT', 'JFK', 'PEK', 'AUA', 'SYD', 'JFK', 'SYD', 'LAX', 'NRT', 'KUL', 'NRT', 'LAX', 'SYD', 'PEK', 'JFK'], 'Test 62');
test(findItinerary([["JFK","NRT"],["JFK","KUL"],["NRT","JFK"],["KUL","JFK"],["JFK","NRT"],["NRT","KUL"],["KUL","NRT"],["NRT","LAX"],["LAX","HOU"],["HOU","SYD"],["SYD","JFK"],["JFK","SYD"],["SYD","HOU"],["HOU","LAX"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 63');
test(findItinerary([["JFK","A"],["A","B"],["B","C"],["C","D"],["D","E"],["E","F"],["F","G"],["G","H"],["H","I"],["I","J"],["J","K"],["K","L"],["L","M"],["M","N"],["N","O"],["O","P"],["P","Q"],["Q","R"],["R","S"],["S","T"],["T","U"],["U","V"],["V","W"],["W","X"],["X","Y"],["Y","Z"],["Z","A"],["A","JFK"],["JFK","Z"],["Z","Y"],["Y","X"],["X","W"],["W","V"],["V","U"],["U","T"],["T","S"],["S","R"],["R","Q"],["Q","P"],["P","O"],["O","N"],["N","M"],["M","L"],["L","K"],["K","J"],["J","I"],["I","H"],["H","G"],["G","F"],["F","E"],["E","D"],["D","C"],["C","B"],["B","A"],["A","JFK"]]), ['JFK', 'A', 'B', 'A', 'JFK', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'A', 'JFK'], 'Test 64');
test(findItinerary([["JFK","KUL"],["KUL","LAX"],["LAX","DXB"],["DXB","JFK"],["JFK","NRT"],["NRT","LAX"],["LAX","SYD"],["SYD","DXB"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 65');
test(findItinerary([["JFK","NRT"],["NRT","JFK"],["JFK","KUL"],["KUL","NRT"],["NRT","JFK"],["JFK","NRT"]]), ['JFK', 'KUL', 'NRT', 'JFK', 'NRT', 'JFK', 'NRT'], 'Test 66');
test(findItinerary([["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"],["DEL","BLR"],["BLR","DEL"],["DEL","JFK"],["JFK","DEL"]]), ['JFK', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'BLR', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL', 'JFK', 'DEL'], 'Test 67');
test(findItinerary([["JFK","B"],["B","JFK"],["JFK","C"],["C","JFK"],["JFK","D"],["D","JFK"],["JFK","E"],["E","JFK"]]), ['JFK', 'B', 'JFK', 'C', 'JFK', 'D', 'JFK', 'E', 'JFK'], 'Test 68');
test(findItinerary([["JFK","CDG"],["CDG","HOU"],["HOU","DXB"],["DXB","SFO"],["SFO","JFK"],["JFK","DXB"],["DXB","HOU"],["HOU","CDG"],["CDG","JFK"],["JFK","HOU"],["HOU","SFO"],["SFO","DXB"],["DXB","JFK"],["JFK","SFO"],["SFO","HOU"],["HOU","CDG"],["CDG","DXB"],["DXB","SFO"],["SFO","CDG"],["CDG","HOU"],["HOU","JFK"],["JFK","CDG"]]), ['JFK', 'CDG', 'DXB', 'HOU', 'CDG', 'HOU', 'CDG', 'HOU', 'DXB', 'JFK', 'CDG', 'JFK', 'DXB', 'SFO', 'DXB', 'SFO', 'HOU', 'JFK', 'HOU', 'SFO', 'JFK', 'SFO', 'CDG'], 'Test 69');
test(findItinerary([["JFK","SFO"],["SFO","DSM"],["DSM","JFK"],["JFK","SFO"],["SFO","LAX"],["LAX","JFK"],["JFK","SFO"],["SFO","DSM"]]), ['JFK', 'SFO', 'DSM', 'JFK', 'SFO', 'LAX', 'JFK', 'SFO', 'DSM'], 'Test 70');
test(findItinerary([["JFK","HOU"],["HOU","LAX"],["LAX","NRT"],["NRT","DXB"],["DXB","SFO"],["SFO","MIA"],["MIA","JFK"],["JFK","HOU"],["HOU","LAX"],["LAX","NRT"],["NRT","DXB"],["DXB","SFO"],["SFO","MIA"],["MIA","JFK"],["JFK","HOU"],["HOU","LAX"],["LAX","NRT"],["NRT","DXB"],["DXB","SFO"],["SFO","MIA"],["MIA","JFK"],["JFK","HOU"],["HOU","LAX"],["LAX","NRT"],["NRT","DXB"],["DXB","SFO"],["SFO","MIA"],["MIA","JFK"]]), ['JFK', 'HOU', 'LAX', 'NRT', 'DXB', 'SFO', 'MIA', 'JFK', 'HOU', 'LAX', 'NRT', 'DXB', 'SFO', 'MIA', 'JFK', 'HOU', 'LAX', 'NRT', 'DXB', 'SFO', 'MIA', 'JFK', 'HOU', 'LAX', 'NRT', 'DXB', 'SFO', 'MIA', 'JFK'], 'Test 71');
test(findItinerary([["JFK","NRT"],["NRT","JFK"],["JFK","KUL"],["KUL","LAX"],["LAX","JFK"],["JFK","SFO"],["SFO","ORD"],["ORD","JFK"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 72');
test(findItinerary([["JFK","A"],["A","B"],["B","C"],["C","A"],["A","D"],["D","E"],["E","F"],["F","G"],["G","F"],["F","E"],["E","D"],["D","C"],["C","B"],["B","A"],["A","JFK"],["JFK","H"],["H","I"],["I","J"],["J","H"],["H","JFK"],["JFK","K"],["K","L"],["L","M"],["M","N"],["N","O"],["O","P"],["P","Q"],["Q","R"],["R","S"],["S","T"],["T","U"],["U","V"],["V","W"],["W","X"],["X","Y"],["Y","Z"],["Z","W"],["W","V"],["V","U"],["U","T"],["T","S"],["S","R"],["R","Q"],["Q","P"],["P","O"],["O","N"],["N","M"],["M","L"],["L","K"],["K","JFK"]]), ['JFK', 'A', 'B', 'A', 'D', 'E', 'F', 'G', 'F', 'E', 'D', 'C', 'B', 'C', 'A', 'JFK', 'H', 'I', 'J', 'H', 'JFK', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'JFK'], 'Test 73');
test(findItinerary([["JFK","LHR"],["LHR","SFO"],["SFO","JFK"],["JFK","LAX"],["LAX","ORD"],["ORD","JFK"],["JFK","CDG"],["CDG","HOU"],["HOU","LAX"],["LAX","JFK"],["JFK","CDG"],["CDG","LHR"],["LHR","ORD"],["ORD","HOU"],["HOU","JFK"],["JFK","LAX"],["LAX","SFO"],["SFO","CDG"],["CDG","JFK"],["JFK","HOU"],["HOU","ORD"],["ORD","LAX"],["LAX","SFO"],["SFO","ORD"],["ORD","JFK"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 74');
test(findItinerary([["JFK","BOS"],["BOS","SFO"],["SFO","BOS"],["BOS","JFK"],["JFK","BOS"],["BOS","JFK"],["JFK","BOS"],["BOS","SFO"]]), ['JFK', 'BOS', 'JFK', 'BOS', 'JFK', 'BOS', 'SFO', 'BOS', 'SFO'], 'Test 75');
test(findItinerary([["JFK","MEX"],["MEX","LAX"],["LAX","JFK"],["JFK","MEX"],["MEX","LAX"],["LAX","MEX"],["MEX","JFK"],["JFK","LAX"],["LAX","MEX"],["MEX","LAX"]]), ['JFK', 'LAX', 'JFK', 'MEX', 'JFK', 'MEX', 'LAX', 'MEX', 'LAX', 'MEX', 'LAX'], 'Test 76');
test(findItinerary([["JFK","A"],["A","B"],["B","C"],["C","A"],["A","D"],["D","E"],["E","F"],["F","G"],["G","E"],["E","D"],["D","A"],["A","C"],["C","B"],["B","A"],["A","F"],["F","E"],["E","D"],["D","C"],["C","A"],["A","B"],["B","C"],["C","D"],["D","E"],["E","F"],["F","G"],["G","F"],["F","E"],["E","D"],["D","C"],["C","B"],["B","A"],["A","JFK"]]), ['JFK', 'A', 'B', 'A', 'B', 'A', 'C', 'A', 'D', 'A', 'F', 'E', 'D', 'C', 'B', 'C', 'B', 'C', 'D', 'E', 'D', 'E', 'F', 'E', 'F', 'G', 'F', 'G', 'E', 'D', 'C', 'A', 'JFK'], 'Test 77');
test(findItinerary([["JFK","SLC"],["SLC","JFK"],["JFK","ATL"],["ATL","JFK"],["JFK","SFO"],["SFO","JFK"],["JFK","ORD"],["ORD","JFK"],["JFK","LAX"],["LAX","JFK"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 78');
test(findItinerary([["JFK","AAA"],["AAA","BBB"],["BBB","CCC"],["CCC","DDD"],["DDD","EEE"],["EEE","DDD"],["DDD","CCC"],["CCC","BBB"],["BBB","AAA"],["AAA","JFK"],["JFK","DDD"],["DDD","EEE"],["EEE","DDD"],["DDD","CCC"],["CCC","BBB"],["BBB","AAA"],["AAA","JFK"]]), ['JFK', 'AAA', 'BBB', 'AAA', 'JFK', 'DDD', 'CCC', 'BBB', 'CCC', 'DDD', 'EEE', 'DDD', 'EEE', 'DDD', 'CCC', 'BBB', 'AAA', 'JFK'], 'Test 79');
test(findItinerary([["JFK","AUA"],["AUA","SFO"],["SFO","HOU"],["HOU","JFK"],["JFK","AUA"],["AUA","HOU"],["HOU","SFO"],["SFO","JFK"],["JFK","AUA"],["AUA","SFO"],["SFO","HOU"],["HOU","JFK"]]), ['JFK', 'AUA', 'HOU', 'JFK', 'AUA', 'SFO', 'HOU', 'JFK', 'AUA', 'SFO', 'HOU', 'SFO', 'JFK'], 'Test 80');
test(findItinerary([["JFK","NRT"],["JFK","KUL"],["NRT","JFK"],["KUL","JFK"],["JFK","NRT"],["NRT","KUL"],["KUL","NRT"]]"), Error: Solution.findItinerary[] missing 1 required positional argument: 'tickets', 'Test 81');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

// Auto-mark DONE when all tests pass
if (!failed) {
  const path = require("path");
  const fs = require("fs");
  const dir = __dirname;
  const folder = path.basename(dir);
  if (!folder.startsWith("DONE-")) {
    const parent = path.dirname(dir);
    const newDir = path.join(parent, "DONE-" + folder);
    fs.renameSync(dir, newDir);
    const readme = path.join(newDir, "README.md");
    if (fs.existsSync(readme)) {
      let c = fs.readFileSync(readme, "utf-8");
      if (!c.includes("<!-- SOLVED -->")) {
        c = c.replace(/^(# .+)$/m, "$1 ✅\n<!-- SOLVED -->");
        fs.writeFileSync(readme, c);
      }
    }
    console.log("✅ DONE → " + "DONE-" + folder);
  }
}
