// Test: 2490. Circular Sentence
// 220 test cases from LeetCodeDataset
// Run: node test.js

const { isCircularSentence } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n2490. Circular Sentence\n");

test(isCircularSentence("sentence ence sent"), false, 'Test 1');
test(isCircularSentence("hello olleh"), true, 'Test 2');
test(isCircularSentence("Aa Aa"), false, 'Test 3');
test(isCircularSentence("ab ba"), true, 'Test 4');
test(isCircularSentence("a"), true, 'Test 5');
test(isCircularSentence("Leetcode is cool"), false, 'Test 6');
test(isCircularSentence("b"), true, 'Test 7');
test(isCircularSentence("A aA A"), false, 'Test 8');
test(isCircularSentence("abcd dcba"), true, 'Test 9');
test(isCircularSentence("circular rular circul"), false, 'Test 10');
test(isCircularSentence("Zz zZ"), true, 'Test 11');
test(isCircularSentence("abc cba"), true, 'Test 12');
test(isCircularSentence("a a a a"), true, 'Test 13');
test(isCircularSentence("example ample exa"), false, 'Test 14');
test(isCircularSentence("A a A"), false, 'Test 15');
test(isCircularSentence("Zz"), false, 'Test 16');
test(isCircularSentence("eetcode"), true, 'Test 17');
test(isCircularSentence("abc cab bca"), true, 'Test 18');
test(isCircularSentence("abc bca cab"), false, 'Test 19');
test(isCircularSentence("B ba B"), false, 'Test 20');
test(isCircularSentence("leetcode exercises sound delightful"), true, 'Test 21');
test(isCircularSentence("b b b"), true, 'Test 22');
test(isCircularSentence("a b c a"), false, 'Test 23');
test(isCircularSentence("A a"), false, 'Test 24');
test(isCircularSentence("test tset"), true, 'Test 25');
test(isCircularSentence("aba"), true, 'Test 26');
test(isCircularSentence("mnopqr stuvwx yzab cd efgh ijklm nopqr"), false, 'Test 27');
test(isCircularSentence("world dlrow"), true, 'Test 28');
test(isCircularSentence("abcdefghijklmnopqrstuvwxyz zabcdefghijklmnopqrstuvwxy"), false, 'Test 29');
test(isCircularSentence("No lemon no melon"), false, 'Test 30');
test(isCircularSentence("Anna"), false, 'Test 31');
test(isCircularSentence("Able was I ere I saw Elba Able"), false, 'Test 32');
test(isCircularSentence("Was it a car or a cat I saw saw I tac a ro rac a si taW taW"), false, 'Test 33');
test(isCircularSentence("Madam In Eden Im Adam"), false, 'Test 34');
test(isCircularSentence("Circular logic confuses brains sourcing smiles"), false, 'Test 35');
test(isCircularSentence("Rotation noitator tor"), false, 'Test 36');
test(isCircularSentence("noon moon moon"), false, 'Test 37');
test(isCircularSentence("peep peep"), true, 'Test 38');
test(isCircularSentence("b aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa aaaaaaaaa aaaaaaaaaa aaaaaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaa aaaaaaaaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaa b"), false, 'Test 39');
test(isCircularSentence("Noon neons number nicely"), false, 'Test 40');
test(isCircularSentence("Madam madam madam"), false, 'Test 41');
test(isCircularSentence("refer level civic civic civic level refer"), false, 'Test 42');
test(isCircularSentence("xyyx xxyy"), false, 'Test 43');
test(isCircularSentence("kayak kayak kayak kayak"), true, 'Test 44');
test(isCircularSentence("rotor racecar level deed civic"), false, 'Test 45');
test(isCircularSentence("stats tacocat stats"), false, 'Test 46');
test(isCircularSentence("racecar civic madam"), false, 'Test 47');
test(isCircularSentence("Step on no pets no step on no pets"), false, 'Test 48');
test(isCircularSentence("Able was I I saw Elba Elba saw I I was Able"), false, 'Test 49');
test(isCircularSentence("tacocat"), true, 'Test 50');
test(isCircularSentence("a quick brown fox jumps over lazy a"), false, 'Test 51');
test(isCircularSentence("zoo online one nice Easter egg"), false, 'Test 52');
test(isCircularSentence("Word dOrw"), false, 'Test 53');
test(isCircularSentence("deed deed"), true, 'Test 54');
test(isCircularSentence("daemon daemon"), false, 'Test 55');
test(isCircularSentence("Palindrome emordnilaP"), true, 'Test 56');
test(isCircularSentence("madam racecar civic"), false, 'Test 57');
test(isCircularSentence("Circular arular ci"), false, 'Test 58');
test(isCircularSentence("Madam adaM"), false, 'Test 59');
test(isCircularSentence("A Santa at NASA"), false, 'Test 60');
test(isCircularSentence("sun sets slowly on nosy wonks"), false, 'Test 61');
test(isCircularSentence("madam racecar level deed civic kayak rotor"), false, 'Test 62');
test(isCircularSentence("abcde edcba"), true, 'Test 63');
test(isCircularSentence("Nested edset n"), false, 'Test 64');
test(isCircularSentence("kayak kayak"), true, 'Test 65');
test(isCircularSentence("Nurses run Nurses"), false, 'Test 66');
test(isCircularSentence("Programming gnostic stem ngram minnow winnow now"), false, 'Test 67');
test(isCircularSentence("rotor rotor"), true, 'Test 68');
test(isCircularSentence("redivider"), true, 'Test 69');
test(isCircularSentence("racecar civic level deed"), false, 'Test 70');
test(isCircularSentence("Abba aaaa aa a"), false, 'Test 71');
test(isCircularSentence("xylophone elephant monkey keen"), false, 'Test 72');
test(isCircularSentence("xyzzyx"), true, 'Test 73');
test(isCircularSentence("circularloop loop"), false, 'Test 74');
test(isCircularSentence("Alaska Kansas suck slyly yelling nasty nasty yaks yak salty knapsack sacks sacks sky kayak kayak kayak"), false, 'Test 75');
test(isCircularSentence("x y z x"), false, 'Test 76');
test(isCircularSentence("programming is simply programming"), false, 'Test 77');
test(isCircularSentence("zoo omega meal alpha"), false, 'Test 78');
test(isCircularSentence("Loop opLo"), false, 'Test 79');
test(isCircularSentence("Startling lightning bugs ignited giants"), false, 'Test 80');
test(isCircularSentence("xylophone one love evolution nation"), false, 'Test 81');
test(isCircularSentence("deed deed deed"), true, 'Test 82');
test(isCircularSentence("Palindrome emordnilaP laP"), false, 'Test 83');
test(isCircularSentence("noon odd level civic civic civic level odd noon"), false, 'Test 84');
test(isCircularSentence("Was it a car or a cat I saw Was"), false, 'Test 85');
test(isCircularSentence("Reflection noitcifilr"), false, 'Test 86');
test(isCircularSentence("ab ba ac ca"), true, 'Test 87');
test(isCircularSentence("racecar racecar"), true, 'Test 88');
test(isCircularSentence("abracadabra arachnophobia"), true, 'Test 89');
test(isCircularSentence("repaper repaper repaper"), true, 'Test 90');
test(isCircularSentence("Complex xs w x"), false, 'Test 91');
test(isCircularSentence("abcd defg ghij jkla"), true, 'Test 92');
test(isCircularSentence("Interstellar rstellar inter"), false, 'Test 93');
test(isCircularSentence("reviled devil level deed vile derevered"), false, 'Test 94');
test(isCircularSentence("Fascinating ideas inspire amazing minds"), false, 'Test 95');
test(isCircularSentence("Alphabet tebahpla A"), false, 'Test 96');
test(isCircularSentence("Unique new weird weed nude euqinu"), false, 'Test 97');
test(isCircularSentence("Wow wow"), false, 'Test 98');
test(isCircularSentence("tortoise einstein noodles stein snot not ossetia"), false, 'Test 99');
test(isCircularSentence("rotor kayak rotor"), false, 'Test 100');
test(isCircularSentence("kayak kayak kayak kayak kayak"), true, 'Test 101');
test(isCircularSentence("zebra apple orange night eagle"), false, 'Test 102');
test(isCircularSentence("Zebra apple orange elephant"), false, 'Test 103');
test(isCircularSentence("redder redder"), true, 'Test 104');
test(isCircularSentence("No lemon no melon no lemon no melon"), false, 'Test 105');
test(isCircularSentence("xylophone elephant monkey keen noodle leet teex"), false, 'Test 106');
test(isCircularSentence("Anna civic radar level rotor"), false, 'Test 107');
test(isCircularSentence("zoo omega anna apple"), false, 'Test 108');
test(isCircularSentence("Detartrated dater dated"), false, 'Test 109');
test(isCircularSentence("xylophone excellent noodles seen"), false, 'Test 110');
test(isCircularSentence("Madam madam"), false, 'Test 111');
test(isCircularSentence("level level"), true, 'Test 112');
test(isCircularSentence("abracadabra aracnidae earthworms mammals sloths"), false, 'Test 113');
test(isCircularSentence("level level level level"), true, 'Test 114');
test(isCircularSentence("Wow wow wow"), false, 'Test 115');
test(isCircularSentence("palindrome emordnilap"), true, 'Test 116');
test(isCircularSentence("Was it a car or a cat I saw seen saw I tac a ro rac a ti saw"), false, 'Test 117');
test(isCircularSentence("a aa aaa aaaa"), true, 'Test 118');
test(isCircularSentence("xylophone objective elegant elegant not"), false, 'Test 119');
test(isCircularSentence("b b b b b"), true, 'Test 120');
test(isCircularSentence("XYlophone emotion motion nation"), false, 'Test 121');
test(isCircularSentence("Zoos own cozy zones"), false, 'Test 122');
test(isCircularSentence("deified deified deified deified"), true, 'Test 123');
test(isCircularSentence("Was it a car or a cat I saw"), false, 'Test 124');
test(isCircularSentence("Zebra apple apple orange onion nginx"), false, 'Test 125');
test(isCircularSentence("cycle ycle c"), false, 'Test 126');
test(isCircularSentence("Wow"), false, 'Test 127');
test(isCircularSentence("Programming gamifies lessons yielding successes"), false, 'Test 128');
test(isCircularSentence("Rhythms mesmerize symphonies"), false, 'Test 129');
test(isCircularSentence("Madam Ada"), false, 'Test 130');
test(isCircularSentence("Madam Arora teaches malayalam Madam"), false, 'Test 131');
test(isCircularSentence("Rotator taro Rotator"), false, 'Test 132');
test(isCircularSentence("a a a a a a a a a a a a"), true, 'Test 133');
test(isCircularSentence("abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba"), true, 'Test 134');
test(isCircularSentence("Civic civic"), false, 'Test 135');
test(isCircularSentence("repaper deed deed deed deed deed deed deed deed deed deed deed deed deed deed deed deed deed deed deed deed"), false, 'Test 136');
test(isCircularSentence("kayak civic deed level odd noon"), false, 'Test 137');
test(isCircularSentence("Madam Arora teaches malayalam"), false, 'Test 138');
test(isCircularSentence("noon odd level deed civic kayak"), false, 'Test 139');
test(isCircularSentence("giraffe elephant noodle leet teex xxyy"), false, 'Test 140');
test(isCircularSentence("Echo Charlie Hotel Hotel Echo"), false, 'Test 141');
test(isCircularSentence("racecar madam rotator"), false, 'Test 142');
test(isCircularSentence("a b c d e f g h i j k l m n o p q r s t u v w x y z a"), false, 'Test 143');
test(isCircularSentence("solo ollas solar lassos"), false, 'Test 144');
test(isCircularSentence("madamrefer"), false, 'Test 145');
test(isCircularSentence("civic racecar level madam deed rotator redivider"), false, 'Test 146');
test(isCircularSentence("Tactocat civic"), false, 'Test 147');
test(isCircularSentence("Xylophones yield xenial xylophiles"), false, 'Test 148');
test(isCircularSentence("civic deed level civic civic"), false, 'Test 149');
test(isCircularSentence("Underground neutergnu"), false, 'Test 150');
test(isCircularSentence("rotor"), true, 'Test 151');
test(isCircularSentence("racecar"), true, 'Test 152');
test(isCircularSentence("singleword"), false, 'Test 153');
test(isCircularSentence("zoo ooz zoo"), false, 'Test 154');
test(isCircularSentence("redder redivider redivider"), true, 'Test 155');
test(isCircularSentence("xylophone one phone nova ava axolotl talontax"), false, 'Test 156');
test(isCircularSentence("ab ac ad ae af ag ah ai aj ak al am an ao ap aq ar as at au av aw ax ay az"), false, 'Test 157');
test(isCircularSentence("kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak kayak"), true, 'Test 158');
test(isCircularSentence("a aa aaaa a"), true, 'Test 159');
test(isCircularSentence("Mushroom nrooms moss stamper reaper"), false, 'Test 160');
test(isCircularSentence("daemon nomad"), true, 'Test 161');
test(isCircularSentence("AbCd DeFg GhIj JkLa"), false, 'Test 162');
test(isCircularSentence("level deed deed level"), false, 'Test 163');
test(isCircularSentence("Stressed desserts"), false, 'Test 164');
test(isCircularSentence("stats stats"), true, 'Test 165');
test(isCircularSentence("A Santa at NASA A"), false, 'Test 166');
test(isCircularSentence("civic madam racecar"), false, 'Test 167');
test(isCircularSentence("repaper repaper"), true, 'Test 168');
test(isCircularSentence("Palindrome emordnilaP el"), false, 'Test 169');
test(isCircularSentence("Able was I I saw Elba"), false, 'Test 170');
test(isCircularSentence("Programming ngRams Make sense"), false, 'Test 171');
test(isCircularSentence("Mimi"), false, 'Test 172');
test(isCircularSentence("rotor rotor rotor"), true, 'Test 173');
test(isCircularSentence("rotor rotor rotor rotor"), true, 'Test 174');
test(isCircularSentence("A Toyota tacoma玛 its a Toyota tacoma玛"), false, 'Test 175');
test(isCircularSentence("rotator rotator"), true, 'Test 176');
test(isCircularSentence("No lemon no melon No"), false, 'Test 177');
test(isCircularSentence("Step on no pets"), false, 'Test 178');
test(isCircularSentence("A Santa at NASA at a Santa A"), false, 'Test 179');
test(isCircularSentence("Was it a car or a cat I saw saw I tac a ro rac a si taW"), false, 'Test 180');
test(isCircularSentence("a aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa aaaaaaaaa aaaaaaaaaa aaaaaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaa aaaaaaaaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaa a"), true, 'Test 181');
test(isCircularSentence("redivider deified civic level rotator deed madam racecar"), false, 'Test 182');
test(isCircularSentence("a aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa aaaaaaaaa aaaaaaaaaa aaaaaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaa aaaaaaaaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaa"), true, 'Test 183');
test(isCircularSentence("level level level"), true, 'Test 184');
test(isCircularSentence("deified deified"), true, 'Test 185');
test(isCircularSentence("Circular larriuC"), false, 'Test 186');
test(isCircularSentence("Symmetry try sym"), false, 'Test 187');
test(isCircularSentence("redivider redivider"), true, 'Test 188');
test(isCircularSentence("banana apple orange emitter"), false, 'Test 189');
test(isCircularSentence("reviled devil"), false, 'Test 190');
test(isCircularSentence("abracadabra arachnid did deep peeled Elba bar"), false, 'Test 191');
test(isCircularSentence("civic deed civic deed"), false, 'Test 192');
test(isCircularSentence("Wow kayak wow wow wow wow wow"), false, 'Test 193');
test(isCircularSentence("Anna annA"), true, 'Test 194');
test(isCircularSentence("Never odd or even"), false, 'Test 195');
test(isCircularSentence("Nurses run"), false, 'Test 196');
test(isCircularSentence("aaaaa aaaaa aaaaa"), true, 'Test 197');
test(isCircularSentence("A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A"), false, 'Test 198');
test(isCircularSentence("Zebra apple orchid night eagle"), false, 'Test 199');
test(isCircularSentence("repaid diaper"), true, 'Test 200');
test(isCircularSentence("Abc bcd def efg gfa"), false, 'Test 201');
test(isCircularSentence("Abc cba abc"), false, 'Test 202');
test(isCircularSentence("a a a a a a a a a a"), true, 'Test 203');
test(isCircularSentence("banana apple orange nice East West"), false, 'Test 204');
test(isCircularSentence("Python nohtyP"), true, 'Test 205');
test(isCircularSentence("Palindrome emordnilaP ndromePal"), false, 'Test 206');
test(isCircularSentence("a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a"), true, 'Test 207');
test(isCircularSentence("Cycle elc yc"), false, 'Test 208');
test(isCircularSentence("algorithm nom alg"), false, 'Test 209');
test(isCircularSentence("Anna annA annA"), false, 'Test 210');
test(isCircularSentence("Twisted tales weave intricate stories"), false, 'Test 211');
test(isCircularSentence("civic civic civic"), true, 'Test 212');
test(isCircularSentence("Rotor rotor"), false, 'Test 213');
test(isCircularSentence("Zoology yggdrasill lloisgoy zoo"), false, 'Test 214');
test(isCircularSentence("coding ngoding going on"), false, 'Test 215');
test(isCircularSentence("repaid repaid"), false, 'Test 216');
test(isCircularSentence("Data analytics sscientist teach harsh"), false, 'Test 217');
test(isCircularSentence("AB BA CA"), false, 'Test 218');
test(isCircularSentence("Mamad Madam Damda"), false, 'Test 219');
test(isCircularSentence("abacabadabacaba"), true, 'Test 220');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

