// Test: 14. Longest Common Prefix
// 148 test cases from LeetCodeDataset
// Run: node test.js

const { longestCommonPrefix } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n14. Longest Common Prefix\n");

test(longestCommonPrefix(["hello","helium","helper"]), hel, 'Test 1');
test(longestCommonPrefix(["a"]), a, 'Test 2');
test(longestCommonPrefix(["","","",""]), , 'Test 3');
test(longestCommonPrefix(["apple","app","apricot"]), ap, 'Test 4');
test(longestCommonPrefix(["abcd","abce","abcf"]), abc, 'Test 5');
test(longestCommonPrefix(["apple","app","application"]), app, 'Test 6');
test(longestCommonPrefix(["interview","interrupt","inter"]), inter, 'Test 7');
test(longestCommonPrefix(["test","testing","tester"]), test, 'Test 8');
test(longestCommonPrefix(["hello","hell","hella"]), hell, 'Test 9');
test(longestCommonPrefix(["flower","flow","flight"]), fl, 'Test 10');
test(longestCommonPrefix(["same","same","same"]), same, 'Test 11');
test(longestCommonPrefix(["single"]), single, 'Test 12');
test(longestCommonPrefix(["ab","abc","abcd"]), ab, 'Test 13');
test(longestCommonPrefix(["abc","abc","abc"]), abc, 'Test 14');
test(longestCommonPrefix(["abcd","dcba","abdc"]), , 'Test 15');
test(longestCommonPrefix(["","b","abc"]), , 'Test 16');
test(longestCommonPrefix(["a","ab","abc"]), a, 'Test 17');
test(longestCommonPrefix(["dog","racecar","car"]), , 'Test 18');
test(longestCommonPrefix(["a","a","a","a"]), a, 'Test 19');
test(longestCommonPrefix(["","","abc"]), , 'Test 20');
test(longestCommonPrefix(["abc","abcd","abcde"]), abc, 'Test 21');
test(longestCommonPrefix(["abcd","abc","ab","a"]), a, 'Test 22');
test(longestCommonPrefix(["banana","bandana","banner"]), ban, 'Test 23');
test(longestCommonPrefix(["aaaa","aaab","aaac"]), aaa, 'Test 24');
test(longestCommonPrefix(["mississippi","mississauga","mission","missed"]), miss, 'Test 25');
test(longestCommonPrefix(["commonality","commonwealth","common","commons"]), common, 'Test 26');
test(longestCommonPrefix(["different","prefixes","here"]), , 'Test 27');
test(longestCommonPrefix(["repetition","repetitive","repeat","repel","repeal","repetend"]), repe, 'Test 28');
test(longestCommonPrefix(["million","millionaire","millionth","millionfold"]), million, 'Test 29');
test(longestCommonPrefix(["algorithm","algorithmic","algebra","alignment"]), al, 'Test 30');
test(longestCommonPrefix(["difficult","difficulty","differ"]), diff, 'Test 31');
test(longestCommonPrefix(["environment","environmental","envision","enzyme"]), en, 'Test 32');
test(longestCommonPrefix(["a","aa","aaa","aaaa"]), a, 'Test 33');
test(longestCommonPrefix(["xylophone","xylotomy","xylography","xylograph"]), xylo, 'Test 34');
test(longestCommonPrefix(["a","aa","aaa","aaaa","aaaaa"]), a, 'Test 35');
test(longestCommonPrefix(["abcde","abc","ab","a","abcde"]), a, 'Test 36');
test(longestCommonPrefix(["unique","unit","universe","unity","un"]), un, 'Test 37');
test(longestCommonPrefix(["same","same","same","same"]), same, 'Test 38');
test(longestCommonPrefix(["abcdef","abcde","abcd","abc","ab","a"]), a, 'Test 39');
test(longestCommonPrefix(["short","small","shallow","shrink"]), s, 'Test 40');
test(longestCommonPrefix(["zebra","zoo","zenith","zest","zone","zephyr"]), z, 'Test 41');
test(longestCommonPrefix(["multidimensional","multidimensionalities","multidimensionally","multidimensionalization"]), multidimensional, 'Test 42');
test(longestCommonPrefix(["computation","compute","computer","comedy"]), com, 'Test 43');
test(longestCommonPrefix(["abcd","ab","a","abcde"]), a, 'Test 44');
test(longestCommonPrefix(["abcde","abcdf","abcde","abcda","abcde","abcdf"]), abcd, 'Test 45');
test(longestCommonPrefix(["zebra","zoo","zealot"]), z, 'Test 46');
test(longestCommonPrefix(["abcd","abcde","ab","a"]), a, 'Test 47');
test(longestCommonPrefix(["microphone","microwave","microscope","microbial"]), micro, 'Test 48');
test(longestCommonPrefix(["longest","long","lonely"]), lon, 'Test 49');
test(longestCommonPrefix(["prefix","preprocessor","prevent"]), pre, 'Test 50');
test(longestCommonPrefix(["algorithm","algorithmically","","algorithmic"]), , 'Test 51');
test(longestCommonPrefix(["algorithm","alert","alibaba","allied"]), al, 'Test 52');
test(longestCommonPrefix(["unbelievable","unbeliever","unbelievably","unbelievability"]), unbeliev, 'Test 53');
test(longestCommonPrefix(["prefix","preposition","prevent","premier"]), pre, 'Test 54');
test(longestCommonPrefix(["prefix","prefixes","prefixation","prefixed"]), prefix, 'Test 55');
test(longestCommonPrefix(["a","b","c","d"]), , 'Test 56');
test(longestCommonPrefix(["","same","same","same","same"]), , 'Test 57');
test(longestCommonPrefix(["same","same","same","same","same"]), same, 'Test 58');
test(longestCommonPrefix(["optimization","optimization","optimized","optimizer"]), optimiz, 'Test 59');
test(longestCommonPrefix(["communication","communicate","commune","communist"]), commun, 'Test 60');
test(longestCommonPrefix(["a","ab","abc","abcd","abcde","abcdef"]), a, 'Test 61');
test(longestCommonPrefix(["algorithm","algorithmically","algebra","allegro"]), al, 'Test 62');
test(longestCommonPrefix(["common","commotion","communicate","community"]), comm, 'Test 63');
test(longestCommonPrefix(["flower","flow","flight","flew","flying","flowing"]), fl, 'Test 64');
test(longestCommonPrefix(["single","singlehandedly","singlemindedness","singlehanded"]), single, 'Test 65');
test(longestCommonPrefix(["algorithm","algebra","alaska"]), al, 'Test 66');
test(longestCommonPrefix(["congratulations","congruity","congruent"]), congr, 'Test 67');
test(longestCommonPrefix(["a","ab","abc","abcd"]), a, 'Test 68');
test(longestCommonPrefix(["algorithm","algorithmic","algorithmically","algorithmically"]), algorithm, 'Test 69');
test(longestCommonPrefix(["preference","prefix","prevent","prey"]), pre, 'Test 70');
test(longestCommonPrefix(["abracadabra","abracadabras","abracadabaster","abracadabration"]), abracadab, 'Test 71');
test(longestCommonPrefix(["supercalifragilisticexpialidocious","super","supersonic"]), super, 'Test 72');
test(longestCommonPrefix(["unanimity","unanimous","unanimously","unanimated"]), unanim, 'Test 73');
test(longestCommonPrefix(["orthogonal","orthodox","orthopedic","orthography"]), ortho, 'Test 74');
test(longestCommonPrefix(["abcd","abcde","abcdef","abcdefg"]), abcd, 'Test 75');
test(longestCommonPrefix(["programming","programmer","programmatic","program"]), program, 'Test 76');
test(longestCommonPrefix(["sequential","sequence","sequent","sequel"]), seque, 'Test 77');
test(longestCommonPrefix(["abracadabra","abr","abracadabrador","abrac"]), abr, 'Test 78');
test(longestCommonPrefix(["consistent","consistency","consistently","consist"]), consist, 'Test 79');
test(longestCommonPrefix(["common","community","comma","communist"]), comm, 'Test 80');
test(longestCommonPrefix(["zebra","zoo","zealot","zest"]), z, 'Test 81');
test(longestCommonPrefix(["a","a","a","a","a"]), a, 'Test 82');
test(longestCommonPrefix(["algorithm","algebra","altitude","altimeter"]), al, 'Test 83');
test(longestCommonPrefix(["supercalifragilisticexpialidocious","super","supercal"]), super, 'Test 84');
test(longestCommonPrefix(["maximum","maximize","maximal"]), maxim, 'Test 85');
test(longestCommonPrefix(["complex","complicated","complect","complete"]), compl, 'Test 86');
test(longestCommonPrefix(["prefix","pre","preface","prefer","preference","prefixing"]), pre, 'Test 87');
test(longestCommonPrefix(["abcd","abcde","abcdef","abcdefg","abcdefgh","abcdefghi"]), abcd, 'Test 88');
test(longestCommonPrefix(["abcdefghij","abcdefgh","abcdefg","abcdef","abcde","abcd","abc","ab","a"]), a, 'Test 89');
test(longestCommonPrefix(["abcde","abcde","abcde","abcde"]), abcde, 'Test 90');
test(longestCommonPrefix(["algorithm","algorhythm","algae"]), alg, 'Test 91');
test(longestCommonPrefix(["","","","","a"]), , 'Test 92');
test(longestCommonPrefix(["xylophone","xylography","xylogen","xylophonist"]), xylo, 'Test 93');
test(longestCommonPrefix(["onomatopoeia","onomatopoetic","onomatope","onomatologist"]), onomato, 'Test 94');
test(longestCommonPrefix(["rehabilitation","rehabilitate","rehabilitative","rehabilitated"]), rehabilitat, 'Test 95');
test(longestCommonPrefix(["mississippi","missile","mission","missive"]), missi, 'Test 96');
test(longestCommonPrefix(["longest","longevity","longitudinal"]), long, 'Test 97');
test(longestCommonPrefix(["psychological","psychologist","psychology","psychic"]), psych, 'Test 98');
test(longestCommonPrefix(["environment","envelope","envoy","evening"]), e, 'Test 99');
test(longestCommonPrefix(["short","shorthand","shortfall"]), short, 'Test 100');
test(longestCommonPrefix(["parallel","parallelogram","parallactic","paralactic"]), paral, 'Test 101');
test(longestCommonPrefix(["cryptography","cryptographic","cryptanalysis","cryptanalytic"]), crypt, 'Test 102');
test(longestCommonPrefix(["zebra","zoo","zero","zapper"]), z, 'Test 103');
test(longestCommonPrefix(["singleword","single","singleton"]), single, 'Test 104');
test(longestCommonPrefix(["anthropomorphic","anthropologist","anthropology","anthropocentric"]), anthropo, 'Test 105');
test(longestCommonPrefix(["","","","a"]), , 'Test 106');
test(longestCommonPrefix(["a","ab","abc","abcd","abcde"]), a, 'Test 107');
test(longestCommonPrefix(["common","commune","command","community"]), comm, 'Test 108');
test(longestCommonPrefix(["same","samsung","sample","sand","satellite","saturn"]), sa, 'Test 109');
test(longestCommonPrefix(["algorithm","algebra","altitude"]), al, 'Test 110');
test(longestCommonPrefix(["implementation","implement","implementing","implementor"]), implement, 'Test 111');
test(longestCommonPrefix(["abracadabra","abracadabra","abracadabra"]), abracadabra, 'Test 112');
test(longestCommonPrefix(["reorganization","reorganize","reorganized","reorganizing"]), reorganiz, 'Test 113');
test(longestCommonPrefix(["university","universe","unique","unicorn"]), uni, 'Test 114');
test(longestCommonPrefix(["","longest","longevity","logistics"]), , 'Test 115');
test(longestCommonPrefix(["","","","abc"]), , 'Test 116');
test(longestCommonPrefix(["environment","envy","envelop","enviable"]), env, 'Test 117');
test(longestCommonPrefix(["unique","unicorn","unify","unity"]), uni, 'Test 118');
test(longestCommonPrefix(["aabbcc","aabbc","aabb","aab","aa"]), aa, 'Test 119');
test(longestCommonPrefix(["zebra","zoo","zeal","zither"]), z, 'Test 120');
test(longestCommonPrefix(["","a","ab","abc","abcd"]), , 'Test 121');
test(longestCommonPrefix(["aardvark","aardwolf","aardvark","aard"]), aard, 'Test 122');
test(longestCommonPrefix(["zzzzzzzz","zzzzz","zzzz","zzz","zz","z"]), z, 'Test 123');
test(longestCommonPrefix(["separation","separately","separated","separating"]), separat, 'Test 124');
test(longestCommonPrefix(["mississippi","missile","mission","miss"]), miss, 'Test 125');
test(longestCommonPrefix(["algorithm","algebra","alien","alert"]), al, 'Test 126');
test(longestCommonPrefix(["commonality","common","commune","community","communicate","commemorative"]), comm, 'Test 127');
test(longestCommonPrefix(["supercalifragilisticexpialidocious","supercalifragilistic","supercalifragili","super"]), super, 'Test 128');
test(longestCommonPrefix(["parallel","parallelepiped","paralleled","paralegal"]), paral, 'Test 129');
test(longestCommonPrefix(["prefix","preference","presentation"]), pre, 'Test 130');
test(longestCommonPrefix(["unified","uniform","universe","unique"]), uni, 'Test 131');
test(longestCommonPrefix(["anagram","anagrams","anagrammatic","anagrammatical"]), anagram, 'Test 132');
test(longestCommonPrefix(["environment","environmental","environments","environmentally"]), environment, 'Test 133');
test(longestCommonPrefix(["xylophone","xylography","xylophonist","xylophonics"]), xylo, 'Test 134');
test(longestCommonPrefix(["prefix","","prefix","prefix"]), , 'Test 135');
test(longestCommonPrefix(["algorithm","algebra","altimeter"]), al, 'Test 136');
test(longestCommonPrefix(["recognition","recognizable","recognize","recognizably"]), recogni, 'Test 137');
test(longestCommonPrefix(["prefix","preposition","presentation"]), pre, 'Test 138');
test(longestCommonPrefix(["challenges","challenging","challenge","challengingly"]), challeng, 'Test 139');
test(longestCommonPrefix(["universally","universe","universal","universality","universes","universally"]), univers, 'Test 140');
test(longestCommonPrefix(["mississippi","missile","missionary","misspell"]), miss, 'Test 141');
test(longestCommonPrefix(["photosynthesis","photosynthetic","photosynthesize","photosynthetically"]), photosynthe, 'Test 142');
test(longestCommonPrefix(["apple","apply","appetite","apparatus"]), app, 'Test 143');
test(longestCommonPrefix(["prefix","pretext","prevent"]), pre, 'Test 144');
test(longestCommonPrefix(["development","develop","developer","developmental","developing","devel"]), devel, 'Test 145');
test(longestCommonPrefix(["prefix","preference","presentation","president","pressure","premier"]), pre, 'Test 146');
test(longestCommonPrefix(["","unique","unanimous","unicorn","unicycle","unify"]), , 'Test 147');
test(longestCommonPrefix(["complex","complicated","completion"]), compl, 'Test 148');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

