// Test: 214. Shortest Palindrome
// 157 test cases from LeetCodeDataset
// Run: node test.js

const { shortestPalindrome } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n214. Shortest Palindrome\n");

test(shortestPalindrome("abcba"), abcba, 'Test 1');
test(shortestPalindrome("madam"), madam, 'Test 2');
test(shortestPalindrome("abcdefghijklmnopqrstuvwxyz"), zyxwvutsrqponmlkjihgfedcbabcdefghijklmnopqrstuvwxyz, 'Test 3');
test(shortestPalindrome("abac"), cabac, 'Test 4');
test(shortestPalindrome("zxcvbnm"), mnbvcxzxcvbnm, 'Test 5');
test(shortestPalindrome("aabbaa"), aabbaa, 'Test 6');
test(shortestPalindrome("abcdcba"), abcdcba, 'Test 7');
test(shortestPalindrome("aaaaa"), aaaaa, 'Test 8');
test(shortestPalindrome("a"), a, 'Test 9');
test(shortestPalindrome("abcabcabc"), cbacbacbabcabcabc, 'Test 10');
test(shortestPalindrome("step"), petstep, 'Test 11');
test(shortestPalindrome("abacdfgdcaba"), abacdgfdcabacdfgdcaba, 'Test 12');
test(shortestPalindrome("ab"), bab, 'Test 13');
test(shortestPalindrome(""), , 'Test 14');
test(shortestPalindrome("abcde"), edcbabcde, 'Test 15');
test(shortestPalindrome("abcabc"), cbacbabcabc, 'Test 16');
test(shortestPalindrome("rotor"), rotor, 'Test 17');
test(shortestPalindrome("aabb"), bbaabb, 'Test 18');
test(shortestPalindrome("racecar"), racecar, 'Test 19');
test(shortestPalindrome("aacecaaa"), aaacecaaa, 'Test 20');
test(shortestPalindrome("aabba"), abbaabba, 'Test 21');
test(shortestPalindrome("abba"), abba, 'Test 22');
test(shortestPalindrome("race"), ecarace, 'Test 23');
test(shortestPalindrome("noon"), noon, 'Test 24');
test(shortestPalindrome("banana"), ananabanana, 'Test 25');
test(shortestPalindrome("deeee"), eeeedeeee, 'Test 26');
test(shortestPalindrome("zzazzacca"), accazzazzacca, 'Test 27');
test(shortestPalindrome("abcd"), dcbabcd, 'Test 28');
test(shortestPalindrome("aba"), aba, 'Test 29');
test(shortestPalindrome("abbacd"), dcabbacd, 'Test 30');
test(shortestPalindrome("level"), level, 'Test 31');
test(shortestPalindrome("zyxwvutsrqponmlkjihgfedcba"), abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba, 'Test 32');
test(shortestPalindrome("aabbaab"), baabbaab, 'Test 33');
test(shortestPalindrome("aabbaca"), acabbaabbaca, 'Test 34');
test(shortestPalindrome("aabbccddeeeffgg"), ggffeeeddccbbaabbccddeeeffgg, 'Test 35');
test(shortestPalindrome("noonappo"), oppanoonappo, 'Test 36');
test(shortestPalindrome("abacabadabacabadabacaba"), abacabadabacabadabacaba, 'Test 37');
test(shortestPalindrome("repaperrepaper"), repaperrepaper, 'Test 38');
test(shortestPalindrome("xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyx"), xyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyx, 'Test 39');
test(shortestPalindrome("abracadabra"), arbadacarbabracadabra, 'Test 40');
test(shortestPalindrome("rotorrotor"), rotorrotor, 'Test 41');
test(shortestPalindrome("zzzz"), zzzz, 'Test 42');
test(shortestPalindrome("abbaa"), aabbaa, 'Test 43');
test(shortestPalindrome("zazazz"), zzazazz, 'Test 44');
test(shortestPalindrome("aaaabaaaa"), aaaabaaaa, 'Test 45');
test(shortestPalindrome("noonnoon"), noonnoon, 'Test 46');
test(shortestPalindrome("aabbccddeeefffgg"), ggfffeeeddccbbaabbccddeeefffgg, 'Test 47');
test(shortestPalindrome("repaid"), diaperepaid, 'Test 48');
test(shortestPalindrome("algorithm"), mhtiroglalgorithm, 'Test 49');
test(shortestPalindrome("ananabanana"), ananabanana, 'Test 50');
test(shortestPalindrome("hello"), ollehello, 'Test 51');
test(shortestPalindrome("abcdecba"), abcedcbabcdecba, 'Test 52');
test(shortestPalindrome("redder"), redder, 'Test 53');
test(shortestPalindrome("qwertyuiop"), poiuytrewqwertyuiop, 'Test 54');
test(shortestPalindrome("noonnoonnoonnoon"), noonnoonnoonnoon, 'Test 55');
test(shortestPalindrome("deeeeffffgggggggggggggggggggggggggggggggg"), ggggggggggggggggggggggggggggggggffffeeeedeeeeffffgggggggggggggggggggggggggggggggg, 'Test 56');
test(shortestPalindrome("abcdabc"), cbadcbabcdabc, 'Test 57');
test(shortestPalindrome("mississippimississippi"), ippississimippississimississippimississippi, 'Test 58');
test(shortestPalindrome("aabbccddeee"), eeeddccbbaabbccddeee, 'Test 59');
test(shortestPalindrome("xyzzyx"), xyzzyx, 'Test 60');
test(shortestPalindrome("abcdefghihgfedcbabc"), cbabcdefghihgfedcbabc, 'Test 61');
test(shortestPalindrome("abca"), acbabca, 'Test 62');
test(shortestPalindrome("bba"), abba, 'Test 63');
test(shortestPalindrome("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, 'Test 64');
test(shortestPalindrome("abbae"), eabbae, 'Test 65');
test(shortestPalindrome("repaperandmorepaperrepaperandmorepaper"), repaperomdnarepaperrepaperomdnarepaperandmorepaperrepaperandmorepaper, 'Test 66');
test(shortestPalindrome("algorhythmhmorthygrola"), alorgyhtromhmhtyhroglalgorhythmhmorthygrola, 'Test 67');
test(shortestPalindrome("palindrome"), emordnilapalindrome, 'Test 68');
test(shortestPalindrome("abacaxi"), ixacabacaxi, 'Test 69');
test(shortestPalindrome("kayak"), kayak, 'Test 70');
test(shortestPalindrome("abab"), babab, 'Test 71');
test(shortestPalindrome("aabbccddeeefffhhh"), hhhfffeeeddccbbaabbccddeeefffhhh, 'Test 72');
test(shortestPalindrome("aabbbaaa"), aaabbbaaa, 'Test 73');
test(shortestPalindrome("xyxz"), zxyxz, 'Test 74');
test(shortestPalindrome("abcdefghihgfedcbabcd"), dcbabcdefghihgfedcbabcd, 'Test 75');
test(shortestPalindrome("aabbccddeeefffggghhh"), hhhgggfffeeeddccbbaabbccddeeefffggghhh, 'Test 76');
test(shortestPalindrome("qwertyuiopasdfghjklzxcvbnm"), mnbvcxzlkjhgfdsapoiuytrewqwertyuiopasdfghjklzxcvbnm, 'Test 77');
test(shortestPalindrome("levelup"), pulevelup, 'Test 78');
test(shortestPalindrome("raceacar"), racaecaraceacar, 'Test 79');
test(shortestPalindrome("levelupandnevergiveup"), puevigrevendnapulevelupandnevergiveup, 'Test 80');
test(shortestPalindrome("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz"), zzzzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz, 'Test 81');
test(shortestPalindrome("abcdeedcba"), abcdeedcba, 'Test 82');
test(shortestPalindrome("leveler"), releveler, 'Test 83');
test(shortestPalindrome("xyzzyxw"), wxyzzyxw, 'Test 84');
test(shortestPalindrome("abcbae"), eabcbae, 'Test 85');
test(shortestPalindrome("aabbccddeeeff"), ffeeeddccbbaabbccddeeeff, 'Test 86');
test(shortestPalindrome("abcdeffedcba"), abcdeffedcba, 'Test 87');
test(shortestPalindrome("deeeeffffgggg"), ggggffffeeeedeeeeffffgggg, 'Test 88');
test(shortestPalindrome("levellevel"), levellevel, 'Test 89');
test(shortestPalindrome("aabbccddeeefffhhhiiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"), zzyyxxwwvvuuttssrrqqppoonnmmllkkjjiiihhhfffeeeddccbbaabbccddeeefffhhhiiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz, 'Test 90');
test(shortestPalindrome("zyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyz"), zyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyz, 'Test 91');
test(shortestPalindrome("aabcd"), dcbaabcd, 'Test 92');
test(shortestPalindrome("abcdefedcba"), abcdefedcba, 'Test 93');
test(shortestPalindrome("thisisnotapalindrome"), emordnilapatonsisihthisisnotapalindrome, 'Test 94');
test(shortestPalindrome("amanaplanacanalsofpnmala"), alamnpfoslanacanalpanamanaplanacanalsofpnmala, 'Test 95');
test(shortestPalindrome("xyzzzzzzzzzzzzzzzzzyx"), xyzzzzzzzzzzzzzzzzzyx, 'Test 96');
test(shortestPalindrome("aeroplaneeplanar"), ranalpeenalporeaeroplaneeplanar, 'Test 97');
test(shortestPalindrome("aaaaabbaaaaa"), aaaaabbaaaaa, 'Test 98');
test(shortestPalindrome("abcdefghijk"), kjihgfedcbabcdefghijk, 'Test 99');
test(shortestPalindrome("abababab"), babababab, 'Test 100');
test(shortestPalindrome("abcdefghihgfedcbaa"), aabcdefghihgfedcbaa, 'Test 101');
test(shortestPalindrome("abacabadabacaba"), abacabadabacaba, 'Test 102');
test(shortestPalindrome("abababa"), abababa, 'Test 103');
test(shortestPalindrome("bananaananab"), bananaananab, 'Test 104');
test(shortestPalindrome("ananabananabana"), anabananabananabana, 'Test 105');
test(shortestPalindrome("rotator"), rotator, 'Test 106');
test(shortestPalindrome("redderredder"), redderredder, 'Test 107');
test(shortestPalindrome("aabbccddeeefffgghhiiijjjkkllmmnnooppqqrrssttuuvvwwxxyyzz"), zzyyxxwwvvuuttssrrqqppoonnmmllkkjjjiiihhggfffeeeddccbbaabbccddeeefffgghhiiijjjkkllmmnnooppqqrrssttuuvvwwxxyyzz, 'Test 108');
test(shortestPalindrome("xyzabcxyzabc"), cbazyxcbazyxyzabcxyzabc, 'Test 109');
test(shortestPalindrome("world"), dlroworld, 'Test 110');
test(shortestPalindrome("abcbabcba"), abcbabcba, 'Test 111');
test(shortestPalindrome("abcbad"), dabcbad, 'Test 112');
test(shortestPalindrome("aabbccddeeefffhhhiijj"), jjiihhhfffeeeddccbbaabbccddeeefffhhhiijj, 'Test 113');
test(shortestPalindrome("abcdefgh"), hgfedcbabcdefgh, 'Test 114');
test(shortestPalindrome("civiccivic"), civiccivic, 'Test 115');
test(shortestPalindrome("detartrated"), detartrated, 'Test 116');
test(shortestPalindrome("racecarcar"), racracecarcar, 'Test 117');
test(shortestPalindrome("aaabaaa"), aaabaaa, 'Test 118');
test(shortestPalindrome("aabbccddeeff"), ffeeddccbbaabbccddeeff, 'Test 119');
test(shortestPalindrome("reviver"), reviver, 'Test 120');
test(shortestPalindrome("madamimadam"), madamimadam, 'Test 121');
test(shortestPalindrome("aabbccddeeefffhhhiiijjkkll"), llkkjjiiihhhfffeeeddccbbaabbccddeeefffhhhiiijjkkll, 'Test 122');
test(shortestPalindrome("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"), zzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz, 'Test 123');
test(shortestPalindrome("amanaplanacanalpanama"), amanaplanacanalpanama, 'Test 124');
test(shortestPalindrome("abcdabcba"), abcbadcbabcdabcba, 'Test 125');
test(shortestPalindrome("abcdefg"), gfedcbabcdefg, 'Test 126');
test(shortestPalindrome("aaaabbbbccccdddd"), ddddccccbbbbaaaabbbbccccdddd, 'Test 127');
test(shortestPalindrome("racecarracecar"), racecarracecar, 'Test 128');
test(shortestPalindrome("abbaab"), baabbaab, 'Test 129');
test(shortestPalindrome("deified"), deified, 'Test 130');
test(shortestPalindrome("repaper"), repaper, 'Test 131');
test(shortestPalindrome("abbaabbaabba"), abbaabbaabba, 'Test 132');
test(shortestPalindrome("abcdef"), fedcbabcdef, 'Test 133');
test(shortestPalindrome("zzzzy"), yzzzzy, 'Test 134');
test(shortestPalindrome("abcdedcba"), abcdedcba, 'Test 135');
test(shortestPalindrome("xyzzzzzzzyx"), xyzzzzzzzyx, 'Test 136');
test(shortestPalindrome("bbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, 'Test 137');
test(shortestPalindrome("qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm"), mnbvcxzlkjhgfdsapoiuytrewqmnbvcxzlkjhgfdsapoiuytrewqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm, 'Test 138');
test(shortestPalindrome("repaperandmorepaper"), repaperomdnarepaperandmorepaper, 'Test 139');
test(shortestPalindrome("deifieddeified"), deifieddeified, 'Test 140');
test(shortestPalindrome("abcddcba"), abcddcba, 'Test 141');
test(shortestPalindrome("civic"), civic, 'Test 142');
test(shortestPalindrome("aaaaabaaa"), aaabaaaaabaaa, 'Test 143');
test(shortestPalindrome("abcdefghihgfedcba"), abcdefghihgfedcba, 'Test 144');
test(shortestPalindrome("amanaplanacanalsofpnmalamalamalamalamal"), lamalamalamalamalamnpfoslanacanalpanamanaplanacanalsofpnmalamalamalamalamal, 'Test 145');
test(shortestPalindrome("ababababa"), ababababa, 'Test 146');
test(shortestPalindrome("aquickbrownfoxjumpsoverthelazydog"), godyzalehtrevospmujxofnworbkciuqaquickbrownfoxjumpsoverthelazydog, 'Test 147');
test(shortestPalindrome("reviled"), delivereviled, 'Test 148');
test(shortestPalindrome("levelupandnevergiveuplevelupandnevergiveup"), puevigrevendnapulevelpuevigrevendnapulevelupandnevergiveuplevelupandnevergiveup, 'Test 149');
test(shortestPalindrome("amandaplanacanalpanama"), amanaplanacanalpadnamandaplanacanalpanama, 'Test 150');
test(shortestPalindrome("aabbcc"), ccbbaabbcc, 'Test 151');
test(shortestPalindrome("mississippi"), ippississimississippi, 'Test 152');
test(shortestPalindrome("aeroplane"), enalporeaeroplane, 'Test 153');
test(shortestPalindrome("deed"), deed, 'Test 154');
test(shortestPalindrome("xyxzyzyx"), xyzyzxyxzyzyx, 'Test 155');
test(shortestPalindrome("xyzabc"), cbazyxyzabc, 'Test 156');
test(shortestPalindrome("refer"), refer, 'Test 157');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

