// Test: 3407. Substring Matching Pattern
// 209 test cases from LeetCodeDataset
// Run: node test.js

const { hasMatch } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n3407. Substring Matching Pattern\n");

test(hasMatch("abcdefg", "a*d*g"), true, 'Test 1');
test(hasMatch("mississippi", "m*ss*"), true, 'Test 2');
test(hasMatch("luck", "u*"), true, 'Test 3');
test(hasMatch("xy", "*"), true, 'Test 4');
test(hasMatch("leetcode", "ee*e"), true, 'Test 5');
test(hasMatch("testcase", "te*se"), true, 'Test 6');
test(hasMatch("car", "c*v"), false, 'Test 7');
test(hasMatch("hello", "he*o"), true, 'Test 8');
test(hasMatch("a", "*a"), true, 'Test 9');
test(hasMatch("pattern", "p*ern"), true, 'Test 10');
test(hasMatch("abcdefghij", "*mnop*abcdefghij*"), false, 'Test 11');
test(hasMatch("abcdefghij", "mnop*abcdefghij"), false, 'Test 12');
test(hasMatch("complexity", "comple*ty"), true, 'Test 13');
test(hasMatch("xylophone", "x*y*l*o*p*h*o*n*e"), true, 'Test 14');
test(hasMatch("abcdefghij", "*mnop*abcdefghij*kl*"), false, 'Test 15');
test(hasMatch("abracadabra", "*bra*bra"), true, 'Test 16');
test(hasMatch("abcdefghijk", "abcdefgh*i*j*k"), true, 'Test 17');
test(hasMatch("abcd", "a*d"), true, 'Test 18');
test(hasMatch("abcdefghij", "a*bcd*efghij"), true, 'Test 19');
test(hasMatch("abcdefghij", "abcdefgh*ij*"), true, 'Test 20');
test(hasMatch("xylophone", "xyloph*one"), true, 'Test 21');
test(hasMatch("abcdef", "a*b*c*d*e*f"), true, 'Test 22');
test(hasMatch("algorithm", "a*th*"), true, 'Test 23');
test(hasMatch("xylophone", "xylo*phne"), false, 'Test 24');
test(hasMatch("abcdef", "ab*ef"), true, 'Test 25');
test(hasMatch("abcdefghi", "abcdefgh*i"), true, 'Test 26');
test(hasMatch("abcdefghij", "mnop*ijkl*abcdefg"), false, 'Test 27');
test(hasMatch("substitution", "sub*sti*"), true, 'Test 28');
test(hasMatch("abcdefghij", "*abcdefghij*"), true, 'Test 29');
test(hasMatch("substring", "su*b*ng"), true, 'Test 30');
test(hasMatch("abcdefghijk", "*bc*ef*hi*j"), true, 'Test 31');
test(hasMatch("mississippi", "mis*ss*"), true, 'Test 32');
test(hasMatch("boundary", "bound*ry"), true, 'Test 33');
test(hasMatch("abcdefghijk", "a*bcdefghijk"), true, 'Test 34');
test(hasMatch("aaaaaaa", "a*a"), true, 'Test 35');
test(hasMatch("xylophone", "xylo*"), true, 'Test 36');
test(hasMatch("abcdef", "*"), true, 'Test 37');
test(hasMatch("abcdefghijk", "a*d*f*h*j"), true, 'Test 38');
test(hasMatch("sequence", "*e*n*ce"), true, 'Test 39');
test(hasMatch("abcdefghi", "abcd*ef*gh*i"), true, 'Test 40');
test(hasMatch("racecar", "r*ecar"), true, 'Test 41');
test(hasMatch("patternmatching", "pa*t*ern"), true, 'Test 42');
test(hasMatch("abcdefghij", "*mnop*ijkl*abcdefg*"), false, 'Test 43');
test(hasMatch("xylophone", "*phone"), true, 'Test 44');
test(hasMatch("interviewquestion", "inte*r*view*q*stion"), true, 'Test 45');
test(hasMatch("depthfirstsearch", "dep*h*f*st*s*"), true, 'Test 46');
test(hasMatch("banana", "*n*na"), true, 'Test 47');
test(hasMatch("fibonacci", "fi*b*oc*nn*i"), false, 'Test 48');
test(hasMatch("xylophone", "xyloph*"), true, 'Test 49');
test(hasMatch("abcdefghij", "abcdef*ghij*"), true, 'Test 50');
test(hasMatch("abcdexyz", "abc*d*yz"), true, 'Test 51');
test(hasMatch("datastructures", "d*ta*s*"), true, 'Test 52');
test(hasMatch("mississippi", "m*ss*i*pi"), true, 'Test 53');
test(hasMatch("abcdefghij", "a*b*cd*ef*gh*ij"), true, 'Test 54');
test(hasMatch("mississippi", "m*ss*si*pp*i"), true, 'Test 55');
test(hasMatch("abcdefghij", "a*ef*i*j"), true, 'Test 56');
test(hasMatch("abcdefghijk", "abcdefghijk*"), true, 'Test 57');
test(hasMatch("floydwarshall", "fl*oyd*w*rsh*ll"), true, 'Test 58');
test(hasMatch("abcdefghij", "abcdefghij*kl*"), false, 'Test 59');
test(hasMatch("xylophone", "x*loph*ne"), true, 'Test 60');
test(hasMatch("xylophone", "*"), true, 'Test 61');
test(hasMatch("longestcommonsubsequence", "long*st*c*m*n*s*b*s*q*nce"), true, 'Test 62');
test(hasMatch("shortestpath", "sh*rt*st*p*th"), true, 'Test 63');
test(hasMatch("abcdefghij", "a*b*c*d*e*f*g*h*i*j*"), true, 'Test 64');
test(hasMatch("substring", "su*ng"), true, 'Test 65');
test(hasMatch("matching", "ma*tching"), true, 'Test 66');
test(hasMatch("dynamicprogramming", "dyn*mic*"), true, 'Test 67');
test(hasMatch("topologicalsort", "t*p*l*g*cal*s*rt"), true, 'Test 68');
test(hasMatch("abcdefghij", "*abcdefg*ijkl*mnop*"), false, 'Test 69');
test(hasMatch("matchmaking", "ma*ing"), true, 'Test 70');
test(hasMatch("abcdefg", "*efg"), true, 'Test 71');
test(hasMatch("abcdefghij", "abcdefghij*mnop*"), false, 'Test 72');
test(hasMatch("abcdefghijk", "abcdefghij*k"), true, 'Test 73');
test(hasMatch("xylophone", "xy*"), true, 'Test 74');
test(hasMatch("mississippi", "m*ss*pp"), true, 'Test 75');
test(hasMatch("abcdefghij", "a*bcdefgh*i*j"), true, 'Test 76');
test(hasMatch("xylophone", "xy*ph*ne"), true, 'Test 77');
test(hasMatch("dynamicprogramming", "dy*n*ic*m*"), true, 'Test 78');
test(hasMatch("hellohello", "he*lo*he*lo"), true, 'Test 79');
test(hasMatch("xylophone", "x*y"), true, 'Test 80');
test(hasMatch("abcdefghij", "a*ij"), true, 'Test 81');
test(hasMatch("substring", "*string"), true, 'Test 82');
test(hasMatch("xylophone", "xy*l*ph*ne"), true, 'Test 83');
test(hasMatch("xyzzyx", "x*z*y"), true, 'Test 84');
test(hasMatch("abcdefghij", "*mnopabcdefghij"), false, 'Test 85');
test(hasMatch("substitution", "sub*sti*t*ion"), true, 'Test 86');
test(hasMatch("interviewquestion", "int*viewq*"), true, 'Test 87');
test(hasMatch("abcdefg", "abcd*fg"), true, 'Test 88');
test(hasMatch("abcdefghijk", "abc*efg*ijk"), true, 'Test 89');
test(hasMatch("abcdefghijk", "a*d*f*h*j*k"), true, 'Test 90');
test(hasMatch("programming", "pro*amm*ng"), true, 'Test 91');
test(hasMatch("mississippi", "mi*s*ippi"), true, 'Test 92');
test(hasMatch("xylophone", "xylo*p*ne"), true, 'Test 93');
test(hasMatch("algorithm", "*rith*"), true, 'Test 94');
test(hasMatch("xylophone", "xylo*ph*"), true, 'Test 95');
test(hasMatch("xylophone", "x*y*"), true, 'Test 96');
test(hasMatch("abcdefgh", "a*d*gh"), true, 'Test 97');
test(hasMatch("theskyisblue", "the*sky*"), true, 'Test 98');
test(hasMatch("transitiveclosure", "tr*ns*t*v*c*l*sr*e"), false, 'Test 99');
test(hasMatch("abcdefghij", "a*ef*i*j*"), true, 'Test 100');
test(hasMatch("abracadabra", "a*bra*"), true, 'Test 101');
test(hasMatch("abcdefghi", "abc*"), true, 'Test 102');
test(hasMatch("abcd", "abcd*"), true, 'Test 103');
test(hasMatch("abcdefg", "*"), true, 'Test 104');
test(hasMatch("abababab", "a*b*a*b*"), true, 'Test 105');
test(hasMatch("abcdefghijk", "abc*efghij*k"), true, 'Test 106');
test(hasMatch("abcdefghij", "abcdefg*ijkl*mnop"), false, 'Test 107');
test(hasMatch("xylophone", "xy*l*phne"), false, 'Test 108');
test(hasMatch("banana", "ba*n*"), true, 'Test 109');
test(hasMatch("complexpattern", "com*pat*"), true, 'Test 110');
test(hasMatch("programming", "pr*am*"), true, 'Test 111');
test(hasMatch("xylophone", "xy*ne"), true, 'Test 112');
test(hasMatch("xyzxyzxyz", "*yzxy*z"), true, 'Test 113');
test(hasMatch("programminglanguage", "pro*ing"), true, 'Test 114');
test(hasMatch("stronglyconnectedcomponent", "str*ongly*c*nn*c*t*ed*c*mp*nt"), true, 'Test 115');
test(hasMatch("abcdefghij", "mnop*abcdefghij*kl*"), false, 'Test 116');
test(hasMatch("xylophone", "*l*phne"), false, 'Test 117');
test(hasMatch("abcdef", "abc*d*ef"), true, 'Test 118');
test(hasMatch("dynamicprogramming", "dy*na*m*i*c*p*r*mm*ng"), true, 'Test 119');
test(hasMatch("recursion", "rec*ion"), true, 'Test 120');
test(hasMatch("xylophone", "*ly*"), false, 'Test 121');
test(hasMatch("xylophone", "x*y*o*"), true, 'Test 122');
test(hasMatch("breadthfirstsearch", "b*eadth*f*st*s*"), true, 'Test 123');
test(hasMatch("abcdefghi", "a*ghi"), true, 'Test 124');
test(hasMatch("patternmatching", "pat*ern*"), true, 'Test 125');
test(hasMatch("algorithms", "algo*rith*m*s"), true, 'Test 126');
test(hasMatch("pattern", "p*t*ern"), true, 'Test 127');
test(hasMatch("abcdefghijk", "*abcdefghijk"), true, 'Test 128');
test(hasMatch("xylophone", "xy*l*o*ph*ne"), true, 'Test 129');
test(hasMatch("abcdefghij", "kl*a*b*c*d*e*f*g*h*i*j*"), false, 'Test 130');
test(hasMatch("abcdefghij", "*kl*abcdefghij*"), false, 'Test 131');
test(hasMatch("abcdefghij", "a*b*c*d*e*f*g*h*i*j*k"), false, 'Test 132');
test(hasMatch("abcdefghij", "mnopabcdefghij*"), false, 'Test 133');
test(hasMatch("abcdefghij", "kl*abcdefghij"), false, 'Test 134');
test(hasMatch("abcdefghi", "*abcdefghi"), true, 'Test 135');
test(hasMatch("abcdefghij", "*abcdefghij"), true, 'Test 136');
test(hasMatch("banana", "ba*a"), true, 'Test 137');
test(hasMatch("supercalifragilisticexpialidocious", "su*er*c*ious"), true, 'Test 138');
test(hasMatch("aaaabaaa", "a*baaa"), true, 'Test 139');
test(hasMatch("xylophone", "x*ylo*phone"), true, 'Test 140');
test(hasMatch("aaaaa", "*a"), true, 'Test 141');
test(hasMatch("abcdefg", "*bcdef"), true, 'Test 142');
test(hasMatch("abcdefg", "*cde*"), true, 'Test 143');
test(hasMatch("minimumspanningtree", "mi*n*mu*m*s*p*a*n*n*g*t*r*ee"), true, 'Test 144');
test(hasMatch("abcdefghij", "a*b*c*d*e*f*g*h*i*j*kl"), false, 'Test 145');
test(hasMatch("abcd", "a*"), true, 'Test 146');
test(hasMatch("xylophone", "*xylophone"), true, 'Test 147');
test(hasMatch("binarysearch", "bi*ary*earch"), true, 'Test 148');
test(hasMatch("xylophone", "*one"), true, 'Test 149');
test(hasMatch("abcdefghij", "*ef*i*j*"), true, 'Test 150');
test(hasMatch("abcd", "*d"), true, 'Test 151');
test(hasMatch("abcdefghij", "a*b*c*d*e*f*g*h*i*j*klmno*"), false, 'Test 152');
test(hasMatch("aaaaaaa", "aa*aa*aa"), true, 'Test 153');
test(hasMatch("xylophone", "*l*ph*ne"), true, 'Test 154');
test(hasMatch("programming", "p*mm*ng"), true, 'Test 155');
test(hasMatch("programming", "p*gram*"), true, 'Test 156');
test(hasMatch("abcdefghi", "*def*"), true, 'Test 157');
test(hasMatch("backtracking", "ba*k*t*ng"), true, 'Test 158');
test(hasMatch("abcdefghij", "a*bcdefgh*ij"), true, 'Test 159');
test(hasMatch("abcdefghijk", "abcdefgh*k*"), true, 'Test 160');
test(hasMatch("abcdefghij", "a*b*c*d*e*f*g*h*i*j"), true, 'Test 161');
test(hasMatch("programminglanguage", "pro*am*age"), true, 'Test 162');
test(hasMatch("mississippi", "mis*si"), true, 'Test 163');
test(hasMatch("aaaaa", "a*"), true, 'Test 164');
test(hasMatch("abcdefghij", "*"), true, 'Test 165');
test(hasMatch("abcdefghi", "*bcd*ef*ghi"), true, 'Test 166');
test(hasMatch("knapsack", "kn*a*ck"), true, 'Test 167');
test(hasMatch("abcd", "*abcd"), true, 'Test 168');
test(hasMatch("xylophone", "x*l*ph*ne"), true, 'Test 169');
test(hasMatch("xylophone", "xyl*phne"), false, 'Test 170');
test(hasMatch("interviewquestion", "in*t*view*q*ion"), true, 'Test 171');
test(hasMatch("xylophone", "xy*o"), true, 'Test 172');
test(hasMatch("mississippi", "mis*si*"), true, 'Test 173');
test(hasMatch("programminglanguage", "pro*ming"), true, 'Test 174');
test(hasMatch("xylophone", "xy*o*"), true, 'Test 175');
test(hasMatch("abcdefghij", "abcdef*ij"), true, 'Test 176');
test(hasMatch("abcdefghij", "abc*ef*g*i*j"), true, 'Test 177');
test(hasMatch("abcdefghij", "abcdefghij*mnop"), false, 'Test 178');
test(hasMatch("patternmatching", "pa*ern*atching"), true, 'Test 179');
test(hasMatch("xylophone", "*xy*"), true, 'Test 180');
test(hasMatch("abcdef", "*f"), true, 'Test 181');
test(hasMatch("abcdefghij", "abcdefghij*kl"), false, 'Test 182');
test(hasMatch("abcdefghij", "abcdefg*ijkl*mnop*"), false, 'Test 183');
test(hasMatch("hellohello", "he*lo*lo"), true, 'Test 184');
test(hasMatch("abcdefghijk", "a*b*c*d*e*f*g*h*i*j*k"), true, 'Test 185');
test(hasMatch("abcdefghij", "mnop*abcdefghij*klmno*"), false, 'Test 186');
test(hasMatch("xylophone", "xylo*ph*e"), true, 'Test 187');
test(hasMatch("mississippi", "mis*is*ip*"), true, 'Test 188');
test(hasMatch("abacabadabacaba", "aba*caba"), true, 'Test 189');
test(hasMatch("algorithm", "algo*rithm"), true, 'Test 190');
test(hasMatch("xylophone", "xylophone*"), true, 'Test 191');
test(hasMatch("abracadabra", "ab*bra"), true, 'Test 192');
test(hasMatch("abacaxi", "a*xi"), true, 'Test 193');
test(hasMatch("abcdef", "abcdef*"), true, 'Test 194');
test(hasMatch("banana", "b*n*a"), true, 'Test 195');
test(hasMatch("multiplication", "mu*li*c*ion"), true, 'Test 196');
test(hasMatch("abcdefg", "abc*"), true, 'Test 197');
test(hasMatch("xylophone", "x*l*phne"), false, 'Test 198');
test(hasMatch("abcdefghij", "abcdefgh*i*j"), true, 'Test 199');
test(hasMatch("abcdef", "*abcdef"), true, 'Test 200');
test(hasMatch("starburst", "s*rbust"), false, 'Test 201');
test(hasMatch("abcdef", "a*"), true, 'Test 202');
test(hasMatch("abcdefghij", "abcdefghij*"), true, 'Test 203');
test(hasMatch("backtracking", "b*ck*"), true, 'Test 204');
test(hasMatch("abcdefghijk", "a*d*h*j"), true, 'Test 205');
test(hasMatch("abcdefghijk", "*gh*i*j*"), true, 'Test 206');
test(hasMatch("algorithm", "a*th*m"), true, 'Test 207');
test(hasMatch("aquickbrownfox", "a*quick*fox"), true, 'Test 208');
test(hasMatch("abcdefghij", "*efgh*i*j"), true, 'Test 209');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

