// Test: 1160. Find Words That Can Be Formed By Characters
// 134 test cases from LeetCodeDataset
// Run: node test.js

const { countCharacters } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1160. Find Words That Can Be Formed By Characters\n");

test(countCharacters(["abcd","ab","bc","cd"], "abcd"), 10, 'Test 1');
test(countCharacters(["cat","bt","hat","tree"], "atach"), 6, 'Test 2');
test(countCharacters(["zxcvbnm","asdfghjkl","qwertyuiop"], "qwertyuiopasdfghjklzxcvbnm"), 26, 'Test 3');
test(countCharacters(["abc","def","ghi"], "abcdefghi"), 9, 'Test 4');
test(countCharacters(["xyz","zyx","wxy"], "xyzzyxw"), 9, 'Test 5');
test(countCharacters(["apple","banana","cherry"], "abc"), 0, 'Test 6');
test(countCharacters(["abc","abc","abc"], "aabbcc"), 9, 'Test 7');
test(countCharacters(["test","case","word"], "tcws"), 0, 'Test 8');
test(countCharacters(["a","b","c"], "abcde"), 3, 'Test 9');
test(countCharacters(["a","b","c"], "abcabcabc"), 3, 'Test 10');
test(countCharacters(["abcd","dcba","abcd"], "abcd"), 12, 'Test 11');
test(countCharacters(["hello","world","leetcode"], "welldonehoneyr"), 10, 'Test 12');
test(countCharacters(["zzz","yyy","xxx"], "zyxzyx"), 0, 'Test 13');
test(countCharacters(["one","two","three"], "onetwothree"), 11, 'Test 14');
test(countCharacters(["python","java","c++"], "pythjavacp"), 4, 'Test 15');
test(countCharacters(["zzz","yyy","xxx"], "zyxwvutsrqponmlkjihgfedcba"), 0, 'Test 16');
test(countCharacters(["a","b","c"], "abc"), 3, 'Test 17');
test(countCharacters(["apple","apple","apple"], "ppale"), 15, 'Test 18');
test(countCharacters(["a","aa","aaa","aaaa"], "aaaaa"), 10, 'Test 19');
test(countCharacters(["aabbcc","abc","abc"], "aabbcc"), 12, 'Test 20');
test(countCharacters(["aaa","bbb","ccc"], "aabbcc"), 0, 'Test 21');
test(countCharacters(["abcd","efgh","ijkl"], "abcdefgh"), 8, 'Test 22');
test(countCharacters(["aaa","bbb","ccc"], "abc"), 0, 'Test 23');
test(countCharacters(["apple","banana","cherry"], "abcde"), 0, 'Test 24');
test(countCharacters(["test","code","contest"], "testcode"), 8, 'Test 25');
test(countCharacters(["challenge","python","code","fun"], "nclhpgfouitay"), 9, 'Test 26');
test(countCharacters(["abcdefghijklmnopqrstuvwxyz","zyxwvutsrqponmlkjihgfedcba"], "abcdefghijklmnopqrstuvwxyz"), 52, 'Test 27');
test(countCharacters(["programming","language","python","java"], "npgmajoasrivl"), 4, 'Test 28');
test(countCharacters(["", "a", "aa", "aaa", "aaaa"], "a"), 1, 'Test 29');
test(countCharacters(["banana","ananas","panama","manana"], "anamnb"), 0, 'Test 30');
test(countCharacters(["aabb","bbcc","ccdd","ddee","eeff","ffgg","gghh","hhiijj","kkll","mmnn","oorr","ppqq","sstt","uuvv","wwxx","yyzz"], "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"), 66, 'Test 31');
test(countCharacters(["complex","words","here"], "owcpxlehre"), 4, 'Test 32');
test(countCharacters(["abcdefghijklmnopqrstuvwxyz","zyxwvutsrqponmlkjihgfedcba","abacax"], "abcdefghijklmnopqrstuvwxyz"), 52, 'Test 33');
test(countCharacters(["one","two","three","four","five","six","seven","eight","nine","ten"], "oentwfhivxsg"), 21, 'Test 34');
test(countCharacters(["xxyyzz","yyzzxx","zzxxyy"], "xyzxyz"), 18, 'Test 35');
test(countCharacters(["aabbccddeeff", "aabbccddeeffgg", "aabbccddeeffgghh", "aabbccddeeffgghhiijj"], "aabbccddeeffgghhiijj"), 62, 'Test 36');
test(countCharacters(["zzzz", "zzz", "zz", "z"], "zzzzzzzzzz"), 10, 'Test 37');
test(countCharacters(["xylophone","guitar","drum","bassoon","violin"], "guitardrumxyz"), 10, 'Test 38');
test(countCharacters(["leetcode","challenge","contest","question"], "oelhctganegqisun"), 8, 'Test 39');
test(countCharacters(["abacax","banana","grape"], "aaabbnagpr"), 0, 'Test 40');
test(countCharacters(["ab","ba","abc","bca","acb","cab","cba","bac","bca","acb","cab","cba","bac","bca","acb","cab","cba","bac","bca","acb","cab","cba","bac","bca","acb","cab","cba","bac","bca","acb","cab","cba"], "abc"), 94, 'Test 41');
test(countCharacters(["alibaba","babala","baliba","lalala"], "balibalab"), 19, 'Test 42');
test(countCharacters(["aabbcc","bbccdd","aaccdd"], "aabbbccdd"), 18, 'Test 43');
test(countCharacters(["abcdefghij","jihgfedcba","hgfedcb","fedcbghij"], "abcdefghij"), 36, 'Test 44');
test(countCharacters(["aabbccddeeffgg","bbccddeeffgghh","ccddeeffgghhiijj"], "abcdefghij"), 0, 'Test 45');
test(countCharacters(["algorithm","data","structure","binary","search"], "lgarithmtdastrucetubynrseahc"), 25, 'Test 46');
test(countCharacters(["abcdefgh","abcdefghi","abcdefghij","abcdefghijk"], "abcdefghij"), 27, 'Test 47');
test(countCharacters(["abcdabcd","dcbaabcd","abcd","abcd"], "abcdabcd"), 24, 'Test 48');
test(countCharacters(["programming","challenge","difficulty","algorithm"], "progaminld"), 0, 'Test 49');
test(countCharacters(["aabbcc","aabbc","aabb","aa","a"], "aabbbcccc"), 18, 'Test 50');
test(countCharacters(["abcdefghijklmnopqrstuvwxyz", "zyxwvutsrqponmlkjihgfedcba"], "abcdefghijklmnopqrstuvwxyz"), 52, 'Test 51');
test(countCharacters(["multiple","words","with","same","letters"], "mlpuwihswtael"), 16, 'Test 52');
test(countCharacters(["abcd","abcde","abcdef"], "abcdefg"), 15, 'Test 53');
test(countCharacters(["hello","world","python","programming"], "helloworldpython"), 16, 'Test 54');
test(countCharacters(["abc","abcd","abcde","abcdef","abcdefg"], "abcdefg"), 25, 'Test 55');
test(countCharacters(["aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz","zz","yy","xx"], "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"), 58, 'Test 56');
test(countCharacters(["optimization","algorithm","datastructure"], "odginatrlhms"), 9, 'Test 57');
test(countCharacters(["short","longerword","evenlonger","longestword","tiny"], "longestword"), 11, 'Test 58');
test(countCharacters(["algorithm","data","structure"], "algorithmdstuct"), 9, 'Test 59');
test(countCharacters(["aabbcc","abcabc","abacbc"], "aabbcc"), 18, 'Test 60');
test(countCharacters(["aabbccddeeff","gghhiijjkk","llmmnnoopp","qqrrssttuu","vvwwxxyyzz"], "abcdefghijklmnopqrstuvwxyz"), 0, 'Test 61');
test(countCharacters(["mississippi","tennessee","delaware","georgia","alabama"], "mississippitennessegeorgiaalamaba"), 34, 'Test 62');
test(countCharacters(["unique","words","here"], "unewordhsere"), 9, 'Test 63');
test(countCharacters(["x", "xx", "xxx", "xxxx", "xxxxx", "xxxxxx", "xxxxxxx", "xxxxxxxx", "xxxxxxxxx", "xxxxxxxxxx"], "x"), 1, 'Test 64');
test(countCharacters(["abcd","dcba","dcba","abcd","abcd"], "abcdabcdabcd"), 20, 'Test 65');
test(countCharacters(["aaaaaabbbbcccc", "bbbbbcccccc", "cccccccc", "ddddd"], "aabbbccccdddd"), 0, 'Test 66');
test(countCharacters(["repeated","repeated","repeated","repeated"], "repeead"), 0, 'Test 67');
test(countCharacters(["programming","code","challenge"], "mprogainlce"), 0, 'Test 68');
test(countCharacters(["abc", "acb", "bac", "bca", "cab", "cba"], "abc"), 18, 'Test 69');
test(countCharacters(["repeat","repear","preear","pareer"], "reapeart"), 24, 'Test 70');
test(countCharacters(["unique","unigue","uneque"], "unequiq"), 6, 'Test 71');
test(countCharacters(["programming","is","fun"], "gimnoprrstu"), 2, 'Test 72');
test(countCharacters(["mississippi", "mississippi", "mississippi", "mississippi"], "misp"), 0, 'Test 73');
test(countCharacters(["abcdefg","bcdefga","cdefgab"], "abcdefg"), 21, 'Test 74');
test(countCharacters(["abcdefghij","jihgfedcba","abcde","edcba"], "abcdefghijabcdefghij"), 30, 'Test 75');
test(countCharacters(["abcd","dcba","abdc","dabc"], "abcd"), 16, 'Test 76');
test(countCharacters(["unique","characters","only","here"], "uneicharstolonhyer"), 8, 'Test 77');
test(countCharacters(["repeated","letters","example"], "repateledmx"), 15, 'Test 78');
test(countCharacters(["programming","python","java","coding"], "gnimmargorpthonavajgnidoc"), 21, 'Test 79');
test(countCharacters(["aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"], "abcdefghijklmnopqrstuvwxyz"), 0, 'Test 80');
test(countCharacters(["mississippi","missouri","mismatch","miss"], "mississippi"), 15, 'Test 81');
test(countCharacters(["abcdefghijk","klmno","pqrstuvw","xyz","mnopqr","stuv","wxyz"], "abcdefghijklmnopqrstuvwxyz"), 41, 'Test 82');
test(countCharacters(["abacax","banana","grape"], "aabacax"), 6, 'Test 83');
test(countCharacters(["programming","python","java"], "pgoramythnvaj"), 10, 'Test 84');
test(countCharacters(["unique","words","only","once"], "nuqowinco"), 0, 'Test 85');
test(countCharacters(["programming","python","java","algorithm"], "pgmnoaahjy"), 0, 'Test 86');
test(countCharacters(["aabbccddeeff","zzzzzzzzzz","yyyyyyyyyy"], "abcdefzy"), 0, 'Test 87');
test(countCharacters(["aaaaaaaa","bbbbbbbb","cccccccc","dddddddd"], "abcd"), 0, 'Test 88');
test(countCharacters(["longerword","evenlongerword","superduperlongword"], "lorenwdsupem"), 0, 'Test 89');
test(countCharacters(["repeated","characters","here","are","some"], "reepeaddttcharseom"), 19, 'Test 90');
test(countCharacters(["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"], "enifxsv"), 7, 'Test 91');
test(countCharacters(["testtest","testtest","testtest"], "ttttseeeesss"), 24, 'Test 92');
test(countCharacters(["abcd","dcba","efgh","hgfe"], "abcdefgh"), 16, 'Test 93');
test(countCharacters(["qwerty","asdfgh","zxcvbn"], "qwertyasdfghzxcvbn"), 18, 'Test 94');
test(countCharacters(["abacax","bacax","cax","ax","x"], "abacax"), 17, 'Test 95');
test(countCharacters(["mississippi","babbling","bookkeeper"], "bmkpeorins"), 0, 'Test 96');
test(countCharacters(["repeated","characters","example","strings","test"], "eeptxsa"), 0, 'Test 97');
test(countCharacters(["this","is","a","test","case"], "tastciehins"), 15, 'Test 98');
test(countCharacters(["banana","bandana","bandanna"], "bandanabandana"), 21, 'Test 99');
test(countCharacters(["encyclopedia","dictionary","thesaurus"], "ctheosuraind"), 0, 'Test 100');
test(countCharacters(["longword","another","wordset"], "longanotwrheds"), 22, 'Test 101');
test(countCharacters(["repeated","characters","in","strings"], "repachint"), 2, 'Test 102');
test(countCharacters(["unique", "words", "only", "once"], "euqinowrsc"), 4, 'Test 103');
test(countCharacters(["encyclopedia","dictionary","encyclopedia","encyclopediab"], "encyclopedia"), 24, 'Test 104');
test(countCharacters(["banana","apple","orange","grape","peach"], "aapplleeorrnggbnpppe"), 16, 'Test 105');
test(countCharacters(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"], "zyxwvutsrqponmlkjihgfedcba"), 26, 'Test 106');
test(countCharacters(["abracadabra","barack","rac","cabra"], "abracadabra"), 19, 'Test 107');
test(countCharacters(["abcdefgh","ijklmnop","qrstuvwx","yz"], "abcdefghijklmnopqrstuvwxyz"), 26, 'Test 108');
test(countCharacters(["algorithm","datastructure","programming"], "datastructureprogramming"), 24, 'Test 109');
test(countCharacters(["one","two","three","four","five"], "onethreefourfive"), 16, 'Test 110');
test(countCharacters(["mississippi","baby","racecar","level","rotor"], "ississippiabaycerracelevrotor"), 12, 'Test 111');
test(countCharacters(["repetition","representation","reform"], "repitnfom"), 0, 'Test 112');
test(countCharacters(["longwordhere","anotherlongword","shortword"], "lnwordhertahoes"), 9, 'Test 113');
test(countCharacters(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx", "yz"], "abcdefghijklmnopqrstuvwxyz"), 26, 'Test 114');
test(countCharacters(["abcd","abce","abcf"], "abcd"), 4, 'Test 115');
test(countCharacters(["abcd", "abac", "aabc", "abcc", "accc"], "abcc"), 4, 'Test 116');
test(countCharacters(["mississippi","elephant","umbrella","java","python"], "ieelmpstuvy"), 0, 'Test 117');
test(countCharacters(["aabbcc","abcabc","ccabba","baccab"], "aabbcc"), 24, 'Test 118');
test(countCharacters(["algorithm","data","structure"], "gahlimstrucotad"), 13, 'Test 119');
test(countCharacters(["abcdefgh","ijklmnop","qrstuvwx","yzabcd","efghij","klmnopqr","stuvwx","yzabcd","efghij","klmnopqr","stuvwx"], "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba"), 76, 'Test 120');
test(countCharacters(["abcdabcd", "abcdabcdabcd", "abcdabcdabcdabcd", "abcd"], "abcdabcdabcdabcd"), 40, 'Test 121');
test(countCharacters(["supercalifragilisticexpialidocious","antidisestablishmentarianism","floccinaucinihilipilification"], "supercalifragilisticexpialidociousantidisestablishmentarianismfloccinaucinihilipilification"), 91, 'Test 122');
test(countCharacters(["abcdefghijklmnopqrstuvwxyz","zyxwvutsrqponmlkjihgfedcba","mnopqrstuvwxyzabcde"], "abcdefghijklmnopqrstuvwxyzzzzzzzzzz"), 71, 'Test 123');
test(countCharacters(["elephant","giraffe","hippopotamus"], "eplhgaifeotmups"), 0, 'Test 124');
test(countCharacters(["repeat", "repeat", "repeat", "repeat"], "eprta"), 0, 'Test 125');
test(countCharacters(["hello","world","leetcode","challenge"], "helloworldleetcodechallenge"), 27, 'Test 126');
test(countCharacters(["abcd","efgh","ijkl","mnop","qrst","uvwx","yz"], "abcdefghijklmnopqrstuvwxyz"), 26, 'Test 127');
test(countCharacters(["stackoverflow","overflow","underflow","flow"], "flowover"), 12, 'Test 128');
test(countCharacters(["supercalifragilisticexpialidocious","supercalifragilistic","califragilistic","expialidocious"], "supercalifragilisticexpialidocious"), 83, 'Test 129');
test(countCharacters(["umbrella","balloon","orange"], "mnbaylobnragoe"), 6, 'Test 130');
test(countCharacters(["xylophone","triangle","piano","drum","guitar"], "tpirangedumxylophone"), 32, 'Test 131');
test(countCharacters(["abcdefg","hijklmn","opqrstu","vwxyz"], "zyxwvutsrqponmlkjihgfedcba"), 26, 'Test 132');
test(countCharacters(["character","char","act","react","actchar"], "character"), 28, 'Test 133');
test(countCharacters(["programming","language","python","java","javascript","c","cpp"], "pgoramlngyjtahivsc"), 21, 'Test 134');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

