// Test: 1125. Smallest Sufficient Team
// 82 test cases from LeetCodeDataset
// Run: node test.js

const { smallestSufficientTeam } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1125. Smallest Sufficient Team\n");

test(smallestSufficientTeam(["python","sql"], [["python"],["sql"],["python","sql"]]), [2], 'Test 1');
test(smallestSufficientTeam(["java","nodejs","reactjs"], [["java"],["nodejs"],["nodejs","reactjs"]]), [2, 0], 'Test 2');
test(smallestSufficientTeam(["programming","testing","design"], [["programming"],["testing"],["design"],["programming","testing"],["testing","design"],["design","programming"]]), [4, 0], 'Test 3');
test(smallestSufficientTeam(["a","b","c"], [["a","b"],["b","c"],["c"],["a"]]), [1, 3], 'Test 4');
test(smallestSufficientTeam(["network","database"], [["network"],["database"],["network","database"]]), [2], 'Test 5');
test(smallestSufficientTeam(["skill1","skill2","skill3","skill4"], [["skill1"],["skill2"],["skill3"],["skill4"],["skill1","skill2","skill3","skill4"]]), [4], 'Test 6');
test(smallestSufficientTeam(["coding","design","writing"], [["coding"],["design"],["writing"],["coding","design","writing"]]), [3], 'Test 7');
test(smallestSufficientTeam(["coding","design"], [["coding"],["design"],["coding","design"]]), [2], 'Test 8');
test(smallestSufficientTeam(["skill1","skill2","skill3","skill4"], [["skill1"],["skill2"],["skill3"],["skill4"],["skill1","skill2"],["skill3","skill4"]]), [5, 4], 'Test 9');
test(smallestSufficientTeam(["algorithms","math","java","reactjs","csharp","aws"], [["algorithms","math","java"],["algorithms","math","reactjs"],["java","csharp","aws"],["reactjs","csharp"],["csharp","math"],["aws","java"]]), [2, 1], 'Test 10');
test(smallestSufficientTeam(["python","data","ai"], [["python"],["data"],["ai"],["python","data"],["data","ai"],["python","ai"]]), [4, 0], 'Test 11');
test(smallestSufficientTeam(["req1","req2"], [["req1"],["req2"],["req1","req2"],["req1"],["req2"]]), [2], 'Test 12');
test(smallestSufficientTeam(["sql","noSql"], [["sql"],["noSql"],["sql","noSql"],["sql"],["noSql"]]), [2], 'Test 13');
test(smallestSufficientTeam(["skill1","skill2","skill3"], [["skill1","skill2"],["skill2","skill3"],["skill3","skill1"]]), [1, 0], 'Test 14');
test(smallestSufficientTeam(["a","b","c","d"], [["a","b"],["b","c"],["c","d"],["d","a"],["a","b","c","d"]]), [4], 'Test 15');
test(smallestSufficientTeam(["frontend","backend","devops"], [["frontend"],["backend"],["devops"],["frontend","backend"],["backend","devops"],["frontend","devops"],["frontend","backend","devops"]]"), Error: Solution.smallestSufficientTeam[] missing 1 required positional argument: 'people', 'Test 16');
test(smallestSufficientTeam(["devops","data_analysis","cloud_services","ui_ux"], [["devops"],["data_analysis"],["cloud_services"],["ui_ux"],["devops","data_analysis"],["cloud_services","ui_ux"],["devops","cloud_services"],["data_analysis","ui_ux"]]), [5, 4], 'Test 17');
test(smallestSufficientTeam(["machinelearning","deeplearning","computer_vision","nlp"], [["machinelearning"],["deeplearning"],["computer_vision"],["nlp"],["machinelearning","deeplearning"],["computer_vision","nlp"],["machinelearning","nlp"]]), [5, 4], 'Test 18');
test(smallestSufficientTeam(["frontend","backend","fullstack","uiux","devops"], [["frontend"],["backend"],["fullstack"],["uiux"],["devops"],["frontend","backend"],["fullstack","uiux"],["backend","devops"],["fullstack","devops"],["frontend","uiux"],["frontend","backend","uiux"]]), [8, 10], 'Test 19');
test(smallestSufficientTeam(["ui","ux","backend","frontend"], [["ui"],["ux"],["backend"],["frontend"],["ui","ux"],["backend","frontend"],["ui","backend"],["ux","frontend"],["ui","ux","backend","frontend"]]), [8], 'Test 20');
test(smallestSufficientTeam(["python","javascript","c++","ruby"], [["python","javascript"],["c++"],["ruby"],["python","c++"],["javascript","ruby"]]), [4, 3], 'Test 21');
test(smallestSufficientTeam(["frontend","backend","devops","qa"], [["frontend"],["backend"],["devops"],["qa"],["frontend","backend"],["backend","devops"],["devops","qa"],["frontend","qa"],["frontend","backend","devops"],["backend","devops","qa"],["frontend","devops","qa"],["frontend","backend","qa"],["frontend","backend","devops","qa"]]), [12], 'Test 22');
test(smallestSufficientTeam(["sql","nosql","big_data","data_warehouse"], [["sql"],["nosql"],["big_data"],["data_warehouse"],["sql","nosql"],["nosql","big_data"],["big_data","data_warehouse"],["sql","data_warehouse"],["sql","nosql","big_data"],["nosql","big_data","data_warehouse"],["sql","big_data","data_warehouse"],["sql","nosql","data_warehouse"],["sql","nosql","big_data","data_warehouse"]]), [12], 'Test 23');
test(smallestSufficientTeam(["mobiledev","webdev","devops","design","testing"], [["mobiledev"],["webdev"],["devops"],["design"],["testing"],["mobiledev","webdev"],["devops","design"],["webdev","testing"],["mobiledev","devops"],["design","testing"],["mobiledev","webdev","devops"],["devops","design","testing"]]), [11, 5], 'Test 24');
test(smallestSufficientTeam(["algorithm","datastructure","programming","problem-solving"], [["algorithm"],["datastructure"],["programming"],["problem-solving"],["algorithm","datastructure"],["programming","problem-solving"],["algorithm","problem-solving"],["datastructure","programming"],["algorithm","datastructure","programming","problem-solving"]]), [8], 'Test 25');
test(smallestSufficientTeam(["iot","ml","ai","automation","cloudcomputing"], [["iot"],["ml"],["ai"],["automation"],["cloudcomputing"],["iot","ml"],["ai","automation"],["cloudcomputing","ml"],["iot","automation"],["ai","cloudcomputing"],["iot","ml","ai"],["automation","cloudcomputing","ml"]]), [11, 10], 'Test 26');
test(smallestSufficientTeam(["project_management","communication","problem_solving","decision_making"], [["project_management"],["communication"],["problem_solving"],["decision_making"],["project_management","communication"],["problem_solving","decision_making"],["project_management","problem_solving"],["communication","decision_making"],["project_management","communication","problem_solving"],["communication","problem_solving","decision_making"]]), [9, 0], 'Test 27');
test(smallestSufficientTeam(["database","frontend","backend","devops","cloud","security"], [["database"],["frontend"],["backend"],["devops"],["cloud"],["security"],["database","frontend"],["backend","devops"],["cloud","security"],["database","backend"],["frontend","devops"],["cloud","frontend"],["database","cloud"],["devops","security"],["database","frontend","backend"],["devops","cloud","security"]]), [15, 14], 'Test 28');
test(smallestSufficientTeam(["python","javascript","ruby","cpp"], [["python","cpp"],["javascript"],["ruby"],["python","javascript"],["cpp","ruby"],["python","ruby"]]), [4, 3], 'Test 29');
test(smallestSufficientTeam(["sql","nosql","devops","cloud","agile"], [["sql"],["nosql"],["devops"],["cloud"],["agile"],["sql","nosql"],["devops","cloud"],["cloud","agile"],["sql","devops"],["nosql","agile"]]), [7, 8, 1], 'Test 30');
test(smallestSufficientTeam(["agile","scrum","kanban","project_management","team_leadership"], [["agile"],["scrum"],["kanban"],["project_management"],["team_leadership"],["agile","scrum"],["kanban","project_management"],["team_leadership","agile"],["scrum","team_leadership"]]"), Error: Solution.smallestSufficientTeam[] missing 1 required positional argument: 'people', 'Test 31');
test(smallestSufficientTeam(["leadership","communication","programming","project-management","design"], [["leadership"],["communication"],["programming"],["project-management"],["design"],["leadership","communication"],["programming","project-management"],["design","communication"],["leadership","programming"],["project-management","design"],["leadership","programming","design"],["communication","project-management","design"],["leadership","communication","design"]]), [11, 8], 'Test 32');
test(smallestSufficientTeam(["javascript","typescript","angular","react"], [["javascript"],["typescript"],["angular"],["react"],["javascript","typescript"],["angular","react"],["javascript","angular"],["typescript","react"],["javascript","typescript","angular","react"]]), [8], 'Test 33');
test(smallestSufficientTeam(["python","javascript","c++","ruby","go"], [["python","javascript"],["c++","ruby"],["go"],["python","c++"],["javascript","ruby","go"]]), [4, 3], 'Test 34');
test(smallestSufficientTeam(["linux","windows","macos","docker"], [["linux"],["windows"],["macos"],["docker"],["linux","windows"],["macos","docker"],["linux","macos"],["windows","docker"],["linux","macos","docker"],["windows","macos","docker"],["linux","windows","docker"],["linux","windows","macos","docker"]]), [11], 'Test 35');
test(smallestSufficientTeam(["sql","nosql","bigdata","machinelearning","datascience"], [["sql","nosql"],["bigdata","machinelearning"],["datascience"],["sql","bigdata"],["nosql","machinelearning"],["bigdata","datascience"],["machinelearning","datascience"],["sql","nosql","bigdata","machinelearning","datascience"]]), [7], 'Test 36');
test(smallestSufficientTeam(["git","docker","jenkins","travis","circleci","aws"], [["git","docker"],["jenkins","travis"],["circleci","aws"],["git","travis"],["docker","circleci"],["jenkins","aws"],["git","docker","jenkins","travis","circleci","aws"]]), [6], 'Test 37');
test(smallestSufficientTeam(["sql","nosql","database_design","database_performance"], [["sql"],["nosql"],["database_design"],["database_performance"],["sql","nosql"],["database_design","database_performance"],["sql","database_performance"],["nosql","database_design"]]"), Error: Solution.smallestSufficientTeam[] missing 1 required positional argument: 'people', 'Test 38');
test(smallestSufficientTeam(["mongodb","postgresql","mysql","oracle"], [["mongodb"],["postgresql"],["mysql"],["oracle"],["mongodb","postgresql"],["mysql","oracle"],["mongodb","mysql"],["postgresql","oracle"],["mongodb","postgresql","mysql"],["postgresql","mysql","oracle"],["mongodb","mysql","oracle"],["mongodb","postgresql","oracle"],["mongodb","postgresql","mysql","oracle"]]), [12], 'Test 39');
test(smallestSufficientTeam(["communication","problem_solving","critical_thinking","leadership"], [["communication"],["problem_solving"],["critical_thinking"],["leadership"],["communication","problem_solving"],["critical_thinking","leadership"],["communication","critical_thinking"],["problem_solving","leadership"],["communication","problem_solving","critical_thinking"],["communication","problem_solving","leadership"],["communication","critical_thinking","leadership"],["problem_solving","critical_thinking","leadership"],["communication","problem_solving","critical_thinking","leadership"]]), [12], 'Test 40');
test(smallestSufficientTeam(["web_development","mobile_development","game_development","software_development"], [["web_development"],["mobile_development"],["game_development"],["software_development"],["web_development","mobile_development"],["game_development","software_development"],["web_development","game_development"],["mobile_development","software_development"]]"), Error: Solution.smallestSufficientTeam[] missing 1 required positional argument: 'people', 'Test 41');
test(smallestSufficientTeam(["image_processing","natural_language_processing","deep_learning","computer_vision"], [["image_processing"],["natural_language_processing"],["deep_learning"],["computer_vision"],["image_processing","natural_language_processing"],["deep_learning","computer_vision"],["image_processing","deep_learning"],["natural_language_processing","computer_vision"],["image_processing","natural_language_processing","deep_learning"],["natural_language_processing","deep_learning","computer_vision"],["image_processing","deep_learning","computer_vision"],["image_processing","natural_language_processing","deep_learning","computer_vision"]]), [11], 'Test 42');
test(smallestSufficientTeam(["java","spring","hibernate","react"], [["java"],["spring"],["hibernate"],["react"],["java","spring"],["spring","hibernate"],["hibernate","react"],["java","react"],["java","spring","hibernate"],["java","spring","react"],["spring","hibernate","react"],["java","spring","hibernate","react"]]), [11], 'Test 43');
test(smallestSufficientTeam(["sql","python","frontend","backend"], [["sql"],["python"],["frontend"],["backend"],["sql","python"],["frontend","backend"]]), [5, 4], 'Test 44');
test(smallestSufficientTeam(["python","java","c++","ruby"], [["python"],["java"],["c++"],["ruby"],["python","java"],["c++","ruby"],["python","c++"],["java","ruby"]]), [5, 4], 'Test 45');
test(smallestSufficientTeam(["aws","azure","gcp"], [["aws","azure"],["gcp"],["aws"],["azure","gcp"],["aws","gcp"],["azure"],["aws","azure","gcp"]]), [6], 'Test 46');
test(smallestSufficientTeam(["data_science","data_engineering","ai","ml"], [["data_science"],["data_engineering"],["ai"],["ml"],["data_science","data_engineering"],["ai","ml"],["data_science","ai"],["data_engineering","ml"],["data_science","data_engineering","ai"],["data_engineering","ai","ml"],["data_science","ai","ml"],["data_science","data_engineering","ai","ml"]]), [11], 'Test 47');
test(smallestSufficientTeam(["security","testing","projectmanagement","communication","design"], [["security"],["testing"],["projectmanagement"],["communication"],["design"],["security","testing"],["projectmanagement","communication"],["design","security"],["testing","communication"],["security","projectmanagement","design"],["testing","communication","design"]]), [9, 8], 'Test 48');
test(smallestSufficientTeam(["coding","debugging","testing","design"], [["coding","debugging"],["testing"],["design"],["coding","testing"],["debugging","design"]]), [4, 3], 'Test 49');
test(smallestSufficientTeam(["photoshop","illustrator","indesign","lightroom"], [["photoshop","illustrator"],["indesign"],["lightroom"],["photoshop","indesign"],["illustrator","lightroom"],["photoshop","lightroom"],["indesign","lightroom"],["photoshop","illustrator","indesign"],["illustrator","indesign","lightroom"],["photoshop","indesign","lightroom"],["photoshop","illustrator","lightroom"],["photoshop","illustrator","indesign","lightroom"]]), [11], 'Test 50');
test(smallestSufficientTeam(["algorithm","data-structures","database","networking","os"], [["algorithm","data-structures"],["database"],["networking"],["os"],["algorithm","os"],["data-structures","networking"],["database","os"],["algorithm","data-structures","database"],["networking","os"],["algorithm","networking","os"]]), [8, 7], 'Test 51');
test(smallestSufficientTeam(["security","analytics","ml","devops"], [["security"],["analytics"],["ml"],["devops"],["security","analytics"],["ml","devops"],["security","ml"],["analytics","devops"],["security","analytics","ml"],["security","analytics","devops"],["security","ml","devops"],["analytics","ml","devops"],["security","analytics","ml","devops"]]), [12], 'Test 52');
test(smallestSufficientTeam(["sql","no_sql","big_data","cloud_computing"], [["sql"],["no_sql"],["big_data"],["cloud_computing"],["sql","no_sql"],["big_data","cloud_computing"],["sql","big_data"],["no_sql","cloud_computing"],["sql","no_sql","big_data"],["no_sql","big_data","cloud_computing"],["sql","big_data","cloud_computing"],["sql","no_sql","cloud_computing"]]), [9, 0], 'Test 53');
test(smallestSufficientTeam(["coding","debugging","design","deployment"], [["coding","debugging"],["design"],["deployment"],["coding","deployment"],["design","debugging"]]), [3, 4], 'Test 54');
test(smallestSufficientTeam(["sql","nosql","bigdata","cloud","devops"], [["sql"],["nosql"],["bigdata"],["cloud"],["devops"],["sql","nosql"],["bigdata","cloud"],["devops","sql"],["nosql","cloud"],["bigdata","devops"],["sql","cloud"],["nosql","devops"],["bigdata","sql"],["cloud","devops"],["sql","nosql","cloud"],["bigdata","sql","cloud"],["nosql","cloud","devops"]]), [16, 12], 'Test 55');
test(smallestSufficientTeam(["python","cpp","java","javascript"], [["python","cpp"],["java"],["javascript","java"],["cpp","python"],["cpp","java"],["javascript"]]), [2, 0], 'Test 56');
test(smallestSufficientTeam(["data_science","machine_learning","deep_learning"], [["data_science"],["machine_learning"],["deep_learning"],["data_science","machine_learning"],["machine_learning","deep_learning"],["data_science","deep_learning"]]"), Error: Solution.smallestSufficientTeam[] missing 1 required positional argument: 'people', 'Test 57');
test(smallestSufficientTeam(["coding","debugging","testing","deployment"], [["coding"],["debugging"],["testing"],["deployment"],["coding","debugging"],["testing","deployment"],["coding","testing"],["debugging","deployment"],["coding","debugging","testing"],["debugging","testing","deployment"],["coding","debugging","deployment"],["coding","testing","deployment"],["coding","debugging","testing","deployment"]]), [12], 'Test 58');
test(smallestSufficientTeam(["networking","security","project_management","budgeting"], [["networking"],["security"],["project_management"],["budgeting"],["networking","security"],["project_management","budgeting"],["networking","project_management"],["security","budgeting"],["networking","project_management","budgeting"],["networking","security","project_management","budgeting"]]), [9], 'Test 59');
test(smallestSufficientTeam(["html","css","javascript","react","nodejs","python"], [["html","css"],["javascript","react"],["nodejs","python"],["html","javascript"],["css","python"],["react","nodejs"],["html","css","javascript","react","nodejs","python"]]"), Error: Solution.smallestSufficientTeam[] missing 1 required positional argument: 'people', 'Test 60');
test(smallestSufficientTeam(["architecture","security","performance","usability","coding"], [["architecture","security"],["performance","usability"],["coding"],["architecture","performance"],["security","usability"],["performance","coding"],["architecture","usability","coding"]]"), Error: Solution.smallestSufficientTeam[] missing 1 required positional argument: 'people', 'Test 61');
test(smallestSufficientTeam(["ui","ux","product_design","interaction_design"], [["ui","ux"],["product_design"],["interaction_design"],["ui","product_design"],["ux","interaction_design"],["ui","ux","product_design"],["product_design","interaction_design"]]"), Error: Solution.smallestSufficientTeam[] missing 1 required positional argument: 'people', 'Test 62');
test(smallestSufficientTeam(["aws","azure","gcp","docker","kubernetes"], [["aws","azure"],["gcp","docker"],["kubernetes"],["aws","docker"],["azure","gcp"],["aws","gcp","kubernetes"]]), [5, 3, 0], 'Test 63');
test(smallestSufficientTeam(["coding","testing","documentation","deployment"], [["coding","testing"],["documentation","deployment"],["coding","documentation"],["testing","deployment"],["coding","testing","documentation"],["testing","documentation","deployment"],["coding","documentation","deployment"],["coding","testing","deployment"],["coding","testing","documentation","deployment"]]), [8], 'Test 64');
test(smallestSufficientTeam(["html","css","javascript","react","nodejs"], [["html","css"],["javascript"],["react","nodejs"],["html","javascript"],["css","nodejs"],["react"],["html","javascript","react"]]), [4, 6], 'Test 65');
test(smallestSufficientTeam(["product","design","backend","frontend","testing"], [["product"],["design"],["backend"],["frontend"],["testing"],["product","design"],["backend","frontend"],["testing","product"],["design","backend"],["frontend","testing"],["product","backend","frontend","testing"],["design","backend","frontend","testing"]]), [11, 0], 'Test 66');
test(smallestSufficientTeam(["docker","kubernetes","aws","gcp"], [["docker"],["kubernetes"],["aws"],["gcp"],["docker","kubernetes"],["aws","gcp"],["docker","aws"],["kubernetes","gcp"]]), [5, 4], 'Test 67');
test(smallestSufficientTeam(["linux","windows","macos","unix"], [["linux"],["windows"],["macos"],["unix"],["linux","windows"],["macos","unix"],["linux","macos"],["windows","unix"],["linux","unix"],["windows","macos"],["linux","macos","unix"],["linux","windows","unix"],["windows","macos","unix"],["linux","windows","macos"],["linux","windows","macos","unix"]]), [14], 'Test 68');
test(smallestSufficientTeam(["python","javascript","typescript","react","angular","vue"], [["python"],["javascript"],["typescript"],["react"],["angular"],["vue"],["python","javascript"],["typescript","react"],["angular","vue"],["python","react"],["javascript","vue"]]), [8, 7, 6], 'Test 69');
test(smallestSufficientTeam(["html","css","javascript","react"], [["html","css"],["javascript"],["react"],["css","javascript"],["html","react"],["html","css","javascript","react"]]), [5], 'Test 70');
test(smallestSufficientTeam(["algorithm","data_structure","design_patterns","software_architecture"], [["algorithm"],["data_structure"],["design_patterns"],["software_architecture"],["algorithm","data_structure"],["design_patterns","software_architecture"],["algorithm","design_patterns"],["data_structure","software_architecture"],["algorithm","data_structure","design_patterns"],["algorithm","data_structure","software_architecture"],["algorithm","design_patterns","software_architecture"],["data_structure","design_patterns","software_architecture"],["algorithm","data_structure","design_patterns","software_architecture"]]), [12], 'Test 71');
test(smallestSufficientTeam(["frontend","backend","devops","qa"], [["frontend"],["backend"],["devops"],["qa"],["frontend","backend"],["devops","qa"],["frontend","devops"],["backend","qa"],["frontend","devops","qa"],["backend","devops","qa"],["frontend","backend","devops"],["frontend","backend","qa"],["frontend","backend","devops","qa"]]), [12], 'Test 72');
test(smallestSufficientTeam(["machine-learning","deep-learning","neural-networks","cv","nlp"], [["machine-learning"],["deep-learning"],["neural-networks"],["cv"],["nlp"],["machine-learning","deep-learning"],["neural-networks","cv"],["nlp","machine-learning"],["deep-learning","cv"],["neural-networks","nlp"],["machine-learning","cv"],["deep-learning","nlp"],["machine-learning","neural-networks"],["deep-learning","neural-networks"],["cv","nlp"],["machine-learning","deep-learning","cv"],["neural-networks","cv","nlp"],["machine-learning","deep-learning","nlp"],["neural-networks","deep-learning","cv","nlp"],["machine-learning","neural-networks","cv","nlp"]]), [18, 0], 'Test 73');
test(smallestSufficientTeam(["python","java","cpp"], [["python","cpp"],["java"],["python","java"],["cpp"],["java","cpp"]]"), Error: Solution.smallestSufficientTeam[] missing 1 required positional argument: 'people', 'Test 74');
test(smallestSufficientTeam(["ai","ml","dl","nlp","cv"], [["ai"],["ml"],["dl"],["nlp"],["cv"],["ai","ml"],["ml","dl"],["dl","nlp"],["nlp","cv"],["cv","ai"],["ai","dl"],["ml","nlp"],["ai","cv"],["ml","cv"],["ai","ml","dl","nlp","cv"]]"), Error: Solution.smallestSufficientTeam[] missing 1 required positional argument: 'people', 'Test 75');
test(smallestSufficientTeam(["network_security","cyber_security","penetration_testing","vulnerability_assessment"], [["network_security"],["cyber_security"],["penetration_testing"],["vulnerability_assessment"],["network_security","cyber_security"],["penetration_testing","vulnerability_assessment"],["network_security","penetration_testing"],["cyber_security","vulnerability_assessment"],["network_security","vulnerability_assessment"],["cyber_security","penetration_testing"],["network_security","cyber_security","penetration_testing","vulnerability_assessment"]]), [10], 'Test 76');
test(smallestSufficientTeam(["front_end","back_end","database","cloud_services"], [["front_end"],["back_end"],["database"],["cloud_services"],["front_end","back_end"],["database","cloud_services"],["front_end","database"],["back_end","cloud_services"],["front_end","back_end","database"],["front_end","back_end","cloud_services"],["front_end","database","cloud_services"],["back_end","database","cloud_services"],["front_end","back_end","database","cloud_services"]]), [12], 'Test 77');
test(smallestSufficientTeam(["data_science","machine_learning","deep_learning","computer_vision"], [["data_science"],["machine_learning"],["deep_learning"],["computer_vision"],["machine_learning","deep_learning"],["data_science","computer_vision"],["data_science","machine_learning"],["data_science","deep_learning"],["machine_learning","computer_vision"],["deep_learning","computer_vision"]]), [9, 6], 'Test 78');
test(smallestSufficientTeam(["python","javascript","html","css","react","nodejs"], [["python"],["javascript"],["html"],["css"],["react"],["nodejs"],["python","javascript"],["html","css"],["react","nodejs"],["python","html","css"],["javascript","react","nodejs"]]), [10, 9], 'Test 79');
test(smallestSufficientTeam(["machine_learning","deep_learning","cv","nlp"], [["machine_learning","deep_learning"],["cv"],["nlp"],["deep_learning","cv"],["machine_learning","nlp"],["deep_learning","nlp","cv"],["machine_learning","deep_learning","cv","nlp"]]), [6], 'Test 80');
test(smallestSufficientTeam(["ux","ui","product","design","marketing"], [["ux"],["ui"],["product"],["design"],["marketing"],["ux","ui"],["product","design"],["marketing","ux"],["ui","product"],["design","marketing"],["ux","product"],["ui","marketing"],["product","design","marketing"],["ux","ui","design"],["ui","product","design"],["ux","product","marketing"],["ux","ui","product","design","marketing"]]), [16], 'Test 81');
test(smallestSufficientTeam(["python","javascript","cpp","go"], [["python","cpp"],["javascript"],["go"],["python","javascript","go"],["cpp","javascript"]]), [3, 0], 'Test 82');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

