// Test: 1813. Sentence Similarity Iii
// 197 test cases from LeetCodeDataset
// Run: node test.js

const { areSentencesSimilar } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1813. Sentence Similarity Iii\n");

test(areSentencesSimilar("Similar sentences", "Similar similar sentences"), true, 'Test 1');
test(areSentencesSimilar("Start end", "Start middle end"), true, 'Test 2');
test(areSentencesSimilar("Eating right now", "Eating"), true, 'Test 3');
test(areSentencesSimilar("A quick brown fox", "A quick brown fox jumps over the lazy dog"), true, 'Test 4');
test(areSentencesSimilar("Quick brown fox", "Quick brown fox jumps over the lazy dog"), true, 'Test 5');
test(areSentencesSimilar("of", "A lot of words"), false, 'Test 6');
test(areSentencesSimilar("Similarity check", "check Similarity"), false, 'Test 7');
test(areSentencesSimilar("Similar sentences", "Sentences Similar"), false, 'Test 8');
test(areSentencesSimilar("Similar sentences", "Similar very very similar sentences"), true, 'Test 9');
test(areSentencesSimilar("Python is great", "Python is very very great"), true, 'Test 10');
test(areSentencesSimilar("One two three", "One three"), true, 'Test 11');
test(areSentencesSimilar("Python is great", "is great"), true, 'Test 12');
test(areSentencesSimilar("Similar sentences", "Sentences that are Similar"), false, 'Test 13');
test(areSentencesSimilar("One", "One two three"), true, 'Test 14');
test(areSentencesSimilar("One", "One"), true, 'Test 15');
test(areSentencesSimilar("Test", "Test test"), true, 'Test 16');
test(areSentencesSimilar("Single", "Single word"), true, 'Test 17');
test(areSentencesSimilar("Test test test", "Test test test test"), true, 'Test 18');
test(areSentencesSimilar("Python programming", "programming"), true, 'Test 19');
test(areSentencesSimilar("This is a test", "This is"), true, 'Test 20');
test(areSentencesSimilar("A B C", "A B X C"), true, 'Test 21');
test(areSentencesSimilar("One two three", "One two three four"), true, 'Test 22');
test(areSentencesSimilar("Similar sentences", "Similar very similar sentences"), true, 'Test 23');
test(areSentencesSimilar("My name is Haley", "My Haley"), true, 'Test 24');
test(areSentencesSimilar("Same Same Same", "Same"), true, 'Test 25');
test(areSentencesSimilar("This is a test", "This is a dummy test"), true, 'Test 26');
test(areSentencesSimilar("Same same", "Same same same"), true, 'Test 27');
test(areSentencesSimilar("Overlap here", "Overlap word here"), true, 'Test 28');
test(areSentencesSimilar("Hello World", "World"), true, 'Test 29');
test(areSentencesSimilar("Hello World", "Hello"), true, 'Test 30');
test(areSentencesSimilar("Same same", "Same same"), true, 'Test 31');
test(areSentencesSimilar("Hello World", "Hello amazing World"), true, 'Test 32');
test(areSentencesSimilar("This is a test", "This is a simple test"), true, 'Test 33');
test(areSentencesSimilar("First Second Third", "First Third"), true, 'Test 34');
test(areSentencesSimilar("Match here", "Match something here"), true, 'Test 35');
test(areSentencesSimilar("Hello World", "Hello from the World"), true, 'Test 36');
test(areSentencesSimilar("Alice in Wonderland", "Alice is in Wonderland"), true, 'Test 37');
test(areSentencesSimilar("Left Right", "Left Middle Right"), true, 'Test 38');
test(areSentencesSimilar("The quick brown fox", "The quick brown fox jumps over"), true, 'Test 39');
test(areSentencesSimilar("To be or not to be that is the question", "To be that is the question"), true, 'Test 40');
test(areSentencesSimilar("The world is a stage", "The world is a stage and all the men and women merely players"), true, 'Test 41');
test(areSentencesSimilar("One two three", "One two insert three"), true, 'Test 42');
test(areSentencesSimilar("The quick brown fox", "The quick brown fox jumps"), true, 'Test 43');
test(areSentencesSimilar("No pain no gain", "No pain no gain but sometimes the pain is not worth the gain"), true, 'Test 44');
test(areSentencesSimilar("Let us play", "Let us play a game"), true, 'Test 45');
test(areSentencesSimilar("Mary had a little lamb", "Mary lamb"), true, 'Test 46');
test(areSentencesSimilar("All roads lead to Rome", "All roads lead to Rome but not all roads are the same"), true, 'Test 47');
test(areSentencesSimilar("Unique words only", "Unique unique words only"), true, 'Test 48');
test(areSentencesSimilar("Quick brown fox jumps over the lazy dog", "Quick brown fox jumps over the lazy quick brown dog"), true, 'Test 49');
test(areSentencesSimilar("a b c d e f g h i j", "a b c X Y Z d e f g h i j"), true, 'Test 50');
test(areSentencesSimilar("OnlyOneWordHere", "Only One Word Here"), false, 'Test 51');
test(areSentencesSimilar("Actions speak louder than words", "Actions speak"), true, 'Test 52');
test(areSentencesSimilar("One two three four five", "One two four five"), true, 'Test 53');
test(areSentencesSimilar("Python programming is fun", "Python programming is very fun"), true, 'Test 54');
test(areSentencesSimilar("Actions speak louder than words", "Actions speak louder than words but intentions matter"), true, 'Test 55');
test(areSentencesSimilar("Python is fun", "Python programming is really fun"), false, 'Test 56');
test(areSentencesSimilar("OpenAI is great", "OpenAI is indeed indeed great"), true, 'Test 57');
test(areSentencesSimilar("Do or do not there is no try", "Do or do not there is no no try"), true, 'Test 58');
test(areSentencesSimilar("Quick brown fox jumps over the lazy dog", "Quick fox jumps over the lazy dog"), true, 'Test 59');
test(areSentencesSimilar("Time flies when you are having fun", "Time flies"), true, 'Test 60');
test(areSentencesSimilar("The world is a book and those who do not travel read only one page", "The world is a book and those who do not travel read only one chapter"), false, 'Test 61');
test(areSentencesSimilar("Python programming is fun and effective", "Python programming effective"), true, 'Test 62');
test(areSentencesSimilar("Complex complex case", "Complex even more complex case"), true, 'Test 63');
test(areSentencesSimilar("Time heals all wounds", "Time heals all wounds but time is also a thief"), true, 'Test 64');
test(areSentencesSimilar("SingleWord", "SingleWord"), true, 'Test 65');
test(areSentencesSimilar("The cat sat on the mat", "The cat sat on the blue mat"), true, 'Test 66');
test(areSentencesSimilar("First and last", "First something in the middle last"), false, 'Test 67');
test(areSentencesSimilar("Once upon a time", "Once upon a time in a land far far away"), true, 'Test 68');
test(areSentencesSimilar("I think therefore I am", "I think therefore I am six"), true, 'Test 69');
test(areSentencesSimilar("Single word match", "Single word match"), true, 'Test 70');
test(areSentencesSimilar("Silence is golden", "Silence is golden in the morning"), true, 'Test 71');
test(areSentencesSimilar("A quick brown fox jumps", "A quick brown fox quick brown fox jumps"), true, 'Test 72');
test(areSentencesSimilar("Complex problem solving", "Complex problem problem solving"), true, 'Test 73');
test(areSentencesSimilar("Short", "Short and sweet"), true, 'Test 74');
test(areSentencesSimilar("a", "a b c d e f g h i j k l m n o p q r s t u v w x y z"), true, 'Test 75');
test(areSentencesSimilar("Overlap at end", "Continue overlap at end"), false, 'Test 76');
test(areSentencesSimilar("Happy birthday", "Happy birthday dear"), true, 'Test 77');
test(areSentencesSimilar("First word last word", "First first word last word"), true, 'Test 78');
test(areSentencesSimilar("To be or not to be", "To be or not to be that is the question"), true, 'Test 79');
test(areSentencesSimilar("May the force be with you", "May the force"), true, 'Test 80');
test(areSentencesSimilar("Python programming is fun", "Python programming is really really fun"), true, 'Test 81');
test(areSentencesSimilar("Alibaba Cloud offers various cloud services", "Alibaba Cloud offers cloud computing and storage services"), false, 'Test 82');
test(areSentencesSimilar("The early morning sun was a beautiful sight", "The early morning sun was a beautiful golden sight"), true, 'Test 83');
test(areSentencesSimilar("This is a long sentence with multiple words in it", "This long sentence with multiple words in it"), true, 'Test 84');
test(areSentencesSimilar("Lorem ipsum dolor sit amet", "Lorem ipsum dolor sit amet consectetur adipiscing elit"), true, 'Test 85');
test(areSentencesSimilar("Hello from the other side", "Hello from this side"), false, 'Test 86');
test(areSentencesSimilar("One two three", "One two X Y Z three"), true, 'Test 87');
test(areSentencesSimilar("Beginning middle end", "Beginning middle middle middle end"), true, 'Test 88');
test(areSentencesSimilar("Unique sentence", "Unique special sentence"), true, 'Test 89');
test(areSentencesSimilar("The quick brown fox jumps over the lazy dog", "The quick brown fox jumps over the lazy"), true, 'Test 90');
test(areSentencesSimilar("Start with a sentence", "Start with a really long sentence"), true, 'Test 91');
test(areSentencesSimilar("Python is fun", "Python is an amazing and fun language"), false, 'Test 92');
test(areSentencesSimilar("All your base are belong to us", "All base are belong to us"), true, 'Test 93');
test(areSentencesSimilar("Longer sentence with multiple words", "Longer sentence with even more multiple words"), true, 'Test 94');
test(areSentencesSimilar("She sells sea shells by the sea shore", "She sells green sea shells by the sea shore"), true, 'Test 95');
test(areSentencesSimilar("Complex algorithm design and analysis", "Complex algorithm"), true, 'Test 96');
test(areSentencesSimilar("In the middle", "In the middle of nowhere"), true, 'Test 97');
test(areSentencesSimilar("First Last", "First in between Last"), true, 'Test 98');
test(areSentencesSimilar("I love to code", "I love to code code code"), true, 'Test 99');
test(areSentencesSimilar("Unique words only", "Unique words in between only"), true, 'Test 100');
test(areSentencesSimilar("The quick brown fox", "The quick brown fox jumps over the lazy dog"), true, 'Test 101');
test(areSentencesSimilar("Single", "Single single single"), true, 'Test 102');
test(areSentencesSimilar("Life is a journey", "Life is a journey not a destination"), true, 'Test 103');
test(areSentencesSimilar("A B C D E", "A B X Y Z C D E"), true, 'Test 104');
test(areSentencesSimilar("The rain in Spain stays mainly in the plain", "The rain in Spain falls mainly in the plain"), false, 'Test 105');
test(areSentencesSimilar("A quick movement of the enemy will jeopardize six gunboats", "A quick movement of the enemy will jeopardize"), true, 'Test 106');
test(areSentencesSimilar("Short", "Very very short"), false, 'Test 107');
test(areSentencesSimilar("Do or do not there is no try", "Do or do not there is no other way"), false, 'Test 108');
test(areSentencesSimilar("Python programming is fun", "Python programming is very very fun"), true, 'Test 109');
test(areSentencesSimilar("Start coding", "Start coding today"), true, 'Test 110');
test(areSentencesSimilar("Happy new year", "Happy new new new year"), true, 'Test 111');
test(areSentencesSimilar("I love programming in Python", "I love programming in Java Python"), true, 'Test 112');
test(areSentencesSimilar("Actions speak louder than words", "Actions speak louder than words but words can inspire actions"), true, 'Test 113');
test(areSentencesSimilar("Python is great", "Programming in Python is great"), true, 'Test 114');
test(areSentencesSimilar("Data engineering and data science", "Data engineering"), true, 'Test 115');
test(areSentencesSimilar("One two three four", "One two five six seven eight three four"), true, 'Test 116');
test(areSentencesSimilar("I love coding", "I love coding in Python"), true, 'Test 117');
test(areSentencesSimilar("Prefix and suffix", "Prefix and more words suffix"), true, 'Test 118');
test(areSentencesSimilar("One two three four", "One two three four five six"), true, 'Test 119');
test(areSentencesSimilar("The quick brown fox jumps over the lazy dog", "The quick brown fox jumps over lazy dog"), true, 'Test 120');
test(areSentencesSimilar("Catch me if you can", "Catch me"), true, 'Test 121');
test(areSentencesSimilar("This is a complex example", "This is an extremely complex example"), false, 'Test 122');
test(areSentencesSimilar("Match start", "Match start middle"), true, 'Test 123');
test(areSentencesSimilar("x y z", "a b c x y z"), true, 'Test 124');
test(areSentencesSimilar("This is a test", "This is only a test"), true, 'Test 125');
test(areSentencesSimilar("The quick brown fox jumps over the lazy dog", "The quick brown fox jumps high over the lazy dog"), true, 'Test 126');
test(areSentencesSimilar("Python is great", "Python is the best language great"), true, 'Test 127');
test(areSentencesSimilar("The cat in the hat sat on the mat", "The cat sat on the mat"), true, 'Test 128');
test(areSentencesSimilar("The pen is mightier than the sword", "The pen is mightier than the sword but silence is golden"), true, 'Test 129');
test(areSentencesSimilar("Machine learning is transforming industries", "Machine learning transforming industries"), true, 'Test 130');
test(areSentencesSimilar("The quick brown fox", "The quick brown lazy dog"), false, 'Test 131');
test(areSentencesSimilar("One two three", "One two two three"), true, 'Test 132');
test(areSentencesSimilar("This is a test", "This is a longer test sentence"), false, 'Test 133');
test(areSentencesSimilar("Insert this sentence", "Insert some words this sentence"), true, 'Test 134');
test(areSentencesSimilar("An apple a day keeps the doctor away", "An apple a day"), true, 'Test 135');
test(areSentencesSimilar("Learning new things every day", "Learning new things every single day"), true, 'Test 136');
test(areSentencesSimilar("Match end", "Middle match end"), false, 'Test 137');
test(areSentencesSimilar("Silence is golden", "Silence is golden but sometimes it's better to speak your mind"), true, 'Test 138');
test(areSentencesSimilar("Test", "Test test test"), true, 'Test 139');
test(areSentencesSimilar("A B C D E", "A B C X Y Z D E"), true, 'Test 140');
test(areSentencesSimilar("Start with this", "Start with something in the middle this"), true, 'Test 141');
test(areSentencesSimilar("Qwen is a large language model", "Qwen is a language model"), true, 'Test 142');
test(areSentencesSimilar("The cat sat on the mat", "The cat sat on the brown mat"), true, 'Test 143');
test(areSentencesSimilar("Last word", "Last last last word"), true, 'Test 144');
test(areSentencesSimilar("Python is great for data science", "Python is great"), true, 'Test 145');
test(areSentencesSimilar("Quick brown fox jumps over the lazy dog", "Quick brown fox quickly jumps over the lazy dog"), true, 'Test 146');
test(areSentencesSimilar("It is a truth universally acknowledged", "It is a universally acknowledged"), true, 'Test 147');
test(areSentencesSimilar("Start and finish", "Start middle and finish"), true, 'Test 148');
test(areSentencesSimilar("SingleWord", "SingleWordInserted"), false, 'Test 149');
test(areSentencesSimilar("End with a sentence", "End with a sentence and more words"), true, 'Test 150');
test(areSentencesSimilar("Overlap at start", "Overlap at start and continue"), true, 'Test 151');
test(areSentencesSimilar("We hold these truths to be self evident", "We hold these self evident"), true, 'Test 152');
test(areSentencesSimilar("Once upon a time in a land far far away", "Once upon a time"), true, 'Test 153');
test(areSentencesSimilar("Java is a high level programming language", "Java is a high level programming language that is platform independent"), true, 'Test 154');
test(areSentencesSimilar("Similar beginning and end", "Similar beginning with extra words and end"), true, 'Test 155');
test(areSentencesSimilar("Hello from the other side", "Hello from the very very other side"), true, 'Test 156');
test(areSentencesSimilar("Quick brown fox jumps over lazy dog", "Quick brown fox jumps over the lazy dog"), true, 'Test 157');
test(areSentencesSimilar("Silence is golden", "Silence"), true, 'Test 158');
test(areSentencesSimilar("Middle insertion is key", "Middle insertion of some text is key"), true, 'Test 159');
test(areSentencesSimilar("To be or not to be that is the question", "To be or not to be"), true, 'Test 160');
test(areSentencesSimilar("This is a simple test", "This is an extremely simple and detailed test"), false, 'Test 161');
test(areSentencesSimilar("It was the best of times it was the worst of times", "It was the best of times"), true, 'Test 162');
test(areSentencesSimilar("Quick brown fox jumps over the lazy dog", "Quick brown fox jumps over the lazy brown dog"), true, 'Test 163');
test(areSentencesSimilar("Learning new things is fun", "Learning fun"), true, 'Test 164');
test(areSentencesSimilar("Life is a journey not a destination", "Life is a journey of ups and downs not a destination"), true, 'Test 165');
test(areSentencesSimilar("She sells sea shells by the sea shore", "She sells sea"), true, 'Test 166');
test(areSentencesSimilar("In the beginning God created the heaven and the earth", "In the beginning God created the earth"), true, 'Test 167');
test(areSentencesSimilar("Insert sentence here", "Insert sentence in the middle sentence here"), true, 'Test 168');
test(areSentencesSimilar("End with this", "End with this and something more"), true, 'Test 169');
test(areSentencesSimilar("Python is fun", "Python is very very fun"), true, 'Test 170');
test(areSentencesSimilar("Advanced machine learning techniques", "Advanced machine learning deep learning techniques"), true, 'Test 171');
test(areSentencesSimilar("Hello from the other side", "Hello from the other side my old friend"), true, 'Test 172');
test(areSentencesSimilar("Single word", "Single single word"), true, 'Test 173');
test(areSentencesSimilar("Time heals all wounds", "Time heals all wounds but sometimes it's better to face them head on"), true, 'Test 174');
test(areSentencesSimilar("One two three four five", "One two six seven eight nine five"), false, 'Test 175');
test(areSentencesSimilar("Same at the start", "Same at the start but different end"), true, 'Test 176');
test(areSentencesSimilar("All animals are equal", "All animals are equal but some animals are more equal than others"), true, 'Test 177');
test(areSentencesSimilar("The rain in Spain stays mainly in the plain", "The rain in Spain stays"), true, 'Test 178');
test(areSentencesSimilar("Multiple words in between", "Multiple multiple words in between"), true, 'Test 179');
test(areSentencesSimilar("Natural language processing is fascinating", "Natural language processing"), true, 'Test 180');
test(areSentencesSimilar("Hello my friend", "Hello my dear friend"), true, 'Test 181');
test(areSentencesSimilar("This is a test", "This is an amazing test"), false, 'Test 182');
test(areSentencesSimilar("Front and back", "Front middle back"), false, 'Test 183');
test(areSentencesSimilar("Complex sentences are fun", "Complex sentences with more words in between are fun"), true, 'Test 184');
test(areSentencesSimilar("Alice went to the market", "Alice went to the market to buy apples"), true, 'Test 185');
test(areSentencesSimilar("The early morning light", "The early morning light is so peaceful"), true, 'Test 186');
test(areSentencesSimilar("Same same same", "Same Same"), false, 'Test 187');
test(areSentencesSimilar("Same at the end", "Different start same at the end"), false, 'Test 188');
test(areSentencesSimilar("Beautiful day in the neighborhood", "Beautiful day in the beautiful neighborhood"), true, 'Test 189');
test(areSentencesSimilar("First second third", "First first first second third"), true, 'Test 190');
test(areSentencesSimilar("Hello from the other side", "Hello"), true, 'Test 191');
test(areSentencesSimilar("I have a dream", "I have a dream that one day this nation will rise up and live out the true meaning of its creed"), true, 'Test 192');
test(areSentencesSimilar("May the force be with you", "May the be with you"), true, 'Test 193');
test(areSentencesSimilar("OpenAI develops AI models", "OpenAI develops cutting edge AI models"), true, 'Test 194');
test(areSentencesSimilar("May the Force be with you", "May the Force be with you always"), true, 'Test 195');
test(areSentencesSimilar("Keep it simple", "Keep it simple stupid"), true, 'Test 196');
test(areSentencesSimilar("A short sentence", "A very very very short sentence"), true, 'Test 197');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

