// Test: 3485. Longest Common Prefix Of K Strings After Removal
// 196 test cases from LeetCodeDataset
// Run: node test.js

const { longestCommonPrefix } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n3485. Longest Common Prefix Of K Strings After Removal\n");

test(longestCommonPrefix(["banana","band","bend","bendy"], 3), [1, 1, 1, 1], 'Test 1');
test(longestCommonPrefix(["abcd","abce","abcf","abcg"], 2), [3, 3, 3, 3], 'Test 2');
test(longestCommonPrefix(["apple","application","aptitude","appetite"], 3), [2, 2, 3, 2], 'Test 3');
test(longestCommonPrefix(["aaa","aa","a"], 2), [1, 1, 2], 'Test 4');
test(longestCommonPrefix(["aaaa","aaa","aa","a"], 2), [2, 2, 3, 3], 'Test 5');
test(longestCommonPrefix(["jump","run","run","jump","run"], 2), [3, 4, 4, 3, 4], 'Test 6');
test(longestCommonPrefix(["apple","application","appetite"], 2), [3, 3, 4], 'Test 7');
test(longestCommonPrefix(["abcdefg","abcde","abcd","abc","ab","a"], 4), [2, 2, 2, 2, 3, 3], 'Test 8');
test(longestCommonPrefix(["a","a","a","a","a"], 3), [1, 1, 1, 1, 1], 'Test 9');
test(longestCommonPrefix(["abc","abcd","ab","abcde"], 3), [2, 2, 3, 2], 'Test 10');
test(longestCommonPrefix(["dog","racer","car"], 2), [0, 0, 0], 'Test 11');
test(longestCommonPrefix(["hello","hell","he","h"], 4), [0, 0, 0, 0], 'Test 12');
test(longestCommonPrefix(["abcd","abcde","ab","abc"], 3), [2, 2, 3, 2], 'Test 13');
test(longestCommonPrefix(["abc","abcd","abcde","abcdef"], 3), [4, 3, 3, 3], 'Test 14');
test(longestCommonPrefix(["cat","cater","category","catalog"], 2), [4, 3, 3, 4], 'Test 15');
test(longestCommonPrefix(["prefix","pre","preface","prefatory","presentation"], 3), [3, 4, 3, 3, 4], 'Test 16');
test(longestCommonPrefix(["banana","banan","ban","ba","b","bananaaa","bananas"], 3), [5, 6, 6, 6, 6, 5, 5], 'Test 17');
test(longestCommonPrefix(["abcdabcd","abcdabc","abcdab","abcd","abc","ab","a"], 4), [3, 3, 3, 3, 4, 4, 4], 'Test 18');
test(longestCommonPrefix(["programming","program","programmer","programmatic"], 4), [0, 0, 0, 0], 'Test 19');
test(longestCommonPrefix(["interview","inter","internal","interpretation","internet"], 3), [5, 5, 5, 5, 5], 'Test 20');
test(longestCommonPrefix(["prefix","preface","preference","pre","predict","prevent","preach","prelude"], 4), [3, 3, 3, 3, 3, 3, 3, 3], 'Test 21');
test(longestCommonPrefix(["hello","hell","he","helloworld","he"], 4), [2, 2, 2, 2, 2], 'Test 22');
test(longestCommonPrefix(["algorithm","algorithms","algo","al","algorith"], 3), [4, 4, 8, 8, 4], 'Test 23');
test(longestCommonPrefix(["sequence","sequential","succession","successive","succeed"], 4), [1, 1, 1, 1, 1], 'Test 24');
test(longestCommonPrefix(["optimization","optimize","optimal","optimum"], 3), [5, 5, 5, 5], 'Test 25');
test(longestCommonPrefix(["zebra","zebra","zebra","zebra","zebra"], 4), [5, 5, 5, 5, 5], 'Test 26');
test(longestCommonPrefix(["banana","bandana","band","bandwidth"], 3), [4, 3, 3, 3], 'Test 27');
test(longestCommonPrefix(["abcdefgh","abcde","abcd","abc","ab","a"], 3), [3, 3, 3, 4, 4, 4], 'Test 28');
test(longestCommonPrefix(["same","sam","sameple","sample","samp"], 3), [3, 3, 3, 3, 3], 'Test 29');
test(longestCommonPrefix(["prefix","pre","preface","preach","prelude"], 3), [3, 3, 3, 3, 3], 'Test 30');
test(longestCommonPrefix(["xxxxxxxxxx","xxxxxxxxx","xxxxxxxx","xxxxxxx","xxxxxx","xxxxx","xxxx","xxx","xx","x"], 5), [5, 5, 5, 5, 5, 6, 6, 6, 6, 6], 'Test 31');
test(longestCommonPrefix(["performance","perform","performanceanalysis","performant"], 4), [0, 0, 0, 0], 'Test 32');
test(longestCommonPrefix(["programming","programmer","program","pro","pr","p"], 2), [7, 7, 8, 8, 8, 8], 'Test 33');
test(longestCommonPrefix(["abcabcabc","abcabc","abc","ab","a"], 2), [3, 3, 6, 6, 6], 'Test 34');
test(longestCommonPrefix(["test","testing","tested","tests","tempest"], 4), [2, 2, 2, 2, 4], 'Test 35');
test(longestCommonPrefix(["longest","longer","long","lon","lo","l"], 3), [3, 3, 3, 4, 4, 4], 'Test 36');
test(longestCommonPrefix(["abcdabcd","abcdabcde","abcdabc","abcdab","abcd"], 3), [6, 6, 6, 7, 7], 'Test 37');
test(longestCommonPrefix(["algorithm","algebra","algorithmic","algae"], 2), [3, 9, 3, 9], 'Test 38');
test(longestCommonPrefix(["mississippi","mississipp","mississip","mississi","mississ","missis","missi","miss","mis","mi","m"], 5), [6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7], 'Test 39');
test(longestCommonPrefix(["unique","unite","unity","unit","universe"], 3), [4, 3, 3, 3, 4], 'Test 40');
test(longestCommonPrefix(["abcdefghijklmnopqrstuvwxyz","abcdefghijklmnopqrstuvwxyz","abcdefghijklmnopqrstuvwxyz","abcdefghijklmnopqrstuvwxyz","abcdefghijklmnopqrstuvwxyz"], 5), [0, 0, 0, 0, 0], 'Test 41');
test(longestCommonPrefix(["abacaxi","abacax","abac","aba","ab"], 2), [4, 4, 6, 6, 6], 'Test 42');
test(longestCommonPrefix(["communication","communicate","communicator","communications"], 3), [10, 10, 10, 10], 'Test 43');
test(longestCommonPrefix(["common","commonly","commonsense","commonplace","commonwealth"], 5), [0, 0, 0, 0, 0], 'Test 44');
test(longestCommonPrefix(["prefix","pre","predefined","premier","pressure"], 5), [0, 0, 0, 0, 0], 'Test 45');
test(longestCommonPrefix(["banana","bandana","banter","bandage","banner","bandwidth"], 5), [3, 3, 3, 3, 3, 3], 'Test 46');
test(longestCommonPrefix(["sun","sunny","sunshine","sunset","sunken","sunflower","sunrise","sundial"], 3), [3, 3, 3, 3, 3, 3, 3, 3], 'Test 47');
test(longestCommonPrefix(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"], 2), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Test 48');
test(longestCommonPrefix(["test","testing","tested","testify","testament"], 4), [4, 4, 4, 4, 4], 'Test 49');
test(longestCommonPrefix(["abc","abcd","abcde","abcdef","abcdefg"], 5), [0, 0, 0, 0, 0], 'Test 50');
test(longestCommonPrefix(["prefix","prefixing","prefixation","prefix","pre"], 3), [6, 6, 6, 6, 6], 'Test 51');
test(longestCommonPrefix(["algorithm","algebra","algorithmic","algorithmically","algebraic"], 4), [3, 3, 3, 3, 3], 'Test 52');
test(longestCommonPrefix(["banana","bananas","bandana","bandanas","band"], 4), [3, 3, 3, 3, 3], 'Test 53');
test(longestCommonPrefix(["cat","cater","category","catalog","catalogue","catalogued","cataloging"], 6), [3, 3, 3, 3, 3, 3, 3], 'Test 54');
test(longestCommonPrefix(["xylophone","xylography","xylophon","xylo","xy","x"], 3), [4, 4, 4, 4, 4, 4], 'Test 55');
test(longestCommonPrefix(["inter","interact","interactive","interface","interleave","interchange","interconnect","intercept","interdependent"], 7), [5, 5, 5, 5, 5, 5, 5, 5, 5], 'Test 56');
test(longestCommonPrefix(["cloud","cloudy","cloudstorage","cloudservices"], 3), [5, 5, 5, 5], 'Test 57');
test(longestCommonPrefix(["abacaxi","abacax","abaca","abac","aba","ab","a"], 4), [3, 3, 3, 3, 4, 4, 4], 'Test 58');
test(longestCommonPrefix(["abacaxi","banana","abacax","bacana","bacaxa"], 3), [2, 0, 2, 0, 0], 'Test 59');
test(longestCommonPrefix(["prefix","preface","prefect","prefer","prelude"], 4), [3, 3, 3, 3, 4], 'Test 60');
test(longestCommonPrefix(["algorithm","algebra","algorithmic","algal","algae","algorithmically","algorithmically"], 5), [3, 3, 3, 3, 3, 3, 3], 'Test 61');
test(longestCommonPrefix(["aabbcc","aabb","aab","aa","a"], 3), [2, 2, 2, 3, 3], 'Test 62');
test(longestCommonPrefix(["banana","bandana","band","bandit","bandwidth"], 4), [4, 3, 3, 3, 3], 'Test 63');
test(longestCommonPrefix(["hello","hell","helo","hallo","heaven"], 3), [2, 2, 2, 3, 3], 'Test 64');
test(longestCommonPrefix(["intersection","inter","interact","interactive"], 2), [8, 8, 5, 5], 'Test 65');
test(longestCommonPrefix(["datastructure","data","database","dataanalysis"], 4), [0, 0, 0, 0], 'Test 66');
test(longestCommonPrefix(["banana","bandana","band","bandanna","bang","ban","banner"], 3), [4, 3, 3, 3, 4, 4, 4], 'Test 67');
test(longestCommonPrefix(["hello","hell","helo","hella","hellomy","hellomyworld"], 4), [4, 4, 4, 4, 4, 4], 'Test 68');
test(longestCommonPrefix(["programming","program","pro","process","processor"], 5), [0, 0, 0, 0, 0], 'Test 69');
test(longestCommonPrefix(["programming","programmer","procrastinate","profession","process"], 4), [3, 3, 3, 3, 3], 'Test 70');
test(longestCommonPrefix(["elephant","elephante","elephant","elephant","eleph","ele","e"], 3), [8, 8, 8, 8, 8, 8, 8], 'Test 71');
test(longestCommonPrefix(["flower","flow","flight","flew","flour"], 2), [3, 3, 4, 4, 4], 'Test 72');
test(longestCommonPrefix(["elephant","elephant","elephant","elephant","elephant","elephant"], 5), [8, 8, 8, 8, 8, 8], 'Test 73');
test(longestCommonPrefix(["different","difficult","difficulty","differently","differ"], 4), [4, 4, 4, 4, 4], 'Test 74');
test(longestCommonPrefix(["programming","program","programmer","programm","programmi","programmin","programmin"], 4), [8, 9, 9, 9, 8, 8, 8], 'Test 75');
test(longestCommonPrefix(["abcdefg","abcdef","abcde","abcd","abc"], 2), [5, 5, 6, 6, 6], 'Test 76');
test(longestCommonPrefix(["test","testing","tested","testing","testify","testament"], 3), [5, 4, 5, 4, 4, 5], 'Test 77');
test(longestCommonPrefix(["abcdefghij","abcdefghi","abcdefgh","abcdefg","abcdef","abcde","abcd","abc","ab","a"], 5), [5, 5, 5, 5, 5, 6, 6, 6, 6, 6], 'Test 78');
test(longestCommonPrefix(["supercalifragilisticexpialidocious","super","supercalifragilistic","superex","supercalifragil"], 4), [5, 5, 5, 5, 5], 'Test 79');
test(longestCommonPrefix(["algorithm","algebra","algorithmic","alibi","alias"], 2), [3, 9, 3, 9, 9], 'Test 80');
test(longestCommonPrefix(["aabbcc","aabb","aabc","aab","aac","aa","ab","ac","a"], 3), [3, 3, 3, 3, 3, 3, 3, 3, 3], 'Test 81');
test(longestCommonPrefix(["prefix","prefixes","prefixing","pref","pre"], 5), [0, 0, 0, 0, 0], 'Test 82');
test(longestCommonPrefix(["banana","band","ban","bandana","bandwidth"], 3), [4, 3, 4, 3, 3], 'Test 83');
test(longestCommonPrefix(["flower","flow","flight","flew","fly"], 4), [2, 2, 2, 2, 2], 'Test 84');
test(longestCommonPrefix(["abcd","abcde","ab","abc","a","abca","abcd"], 4), [3, 3, 3, 3, 3, 3, 3], 'Test 85');
test(longestCommonPrefix(["repeated","repeat","repetition","repetitive","repel"], 3), [4, 4, 4, 4, 4], 'Test 86');
test(longestCommonPrefix(["flower","flow","flight","flock","flour","flat","flog"], 3), [3, 3, 3, 3, 3, 3, 3], 'Test 87');
test(longestCommonPrefix(["prefix","pre","precondition","preference"], 3), [3, 3, 3, 3], 'Test 88');
test(longestCommonPrefix(["repeated","repeatedly","rep","repeat","repe"], 3), [4, 4, 6, 4, 6], 'Test 89');
test(longestCommonPrefix(["flower","flow","flight","flour","flourish","flourish","flourish"], 5), [3, 3, 3, 3, 3, 3, 3], 'Test 90');
test(longestCommonPrefix(["prefix","pre","predict","precondition","prevent","precedent"], 4), [3, 3, 3, 3, 3, 3], 'Test 91');
test(longestCommonPrefix(["xylophone","xenon","xylography","xylo","xylophoneography"], 2), [4, 9, 9, 9, 4], 'Test 92');
test(longestCommonPrefix(["small","smaller","smallest","smallests","smallestest"], 5), [0, 0, 0, 0, 0], 'Test 93');
test(longestCommonPrefix(["distinct","distinguish","distant","distortion","distract","distrust"], 4), [4, 4, 4, 4, 4, 4], 'Test 94');
test(longestCommonPrefix(["unique","uniqueness","un","uniq","uniquer"], 4), [2, 2, 4, 2, 2], 'Test 95');
test(longestCommonPrefix(["aaa","bbb","aaa","bbb","aaa","bbb"], 3), [3, 3, 3, 3, 3, 3], 'Test 96');
test(longestCommonPrefix(["test","testing","tested","testing","testify"], 2), [7, 5, 7, 5, 7], 'Test 97');
test(longestCommonPrefix(["programming","program","programmer","pro","programming"], 3), [7, 8, 7, 8, 7], 'Test 98');
test(longestCommonPrefix(["aaaaa","aaa","aa","a","abcd","abc","ab","a"], 3), [2, 2, 2, 2, 2, 2, 2, 2], 'Test 99');
test(longestCommonPrefix(["abcd","abcde","abcdef","abcdefg","abcdefgh","abcdefghi"], 5), [5, 4, 4, 4, 4, 4], 'Test 100');
test(longestCommonPrefix(["algorithm","algori","algor","algo","alg","al","a","algorithmic","algorith","algorithmically"], 6), [4, 4, 4, 5, 5, 5, 5, 4, 4, 4], 'Test 101');
test(longestCommonPrefix(["consistent","consistency","consist","cons","con","co","c"], 3), [4, 4, 4, 7, 7, 7, 7], 'Test 102');
test(longestCommonPrefix(["civic","civ","city","citizens","citizen","citize","citizi"], 5), [3, 3, 2, 2, 2, 2, 2], 'Test 103');
test(longestCommonPrefix(["aaaab","aaab","aab","ab","b"], 2), [2, 2, 3, 3, 3], 'Test 104');
test(longestCommonPrefix(["consistent","consistency","consist","cons","con"], 3), [4, 4, 4, 7, 7], 'Test 105');
test(longestCommonPrefix(["abacaxi","abacax","abac","aba","ab","a"], 5), [1, 1, 1, 1, 1, 2], 'Test 106');
test(longestCommonPrefix(["supercalifragilisticexpialidocious","super","supercal","supercali","superca"], 2), [8, 9, 9, 8, 9], 'Test 107');
test(longestCommonPrefix(["banana","bandana","band","ban","ba","b"], 3), [3, 3, 3, 3, 3, 3], 'Test 108');
test(longestCommonPrefix(["aabbcc","aabbc","aabb","aab","aa","a"], 4), [2, 2, 2, 2, 3, 3], 'Test 109');
test(longestCommonPrefix(["longest","longer","long","lo","l","longestword"], 4), [2, 2, 2, 4, 4, 2], 'Test 110');
test(longestCommonPrefix(["repetition","rep","repet","repetit","repetiti"], 3), [5, 7, 7, 5, 5], 'Test 111');
test(longestCommonPrefix(["test","testing","tested","tes"], 3), [3, 3, 3, 4], 'Test 112');
test(longestCommonPrefix(["prefix","pre","pref","prefer"], 3), [3, 4, 3, 3], 'Test 113');
test(longestCommonPrefix(["abcd","abce","abcf"], 2), [3, 3, 3], 'Test 114');
test(longestCommonPrefix(["abcd","abc","ab","a"], 3), [1, 1, 1, 2], 'Test 115');
test(longestCommonPrefix(["hello","hell","heaven","heavy"], 2), [4, 4, 4, 4], 'Test 116');
test(longestCommonPrefix(["abcd","abce","abcf","abcg"], 4), [0, 0, 0, 0], 'Test 117');
test(longestCommonPrefix(["aaaaa","aaaab","aaabb","aabbb","abbbb"], 3), [2, 2, 2, 3, 3], 'Test 118');
test(longestCommonPrefix(["dog","racer","car"], 2), [0, 0, 0], 'Test 119');
test(longestCommonPrefix(["a","b","c","d","e"], 1), [1, 1, 1, 1, 1], 'Test 120');
test(longestCommonPrefix(["hello","world","help","hero"], 2), [2, 3, 2, 3], 'Test 121');
test(longestCommonPrefix(["interspecies","interstellar","interstate"], 2), [7, 6, 6], 'Test 122');
test(longestCommonPrefix(["one","once","on","oneone"], 2), [2, 3, 3, 2], 'Test 123');
test(longestCommonPrefix(["abcde","abcdf","abcda","abcdz"], 3), [4, 4, 4, 4], 'Test 124');
test(longestCommonPrefix(["aaaa","aaa","aa","a"], 3), [1, 1, 1, 2], 'Test 125');
test(longestCommonPrefix(["prefix","preface","prefer","preach"], 2), [4, 4, 4, 4], 'Test 126');
test(longestCommonPrefix(["abc","abcd","abcde","abcdef","abcdefg"], 4), [4, 3, 3, 3, 3], 'Test 127');
test(longestCommonPrefix(["abc","abcd","abcde","abcdef"], 2), [5, 5, 4, 4], 'Test 128');
test(longestCommonPrefix(["flower","flow","flight","flute"], 3), [2, 2, 2, 2], 'Test 129');
test(longestCommonPrefix(["flower","flow","flight","floor"], 2), [3, 3, 4, 4], 'Test 130');
test(longestCommonPrefix(["abcd","abce","abcf"], 2), [3, 3, 3], 'Test 131');
test(longestCommonPrefix(["flower","flow","flight"], 2), [2, 2, 4], 'Test 132');
test(longestCommonPrefix(["abc","abcd","abcde"], 3), [0, 0, 0], 'Test 133');
test(longestCommonPrefix(["hello","help","hold"], 2), [1, 1, 3], 'Test 134');
test(longestCommonPrefix(["abc","abcd","abcde","abcdef"], 4), [0, 0, 0, 0], 'Test 135');
test(longestCommonPrefix(["test","taste","testing","temple"], 2), [2, 4, 2, 4], 'Test 136');
test(longestCommonPrefix(["apple","applet","application"], 3), [0, 0, 0], 'Test 137');
test(longestCommonPrefix(["a","a","a","a","a"], 5), [0, 0, 0, 0, 0], 'Test 138');
test(longestCommonPrefix(["a","b","c","d","e","f","g","h","i","j"], 4), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Test 139');
test(longestCommonPrefix(["aaa","aa","a"], 2), [1, 1, 2], 'Test 140');
test(longestCommonPrefix(["hello","hell","he","h"], 2), [2, 2, 4, 4], 'Test 141');
test(longestCommonPrefix(["flower","flow","flight","flour"], 3), [2, 2, 3, 2], 'Test 142');
test(longestCommonPrefix(["abc","abcd","abcde"], 3), [0, 0, 0], 'Test 143');
test(longestCommonPrefix(["prefix","preform","preference","prelude"], 3), [3, 3, 3, 4], 'Test 144');
test(longestCommonPrefix(["a","a","a","a","a"], 2), [1, 1, 1, 1, 1], 'Test 145');
test(longestCommonPrefix(["prefix","pre","pref","prefer","prefi"], 4), [3, 4, 3, 3, 3], 'Test 146');
test(longestCommonPrefix(["apple","application","apt","appetite"], 3), [2, 2, 3, 2], 'Test 147');
test(longestCommonPrefix(["prefix","pre","pref","prefer"], 2), [4, 4, 4, 4], 'Test 148');
test(longestCommonPrefix(["a","b","c","d","e","f","g","h","i","j"], 3), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Test 149');
test(longestCommonPrefix(["distinct","words","only","here"], 3), [0, 0, 0, 0], 'Test 150');
test(longestCommonPrefix(["abc","abc","abc","abc","abc"], 5), [0, 0, 0, 0, 0], 'Test 151');
test(longestCommonPrefix(["flower","flow","flight","flour"], 2), [3, 3, 4, 4], 'Test 152');
test(longestCommonPrefix(["aaaa","aaab","aaac","aabb"], 3), [2, 2, 2, 3], 'Test 153');
test(longestCommonPrefix(["abcde","abcdf","abcda","abcdb"], 4), [0, 0, 0, 0], 'Test 154');
test(longestCommonPrefix(["abc","abcde","abcdf"], 3), [0, 0, 0], 'Test 155');
test(longestCommonPrefix(["flower","flow","flight","fluent"], 3), [2, 2, 2, 2], 'Test 156');
test(longestCommonPrefix(["a"], 1), [0], 'Test 157');
test(longestCommonPrefix(["abcd","abcde","abcdef","abcdefg","abcdefgh"], 2), [7, 7, 7, 6, 6], 'Test 158');
test(longestCommonPrefix(["aaaaa","aaaab","aaabb","aabbb","abbbb"], 4), [1, 1, 1, 1, 2], 'Test 159');
test(longestCommonPrefix(["same","same","same"], 2), [4, 4, 4], 'Test 160');
test(longestCommonPrefix(["aaaa","aa","aaa","a","aaaaa"], 2), [3, 4, 4, 4, 3], 'Test 161');
test(longestCommonPrefix(["aabb","aabc","aabd","aabe"], 3), [3, 3, 3, 3], 'Test 162');
test(longestCommonPrefix(["distinct","words","are","here"], 2), [0, 0, 0, 0], 'Test 163');
test(longestCommonPrefix(["abc","abcd","abce","abcdef"], 3), [3, 3, 3, 3], 'Test 164');
test(longestCommonPrefix(["prefix","pre","prepend","presume"], 3), [3, 3, 3, 3], 'Test 165');
test(longestCommonPrefix(["throne","throne","throne","throne"], 3), [6, 6, 6, 6], 'Test 166');
test(longestCommonPrefix(["prefix","prefix","prefix","prefix","prefix"], 4), [6, 6, 6, 6, 6], 'Test 167');
test(longestCommonPrefix(["abab","aba",""], 2), [0, 0, 3], 'Test 168');
test(longestCommonPrefix(["test","testing","testcase","testing","testcases"], 3), [4, 4, 4, 4, 4], 'Test 169');
test(longestCommonPrefix(["apple","application","appetite","appreciate"], 3), [3, 3, 3, 3], 'Test 170');
test(longestCommonPrefix(["hello","hell","he","h"], 3), [1, 1, 1, 2], 'Test 171');
test(longestCommonPrefix(["abcd","abc","ab","a"], 2), [2, 2, 3, 3], 'Test 172');
test(longestCommonPrefix(["banana","bandana","ban","band","bandana"], 4), [3, 3, 3, 3, 3], 'Test 173');
test(longestCommonPrefix(["interspecies","interstellar","interstate"], 3), [0, 0, 0], 'Test 174');
test(longestCommonPrefix(["aaaa","aa","aaa","aaaaa"], 3), [2, 3, 2, 2], 'Test 175');
test(longestCommonPrefix(["apple","application","app","applet","apples"], 2), [5, 5, 5, 5, 5], 'Test 176');
test(longestCommonPrefix(["abcd","abce","abcf","abcg"], 3), [3, 3, 3, 3], 'Test 177');
test(longestCommonPrefix(["a","a","a","a"], 2), [1, 1, 1, 1], 'Test 178');
test(longestCommonPrefix(["hello","hell","he","helloworld"], 4), [0, 0, 0, 0], 'Test 179');
test(longestCommonPrefix(["prefix","preface","presentation","preference","prestige"], 4), [3, 3, 3, 3, 3], 'Test 180');
test(longestCommonPrefix(["prefix","pre","predict","printing"], 2), [3, 3, 3, 3], 'Test 181');
test(longestCommonPrefix(["a","a","a","a","a","a","a","a","a","a"], 5), [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'Test 182');
test(longestCommonPrefix(["aaaa","aabb","aabc","aacc"], 3), [2, 2, 2, 2], 'Test 183');
test(longestCommonPrefix(["aaaa","bbbb","cccc","dddd"], 2), [0, 0, 0, 0], 'Test 184');
test(longestCommonPrefix(["apple","app","application","appetite"], 2), [3, 4, 3, 4], 'Test 185');
test(longestCommonPrefix(["jump","run","run","jump","run"], 2), [3, 4, 4, 3, 4], 'Test 186');
test(longestCommonPrefix(["a","b","c","d","e","f","g","h","i","j"], 5), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Test 187');
test(longestCommonPrefix(["same","same","same","same"], 2), [4, 4, 4, 4], 'Test 188');
test(longestCommonPrefix(["abcdefg","abcdef","abcde","abcd"], 2), [5, 5, 6, 6], 'Test 189');
test(longestCommonPrefix(["prefix","preform","president","presentation"], 2), [4, 4, 4, 4], 'Test 190');
test(longestCommonPrefix(["aaaa","aaaa","aaaa","aaaa"], 4), [0, 0, 0, 0], 'Test 191');
test(longestCommonPrefix(["hello","he","hell","helper"], 2), [3, 4, 3, 4], 'Test 192');
test(longestCommonPrefix(["prefix","pre","pref","prefer","preference"], 4), [3, 4, 3, 3, 3], 'Test 193');
test(longestCommonPrefix(["prefix","pre","prepend","prevent"], 3), [3, 3, 3, 3], 'Test 194');
test(longestCommonPrefix(["same","same","same","same","same"], 4), [4, 4, 4, 4, 4], 'Test 195');
test(longestCommonPrefix(["hello","hell","heaven","heavy"], 3), [2, 2, 2, 2], 'Test 196');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

