// Test: 2785. Sort Vowels In A String
// 150 test cases from LeetCodeDataset
// Run: node test.js

const { sortVowels } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n2785. Sort Vowels In A String\n");

test(sortVowels("b"), b, 'Test 1');
test(sortVowels("bCdEfGhIjK"), bCdEfGhIjK, 'Test 2');
test(sortVowels("abcdefghijklmnopqrstuvwxyz"), abcdefghijklmnopqrstuvwxyz, 'Test 3');
test(sortVowels("AEIOUaeiou"), AEIOUaeiou, 'Test 4');
test(sortVowels("uoiea"), aeiou, 'Test 5');
test(sortVowels("AbEcIdOfUg"), AbEcIdOfUg, 'Test 6');
test(sortVowels("aAeEiIoOuU"), AEIOUaeiou, 'Test 7');
test(sortVowels("ThIsIsAtEsTcAsE"), ThAsAsEtEsTcIsI, 'Test 8');
test(sortVowels("SortingVowels"), SertingVowols, 'Test 9');
test(sortVowels("a"), a, 'Test 10');
test(sortVowels("ABCDEFGHIJKLMNOPQRSTUVWXYZ"), ABCDEFGHIJKLMNOPQRSTUVWXYZ, 'Test 11');
test(sortVowels("aBcDeFgHiJkLmNoPqRsTuVwXyZ"), aBcDeFgHiJkLmNoPqRsTuVwXyZ, 'Test 12');
test(sortVowels("aeiouAEIOU"), AEIOUaeiou, 'Test 13');
test(sortVowels(""), , 'Test 14');
test(sortVowels("aAbBcCdDeEfFgGiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ"), AEbBcCdDIOfFgGUajJkKlLmMnNeipPqQrRsStTouvVwWxXyYzZ, 'Test 15');
test(sortVowels("lEetcOde"), lEOtcede, 'Test 16');
test(sortVowels("ZyXwVutSrQpOnMlKjIhGfEdCbA"), ZyXwVAtSrQpEnMlKjIhGfOdCbu, 'Test 17');
test(sortVowels("ZYXWVUTSRQPONMLKJIHGFEDCBA"), ZYXWVATSRQPENMLKJIHGFODCBU, 'Test 18');
test(sortVowels("lYmpH"), lYmpH, 'Test 19');
test(sortVowels("Consonants"), Cansononts, 'Test 20');
test(sortVowels("aEIoU"), EIUao, 'Test 21');
test(sortVowels("AEIOU"), AEIOU, 'Test 22');
test(sortVowels("uUuUuUuUuUuUuUuUuUuUuUuUuUuU"), UUUUUUUUUUUUUUuuuuuuuuuuuuuu, 'Test 23');
test(sortVowels("mIxEdcAsEvOwElScOnSoNnTs"), mAxEdcEsEvIwOlScOnSoNnTs, 'Test 24');
test(sortVowels("rEvErsE"), rEvErsE, 'Test 25');
test(sortVowels("mIxEdCaSeVoWels"), mExIdCaSeVeWols, 'Test 26');
test(sortVowels("ThIsIsAVeRyLoNgStRiNgWhItHaMuLtIpLeVoWels"), ThAsIsIVIRyLINgStRaNgWhetHeMeLtipLoVoWuls, 'Test 27');
test(sortVowels("aBbAcCcAdDeE"), ABbAcCcEdDae, 'Test 28');
test(sortVowels("AeIoUeIoUaEiOuaEiOueIoU"), AEEIIIOOUUUaaeeeiiooouu, 'Test 29');
test(sortVowels("sAd"), sAd, 'Test 30');
test(sortVowels("bYpHtRfjK"), bYpHtRfjK, 'Test 31');
test(sortVowels("UnIvErSiTy"), EnIvUrSiTy, 'Test 32');
test(sortVowels("aEiOuAeIoUaEiOuAeIoUaEiOu"), AAEEEIIOOOUUaaaeeiiioouuu, 'Test 33');
test(sortVowels("UPPERCASE"), APPERCESU, 'Test 34');
test(sortVowels("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"), AbcdEfghIjklmnOpqrstUvwxyzaBCDeFGHiJKLMNoPQRSTuVWXYZ, 'Test 35');
test(sortVowels("pYtHoNpRoGrAmMiNg"), pYtHANpRiGromMoNg, 'Test 36');
test(sortVowels("bBcCdDfFgGhHjJkKlLmMpPqQrRsStTvVwWxXyYzZ"), bBcCdDfFgGhHjJkKlLmMpPqQrRsStTvVwWxXyYzZ, 'Test 37');
test(sortVowels("bCdfGhjklmnpqrstvwxyz"), bCdfGhjklmnpqrstvwxyz, 'Test 38');
test(sortVowels("ThiSisAnExAmPlE"), ThASAsEnEximPli, 'Test 39');
test(sortVowels("HELLOworld"), HELLOworld, 'Test 40');
test(sortVowels("VowelsVowelsVowels"), VewelsVewolsVowols, 'Test 41');
test(sortVowels("fEaIoUeIaO"), fEIIOUaaeo, 'Test 42');
test(sortVowels("vOwElsInThEmIdDlE"), vEwElsEnThImIdDlO, 'Test 43');
test(sortVowels("uUoOiIeEaAA"), AAEIOUaeiou, 'Test 44');
test(sortVowels("ThiSisAEeIoU"), ThASEsIUeiio, 'Test 45');
test(sortVowels("VoWeLs12345"), VeWoLs12345, 'Test 46');
test(sortVowels("sTrInGwItHvErYsMaLlVoWels"), sTrEnGwItHvIrYsMaLlVeWols, 'Test 47');
test(sortVowels("cOnSoN4nt55tR1nGw1th1NoVoW3ls"), cOnSoN4nt55tR1nGw1th1NoVoW3ls, 'Test 48');
test(sortVowels("ThIsIsAVeRyLoNgStRiNgThAtCoNTaInSaLlThEvOwElScInDiFfErEnTcAsEs"), ThAsAsAVERyLENgStRENgThEtCENTIInSILlThIvOwalScanDeFfirinTcosos, 'Test 49');
test(sortVowels("uoieaUOIEA"), AEIOUaeiou, 'Test 50');
test(sortVowels("pythonProgramming"), pythanPrigrommong, 'Test 51');
test(sortVowels("vowelVowelVowel"), vewelVewolVowol, 'Test 52');
test(sortVowels("Vowels"), Vewols, 'Test 53');
test(sortVowels("Th1s1s4t3stW1thS0m3N0Nv0w3ls"), Th1s1s4t3stW1thS0m3N0Nv0w3ls, 'Test 54');
test(sortVowels("aAaAaAaAaAaA"), AAAAAAaaaaaa, 'Test 55');
test(sortVowels("MixedCASEaeiou"), MAxEdCaSeeiiou, 'Test 56');
test(sortVowels("vOwElsShOuLdBeSoRtEd"), vEwElsShOOLdBeSoRtud, 'Test 57');
test(sortVowels("aAaAaAaAaAaAaAaAaAaAaAaAaA"), AAAAAAAAAAAAAaaaaaaaaaaaaa, 'Test 58');
test(sortVowels("VoWaElScOlE"), VEWEOlScalo, 'Test 59');
test(sortVowels("bcdfghjklmnpqrstvwxyzAEIOU"), bcdfghjklmnpqrstvwxyzAEIOU, 'Test 60');
test(sortVowels("eEeEoOiIuUaAA"), AAEEIOUaeeiou, 'Test 61');
test(sortVowels("mEaTbAlL"), mAETbalL, 'Test 62');
test(sortVowels("uUoOiIaAeE"), AEIOUaeiou, 'Test 63');
test(sortVowels("UPPERCASEAEIOU"), APPARCESEEIOUU, 'Test 64');
test(sortVowels("ZyXwVuTsRqPoNmLkJiHgFeDcBa"), ZyXwVaTsRqPeNmLkJiHgFoDcBu, 'Test 65');
test(sortVowels("QwErTyUiOpAsDfGhJkLzXcVbNm"), QwArTyEOUpisDfGhJkLzXcVbNm, 'Test 66');
test(sortVowels("bAnAnA"), bAnAnA, 'Test 67');
test(sortVowels("vOwElScOnSoNnTsWiThMiXeDcAsE"), vAwElScEnSONnTsWOThMeXiDciso, 'Test 68');
test(sortVowels("ThEQUICKBRoWNfOxJUmpEDoVERtHElAZYdOG"), ThAQEECKBREWNfExJImpODOVURtHUloZYdoG, 'Test 69');
test(sortVowels("AEIOUaeiouAEIOUaeiou"), AAEEIIOOUUaaeeiioouu, 'Test 70');
test(sortVowels("CoMpLeXsTrInGwItHoUtvOwElS"), CEMpLIXsTrInGwOtHUetvowolS, 'Test 71');
test(sortVowels("aeiouAEIOUbcdfghjklmnpqrstvwxyz"), AEIOUaeioubcdfghjklmnpqrstvwxyz, 'Test 72');
test(sortVowels("Mississippi"), Mississippi, 'Test 73');
test(sortVowels("qwertyUIOP"), qwIrtyOUeP, 'Test 74');
test(sortVowels("MixedWithVowelsAndConsonants"), MAxadWethVewilsindConsononts, 'Test 75');
test(sortVowels("Th1s1s1a1n1Ex1Am1Pl1E"), Th1s1s1A1n1Ex1Em1Pl1a, 'Test 76');
test(sortVowels("hApPy"), hApPy, 'Test 77');
test(sortVowels("bBbBbBbBbBbB"), bBbBbBbBbBbB, 'Test 78');
test(sortVowels("UoIeA"), AIUeo, 'Test 79');
test(sortVowels("fLkDjGhtY"), fLkDjGhtY, 'Test 80');
test(sortVowels("mIxEdVoWElScAsE"), mAxEdVEWElScIso, 'Test 81');
test(sortVowels("iIiIiIiIiIiIiIiIiIiIiIiIiIiI"), IIIIIIIIIIIIIIiiiiiiiiiiiiii, 'Test 82');
test(sortVowels("aAAAAAeiouuuuuuuuuuuuu"), AAAAAaeiouuuuuuuuuuuuu, 'Test 83');
test(sortVowels("vowelsAndConsonants"), vAwalsendConsononts, 'Test 84');
test(sortVowels("AeIoUxyZ"), AIUeoxyZ, 'Test 85');
test(sortVowels("mIxEdCaSe"), mExIdCaSe, 'Test 86');
test(sortVowels("Lowercaseaeiou"), Lawarceseeioou, 'Test 87');
test(sortVowels("Alphabetical"), Alphabatecil, 'Test 88');
test(sortVowels("tHeQuIcKBrOwNBrownFoxJumpsOverLaZyDog"), tHIQOOcKBrawNBrewnFexJompsovorLuZyDug, 'Test 89');
test(sortVowels("ThIsIsAVeRyLoNgStRiNgWitHaLoTofVoWels"), ThAsIsIVaRyLeNgStReNgWitHiLoTofVoWols, 'Test 90');
test(sortVowels("vowel"), vewol, 'Test 91');
test(sortVowels("aAeE"), AEae, 'Test 92');
test(sortVowels("AeIoUaEiOuAEIOUaeiouAEIOU"), AAAEEEIIIOOOUUUaaeeiioouu, 'Test 93');
test(sortVowels("tRiUmPh"), tRUimPh, 'Test 94');
test(sortVowels("sTrInGwItHmUlTiPlEvOwEl"), sTrEnGwEtHmIlTIPlOvUwil, 'Test 95');
test(sortVowels("dFdFdFdFdFdFdFdFdfDFDF"), dFdFdFdFdFdFdFdFdfDFDF, 'Test 96');
test(sortVowels("VowElScOdInG"), VEwIlScOdonG, 'Test 97');
test(sortVowels("aAeEiIoOuUaAeEiIoOuU"), AAEEIIOOUUaaeeiioouu, 'Test 98');
test(sortVowels("aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZ"), aBcDaFgHeJkLmNePqRsTiVwXyZiBcDoFgHoJkLmNuPqRsTuVwXyZ, 'Test 99');
test(sortVowels("auDiEnCe"), EaDeinCu, 'Test 100');
test(sortVowels("bcdfghjklmnpqrstvwxyz"), bcdfghjklmnpqrstvwxyz, 'Test 101');
test(sortVowels("aAaAaAaAaAaAaAaAaAaAaAaA"), AAAAAAAAAAAAaaaaaaaaaaaa, 'Test 102');
test(sortVowels("ProgrammingIsFun"), PrIgrammingosFun, 'Test 103');
test(sortVowels("MultipleVowels"), MeltepliVowuls, 'Test 104');
test(sortVowels("aAAAAAAAAAAAAAAAAAAAAAAAAAAAAa"), AAAAAAAAAAAAAAAAAAAAAAAAAAAAaa, 'Test 105');
test(sortVowels("aEiOuAeIoU"), AEIOUaeiou, 'Test 106');
test(sortVowels("ThIsIsAComPlExStRiNgWitHvArIoUsVoWElS"), ThAsAsECEmPlIxStRINgWItHvUriiosVoWolS, 'Test 107');
test(sortVowels("sOrTiNg"), sOrTiNg, 'Test 108');
test(sortVowels("aEiOuBCDFG"), EOaiuBCDFG, 'Test 109');
test(sortVowels("oOoOoOoOoOoOoOoOoOoOoOoOoOoO"), OOOOOOOOOOOOOOoooooooooooooo, 'Test 110');
test(sortVowels("lowercase"), lawerceso, 'Test 111');
test(sortVowels("consonantsConsonantsVowelsVowels"), cansanentsCensonontsVowolsVowols, 'Test 112');
test(sortVowels("aEiOuAeIouAeIouAeIouAeIou"), AAAAEIIIIOaeeeeioooouuuuu, 'Test 113');
test(sortVowels("bbbbbbbbbbbbbbbbbAEIOU"), bbbbbbbbbbbbbbbbbAEIOU, 'Test 114');
test(sortVowels("abcdefgABCDEFGhijklmHIJKLmnopqrNOPQRSTuvwxyzUVWXYS"), AbcdEfgIBCDOFGhUjklmHaJKLmnepqrNiPQRSTovwxyzuVWXYS, 'Test 115');
test(sortVowels("vErYlArGeInPuTStRiNgWiThMaNyVoWels"), vArYlErGIanPeTStReNgWiThMiNyVoWuls, 'Test 116');
test(sortVowels("zyxwvutsrqponmlkjihgfedcba"), zyxwvatsrqpenmlkjihgfodcbu, 'Test 117');
test(sortVowels("vowelVOWELvowelVOWEL"), vEwElVOWOLvewelVoWoL, 'Test 118');
test(sortVowels("bCdfGhJklMnpQrStVwXz"), bCdfGhJklMnpQrStVwXz, 'Test 119');
test(sortVowels("cOdInGqUeStIoN"), cIdInGqOUSteoN, 'Test 120');
test(sortVowels("ThIsIsAtEsT"), ThAsEsItIsT, 'Test 121');
test(sortVowels("pRoGrAmMiNg"), pRAGrimMoNg, 'Test 122');
test(sortVowels("Th1sStR1nGh4sN0Nv0w3l5"), Th1sStR1nGh4sN0Nv0w3l5, 'Test 123');
test(sortVowels("AaEeIiOoUuAaEeIiOoUu"), AAEEIIOOUUaaeeiioouu, 'Test 124');
test(sortVowels("mIxEdVoWelsInThEString"), mExEdVIWIlsenThiStrong, 'Test 125');
test(sortVowels("aBCdEFGhIJKLmNoPQrSTuVwXyZ"), EBCdIFGhaJKLmNoPQrSTuVwXyZ, 'Test 126');
test(sortVowels("aAAAAA"), AAAAAa, 'Test 127');
test(sortVowels("VowelsAndConsonants"), VAwalsendConsononts, 'Test 128');
test(sortVowels("UniqueVowels"), UneqeiVowuls, 'Test 129');
test(sortVowels("joyFul"), joyFul, 'Test 130');
test(sortVowels("vOwElMvOwElMvOwElMvOwElM"), vEwElMvEwElMvOwOlMvOwOlM, 'Test 131');
test(sortVowels("VowelsMixed"), VewelsMixod, 'Test 132');
test(sortVowels("vOwElS98765"), vEwOlS98765, 'Test 133');
test(sortVowels("UeOiAaUeOiAaUeOiAaUeOiAa"), AAAAOOOOUUUUaaaaeeeeiiii, 'Test 134');
test(sortVowels("cOdInG"), cIdOnG, 'Test 135');
test(sortVowels("eEeEeEeEeEeEeEeEeEeEeEeEeE"), EEEEEEEEEEEEEeeeeeeeeeeeee, 'Test 136');
test(sortVowels("bBbBbBbBbBbBbBbBbBbBbBbB"), bBbBbBbBbBbBbBbBbBbBbBbB, 'Test 137');
test(sortVowels("fghijklmno"), fghijklmno, 'Test 138');
test(sortVowels("AEIOUzzzzzzzzzzzzzzzzzzzzzzzzzz"), AEIOUzzzzzzzzzzzzzzzzzzzzzzzzzz, 'Test 139');
test(sortVowels("VoWeLiInInG"), VIWILeinonG, 'Test 140');
test(sortVowels("MiXeDcAsEaeiouAEIOU"), MAXADcEsEIOUaeeiiou, 'Test 141');
test(sortVowels("QWERTYUIOPASDFGHJKLZXCVBNM"), QWARTYEIOPUSDFGHJKLZXCVBNM, 'Test 142');
test(sortVowels("zXcVbNMA"), zXcVbNMA, 'Test 143');
test(sortVowels("ConsonantsWithVowels"), CansenintsWothVowols, 'Test 144');
test(sortVowels("aAeEiIoOuUaAeEiIoOuUaAeEiIoOuU"), AAAEEEIIIOOOUUUaaaeeeiiiooouuu, 'Test 145');
test(sortVowels("aAbBcCdDeEfFgGiImMoOnNpPrRsStTuUvVwWxXyYzZ"), AEbBcCdDIOfFgGUamMeinNpPrRsStTouvVwWxXyYzZ, 'Test 146');
test(sortVowels("uUUUUU"), UUUUUu, 'Test 147');
test(sortVowels("aEiOuaEiOuaEiOuaEiOu"), EEEEOOOOaaaaiiiiuuuu, 'Test 148');
test(sortVowels("AbCdEfGhIjKlMnOpQrStUvWxYz"), AbCdEfGhIjKlMnOpQrStUvWxYz, 'Test 149');
test(sortVowels("sOrtThEvOwElS"), sErtThEvOwOlS, 'Test 150');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

