// Test: 925. Long Pressed Name
// 140 test cases from LeetCodeDataset
// Run: node test.js

const { isLongPressedName } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n925. Long Pressed Name\n");

test(isLongPressedName("zzzzzzzz", "zzzzzzzz"), true, 'Test 1');
test(isLongPressedName("abcd", "abcde"), false, 'Test 2');
test(isLongPressedName("test", "ttest"), true, 'Test 3');
test(isLongPressedName("dfuyalc", "fuuyallc"), false, 'Test 4');
test(isLongPressedName("zzzyyyyy", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"), false, 'Test 5');
test(isLongPressedName("abcd", "abcddcba"), false, 'Test 6');
test(isLongPressedName("alex", "aaleexa"), false, 'Test 7');
test(isLongPressedName("kikcxmvzi", "kiikcxxmmvvzzz"), false, 'Test 8');
test(isLongPressedName("pyplrz", "ppyypllrz"), true, 'Test 9');
test(isLongPressedName("ggggggg", "ggggggg"), true, 'Test 10');
test(isLongPressedName("laiden", "laiden"), true, 'Test 11');
test(isLongPressedName("saeed", "ssaaedd"), false, 'Test 12');
test(isLongPressedName("a", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), true, 'Test 13');
test(isLongPressedName("a", "b"), false, 'Test 14');
test(isLongPressedName("abcd", "abc"), false, 'Test 15');
test(isLongPressedName("pyplrz", "ppyypllr"), false, 'Test 16');
test(isLongPressedName("a", "aaaaaa"), true, 'Test 17');
test(isLongPressedName("leelee", "lleeelee"), true, 'Test 18');
test(isLongPressedName("zzzaaa", "zzzzzaaaa"), true, 'Test 19');
test(isLongPressedName("alex", "aaleex"), true, 'Test 20');
test(isLongPressedName("vtkgn", "vttkgnn"), true, 'Test 21');
test(isLongPressedName("alex", "ale"), false, 'Test 22');
test(isLongPressedName("hello", "hheeelllloo"), true, 'Test 23');
test(isLongPressedName("mississippi", "miiiiiiissssssippiiiiii"), false, 'Test 24');
test(isLongPressedName("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzz"), true, 'Test 25');
test(isLongPressedName("repeated", "repeeeaatteedd"), true, 'Test 26');
test(isLongPressedName("testing", "testings"), false, 'Test 27');
test(isLongPressedName("mississippi", "mmiissssippip"), false, 'Test 28');
test(isLongPressedName("aabbcc", "aaabbbccc"), true, 'Test 29');
test(isLongPressedName("abcdefghij", "aabbccddeeffgghhiijj"), true, 'Test 30');
test(isLongPressedName("mississippi", "mmiiisssssiiiippp"), false, 'Test 31');
test(isLongPressedName("flower", "ffflowweerrr"), true, 'Test 32');
test(isLongPressedName("consistent", "cccooonnsisstiisstteeennnttt"), false, 'Test 33');
test(isLongPressedName("algorithm", "aaalgggggorithm"), true, 'Test 34');
test(isLongPressedName("programming", "pprooggrammmiinngg"), true, 'Test 35');
test(isLongPressedName("mississippi", "mmiiississipppi"), true, 'Test 36');
test(isLongPressedName("friend", "ffriiieeeennnd"), true, 'Test 37');
test(isLongPressedName("longpressed", "lllooonngggppprrreeesssppeeeedd"), false, 'Test 38');
test(isLongPressedName("longpressed", "lllongggppppreeesssssssedd"), true, 'Test 39');
test(isLongPressedName("polygon", "pppollooogooonnnggg"), false, 'Test 40');
test(isLongPressedName("unique", "uuunnnnuuuuuuuuqeeeuuuuuuuuuueee"), false, 'Test 41');
test(isLongPressedName("consistent", "ccoonnsissssttttiinnnsss"), false, 'Test 42');
test(isLongPressedName("mississippi", "mmiississippip"), false, 'Test 43');
test(isLongPressedName("xxyyzz", "xxyyzzzxxxyyyzzz"), false, 'Test 44');
test(isLongPressedName("alexandria", "aaalllexxaandria"), true, 'Test 45');
test(isLongPressedName("qwert", "qqqqwweeeerrrttt"), true, 'Test 46');
test(isLongPressedName("vtkgn", "vtttkkkgggnnn"), true, 'Test 47');
test(isLongPressedName("rhinoceros", "rrrhhiinnoocceerrrsss"), false, 'Test 48');
test(isLongPressedName("longpressed", "lllooonngggpppreesssed"), true, 'Test 49');
test(isLongPressedName("qwerty", "qqqwwweeeerrrrttyyyy"), true, 'Test 50');
test(isLongPressedName("xylophone", "xxyyylloophooneee"), true, 'Test 51');
test(isLongPressedName("rhythm", "rhythm"), true, 'Test 52');
test(isLongPressedName("aabbcc", "aaabbcccc"), true, 'Test 53');
test(isLongPressedName("mississippi", "miiisiiisssiiipppii"), false, 'Test 54');
test(isLongPressedName("queue", "qqquuuuuuuuueee"), false, 'Test 55');
test(isLongPressedName("abcdefghij", "aabbbbccccddddeeeeffffgggghhhhiiiijjjj"), true, 'Test 56');
test(isLongPressedName("ababab", "aabbababb"), true, 'Test 57');
test(isLongPressedName("qlssqwwfw", "qqllssqqwwwwwfwf"), false, 'Test 58');
test(isLongPressedName("aabbcc", "aabbbcccc"), true, 'Test 59');
test(isLongPressedName("flower", "ffffllllooower"), true, 'Test 60');
test(isLongPressedName("programming", "ppprroogrraammmmiinngggg"), true, 'Test 61');
test(isLongPressedName("mississippi", "mmyisssssippis"), false, 'Test 62');
test(isLongPressedName("longpress", "lloongggppppreeessss"), true, 'Test 63');
test(isLongPressedName("aaaabbbbcccc", "aaaabbbbbbcccc"), true, 'Test 64');
test(isLongPressedName("xy", "xyxyxyxyxyxyxyxy"), false, 'Test 65');
test(isLongPressedName("unique", "uunniiquee"), true, 'Test 66');
test(isLongPressedName("longpressed", "lllllooonnggggppprrreeesss"), false, 'Test 67');
test(isLongPressedName("abcdefgh", "aabbbcccdddddeeeeeffffffgggghhhh"), true, 'Test 68');
test(isLongPressedName("algorithm", "aalllgggggoooooorrrriiitthhhhhmmmmm"), true, 'Test 69');
test(isLongPressedName("kikcxmvzi", "kiikcxxmmvvvzzzii"), true, 'Test 70');
test(isLongPressedName("abcde", "abcdeabcde"), false, 'Test 71');
test(isLongPressedName("keyboard", "kkkkeeyyyboooaarrdd"), true, 'Test 72');
test(isLongPressedName("a", "aaaaaaaaaaa"), true, 'Test 73');
test(isLongPressedName("qwerty", "qqqqwwwwertyyyyy"), true, 'Test 74');
test(isLongPressedName("leetcode", "lleettcoodde"), true, 'Test 75');
test(isLongPressedName("laiden", "laidenlaiden"), false, 'Test 76');
test(isLongPressedName("aabbcc", "aabbbccc"), true, 'Test 77');
test(isLongPressedName("characters", "ccccchaarrrrrttaaaaccchhhhheeeersss"), false, 'Test 78');
test(isLongPressedName("xylophone", "xyyylloophooneee"), true, 'Test 79');
test(isLongPressedName("keyboard", "kkkkeeyyyboaaaarrrddddd"), true, 'Test 80');
test(isLongPressedName("elephant", "eleelphhhaannnttt"), false, 'Test 81');
test(isLongPressedName("longnamehere", "lllooonnggnnaaammmeehheerrree"), true, 'Test 82');
test(isLongPressedName("zebra", "zzzeebrraaa"), true, 'Test 83');
test(isLongPressedName("function", "fffuunncctttiooonnnn"), true, 'Test 84');
test(isLongPressedName("abcdefg", "abcdeeeefg"), true, 'Test 85');
test(isLongPressedName("qwertyuiop", "qqqwwweerrttyyuuiioopp"), true, 'Test 86');
test(isLongPressedName("hello", "heeeelllllooo"), true, 'Test 87');
test(isLongPressedName("robert", "rroobbeerrtt"), true, 'Test 88');
test(isLongPressedName("repeated", "rrreeeepppeeeaaatteeeedd"), true, 'Test 89');
test(isLongPressedName("rhell", "rhellllllll"), true, 'Test 90');
test(isLongPressedName("mississippi", "mmiisssssippppi"), false, 'Test 91');
test(isLongPressedName("supercalifragilisticexpialidocious", "ssuupercccaliiifffragggiilissticceexpiialiiddoouuusss"), false, 'Test 92');
test(isLongPressedName("triangle", "tttriiaanngggllee"), true, 'Test 93');
test(isLongPressedName("variable", "vvvvvaaarriiiaabbbblllee"), true, 'Test 94');
test(isLongPressedName("aabbc", "aabbbcc"), true, 'Test 95');
test(isLongPressedName("abcd", "aabbbccccdddd"), true, 'Test 96');
test(isLongPressedName("hello", "heeeelllllllllo"), true, 'Test 97');
test(isLongPressedName("typing", "ttypiinggggg"), true, 'Test 98');
test(isLongPressedName("longpressed", "lllllonggggppppreeeesssssssppppeeeedd"), false, 'Test 99');
test(isLongPressedName("unique", "uunniiqueee"), true, 'Test 100');
test(isLongPressedName("aaab", "aaaaaabbbb"), true, 'Test 101');
test(isLongPressedName("", ""), true, 'Test 102');
test(isLongPressedName("elephant", "eeelleeeephhhhaaaalllllltttt"), false, 'Test 103');
test(isLongPressedName("ggg", "ggggggggggg"), true, 'Test 104');
test(isLongPressedName("abcd", "aabbccddeeffgg"), false, 'Test 105');
test(isLongPressedName("testing", "testtinngg"), true, 'Test 106');
test(isLongPressedName("abcdef", "aabbccddeeffgg"), false, 'Test 107');
test(isLongPressedName("sequence", "sseeqqqquuuuuuennnnccccceee"), true, 'Test 108');
test(isLongPressedName("carlosgomez", "cccarllloossgggoommezz"), true, 'Test 109');
test(isLongPressedName("elephant", "eeellllepphaaannntt"), true, 'Test 110');
test(isLongPressedName("aaaaaa", "aaaaaaaaaaaa"), true, 'Test 111');
test(isLongPressedName("programming", "ppprroogggrraammmiinnnggg"), true, 'Test 112');
test(isLongPressedName("aaabbbccc", "aabbbccc"), false, 'Test 113');
test(isLongPressedName("algorithm", "aalllggggorrrrithhhoonnmmm"), false, 'Test 114');
test(isLongPressedName("abcdabcd", "aabbccddeeffgg"), false, 'Test 115');
test(isLongPressedName("programming", "pprrrooggggrrraaaaammmmmmiiiiinnnggggggggg"), true, 'Test 116');
test(isLongPressedName("sequence", "sseeeequuuuueeeennnnncceeeeee"), true, 'Test 117');
test(isLongPressedName("farruh", "faaarrrruuhhhh"), true, 'Test 118');
test(isLongPressedName("abcdefghijk", "aabbcdddeeeffggghhhiiiijjjkkk"), true, 'Test 119');
test(isLongPressedName("xylophone", "xyyyylloophooneee"), true, 'Test 120');
test(isLongPressedName("xylophone", "xxxyyylloooophooooneee"), true, 'Test 121');
test(isLongPressedName("abcdefg", "abcdddddeeeffffffggg"), true, 'Test 122');
test(isLongPressedName("carlos", "cccaaarlllooss"), true, 'Test 123');
test(isLongPressedName("mississippi", "miisissiipppi"), false, 'Test 124');
test(isLongPressedName("challenge", "chhaalllaannggeee"), false, 'Test 125');
test(isLongPressedName("abcd", "aabbccdd"), true, 'Test 126');
test(isLongPressedName("consistent", "ccconinnsisttteeennnsssstt"), false, 'Test 127');
test(isLongPressedName("consistent", "cccooonnsiisstteeeennnttt"), true, 'Test 128');
test(isLongPressedName("abababa", "aabbaabbaabbaaba"), false, 'Test 129');
test(isLongPressedName("mississippi", "mmiissssssiiipppp"), false, 'Test 130');
test(isLongPressedName("example", "eexxaammmppllee"), true, 'Test 131');
test(isLongPressedName("testcase", "tteeeessttccaaase"), true, 'Test 132');
test(isLongPressedName("aaa", "aaaaa"), true, 'Test 133');
test(isLongPressedName("friend", "frrriieeedd"), false, 'Test 134');
test(isLongPressedName("algorithm", "aalllgggggoooooorrriiithhhhhmmmmm"), true, 'Test 135');
test(isLongPressedName("xyz", "xxxyyyzzz"), true, 'Test 136');
test(isLongPressedName("xyz", "xxyyyzzz"), true, 'Test 137');
test(isLongPressedName("longpressed", "lllllooonngggpppprrreeeesssssseeeedd"), true, 'Test 138');
test(isLongPressedName("complexity", "cccomppplleexxiittiityyy"), false, 'Test 139');
test(isLongPressedName("zebra", "zzzeeebrrraa"), true, 'Test 140');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

