// Test: 1392. Longest Happy Prefix
// 162 test cases from LeetCodeDataset
// Run: node test.js

const { longestPrefix } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1392. Longest Happy Prefix\n");

test(longestPrefix("prefixprefix"), prefix, 'Test 1');
test(longestPrefix("abcdef"), , 'Test 2');
test(longestPrefix("aaaaa"), aaaa, 'Test 3');
test(longestPrefix("aaaaabaaaa"), aaaa, 'Test 4');
test(longestPrefix("a"), , 'Test 5');
test(longestPrefix("abacabadabacaba"), abacaba, 'Test 6');
test(longestPrefix("abcabcabc"), abcabc, 'Test 7');
test(longestPrefix("abcabcabcabc"), abcabcabc, 'Test 8');
test(longestPrefix("aaaaaabbbaaaa"), aaaa, 'Test 9');
test(longestPrefix("happy"), , 'Test 10');
test(longestPrefix("noon"), n, 'Test 11');
test(longestPrefix("banana"), , 'Test 12');
test(longestPrefix("abc"), , 'Test 13');
test(longestPrefix("aabbccddeeaabbccdd"), aabbccdd, 'Test 14');
test(longestPrefix("abcd"), , 'Test 15');
test(longestPrefix("aabbccddeeffgg"), , 'Test 16');
test(longestPrefix("suffix"), , 'Test 17');
test(longestPrefix("aaaa"), aaa, 'Test 18');
test(longestPrefix("mississippi"), , 'Test 19');
test(longestPrefix("abcdabc"), abc, 'Test 20');
test(longestPrefix("ababab"), abab, 'Test 21');
test(longestPrefix("level"), l, 'Test 22');
test(longestPrefix("abacababacab"), abacab, 'Test 23');
test(longestPrefix("ababababcababab"), ababab, 'Test 24');
test(longestPrefix("abacabadabacabadabacaba"), abacabadabacaba, 'Test 25');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc, 'Test 26');
test(longestPrefix("abcdefghijabcdefghijabcdefghijabcdefghij"), abcdefghijabcdefghijabcdefghij, 'Test 27');
test(longestPrefix("bananaananabay"), , 'Test 28');
test(longestPrefix("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, 'Test 29');
test(longestPrefix("abracadabra"), abra, 'Test 30');
test(longestPrefix("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, 'Test 31');
test(longestPrefix("abcdefabcdefabcdef"), abcdefabcdef, 'Test 32');
test(longestPrefix("abacabadabacabadabacabadabacabad"), abacabadabacabadabacabad, 'Test 33');
test(longestPrefix("abcabcabcabcabcd"), , 'Test 34');
test(longestPrefix("xyzxyzxyzxyzxyzxyzxyz"), xyzxyzxyzxyzxyzxyz, 'Test 35');
test(longestPrefix("aababaabaababaaba"), aababaaba, 'Test 36');
test(longestPrefix("aaaabaaaa"), aaaa, 'Test 37');
test(longestPrefix("zazazazazazazazazazaz"), zazazazazazazazazaz, 'Test 38');
test(longestPrefix("abcabcabcabcabcabca"), abcabcabcabcabca, 'Test 39');
test(longestPrefix("abbaabbaabbaabbaabbaabba"), abbaabbaabbaabbaabba, 'Test 40');
test(longestPrefix("aabaaabaabaaabaabaabaaabaabaab"), aab, 'Test 41');
test(longestPrefix("mississippimississippimississippimis"), mississippimississippimis, 'Test 42');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc, 'Test 43');
test(longestPrefix("abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad"), abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad, 'Test 44');
test(longestPrefix("abcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcba"), abcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcbaabcdefghijkllkjihgfedcba, 'Test 45');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc, 'Test 46');
test(longestPrefix("aaaaaaabaaaaaab"), , 'Test 47');
test(longestPrefix("aaaaabbbbbccccdddd"), , 'Test 48');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabc, 'Test 49');
test(longestPrefix("acacacacac"), acacacac, 'Test 50');
test(longestPrefix("xyzxyzxyzxyz"), xyzxyzxyz, 'Test 51');
test(longestPrefix("mississippimississippi"), mississippi, 'Test 52');
test(longestPrefix("aaaaaabbbaaaaa"), aaaaa, 'Test 53');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabcabc, 'Test 54');
test(longestPrefix("aaaaabbbbbbbaaaaa"), aaaaa, 'Test 55');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc, 'Test 56');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc, 'Test 57');
test(longestPrefix("bananaananabanana"), banana, 'Test 58');
test(longestPrefix("mississippimississippimiss"), mississippimiss, 'Test 59');
test(longestPrefix("aabbaabbaabbaabb"), aabbaabbaabb, 'Test 60');
test(longestPrefix("abacabadabacabadabacabadabacabadabacaba"), abacabadabacabadabacabadabacaba, 'Test 61');
test(longestPrefix("abcabcabcabcabcabcabc"), abcabcabcabcabcabc, 'Test 62');
test(longestPrefix("zazazazazazaz"), zazazazazaz, 'Test 63');
test(longestPrefix("abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh"), abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh, 'Test 64');
test(longestPrefix("ababcabababa"), aba, 'Test 65');
test(longestPrefix("aaabaaaab"), aaab, 'Test 66');
test(longestPrefix("aaaaaaaab"), , 'Test 67');
test(longestPrefix("abacabacabac"), abacabac, 'Test 68');
test(longestPrefix("abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"), abcdabcdabcdabcdabcdabcdabcdabcdabcd, 'Test 69');
test(longestPrefix("mississippimississippimississippi"), mississippimississippi, 'Test 70');
test(longestPrefix("xyzxyzzxyzxyz"), xyzxyz, 'Test 71');
test(longestPrefix("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"), zzzzzzzzzzzzzzzzzzzzzzzzzzzzz, 'Test 72');
test(longestPrefix("abcdabcde"), , 'Test 73');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabc, 'Test 74');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc, 'Test 75');
test(longestPrefix("ababbababbababbabab"), ababbababbabab, 'Test 76');
test(longestPrefix("abcabcabcabcab"), abcabcabcab, 'Test 77');
test(longestPrefix("aaaaaaaaaaaaaaaaaaaaa"), aaaaaaaaaaaaaaaaaaaa, 'Test 78');
test(longestPrefix("ababababababab"), abababababab, 'Test 79');
test(longestPrefix("abcdeedcba"), a, 'Test 80');
test(longestPrefix("aaaaaa"), aaaaa, 'Test 81');
test(longestPrefix("abababababababab"), ababababababab, 'Test 82');
test(longestPrefix("ababababababababab"), abababababababab, 'Test 83');
test(longestPrefix("abcabcabcabcabcabc"), abcabcabcabcabc, 'Test 84');
test(longestPrefix("aaaaaaaaaabaaaaaaaaa"), aaaaaaaaa, 'Test 85');
test(longestPrefix("aaaaabaaaabaaaaaa"), aaaaa, 'Test 86');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc, 'Test 87');
test(longestPrefix("aaaaaaa"), aaaaaa, 'Test 88');
test(longestPrefix("abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh"), abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh, 'Test 89');
test(longestPrefix("abababababababababababababab"), ababababababababababababab, 'Test 90');
test(longestPrefix("racecaracecarace"), racecarace, 'Test 91');
test(longestPrefix("abcdabcdabcdabcdabcd"), abcdabcdabcdabcd, 'Test 92');
test(longestPrefix("racecaracecaracecar"), racecaracecar, 'Test 93');
test(longestPrefix("abcdeedcbaedcbaedcba"), a, 'Test 94');
test(longestPrefix("racecaracecaracecarace"), racecaracecarace, 'Test 95');
test(longestPrefix("ababababababababababababa"), abababababababababababa, 'Test 96');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc, 'Test 97');
test(longestPrefix("racecaracecaracecaracecaracecarace"), racecaracecaracecaracecarace, 'Test 98');
test(longestPrefix("aaaaaabaaaaaab"), aaaaaab, 'Test 99');
test(longestPrefix("xyxyxyxyxyxyxyxyxyxy"), xyxyxyxyxyxyxyxyxy, 'Test 100');
test(longestPrefix("xyxxyxyxyxxyx"), xyxxyx, 'Test 101');
test(longestPrefix("zazazazazazaza"), zazazazazaza, 'Test 102');
test(longestPrefix("abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad"), abacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabadabacabad, 'Test 103');
test(longestPrefix("xyzxyzxyzxyzxyzxyz"), xyzxyzxyzxyzxyz, 'Test 104');
test(longestPrefix("aabbccddeeffggaabbccddeeffgg"), aabbccddeeffgg, 'Test 105');
test(longestPrefix("abcdabcabc"), abc, 'Test 106');
test(longestPrefix("aaaaaaaaaab"), , 'Test 107');
test(longestPrefix("aaaaaaabaaaaaaaa"), aaaaaaa, 'Test 108');
test(longestPrefix("mnopqrstuvutsrqponm"), m, 'Test 109');
test(longestPrefix("ababababc"), , 'Test 110');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabcabcabc, 'Test 111');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc, 'Test 112');
test(longestPrefix("abcdefgabcdefg"), abcdefg, 'Test 113');
test(longestPrefix("abcdabcabcabcd"), abcd, 'Test 114');
test(longestPrefix("abcdeabcdeabcdeabcde"), abcdeabcdeabcde, 'Test 115');
test(longestPrefix("aaaaaaabcabcabc"), , 'Test 116');
test(longestPrefix("abcdabcdabcdabcdabcda"), abcdabcdabcdabcda, 'Test 117');
test(longestPrefix("abcdabcabcabc"), abc, 'Test 118');
test(longestPrefix("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"), , 'Test 119');
test(longestPrefix("aaaaaaaaaabaaaaaaaaaa"), aaaaaaaaaa, 'Test 120');
test(longestPrefix("abacabadabacabadabacabadabacabadabacabadabacabad"), abacabadabacabadabacabadabacabadabacabad, 'Test 121');
test(longestPrefix("aabbccddeeffaabbccddeeff"), aabbccddeeff, 'Test 122');
test(longestPrefix("aaaaaabaaaaa"), aaaaa, 'Test 123');
test(longestPrefix("abcdabcabcabcabcabcabcabcabc"), abc, 'Test 124');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcd"), , 'Test 125');
test(longestPrefix("abcabcabcabcabcabcabcab"), abcabcabcabcabcabcab, 'Test 126');
test(longestPrefix("ababababababababababababababababababababababababababababababababababababababab"), abababababababababababababababababababababababababababababababababababababab, 'Test 127');
test(longestPrefix("aabbaabbaabbaabbaabb"), aabbaabbaabbaabb, 'Test 128');
test(longestPrefix("abcdabcdabcdabcdabcdabcdabcdabcdabcd"), abcdabcdabcdabcdabcdabcdabcdabcd, 'Test 129');
test(longestPrefix("bananaananabananaananaba"), bananaananaba, 'Test 130');
test(longestPrefix("aabaaabaabaaabaab"), aabaaabaab, 'Test 131');
test(longestPrefix("abcdefghijkllkjihgfedcba"), a, 'Test 132');
test(longestPrefix("aabaaab"), aab, 'Test 133');
test(longestPrefix("aaaaaaabaaaaaa"), aaaaaa, 'Test 134');
test(longestPrefix("abcdeabcdeabcde"), abcdeabcde, 'Test 135');
test(longestPrefix("abcdabcabcde"), , 'Test 136');
test(longestPrefix("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"), zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz, 'Test 137');
test(longestPrefix("zxyxzyxyzxyxzyxzyz"), z, 'Test 138');
test(longestPrefix("ababababab"), abababab, 'Test 139');
test(longestPrefix("abababababababababababab"), ababababababababababab, 'Test 140');
test(longestPrefix("xyzxyzxyzxyzxyzxyzxyzxyz"), xyzxyzxyzxyzxyzxyzxyz, 'Test 141');
test(longestPrefix("abcdabcdabcdabcdabcdabcdabcdabcd"), abcdabcdabcdabcdabcdabcdabcd, 'Test 142');
test(longestPrefix("axbyczdxcyzbyxa"), a, 'Test 143');
test(longestPrefix("abcdefgabcdefgabcdefg"), abcdefgabcdefg, 'Test 144');
test(longestPrefix("abcxyzabcxyzabcxyz"), abcxyzabcxyz, 'Test 145');
test(longestPrefix("abcdefghihgfedcba"), a, 'Test 146');
test(longestPrefix("racecar"), r, 'Test 147');
test(longestPrefix("abcdefghijabcdefghij"), abcdefghij, 'Test 148');
test(longestPrefix("abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab"), ababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab, 'Test 149');
test(longestPrefix("abcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabc, 'Test 150');
test(longestPrefix("bananaabanana"), banana, 'Test 151');
test(longestPrefix("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"), zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz, 'Test 152');
test(longestPrefix("abcabcabcabcabcabcabcabcabcabcabc"), abcabcabcabcabcabcabcabcabcabc, 'Test 153');
test(longestPrefix("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, 'Test 154');
test(longestPrefix("aabaaabaabaaabaabaab"), aab, 'Test 155');
test(longestPrefix("ababcabcababc"), ababc, 'Test 156');
test(longestPrefix("abababcabababc"), abababc, 'Test 157');
test(longestPrefix("abcabcabcabcabc"), abcabcabcabc, 'Test 158');
test(longestPrefix("abracadabracadabrac"), abracadabrac, 'Test 159');
test(longestPrefix("ababababababababababababababababababab"), abababababababababababababababababab, 'Test 160');
test(longestPrefix("xyzxyzyzyzxzyzyzyzyzyz"), , 'Test 161');
test(longestPrefix("papapapapapap"), papapapapap, 'Test 162');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

