// Test: 2211. Count Collisions On A Road
// 177 test cases from LeetCodeDataset
// Run: node test.js

const { countCollisions } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n2211. Count Collisions On A Road\n");

test(countCollisions("SSRLSL"), 3, 'Test 1');
test(countCollisions("LRLRLR"), 4, 'Test 2');
test(countCollisions("RRRR"), 0, 'Test 3');
test(countCollisions("LRRSLRLR"), 5, 'Test 4');
test(countCollisions("LSRL"), 2, 'Test 5');
test(countCollisions("SSSS"), 0, 'Test 6');
test(countCollisions("RLSLRL"), 5, 'Test 7');
test(countCollisions("RSLSLSLS"), 4, 'Test 8');
test(countCollisions("SSSRRSLL"), 4, 'Test 9');
test(countCollisions("LRSLSR"), 2, 'Test 10');
test(countCollisions("RLSL"), 3, 'Test 11');
test(countCollisions("RLLLLLL"), 7, 'Test 12');
test(countCollisions("RRRRRRS"), 6, 'Test 13');
test(countCollisions("LLRR"), 0, 'Test 14');
test(countCollisions("RRLR"), 3, 'Test 15');
test(countCollisions("SSLSLS"), 2, 'Test 16');
test(countCollisions("RLRRLL"), 6, 'Test 17');
test(countCollisions("RRRSSSLL"), 5, 'Test 18');
test(countCollisions("SSSSS"), 0, 'Test 19');
test(countCollisions("LLLLL"), 0, 'Test 20');
test(countCollisions("RLRSLL"), 5, 'Test 21');
test(countCollisions("LSLR"), 1, 'Test 22');
test(countCollisions("LLLL"), 0, 'Test 23');
test(countCollisions("RSLRS"), 3, 'Test 24');
test(countCollisions("RSLRLRLS"), 6, 'Test 25');
test(countCollisions("RRSLRR"), 3, 'Test 26');
test(countCollisions("LRLR"), 2, 'Test 27');
test(countCollisions("RRRSSSLLLRRR"), 6, 'Test 28');
test(countCollisions("LSRLSL"), 3, 'Test 29');
test(countCollisions("LRLL"), 3, 'Test 30');
test(countCollisions("SSRLSS"), 2, 'Test 31');
test(countCollisions("RRRRR"), 0, 'Test 32');
test(countCollisions("RSLR"), 2, 'Test 33');
test(countCollisions("SSS"), 0, 'Test 34');
test(countCollisions("LRRLRRLL"), 7, 'Test 35');
test(countCollisions("RSLRSL"), 4, 'Test 36');
test(countCollisions("LSSRLL"), 3, 'Test 37');
test(countCollisions("RSLRLR"), 4, 'Test 38');
test(countCollisions("SSRSLLS"), 3, 'Test 39');
test(countCollisions("RRRRRSSSSSLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLSSSSSSSSSSS"), 43, 'Test 40');
test(countCollisions("LRLRLRLRLRLR"), 10, 'Test 41');
test(countCollisions("RRLRLRLRLRLRLRLRLRLR"), 19, 'Test 42');
test(countCollisions("LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL"), 0, 'Test 43');
test(countCollisions("SSRSLRRRLLSLSSS"), 8, 'Test 44');
test(countCollisions("RRRRRSSLLLLLRRRR"), 10, 'Test 45');
test(countCollisions("RLLLLRRRRLLLLRRRRRLLLLRRRR"), 22, 'Test 46');
test(countCollisions("RSSSSRRRRRRRRRRSSSLL"), 13, 'Test 47');
test(countCollisions("RRRRRRRRRRSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"), 10, 'Test 48');
test(countCollisions("LRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"), 0, 'Test 49');
test(countCollisions("RLRLRLRLRLRLRLRL"), 16, 'Test 50');
test(countCollisions("RRRSSLLLLRRRSSLLLL"), 14, 'Test 51');
test(countCollisions("RRRLRSSRRRLRRRRRSLRRRRRR"), 15, 'Test 52');
test(countCollisions("RLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"), 2, 'Test 53');
test(countCollisions("RSLRRSLRRSLR"), 8, 'Test 54');
test(countCollisions("LLLSRSSRRRLRRRRRSLRRRRRR"), 11, 'Test 55');
test(countCollisions("RLRSLLRSLLRSLLRSLLRS"), 15, 'Test 56');
test(countCollisions("LLLLLLLLLLSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"), 0, 'Test 57');
test(countCollisions("RSLRSLRSLRSLRSLRSLRSLRSLRL"), 18, 'Test 58');
test(countCollisions("LLLLSSSSRRRRRRRRRLLLLL"), 14, 'Test 59');
test(countCollisions("RRRRSSSSLLLLRRRRRRSSSSLLLLRRRRRRSSSSLLLL"), 28, 'Test 60');
test(countCollisions("RRRRRRRRRRRR"), 0, 'Test 61');
test(countCollisions("SLRLRLRLRLRSLSLSL"), 13, 'Test 62');
test(countCollisions("LLLLSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSRRRRRR"), 0, 'Test 63');
test(countCollisions("RSSSSRRRLLLLRRRSL"), 12, 'Test 64');
test(countCollisions("RRRRRRRRRRSSSSSSSSSLLLLLLLL"), 18, 'Test 65');
test(countCollisions("LRRRRRLLLLLS"), 10, 'Test 66');
test(countCollisions("SLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL"), 44, 'Test 67');
test(countCollisions("LLLLLLLLLLLLLLLL"), 0, 'Test 68');
test(countCollisions("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"), 0, 'Test 69');
test(countCollisions("RRRSLSLSSSLLLLRRRS"), 12, 'Test 70');
test(countCollisions("LLLLRRRRRRRR"), 0, 'Test 71');
test(countCollisions("RLRSRLRSRLRSRLRS"), 12, 'Test 72');
test(countCollisions("SSSSSSSSSSSSSSRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"), 52, 'Test 73');
test(countCollisions("RLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"), 2, 'Test 74');
test(countCollisions("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"), 0, 'Test 75');
test(countCollisions("SSSSSSSSSSSS"), 0, 'Test 76');
test(countCollisions("RSLRSLSRLRSLSR"), 8, 'Test 77');
test(countCollisions("RRRSLSLRSLRRRRLLL"), 14, 'Test 78');
test(countCollisions("RRRRRRRRRRRRRRRRRRRR"), 0, 'Test 79');
test(countCollisions("SSSSSRRRRRSSSSS"), 5, 'Test 80');
test(countCollisions("RRRRSSSLLLLLRRRR"), 9, 'Test 81');
test(countCollisions("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRR"), 44, 'Test 82');
test(countCollisions("SSRRRRLLLLSSRRRRLLLLSS"), 16, 'Test 83');
test(countCollisions("RSLRSLSRLSRLSRLRSLSR"), 12, 'Test 84');
test(countCollisions("RRRRRRRRLLLLLLLL"), 16, 'Test 85');
test(countCollisions("SLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL"), 46, 'Test 86');
test(countCollisions("RRRLLRRRLLLLLSS"), 13, 'Test 87');
test(countCollisions("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRR"), 43, 'Test 88');
test(countCollisions("LLLLLRRRRRLLLLLRRRRRLLLLLRRRRRLLLLLRRRRR"), 30, 'Test 89');
test(countCollisions("LLLLRRRRRRSSSSSLLLL"), 10, 'Test 90');
test(countCollisions("RLRLRLRLRLRL"), 12, 'Test 91');
test(countCollisions("RLRSLRSLRSLRSLRS"), 11, 'Test 92');
test(countCollisions("RRRRRRRRRRRRRRRR"), 0, 'Test 93');
test(countCollisions("SLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL"), 48, 'Test 94');
test(countCollisions("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRR"), 44, 'Test 95');
test(countCollisions("LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL"), 0, 'Test 96');
test(countCollisions("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRR"), 44, 'Test 97');
test(countCollisions("SSSSSSRRRRRSSSSSSSSS"), 5, 'Test 98');
test(countCollisions("LRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLR"), 38, 'Test 99');
test(countCollisions("SSSLRRRLLSSL"), 7, 'Test 100');
test(countCollisions("SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"), 0, 'Test 101');
test(countCollisions("RRRLRLRLRLRLRLRLRLRLRLRLRLRRRRRRRRRRRR"), 26, 'Test 102');
test(countCollisions("SSSSRRRRLLLLRRRRLLLL"), 16, 'Test 103');
test(countCollisions("RRRRRLSLLSLLLL"), 12, 'Test 104');
test(countCollisions("SSSSSSSSSSSSSSSS"), 0, 'Test 105');
test(countCollisions("RRRRRSSSSLLLLLLLL"), 13, 'Test 106');
test(countCollisions("LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL"), 0, 'Test 107');
test(countCollisions("RLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"), 2, 'Test 108');
test(countCollisions("SSRRRRRSSSSLLLSSSL"), 9, 'Test 109');
test(countCollisions("SSSSSSSSSSSSSSSSSSSS"), 0, 'Test 110');
test(countCollisions("LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL"), 0, 'Test 111');
test(countCollisions("RLRRLLRLRRLLRLRR"), 14, 'Test 112');
test(countCollisions("LLLLLLLLLLLLLLLLLLLLLLLLSSSS"), 0, 'Test 113');
test(countCollisions("RRRRSSSSSSRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRL"), 38, 'Test 114');
test(countCollisions("LSRSSRSLLRSRLS"), 7, 'Test 115');
test(countCollisions("LLLLLLRRRRRRLLLLRRRRRR"), 10, 'Test 116');
test(countCollisions("LLLLSSSSRRRRSSSSLLLL"), 8, 'Test 117');
test(countCollisions("SSSSSSSSSSSRRRRRRSSSSSSLLLLLLLLSSSSSSSSSSS"), 14, 'Test 118');
test(countCollisions("RRRSSLRLRLRSLL"), 11, 'Test 119');
test(countCollisions("RSLSLRLSLSLRLSLR"), 10, 'Test 120');
test(countCollisions("SSSSSRRRRRSSSSSLLLLL"), 10, 'Test 121');
test(countCollisions("SSSSRRRRSSSSSSSSSSSSSSSSSSS"), 4, 'Test 122');
test(countCollisions("SSSSRRRRRRLLLLSSSSSLLLL"), 14, 'Test 123');
test(countCollisions("SSLRRRSSLLSL"), 7, 'Test 124');
test(countCollisions("RRSSSLRSLSSSRRSSSLRSL"), 10, 'Test 125');
test(countCollisions("LSLSLSLSLSLSLSLSLRRRRRR"), 8, 'Test 126');
test(countCollisions("LLLLSSRRRRSSSSRRRR"), 4, 'Test 127');
test(countCollisions("RSLSRSLSRSLSRS"), 7, 'Test 128');
test(countCollisions("SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"), 0, 'Test 129');
test(countCollisions("RSLRSSLSRSSL"), 6, 'Test 130');
test(countCollisions("LRLRLRLRLRLRLRLRLRLR"), 18, 'Test 131');
test(countCollisions("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRR"), 43, 'Test 132');
test(countCollisions("RRRRRSSSLLLLLLLLRRRR"), 13, 'Test 133');
test(countCollisions("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"), 0, 'Test 134');
test(countCollisions("LLLLRRRRSSSSLLRRRR"), 6, 'Test 135');
test(countCollisions("LRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"), 0, 'Test 136');
test(countCollisions("LLLSRLRLRLRLRLL"), 11, 'Test 137');
test(countCollisions("RRRRSSSSLLLL"), 8, 'Test 138');
test(countCollisions("RLRLRLRLRLRLRLRLRLRL"), 20, 'Test 139');
test(countCollisions("LLLLRRRRSSSSLLLL"), 8, 'Test 140');
test(countCollisions("LRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"), 0, 'Test 141');
test(countCollisions("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLL"), 46, 'Test 142');
test(countCollisions("RRRRRRRRRSSSSSSSLLLLLLLLSSSSSSSSSSSSSSSSSS"), 17, 'Test 143');
test(countCollisions("RRRRRRRRRRRRRRRRRRRLLSSSSSSSSSSSSSSSSSL"), 22, 'Test 144');
test(countCollisions("RLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRL"), 40, 'Test 145');
test(countCollisions("LRRRSLRRRLSLSLLSLRR"), 12, 'Test 146');
test(countCollisions("LRRRLRRLLRLLRLRRRLLR"), 18, 'Test 147');
test(countCollisions("RRRRLLLLRRRRLLLLRRRRLLLLRRRRLLLLRRRRLLLL"), 40, 'Test 148');
test(countCollisions("SRLRSRLRSRLRSRLRSRLRSRLRSRLRSRLRSRLRSR"), 27, 'Test 149');
test(countCollisions("RRRRRSSLLLLLLLLLL"), 15, 'Test 150');
test(countCollisions("SSSSRRRRLLLLSSSS"), 8, 'Test 151');
test(countCollisions("SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"), 0, 'Test 152');
test(countCollisions("SSSSRRRRLLLLSSSSRRRR"), 8, 'Test 153');
test(countCollisions("SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"), 0, 'Test 154');
test(countCollisions("SRRRRRLRRRRLLSRRRRLLL"), 19, 'Test 155');
test(countCollisions("RRRLLLLLSSSSRRRLLLLL"), 16, 'Test 156');
test(countCollisions("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"), 0, 'Test 157');
test(countCollisions("RLLLLLRRRRRR"), 6, 'Test 158');
test(countCollisions("RSLRRSLSLSLSLSLSL"), 10, 'Test 159');
test(countCollisions("RLRSLRSLRSLRSLRSLRSLRSLRSLRSLRSLR"), 22, 'Test 160');
test(countCollisions("RRRRRRRRRRLLLLLLLLLL"), 20, 'Test 161');
test(countCollisions("RRRRSSSLLLLLLLRRRRRR"), 11, 'Test 162');
test(countCollisions("SSSSRRRRLLLLLRRRRLLLLLSSSSRRRRLLLLLRRRRLLLLL"), 36, 'Test 163');
test(countCollisions("LLLLLLLLLLSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSRRRR"), 0, 'Test 164');
test(countCollisions("RRRRRRRRRRRRRRSSSLSSSSSSSSSSSSSSSSSSSSSSSL"), 16, 'Test 165');
test(countCollisions("RRRRRRSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSLLLLLL"), 12, 'Test 166');
test(countCollisions("RRRRLLLLSSSSRRRLLL"), 14, 'Test 167');
test(countCollisions("LLLLLLLLLLLLLLLLLLLL"), 0, 'Test 168');
test(countCollisions("RLRRRLRLRLRLRLRLRLRLRLRLRLRR"), 26, 'Test 169');
test(countCollisions("RRRRRSSSSSSLLLLSSSSSS"), 9, 'Test 170');
test(countCollisions("SSRRRRRLLLLLSS"), 10, 'Test 171');
test(countCollisions("RRRRRRRRRRRRRLLLLLLLLLLLL"), 25, 'Test 172');
test(countCollisions("RRRRRRRRRRSSSSSSSSSSSSSSSSSSSSSSSSSSSSSLLLL"), 14, 'Test 173');
test(countCollisions("RSLSLRSLRRSLRSLRL"), 12, 'Test 174');
test(countCollisions("SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"), 0, 'Test 175');
test(countCollisions("RSSSSSSRRRRRRRLLLLLLLLLLLLLRRRRRR"), 21, 'Test 176');
test(countCollisions("RLRSLRLRSLRL"), 10, 'Test 177');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

