// Test: 71. Simplify Path
// 198 test cases from LeetCodeDataset
// Run: node test.js

const { simplifyPath } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n71. Simplify Path\n");

test(simplifyPath("/.../a/../b/c/../d/./"), /.../b/d, 'Test 1');
test(simplifyPath("/a/../../b/../c///.//"), /c, 'Test 2');
test(simplifyPath("/a/b/c/d/e/f/g/../../.."), /a/b/c/d, 'Test 3');
test(simplifyPath("/a/b/c/d/e/../../..//f/"), /a/b/f, 'Test 4');
test(simplifyPath("/a/b/c/../"), /a/b, 'Test 5');
test(simplifyPath("/a/b/c/d/e/../../../..///f/"), /a/f, 'Test 6');
test(simplifyPath("/a/b/c/d/e/../../../"), /a/b, 'Test 7');
test(simplifyPath("/a/b/c/d/"), /a/b/c/d, 'Test 8');
test(simplifyPath("/a/b/c/d/e/../../../../f/"), /a/f, 'Test 9');
test(simplifyPath("/a/b/c/d/../../.."), /a, 'Test 10');
test(simplifyPath("/a//b////c/d//././/.."), /a/b/c, 'Test 11');
test(simplifyPath("/home/"), /home, 'Test 12');
test(simplifyPath("/a/b/c/d/e/./../../f/"), /a/b/c/f, 'Test 13');
test(simplifyPath("/a/.."), /, 'Test 14');
test(simplifyPath("/a/b/c/d/e/f/g/.."), /a/b/c/d/e/f, 'Test 15');
test(simplifyPath("/a/b/c/../../d/e/"), /a/d/e, 'Test 16');
test(simplifyPath("/a/b/c/d/e/f/.."), /a/b/c/d/e, 'Test 17');
test(simplifyPath("/a/b/c/d/e/f/g/../.."), /a/b/c/d/e, 'Test 18');
test(simplifyPath("/a/b/c/../../"), /a, 'Test 19');
test(simplifyPath("/a/./b/../c/../../d/../../../e/../../../../f/"), /f, 'Test 20');
test(simplifyPath("/home/user/Documents/../Pictures"), /home/user/Pictures, 'Test 21');
test(simplifyPath("/a/./b/../../c/"), /c, 'Test 22');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 23');
test(simplifyPath("/a/b/c/d/e/f/g"), /a/b/c/d/e/f/g, 'Test 24');
test(simplifyPath("/a/b/c/d/e/../../..///f/"), /a/b/f, 'Test 25');
test(simplifyPath("/a/./b/./c/./d/"), /a/b/c/d, 'Test 26');
test(simplifyPath("/home//foo/"), /home/foo, 'Test 27');
test(simplifyPath("/a/./b/./c/./"), /a/b/c, 'Test 28');
test(simplifyPath("/a/b/c/./././"), /a/b/c, 'Test 29');
test(simplifyPath("/a/b/c/d/e/../../../..//f/"), /a/f, 'Test 30');
test(simplifyPath("/../"), /, 'Test 31');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../.././.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w, 'Test 32');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../..//"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s, 'Test 33');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../"), /, 'Test 34');
test(simplifyPath("/home/user/.../a/b/../../c/d/./e/f/../g/h/i/j/k/l/m/n/o/p/../../../q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../"), /home/user/.../c/d/e/g/h/i/j/k/l/m, 'Test 35');
test(simplifyPath("/..////../home/user/Documents"), /home/user/Documents, 'Test 36');
test(simplifyPath("/valid/./..../name/./with/./multiple/./dots/./in/./it"), /valid/..../name/with/multiple/dots/in/it, 'Test 37');
test(simplifyPath("/a/b/c/d/./e/../../f/g/"), /a/b/c/f/g, 'Test 38');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../..."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/..., 'Test 39');
test(simplifyPath("/valid/directory/name/./with/./multiple/./dots/./in/./it"), /valid/directory/name/with/multiple/dots/in/it, 'Test 40');
test(simplifyPath("/x/y/z/..../...../......./........"), /x/y/z/..../...../......./........, 'Test 41');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../.."), /a/b/c/d/e/f/g/h/i/j/k/l/m, 'Test 42');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../..."), /a/b/c/d/e/f/g/h/i/j/..., 'Test 43');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../..////"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s, 'Test 44');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../.."), /a/b/c/d/e/f/g/h/i, 'Test 45');
test(simplifyPath("/.../a/b/c/d/e/./f/g/./h/./i/./j/./k/./l/./m/./n/./o/./p/./q/./r/./s/./t/./u/./v/./w/./x/./y/./z/../../../"), /.../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w, 'Test 46');
test(simplifyPath("/home/user/../../../var/log/../../usr/local/bin/"), /usr/local/bin, 'Test 47');
test(simplifyPath("/home/user/./././Documents/"), /home/user/Documents, 'Test 48');
test(simplifyPath("/home/user/.../Documents/.../Pictures/././../Videos"), /home/user/.../Documents/.../Videos, 'Test 49');
test(simplifyPath("/x/y/z/....//....//....//...."), /x/y/z/..../..../..../...., 'Test 50');
test(simplifyPath("/home/user////....///.....///home/./../..///"), /home/user/...., 'Test 51');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o, 'Test 52');
test(simplifyPath("/home/user/./Documents/./../Pictures/./"), /home/user/Pictures, 'Test 53');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o, 'Test 54');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../..."), /a/b/c/d/e/f/..., 'Test 55');
test(simplifyPath("/start/..//end"), /end, 'Test 56');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/..///./../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w, 'Test 57');
test(simplifyPath("/a/b/c/././../d/e/f/.."), /a/b/d/e, 'Test 58');
test(simplifyPath("/home/user////....///.....///home"), /home/user/..../...../home, 'Test 59');
test(simplifyPath("/a/./b/./c/./d/./e/./f/./g/./h/./i/./j/./k/./l/./m/./n/./o/./p/./q/./r/./s/./t/./u/./v/./w/./x/./y/./z/.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y, 'Test 60');
test(simplifyPath("/home/user/.../Documents/././../Pictures/././..///"), /home/user/..., 'Test 61');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../.././.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u, 'Test 62');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../..///"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s, 'Test 63');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../..//////"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s, 'Test 64');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m, 'Test 65');
test(simplifyPath("/one/two/three/../../../four/five/six/../../seven"), /four/seven, 'Test 66');
test(simplifyPath("/home/user/./Documents/./../Pictures/./../Videos/./../Music/./../Downloads/./../Documents/./../Pictures/./../Videos"), /home/user/Videos, 'Test 67');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p, 'Test 68');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../.././.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s, 'Test 69');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../../../../..."), /..., 'Test 70');
test(simplifyPath("/a/./b/./c/./d/./e/./f/./g/./h/./i/./j/./k/./l/./m/./n/./o/./p/./q/./r/./s/./t/./u/./v/./w/./x/./y/./z"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 71');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../..."), /a/b/c/d/e/f/g/h/i/j/k/..., 'Test 72');
test(simplifyPath("/...../a/b/../../c/d/e/f/../g/h"), /...../c/d/e/g/h, 'Test 73');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u, 'Test 74');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r, 'Test 75');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../../../../../.."), /, 'Test 76');
test(simplifyPath("/a/b/c/d/e/../../f/g/./h/./i/./j/./k/./l/./m/./n/./o/./p/./q/./r/./s/./t/./u/./v/./w/./x/./y/./z/././"), /a/b/c/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 77');
test(simplifyPath("/valid/./name/./with/./multiple/./dots/./in/./..../it"), /valid/name/with/multiple/dots/in/..../it, 'Test 78');
test(simplifyPath("/user/./home/./.././..././...."), /user/.../...., 'Test 79');
test(simplifyPath("/home/user////....///.....///home/./../.."), /home/user/...., 'Test 80');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d, 'Test 81');
test(simplifyPath("/a/b/c/d/e/../../f/g/./h/./i/./j/./k/./l/./m/./n/./o/./p/./q/./r/./s/./t/./u/./v/./w/./x/./y/./z/./"), /a/b/c/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 82');
test(simplifyPath("/a/b/c/d/../../../../e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z"), /e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 83');
test(simplifyPath("/a/b/c/.../d/e/f/../../g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/../../../../z"), /a/b/c/.../d/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/z, 'Test 84');
test(simplifyPath("/home/user/./Documents/./../Pictures/./../Videos/./../Music/./../Downloads/./../"), /home/user, 'Test 85');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/..///././././..///"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x, 'Test 86');
test(simplifyPath("/home/user//...///....//.....//home"), /home/user/.../..../...../home, 'Test 87');
test(simplifyPath("/a/b/c/d/e/f/g/../../../..//../m/n/o/p/"), /a/b/m/n/o/p, 'Test 88');
test(simplifyPath("/home/user/.../Documents/././../Pictures/././..///././././.."), /home/user, 'Test 89');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 90');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../..."), /..., 'Test 91');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q, 'Test 92');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w, 'Test 93');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../..."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/..., 'Test 94');
test(simplifyPath("/...."), /...., 'Test 95');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../..///u/"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u, 'Test 96');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../.."), /a/b/c/d/e/f/g, 'Test 97');
test(simplifyPath("/a/./b/./c/./d/./e"), /a/b/c/d/e, 'Test 98');
test(simplifyPath("/many/../../dots/../../../in/../../../../path/../../../../../root"), /root, 'Test 99');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../.."), /, 'Test 100');
test(simplifyPath("/a/b/c/d/e/./f/g/././h/./i/./j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 101');
test(simplifyPath("/home////user/..///Documents///"), /home/Documents, 'Test 102');
test(simplifyPath("/home/user/.../a/b/../../c/d/./e/f/../g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z"), /home/user/.../c/d/e/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 103');
test(simplifyPath("/a/b/c/d/e/f/g/../../../../../../"), /a, 'Test 104');
test(simplifyPath("/a/b/c/d/e/f/g/../../.././../../"), /a/b, 'Test 105');
test(simplifyPath("/a/b/c/d/e/../../f/g/./h/./i/./j/./k/./l/./m/./n/./o/./p/./q/./r/./s/./t/./u/./v/./w/./x/./y/./z/../../"), /a/b/c/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x, 'Test 106');
test(simplifyPath("/.../a/b/c/d/e/./f/g/./h/./i/./j/./k/./l/./m/./n/./o/./p/./q/./r/./s/./t/./u/./v/./w/./x/./y/./z/../../"), /.../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x, 'Test 107');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 108');
test(simplifyPath("/home/user////....///.....///home/./../..///./../..///./../.."), /, 'Test 109');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t, 'Test 110');
test(simplifyPath("/home/user/./Documents/./../Pictures/./../Videos/./../Music/./../Downloads/./../Documents/./../"), /home/user, 'Test 111');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../..."), /a/b/..., 'Test 112');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../../../../../..."), /..., 'Test 113');
test(simplifyPath("/home/user/.../a/b/../../c/d/./e/f/../g/h/i/j/k/l/m/n/o/p/../../../q/r/s/t/u/v/w/x/y/z/../../../../"), /home/user/.../c/d/e/g/h/i/j/k/l/m/q/r/s/t/u/v, 'Test 114');
test(simplifyPath("/home/user////....///.....///home/./../..///./.."), /home/user, 'Test 115');
test(simplifyPath("/x/y/z/../../../../w/x/y"), /w/x/y, 'Test 116');
test(simplifyPath("/home/user/./Documents/./../Pictures/./../Videos/./../Music/./../Downloads/./../Documents/./../Pictures"), /home/user/Pictures, 'Test 117');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../"), /a/b/c/d, 'Test 118');
test(simplifyPath("/home/user////....///.....///home/./.."), /home/user/..../....., 'Test 119');
test(simplifyPath("/x/y/z/../../w/../../v/..///u/"), /u, 'Test 120');
test(simplifyPath("/home/user/././././././././././././././././././././././././././././././././"), /home/user, 'Test 121');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u, 'Test 122');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p, 'Test 123');
test(simplifyPath("/home/user/.../Documents/../Pictures/./../Videos"), /home/user/.../Videos, 'Test 124');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s, 'Test 125');
test(simplifyPath("/a/b/c/.../d/e/f/../../g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/../../z"), /a/b/c/.../d/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/z, 'Test 126');
test(simplifyPath("/a/b/c/d/e/../../f/g/../../h/i/../../j/k/../../l/m/../../n/o/p/../../q/r/s/t/../../u/v/w/x/../../y/z"), /a/b/c/n/q/r/u/v/y/z, 'Test 127');
test(simplifyPath("/user/..///////...///////"), /..., 'Test 128');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l, 'Test 129');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/././././.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y, 'Test 130');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p, 'Test 131');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../.."), /a/b/c, 'Test 132');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 133');
test(simplifyPath("/nested/../../deep/../../.."), /, 'Test 134');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t, 'Test 135');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/././././..//.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x, 'Test 136');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/./.././.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x, 'Test 137');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v, 'Test 138');
test(simplifyPath("/usr/local/../../local/bin/../../../bin"), /bin, 'Test 139');
test(simplifyPath("/a/b/c/.../d/e/f/../../g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z"), /a/b/c/.../d/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 140');
test(simplifyPath("/a/b/c/../../d/e/../../f/g/h/../../../i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z"), /a/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 141');
test(simplifyPath("/var/log/../log/./error.log"), /var/log/error.log, 'Test 142');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y, 'Test 143');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../..."), /a/b/c/d/e/f/g/..., 'Test 144');
test(simplifyPath("/valid/./name/./with/./multiple/./dots/./..../in/./it"), /valid/name/with/multiple/dots/..../in/it, 'Test 145');
test(simplifyPath("/a/b/c/d/e/f/g/./.././h/i/j/k/l/.."), /a/b/c/d/e/f/h/i/j/k, 'Test 146');
test(simplifyPath("/multiple/////slashes/are/here/./../still/reduced"), /multiple/slashes/are/still/reduced, 'Test 147');
test(simplifyPath("/home/user/.../a/b/../../c/d/./e/f/../g/h/i/j/k/l/m/n/o/p/../../../q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z"), /home/user/.../c/d/e/g/h/i/j/k/l/m/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 148');
test(simplifyPath("/foo/./bar/./baz/../qux/../.././quux"), /foo/quux, 'Test 149');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/./././././././././././././././././././././././././././././././././.././././././././././././././././././././././././././././././././././././././././."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y, 'Test 150');
test(simplifyPath("/home/user/.../Documents/././../Pictures/././.."), /home/user/..., 'Test 151');
test(simplifyPath("/home/user////....///.....///home/./../..///./../.."), /home, 'Test 152');
test(simplifyPath("/home/user/.../Documents/.../Pictures/././../Videos///"), /home/user/.../Documents/.../Videos, 'Test 153');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/./"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d, 'Test 154');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../"), /a/b, 'Test 155');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../"), /a/b/c/d/e/f/g/h/i/j, 'Test 156');
test(simplifyPath("/.../a/b/c/d/e/./f/g/./h/./i/./j/./k/./l/./m/./n/./o/./p/./q/./r/./s/./t/./u/./v/./w/./x/./y/./z/../"), /.../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y, 'Test 157');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../..."), /a/b/c/..., 'Test 158');
test(simplifyPath("/home/user/./Documents/./../Pictures/./../Videos/./../Music/./../Downloads/./../Documents/./../Pictures/./../Videos/./../Music/./../Downloads"), /home/user/Downloads, 'Test 159');
test(simplifyPath("/a/b/c/d/e/f/g/h/./i/../../j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z"), /a/b/c/d/e/f/g/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 160');
test(simplifyPath("/valid/./name/./with/./multiple/./..../dots/./in/./it"), /valid/name/with/multiple/..../dots/in/it, 'Test 161');
test(simplifyPath("/a/b/c/././././././d/e/f/../g/h/i/j/k/l/m/n/o/p/../../../q/r/s/t/u/v/w/x/y/z"), /a/b/c/d/e/g/h/i/j/k/l/m/q/r/s/t/u/v/w/x/y/z, 'Test 162');
test(simplifyPath("/a/b/c/d/e/../../f/g/././h/./i/./j/./k/./l/./m/./n/./o/./p/./q/./r/./s/./t/./u/./v/./w/./x/./y/./z"), /a/b/c/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 163');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w, 'Test 164');
test(simplifyPath("/home/user/../../../../../../"), /, 'Test 165');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p, 'Test 166');
test(simplifyPath("/.../a/./b/./c/./d/./e"), /.../a/b/c/d/e, 'Test 167');
test(simplifyPath("/a/b/c/d/e/f/g/./.././.././../../"), /a/b/c, 'Test 168');
test(simplifyPath("/a/b/c/../../d/e/../../f/g/h/./../"), /a/f/g, 'Test 169');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../..."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/..., 'Test 170');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../../../"), /, 'Test 171');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/..////..////.."), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w, 'Test 172');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c, 'Test 173');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../.."), /a/b/c/d/e/f/g/h/i/j/k/l, 'Test 174');
test(simplifyPath("/home/user////....///.....///home/./../..///./../..///./.."), /, 'Test 175');
test(simplifyPath("/x/y/z/../../../../../../../../../"), /, 'Test 176');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../../../.."), /, 'Test 177');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../../../../../"), /, 'Test 178');
test(simplifyPath("/a/b/c/d/e/../../f/g/./h/./i/./j/./k/./l/./m/./n/./o/./p/./q/./r/./s/./t/./u/./v/./w/./x/./y/./z/../../../"), /a/b/c/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w, 'Test 179');
test(simplifyPath("/trailing/./slashes/./should/./be/./removed"), /trailing/slashes/should/be/removed, 'Test 180');
test(simplifyPath("/home/user/../../root///"), /root, 'Test 181');
test(simplifyPath("/a/b/c/./../../d/e/./f/../g"), /a/d/e/g, 'Test 182');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../"), /a/b/c/d/e/f/g/h, 'Test 183');
test(simplifyPath("/home/user/./Documents/../Pictures/./Vacation/../../Pictures"), /home/user/Pictures, 'Test 184');
test(simplifyPath("/x/y/z/./././././././"), /x/y/z, 'Test 185');
test(simplifyPath("/x/y/z/....//....//....//....//a/b/c/d"), /x/y/z/..../..../..../..../a/b/c/d, 'Test 186');
test(simplifyPath("/a/b/c/d/e/../../f/g/./h/./i/./j/./k/./l/./m/./n/./o/./p/./q/./r/./s/./t/./u/./v/./w/./x/./y/./z/../"), /a/b/c/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y, 'Test 187');
test(simplifyPath("/a/b/c/d/././././e/f/g/../././h"), /a/b/c/d/e/f/h, 'Test 188');
test(simplifyPath("/home/user////....///.....///home/./../..///./../..///"), /home, 'Test 189');
test(simplifyPath("/home/user/./Documents/./../Pictures/./../Videos/./../Music/./../Downloads/./../Documents/./../Pictures/./../Videos/./../Music"), /home/user/Music, 'Test 190');
test(simplifyPath("/user//.///...///file"), /user/.../file, 'Test 191');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../.."), /a/b/c/d/e, 'Test 192');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../..////////"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s, 'Test 193');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n, 'Test 194');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z"), /a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z, 'Test 195');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../"), /a/b/c/d/e/f, 'Test 196');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../..///.."), /a/b/c/d/e/f/g/h/i/j/k/l, 'Test 197');
test(simplifyPath("/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/../../../../../../../../../../../../../../../../../../../../../../../../.."), /a, 'Test 198');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

// Auto-mark DONE when all tests pass
if (!failed) {
  const path = require("path");
  const fs = require("fs");
  const dir = __dirname;
  const folder = path.basename(dir);
  if (!folder.startsWith("DONE-")) {
    const parent = path.dirname(dir);
    const newDir = path.join(parent, "DONE-" + folder);
    fs.renameSync(dir, newDir);
    const readme = path.join(newDir, "README.md");
    if (fs.existsSync(readme)) {
      let c = fs.readFileSync(readme, "utf-8");
      if (!c.includes("<!-- SOLVED -->")) {
        c = c.replace(/^(# .+)$/m, "$1 ✅\n<!-- SOLVED -->");
        fs.writeFileSync(readme, c);
      }
    }
    console.log("✅ DONE → " + "DONE-" + folder);
  }
}
