// Test: 1048. Longest String Chain
// 84 test cases from LeetCodeDataset
// Run: node test.js

const { longestStrChain } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1048. Longest String Chain\n");

test(longestStrChain(["xbc","pcxbcf","xb","cxbc","pcxbc"]), 5, 'Test 1');
test(longestStrChain(["a","b","ba","bca","bda","bdca"]), 4, 'Test 2');
test(longestStrChain(["abcd","abde","acde","bcde","abcde"]), 2, 'Test 3');
test(longestStrChain(["a","abc","bde","abdce"]), 1, 'Test 4');
test(longestStrChain(["m","mo","moc","moch","mocha","lca","lcoa","lcoc","lococ","loccoc"]), 5, 'Test 5');
test(longestStrChain(["ksqvsyqpcq","ksqvsyqcpcq","vqsqpcq","ksqvsyqckpcq","kpcq","cqcq","qpcq","pcqcq"]), 3, 'Test 6');
test(longestStrChain(["ksq","ksqa","k","q","kq","pql","kqs","ks","ar","n","qn","kaq","pxq"]), 4, 'Test 7');
test(longestStrChain(["a","abc","bcd","abcd","abcde"]), 3, 'Test 8');
test(longestStrChain(["a","abc","bdc","bcd","abcd","bdca","edcba"]), 2, 'Test 9');
test(longestStrChain(["abcd","dbqca"]), 1, 'Test 10');
test(longestStrChain(["a","abc","bdc","abcde"]), 1, 'Test 11');
test(longestStrChain(["xyz","xyaz","xyazt","xyaztr","xyaztrd","xyaztrdf","xyaztrdfg","xyaztrdfgh","xyaztrdfghj","xyaztrdfghjk","xyaztrdfghjkl","xyaztrdfghjklm"]), 12, 'Test 12');
test(longestStrChain(["abcdef","abcde","abce","abceg","abeg","ae","ag","aeg","abc","ab","a","abcdefg","abcdefgh","abcdefghi","abcdefghij","abcdefghijk","abcdefghijkl","abcdefghijklm","abcdefghijklmn","abcdefghijklmnop"]), 14, 'Test 13');
test(longestStrChain(["abcdef","abdef","abcdf","abcef","abcd","abde","abcdx","abcdey","abcdez","abcde","abcdfg","abcdegh","abcdeghi","abcdeghij","abcdeghijk","abcdeghijkl","abcdeghijklm","abcdeghijklmn","abcdeghijklmno","abcdeghijklmnop","abcdeghijklmnopq","abcdeghijklmnopqr","abcdeghijklmnopqrs","abcdeghijklmnopqrst","abcdeghijklmnopqrstu","abcdeghijklmnopqrstuv","abcdeghijklmnopqrstuvw","abcdeghijklmnopqrstuvwx","abcdeghijklmnopqrstuvwxy","abcdeghijklmnopqrstuvwxyz"]), 19, 'Test 14');
test(longestStrChain(["z","az","azm","azmn","azmno","azmnop","azmnopq","azmnopqr","azmnopqrs","azmnopqrst","azmnopqrstu","azmnopqrstuv","azmnopqrstuvw","azmnopqrstuvwx","azmnopqrstuvwxy","azmnopqrstuvwxyz","azmnopqrstuvwxyza","azmnopqrstuvwxyzab","azmnopqrstuvwxyzabc","azmnopqrstuvwxyzabcd","azmnopqrstuvwxyzabcde","azmnopqrstuvwxyzabcdef","azmnopqrstuvwxyzabcdefg","azmnopqrstuvwxyzabcdefgh","azmnopqrstuvwxyzabcdefghi"]), 25, 'Test 15');
test(longestStrChain(["xyz","xy","xz","yz","x","y","z","xyza","xyzab","xyzabc","xyzabcd","xyzabcde"]), 8, 'Test 16');
test(longestStrChain(["a","ab","abc","abcd","abcde","abcdef","abcdefg","abcdefgh","abcdefghi","abcdefghij"]), 10, 'Test 17');
test(longestStrChain(["abcd","abdc","acbd","bacd","cabd","dabc","abcdx","abcdxy","abcdxyz","abcdxyza"]), 5, 'Test 18');
test(longestStrChain(["a","ab","abc","abcd","abcde","abcdef","abcdefg","abcdefgh","abcdefghi","abcdefghij","abcdefghijk","abcdefghijkl","abcdefghijklm","abcdefghijklmn","abcdefghijklmno","abcdefghijklmnop"]), 16, 'Test 19');
test(longestStrChain(["abc","abcd","abcde","abcdef","abcdefg","abcdefgh","abcdefghi","abcdefghij","abcdefghijk","abcdefghijkl","abcdefghijklm","abcdefghijklmn","abcdefghijklmno","abcdefghijklmnop"]), 14, 'Test 20');
test(longestStrChain(["a","ab","abc","abcd","abcde","abcdef","abcdefg","abcdefgh","abcdefghi","abcdefghij","abcdefghijk","abcdefghijkl","abcdefghijklm","abcdefghijklmn","abcdefghijklmnop","abcdefghijklmnopq","abcdefghijklmnopqr","abcdefghijklmnopqrs","abcdefghijklmnopqrst","abcdefghijklmnopqrstu","abcdefghijklmnopqrstuv","abcdefghijklmnopqrstuvw","abcdefghijklmnopqrstuvwx","abcdefghijklmnopqrstuvwxy","abcdefghijklmnopqrstuvwxyz"]), 14, 'Test 21');
test(longestStrChain(["abc","def","ab","bc","de","ef","abcd","defg","abef","abcd","bcde","cdef","abcd","bcde","cdefg","defgh","efghi","fghij","ghijk","hijkl","ijklm","jklmn","klmno","lmnop","mnopq","nopqr","opqrs","pqrs","qrstu","rstuv","stuvw","tuvwx","uvwxy","vwxyz"]), 4, 'Test 22');
test(longestStrChain(["abcd","abcde","abfde","abfce","abcfg","abcgd","abcdefgh","abcdfeh","abcdfehi","abcdfehij"]), 3, 'Test 23');
test(longestStrChain(["z","y","x","w","v","u","t","s","r","q","p","o","n","m","l","k","j","i","h","g","f","e","d","c","b","a"]), 1, 'Test 24');
test(longestStrChain(["ab","abc","abcd","abcde","abcdef","abcdefg","abcdefgh","abcdefghi","abcdefghij","abcdefghijk","abcdefghijkl","abcdefghijklm","abcdefghijklmn","abcdefghijklmno","abcdefghijklmnop"]), 15, 'Test 25');
test(longestStrChain(["abcdefghijklmnopqrstuvwxyz","abcdefghijklmnopqrstuvwx","abcdefghijklmnopqrstuvw","abcdefghijklmnopqrstu","abcdefghijklmnopqrstuv","abcdefghijklmnopqrst","abcdefghijklmnopqr","abcdefghijklmnopq","abcdefghijklmnop","abcdefghijklmnopq","abcdefghijklmnopqr","abcdefghijklmnopqrs","abcdefghijklmnopqrstuv","abcdefghijklmnopqrstuvw","abcdefghijklmnopqrstuvwx","abcdefghijklmnopqrstuvwxy"]), 11, 'Test 26');
test(longestStrChain(["xyz","xzy","zyx","yxz","yzx","zxy","yza","yab","yac","yad","ybc","ybd","ycd","yabc","yabd","yacd","ybcd","yabcd","yabdc","yacdb","ybcda","yzcdb","yzdcb","zydcb","zydcba","zydcbaq","zydcbaqp","zydcbaqpo","zydcbaqpon","zydcbaqponm","zydcbaqponml","zydcbaqponmlk","zydcbaqponmlkj","zydcbaqponmlkji","zydcbaqponmlkjih","zydcbaqponmlkjihg","zydcbaqponmlkjihgf"]), 14, 'Test 27');
test(longestStrChain(["a","ab","abc","abcd","abcde","abcdef","abcdefg","abcdefgh"]), 8, 'Test 28');
test(longestStrChain(["k","ko","kom","komo","komol","komole","komolen","komolex","komolexy","komolexyu","komolexyuc","komolexyucn","komolexyucne","komolexyucnew","komolexyucnewd","komolexyucnewdy","komolexyucnewdyt"]), 16, 'Test 29');
test(longestStrChain(["xyz","xyzu","xyzuv","xyzuvw","xyzuvwx","xyzuvwxy","xyzuvwxz","xyzuvwxyz","xyzuvwxyza","xyzuvwxyzab","xyzuvwxyzabc","xyzuvwxyzabcd","xyzuvwxyzabce","xyzuvwxyzabcde","xyzuvwxyzabcdef","xyzuvwxyzabcdefg"]), 14, 'Test 30');
test(longestStrChain(["abcd","abdc","acbd","bacd","bcad","cabd","cbad","dabc","dbac","dcab","dcba","bdac","bcad","acdb","cdba","adbc","bdca","cadb","cdab","cbda","abcd","abdc","acbd","bacd","bcad","cabd","cbad","dabc","dbac","dcab","dcba","bdac","bcad","acdb","cdba","adbc","bdca","cadb","cdab","cbda"]), 1, 'Test 31');
test(longestStrChain(["one","two","three","thre","threfo","threef","threefo","threefon","threefont","threefonto","threefonton","threefontona","threefontonat","threefontonatu","threefontonatup","threefontonatupl","threefontonatuplo","threefontonatuploe","threefontonatuploei","threefontonatuploein","threefontonatuploeink","threefontonatuploeinkf","threefontonatuploeinkfg","threefontonatuploeinkfgj","threefontonatuploeinkfgjo","threefontonatuploeinkfgjob","threefontonatuploeinkfgjobk"]), 24, 'Test 32');
test(longestStrChain(["mnop","mno","mn","m","ml","mlp","mlpq","mlpqr","mlpqrs","mlpqrst","mlpqrstu","mlpqrstuv","mlpqrstuvw","mlpqrstuvwx","mlpqrstuvwxy","mlpqrstuvwxyza","mlpqrstuvwxyzaq","mlpqrstuvwxyzaqp","mlpqrstuvwxyzaqpo","mlpqrstuvwxyzaqpom","mlpqrstuvwxyzaqpomn"]), 12, 'Test 33');
test(longestStrChain(["xyz","xz","xy","yz","x","y","z","xyza","xyzab","xyzabc","xyzabcd","xyzabcde"]), 8, 'Test 34');
test(longestStrChain(["a","aa","aaa","aaaa","aaaaa","aaaaaa","aaaaaaa","aaaaaaaa","aaaaaaaaa","aaaaaaaaaa","aaaaaaaaaaa","aaaaaaaaaaaa"]), 12, 'Test 35');
test(longestStrChain(["mn","mno","mnoa","mnob","mnoab","mnop","mnopq","mnopqr","mnopqrs","mnopqrst"]), 7, 'Test 36');
test(longestStrChain(["x","xy","xyz","xyza","xyzab","xyzabc","xyzabcd","xyzabcde","xyzabcdef","xyzabcdefg","xyzabcdefgh","xyzabcdefghi","xyzabcdefghij","xyzabcdefghijk","xyzabcdefghijklm","xyzabcdefghijklmn","xyzabcdefghijklmno","xyzabcdefghijklmnop"]), 14, 'Test 37');
test(longestStrChain(["z","zy","zyx","zyxz","zyxza","zyxzag","zyxzagh","zyxzaghd","zyxzaghde","zyxzaghdef","zyxzaghdefg","zyxzaghdefgh","zyxzaghdefghi","zyxzaghdefghj","zyxzaghdefghjk","zyxzaghdefghjkl","zyxzaghdefghjklm","zyxzaghdefghjklmn","zyxzaghdefghjklmno","zyxzaghdefghjklmnop"]), 19, 'Test 38');
test(longestStrChain(["abcd","acbd","adcb","bacd","bcad","bdac","cabd","cbad","cdab","dabc","dbac","dcab"]), 1, 'Test 39');
test(longestStrChain(["xyz","xyaz","xyazb","xyazbc","xyazbcd","xyazbcde","xyazbcdef","xyazbcdefg","xyazbcdefgh","xyazbcdefghi","xyazbcdefghij","xyazbcdefghijk","xyazbcdefghijkl","xyazbcdefghijklm","xyazbcdefghijklmn","xyazbcdefghijklmno"]), 16, 'Test 40');
test(longestStrChain(["abcd","abdc","acbd","adbc","bacd","badc","bcad","bcda","bdac","bdca","cabd","cadb","cbad","cbda","cdab","cdba","dcab","dcba","abcdex","abdcex","acbdex","adbcex","bacdex","badcex","bcadex","bcdaex","bdacex","bdcaex","cabdex","cadbex","cbadex","cbdaex","cdabex","cdbaex","dcabex","dcbaex","abcdexy","abdcexy","acbdexy","adbcexy","bacdexy","badcexy","bcadexy","bcdaexy","bdacexy","bdcaexy","cabdexy","cadbexy","cbadexy","cbdaexy","cdabexy","cdbaexy","dcabexy","dcbaexy","abcdexyz","abdcexyz","acbdexyz","adbcexyz","bacdexyz","badcexyz","bcadexyz","bcdaexyz","bdacexyz","bdcaexyz","cabdexyz","cadbexyz","cbadexyz","cbdaexyz","cdabexyz","cdbaexyz","dcabexyz","dcbaexyz","abcdefghij","abcdefghijk","abcdefghijl","abcdefghijm","abcdefghijn","abcdefghijo","abcdefghijp","abcdefghijq","abcdefghijr","abcdefghijs","abcdefghijt","abcdefghiju","abcdefghijv","abcdefghijw","abcdefghijx","abcdefghijy","abcdefghijz","abcdefghijkq","abcdefghijkqr","abcdefghijkqrs","abcdefghijkqrst","abcdefghijkqrstu","abcdefghijkqrstuv","abcdefghijkqrstuvw","abcdefghijkqrstuvwx","abcdefghijkqrstuvwxy","abcdefghijkqrstuvwxyz","abcdefghijkqrstuvwxys","abcdefghijkqrstuvwxyt","abcdefghijkqrstuvwxysu","abcdefghijkqrstuvwxyts","abcdefghijkqrstuvwxysut","abcdefghijkqrstuvwxytus","abcdefghijkqrstuvwxysutz","abcdefghijkqrstuvwxytzs","abcdefghijkqrstuvwxytzsu","abcdefghijkqrstuvwxytzst","abcdefghijkqrstuvwxytzstu","abcdefghijkqrstuvwxytzstuv","abcdefghijkqrstuvwxytzstuvw","abcdefghijkqrstuvwxytzstuvwx","abcdefghijkqrstuvwxytzstuvwxy","abcdefghijkqrstuvwxytzstuvwxyz","abcdefghijkqrstuvwxytzstuvwxyzs","abcdefghijkqrstuvwxytzstuvwxyzst","abcdefghijkqrstuvwxytzstuvwxyzstu","abcdefghijkqrstuvwxytzstuvwxyzstuv","abcdefghijkqrstuvwxytzstuvwxyzstuvw","abcdefghijkqrstuvwxytzstuvwxyzstuvwx","abcdefghijkqrstuvwxytzstuvwxyzstuvwxy","abcdefghijkqrstuvwxytzstuvwxyzstuvwxyz"]), 29, 'Test 41');
test(longestStrChain(["a","b","c","ab","bc","abc","abcd","abdc","acbd","bacd","bdac","cabd","cbad","dabc","dbac"]), 4, 'Test 42');
test(longestStrChain(["apple","ape","aple","appel","apples","appl","applle","appllees"]), 4, 'Test 43');
test(longestStrChain(["x","xa","xaz","xazl","xazld","xazldq","xazldqw","xazldqwj","xazldqwji","xazldqwjit","xazldqwjitp","xazldqwjitpe","xazldqwjitpek","xazldqwjitpekf","xazldqwjitpekfg","xazldqwjitpekfgh","xazldqwjitpekfghi","xazldqwjitpekfghij","xazldqwjitpekfghijk","xazldqwjitpekfghijkl","xazldqwjitpekfghijklm","xazldqwjitpekfghijklmn","xazldqwjitpekfghijklmno","xazldqwjitpekfghijklmnop","xazldqwjitpekfghijklmnopq","xazldqwjitpekfghijklmnopqr","xazldqwjitpekfghijklmnopqrs","xazldqwjitpekfghijklmnopqrst","xazldqwjitpekfghijklmnopqrstu","xazldqwjitpekfghijklmnopqrstuv","xazldqwjitpekfghijklmnopqrstuvw","xazldqwjitpekfghijklmnopqrstuvwx","xazldqwjitpekfghijklmnopqrstuvwxy","xazldqwjitpekfghijklmnopqrstuvwxyz"]), 34, 'Test 44');
test(longestStrChain(["xyz","xyzz","xyyzz","xyyyzz","xyyyyzz","xyyyyyzz","xyyyyyyzz","xyyyyyzzz","xyyyyyyzzzz"]), 7, 'Test 45');
test(longestStrChain(["abcd","abdc","acbd","bacd","badc","cabd","cbad","cdab","cdba","dcba","dcab","dbac","dbca"]), 1, 'Test 46');
test(longestStrChain(["apple","app","aple","appl","applu","apples","applks","applksa","applksag","applksage","applksager","applksagerm"]), 6, 'Test 47');
test(longestStrChain(["m","mo","moc","moch","mocha","mochas","mochaste","mochaster","mochastera","mochasteras"]), 6, 'Test 48');
test(longestStrChain(["p","pq","pqr","pqrs","pqrst","pqrstu","pqrstuv","pqrstuvw","pqrstuvwx","pqrstuvwxy","pqrstuvwxyz","pqrstuvwxyza","pqrstuvwxyzab","pqrstuvwxyzabc","pqrstuvwxyzabcd","pqrstuvwxyzabcde"]), 16, 'Test 49');
test(longestStrChain(["aa","aaa","aaaa","abc","abcd","abce","abcef","abcdeg","abcdegh","abcdefg","abcdefgh","abcdefghi","abcdefghij","abcdefghijk","abcdefghijkl","abcdefghijklm","abcdefghijklmn","abcdefghijklmnop","abcdefghijklmnopq","abcdefghijklmnopqr","abcdefghijklmnopqrs","abcdefghijklmnopqrst","abcdefghijklmnopqrstu","abcdefghijklmnopqrstuv","abcdefghijklmnopqrstuvw","abcdefghijklmnopqrstuvwx","abcdefghijklmnopqrstuvwxy","abcdefghijklmnopqrstuvwxyz"]), 11, 'Test 50');
test(longestStrChain(["a","aa","aaa","aaaa","aaaaa","aaaaaa","aaaaaaa","aaaaaaaa","aaaaaaaaa","aaaaaaaaaa"]), 10, 'Test 51');
test(longestStrChain(["aaa","aaab","aaabc","aab","aabcc","aabc","aabcd","aabccd","abc","abccd","abcd","abccd","abcde","abcdde","abcdee","abcdef","abcdefg","abcdefgh","abcdefghi","abcdefghij","abcdefghijk","abcdefghijkl","abcdefghijklm","abcdefghijklmn","abcdefghijklmno","abcdefghijklmnop","abcdefghijklmnopq","abcdefghijklmnopqr","abcdefghijklmnopqrs","abcdefghijklmnopqrst","abcdefghijklmnopqrstu","abcdefghijklmnopqrstuv","abcdefghijklmnopqrstuvw","abcdefghijklmnopqrstuvwx","abcdefghijklmnopqrstuvwxy","abcdefghijklmnopqrstuvxyz"]), 23, 'Test 52');
test(longestStrChain(["a","ab","abc","abcd","abcde","abcdef","abcdefg","abcdefgh","abcdefghi","abcdefghij","abcdefghijk","abcdefghijkl","abcdefghijklm","abcdefghijklmn","abcdefghijklmno","abcdefghijklmnp","abcdefghijklmnpo","abcdefghijklmnpqr","abcdefghijklmnpqrs","abcdefghijklmnpqrst","abcdefghijklmnpqrstu","abcdefghijklmnpqrstuv","abcdefghijklmnpqrstuvw","abcdefghijklmnpqrstuvwx","abcdefghijklmnpqrstuvwxy","abcdefghijklmnpqrstuvwxyz"]), 16, 'Test 53');
test(longestStrChain(["m","mo","mop","mopt","mopti","moptio","moptiop","moptiopi","moptiopim","moptiopimu","moptiopimuv","moptiopimuvi","moptiopimuvis","moptiopimuvisd"]), 14, 'Test 54');
test(longestStrChain(["abcdefgh","abcdefg","abcdef","abcde","abcd","abc","ab","a","abcdefghij","abcdefghijk","abcdefghijkl","abcdefghijklm","abcdefghijklmn","abcdefghijklmnop"]), 8, 'Test 55');
test(longestStrChain(["xyz","xy","x","xyzpq","yzpq","ypq","pq","zpq","p","q","qp"]), 5, 'Test 56');
test(longestStrChain(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","az","bz","cz","dz","ez","fz","gz","hz","iz","jz","kz","lz","mz","nz","oz","pz","qz","rz","sz","tz","uz","vz","wz","xz","yz","abc","bcd","cde","def","efg","fgh","ghi","hij","ijk","jkl","klm","lmn","mno","nop","opq","pqr","qrs","rst","stu","tuv","uvw","vwx","wxy","xyz"]), 3, 'Test 57');
test(longestStrChain(["m","mo","mop","mops","mopsi","mopsin","mopsing","mopsing","mopsingh","mopsingha","mopsinghar","mopsinghark","mopsingharky","mopsingharkyz","mopsingharkyzr","mopsingharkyzrf","mopsingharkyzrfc","mopsingharkyzrfca","mopsingharkyzrfcal","mopsingharkyzrfcala","mopsingharkyzrfcalab","mopsingharkyzrfcalabs","mopsingharkyzrfcalabss","mopsingharkyzrfcalabsss","mopsingharkyzrfcalabssss","mopsingharkyzrfcalabsssss","mopsingharkyzrfcalabssssss","mopsingharkyzrfcalabsssssss","mopsingharkyzrfcalabssssssss","mopsingharkyzrfcalabsssssssss","mopsingharkyzrfcalabssssssssss","mopsingharkyzrfcalabsssssssssss","mopsingharkyzrfcalabssssssssssss","mopsingharkyzrfcalabsssssssssssss","mopsingharkyzrfcalabssssssssssssss","mopsingharkyzrfcalabsssssssssssssss"]), 35, 'Test 58');
test(longestStrChain(["p","pa","pau","paws","pawst","pawstd","pawstde","pawstdef","pawstdefp","pawstdefpg","pawstdefpgm","pawstdefpgmn","pawstdefpgmno","pawstdefpgmnop","pawstdefpgmnopq","pawstdefpgmnopqr","pawstdefpgmnopqrs","pawstdefpgmnopqrst","pawstdefpgmnopqrstu","pawstdefpgmnopqrstuv","pawstdefpgmnopqrstuvw","pawstdefpgmnopqrstuvwx","pawstdefpgmnopqrstuvwxy","pawstdefpgmnopqrstuvwxyz"]), 21, 'Test 59');
test(longestStrChain(["xyz","xz","xy","x","yz","y","xzpq","zpq","zq","pq","q"]), 4, 'Test 60');
test(longestStrChain(["abcdef","abcde","abcd","abc","ab","a","aghij","aghi","agh","ag","a","agghij","agghijr","agghijrk","agghijrkm","agghijrkmp","agghijrkmpa","agghijrkmpab","agghijrkmpabc","agghijrkmpabcd"]), 14, 'Test 61');
test(longestStrChain(["aa","aaa","aaaa","aaaaa","aaaaaa","aaaaaaa","aaaaaaaa","aaaaaaaaa","aaaaaaaaaa","aaaaaaaaaaa","aaaaaaaaaaaa","aaaaaaaaaaaaa","aaaaaaaaaaaaaa","aaaaaaaaaaaaaaa","aaaaaaaaaaaaaaaa","aaaaaaaaaaaaaaaaa","aaaaaaaaaaaaaaaaaa"]), 17, 'Test 62');
test(longestStrChain(["q","qz","qzh","qzhd","qzhdr","qzhdre","qzhdrec","qzhdrecu","qzhdrecuj","qzhdrecuju","qzhdrecujuu","qzhdrecujuus"]), 12, 'Test 63');
test(longestStrChain(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","aa","bb","cc","dd","ee","ff","gg","hh","ii","jj","kk","ll","mm","nn","oo","pp","qq","rr","ss","tt","uu","vv","ww","xx","yy","zz"]), 2, 'Test 64');
test(longestStrChain(["abc","bca","cab","abcd","bcad","cabd","acbd","bacd","badc","bcda","acdb","cadb","cbad","cbda","cdab","cdba","dcab","dcba","dabc","dacb","dbac","dbca","dcab","dcba","abcdx","bcadx","cabdx","abcxd","bcadcx","cabdcx","acbdcx","bacdcx","bacdx","bcadcx","bcadxc","cabdxc","acbdcx","bacdxc","bacdx","bcadxc","bcadcx","bcadxc","abcde","bcade","cabde","acbed","bacde","baced","bcade","bcdea","cabde","cabed","cbade","cbdea","cdabe","cdbe","cdba","dcab","dcba","abcd","bcad","cabd","acbd","bacd","badc","bcda","acdb","cadb","cbad","cbda","cdab","cdba","dcab","dcba","dabc","dacb","dbac","dbca","dcab","dcba","xyz","xyaz","xyazb","xyazbc","xyazbcd","xyazbcde","xyazbcdef","xyazbcdefg","xyazbcdefgh","xyazbcdefghi","xyazbcdefghij","xyazbcdefghijk","xyazbcdefghijkl","xyazbcdefghijklm","xyazbcdefghijklmn","xyazbcdefghijklmno"]), 16, 'Test 65');
test(longestStrChain(["a","b","ab","bc","abc","abcd","bcde","cde","efg","fgh","efgh","efghi","efghij"]), 4, 'Test 66');
test(longestStrChain(["mnop","mno","mo","mn","m","on","om","op","pn","po","np","no","p","o","n"]), 4, 'Test 67');
test(longestStrChain(["jkl","jkla","jklo","jkloi","jkloip","jkloipq","jkloipqr","jkloipqrs","jkloipqrst","jkloipqrstu","jkloipqrstuv","jkloipqrstuvw","jkloipqrstuvwx","jkloipqrstuvwxy","jkloipqrstuvwxyz","jkloipqrstuvwxyzv","jkloipqrstuvwxyza","jkloipqrstuvwxyzab","jkloipqrstuvwxyzabc","jkloipqrstuvwxyzabcd","jkloipqrstuvwxyzabcde","jkloipqrstuvwxyzabcdef","jkloipqrstuvwxyzabcdefg","jkloipqrstuvwxyzabcdefgh","jkloipqrstuvwxyzabcdefghi","jkloipqrstuvwxyzabcdefghij"]), 24, 'Test 68');
test(longestStrChain(["abcd","abcde","abcdef","abcdf","abcdg","abcdefgh","abcdefghi","abcdefghij","abcdefghijk"]), 4, 'Test 69');
test(longestStrChain(["abcd","abdc","abacd","abcd","abac","abcde","abcfde","abcdefg","abcdegh"]), 3, 'Test 70');
test(longestStrChain(["abc","ab","bc","abcde","abde","acde","cde","a","b","c","d","e"]), 3, 'Test 71');
test(longestStrChain(["z","yz","xyz","wxyz","vwxyz","uvwxy","uvwx","uvx","ux","x","pq","pqr","pqrs","pqrsu","pqrstuv","pqrstuvw","pqrstuvwx","pqrstuvwxy","pqrstuvwxyz","abcdefghijkl","abcdefghij","abcdefghijk","abcdefghijklm","abcdefghijklmn","abcdefghijklmnop"]), 5, 'Test 72');
test(longestStrChain(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]), 1, 'Test 73');
test(longestStrChain(["qwe","qwerty","qwertyu","qwertyui","qwertyuio","qwertyuiop","qwertyuiopl","qwertyuioplk","qwertyuioplkj","qwertyuioplkjh","qwertyuioplkjhg","qwertyuioplkjhgfd","qwertyuioplkjhgfdc","qwertyuioplkjhgfdcv","qwertyuioplkjhgfdcvb","qwertyuioplkjhgfdcvbn","qwertyuioplkjhgfdcvbnn","qwertyuioplkjhgfdcvbnm"]), 10, 'Test 74');
test(longestStrChain(["k","a","b","ka","kb","abc","bcd","abcd","bcde","abcde","fgh","ghij","hijk","ijkl","jklm","klmn","lmno","mnop","nopq","opqr","pqr","pqrs","qrst","rstu","stuv","tuvw","uvwx","vwxy","wxyz"]), 3, 'Test 75');
test(longestStrChain(["abcd","abce","abcf","abcg","abch","abci","abcfi","abcei","abceg","abcef","abcefj","abcefg","abcefgk","abcefgkl","abcefgklm","abcefgklmn","abcefgklmno","abcefgklmnop","abcefgklmnopq","abcefgklmnopqr","abcefgklmnopqrs","abcefgklmnopqrst","abcefgklmnopqrstu","abcefgklmnopqrstuv","abcefgklmnopqrstuvw","abcefgklmnopqrstuvwx","abcefgklmnopqrstuvwxy","abcefgklmnopqrstuvwxyz"]), 19, 'Test 76');
test(longestStrChain(["aaaaab","aaab","aab","ab","b","ba","aba","abab","ababa","ababab","abababa","abababab","ababababa","ababababab"]), 10, 'Test 77');
test(longestStrChain(["mnop","mno","mn","mnoq","mnopqr","mnopqrs","mnopqrst","mnopqrstu","mnopqrstuv","mnopqrstuvw","mnopqrstuvwx","mnopqrstuvwxz"]), 8, 'Test 78');
test(longestStrChain(["xy","xyc","xyz","xyzq","xyzqr","xyzqrs","xyzqrst","xyzqrstuv","xyzqrstuvw","xyzqrstuvwx","xyzqrstuvwxy","xyzqrstuvwxyz","xyzqrstuvwxys","xyzqrstuvwxyt","xyzqrstuvwxysu","xyzqrstuvwxyts","xyzqrstuvwxysut","xyzqrstuvwxytus","xyzqrstuvwxysutz","xyzqrstuvwxytzs","xyzqrstuvwxytzsu","xyzqrstuvwxytzst","xyzqrstuvwxytzstu","xyzqrstuvwxytzstuv","xyzqrstuvwxytzstuvw","xyzqrstuvwxytzstuvwx","xyzqrstuvwxytzstuvwxy","xyzqrstuvwxytzstuvwxyz","xyzqrstuvwxytzstuvwxyzs","xyzqrstuvwxytzstuvwxyzst","xyzqrstuvwxytzstuvwxyzstu","xyzqrstuvwxytzstuvwxyzstuv","xyzqrstuvwxytzstuvwxyzstuvw","xyzqrstuvwxytzstuvwxyzstuvwx","xyzqrstuvwxytzstuvwxyzstuvwxy","xyzqrstuvwxytzstuvwxyzstuvwxyz"]), 22, 'Test 79');
test(longestStrChain(["mno","mnop","mnop","mnopq","mnopqr","mnopqrs","mnopqrst","mnopqrstu","mnopqrstuv","mnopqrstuvw","mnopqrstuvwx","mnopqrstuvwxy","mnopqrstuvwxyz","mnopqrstuvwxyza","mnopqrstuvwxyzab","mnopqrstuvwxyzabc","mnopqrstuvwxyzabcd","mnopqrstuvwxyzabcde","mnopqrstuvwxyzabcdef","mnopqrstuvwxyzabcdefg","mnopqrstuvwxyzabcdefgh","mnopqrstuvwxyzabcdefghi","mnopqrstuvwxyzabcdefghij","mnopqrstuvwxyzabcdefghijk","mnopqrstuvwxyzabcdefghijkl","mnopqrstuvwxyzabcdefghijklm","mnopqrstuvwxyzabcdefghijklmn","mnopqrstuvwxyzabcdefghijklmno","mnopqrstuvwxyzabcdefghijklmnop","mnopqrstuvwxyzabcdefghijklmnopq","mnopqrstuvwxyzabcdefghijklmnopqr","mnopqrstuvwxyzabcdefghijklmnopqrs","mnopqrstuvwxyzabcdefghijklmnopqrst","mnopqrstuvwxyzabcdefghijklmnopqrstu","mnopqrstuvwxyzabcdefghijklmnopqrstuv","mnopqrstuvwxyzabcdefghijklmnopqrstuvw","mnopqrstuvwxyzabcdefghijklmnopqrstuvwx","mnopqrstuvwxyzabcdefghijklmnopqrstuvwxy","mnopqrstuvwxyzabcdefghijklmnopqrstuvwxyza"]), 37, 'Test 80');
test(longestStrChain(["abcdef","abef","abcf","acdf","adef","abdf","abefg","abecf","abedf","abcef","abcdf","abdef","abcdefg"]), 4, 'Test 81');
test(longestStrChain(["zyx","zyxa","zyxb","zyxc","zyxd","zyxe","zyxf","zyxg","zyxh","zyxi","zyxj","zyxk","zyxl","zyxm","zyxn","zyxo","zyxp","zyxq","zyxr","zyxs","zyxt","zyxu","zyxv","zyxw","zyxx","zyxy","zyxz"]), 2, 'Test 82');
test(longestStrChain(["xyz","xz","xy","x","wxyz","wxz","wxy","wx","w","vxyz","vxz","vxy","vx","v","uvxyz","uvxz","uvxy","uvx","uv","tuvsxyz","tuvsxz","tuvsxy","tuvsx","tuvs","tuvxyz","tuvxz","tuvxy","tuvx","tuv","stuvxyz","stuvxz","stuvxy","stuvx","stuv","stuvxyz","stuvxz","stuvxy","stuvx","stuv"]), 7, 'Test 83');
test(longestStrChain(["abcd","acbd","adcb","bacd","bcad","cabd","cbad","cdab","cdba","dcba","dcab","dbac","dbca","abcdxyz","abcdeyz","abcdefz","abcdefw"]), 1, 'Test 84');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

