// Test: 1704. Determine If String Halves Are Alike
// 175 test cases from LeetCodeDataset
// Run: node test.js

const { halvesAreAlike } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1704. Determine If String Halves Are Alike\n");

test(halvesAreAlike("UFO"), false, 'Test 1');
test(halvesAreAlike("aAeEiIoOuU"), true, 'Test 2');
test(halvesAreAlike("Leetcode"), true, 'Test 3');
test(halvesAreAlike("abcdefgihjklmno"), false, 'Test 4');
test(halvesAreAlike("Regal"), true, 'Test 5');
test(halvesAreAlike("Reinholdmes"), true, 'Test 6');
test(halvesAreAlike("AbCdEfGh"), true, 'Test 7');
test(halvesAreAlike("textbook"), false, 'Test 8');
test(halvesAreAlike("cOdInGQuEsTiOn"), false, 'Test 9');
test(halvesAreAlike("pYthOnPrOgRaMmInG"), false, 'Test 10');
test(halvesAreAlike("AaEeIiOoUu"), true, 'Test 11');
test(halvesAreAlike("leetcode"), true, 'Test 12');
test(halvesAreAlike("Eve"), false, 'Test 13');
test(halvesAreAlike("racecar"), false, 'Test 14');
test(halvesAreAlike("VoIcE"), true, 'Test 15');
test(halvesAreAlike("Madam"), true, 'Test 16');
test(halvesAreAlike("abcdefgH"), true, 'Test 17');
test(halvesAreAlike("Margelet"), false, 'Test 18');
test(halvesAreAlike("book"), true, 'Test 19');
test(halvesAreAlike("Uncopyrightable"), true, 'Test 20');
test(halvesAreAlike("DAD"), false, 'Test 21');
test(halvesAreAlike("MerryChristmas"), false, 'Test 22');
test(halvesAreAlike("ComputerScience"), false, 'Test 23');
test(halvesAreAlike("ArtificialIntelligence"), false, 'Test 24');
test(halvesAreAlike("aAbBcCdDeEfFgG"), true, 'Test 25');
test(halvesAreAlike("Supercalifragilisticexpialidocious"), false, 'Test 26');
test(halvesAreAlike("InDiCoRn"), false, 'Test 27');
test(halvesAreAlike("vowelvowelvowelvowelvowelvowel"), true, 'Test 28');
test(halvesAreAlike("LyoPHiNiC"), false, 'Test 29');
test(halvesAreAlike("VowelCOnsonAnt"), false, 'Test 30');
test(halvesAreAlike("SyNtHeSiS"), false, 'Test 31');
test(halvesAreAlike("CoMpUterScIeNcE"), false, 'Test 32');
test(halvesAreAlike("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"), true, 'Test 33');
test(halvesAreAlike("Pneumonoultramicroscopicsilicovolcanoconiosis"), false, 'Test 34');
test(halvesAreAlike("ABCDEFGHIJKLMNOPQRSTUVWXYZ"), false, 'Test 35');
test(halvesAreAlike("bBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ"), true, 'Test 36');
test(halvesAreAlike("Supercalifragilisticexpialidocioussuper"), false, 'Test 37');
test(halvesAreAlike("EqUiVaLeNt"), false, 'Test 38');
test(halvesAreAlike("unevenNumberOfVowels"), true, 'Test 39');
test(halvesAreAlike("MachineLearning"), true, 'Test 40');
test(halvesAreAlike("QuantumComputing"), true, 'Test 41');
test(halvesAreAlike("Pneumonoultramicroscopicsilicovolcanoconioses"), false, 'Test 42');
test(halvesAreAlike("DeViScIoN"), true, 'Test 43');
test(halvesAreAlike("AbCdEfGhIjKlMnOpQrStUvWxYz"), false, 'Test 44');
test(halvesAreAlike("CoRaL"), true, 'Test 45');
test(halvesAreAlike("Internationalization"), true, 'Test 46');
test(halvesAreAlike("CaSeInSeNsItIvE"), true, 'Test 47');
test(halvesAreAlike("EvEnAnDdOuD"), false, 'Test 48');
test(halvesAreAlike("CoMpLeX"), true, 'Test 49');
test(halvesAreAlike("AbcDeFgHiJkLmNoPqRsTuVwXyZ"), false, 'Test 50');
test(halvesAreAlike("Electroencephalographies"), true, 'Test 51');
test(halvesAreAlike("fAcEtImE"), true, 'Test 52');
test(halvesAreAlike("AnALoGuIzAtIoN"), true, 'Test 53');
test(halvesAreAlike("sImPlEVoWaElStRiNg"), true, 'Test 54');
test(halvesAreAlike("OpenAIChatGPT"), false, 'Test 55');
test(halvesAreAlike("Incomprehensibility"), false, 'Test 56');
test(halvesAreAlike("ThEoReTiCaL"), false, 'Test 57');
test(halvesAreAlike("VoWaElCoUnTiNg"), true, 'Test 58');
test(halvesAreAlike("SiMpLy"), false, 'Test 59');
test(halvesAreAlike("Electroencephalography"), false, 'Test 60');
test(halvesAreAlike("Honorificabilitudinitatibus"), false, 'Test 61');
test(halvesAreAlike("ConsonantsToo"), true, 'Test 62');
test(halvesAreAlike("abcdefghijABCDEFGHIJ"), true, 'Test 63');
test(halvesAreAlike("METHINKSITISLIKEALITTLEIODEUCALYPTUS"), false, 'Test 64');
test(halvesAreAlike("Alphabetization"), false, 'Test 65');
test(halvesAreAlike("HumanComputerInteraction"), true, 'Test 66');
test(halvesAreAlike("AmOrAnGe"), true, 'Test 67');
test(halvesAreAlike("balancedString"), false, 'Test 68');
test(halvesAreAlike("EuPoCrAtIc"), false, 'Test 69');
test(halvesAreAlike("MississippiRiverOdd"), false, 'Test 70');
test(halvesAreAlike("RoMaNiCa"), true, 'Test 71');
test(halvesAreAlike("aAaAaAaAaAbBbBbBbB"), false, 'Test 72');
test(halvesAreAlike("MiwEldrom"), false, 'Test 73');
test(halvesAreAlike("AQuickBrownFoxJumpsOverTheLazyDog"), false, 'Test 74');
test(halvesAreAlike("MaRiNo"), false, 'Test 75');
test(halvesAreAlike("CloudComputing"), false, 'Test 76');
test(halvesAreAlike("DataScienceAndML"), false, 'Test 77');
test(halvesAreAlike("Hippopotomonstrosesquippedaliophobia"), false, 'Test 78');
test(halvesAreAlike("ImAgInAtIoN"), true, 'Test 79');
test(halvesAreAlike("Pseudopseudohypoparathyroidism"), true, 'Test 80');
test(halvesAreAlike("PaLInDoRoMa"), true, 'Test 81');
test(halvesAreAlike("DatabaseManagement"), true, 'Test 82');
test(halvesAreAlike("ComplexExample"), false, 'Test 83');
test(halvesAreAlike("sYmMeTrIcVoWaEl"), false, 'Test 84');
test(halvesAreAlike("QwErTyUiOpAsDfGhJkLzXcVbNm"), false, 'Test 85');
test(halvesAreAlike("cOmPlExStRiNgWitHaLoTOfVoWels"), false, 'Test 86');
test(halvesAreAlike("AlEpInAtIoN"), true, 'Test 87');
test(halvesAreAlike("AEIOUaeiouAEIOUaeiou"), true, 'Test 88');
test(halvesAreAlike("Environmental"), false, 'Test 89');
test(halvesAreAlike("SyMmEtrY"), false, 'Test 90');
test(halvesAreAlike("PaLInDrOmE"), true, 'Test 91');
test(halvesAreAlike("Interpolation"), false, 'Test 92');
test(halvesAreAlike("Floccinaucinihilipilifications"), true, 'Test 93');
test(halvesAreAlike("AlphabetSymmetry"), false, 'Test 94');
test(halvesAreAlike("BiChRoChO"), true, 'Test 95');
test(halvesAreAlike("SoftwareEngineering"), true, 'Test 96');
test(halvesAreAlike("Mississippi"), false, 'Test 97');
test(halvesAreAlike("NaturalLanguageProcessing"), true, 'Test 98');
test(halvesAreAlike("VowelsInBoth"), true, 'Test 99');
test(halvesAreAlike("FLUtTuAtIoNs"), false, 'Test 100');
test(halvesAreAlike("SuPeRaLpHaBeT"), false, 'Test 101');
test(halvesAreAlike("MaLiNoUs"), true, 'Test 102');
test(halvesAreAlike("InternetOfThings"), false, 'Test 103');
test(halvesAreAlike("PeRuKkIa"), true, 'Test 104');
test(halvesAreAlike("TrAnSaPoRt"), false, 'Test 105');
test(halvesAreAlike("OddAndEven"), true, 'Test 106');
test(halvesAreAlike("aEiOuUoIeA"), true, 'Test 107');
test(halvesAreAlike("Alphabetical"), false, 'Test 108');
test(halvesAreAlike("VowelsAEIOUaeiou"), false, 'Test 109');
test(halvesAreAlike("aEiOuUeIoA"), true, 'Test 110');
test(halvesAreAlike("SeNtEnCe"), false, 'Test 111');
test(halvesAreAlike("RepetitionRepetition"), true, 'Test 112');
test(halvesAreAlike("MississippiRiver"), true, 'Test 113');
test(halvesAreAlike("Vowelsareeverywhere"), false, 'Test 114');
test(halvesAreAlike("vowelvowelvowelvowel"), true, 'Test 115');
test(halvesAreAlike("DataStructure"), true, 'Test 116');
test(halvesAreAlike("MississippiRiverside"), false, 'Test 117');
test(halvesAreAlike("aeiouAEIOUaeiouAEIOU"), true, 'Test 118');
test(halvesAreAlike("XiLoPhOnE"), false, 'Test 119');
test(halvesAreAlike("Floccinaucinihilipilification"), false, 'Test 120');
test(halvesAreAlike("PythonCoding"), false, 'Test 121');
test(halvesAreAlike("VowelsAreVowels"), true, 'Test 122');
test(halvesAreAlike("aEiOuUaEiO"), true, 'Test 123');
test(halvesAreAlike("NotSoBalanced"), false, 'Test 124');
test(halvesAreAlike("Engineering"), false, 'Test 125');
test(halvesAreAlike("SuBiT"), true, 'Test 126');
test(halvesAreAlike("ProgrammingIsFun"), false, 'Test 127');
test(halvesAreAlike("aEiOuAeIoU"), true, 'Test 128');
test(halvesAreAlike("Alphabetically"), false, 'Test 129');
test(halvesAreAlike("PyThOnIsFuN"), false, 'Test 130');
test(halvesAreAlike("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"), false, 'Test 131');
test(halvesAreAlike("AnNiHaLiLaToR"), true, 'Test 132');
test(halvesAreAlike("zyxwvutsrqponmlkjihgfedcba"), false, 'Test 133');
test(halvesAreAlike("consonantsAEIOUconsonants"), false, 'Test 134');
test(halvesAreAlike("Thyroparathyroidectomized"), false, 'Test 135');
test(halvesAreAlike("EvenlyDistributed"), true, 'Test 136');
test(halvesAreAlike("DataAnalysis"), false, 'Test 137');
test(halvesAreAlike("CyberSecurity"), false, 'Test 138');
test(halvesAreAlike("VoCaBuLaRy"), true, 'Test 139');
test(halvesAreAlike("AEIOUaeiou"), true, 'Test 140');
test(halvesAreAlike("abcdefghijklmnopqrstuvwxyz"), false, 'Test 141');
test(halvesAreAlike("CaThODoRiC"), true, 'Test 142');
test(halvesAreAlike("AlGoRiThM"), false, 'Test 143');
test(halvesAreAlike("Antidisestablishmentarianism"), false, 'Test 144');
test(halvesAreAlike("CoNtRoVeRtEdbUt"), false, 'Test 145');
test(halvesAreAlike("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz"), false, 'Test 146');
test(halvesAreAlike("BaLaNcEd"), false, 'Test 147');
test(halvesAreAlike("BlockchainTechnology"), true, 'Test 148');
test(halvesAreAlike("SystemAnalysis"), true, 'Test 149');
test(halvesAreAlike("VowelsAndConsonants"), true, 'Test 150');
test(halvesAreAlike("hAlFVaLuEs"), false, 'Test 151');
test(halvesAreAlike("AlphabetSoup"), false, 'Test 152');
test(halvesAreAlike("Unbelievable"), true, 'Test 153');
test(halvesAreAlike("SplittingStrings"), false, 'Test 154');
test(halvesAreAlike("GrApHiTe"), false, 'Test 155');
test(halvesAreAlike("AnAgrAm"), false, 'Test 156');
test(halvesAreAlike("evenNumberOfVowels"), false, 'Test 157');
test(halvesAreAlike("RoTiCoRn"), false, 'Test 158');
test(halvesAreAlike("bYtEcOdE"), false, 'Test 159');
test(halvesAreAlike("BigDataAnalytics"), false, 'Test 160');
test(halvesAreAlike("FLYINGDUCK"), true, 'Test 161');
test(halvesAreAlike("ComplexityAnalysis"), true, 'Test 162');
test(halvesAreAlike("VowelsAreEven"), false, 'Test 163');
test(halvesAreAlike("cHiCaGo"), true, 'Test 164');
test(halvesAreAlike("PythonIsAwesome"), false, 'Test 165');
test(halvesAreAlike("FeBrIfIoN"), false, 'Test 166');
test(halvesAreAlike("Electroencephalographically"), true, 'Test 167');
test(halvesAreAlike("mIxEdCaSeTeStStRiNg"), false, 'Test 168');
test(halvesAreAlike("ProgrammingLanguage"), true, 'Test 169');
test(halvesAreAlike("MississippiUniversity"), false, 'Test 170');
test(halvesAreAlike("equalvowelcounts"), false, 'Test 171');
test(halvesAreAlike("EnvironmentalStudies"), true, 'Test 172');
test(halvesAreAlike("InDeXeS"), false, 'Test 173');
test(halvesAreAlike("Supercalifragilisticexpialidociousxyz"), false, 'Test 174');
test(halvesAreAlike("xyzXYZxyzXYZ"), true, 'Test 175');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

