// Test: 1926. Nearest Exit From Entrance In Maze
// 116 test cases from LeetCodeDataset
// Run: node test.js

const { nearestExit } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1926. Nearest Exit From Entrance In Maze\n");

test(nearestExit([["+]","+]","+]",[".+",".+",".+",["+]","+]","+]"]], [1,0]), Error: Solution.nearestExit[] missing 1 required positional argument: 'maze', 'Test 1');
test(nearestExit([[".+",["+]"]], [0,0]), Error: Solution.nearestExit[] missing 1 required positional argument: 'maze', 'Test 2');
test(nearestExit({"maze": [["+","+",".","+"],[".",".",".","+"],["+","+","+","."]], "entrance": [1,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 3');
test(nearestExit({"maze": [["+","+","+"],[".",".","."],["+","+","+"]], "entrance": [1,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 4');
test(nearestExit([[".","+"],], [0,0]), -1, 'Test 5');
test(nearestExit([[".",".","."],[".",".","."],[".",".","."]], [0,1]), 1, 'Test 6');
test(nearestExit([[".",".",".","."],[".",".",".","."],[".",".",".","."],[".",".",".","."]], [0,0]), 1, 'Test 7');
test(nearestExit([[".+",".+",".+",[".+",".+",".+"]], [1,1]), Error: Solution.nearestExit[] missing 1 required positional argument: 'maze', 'Test 8');
test(nearestExit([[".",".","."],[".",".","."],[".",".","."]], [2,2]), 1, 'Test 9');
test(nearestExit([[".+",".+",[".+",".+"]], [0,1]), Error: Solution.nearestExit[] missing 1 required positional argument: 'maze', 'Test 10');
test(nearestExit({"maze": [[".",".","."],[".",".","."],[".",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 11');
test(nearestExit([["+]","+]","+"],[".",".","."],["+]","+]","+"]], [1,0]), 2, 'Test 12');
test(nearestExit([["+]","+]","."],[".",".",".","+"],["+]","+]","+]","."]], [1,2]), 1, 'Test 13');
test(nearestExit([["+]","+]",".+",["+]",".+",".+",["+]","+]",".+"]], [1,2]), Error: Solution.nearestExit[] missing 1 required positional argument: 'maze', 'Test 14');
test(nearestExit([["+",".","+"],[".",".","."],["+",".","+"]], [1,1]), 1, 'Test 15');
test(nearestExit([[".",".","+","."],[".",".",".","."],[".",".",".","."],[".",".",".","."]], [0,3]), 1, 'Test 16');
test(nearestExit([[".",".",".","."],[".","+",".","."],[".",".",".","."],[".",".",".","."]], [1,1]), 1, 'Test 17');
test(nearestExit([[".",".","."],[".",".","."],[".",".","."]], [1,1]), 1, 'Test 18');
test(nearestExit({"maze": [[".","+"],"entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 19');
test(nearestExit({"maze": [["+","+","+","+"],[".",".",".","."],["+",".",".","+"],["+","+","+","+"]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 20');
test(nearestExit({"maze": [[".",".",".",".","."],[".","+","+","+","."],[".",".",".",".","."],[".",".","+",".","."],[".",".",".",".","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 21');
test(nearestExit({"maze": [[".",".","+",".","."],[".","+",".",".","."],["+",".",".",".","+"],[".","+",".",".","."],[".",".","+",".","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 22');
test(nearestExit({"maze": [[".",".",".","."],[".","+","+","."],[".","+",".","."],[".",".",".","."]], "entrance": [3,3]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 23');
test(nearestExit({"maze": [[".",".","+","+","."],["+",".",".","+","."],[".",".",".",".","."],[".",".","+",".","."],[".",".","+","+","."]], "entrance": [2,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 24');
test(nearestExit({"maze": [["+","+","+","."],[".",".",".","."],[".","+","+","."],[".",".",".","+"],["+",".",".","."]], "entrance": [1,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 25');
test(nearestExit({"maze": [[".",".",".",".","."],[".",".","+",".","."],[".",".",".",".","."],[".",".",".",".","."],[".",".",".",".","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 26');
test(nearestExit({"maze": [[".",".",".","+"],[".","+",".","."],[".",".","+","."],[".","+",".","."],[".",".",".","."],[".",".",".","+"],["+","+",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 27');
test(nearestExit({"maze": [[".",".",".","+"],[".","+",".","."],[".",".","+","."],[".",".",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 28');
test(nearestExit({"maze": [["+","+","+"],[".",".","."],["+","+","+"],[".",".","."],["+","+","+"],[".",".","."]], "entrance": [3,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 29');
test(nearestExit({"maze": [[".",".",".","."],[".","+",".","."],[".","+",".","."],[".","+","+","."],[".",".",".","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 30');
test(nearestExit({"maze": [["+",".",".","."],[".",".",".","."],[".",".","+","."],[".","+",".","."]], "entrance": [0,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 31');
test(nearestExit({"maze": [[".",".",".",".","."],[".","+","+","+","."],[".","+",".","+","."],[".","+","+","+","."],[".",".",".",".","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 32');
test(nearestExit({"maze": [[".",".",".","+","."],[".","+","+","+","."],[".",".",".",".","."],[".",".",".",".","."],[".",".",".",".","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 33');
test(nearestExit({"maze": [[".",".","+"],[".",".","."],[".",".","."]], "entrance": [0,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 34');
test(nearestExit({"maze": [[".",".",".",".","."],[".","+","+","+","."],[".",".",".","+","."],[".","+",".","+","."],[".",".",".",".","."]], "entrance": [0,4]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 35');
test(nearestExit({"maze": [[".",".",".","+"],["+","+",".","."],[".",".","+","."],[".",".",".","."]], "entrance": [1,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 36');
test(nearestExit({"maze": [["+",".",".","+"],["+",".",".","+"],["+","+",".","+"],["+",".",".","+"],["+","+","+","+"]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 37');
test(nearestExit({"maze": [[".",".","+"],[".","+","."],[".",".","."]], "entrance": [0,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 38');
test(nearestExit({"maze": [[".",".","+","+"],[".",".",".","."],[".",".",".","."],[".","+",".","."],[".","+","+","."]], "entrance": [4,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 39');
test(nearestExit({"maze": [[".",".",".",".","."],[".",".",".",".","."],[".",".",".",".","."],[".",".",".",".","."],[".",".",".",".","."],[".",".",".",".","."],[".",".",".",".","."]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 40');
test(nearestExit({"maze": [["+","+","+","."],[".",".",".","."],["+","+","+","+"],[".",".",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 41');
test(nearestExit({"maze": [["+",".","+"],[".",".","."],["+",".","+"]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 42');
test(nearestExit({"maze": [[".","+",".",".","."],[".",".",".","+","."],["+",".",".",".","+"],[".",".",".",".","."],[".","+",".",".","."]], "entrance": [1,3]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 43');
test(nearestExit({"maze": [[".","+",".","+",".","+"],["+",".",".",".",".","."],[".",".",".",".",".","."],[".","+",".","+",".","+"],[".",".",".",".",".","."],[".",".",".",".",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 44');
test(nearestExit({"maze": [["+","+","+"],["+",".","."],["+",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 45');
test(nearestExit({"maze": [[".",".",".","."],[".","+",".","."],[".",".",".","."],[".",".",".","."],[".",".",".","."]], "entrance": [1,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 46');
test(nearestExit({"maze": [[".",".",".","+"],[".","+","+","."],[".",".",".","."],["+",".","+","."]], "entrance": [0,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 47');
test(nearestExit({"maze": [[".","+","+"],[".",".","."],[".","+","."],[".",".","+"],[".",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 48');
test(nearestExit({"maze": [[".",".",".","."],[".","+",".","."],[".",".","+","."],[".",".",".","."],[".","+","+","."]], "entrance": [2,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 49');
test(nearestExit({"maze": [[".",".",".","+"],[".","+","+","."],[".",".",".","."],[".",".",".","."],[".",".",".","+"],[".","+","+","."]], "entrance": [0,3]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 50');
test(nearestExit({"maze": [[".",".",".","+","+"],[".","+",".",".","."],[".","+",".","+","."],[".","+",".",".","."],[".",".",".",".","+"]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 51');
test(nearestExit({"maze": [["+","+","+","+","+"],[".",".",".",".","."],[".","+","+","+","."],[".",".",".",".","."],["+","+","+","+","+"]], "entrance": [2,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 52');
test(nearestExit({"maze": [[".","+","+"],[".","+","+"],["+",".","+"],[".",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 53');
test(nearestExit({"maze": [[".",".",".","+"],[".","+",".","."],[".",".",".","+"],[".",".",".","."]], "entrance": [0,3]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 54');
test(nearestExit({"maze": [[".",".",".","+"],["+","+",".","."],[".",".","+","."],[".","+",".","."],[".",".",".","."]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 55');
test(nearestExit({"maze": [["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 56');
test(nearestExit({"maze": [[".",".",".",".","."],["+",".",".",".","."],[".",".","+",".","."],[".",".",".",".","."],[".",".",".",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 57');
test(nearestExit({"maze": [[".",".",".",".","."],["+","+","+","+","."],[".",".",".",".","."],[".",".",".","+","."],[".",".",".",".","."]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 58');
test(nearestExit({"maze": [[".","+",".","+","."],[".",".",".",".","."],["+","+","+",".","+"],[".",".",".",".","."],[".",".",".",".","."]], "entrance": [3,3]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 59');
test(nearestExit({"maze": [[".",".",".","+"],[".","+","+","."],[".",".","+","."],[".",".",".","."]], "entrance": [1,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 60');
test(nearestExit({"maze": [[".",".","+","."],[".","+",".","."],[".",".",".","."],[".",".","+","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 61');
test(nearestExit({"maze": [["+",".",".",".","+"],[".",".","+",".","."],[".",".",".",".","."],[".",".","+",".","."],["+",".",".",".","+"]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 62');
test(nearestExit({"maze": [[".","+","+",".","."],[".",".",".",".","."],[".",".","+",".","."],[".",".",".",".","."],[".",".",".",".","."]], "entrance": [3,3]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 63');
test(nearestExit({"maze": [["+",".",".",".","+"],[".",".","+",".","."],["+",".","+",".","."],[".",".",".",".","."],[".","+",".","+","."]], "entrance": [3,3]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 64');
test(nearestExit({"maze": [["+","+","+","+"],[".","+",".","."],[".",".",".","."],["+",".","+","+"],[".",".",".","+"]], "entrance": [1,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 65');
test(nearestExit({"maze": [[".",".","+"],[".","+","."],[".",".","."],["+",".","."],[".",".","+"]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 66');
test(nearestExit({"maze": [[".","+","+"],[".",".","."],[".","+","."]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 67');
test(nearestExit({"maze": [[".",".","+","."],[".",".",".","."],[".",".",".","."],[".","+",".","."],[".",".","+","."]], "entrance": [0,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 68');
test(nearestExit({"maze": [["+","+","+","+"],["+",".",".","."],["+",".",".","."],["+","+","+","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 69');
test(nearestExit({"maze": [[".",".","+","."],[".",".",".","."],[".",".",".","."],[".","+","+","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 70');
test(nearestExit({"maze": [[".",".",".","."],[".","+","+","."],[".",".",".","."],[".",".","+","."]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 71');
test(nearestExit({"maze": [["+","+","+","+"],[".",".",".","."],["+","+",".","+"],[".",".",".","."],["+",".",".","+"]], "entrance": [1,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 72');
test(nearestExit({"maze": [[".",".",".",".","+"],[".",".",".",".","."],[".",".",".",".","."],["+","+","+","+","."],[".",".",".",".","."]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 73');
test(nearestExit({"maze": [[".","+",".","+","+"],[".","+",".",".","."],["+",".",".","+","+"],[".",".",".",".","+"],["+","+","+",".","+"]], "entrance": [1,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 74');
test(nearestExit({"maze": [["+",".",".","+"],[".",".",".","."],["+",".",".","+"],[".",".",".","+"]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 75');
test(nearestExit({"maze": [[".",".",".","."],[".",".",".","."],[".",".",".","."],[".",".",".","."]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 76');
test(nearestExit({"maze": [["+",".","+"],[".","+","."],["+",".","+"],[".",".","."],["+",".","+"],[".",".","."]], "entrance": [0,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 77');
test(nearestExit({"maze": [[".",".",".","."],[".","+","+","."],[".",".",".","."],[".",".",".","."]], "entrance": [1,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 78');
test(nearestExit({"maze": [["+","+","+","+","+"],[".",".",".",".","."],["+","+",".","+","+"],[".",".",".",".","."],["+","+","+","+","+"],[".",".",".",".","."],["+","+","+","+","+"],[".",".",".",".","."],["+","+","+","+","+"],[".",".",".",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 79');
test(nearestExit({"maze": [[".","+","+","+"],[".",".",".","."],["+",".","+","."],[".",".",".","+"]], "entrance": [0,3]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 80');
test(nearestExit({"maze": [["+",".","+",".","+"],[".",".",".",".","."],["+","+",".","+","+"],[".",".",".",".","."],["+",".","+",".","+"],"entrance": [1,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 81');
test(nearestExit({"maze": [[".",".",".",".","."],[".","+","+","+","."],[".",".",".",".","."],[".","+","+","+","."],[".",".",".",".","."]], "entrance": [0,4]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 82');
test(nearestExit({"maze": [[".",".",".","+"],[".","+",".","."],[".",".",".","."],[".","+","+","."]], "entrance": [3,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 83');
test(nearestExit({"maze": [["+",".",".","+"],[".",".",".","."],[".",".",".","."],["+",".",".","+"],[".",".",".","."],["+",".",".","+"],["+","+","+","+"], "entrance": [3,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 84');
test(nearestExit({"maze": [[".",".","+","."],[".","+",".","."],[".",".",".","."],[".","+","+","."]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 85');
test(nearestExit({"maze": [[".",".",".",".","."],[".",".",".",".","."],[".",".",".",".","."],[".",".",".",".","."],[".",".",".",".","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 86');
test(nearestExit({"maze": [[".",".","+"],[".","+","."],["+",".","."],[".",".","+"],[".","+","."],[".",".","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 87');
test(nearestExit({"maze": [[".","+",".","+"],[".",".",".","."],[".",".","+","."],["+","+",".","+"],[".",".",".","."]], "entrance": [3,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 88');
test(nearestExit({"maze": [[".","+","+","+","."],["+","+",".",".","."],[".",".",".",".","."],[".",".",".",".","+"],[".",".",".",".","."]], "entrance": [0,4]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 89');
test(nearestExit({"maze": [[".",".",".",".",".","."],[".","+","+","+","+","."],[".",".",".",".",".","."],[".","+","+","+","+","."],[".",".",".",".",".","."],[".",".",".",".",".","."]], "entrance": [0,5]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 90');
test(nearestExit({"maze": [[".","+","+","+"],[".",".",".","."],[".","+",".","+"],[".",".",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 91');
test(nearestExit({"maze": [[".",".",".",".","."],[".","+",".",".","."],[".",".",".",".","."],[".","+",".",".","."],[".",".",".",".","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 92');
test(nearestExit({"maze": [[".",".",".",".",".","+","."],[".","+","+",".","+","+","."],[".",".",".",".",".","+","."],[".","+",".",".",".",".","."],[".","+",".",".",".","+","."],[".",".",".",".",".","+","."]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 93');
test(nearestExit({"maze": [[".",".",".","."],[".","+","+","."],[".",".",".","."],[".",".","+","."]], "entrance": [0,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 94');
test(nearestExit({"maze": [[".",".","+",".","."],[".","+","+",".","."],[".",".",".",".","."],[".","+","+",".","."],[".",".","+",".","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 95');
test(nearestExit({"maze": [[".",".",".","+"],[".","+",".","."],[".","+",".","+"],[".",".",".","."]], "entrance": [3,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 96');
test(nearestExit({"maze": [[".",".",".","."],[".","+",".","."],[".",".","+","."],[".",".",".","."]], "entrance": [0,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 97');
test(nearestExit({"maze": [["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"],["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"]], "entrance": [50,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 98');
test(nearestExit({"maze": [["+","+","+","+","+","+"],["+",".",".",".",".","+"],["+",".","+",".",".","+"],["+",".",".",".",".","+"],["+","+","+","+","+","+"], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 99');
test(nearestExit({"maze": [[".","+","+","+"],[".","+",".","."],[".",".","+","."],[".","+",".","."]], "entrance": [2,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 100');
test(nearestExit({"maze": [[".",".",".",".",".","+"],[".","+","+","+",".","."],[".","+",".","+",".","."],[".","+","+","+",".","."],[".",".",".",".",".","+"],[".",".",".",".",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 101');
test(nearestExit({"maze": [[".",".",".","."],["+",".",".","."],[".",".",".","."],[".",".",".","."]], "entrance": [0,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 102');
test(nearestExit({"maze": [[".","+","+","."],[".","+",".","."],[".",".",".","."],[".",".",".","."]], "entrance": [2,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 103');
test(nearestExit({"maze": [[".",".","+","+","."],[".",".",".",".","."],["+","+",".","+","+"],[".",".",".",".","."],[".","+",".",".","."]], "entrance": [0,4]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 104');
test(nearestExit({"maze": [["+","+","+","+","+","+","+","+"],["+",".",".",".",".",".",".","+"],["+",".","+","+","+","+",".","+"],["+",".",".",".",".",".",".","+"],["+",".","+","+","+","+","+","+"],["+",".",".",".",".",".",".","+"],["+","+","+","+","+","+",".","+"],["+",".",".",".",".",".",".","+"],["+","+","+","+","+","+","+","+"], "entrance": [4,4]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 105');
test(nearestExit({"maze": [[".",".","+"],[".",".","."],[".",".","."]], "entrance": [2,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 106');
test(nearestExit({"maze": [["+",".","+","."],[".",".",".","."],[".","+",".","."],[".",".",".","+"]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 107');
test(nearestExit({"maze": [[".",".","+","."],[".","+",".","."],["+",".",".","+"],[".","+",".","."],[".",".",".","."]], "entrance": [4,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 108');
test(nearestExit({"maze": [[".",".","+","."],[".","+","+","."],[".",".","+","."],[".",".",".","."]], "entrance": [2,0]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 109');
test(nearestExit({"maze": [["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 110');
test(nearestExit({"maze": [[".",".","+","."],["+",".",".","."],[".",".","+","."],[".",".",".","."]], "entrance": [3,3]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 111');
test(nearestExit({"maze": [["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 112');
test(nearestExit({"maze": [[".","+","+"],[".",".","."],[".","+","."],[".",".","."]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 113');
test(nearestExit({"maze": [[".",".",".","+"],[".",".",".","."],[".","+",".","."],[".",".",".","."],["+",".",".","+"]], "entrance": [1,1]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 114');
test(nearestExit({"maze": [[".","+","+","+","+","+","."],[".",".",".",".",".",".","."],[".",".","+",".","+",".","."],[".","+",".",".",".","+","."],[".",".",".",".",".",".","."],[".","+","+","+","+","+","."]], "entrance": [3,3]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 115');
test(nearestExit({"maze": [["+","+","+","+"],["+",".",".","+"],["+",".",".","+"],["+","+","+","+"]], "entrance": [1,2]}), Error: Solution.nearestExit[] missing 2 required positional arguments: 'maze' and 'entrance', 'Test 116');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

