// Test: 649. Dota2 Senate
// 177 test cases from LeetCodeDataset
// Run: node test.js

const { predictPartyVictory } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n649. Dota2 Senate\n");

test(predictPartyVictory("RDDRDR"), Dire, 'Test 1');
test(predictPartyVictory("RDD"), Dire, 'Test 2');
test(predictPartyVictory("DDDARR"), Dire, 'Test 3');
test(predictPartyVictory("DRDR"), Dire, 'Test 4');
test(predictPartyVictory("RDDRRD"), Radiant, 'Test 5');
test(predictPartyVictory("RDRDRDRDRDRDRD"), Radiant, 'Test 6');
test(predictPartyVictory("RD"), Radiant, 'Test 7');
test(predictPartyVictory("DRDRDR"), Dire, 'Test 8');
test(predictPartyVictory("RRRDDD"), Radiant, 'Test 9');
test(predictPartyVictory("DDDD"), Dire, 'Test 10');
test(predictPartyVictory("RRDDRR"), Radiant, 'Test 11');
test(predictPartyVictory("DDDDRRRRRDDDDRRRR"), Dire, 'Test 12');
test(predictPartyVictory("RRDDDD"), Dire, 'Test 13');
test(predictPartyVictory("DDDDRRRR"), Dire, 'Test 14');
test(predictPartyVictory("RDRDRD"), Radiant, 'Test 15');
test(predictPartyVictory("DDRRR"), Dire, 'Test 16');
test(predictPartyVictory("DDDRRR"), Dire, 'Test 17');
test(predictPartyVictory("DDDDDDRRRRRR"), Dire, 'Test 18');
test(predictPartyVictory("RRDD"), Radiant, 'Test 19');
test(predictPartyVictory("RRRDDDDRRDDRR"), Radiant, 'Test 20');
test(predictPartyVictory("RRDDD"), Radiant, 'Test 21');
test(predictPartyVictory("DRDRDRDRDRDRDR"), Dire, 'Test 22');
test(predictPartyVictory("DRDRDRDR"), Dire, 'Test 23');
test(predictPartyVictory("DDRR"), Dire, 'Test 24');
test(predictPartyVictory("DDRDRR"), Dire, 'Test 25');
test(predictPartyVictory("RRRRDDDD"), Radiant, 'Test 26');
test(predictPartyVictory("RRRR"), Radiant, 'Test 27');
test(predictPartyVictory("RRRRRRRDDDDDDD"), Radiant, 'Test 28');
test(predictPartyVictory("RDRD"), Radiant, 'Test 29');
test(predictPartyVictory("DRDRDRDRDRDRDRDRDR"), Dire, 'Test 30');
test(predictPartyVictory("DRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRD"), Dire, 'Test 31');
test(predictPartyVictory("RRDDDRRRRDDDRRDD"), Radiant, 'Test 32');
test(predictPartyVictory("AAAAAAAAAAAAADDDDDDDDDDDAAAAAAAAAAAAADDDDDDDDDDDAAAAAAAAAAAAADDDDDDDDDDDAAAAAAAAAAAAADDDDDDDDDDD"), Dire, 'Test 33');
test(predictPartyVictory("RDRRDDRRDDRRDD"), Radiant, 'Test 34');
test(predictPartyVictory("DDDDDRRRRRRDDDDRRRRRRRRDDDRRR"), Radiant, 'Test 35');
test(predictPartyVictory("RDDDRDRDRRDDRR"), Dire, 'Test 36');
test(predictPartyVictory("DDDDDDDDRRRRRDDD"), Dire, 'Test 37');
test(predictPartyVictory("RRDDRRDDRRDDRRDD"), Radiant, 'Test 38');
test(predictPartyVictory("RRRRRDDDDD-DDRRR"), Radiant, 'Test 39');
test(predictPartyVictory("RRRRRRRRRRDDDDDDDDDD"), Radiant, 'Test 40');
test(predictPartyVictory("RDRDRDRDRDRDRDRD"), Radiant, 'Test 41');
test(predictPartyVictory("RRRDDDRRDDDRRDDDRRDDRRRRRR"), Radiant, 'Test 42');
test(predictPartyVictory("DDDRRDDDRRRDDDDD"), Dire, 'Test 43');
test(predictPartyVictory("DDDDDDDDRRRRRR"), Dire, 'Test 44');
test(predictPartyVictory("RDRRDDDRRDDDRRDDDRDD"), Dire, 'Test 45');
test(predictPartyVictory("RRDDDDRRRRDDDDRR"), Radiant, 'Test 46');
test(predictPartyVictory("DRRDDDDDDRRRRRDD"), Dire, 'Test 47');
test(predictPartyVictory("RRRRRRRRRRRDDDDDDDDDDDDDDDDD"), Radiant, 'Test 48');
test(predictPartyVictory("RRRDRRDDDRRDDDRRDDDRRDDDRRDDDR"), Radiant, 'Test 49');
test(predictPartyVictory("RDDDRRDDDRRDDDRRDDDRRDDDRRDD"), Dire, 'Test 50');
test(predictPartyVictory("RRRDDDDRRRDDDDRRRDDDDRRRDDDD"), Dire, 'Test 51');
test(predictPartyVictory("DDRDRDRDRDRDRDRDRDRD"), Dire, 'Test 52');
test(predictPartyVictory("RRDDDDDDRRRRRRDDDDDDRRRRRRDDDD"), Dire, 'Test 53');
test(predictPartyVictory("RRRRRRDDDDDDRRRRRRDDDDDDRRRRRRDD"), Radiant, 'Test 54');
test(predictPartyVictory("RRDDDDDRDDRRDDDR"), Dire, 'Test 55');
test(predictPartyVictory("DDDDDDRRRRRRRRRR"), Radiant, 'Test 56');
test(predictPartyVictory("RRRDDDRRDDDRRDDDRRDDRR"), Radiant, 'Test 57');
test(predictPartyVictory("RRDDDDDDRRRDDDRRRRDD"), Dire, 'Test 58');
test(predictPartyVictory("RDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRD"), Radiant, 'Test 59');
test(predictPartyVictory("DDDDRRRRRDRRDDDD"), Dire, 'Test 60');
test(predictPartyVictory("RDDDRRRRDDDDRRRR"), Radiant, 'Test 61');
test(predictPartyVictory("RRDRRDDDRRDDDRDD"), Radiant, 'Test 62');
test(predictPartyVictory("DDRDDRDDRDDRDDRDDRDDRDDRDDRDDRDDRDDRDDRDDRDDRDDRDDRDDRDDRDDRDD"), Dire, 'Test 63');
test(predictPartyVictory("DRDRDRDRDRDRDRDRDRDR"), Dire, 'Test 64');
test(predictPartyVictory("DDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAA"), Dire, 'Test 65');
test(predictPartyVictory("RRRRRRRDDDDDDDD"), Radiant, 'Test 66');
test(predictPartyVictory("DRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDR"), Dire, 'Test 67');
test(predictPartyVictory("RRRDDDDRRRRRDDDD"), Radiant, 'Test 68');
test(predictPartyVictory("RRRDDDRRDDDRRDDDRRDD"), Radiant, 'Test 69');
test(predictPartyVictory("DDDDDDDDDAAAAAAAAAAAADDDDDDDDDAAAAAAAAAAAADDDDDDDDDAAAAAAAAAAAA"), Dire, 'Test 70');
test(predictPartyVictory("RRRRRRRRDDDDDDDDD"), Radiant, 'Test 71');
test(predictPartyVictory("DRRDDDRRDDDRRDDDRRDDDDDDDD"), Dire, 'Test 72');
test(predictPartyVictory("RRRRRDDDDRRRRRDD"), Radiant, 'Test 73');
test(predictPartyVictory("RRRRRRRRRRDDDDDDDDDDDDDDDDDDDD"), Dire, 'Test 74');
test(predictPartyVictory("RRDDDDRRRRRDDDDRRRR"), Radiant, 'Test 75');
test(predictPartyVictory("AAAAAAAAAAADDDDDDDDDAAAAAAAAAAADDDDDDDDDAAAAAAAAAAADDDDDDDDDAAAAAAAAAAA"), Dire, 'Test 76');
test(predictPartyVictory("DDDDDDRRRRRRRRRRRRRR"), Radiant, 'Test 77');
test(predictPartyVictory("DDDDRRRRDDRRRDDRRRDD"), Dire, 'Test 78');
test(predictPartyVictory("RRRRDDDDDDRRRRRDDDDDDRRRRRDD"), Radiant, 'Test 79');
test(predictPartyVictory("RRDDRRRDRDDDRRDD"), Radiant, 'Test 80');
test(predictPartyVictory("RRDDDDRRDDDDRRDDDDRRDDDDRRDDDD"), Dire, 'Test 81');
test(predictPartyVictory("RRDDDRRDDDDDRRDD"), Dire, 'Test 82');
test(predictPartyVictory("RDDRRRDDDDRRRDDDDRRRDD"), Dire, 'Test 83');
test(predictPartyVictory("DRRDDDRRDDDRRDDDRRDDDDDD"), Dire, 'Test 84');
test(predictPartyVictory("DDDDRRRDDDDRRRDDDDRRRDDDDRRRDD"), Dire, 'Test 85');
test(predictPartyVictory("RRDRDRDRDRDRDRDRDRDR"), Radiant, 'Test 86');
test(predictPartyVictory("RRDDRRDDRRDDRRDDRRDDRRDDRRDDRRDD"), Radiant, 'Test 87');
test(predictPartyVictory("RRRDDDRRDDDRRDDDRRDDRRRDDDRRDDDRRDD"), Dire, 'Test 88');
test(predictPartyVictory("DDRRDDRRDDRRDDRRDDRRDDRRDDRRDDRRDDRRDDRRDD"), Dire, 'Test 89');
test(predictPartyVictory("DDDDDRRRDDDRRRDD"), Dire, 'Test 90');
test(predictPartyVictory("DRRRRRDDDDDDD"), Dire, 'Test 91');
test(predictPartyVictory("RDRDRDRDRDRDRDRDRDRDRDRDRDRDRD"), Radiant, 'Test 92');
test(predictPartyVictory("DDDDDDRRRRRRDDDDDDRRRRRRDDDDDD"), Dire, 'Test 93');
test(predictPartyVictory("RRRDDDDRRRDDRRRRRR"), Radiant, 'Test 94');
test(predictPartyVictory("DDRRDDRRDDRRDDRRDDRRDDRRDDRRDD"), Dire, 'Test 95');
test(predictPartyVictory("DRDDRRDDRRDDRRDD"), Dire, 'Test 96');
test(predictPartyVictory("RDDDRRDDDRRDDDRRDD"), Dire, 'Test 97');
test(predictPartyVictory("RRRRRRRDRDDDDDDD"), Radiant, 'Test 98');
test(predictPartyVictory("DDDRRRDDRRRDD"), Dire, 'Test 99');
test(predictPartyVictory("DDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRD"), Dire, 'Test 100');
test(predictPartyVictory("RRRRDDDDDDDDRRRRRRDDDD"), Dire, 'Test 101');
test(predictPartyVictory("DDRDRDRDRDRDRDRDRDRDRDRDRDRD"), Dire, 'Test 102');
test(predictPartyVictory("DRRDDDRRDDDRRDDDRRDDRRRDDDRRDDDRRDD"), Dire, 'Test 103');
test(predictPartyVictory("DDDDDDDDDDRRRRRRRRRR"), Dire, 'Test 104');
test(predictPartyVictory("DRDDRRDRDRDRDR"), Dire, 'Test 105');
test(predictPartyVictory("DDRRDDDDBBRRDDDDRRRRDDRRDDDDBB"), Dire, 'Test 106');
test(predictPartyVictory("RRRRDDDDDDDDRRRR"), Radiant, 'Test 107');
test(predictPartyVictory("AAAAAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAA"), Dire, 'Test 108');
test(predictPartyVictory("DDDDRRRRDDD"), Dire, 'Test 109');
test(predictPartyVictory("DDRRRRRRRRDD"), Radiant, 'Test 110');
test(predictPartyVictory("DDDDRRRRRRRRRRRRRDDDDDDDD"), Radiant, 'Test 111');
test(predictPartyVictory("RRRDDDRDDRRRDDDD"), Radiant, 'Test 112');
test(predictPartyVictory("RRRRDDDSSSSSRRRRRR"), Radiant, 'Test 113');
test(predictPartyVictory("RRRRRRDDDDDDDDDDDD"), Dire, 'Test 114');
test(predictPartyVictory("RRRRRDDDDDRRRRDDDD"), Radiant, 'Test 115');
test(predictPartyVictory("DDDDRRRRRR"), Dire, 'Test 116');
test(predictPartyVictory("RRRRDDD-DDDDDDRRRR"), Dire, 'Test 117');
test(predictPartyVictory("RRRRRDDDDD"), Radiant, 'Test 118');
test(predictPartyVictory("RRDDDDRRDDRRDDRRDDRRDDRRDD"), Dire, 'Test 119');
test(predictPartyVictory("RRRRRRRRRRRRDDDDDD"), Radiant, 'Test 120');
test(predictPartyVictory("DRRDDDRRDDDRRDDDRRDDDRRDDDRRDD"), Dire, 'Test 121');
test(predictPartyVictory("RRRDDDDRRRDDDDRRRDDDDRRRDDDDRRRDDDD"), Dire, 'Test 122');
test(predictPartyVictory("DDDDDDDDRRRRRRRRDDDDDDDDRRRRRRRR"), Dire, 'Test 123');
test(predictPartyVictory("DDRRRRDDDDRRRRDD"), Dire, 'Test 124');
test(predictPartyVictory("RRRRRDDDRRDDDRRDDDRRDD"), Radiant, 'Test 125');
test(predictPartyVictory("RRDRRDDRRRDDRRDR"), Radiant, 'Test 126');
test(predictPartyVictory("RRRRRDDDDDRRRRDDDDDRRRRDDDDD"), Radiant, 'Test 127');
test(predictPartyVictory("DRRRRDDDDDDD"), Dire, 'Test 128');
test(predictPartyVictory("DDDDDDDDDDDDDDRRRRRRRRRRRRRR"), Dire, 'Test 129');
test(predictPartyVictory("RRRRRRRDDDDDDDDD"), Radiant, 'Test 130');
test(predictPartyVictory("RRRDRRDDDRRDRRDDDRRDRRDDDRRD"), Radiant, 'Test 131');
test(predictPartyVictory("DRRDDDRRDDDRRDDDRRDD"), Dire, 'Test 132');
test(predictPartyVictory("RDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDR"), Radiant, 'Test 133');
test(predictPartyVictory("RRRDDDDRRRDDDDRRRDDDDRRRDDDDRR"), Dire, 'Test 134');
test(predictPartyVictory("RDRDRDRDRDRDRDRDRDRD"), Radiant, 'Test 135');
test(predictPartyVictory("RRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDRDR"), Radiant, 'Test 136');
test(predictPartyVictory("DRDRDRDRDRDRDRDRDRDRDRDR"), Dire, 'Test 137');
test(predictPartyVictory("RRRDRDDDRRDD"), Radiant, 'Test 138');
test(predictPartyVictory("DRDRDRDRDRDRDRDRDRDRDRDRDRDRDR"), Dire, 'Test 139');
test(predictPartyVictory("DDDDDDRRRRDDDDDDRRRRDDDDDDRRRR"), Dire, 'Test 140');
test(predictPartyVictory("RRRRRDDDDDDRRRRRDDDDDDRRRRRDDDDD"), Radiant, 'Test 141');
test(predictPartyVictory("RRRRDDDDRRRRDDDD"), Radiant, 'Test 142');
test(predictPartyVictory("RRRRRRRRRRRRRRRRRDDDDDDDDDDDDDDDDDRRRRRRRRRRRRRRRRDDDDDDDDDDDDDDDDDRRRRRRRRRRRRRRRRDDDDDDDDDDDDDDDDD"), Radiant, 'Test 143');
test(predictPartyVictory("RRDDRRDDRRDDRRDDRRDDRRDD"), Radiant, 'Test 144');
test(predictPartyVictory("RRDRDRDRDRDRDR"), Radiant, 'Test 145');
test(predictPartyVictory("DDDDDDDDDDDAAAAAAAAAAAAADDDDDDDDDAAAAAAAAAAAADDDDDDDDDAAAAAAAAAAADDDDDDDDDAAAAAAAAAAA"), Dire, 'Test 146');
test(predictPartyVictory("DRDDDRRDDDRRDDDRRDDDRRDDDRRDDDRRDD"), Dire, 'Test 147');
test(predictPartyVictory("DDDDDDRRRRRRDDDDDD"), Dire, 'Test 148');
test(predictPartyVictory("DDDDDDRRRRRRDDRRRRR"), Dire, 'Test 149');
test(predictPartyVictory("DDDRRRDDDDRRRRRDDDDDDRRRRRDDDDDDD"), Dire, 'Test 150');
test(predictPartyVictory("DDDDRRRRDDDDRRRRDDDDRRRRDDDDRRRRDDDDRRRR"), Dire, 'Test 151');
test(predictPartyVictory("RRDDRRDDRRDDRRDDRRDDRRDDRRDDRR"), Radiant, 'Test 152');
test(predictPartyVictory("DRRDDDRRDDDRRDDDRRDDDD"), Dire, 'Test 153');
test(predictPartyVictory("RRRRRDDDDDRRRRDDDDRRRRRDDDDDRR"), Radiant, 'Test 154');
test(predictPartyVictory("RRRRRDDDDDDDDDRRRRDDDDDDDDDRRRRDDDDDDDDDRRRRDDDDDDDDDRRRRDDDDDD"), Dire, 'Test 155');
test(predictPartyVictory("DDDDDDDDDDRRRRRRR"), Dire, 'Test 156');
test(predictPartyVictory("DDDDRRRRDDDDRRRR"), Dire, 'Test 157');
test(predictPartyVictory("DDDDRRDDDDRRDDDDRRDDDDRRDDDDRR"), Dire, 'Test 158');
test(predictPartyVictory("RRRRRDDDDDDDDDRRRDDDRRDDDD"), Dire, 'Test 159');
test(predictPartyVictory("RRRRDDDDRRRRDDDDRRRRDDDDRRRRDDDDRRRRDDDD"), Radiant, 'Test 160');
test(predictPartyVictory("RRRRRRRRRRRRRDDDDDDDDDDDDDRRRRRRRRRRRRDDDDDDDDDDDDDRRRRRRRRRRRRDDDDDDDDD"), Radiant, 'Test 161');
test(predictPartyVictory("DDDDDDDDRRRRRRRR"), Dire, 'Test 162');
test(predictPartyVictory("DDRRRDDDDRRRRDDDRRR"), Dire, 'Test 163');
test(predictPartyVictory("DDRRDDRRDDRRDDRR"), Dire, 'Test 164');
test(predictPartyVictory("RRDDDRRDDDRRDDDRRDDDRRDDDRRDDDRRDD"), Dire, 'Test 165');
test(predictPartyVictory("DDDDRRDDRRDDRRDDRRDD"), Dire, 'Test 166');
test(predictPartyVictory("DRDDRRDDRRDDRRDR"), Dire, 'Test 167');
test(predictPartyVictory("DRDRDRDRDRDRDRDR"), Dire, 'Test 168');
test(predictPartyVictory("RRRDDDDDRRRRDDDDDRRRRDDDDDRRRRDDDDDRRRRDDDD"), Dire, 'Test 169');
test(predictPartyVictory("RRRDDDDRRRDDDDRR"), Radiant, 'Test 170');
test(predictPartyVictory("RDDDRDDDRDDDRDDD"), Dire, 'Test 171');
test(predictPartyVictory("RRDRDRDRDRDRDRDRDRDRDRDRDRDR"), Radiant, 'Test 172');
test(predictPartyVictory("DDRRDDRRDDRRDDRRDDRRDDRRDDRRDDRR"), Dire, 'Test 173');
test(predictPartyVictory("DDRDRDRDRDRDRDRD"), Dire, 'Test 174');
test(predictPartyVictory("DDRDDDRRDDDRRDDDRRDDDRRDDDRRDDDR"), Dire, 'Test 175');
test(predictPartyVictory("RRRDDDRRDDDRRDDDRRDDRRRR"), Radiant, 'Test 176');
test(predictPartyVictory("RRRRRDDDDRRRDDDDRRRDDDDRRRDD"), Radiant, 'Test 177');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

