// Test: 10. Regular Expression Matching
// 151 test cases from LeetCodeDataset
// Run: node test.js

const { isMatch } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n10. Regular Expression Matching\n");

test(isMatch("aa", "a*"), true, 'Test 1');
test(isMatch("aab", "c*a*b"), true, 'Test 2');
test(isMatch("ab", ".*"), true, 'Test 3');
test(isMatch("aa", "a"), false, 'Test 4');
test(isMatch("mississippi", "mis*is*p*."), false, 'Test 5');
test(isMatch("aabbccddeeff", "a*b*c*d*e*f*f*"), true, 'Test 6');
test(isMatch("abababa", "[ab]*a"), false, 'Test 7');
test(isMatch("abcde", "a*.*e"), true, 'Test 8');
test(isMatch("ababcd", "a.*a.*d"), true, 'Test 9');
test(isMatch("aabbbbc", "a*b*c"), true, 'Test 10');
test(isMatch("aaaaaa", "a*a*a*a*a*a"), true, 'Test 11');
test(isMatch("aabb", "ab*a*b*"), true, 'Test 12');
test(isMatch("abcccccaaaa", "ab*c*a*.*"), true, 'Test 13');
test(isMatch("abcdef", "abc.*f"), true, 'Test 14');
test(isMatch("ababab", "[ab]*"), false, 'Test 15');
test(isMatch("ab", "a*b*c*d*.*e*"), true, 'Test 16');
test(isMatch("xaymz", "x.*z"), true, 'Test 17');
test(isMatch("xaybz", "xa*y*b*z"), true, 'Test 18');
test(isMatch("abcdefgh", "a*d*fh"), false, 'Test 19');
test(isMatch("aaa", "a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a"), true, 'Test 20');
test(isMatch("mississippi", "mi*ss*is*si*p*i*"), true, 'Test 21');
test(isMatch("zzzz", "z*"), true, 'Test 22');
test(isMatch("abcdefgh", "a.h"), false, 'Test 23');
test(isMatch("ababab", "[ab]*b*"), false, 'Test 24');
test(isMatch("abcdefgh", "a.*h"), true, 'Test 25');
test(isMatch("mississippi", "mi.*is.*p*i"), true, 'Test 26');
test(isMatch("abcdefgh", "abcdefgh"), true, 'Test 27');
test(isMatch("abcdefg", "a*bc.d*efg"), true, 'Test 28');
test(isMatch("abcdefgh", "a*b*c*d*e*f*g*h"), true, 'Test 29');
test(isMatch("abcdefgh", "a*b*c*d*e*f*g*h*"), true, 'Test 30');
test(isMatch("abcd", "a.b.c.d"), false, 'Test 31');
test(isMatch("aabbcc", "a*b*c*c"), true, 'Test 32');
test(isMatch("abc", "abc."), false, 'Test 33');
test(isMatch("mississippi", "m*is*i*s*i*p*i"), true, 'Test 34');
test(isMatch("mississippi", "m*i*ss*i*p*i*"), false, 'Test 35');
test(isMatch("abcde", "a.*de"), true, 'Test 36');
test(isMatch("abcdeabcde", "abc*de*abc*de*"), true, 'Test 37');
test(isMatch("abcd", "a*b*c*d*"), true, 'Test 38');
test(isMatch("abcde", "a*.b*c*e*"), false, 'Test 39');
test(isMatch("aabbbcccddd", "a*b*c*d*"), true, 'Test 40');
test(isMatch("abc", "a.b.c"), false, 'Test 41');
test(isMatch("abababab", "[ab]*"), false, 'Test 42');
test(isMatch("hello", "he*llo*"), true, 'Test 43');
test(isMatch("hello", "he.*o"), true, 'Test 44');
test(isMatch("abcd", "d*"), false, 'Test 45');
test(isMatch("abcde", "a..de"), true, 'Test 46');
test(isMatch("abcabcabcabc", "[abc]*d"), false, 'Test 47');
test(isMatch("abcdabcd", "abcd*"), false, 'Test 48');
test(isMatch("aabb", "aab*b*"), true, 'Test 49');
test(isMatch("xyzzy", "x*zy"), false, 'Test 50');
test(isMatch("abcd", "a.*d"), true, 'Test 51');
test(isMatch("xxyyzz", "x*y*z*"), true, 'Test 52');
test(isMatch("abc", "a.c"), true, 'Test 53');
test(isMatch("xyxxyxyx", "[xy]*x"), false, 'Test 54');
test(isMatch("aabbbccc", "a*b*c*"), true, 'Test 55');
test(isMatch("abcabcabcabc", "[abc]*"), false, 'Test 56');
test(isMatch("abcdef", "a*bcdef"), true, 'Test 57');
test(isMatch("aaaab", "a*b*"), true, 'Test 58');
test(isMatch("complex", "c*o*m*p*l*e*x*"), true, 'Test 59');
test(isMatch("aaa", "a*a"), true, 'Test 60');
test(isMatch("xyz", "x*y*z*"), true, 'Test 61');
test(isMatch("abcdefgh", "a.*g"), false, 'Test 62');
test(isMatch("abcde", "a*b.c*d*e*"), true, 'Test 63');
test(isMatch("abcde", "a*b*c*d*e*"), true, 'Test 64');
test(isMatch("zzzzzzzzzzzz", "z*z*z*z*z*z*z*z*z*z*z*z*z*z*z*z*z*"), true, 'Test 65');
test(isMatch("aabbccddeeff", "a*b*c*d*e*f*"), true, 'Test 66');
test(isMatch("hello", "he.*"), true, 'Test 67');
test(isMatch("abcde", "a*b*c*d.e"), false, 'Test 68');
test(isMatch("aaaaabbb", "a*b*.*"), true, 'Test 69');
test(isMatch("aabbccddeeffgghh", "a*b*c*d*e*f*g*h*"), true, 'Test 70');
test(isMatch("abbabb", "a*b*b*"), false, 'Test 71');
test(isMatch("sequence", "s.e*q*u*e*n*c*e*"), true, 'Test 72');
test(isMatch("abcdabcd", "a*b*c*d*"), false, 'Test 73');
test(isMatch("abcdedef", "abcd*e*f*"), false, 'Test 74');
test(isMatch("abcdefgh", "a.b.c.d.e.f.g.h"), false, 'Test 75');
test(isMatch("mississippi", "mi.*.pi.*"), true, 'Test 76');
test(isMatch("hello", "he*ll*o"), true, 'Test 77');
test(isMatch("abcde", "a*bc.e*"), true, 'Test 78');
test(isMatch("aaaab", "a*a*a*a"), false, 'Test 79');
test(isMatch("abcde", "a.*e"), true, 'Test 80');
test(isMatch("aabbb", "a*b*b"), true, 'Test 81');
test(isMatch("regex", "r.e*g*e*x*"), true, 'Test 82');
test(isMatch("abcdef", "a*b*c*d*e*f*"), true, 'Test 83');
test(isMatch("aaaa", "a*a*a*a"), true, 'Test 84');
test(isMatch("teststring", "te*t*st*ring"), false, 'Test 85');
test(isMatch("abcde", "a*b*c*de"), true, 'Test 86');
test(isMatch("bbbac", "ba*ac"), false, 'Test 87');
test(isMatch("aabbccddeeffgg", "a*b*c*d*e*f*g*"), true, 'Test 88');
test(isMatch("abcde", "a*bc*de"), true, 'Test 89');
test(isMatch("xyxyxyxyxyx", "x.y.x.y.x.y.x.y.x.y.x"), false, 'Test 90');
test(isMatch("a", "a*a*a*a*"), true, 'Test 91');
test(isMatch("abababab", "a*b*a*b*a*b*a*b"), true, 'Test 92');
test(isMatch("abcdeabcdeabcde", "abc*de*abc*de*abc*de*f*"), true, 'Test 93');
test(isMatch("abbbba", "ab*ba"), true, 'Test 94');
test(isMatch("teststring", "t.*st.*r.*ing"), true, 'Test 95');
test(isMatch("abcabc", "abc*"), false, 'Test 96');
test(isMatch("abcd", "a*b*c*d*.*"), true, 'Test 97');
test(isMatch("zzzzzzzzzzzz", "z*"), true, 'Test 98');
test(isMatch("mississippi", "m.*s*is*p*i*.*"), true, 'Test 99');
test(isMatch("abcdefgh", ".*"), true, 'Test 100');
test(isMatch("abcdefg", ".*f.*"), true, 'Test 101');
test(isMatch("abccde", "abc*d*e"), true, 'Test 102');
test(isMatch("aabbbccdd", "aa*bbb*cc*dd*"), true, 'Test 103');
test(isMatch("foobar", "fo*oba*r"), true, 'Test 104');
test(isMatch("abcde", "a.*f"), false, 'Test 105');
test(isMatch("aabb", "a*b*b*a*"), true, 'Test 106');
test(isMatch("zabczabcz", "z*abc*z*"), false, 'Test 107');
test(isMatch("aaaabbbb", "a*b*b*"), true, 'Test 108');
test(isMatch("aabbcc", "a*b*b*c*c*"), true, 'Test 109');
test(isMatch("abc", "a*b*c*"), true, 'Test 110');
test(isMatch("abcdeabcdeabcde", "abc*de*abc*de*abc*de*"), true, 'Test 111');
test(isMatch("abcde", "a*c*e"), false, 'Test 112');
test(isMatch("xyzzaz", "x*y*.*z*"), true, 'Test 113');
test(isMatch("ababab", "[ab]*b"), false, 'Test 114');
test(isMatch("abcdef", "abc.def"), false, 'Test 115');
test(isMatch("xyx", "x*y*x*"), true, 'Test 116');
test(isMatch("aaaaaa", "a*a*a*a*"), true, 'Test 117');
test(isMatch("abbb", "ab*"), true, 'Test 118');
test(isMatch("a", "."), true, 'Test 119');
test(isMatch("abcdexyz", "abc.*xyz"), true, 'Test 120');
test(isMatch("aabbcc", "a*b*c*"), true, 'Test 121');
test(isMatch("leetcode", "le.*e.*tcode"), true, 'Test 122');
test(isMatch("aaa", "ab*a*c*a"), true, 'Test 123');
test(isMatch("abcd", "a.d"), false, 'Test 124');
test(isMatch("xylophone", "x.l*o.h.p*ne"), true, 'Test 125');
test(isMatch("abcde", ".*"), true, 'Test 126');
test(isMatch("abxyzbcd", "ab.*bc*d"), true, 'Test 127');
test(isMatch("zzzzz", "z*"), true, 'Test 128');
test(isMatch("aaa", "a*a*"), true, 'Test 129');
test(isMatch("aaaaaaab", "a*a*a*a*a*a*a*b"), true, 'Test 130');
test(isMatch("hello world", "h.*o w*r*d"), false, 'Test 131');
test(isMatch("abcdefgh", "a.*b.*c.*d.*e.*f.*g.*h"), true, 'Test 132');
test(isMatch("hello", "h.l.o"), true, 'Test 133');
test(isMatch("abcd", "a.b*c.d"), false, 'Test 134');
test(isMatch("abcdefgh", "abcdefgh."), false, 'Test 135');
test(isMatch("a", "ab*a"), false, 'Test 136');
test(isMatch("patternmatching", "pat*tern*m*atching*"), true, 'Test 137');
test(isMatch("abcabcabc", "[abc]*"), false, 'Test 138');
test(isMatch("ababab", "[ab]*ab*"), false, 'Test 139');
test(isMatch("abcd", "a.c*d*"), true, 'Test 140');
test(isMatch("a", ".*"), true, 'Test 141');
test(isMatch("abcdef", "abcd.e*f"), true, 'Test 142');
test(isMatch("aabb", "a*bb"), true, 'Test 143');
test(isMatch("abcdefgh", "abcdefgh*"), true, 'Test 144');
test(isMatch("aaa", "a*a*a*a*a*a*"), true, 'Test 145');
test(isMatch("aaaaaa", "a*a*a*a*a*a*"), true, 'Test 146');
test(isMatch("abab", "[ab]*"), false, 'Test 147');
test(isMatch("mississippi", "mi*s*is*ip*pi*s*"), true, 'Test 148');
test(isMatch("aaaaab", "a*ba*"), true, 'Test 149');
test(isMatch("abc", ".b."), true, 'Test 150');
test(isMatch("abcd", "a*b.c*d*"), true, 'Test 151');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

