// Test: 1948. Delete Duplicate Folders In System
// 76 test cases from LeetCodeDataset
// Run: node test.js

const { deleteDuplicateFolder } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1948. Delete Duplicate Folders In System\n");

test(deleteDuplicateFolder([["project"],["project","src"],["project","src","main"],["project","src","test"],["project","docs"],["project","docs","api"],["project","docs","user"]]), [['project', 'docs', 'api'], ['project', 'docs', 'user'], ['project', 'docs'], ['project', 'src', 'main'], ['project', 'src', 'test'], ['project', 'src'], ['project']], 'Test 1');
test(deleteDuplicateFolder([["x"],["x","y"],["x","z"],["y"],["y","x"],["z"],["z","x"]]), [['x', 'y'], ['x', 'z'], ['x']], 'Test 2');
test(deleteDuplicateFolder([["a","b"],["c","d"],["c"],["a"]]), [['a', 'b'], ['a'], ['c', 'd'], ['c']], 'Test 3');
test(deleteDuplicateFolder([["home"],["home","user"],["home","user","documents"],["home","guest"],["home","guest","documents"]]), [['home']], 'Test 4');
test(deleteDuplicateFolder([["a"],["a","b"],["a","b","c"],["a","b","c","d"],["a","b","c","d","e"],["f"],["f","g"],["f","g","h"],["f","g","h","i"],["f","g","h","i","j"]]), [['a', 'b', 'c', 'd', 'e'], ['a', 'b', 'c', 'd'], ['a', 'b', 'c'], ['a', 'b'], ['a'], ['f', 'g', 'h', 'i', 'j'], ['f', 'g', 'h', 'i'], ['f', 'g', 'h'], ['f', 'g'], ['f']], 'Test 5');
test(deleteDuplicateFolder([["root"],["root","a"],["root","b"],["root","a","x"],["root","b","x"],["root","a","x","y"],["root","b","x","y"]]), [['root']], 'Test 6');
test(deleteDuplicateFolder([["folder1"],["folder1","sub1"],["folder1","sub2"],["folder2"],["folder2","sub1"],["folder2","sub2"]]), [], 'Test 7');
test(deleteDuplicateFolder([["a"],["c"],["a","b"],["c","b"],["a","b","x"],["a","b","x","y"],["w"],["w","y"]]), [['a', 'b'], ['a'], ['c', 'b'], ['c']], 'Test 8');
test(deleteDuplicateFolder([["x"],["x","y"],["x","y","z"],["x","y","z","w"],["u"],["u","v"],["u","v","w"]]), [['u'], ['x', 'y'], ['x']], 'Test 9');
test(deleteDuplicateFolder([["m"],["m","n"],["n"],["n","m"],["m","n","o"],["n","m","o"]]), [['m'], ['n']], 'Test 10');
test(deleteDuplicateFolder([["root"],["root","folder1"],["root","folder2"],["root","folder1","subfolder1"],["root","folder2","subfolder1"]]), [['root']], 'Test 11');
test(deleteDuplicateFolder([["m"],["m","n"],["p"],["p","n"]]), [], 'Test 12');
test(deleteDuplicateFolder([["a"],["c"],["d"],["a","b"],["c","b"],["d","a"]]), [['d', 'a'], ['d']], 'Test 13');
test(deleteDuplicateFolder([["x"],["x","y"],["x","y","z"],["y"],["y","z"]]), [['x']], 'Test 14');
test(deleteDuplicateFolder([["one"],["one","two"],["one","two","three"],["two"],["two","three"]]), [['one']], 'Test 15');
test(deleteDuplicateFolder([["p"],["p","q"],["p","q","r"],["p","q","r","s"],["p","q","r","t"],["q"],["q","r"],["q","r","s"],["q","r","t"],["r"],["r","s"],["r","t"],["s"],["t"],["u"],["u","v"],["u","v","w"],["u","v","w","x"],["u","v","w","y"],["v"],["v","w"],["v","w","x"],["v","w","y"],["w"],["w","x"],["w","y"],["x"],["y"]]), [['p'], ['s'], ['t'], ['u'], ['x'], ['y']], 'Test 16');
test(deleteDuplicateFolder([["level1","level2","level3","level4"],["level1","level2","level5","level4"],["level1","level6","level3","level4"],["level1","level6","level5","level4"],["level1","level7","level8"],["level1","level9","level10","level11"],["level1","level9","level10","level12"]]), [['level1', 'level7', 'level8'], ['level1', 'level7'], ['level1', 'level9', 'level10', 'level11'], ['level1', 'level9', 'level10', 'level12'], ['level1', 'level9', 'level10'], ['level1', 'level9'], ['level1']], 'Test 17');
test(deleteDuplicateFolder([["system","folderA"],["system","folderB"],["system","folderA","subfolderA1"],["system","folderB","subfolderA1"],["system","folderA","subfolderA2"],["system","folderB","subfolderA2"],["system","folderA","subfolderA1","subsubfolderA1"],["system","folderB","subfolderA1","subsubfolderA1"],["system","folderA","subfolderA1","subsubfolderA2"],["system","folderB","subfolderA1","subsubfolderA2"],["system","folderA","subfolderA2","subsubfolderA1"],["system","folderB","subfolderA2","subsubfolderA1"],["system","folderA","subfolderA2","subsubfolderA2"],["system","folderB","subfolderA2","subsubfolderA2"]]), [['system']], 'Test 18');
test(deleteDuplicateFolder([["home","user","docs"],["home","user","photos"],["home","guest","docs"],["home","guest","photos"],["home","user","docs","file1"],["home","guest","docs","file1"],["home","user","photos","image1"],["home","guest","photos","image1"],["home","user","docs","file2"],["home","guest","docs","file2"]]), [['home']], 'Test 19');
test(deleteDuplicateFolder([["projects","proj1"],["projects","proj2"],["projects","proj1","src"],["projects","proj2","src"],["projects","proj1","src","main"],["projects","proj2","src","main"],["projects","proj1","src","test"],["projects","proj2","src","test"],["projects","proj1","src","main","file1"],["projects","proj2","src","main","file1"],["projects","proj1","src","test","test1"],["projects","proj2","src","test","test1"]]), [['projects']], 'Test 20');
test(deleteDuplicateFolder([["alpha"],["alpha","beta"],["alpha","beta","gamma"],["alpha","beta","delta"],["alpha","epsilon"],["alpha","epsilon","gamma"],["alpha","epsilon","delta"],["beta"],["beta","gamma"],["beta","delta"],["epsilon"],["epsilon","gamma"],["epsilon","delta"],["gamma"],["delta"],["charlie"],["charlie","foxtrot"],["charlie","foxtrot","gamma"],["charlie","foxtrot","delta"],["charlie","tango"],["charlie","tango","gamma"],["charlie","tango","delta"]]), [['alpha'], ['charlie'], ['delta'], ['gamma']], 'Test 21');
test(deleteDuplicateFolder([["project"],["project","src"],["project","docs"],["project","src","main"],["project","src","test"],["project","docs","api"],["project","docs","userguide"],["project","src","main","java"],["project","src","test","java"],["project","docs","api","java"],["project","docs","userguide","java"],["project","src","main","java","utils"],["project","src","test","java","utils"],["project","docs","api","java","utils"],["project","docs","userguide","java","utils"]]), [['project', 'docs'], ['project', 'src'], ['project']], 'Test 22');
test(deleteDuplicateFolder([["data","archive"],["data","archive","2021"],["data","archive","2022"],["data","archive","2023"],["data","backup"],["data","backup","2021"],["data","backup","2022"],["data","backup","2023"],["data","logs"],["data","logs","server1"],["data","logs","server2"],["data","logs","server3"],["data","temp"],["data","temp","server1"],["data","temp","server2"],["data","temp","server3"]]), [['data']], 'Test 23');
test(deleteDuplicateFolder([["app"],["app","module1"],["app","module2"],["app","module1","component1"],["app","module2","component1"],["app","module1","component2"],["app","module2","component2"],["app","module1","component1","subcomponent1"],["app","module2","component1","subcomponent1"],["app","module1","component2","subcomponent1"],["app","module2","component2","subcomponent1"],["app","module1","component1","subcomponent2"],["app","module2","component1","subcomponent2"],["app","module1","component2","subcomponent2"],["app","module2","component2","subcomponent2"],["app","module1","component1","subcomponent2","deep1"],["app","module2","component1","subcomponent2","deep1"]]), [['app']], 'Test 24');
test(deleteDuplicateFolder([["root","a"],["root","b"],["root","a","c"],["root","b","c"],["root","a","d"],["root","b","d"],["root","a","c","e"],["root","b","c","e"]]), [['root']], 'Test 25');
test(deleteDuplicateFolder([["root","folder1"],["root","folder2"],["root","folder1","subfolder1"],["root","folder2","subfolder1"],["root","folder1","subfolder1","subsubfolder1"],["root","folder2","subfolder1","subsubfolder1"],["root","unique","folder1"],["root","unique","folder1","subfolder1"],["root","unique","folder1","subfolder1","subsubfolder1"]]), [['root', 'unique'], ['root']], 'Test 26');
test(deleteDuplicateFolder([["home"],["home","user1"],["home","user2"],["home","user1","files"],["home","user2","files"],["home","user1","files","docs"],["home","user2","files","docs"],["home","user1","files","docs","report1"],["home","user2","files","docs","report1"],["home","user1","files","docs","report2"],["home","user2","files","docs","report2"]]), [['home']], 'Test 27');
test(deleteDuplicateFolder([["x"],["y"],["z"],["x","a"],["y","a"],["z","a"],["x","a","b"],["y","a","b"],["z","a","b"],["x","a","b","c"],["y","a","b","c"],["z","a","b","c"],["x","d"],["y","e"],["z","f"]]), [['x', 'd'], ['x'], ['y', 'e'], ['y'], ['z', 'f'], ['z']], 'Test 28');
test(deleteDuplicateFolder([["root","a","b","c","d"],["root","x","y","z","w"],["root","a","b","c","d","e"],["root","x","y","z","w","v"],["root","a","b","f"],["root","x","y","f"],["root","a","g"],["root","x","g"],["root","a","h"],["root","x","h"],["root","a","i","j"],["root","x","i","j"],["root","a","i","k"],["root","x","i","k"]]), [['root', 'a', 'b', 'c', 'd', 'e'], ['root', 'a', 'b', 'c', 'd'], ['root', 'a', 'b', 'c'], ['root', 'a', 'b', 'f'], ['root', 'a', 'b'], ['root', 'a', 'g'], ['root', 'a', 'h'], ['root', 'a'], ['root', 'x', 'g'], ['root', 'x', 'h'], ['root', 'x', 'y', 'f'], ['root', 'x', 'y', 'z', 'w', 'v'], ['root', 'x', 'y', 'z', 'w'], ['root', 'x', 'y', 'z'], ['root', 'x', 'y'], ['root', 'x'], ['root']], 'Test 29');
test(deleteDuplicateFolder([["root"],["root","folder1"],["root","folder2"],["root","folder1","sub1"],["root","folder2","sub1"],["root","folder1","sub1","subsub1"],["root","folder2","sub1","subsub1"]]), [['root']], 'Test 30');
test(deleteDuplicateFolder([["base"],["base","folder1"],["base","folder1","subfolder1"],["base","folder1","subfolder2"],["base","folder2"],["base","folder2","subfolder1"],["base","folder2","subfolder2"],["base","folder3"],["base","folder3","subfolder1"],["base","folder3","subfolder2"],["base","folder1","subfolder1","deep1"],["base","folder2","subfolder1","deep1"],["base","folder3","subfolder1","deep1"]]), [['base']], 'Test 31');
test(deleteDuplicateFolder([["system"],["system","app1"],["system","app1","data"],["system","app2"],["system","app2","data"],["system","app3"],["system","app3","data"],["system","app3","logs"],["system","app4"],["system","app4","data"],["system","app4","logs"],["system","app4","temp"],["system","app5"],["system","app5","data"],["system","app5","logs"],["system","app5","temp"],["system","app6"],["system","app6","data"],["system","app6","logs"],["system","app6","temp"],["system","app6","config"],["system","app7"],["system","app7","data"],["system","app7","logs"],["system","app7","temp"],["system","app7","config"],["system","app8"],["system","app8","data"],["system","app8","logs"],["system","app8","temp"],["system","app8","config"],["system","app8","bin"]]), [['system', 'app3', 'data'], ['system', 'app3', 'logs'], ['system', 'app3'], ['system', 'app8', 'bin'], ['system', 'app8', 'config'], ['system', 'app8', 'data'], ['system', 'app8', 'logs'], ['system', 'app8', 'temp'], ['system', 'app8'], ['system']], 'Test 32');
test(deleteDuplicateFolder([["root","x"],["root","y"],["root","x","z"],["root","y","z"],["root","x","a"],["root","y","a"],["root","x","a","b"],["root","y","a","b"]]), [['root']], 'Test 33');
test(deleteDuplicateFolder([["root","level1","level2","level3"],["root","level1","level2","level4"],["root","level5","level6"],["root","level1","level2","level3","level7"],["root","level5","level6","level7"],["root","level1","level2","level3","level7","level8"],["root","level5","level6","level7","level8"]]), [['root', 'level1', 'level2', 'level4'], ['root', 'level1', 'level2'], ['root', 'level1'], ['root', 'level5'], ['root']], 'Test 34');
test(deleteDuplicateFolder([["data"],["data","backup"],["data","backup","2021"],["data","backup","2022"],["data","backup","2021","month1"],["data","backup","2022","month1"],["data","backup","2021","month2"],["data","backup","2022","month2"],["data","backup","2021","month1","day1"],["data","backup","2022","month1","day1"],["data","backup","2021","month1","day2"],["data","backup","2022","month1","day2"],["data","backup","2021","month2","day1"],["data","backup","2022","month2","day1"],["data","backup","2021","month2","day2"],["data","backup","2022","month2","day2"],["data","backup","2021","month1","day1","file1"],["data","backup","2022","month1","day1","file1"],["data","backup","2021","month1","day2","file1"],["data","backup","2022","month1","day2","file1"],["data","backup","2021","month2","day1","file1"],["data","backup","2022","month2","day1","file1"],["data","backup","2021","month2","day2","file1"],["data","backup","2022","month2","day2","file1"]]), [['data', 'backup'], ['data']], 'Test 35');
test(deleteDuplicateFolder([["root","dir1","subdir1"],["root","dir1","subdir2"],["root","dir2","subdir1"],["root","dir2","subdir3"],["root","dir3","subdir2"],["root","dir3","subdir4"]]), [['root', 'dir1', 'subdir1'], ['root', 'dir1', 'subdir2'], ['root', 'dir1'], ['root', 'dir2', 'subdir1'], ['root', 'dir2', 'subdir3'], ['root', 'dir2'], ['root', 'dir3', 'subdir2'], ['root', 'dir3', 'subdir4'], ['root', 'dir3'], ['root']], 'Test 36');
test(deleteDuplicateFolder([["x"],["x","y"],["x","y","z"],["x","y","w"],["y"],["y","z"],["y","w"],["a"],["a","b"],["a","b","c"],["b"],["b","c"],["b","d"],["c"],["c","d"],["d"]]), [['a', 'b', 'c'], ['a', 'b'], ['a'], ['b', 'c'], ['b', 'd'], ['b'], ['c', 'd'], ['c'], ['d'], ['x']], 'Test 37');
test(deleteDuplicateFolder([["base","level1","level2","level3"],["other","level1","level2","level3"],["base","level1","level2","level3","level4"],["other","level1","level2","level3","level4"],["base","level1","level2","level3","level4","level5"],["other","level1","level2","level3","level4","level5"],["base","level1","level2","other"],["other","level1","level2","other"]]), [], 'Test 38');
test(deleteDuplicateFolder([["home","user1","documents"],["home","user2","documents"],["home","user1","documents","file1"],["home","user2","documents","file1"],["home","user1","pictures"],["home","user2","pictures"],["home","user1","pictures","photo1"],["home","user2","pictures","photo1"]]), [['home']], 'Test 39');
test(deleteDuplicateFolder([["nested","folder1"],["nested","folder2"],["nested","folder1","subfolder1"],["nested","folder2","subfolder1"],["nested","folder1","subfolder1","subsubfolder1"],["nested","folder2","subfolder1","subsubfolder1"],["nested","folder1","subfolder2"],["nested","folder2","subfolder2"],["nested","folder1","subfolder2","subsubfolder2"],["nested","folder2","subfolder2","subsubfolder2"],["nested","folder1","subfolder2","subsubfolder2","file1"],["nested","folder2","subfolder2","subsubfolder2","file1"]]), [['nested']], 'Test 40');
test(deleteDuplicateFolder([["a","b","c","d","e"],["f","g","h"],["a","b","c","d","f"],["f","g","h","i"],["a","b","c","d","j"],["j","k"],["f","g","h","i","k"]]), [['a', 'b', 'c', 'd', 'e'], ['a', 'b', 'c', 'd', 'f'], ['a', 'b', 'c', 'd', 'j'], ['a', 'b', 'c', 'd'], ['a', 'b', 'c'], ['a', 'b'], ['a'], ['f', 'g', 'h'], ['f', 'g'], ['f']], 'Test 41');
test(deleteDuplicateFolder([["root","a","b","c"],["root","x","y","z"],["root","a","b","d"],["root","x","y","d"],["root","a","b","c","e"],["root","x","y","z","e"],["root","a","b","c","f"],["root","x","y","z","f"],["root","a","g"],["root","x","g"],["root","a","h"],["root","x","h"]]), [['root', 'a', 'b', 'd'], ['root', 'a', 'b'], ['root', 'a', 'g'], ['root', 'a', 'h'], ['root', 'a'], ['root', 'x', 'g'], ['root', 'x', 'h'], ['root', 'x', 'y', 'd'], ['root', 'x', 'y'], ['root', 'x'], ['root']], 'Test 42');
test(deleteDuplicateFolder([["library","books","genre1"],["library","books","genre2"],["library","books","genre3"],["library","books","genre1","author1"],["library","books","genre3","author1"],["library","books","genre2","author2"],["library","books","genre3","author2"],["library","books","genre1","author1","book1"],["library","books","genre3","author1","book1"]]), [['library', 'books', 'genre1'], ['library', 'books', 'genre2', 'author2'], ['library', 'books', 'genre2'], ['library', 'books', 'genre3', 'author2'], ['library', 'books', 'genre3'], ['library', 'books'], ['library']], 'Test 43');
test(deleteDuplicateFolder([["a"],["a","b"],["a","b","c"],["a","b","c","d"],["a","b","c","d","e"],["b"],["b","c"],["b","c","d"],["b","c","d","e"],["c"],["c","d"],["c","d","e"],["d"],["d","e"],["e"]]), [['a'], ['e']], 'Test 44');
test(deleteDuplicateFolder([["folder1"],["folder1","folder2"],["folder1","folder2","folder3"],["folder1","folder2","folder3","folder4"],["folder1","folder2","folder3","folder5"],["folder1","folder2","folder6"],["folder1","folder2","folder6","folder7"],["folder1","folder2","folder6","folder8"],["folder1","folder9"],["folder1","folder9","folder10"],["folder1","folder9","folder10","folder11"],["folder1","folder9","folder10","folder12"],["folder1","folder9","folder13"],["folder1","folder9","folder13","folder14"],["folder1","folder9","folder13","folder15"]]), [['folder1', 'folder2', 'folder3', 'folder4'], ['folder1', 'folder2', 'folder3', 'folder5'], ['folder1', 'folder2', 'folder3'], ['folder1', 'folder2', 'folder6', 'folder7'], ['folder1', 'folder2', 'folder6', 'folder8'], ['folder1', 'folder2', 'folder6'], ['folder1', 'folder2'], ['folder1', 'folder9', 'folder10', 'folder11'], ['folder1', 'folder9', 'folder10', 'folder12'], ['folder1', 'folder9', 'folder10'], ['folder1', 'folder9', 'folder13', 'folder14'], ['folder1', 'folder9', 'folder13', 'folder15'], ['folder1', 'folder9', 'folder13'], ['folder1', 'folder9'], ['folder1']], 'Test 45');
test(deleteDuplicateFolder([["projects","projectA"],["projects","projectB"],["projects","projectA","src"],["projects","projectB","src"],["projects","projectA","src","module1"],["projects","projectB","src","module1"],["projects","projectA","src","module2"],["projects","projectB","src","module2"],["projects","projectA","src","module1","file1"],["projects","projectB","src","module1","file1"],["projects","projectA","src","module2","file2"],["projects","projectB","src","module2","file3"],["projects","projectA","src","module1","file4"],["projects","projectB","src","module1","file5"]]), [['projects', 'projectA', 'src', 'module1', 'file1'], ['projects', 'projectA', 'src', 'module1', 'file4'], ['projects', 'projectA', 'src', 'module1'], ['projects', 'projectA', 'src', 'module2', 'file2'], ['projects', 'projectA', 'src', 'module2'], ['projects', 'projectA', 'src'], ['projects', 'projectA'], ['projects', 'projectB', 'src', 'module1', 'file1'], ['projects', 'projectB', 'src', 'module1', 'file5'], ['projects', 'projectB', 'src', 'module1'], ['projects', 'projectB', 'src', 'module2', 'file3'], ['projects', 'projectB', 'src', 'module2'], ['projects', 'projectB', 'src'], ['projects', 'projectB'], ['projects']], 'Test 46');
test(deleteDuplicateFolder([["dir1"],["dir2"],["dir3"],["dir1","sub1"],["dir2","sub2"],["dir3","sub1"],["dir1","sub1","subsub1"],["dir2","sub2","subsub2"],["dir3","sub1","subsub1"],["dir1","sub1","subsub1","deeper1"],["dir3","sub1","subsub1","deeper1"]]), [['dir2', 'sub2', 'subsub2'], ['dir2', 'sub2'], ['dir2']], 'Test 47');
test(deleteDuplicateFolder([["a"],["a","b"],["a","b","c"],["a","b","d"],["b"],["b","c"],["b","d"],["c"],["c","a"],["c","a","b"],["d"],["d","a"],["d","a","b"]]), [['a']], 'Test 48');
test(deleteDuplicateFolder([["root","folder1","subfolder1","subsubfolder1"],["root","folder2","subfolder2","subsubfolder1"],["root","folder3","subfolder3"],["root","folder1","subfolder1"],["root","folder2","subfolder2"]]), [['root', 'folder1'], ['root', 'folder2'], ['root', 'folder3', 'subfolder3'], ['root', 'folder3'], ['root']], 'Test 49');
test(deleteDuplicateFolder([["folderA"],["folderB"],["folderA","subA"],["folderB","subA"],["folderA","subA","subsubA"],["folderB","subA","subsubA"],["folderC"],["folderC","subB"],["folderD"],["folderD","subB","subsubB"],["folderE"],["folderE","subB","subsubB","deepB"]]), [['folderC', 'subB'], ['folderC'], ['folderD', 'subB', 'subsubB'], ['folderD', 'subB'], ['folderD'], ['folderE', 'subB', 'subsubB', 'deepB'], ['folderE', 'subB', 'subsubB'], ['folderE', 'subB'], ['folderE']], 'Test 50');
test(deleteDuplicateFolder([["main"],["main","projects"],["main","projects","project1"],["main","projects","project2"],["main","projects","project1","code"],["main","projects","project2","code"],["main","docs"],["main","docs","project1"],["main","docs","project2"],["main","docs","project1","notes"],["main","docs","project2","notes"]]), [['main', 'docs'], ['main', 'projects'], ['main']], 'Test 51');
test(deleteDuplicateFolder([["folder1","subfolder1","deepsub1"],["folder2","subfolder2","deepsub2"],["folder1","subfolder1","deepsub3"],["folder2","subfolder2","deepsub3"],["folder1","subfolder2"],["folder2","subfolder2"],["folder3","subfolder3"]]), [['folder1', 'subfolder1', 'deepsub1'], ['folder1', 'subfolder1', 'deepsub3'], ['folder1', 'subfolder1'], ['folder1', 'subfolder2'], ['folder1'], ['folder2', 'subfolder2', 'deepsub2'], ['folder2', 'subfolder2', 'deepsub3'], ['folder2', 'subfolder2'], ['folder2'], ['folder3', 'subfolder3'], ['folder3']], 'Test 52');
test(deleteDuplicateFolder([["parent","child1","grandchild1"],["parent","child2","grandchild1"],["parent","child1","grandchild2"],["parent","child2","grandchild2"],["parent","child1","grandchild3"],["parent","child2","grandchild3"],["parent","child1","subchild1","subsubchild1"],["parent","child2","subchild1","subsubchild1"],["parent","child1","subchild2","subsubchild2"],["parent","child2","subchild2","subsubchild2"]]), [['parent']], 'Test 53');
test(deleteDuplicateFolder([["root","a","x"],["root","b","x"],["root","a","y"],["root","b","y"],["root","a","x","z"],["root","b","x","z"],["root","a","w"],["root","b","w"]]), [['root']], 'Test 54');
test(deleteDuplicateFolder([["a","b","c"],["a","d","e"],["a","d","e","f"],["g","h","i"],["g","j","k"],["g","j","l"],["a","b","c","m"],["g","h","i","m"],["n","o","p"],["n","o","q"],["n","r","s"],["n","r","s","t"]]), [['a', 'b'], ['a', 'd', 'e', 'f'], ['a', 'd', 'e'], ['a', 'd'], ['a'], ['g', 'h'], ['g', 'j', 'k'], ['g', 'j', 'l'], ['g', 'j'], ['g'], ['n', 'o', 'p'], ['n', 'o', 'q'], ['n', 'o'], ['n', 'r', 's', 't'], ['n', 'r', 's'], ['n', 'r'], ['n']], 'Test 55');
test(deleteDuplicateFolder([["x"],["x","y"],["x","y","z"],["x","y","z","w"],["y"],["y","z"],["y","z","w"],["z"],["z","w"],["w"]]), [['w'], ['x']], 'Test 56');
test(deleteDuplicateFolder([["main","branch1"],["main","branch2"],["main","branch1","sub1"],["main","branch2","sub1"],["main","branch1","sub2"],["main","branch2","sub2"],["main","branch1","sub1","subsub1"],["main","branch2","sub1","subsub1"],["main","branch1","sub1","subsub2"],["main","branch2","sub1","subsub2"]]), [['main']], 'Test 57');
test(deleteDuplicateFolder([["x"],["y"],["z"],["x","a"],["y","a"],["z","a"],["x","a","b"],["y","a","b"],["x","a","b","c"],["y","a","b","c"],["w"],["w","d"],["w","d","e"],["w","d","e","f"],["v"],["v","d"],["v","d","e"],["v","d","e","f"]]), [['z', 'a'], ['z']], 'Test 58');
test(deleteDuplicateFolder([["level1"],["level1","level2"],["level1","level2","level3"],["level1","level2","level3","level4"],["level1","level2","level3","level4","level5"],["levelA"],["levelA","level2"],["levelA","level2","level3"],["levelA","level2","level3","level4"],["levelA","level2","level3","level4","level5"]]), [], 'Test 59');
test(deleteDuplicateFolder([["root"],["root","dir1"],["root","dir1","subdir1"],["root","dir2"],["root","dir2","subdir1"],["root","dir2","subdir2"],["root","dir3"],["root","dir3","subdir2"],["root","dir4"],["root","dir4","subdir1"],["root","dir4","subdir2"]]), [['root', 'dir1', 'subdir1'], ['root', 'dir1'], ['root', 'dir3', 'subdir2'], ['root', 'dir3'], ['root']], 'Test 60');
test(deleteDuplicateFolder([["root","folder1","subfolder1"],["root","folder2","subfolder1"],["root","folder3","subfolder2"],["root","folder3","subfolder2","deepsubfolder1"],["root","folder4","subfolder2","deepsubfolder1"],["root","folder5","subfolder2","deepsubfolder1","deeper1"]]), [['root', 'folder5', 'subfolder2', 'deepsubfolder1', 'deeper1'], ['root', 'folder5', 'subfolder2', 'deepsubfolder1'], ['root', 'folder5', 'subfolder2'], ['root', 'folder5'], ['root']], 'Test 61');
test(deleteDuplicateFolder([["home","user1","docs"],["home","user2","docs"],["home","user1","music"],["home","user2","music"],["home","user1","docs","report"],["home","user2","docs","report"],["home","user1","music","song1"],["home","user2","music","song2"],["home","user1","docs","report","summary"],["home","user2","docs","report","summary"],["home","user1","docs","report","summary","details"],["home","user2","docs","report","summary","details"]]), [['home', 'user1', 'music', 'song1'], ['home', 'user1', 'music'], ['home', 'user1'], ['home', 'user2', 'music', 'song2'], ['home', 'user2', 'music'], ['home', 'user2'], ['home']], 'Test 62');
test(deleteDuplicateFolder([["main","project","src","module1"],["main","project","src","module2"],["main","project","src","module1","submodule1"],["main","project","src","module2","submodule1"],["main","project","src","module1","submodule2"],["main","project","src","module2","submodule2"],["main","project","src","module1","submodule1","subsubmodule1"],["main","project","src","module2","submodule1","subsubmodule1"],["main","unique","project","src","module1"],["main","unique","project","src","module1","submodule1"],["main","unique","project","src","module1","submodule1","subsubmodule1"]]), [['main', 'project', 'src'], ['main', 'project'], ['main', 'unique', 'project', 'src', 'module1'], ['main', 'unique', 'project', 'src'], ['main', 'unique', 'project'], ['main', 'unique'], ['main']], 'Test 63');
test(deleteDuplicateFolder([["projects","proj1","src"],["projects","proj2","src"],["projects","proj3"],["projects","proj1","src","main"],["projects","proj2","src","main"],["projects","proj1","docs"],["projects","proj2","docs"],["projects","proj3","docs"]]), [['projects', 'proj3', 'docs'], ['projects', 'proj3'], ['projects']], 'Test 64');
test(deleteDuplicateFolder([["alpha"],["beta"],["gamma"],["alpha","delta"],["beta","delta"],["gamma","epsilon"],["alpha","delta","zeta"],["beta","delta","zeta"],["alpha","delta","zeta","eta"],["beta","delta","zeta","eta"],["alpha","theta"],["beta","theta"],["gamma","theta"]]), [['gamma', 'epsilon'], ['gamma', 'theta'], ['gamma']], 'Test 65');
test(deleteDuplicateFolder([["project"],["project","module1"],["project","module1","file1"],["project","module2"],["project","module2","file1"],["project","module3"],["project","module3","file2"],["project","module4"],["project","module4","file3"],["project","module5"],["project","module5","file3"],["project","module6"],["project","module6","file4"],["project","module7"],["project","module7","file4"],["project","module8"],["project","module8","file5"],["project","module8","file6"]]), [['project', 'module3', 'file2'], ['project', 'module3'], ['project', 'module8', 'file5'], ['project', 'module8', 'file6'], ['project', 'module8'], ['project']], 'Test 66');
test(deleteDuplicateFolder([["app","module1","service1"],["app","module2","service2"],["app","module3","service1"],["app","module4","service4"],["app","module1","service1","endpoint1"],["app","module3","service1","endpoint1"],["app","module5"],["app","module5","endpoint2"]]), [['app', 'module2', 'service2'], ['app', 'module2'], ['app', 'module4', 'service4'], ['app', 'module4'], ['app', 'module5', 'endpoint2'], ['app', 'module5'], ['app']], 'Test 67');
test(deleteDuplicateFolder([["root","dir1","subdir1"],["root","dir2","subdir1"],["root","dir1","subdir2"],["root","dir2","subdir2"],["root","dir1","subdir1","subsubdir1"],["root","dir2","subdir1","subsubdir1"],["root","dir1","subdir3"],["root","dir2","subdir3"]]), [['root']], 'Test 68');
test(deleteDuplicateFolder([["root"],["root","child1"],["root","child2"],["root","child1","sub1"],["root","child2","sub1"],["root","child1","sub1","subsub1"],["root","child2","sub1","subsub1"],["root","child1","sub2"],["root","child2","sub2"],["root","child1","sub2","subsub2"],["root","child2","sub2","subsub2"],["root","child3"],["root","child3","sub1"],["root","child3","sub1","subsub1"],["root","child3","sub2"],["root","child3","sub2","subsub2"]]), [['root']], 'Test 69');
test(deleteDuplicateFolder([["home"],["home","user1"],["home","user1","documents"],["home","user1","pictures"],["home","user2"],["home","user2","documents"],["home","user2","pictures"],["home","user3"],["home","user3","documents"],["home","user3","pictures"],["home","user3","videos"],["home","user4"],["home","user4","documents"],["home","user4","pictures"],["home","user4","videos"],["home","user5"],["home","user5","documents"],["home","user5","pictures"],["home","user5","videos"],["home","user6"],["home","user6","documents"],["home","user6","pictures"],["home","user6","videos"],["home","user6","music"]]), [['home', 'user6', 'documents'], ['home', 'user6', 'music'], ['home', 'user6', 'pictures'], ['home', 'user6', 'videos'], ['home', 'user6'], ['home']], 'Test 70');
test(deleteDuplicateFolder([["documents","work","reports"],["documents","work","reports","monthly"],["documents","work","reports","monthly","jan"],["documents","work","reports","monthly","feb"],["documents","work","reports","monthly","mar"],["documents","home","reports"],["documents","home","reports","monthly"],["documents","home","reports","monthly","jan"],["documents","home","reports","monthly","feb"],["documents","home","reports","monthly","mar"],["documents","finance","reports"],["documents","finance","reports","monthly"],["documents","finance","reports","monthly","jan"],["documents","finance","reports","monthly","feb"],["documents","finance","reports","monthly","mar"]]), [['documents']], 'Test 71');
test(deleteDuplicateFolder([["root","folder1","sub1"],["root","folder2","sub1"],["root","folder1","sub2"],["root","folder2","sub2"],["root","folder3","sub1"],["root","folder4","sub1"],["root","folder3","sub3"],["root","folder4","sub3"]]), [['root']], 'Test 72');
test(deleteDuplicateFolder([["home","user1","docs","work"],["home","user2","docs","work"],["home","user1","docs","projects"],["home","user2","docs","projects"],["home","user1","downloads","movies"],["home","user2","downloads","movies"],["home","user1","downloads","music"],["home","user2","downloads","music"],["home","user1","pictures","vacation"],["home","user2","pictures","vacation"],["home","user1","pictures","wedding"],["home","user2","pictures","wedding"]]), [['home']], 'Test 73');
test(deleteDuplicateFolder([["library"],["library","section1"],["library","section1","shelf1"],["library","section1","shelf2"],["library","section1","shelf3"],["library","section2"],["library","section2","shelf1"],["library","section2","shelf2"],["library","section2","shelf4"],["library","section3"],["library","section3","shelf3"],["library","section3","shelf4"],["library","section4"],["library","section4","shelf5"],["library","section4","shelf6"],["library","section5"],["library","section5","shelf5"],["library","section5","shelf6"],["library","section6"],["library","section6","shelf7"],["library","section6","shelf8"],["library","section7"],["library","section7","shelf9"],["library","section7","shelf10"]]), [['library', 'section1', 'shelf1'], ['library', 'section1', 'shelf2'], ['library', 'section1', 'shelf3'], ['library', 'section1'], ['library', 'section2', 'shelf1'], ['library', 'section2', 'shelf2'], ['library', 'section2', 'shelf4'], ['library', 'section2'], ['library', 'section3', 'shelf3'], ['library', 'section3', 'shelf4'], ['library', 'section3'], ['library', 'section6', 'shelf7'], ['library', 'section6', 'shelf8'], ['library', 'section6'], ['library', 'section7', 'shelf10'], ['library', 'section7', 'shelf9'], ['library', 'section7'], ['library']], 'Test 74');
test(deleteDuplicateFolder([["home"],["home","user1"],["home","user2"],["home","user1","documents"],["home","user2","documents"],["home","user1","pictures"],["home","user2","pictures"],["home","user1","documents","work"],["home","user2","documents","work"],["home","user1","documents","personal"],["home","user2","documents","personal"],["home","user1","pictures","vacation"],["home","user2","pictures","vacation"],["home","user1","pictures","travel"],["home","user2","pictures","travel"],["home","user1","pictures","travel","2022"],["home","user2","pictures","travel","2022"]]), [['home']], 'Test 75');
test(deleteDuplicateFolder([["root"],["root","dir1"],["root","dir2"],["root","dir1","dir3"],["root","dir2","dir4"],["root","dir2","dir3"],["root","dir1","dir3","dir5"],["root","dir2","dir3","dir5"]]), [['root', 'dir1'], ['root', 'dir2', 'dir4'], ['root', 'dir2'], ['root']], 'Test 76');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

// Auto-mark DONE when all tests pass
if (!failed) {
  const path = require("path");
  const fs = require("fs");
  const dir = __dirname;
  const folder = path.basename(dir);
  if (!folder.startsWith("DONE-")) {
    const parent = path.dirname(dir);
    const newDir = path.join(parent, "DONE-" + folder);
    fs.renameSync(dir, newDir);
    const readme = path.join(newDir, "README.md");
    if (fs.existsSync(readme)) {
      let c = fs.readFileSync(readme, "utf-8");
      if (!c.includes("<!-- SOLVED -->")) {
        c = c.replace(/^(# .+)$/m, "$1 ✅\n<!-- SOLVED -->");
        fs.writeFileSync(readme, c);
      }
    }
    console.log("✅ DONE → " + "DONE-" + folder);
  }
}
