// Test: 551. Student Attendance Record I
// 181 test cases from LeetCodeDataset
// Run: node test.js

const { checkRecord } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n551. Student Attendance Record I\n");

test(checkRecord("AALL"), false, 'Test 1');
test(checkRecord("LLA"), true, 'Test 2');
test(checkRecord("PPALLPLL"), true, 'Test 3');
test(checkRecord("PLPLPL"), true, 'Test 4');
test(checkRecord("PA"), true, 'Test 5');
test(checkRecord("LLLLL"), false, 'Test 6');
test(checkRecord("LPPALLP"), true, 'Test 7');
test(checkRecord("PPALLP"), true, 'Test 8');
test(checkRecord("PPALLL"), false, 'Test 9');
test(checkRecord("ALPALP"), false, 'Test 10');
test(checkRecord("LLLP"), false, 'Test 11');
test(checkRecord("ALP"), true, 'Test 12');
test(checkRecord("AA"), false, 'Test 13');
test(checkRecord("PLLPLL"), true, 'Test 14');
test(checkRecord("PPPLLL"), false, 'Test 15');
test(checkRecord("LLL"), false, 'Test 16');
test(checkRecord("ALLL"), false, 'Test 17');
test(checkRecord("AAA"), false, 'Test 18');
test(checkRecord("A"), true, 'Test 19');
test(checkRecord("PPPPPPP"), true, 'Test 20');
test(checkRecord("LL"), true, 'Test 21');
test(checkRecord("ALPLL"), true, 'Test 22');
test(checkRecord("PPPPPP"), true, 'Test 23');
test(checkRecord("AALLPPP"), false, 'Test 24');
test(checkRecord("AALPLL"), false, 'Test 25');
test(checkRecord("PL"), true, 'Test 26');
test(checkRecord("PLLPLP"), true, 'Test 27');
test(checkRecord("PPALLAP"), false, 'Test 28');
test(checkRecord("ALLAPL"), false, 'Test 29');
test(checkRecord("PPALLAPA"), false, 'Test 30');
test(checkRecord("PPA"), true, 'Test 31');
test(checkRecord("AAAA"), false, 'Test 32');
test(checkRecord("AP"), true, 'Test 33');
test(checkRecord("APLLAA"), false, 'Test 34');
test(checkRecord("L"), true, 'Test 35');
test(checkRecord("PPLLP"), true, 'Test 36');
test(checkRecord("PPAALP"), false, 'Test 37');
test(checkRecord("P"), true, 'Test 38');
test(checkRecord("PPPP"), true, 'Test 39');
test(checkRecord("APLPALPPAL"), false, 'Test 40');
test(checkRecord("PPALLAPLPP"), false, 'Test 41');
test(checkRecord("AAPAAPA"), false, 'Test 42');
test(checkRecord("PPPPLLLPPP"), false, 'Test 43');
test(checkRecord("APLLPPPPPPPLL"), true, 'Test 44');
test(checkRecord("ALLPPAAPLPLP"), false, 'Test 45');
test(checkRecord("PLLLPLPLLPLLPPP"), false, 'Test 46');
test(checkRecord("APLPLPALPLPALPPPP"), false, 'Test 47');
test(checkRecord("AALLPPAPLALLPP"), false, 'Test 48');
test(checkRecord("APLLLLP"), false, 'Test 49');
test(checkRecord("APLPLPALPLPALPP"), false, 'Test 50');
test(checkRecord("LLLLPPPAPPLPPP"), false, 'Test 51');
test(checkRecord("ALALALAL"), false, 'Test 52');
test(checkRecord("APALLPAPL"), false, 'Test 53');
test(checkRecord("PPPPPPPPPPPP"), true, 'Test 54');
test(checkRecord("AAPALLPPALL"), false, 'Test 55');
test(checkRecord("PPPLLLLPP"), false, 'Test 56');
test(checkRecord("ALPPALP"), false, 'Test 57');
test(checkRecord("PPLPPPLLPPA"), true, 'Test 58');
test(checkRecord("PLLPLLPLLPLLPLLPLLPLL"), true, 'Test 59');
test(checkRecord("ALPLLPLLPLLPLLPLLPLLPLLPLL"), true, 'Test 60');
test(checkRecord("LPLPLPLPLPLPLP"), true, 'Test 61');
test(checkRecord("PPLPPPLPPLLPPP"), true, 'Test 62');
test(checkRecord("LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLP"), false, 'Test 63');
test(checkRecord("AALPLPLLPLL"), false, 'Test 64');
test(checkRecord("PLPPPLPPPL"), true, 'Test 65');
test(checkRecord("PPLPPLPLL"), true, 'Test 66');
test(checkRecord("PPPPPPLPPPP"), true, 'Test 67');
test(checkRecord("PPALLPALPPALLP"), false, 'Test 68');
test(checkRecord("LPLLPLLPLLPLLPLLPLLPLLPLL"), true, 'Test 69');
test(checkRecord("PPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPPLPPP"), true, 'Test 70');
test(checkRecord("PLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLLPLP"), true, 'Test 71');
test(checkRecord("PPALPPALPP"), false, 'Test 72');
test(checkRecord("PLPLPLPLPLPL"), true, 'Test 73');
test(checkRecord("PLAPLLPLPAL"), false, 'Test 74');
test(checkRecord("LLPALPALPALP"), false, 'Test 75');
test(checkRecord("LLLLLPLPPPPP"), false, 'Test 76');
test(checkRecord("AAPAPAPAPAPAPAPAPAPAPAPAPAPAPAPAPAPA"), false, 'Test 77');
test(checkRecord("APLALPALPALP"), false, 'Test 78');
test(checkRecord("PLLPPLPLLPLLPPP"), true, 'Test 79');
test(checkRecord("ALLPPAPL"), false, 'Test 80');
test(checkRecord("PPLPPPLPPLLPPPPP"), true, 'Test 81');
test(checkRecord("PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP"), true, 'Test 82');
test(checkRecord("APLPLPLLAPA"), false, 'Test 83');
test(checkRecord("PLLPLLPLLPLL"), true, 'Test 84');
test(checkRecord("AAPLAPPLAPLPPP"), false, 'Test 85');
test(checkRecord("PLPLPLPLPLLPPPLP"), true, 'Test 86');
test(checkRecord("LPLLPLLPLL"), true, 'Test 87');
test(checkRecord("PPPPPPPPLLLPPPPP"), false, 'Test 88');
test(checkRecord("APALPPALPPAL"), false, 'Test 89');
test(checkRecord("PLLAPLLP"), true, 'Test 90');
test(checkRecord("ALALALALALALAL"), false, 'Test 91');
test(checkRecord("ALALALALALAL"), false, 'Test 92');
test(checkRecord("APLPLPALPLPA"), false, 'Test 93');
test(checkRecord("PLLPPLLPLPLL"), true, 'Test 94');
test(checkRecord("LLAALLLLPLLPPP"), false, 'Test 95');
test(checkRecord("LLPPPPPPPPPPPPPPPPPPPPPPPPPPPPLLPPPPPP"), true, 'Test 96');
test(checkRecord("PPALLPA"), false, 'Test 97');
test(checkRecord("PPPPPPPPPPPPLL"), true, 'Test 98');
test(checkRecord("PLPLPLPLPLLPPPA"), true, 'Test 99');
test(checkRecord("PLLALPPLPLL"), true, 'Test 100');
test(checkRecord("APAPAPAPAP"), false, 'Test 101');
test(checkRecord("PPALLLPPALLP"), false, 'Test 102');
test(checkRecord("LLPLLLP"), false, 'Test 103');
test(checkRecord("LLPPPPPPPPPP"), true, 'Test 104');
test(checkRecord("PPAPAPAP"), false, 'Test 105');
test(checkRecord("PPALLPLPA"), false, 'Test 106');
test(checkRecord("PLPLPLPLPL"), true, 'Test 107');
test(checkRecord("PPALLPLLALLPP"), false, 'Test 108');
test(checkRecord("PPLPPPPPLP"), true, 'Test 109');
test(checkRecord("AAPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLLPPPPPP"), false, 'Test 110');
test(checkRecord("PPPPPPPPPPPPPPPPPPPPPPP"), true, 'Test 111');
test(checkRecord("PLPLLPLLPLLAP"), true, 'Test 112');
test(checkRecord("AAAAAAAA"), false, 'Test 113');
test(checkRecord("LLAALLAALLAALLAALLAALLAALLAALLAALLAALLAALLAALLAALLAALLAALL"), false, 'Test 114');
test(checkRecord("PALPALPALP"), false, 'Test 115');
test(checkRecord("ALLPLALPA"), false, 'Test 116');
test(checkRecord("PPPPPLPPPPLL"), true, 'Test 117');
test(checkRecord("PAPAPAPAPA"), false, 'Test 118');
test(checkRecord("PPPLAPLLPA"), false, 'Test 119');
test(checkRecord("PLPPPPLPPPLPPP"), true, 'Test 120');
test(checkRecord("PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLLL"), false, 'Test 121');
test(checkRecord("PALLPLLP"), true, 'Test 122');
test(checkRecord("LLPPLLPLP"), true, 'Test 123');
test(checkRecord("LLPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP"), true, 'Test 124');
test(checkRecord("PPALLPLLPLPPP"), true, 'Test 125');
test(checkRecord("PPPPPPPPPPPPPPPPPPPPPPPPPPPPPAL"), true, 'Test 126');
test(checkRecord("PLALLAPLLP"), false, 'Test 127');
test(checkRecord("LLAAPLLAALLP"), false, 'Test 128');
test(checkRecord("ALPLPALPALLP"), false, 'Test 129');
test(checkRecord("PPPPPPPPPPPPPPPPPPPPPPPPPPPPP"), true, 'Test 130');
test(checkRecord("PPALPLPLPLPA"), false, 'Test 131');
test(checkRecord("PLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLL"), true, 'Test 132');
test(checkRecord("PPPLLPPPLLPPPLL"), true, 'Test 133');
test(checkRecord("AAAAAAAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP"), false, 'Test 134');
test(checkRecord("AAAAA"), false, 'Test 135');
test(checkRecord("PPPLAALLPPPL"), false, 'Test 136');
test(checkRecord("LPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLLPLP"), true, 'Test 137');
test(checkRecord("PALPALPALPAL"), false, 'Test 138');
test(checkRecord("PAALPAALPPA"), false, 'Test 139');
test(checkRecord("ALALALALAL"), false, 'Test 140');
test(checkRecord("LLALALALALL"), false, 'Test 141');
test(checkRecord("PLLPPPLLPPPPPPLL"), true, 'Test 142');
test(checkRecord("LLLL"), false, 'Test 143');
test(checkRecord("PLPLLPLLPLLPLLPLLPL"), true, 'Test 144');
test(checkRecord("PPPPPLPPPPLP"), true, 'Test 145');
test(checkRecord("LLLPLLPPP"), false, 'Test 146');
test(checkRecord("PLLPLLPLL"), true, 'Test 147');
test(checkRecord("PPALLPLLPA"), false, 'Test 148');
test(checkRecord("PPPPPPPPPPPPPPLL"), true, 'Test 149');
test(checkRecord("PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLL"), true, 'Test 150');
test(checkRecord("PLPPPPLPPPPPP"), true, 'Test 151');
test(checkRecord("AAPAAPAAPAAPAP"), false, 'Test 152');
test(checkRecord("APAPAPAPAPAP"), false, 'Test 153');
test(checkRecord("AAPPLL"), false, 'Test 154');
test(checkRecord("PPAALLL"), false, 'Test 155');
test(checkRecord("PPAPLPLAPL"), false, 'Test 156');
test(checkRecord("LLLLPPLP"), false, 'Test 157');
test(checkRecord("PPALLPLLAP"), false, 'Test 158');
test(checkRecord("PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP"), true, 'Test 159');
test(checkRecord("PPPLLLPPPLLPP"), false, 'Test 160');
test(checkRecord("ALLPPLLAPL"), false, 'Test 161');
test(checkRecord("PPALLPLLALLL"), false, 'Test 162');
test(checkRecord("PLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLP"), true, 'Test 163');
test(checkRecord("PPPPPPPPPPLL"), true, 'Test 164');
test(checkRecord("PPLPALPALPAL"), false, 'Test 165');
test(checkRecord("PPALLLL"), false, 'Test 166');
test(checkRecord("LLPLLLPLL"), false, 'Test 167');
test(checkRecord("PPAALPPALLP"), false, 'Test 168');
test(checkRecord("PLAPLLPLPAPL"), false, 'Test 169');
test(checkRecord("LLPPLLPLPLLPLL"), true, 'Test 170');
test(checkRecord("PLLAPPPALPLL"), false, 'Test 171');
test(checkRecord("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALLL"), false, 'Test 172');
test(checkRecord("PAPAPAPAPAPAPAPAPAPA"), false, 'Test 173');
test(checkRecord("LLPPALLPLL"), true, 'Test 174');
test(checkRecord("LLLLPPL"), false, 'Test 175');
test(checkRecord("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"), false, 'Test 176');
test(checkRecord("PPPLPPPPLLPPPLL"), true, 'Test 177');
test(checkRecord("PPALLALPLAL"), false, 'Test 178');
test(checkRecord("PPALLPLLALLP"), false, 'Test 179');
test(checkRecord("LLPPLLPLL"), true, 'Test 180');
test(checkRecord("LLPLLPALL"), true, 'Test 181');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

