// Test: 2901. Longest Unequal Adjacent Groups Subsequence Ii
// 310 test cases from LeetCodeDataset
// Run: node test.js

const { getWordsInLongestSubsequence } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n2901. Longest Unequal Adjacent Groups Subsequence Ii\n");

test(getWordsInLongestSubsequence(["abc","bac","bca","cab","cba","acb"], [1,2,1,2,1,2]), ['abc'], 'Test 1');
test(getWordsInLongestSubsequence(["same","sane","same"], [1,2,1]), ['same', 'sane', 'same'], 'Test 2');
test(getWordsInLongestSubsequence(["test","tast","best","rest"], [1,2,2,3]), ['test', 'best', 'rest'], 'Test 3');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","hexlo"], [1,2,2,3]), ['hello', 'hallo'], 'Test 4');
test(getWordsInLongestSubsequence(["abcd","abcf","abgf","abgh"], [1,2,2,3]), ['abcd', 'abcf'], 'Test 5');
test(getWordsInLongestSubsequence(["hello","hallo","hbllo","hillo"], [1,1,2,3]), ['hello', 'hbllo', 'hillo'], 'Test 6');
test(getWordsInLongestSubsequence(["bab","dab","cab"], [1,2,2]), ['bab', 'dab'], 'Test 7');
test(getWordsInLongestSubsequence(["word","worm","wore","core"], [1,2,1,2]), ['word', 'worm', 'wore', 'core'], 'Test 8');
test(getWordsInLongestSubsequence(["same","sane","tame","game"], [1,2,2,3]), ['same', 'tame', 'game'], 'Test 9');
test(getWordsInLongestSubsequence(["a","b","c","d"], [1,2,3,4]), ['a', 'b', 'c', 'd'], 'Test 10');
test(getWordsInLongestSubsequence(["apple","appla","appel"], [1,2,1]), ['apple', 'appla'], 'Test 11');
test(getWordsInLongestSubsequence(["a","ab","abc","abcd"], [1,2,3,4]), ['a'], 'Test 12');
test(getWordsInLongestSubsequence(["zzz","zzx","zzw","zzv"], [1,2,3,4]), ['zzz', 'zzx', 'zzw', 'zzv'], 'Test 13');
test(getWordsInLongestSubsequence(["test","tast","tost","test"], [1,2,1,2]), ['test', 'tast', 'tost', 'test'], 'Test 14');
test(getWordsInLongestSubsequence(["abc","bcd","cde","def"], [1,2,3,4]), ['abc'], 'Test 15');
test(getWordsInLongestSubsequence(["one","two","three","four"], [1,2,2,3]), ['one'], 'Test 16');
test(getWordsInLongestSubsequence(["abc","def","ghi","jkl"], [1,1,2,2]), ['abc'], 'Test 17');
test(getWordsInLongestSubsequence(["word","wird","word","wird"], [1,2,1,2]), ['word', 'wird', 'word', 'wird'], 'Test 18');
test(getWordsInLongestSubsequence(["abc", "abb", "aba", "aaa", "aab"], [1, 2, 3, 4, 5]), ['abc', 'abb', 'aba', 'aaa', 'aab'], 'Test 19');
test(getWordsInLongestSubsequence(["aabb","abab","abba","baab"], [1,2,1,2]), ['aabb'], 'Test 20');
test(getWordsInLongestSubsequence(["aabb","abab","babb","baab"], [1,2,1,2]), ['babb', 'baab'], 'Test 21');
test(getWordsInLongestSubsequence(["cat","cot","dog","dot","log"], [1,2,1,2,3]), ['cat', 'cot'], 'Test 22');
test(getWordsInLongestSubsequence(["abc","acb","bac","bca","cab","cba"], [1,2,1,2,1,2]), ['abc'], 'Test 23');
test(getWordsInLongestSubsequence(["xyz","xyw","xyv","xyu"], [1,2,3,4]), ['xyz', 'xyw', 'xyv', 'xyu'], 'Test 24');
test(getWordsInLongestSubsequence(["aaaa","aaab","aabb","abbb","bbbb"], [1,2,3,4,5]), ['aaaa', 'aaab', 'aabb', 'abbb', 'bbbb'], 'Test 25');
test(getWordsInLongestSubsequence(["abc","bac","cab","bca","acb","cba"], [1,2,3,1,2,3]), ['abc'], 'Test 26');
test(getWordsInLongestSubsequence(["abcd","abce","abcf","abcg"], [1,2,3,4]), ['abcd', 'abce', 'abcf', 'abcg'], 'Test 27');
test(getWordsInLongestSubsequence(["abc","abd","acd","bcd","ace"], [1,2,1,2,1]), ['abc', 'abd', 'acd', 'bcd'], 'Test 28');
test(getWordsInLongestSubsequence(["abcd","abcf","abdf","abef","acdf","acef","bcdf","bcef"], [1,2,1,2,1,2,1,2]), ['abcd', 'abcf', 'abdf', 'abef'], 'Test 29');
test(getWordsInLongestSubsequence(["code","codd","cods","coex","coey"], [1,2,2,3,3]), ['code', 'codd'], 'Test 30');
test(getWordsInLongestSubsequence(["abc","bcd","cde","def","efg"], [1,2,3,4,5]), ['abc'], 'Test 31');
test(getWordsInLongestSubsequence(["apple","apples","appl","app"], [1,2,3,4]), ['apple'], 'Test 32');
test(getWordsInLongestSubsequence(["a","b","c","d","e","f","g","h","i","j"], [1,2,3,4,5,6,7,8,9,10]), ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], 'Test 33');
test(getWordsInLongestSubsequence(["same","sane","sate","site"], [1,2,1,2]), ['same', 'sane', 'sate', 'site'], 'Test 34');
test(getWordsInLongestSubsequence(["abcde","abfde","abcfe","abcef"], [1,2,3,4]), ['abcde', 'abfde'], 'Test 35');
test(getWordsInLongestSubsequence(["abc", "abd", "acd", "bcd", "bce", "bde"], [1, 2, 1, 2, 1, 2]), ['abc', 'abd', 'acd', 'bcd', 'bce', 'bde'], 'Test 36');
test(getWordsInLongestSubsequence(["mnop","mnoq","mnrp","mnsp","mntp"], [1,2,3,2,1]), ['mnop', 'mnrp', 'mnsp', 'mntp'], 'Test 37');
test(getWordsInLongestSubsequence(["apple","apply","appla","appla"], [1,2,1,3]), ['apple', 'apply', 'appla'], 'Test 38');
test(getWordsInLongestSubsequence(["aaaa","abaa","acaa","aada","aada","aadd"], [1,2,3,1,2,3]), ['aaaa', 'abaa', 'acaa'], 'Test 39');
test(getWordsInLongestSubsequence(["dog","cog","dag","dog","dig"], [1,2,1,2,1]), ['dag', 'dog', 'dig'], 'Test 40');
test(getWordsInLongestSubsequence(["word","worm","wirm","wirm","wirn"], [1,2,3,4,5]), ['word', 'worm', 'wirm', 'wirn'], 'Test 41');
test(getWordsInLongestSubsequence(["test","tast","tost","test","teat"], [1,2,1,2,1]), ['test', 'tast', 'tost', 'test', 'teat'], 'Test 42');
test(getWordsInLongestSubsequence(["aaaaa","aaaba","aaaca","aaada"], [1,2,1,2]), ['aaaaa', 'aaaba', 'aaaca', 'aaada'], 'Test 43');
test(getWordsInLongestSubsequence(["cat","bat","rat","tat"], [1,2,1,2]), ['cat', 'bat', 'rat', 'tat'], 'Test 44');
test(getWordsInLongestSubsequence(["abcde","abcdf","abcgf","abchg","abchf"], [1,2,3,4,3]), ['abcde', 'abcdf', 'abcgf'], 'Test 45');
test(getWordsInLongestSubsequence(["abcde","abcdf","abcef","abcag"], [1,2,1,2]), ['abcde', 'abcdf', 'abcef'], 'Test 46');
test(getWordsInLongestSubsequence(["apple","appla","appla","applb","applc"], [1,2,2,3,3]), ['apple', 'appla', 'applb'], 'Test 47');
test(getWordsInLongestSubsequence(["abc", "acc", "bcd", "bce", "bde"], [1, 2, 1, 2, 1]), ['bcd', 'bce', 'bde'], 'Test 48');
test(getWordsInLongestSubsequence(["start","starr","statr","strat","strot"], [1,2,1,2,1]), ['start', 'starr', 'statr'], 'Test 49');
test(getWordsInLongestSubsequence(["abcd","abcf","abdg","abef"], [1,2,3,4]), ['abcd', 'abcf', 'abef'], 'Test 50');
test(getWordsInLongestSubsequence(["aaaa","aaab","aaba","abaa","baaa"], [1,2,3,4,5]), ['aaaa', 'aaab'], 'Test 51');
test(getWordsInLongestSubsequence(["kitten","sitten","bitten","bitter","bitter"], [1,2,3,4,5]), ['kitten', 'sitten', 'bitten', 'bitter'], 'Test 52');
test(getWordsInLongestSubsequence(["hello","hallo","hella","hellu"], [1,2,1,2]), ['hello', 'hallo'], 'Test 53');
test(getWordsInLongestSubsequence(["abcd","abce","abcf","abcg","abch","abcx"], [1,2,3,4,5,6]), ['abcd', 'abce', 'abcf', 'abcg', 'abch', 'abcx'], 'Test 54');
test(getWordsInLongestSubsequence(["hello","hxllo","hexlo","helxo"], [1,2,3,4]), ['hello', 'hxllo'], 'Test 55');
test(getWordsInLongestSubsequence(["aabb","abab","baba","bbaa"], [1,2,1,2]), ['aabb'], 'Test 56');
test(getWordsInLongestSubsequence(["apple","abble","abble","abble"], [1,2,3,2]), ['apple'], 'Test 57');
test(getWordsInLongestSubsequence(["abcd","abce","abcf","abcg","abch","abci"], [1,2,3,4,5,6]), ['abcd', 'abce', 'abcf', 'abcg', 'abch', 'abci'], 'Test 58');
test(getWordsInLongestSubsequence(["abc","abd","abe","bcd","bce"], [1,1,2,2,3]), ['abc', 'abe'], 'Test 59');
test(getWordsInLongestSubsequence(["abcd","abcf","abcd","abcf"], [1,2,1,2]), ['abcd', 'abcf', 'abcd', 'abcf'], 'Test 60');
test(getWordsInLongestSubsequence(["abcd","abcf","abcd","abdf"], [1,2,3,4]), ['abcd', 'abcf', 'abcd'], 'Test 61');
test(getWordsInLongestSubsequence(["abcd","acbd","abzd","abxc"], [1,2,3,4]), ['abcd', 'abzd'], 'Test 62');
test(getWordsInLongestSubsequence(["same","same","same","same"], [1,2,3,4]), ['same'], 'Test 63');
test(getWordsInLongestSubsequence(["abc","abd","acc","bcd"], [1,2,1,3]), ['abc', 'abd'], 'Test 64');
test(getWordsInLongestSubsequence(["zebra","zeara","zeraa","zerar"], [1,2,1,2]), ['zebra', 'zeara'], 'Test 65');
test(getWordsInLongestSubsequence(["abcd","abdc","acdb","adcb","bacd","bcad","bdac","bdca"], [1,2,1,2,1,2,1,2]), ['abcd'], 'Test 66');
test(getWordsInLongestSubsequence(["apple","apply","spoke","slope"], [1,2,3,4]), ['apple', 'apply'], 'Test 67');
test(getWordsInLongestSubsequence(["abcd","abcf","abdc","abcf"], [1,2,1,2]), ['abcd', 'abcf'], 'Test 68');
test(getWordsInLongestSubsequence(["hello","hallo","hullo","hella","hillo"], [1,2,1,2,1]), ['hello', 'hallo', 'hullo'], 'Test 69');
test(getWordsInLongestSubsequence(["hello","hallo","hella","hell"], [1,2,1,2]), ['hello', 'hallo'], 'Test 70');
test(getWordsInLongestSubsequence(["test","tset","sett","stet"], [1,2,1,2]), ['test'], 'Test 71');
test(getWordsInLongestSubsequence(["word", "worm", "wore", "core", "cord", "cred"], [1, 2, 1, 2, 1, 2]), ['word', 'worm', 'wore', 'core', 'cord'], 'Test 72');
test(getWordsInLongestSubsequence(["zebra","zera","zeraa","zeara"], [1,2,1,2]), ['zebra', 'zeara'], 'Test 73');
test(getWordsInLongestSubsequence(["zebra","zebra","zebra","zebra"], [1,2,1,2]), ['zebra'], 'Test 74');
test(getWordsInLongestSubsequence(["abcd","abce","abcf","abca"], [1,2,3,4]), ['abcd', 'abce', 'abcf', 'abca'], 'Test 75');
test(getWordsInLongestSubsequence(["dog","dig","dug","dot"], [1,2,1,2]), ['dog', 'dig', 'dug'], 'Test 76');
test(getWordsInLongestSubsequence(["abcd","abcf","abde","abdc"], [1,2,3,4]), ['abcd', 'abcf'], 'Test 77');
test(getWordsInLongestSubsequence(["hello","hallo","hella","hellu"], [1,2,1,3]), ['hello', 'hallo'], 'Test 78');
test(getWordsInLongestSubsequence(["abcd","abcf","abdg","abeg"], [1,2,3,4]), ['abcd', 'abcf'], 'Test 79');
test(getWordsInLongestSubsequence(["abc","abd","acd","bcd","ace","bce","abe","bde","cde","abc"], [1,2,3,4,5,6,7,8,9,10]), ['abc', 'abd', 'acd', 'bcd', 'bce', 'bde', 'cde'], 'Test 80');
test(getWordsInLongestSubsequence(["one","two","three","four","five"], [1,2,3,4,5]), ['one'], 'Test 81');
test(getWordsInLongestSubsequence(["word","wird","wurd","wurd","wurk"], [1,2,1,2,3]), ['word', 'wird', 'wurd', 'wurk'], 'Test 82');
test(getWordsInLongestSubsequence(["same","sane","sane","sane","same"], [1,2,2,3,3]), ['same', 'sane', 'same'], 'Test 83');
test(getWordsInLongestSubsequence(["abc","acb","bac","bca","cab","cba","abc"], [1,2,1,2,1,2,1]), ['abc'], 'Test 84');
test(getWordsInLongestSubsequence(["abcd","abcf","abde","abce","abcd"], [1,2,3,4,1]), ['abcd', 'abcf', 'abce', 'abcd'], 'Test 85');
test(getWordsInLongestSubsequence(["xyza","xyzb","xyzc","xyzd"], [1,2,3,4]), ['xyza', 'xyzb', 'xyzc', 'xyzd'], 'Test 86');
test(getWordsInLongestSubsequence(["abc","acd","bcd","bed"], [1,2,1,2]), ['acd', 'bcd', 'bed'], 'Test 87');
test(getWordsInLongestSubsequence(["zebra","zera","zeraa","zerab","zercb"], [1,2,1,2,1]), ['zeraa', 'zerab', 'zercb'], 'Test 88');
test(getWordsInLongestSubsequence(["code","kode","coke","cide"], [1,2,1,2]), ['code', 'kode'], 'Test 89');
test(getWordsInLongestSubsequence(["abc","abd","bcd","bce"], [1,2,1,2]), ['abc', 'abd'], 'Test 90');
test(getWordsInLongestSubsequence(["word","worm","worn","word"], [1,2,1,2]), ['word', 'worm', 'worn', 'word'], 'Test 91');
test(getWordsInLongestSubsequence(["python","phyton","phthon","pyhton"], [1,2,1,2]), ['python'], 'Test 92');
test(getWordsInLongestSubsequence(["hello","hallo","hillo","hella","hellb"], [1,2,2,3,3]), ['hello', 'hallo'], 'Test 93');
test(getWordsInLongestSubsequence(["test","tast","tost","test"], [1,2,3,4]), ['test', 'tast', 'tost', 'test'], 'Test 94');
test(getWordsInLongestSubsequence(["abc","aabb","abbb","babb","bbcc"], [1,2,2,3,3]), ['aabb', 'babb'], 'Test 95');
test(getWordsInLongestSubsequence(["abcd","abcf","abdf","acdf"], [1,2,3,1]), ['abcd', 'abcf', 'abdf', 'acdf'], 'Test 96');
test(getWordsInLongestSubsequence(["hello","hallo","hullo","hella"], [1,2,3,4]), ['hello', 'hallo', 'hullo'], 'Test 97');
test(getWordsInLongestSubsequence(["aaaa","aaab","aabb","abbb"], [1,1,2,2]), ['aaab', 'aabb'], 'Test 98');
test(getWordsInLongestSubsequence(["abcd","abdd","acdd","acdd","acde","acdf"], [1,2,3,1,2,3]), ['abcd', 'abdd', 'acdd', 'acde', 'acdf'], 'Test 99');
test(getWordsInLongestSubsequence(["abc","def","ghi","jkl","mno"], [1,1,1,1,1]), ['abc'], 'Test 100');
test(getWordsInLongestSubsequence(["aabb","abab","abba","baab","baba","bbaa"], [1,2,3,4,5,6]), ['aabb'], 'Test 101');
test(getWordsInLongestSubsequence(["hello","hallo","hillo","hollo"], [1,1,2,2]), ['hello', 'hillo'], 'Test 102');
test(getWordsInLongestSubsequence(["aabb","aacc","aadd","aabb","aacc"], [1,2,3,1,2]), ['aabb'], 'Test 103');
test(getWordsInLongestSubsequence(["abcd","abcf","acdf","bcdf"], [1,2,3,4]), ['abcd', 'abcf'], 'Test 104');
test(getWordsInLongestSubsequence(["one", "two", "thr", "fou", "fiv"], [1, 2, 1, 2, 1]), ['one'], 'Test 105');
test(getWordsInLongestSubsequence(["apple","appla","applb","applc","appld"], [1,2,2,2,3]), ['apple', 'appla', 'appld'], 'Test 106');
test(getWordsInLongestSubsequence(["graph","grapf","graph","grapt","grapt"], [1,2,3,2,1]), ['graph', 'grapf', 'graph', 'grapt'], 'Test 107');
test(getWordsInLongestSubsequence(["abcd","abce","abcf","abcd"], [1,2,1,2]), ['abcd', 'abce', 'abcf', 'abcd'], 'Test 108');
test(getWordsInLongestSubsequence(["aaab","abab","abba","baaa"], [1,2,3,4]), ['aaab', 'abab'], 'Test 109');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","hexlo","hexxo"], [1,2,2,3,3]), ['hello', 'hallo'], 'Test 110');
test(getWordsInLongestSubsequence(["abc","bcd","bce","bde","bdf"], [1,2,2,3,4]), ['bce', 'bde', 'bdf'], 'Test 111');
test(getWordsInLongestSubsequence(["abcd","abcf","abde","abce"], [1,2,3,4]), ['abcd', 'abcf', 'abce'], 'Test 112');
test(getWordsInLongestSubsequence(["abcd","abce","abcf","abcg","abch"], [1,2,3,4,5]), ['abcd', 'abce', 'abcf', 'abcg', 'abch'], 'Test 113');
test(getWordsInLongestSubsequence(["abcd","abce","abcf","abdg","abdh"], [1,2,3,4,5]), ['abcd', 'abce', 'abcf'], 'Test 114');
test(getWordsInLongestSubsequence(["abc","abd","abe","ace","adf","aeg"], [1,2,1,2,1,2]), ['abc', 'abd', 'abe', 'ace'], 'Test 115');
test(getWordsInLongestSubsequence(["cat","bat","rat","mat"], [1,2,1,2]), ['cat', 'bat', 'rat', 'mat'], 'Test 116');
test(getWordsInLongestSubsequence(["apple","apble","appla","applb","applc"], [1,2,3,2,1]), ['apple', 'appla', 'applb', 'applc'], 'Test 117');
test(getWordsInLongestSubsequence(["aaaa","aaab","aaba","abaa"], [1,2,1,2]), ['aaaa', 'aaab'], 'Test 118');
test(getWordsInLongestSubsequence(["abcd","abce","abcf","abci","abcj"], [1,2,3,4,5]), ['abcd', 'abce', 'abcf', 'abci', 'abcj'], 'Test 119');
test(getWordsInLongestSubsequence(["hello", "hallo", "hxllo", "hexlo", "hexxo"], [1, 2, 3, 4, 5]), ['hello', 'hallo', 'hxllo'], 'Test 120');
test(getWordsInLongestSubsequence(["cat","bat","rat","cap","car"], [1,2,3,4,5]), ['cat', 'bat', 'rat'], 'Test 121');
test(getWordsInLongestSubsequence(["aaaa","abaa","acaa","aada"], [1,1,2,2]), ['aaaa', 'acaa'], 'Test 122');
test(getWordsInLongestSubsequence(["apple", "abble", "abble", "abble", "abble"], [1, 2, 1, 2, 1]), ['apple'], 'Test 123');
test(getWordsInLongestSubsequence(["zzzz","zzzw","zzzx","zzzy"], [1,2,3,4]), ['zzzz', 'zzzw', 'zzzx', 'zzzy'], 'Test 124');
test(getWordsInLongestSubsequence(["abcd","abcc","abcb","abca"], [1,2,1,2]), ['abcd', 'abcc', 'abcb', 'abca'], 'Test 125');
test(getWordsInLongestSubsequence(["aaaa","abaa","acaa","adab","adac"], [1,2,3,1,2]), ['aaaa', 'abaa', 'acaa'], 'Test 126');
test(getWordsInLongestSubsequence(["xylo","xyxo","xyxo","xylo","xylo"], [1,2,3,2,1]), ['xylo', 'xyxo', 'xylo'], 'Test 127');
test(getWordsInLongestSubsequence(["aaaa", "aaba", "abaa", "abba", "acaa", "acba"], [1, 2, 1, 2, 1, 2]), ['aaaa', 'aaba'], 'Test 128');
test(getWordsInLongestSubsequence(["zzzz","zzzy","zzzx","zzxw"], [5,4,3,2]), ['zzzz', 'zzzy', 'zzzx'], 'Test 129');
test(getWordsInLongestSubsequence(["abcd","abdc","acdb","adcb"], [1,2,1,2]), ['abcd'], 'Test 130');
test(getWordsInLongestSubsequence(["aaaa","aaab","aaba","abaa","aaaa"], [1,2,1,2,1]), ['aaaa', 'aaab', 'aaaa'], 'Test 131');
test(getWordsInLongestSubsequence(["hello","hallo","hillo","hillo"], [1,2,1,3]), ['hello', 'hallo', 'hillo'], 'Test 132');
test(getWordsInLongestSubsequence(["abcde","abxde","abxde","abcye"], [1,2,2,3]), ['abcde', 'abxde'], 'Test 133');
test(getWordsInLongestSubsequence(["aaaa","abaa","acaa","aada","aada","aadd","aadd","aade"], [1,2,1,2,3,3,4,4]), ['aaaa', 'aada', 'aadd', 'aade'], 'Test 134');
test(getWordsInLongestSubsequence(["apple","appla","abble","abble"], [1,2,3,2]), ['apple', 'appla'], 'Test 135');
test(getWordsInLongestSubsequence(["hello","hallo","hullo","hellu"], [1,2,1,2]), ['hello', 'hallo', 'hullo'], 'Test 136');
test(getWordsInLongestSubsequence(["test", "tast", "tost", "test", "tast", "tost", "test"], [1, 2, 1, 2, 1, 2, 1]), ['test', 'tast', 'tost', 'test', 'tast', 'tost', 'test'], 'Test 137');
test(getWordsInLongestSubsequence(["zzzz","zzzy","zzzx","zzxw"], [1,2,1,2]), ['zzzz', 'zzzy', 'zzzx'], 'Test 138');
test(getWordsInLongestSubsequence(["apple","apply","appla","applu"], [1,2,3,4]), ['apple', 'apply', 'appla', 'applu'], 'Test 139');
test(getWordsInLongestSubsequence(["word", "ward", "wird", "wrod", "wore", "core"], [1, 2, 1, 2, 1, 2]), ['word', 'ward', 'wird'], 'Test 140');
test(getWordsInLongestSubsequence(["word","worm","womb","womb"], [1,2,1,3]), ['word', 'worm'], 'Test 141');
test(getWordsInLongestSubsequence(["dog","dot","lot","log","cog"], [1,2,2,3,4]), ['dog', 'log', 'cog'], 'Test 142');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","hellp"], [1,2,3,4]), ['hello', 'hallo', 'hxllo'], 'Test 143');
test(getWordsInLongestSubsequence(["same","sane","sane","same"], [1,2,3,4]), ['same', 'sane', 'same'], 'Test 144');
test(getWordsInLongestSubsequence(["abc","abd","acd","bcd"], [1,2,1,2]), ['abc', 'abd', 'acd', 'bcd'], 'Test 145');
test(getWordsInLongestSubsequence(["one","two","three"], [1,2,1]), ['one'], 'Test 146');
test(getWordsInLongestSubsequence(["abc","abd","acc","bcd"], [1,1,2,2]), ['abc', 'acc'], 'Test 147');
test(getWordsInLongestSubsequence(["abc","abd","abc","abe"], [1,2,3,4]), ['abc', 'abd', 'abc', 'abe'], 'Test 148');
test(getWordsInLongestSubsequence(["hello","hallo","hullo","hellu"], [1,1,2,2]), ['hello', 'hullo'], 'Test 149');
test(getWordsInLongestSubsequence(["abc","def","ghi","jkl"], [1,1,1,1]), ['abc'], 'Test 150');
test(getWordsInLongestSubsequence(["aaaa","aaab","aaba","abaa","abab","abba","bbaa","bbab","bbba","bbbb"], [1,1,1,1,1,1,1,1,1,1]), ['aaaa'], 'Test 151');
test(getWordsInLongestSubsequence(["abc","abd","bcd","ace"], [1,2,1,2]), ['abc', 'abd'], 'Test 152');
test(getWordsInLongestSubsequence(["loop","loap","leep","leap"], [1,2,3,4]), ['loop', 'loap', 'leap'], 'Test 153');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","hexlo"], [1,2,1,2]), ['hello', 'hallo', 'hxllo'], 'Test 154');
test(getWordsInLongestSubsequence(["word","ward","wear","ware"], [1,2,3,2]), ['word', 'ward'], 'Test 155');
test(getWordsInLongestSubsequence(["aaa","aab","aac","aba","abb"], [1,2,3,4,5]), ['aaa', 'aab', 'aac'], 'Test 156');
test(getWordsInLongestSubsequence(["fun","sun","tun","fum"], [1,2,3,4]), ['fun', 'sun', 'tun'], 'Test 157');
test(getWordsInLongestSubsequence(["abcd","abcf","abdc"], [1,2,1]), ['abcd', 'abcf'], 'Test 158');
test(getWordsInLongestSubsequence(["word","woro","work"], [3,3,4]), ['word', 'work'], 'Test 159');
test(getWordsInLongestSubsequence(["test","tast","tist","best"], [1,2,3,1]), ['test', 'tast', 'tist'], 'Test 160');
test(getWordsInLongestSubsequence(["cat","bat","rat","car"], [1,2,1,2]), ['cat', 'bat', 'rat'], 'Test 161');
test(getWordsInLongestSubsequence(["test","text","tast","tect"], [1,2,1,2]), ['test', 'text'], 'Test 162');
test(getWordsInLongestSubsequence(["apple","appla","applb","applc"], [3,3,4,4]), ['apple', 'applb'], 'Test 163');
test(getWordsInLongestSubsequence(["zero","hero","hero","hero"], [1,2,1,2]), ['zero', 'hero'], 'Test 164');
test(getWordsInLongestSubsequence(["cat","bat","rat","car"], [1,2,3,4]), ['cat', 'bat', 'rat'], 'Test 165');
test(getWordsInLongestSubsequence(["abcd","abcf","abgd"], [1,2,1]), ['abcd', 'abcf'], 'Test 166');
test(getWordsInLongestSubsequence(["word","work","worm","worn"], [1,2,1,2]), ['word', 'work', 'worm', 'worn'], 'Test 167');
test(getWordsInLongestSubsequence(["word","wird","word","wird"], [1,2,3,4]), ['word', 'wird', 'word', 'wird'], 'Test 168');
test(getWordsInLongestSubsequence(["zebra","zebra","zebra"], [1,2,1]), ['zebra'], 'Test 169');
test(getWordsInLongestSubsequence(["hello","hallo","hellp","hxllo"], [5,5,6,7]), ['hello', 'hellp'], 'Test 170');
test(getWordsInLongestSubsequence(["hello","hallo","hella"], [1,2,3]), ['hello', 'hallo'], 'Test 171');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","hexlo"], [1,1,2,2]), ['hello', 'hxllo'], 'Test 172');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo"], [1,1,2]), ['hello', 'hxllo'], 'Test 173');
test(getWordsInLongestSubsequence(["dog","dot","lot","log"], [1,2,3,4]), ['dog', 'dot', 'lot', 'log'], 'Test 174');
test(getWordsInLongestSubsequence(["test","text","tast","tuxt"], [1,1,2,2]), ['test', 'tast'], 'Test 175');
test(getWordsInLongestSubsequence(["star","tart","kart","tars"], [1,2,3,4]), ['tart', 'kart'], 'Test 176');
test(getWordsInLongestSubsequence(["tiny","tint","tint","tank"], [1,2,1,2]), ['tiny', 'tint'], 'Test 177');
test(getWordsInLongestSubsequence(["aaa","aab","aac","aba","aca","baa","bab","bac","caa","cab","cac"], [1,2,3,4,5,6,7,8,9,10,11]), ['aaa', 'aab', 'aac', 'bac', 'cac'], 'Test 178');
test(getWordsInLongestSubsequence(["apple","appla","applu","appli"], [1,2,1,2]), ['apple', 'appla', 'applu', 'appli'], 'Test 179');
test(getWordsInLongestSubsequence(["java","lava","slava","flava"], [1,2,3,4]), ['java', 'lava'], 'Test 180');
test(getWordsInLongestSubsequence(["same","sane","tame","game"], [1,2,1,2]), ['same', 'sane'], 'Test 181');
test(getWordsInLongestSubsequence(["a","aa","aaa","aaaa","aaaaa"], [1,2,3,4,5]), ['a'], 'Test 182');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","hellp"], [1,1,2,2]), ['hello', 'hxllo'], 'Test 183');
test(getWordsInLongestSubsequence(["word","wird","word","wird"], [1,2,2,3]), ['word', 'wird'], 'Test 184');
test(getWordsInLongestSubsequence(["zzz","zyz","zxy","zyx"], [1,2,3,4]), ['zzz', 'zyz', 'zyx'], 'Test 185');
test(getWordsInLongestSubsequence(["xyz","xyx","yzz","zzy"], [3,2,3,2]), ['xyz', 'xyx'], 'Test 186');
test(getWordsInLongestSubsequence(["test","text","tset","best"], [1,2,3,4]), ['test', 'text'], 'Test 187');
test(getWordsInLongestSubsequence(["apple","appla","applb","applc"], [1,2,3,4]), ['apple', 'appla', 'applb', 'applc'], 'Test 188');
test(getWordsInLongestSubsequence(["abc","def","ghi"], [1,2,3]), ['abc'], 'Test 189');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","pxllo"], [1,2,1,2]), ['hello', 'hallo', 'hxllo', 'pxllo'], 'Test 190');
test(getWordsInLongestSubsequence(["code","kode","kode"], [1,2,1]), ['code', 'kode'], 'Test 191');
test(getWordsInLongestSubsequence(["hello","hallo","hullo","hellp"], [1,2,1,2]), ['hello', 'hallo', 'hullo'], 'Test 192');
test(getWordsInLongestSubsequence(["test","tast","west","lest"], [1,2,1,2]), ['test', 'tast'], 'Test 193');
test(getWordsInLongestSubsequence(["cat","bat","rat","car"], [1,1,2,2]), ['cat', 'rat'], 'Test 194');
test(getWordsInLongestSubsequence(["abc","abd","acc","bcd"], [1,2,1,2]), ['abc', 'abd'], 'Test 195');
test(getWordsInLongestSubsequence(["abc","bcd","cde","dec"], [1,2,3,4]), ['abc'], 'Test 196');
test(getWordsInLongestSubsequence(["test","tast","fest","best"], [1,2,1,2]), ['test', 'tast'], 'Test 197');
test(getWordsInLongestSubsequence(["aaa","aab","aba","baa","bbb"], [1,2,3,2,1]), ['aaa', 'aab'], 'Test 198');
test(getWordsInLongestSubsequence(["hello","hallo","hellp","herlo"], [1,1,2,2]), ['hello', 'hellp'], 'Test 199');
test(getWordsInLongestSubsequence(["test","tast","tist"], [1,2,3]), ['test', 'tast', 'tist'], 'Test 200');
test(getWordsInLongestSubsequence(["one","two","three","four"], [1,1,1,1]), ['one'], 'Test 201');
test(getWordsInLongestSubsequence(["aaaa","aaab","aaba","abaa"], [1,2,3,4]), ['aaaa', 'aaab'], 'Test 202');
test(getWordsInLongestSubsequence(["one","two","three","four"], [1,1,2,2]), ['one'], 'Test 203');
test(getWordsInLongestSubsequence(["hello","hallo","hella"], [1,2,1]), ['hello', 'hallo'], 'Test 204');
test(getWordsInLongestSubsequence(["test","tast","tist","teat"], [1,2,1,2]), ['test', 'tast', 'tist'], 'Test 205');
test(getWordsInLongestSubsequence(["test","tast","tast"], [1,2,1]), ['test', 'tast'], 'Test 206');
test(getWordsInLongestSubsequence(["abc","abd","acc"], [1,2,1]), ['abc', 'abd'], 'Test 207');
test(getWordsInLongestSubsequence(["abc","abd","acc","acd"], [1,2,3,4]), ['abc', 'abd', 'acd'], 'Test 208');
test(getWordsInLongestSubsequence(["abc","abcd","abce"], [1,2,3]), ['abcd', 'abce'], 'Test 209');
test(getWordsInLongestSubsequence(["apple","apble","aagle","apgle","applu"], [1,2,1,2,1]), ['apple', 'apble'], 'Test 210');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","hell"], [1,2,1,2]), ['hello', 'hallo', 'hxllo'], 'Test 211');
test(getWordsInLongestSubsequence(["hello","hallo","hella","hellu"], [1,2,2,3]), ['hello', 'hella', 'hellu'], 'Test 212');
test(getWordsInLongestSubsequence(["same","sane","sane","same"], [1,2,1,2]), ['same', 'sane'], 'Test 213');
test(getWordsInLongestSubsequence(["apple","appla","applb","applc"], [1,2,1,2]), ['apple', 'appla', 'applb', 'applc'], 'Test 214');
test(getWordsInLongestSubsequence(["code","cide","codi","coie"], [1,1,2,2]), ['code', 'codi'], 'Test 215');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo"], [1,2,1]), ['hello', 'hallo', 'hxllo'], 'Test 216');
test(getWordsInLongestSubsequence(["zoom","boom","boon","boom"], [1,2,1,3]), ['zoom', 'boom', 'boon', 'boom'], 'Test 217');
test(getWordsInLongestSubsequence(["abcd","abcf","abef","abeg"], [1,2,3,4]), ['abcd', 'abcf', 'abef', 'abeg'], 'Test 218');
test(getWordsInLongestSubsequence(["keep","peek","peel"], [1,2,1]), ['peek', 'peel'], 'Test 219');
test(getWordsInLongestSubsequence(["word","worm","worn"], [1,2,3]), ['word', 'worm', 'worn'], 'Test 220');
test(getWordsInLongestSubsequence(["apple","appla","applb","applc"], [1,2,2,3]), ['apple', 'appla', 'applc'], 'Test 221');
test(getWordsInLongestSubsequence(["aaa","aab","aac","aad"], [1,2,1,2]), ['aaa', 'aab', 'aac', 'aad'], 'Test 222');
test(getWordsInLongestSubsequence(["abc","bcd","cde","def"], [1,1,2,3]), ['abc'], 'Test 223');
test(getWordsInLongestSubsequence(["aaa","aab","aac"], [1,2,3]), ['aaa', 'aab', 'aac'], 'Test 224');
test(getWordsInLongestSubsequence(["test","tast","tist","tast"], [1,2,3,1]), ['test', 'tast', 'tist', 'tast'], 'Test 225');
test(getWordsInLongestSubsequence(["test","tast","tekt"], [1,2,3]), ['test', 'tast'], 'Test 226');
test(getWordsInLongestSubsequence(["abcd","abce","abcf"], [1,2,3]), ['abcd', 'abce', 'abcf'], 'Test 227');
test(getWordsInLongestSubsequence(["word","wore","word","worn"], [1,2,3,4]), ['word', 'wore', 'word', 'worn'], 'Test 228');
test(getWordsInLongestSubsequence(["one","two","thr"], [1,1,1]), ['one'], 'Test 229');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","hellp"], [1,2,1,2]), ['hello', 'hallo', 'hxllo'], 'Test 230');
test(getWordsInLongestSubsequence(["code","coed","cdeo"], [2,2,3]), ['code'], 'Test 231');
test(getWordsInLongestSubsequence(["loop","lopo","leep"], [1,2,1]), ['loop'], 'Test 232');
test(getWordsInLongestSubsequence(["same","sane","safe"], [1,1,2]), ['same', 'safe'], 'Test 233');
test(getWordsInLongestSubsequence(["apple","apply","spoil","spied"], [1,1,2,2]), ['apple'], 'Test 234');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","pxllo"], [1,2,3,4]), ['hello', 'hallo', 'hxllo', 'pxllo'], 'Test 235');
test(getWordsInLongestSubsequence(["test","text","tast","tast"], [1,2,1,3]), ['test', 'text'], 'Test 236');
test(getWordsInLongestSubsequence(["abcd","abcf","abdf","abef"], [1,2,3,4]), ['abcd', 'abcf', 'abdf', 'abef'], 'Test 237');
test(getWordsInLongestSubsequence(["one","two","ton","oen"], [1,1,2,2]), ['one'], 'Test 238');
test(getWordsInLongestSubsequence(["word","wird","word","wond"], [1,1,2,2]), ['wird', 'word'], 'Test 239');
test(getWordsInLongestSubsequence(["test","tast","ttst"], [1,2,3]), ['test', 'tast', 'ttst'], 'Test 240');
test(getWordsInLongestSubsequence(["aaa","aab","aac"], [1,2,1]), ['aaa', 'aab', 'aac'], 'Test 241');
test(getWordsInLongestSubsequence(["dog","dot","lot","log"], [1,2,1,2]), ['dog', 'dot', 'lot', 'log'], 'Test 242');
test(getWordsInLongestSubsequence(["test","tast","teat"], [1,2,3]), ['test', 'tast'], 'Test 243');
test(getWordsInLongestSubsequence(["same","sane","same","sane"], [1,2,1,2]), ['same', 'sane', 'same', 'sane'], 'Test 244');
test(getWordsInLongestSubsequence(["apple","bpple","cppld"], [1,2,1]), ['apple', 'bpple'], 'Test 245');
test(getWordsInLongestSubsequence(["xyz","xyx","xzx","xxz"], [1,1,1,1]), ['xyz'], 'Test 246');
test(getWordsInLongestSubsequence(["apple","appla","bpple","appea"], [1,2,3,4]), ['apple', 'appla', 'appea'], 'Test 247');
test(getWordsInLongestSubsequence(["apple","appla","applp"], [1,2,1]), ['apple', 'appla', 'applp'], 'Test 248');
test(getWordsInLongestSubsequence(["abcd","abcf","abce","abdc"], [1,1,2,1]), ['abcd', 'abce'], 'Test 249');
test(getWordsInLongestSubsequence(["same","sane","sale","tale"], [1,2,3,4]), ['same', 'sane', 'sale', 'tale'], 'Test 250');
test(getWordsInLongestSubsequence(["test","tast","tost","fest"], [1,2,3,4]), ['test', 'tast', 'tost'], 'Test 251');
test(getWordsInLongestSubsequence(["cat","bat","rat","hat"], [1,1,2,2]), ['cat', 'rat'], 'Test 252');
test(getWordsInLongestSubsequence(["one","two","three","four"], [1,2,3,4]), ['one'], 'Test 253');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","pxllo"], [1,2,2,3]), ['hello', 'hxllo', 'pxllo'], 'Test 254');
test(getWordsInLongestSubsequence(["same","sane","sane","same"], [1,2,2,3]), ['same', 'sane', 'same'], 'Test 255');
test(getWordsInLongestSubsequence(["apple","appla","applu","applp"], [1,1,2,2]), ['apple', 'applu'], 'Test 256');
test(getWordsInLongestSubsequence(["same","sane","safe","same"], [1,2,3,1]), ['same', 'sane', 'safe', 'same'], 'Test 257');
test(getWordsInLongestSubsequence(["xyz","xyw","xzz","xyx"], [1,2,1,2]), ['xyz', 'xyw'], 'Test 258');
test(getWordsInLongestSubsequence(["cat","dog","bat"], [1,2,3]), ['cat', 'bat'], 'Test 259');
test(getWordsInLongestSubsequence(["word","ward","cord","card"], [1,2,3,4]), ['word', 'ward', 'card'], 'Test 260');
test(getWordsInLongestSubsequence(["same","sane","sake"], [1,2,1]), ['same', 'sane', 'sake'], 'Test 261');
test(getWordsInLongestSubsequence(["abc","abd","acc","aba"], [1,2,3,2]), ['abc', 'abd'], 'Test 262');
test(getWordsInLongestSubsequence(["apple","appla","abble","abble"], [1,2,2,3]), ['apple', 'appla'], 'Test 263');
test(getWordsInLongestSubsequence(["test","text","tast"], [1,2,1]), ['test', 'text'], 'Test 264');
test(getWordsInLongestSubsequence(["abcd","abcf","abdf"], [1,1,2]), ['abcf', 'abdf'], 'Test 265');
test(getWordsInLongestSubsequence(["word","worm","wirm","wirt"], [1,2,1,3]), ['word', 'worm', 'wirm', 'wirt'], 'Test 266');
test(getWordsInLongestSubsequence(["code","kode","cide","coke"], [1,2,3,4]), ['code', 'kode'], 'Test 267');
test(getWordsInLongestSubsequence(["word","worm","worn"], [1,2,1]), ['word', 'worm', 'worn'], 'Test 268');
test(getWordsInLongestSubsequence(["xyz","xyw","xzz","xyy"], [2,3,2,3]), ['xyz', 'xyw'], 'Test 269');
test(getWordsInLongestSubsequence(["xyz","xyx","xyy","xyw"], [1,2,3,4]), ['xyz', 'xyx', 'xyy', 'xyw'], 'Test 270');
test(getWordsInLongestSubsequence(["same","sane","tame","game"], [1,2,3,4]), ['same', 'tame', 'game'], 'Test 271');
test(getWordsInLongestSubsequence(["tree","trex","trey","gree"], [1,2,1,2]), ['tree', 'trex', 'trey'], 'Test 272');
test(getWordsInLongestSubsequence(["abc","bcd","cde","def"], [1,1,2,2]), ['abc'], 'Test 273');
test(getWordsInLongestSubsequence(["test","tets","tast","tast"], [1,2,2,3]), ['test', 'tast'], 'Test 274');
test(getWordsInLongestSubsequence(["abcd","abcf","abdg"], [1,2,3]), ['abcd', 'abcf'], 'Test 275');
test(getWordsInLongestSubsequence(["hello","hallo","hullo"], [1,2,1]), ['hello', 'hallo', 'hullo'], 'Test 276');
test(getWordsInLongestSubsequence(["abc","bcd","cde"], [1,1,2]), ['abc'], 'Test 277');
test(getWordsInLongestSubsequence(["same","sane","game","tame"], [1,2,1,2]), ['same', 'sane'], 'Test 278');
test(getWordsInLongestSubsequence(["test","tast","teat","teet"], [1,2,3,4]), ['test', 'teat', 'teet'], 'Test 279');
test(getWordsInLongestSubsequence(["abc","abd","acc"], [1,2,3]), ['abc', 'abd'], 'Test 280');
test(getWordsInLongestSubsequence(["code","cide","kode","coda"], [1,2,1,2]), ['code', 'cide'], 'Test 281');
test(getWordsInLongestSubsequence(["same","sane","game"], [1,1,2]), ['same', 'game'], 'Test 282');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo","hexlo"], [10,20,10,30]), ['hello', 'hallo', 'hxllo'], 'Test 283');
test(getWordsInLongestSubsequence(["abc","abd","acc","bcd"], [1,2,3,4]), ['abc', 'abd'], 'Test 284');
test(getWordsInLongestSubsequence(["hello","hallo","hullo","hellp"], [1,2,1,3]), ['hello', 'hallo', 'hullo'], 'Test 285');
test(getWordsInLongestSubsequence(["play","plby","plya","plax"], [1,1,2,2]), ['play', 'plax'], 'Test 286');
test(getWordsInLongestSubsequence(["test","tast","tost","tett"], [1,2,1,2]), ['test', 'tast', 'tost'], 'Test 287');
test(getWordsInLongestSubsequence(["same","sane","sage","page"], [1,1,2,2]), ['same', 'sage'], 'Test 288');
test(getWordsInLongestSubsequence(["test","tast","tell","tall"], [1,2,3,4]), ['test', 'tast'], 'Test 289');
test(getWordsInLongestSubsequence(["same","sane","sale","male"], [1,2,3,4]), ['same', 'sane', 'sale', 'male'], 'Test 290');
test(getWordsInLongestSubsequence(["abcd","abcf","abdf","acdf"], [1,2,3,4]), ['abcd', 'abcf', 'abdf', 'acdf'], 'Test 291');
test(getWordsInLongestSubsequence(["apple","apply","spork"], [1,2,1]), ['apple', 'apply'], 'Test 292');
test(getWordsInLongestSubsequence(["test","text","tast","best"], [1,2,1,3]), ['test', 'text'], 'Test 293');
test(getWordsInLongestSubsequence(["hello","hallo","hxllo"], [1,2,3]), ['hello', 'hallo', 'hxllo'], 'Test 294');
test(getWordsInLongestSubsequence(["abc","abd","bcd","bce"], [1,2,2,3]), ['abc', 'abd'], 'Test 295');
test(getWordsInLongestSubsequence(["one","two","three"], [1,2,3]), ['one'], 'Test 296');
test(getWordsInLongestSubsequence(["same","sane","safe","sale"], [1,2,1,2]), ['same', 'sane', 'safe', 'sale'], 'Test 297');
test(getWordsInLongestSubsequence(["dog","cog","rog"], [1,2,3]), ['dog', 'cog', 'rog'], 'Test 298');
test(getWordsInLongestSubsequence(["five","fife","five","five"], [1,2,1,2]), ['five', 'fife', 'five'], 'Test 299');
test(getWordsInLongestSubsequence(["abc","bcd","cde","efg"], [1,1,2,2]), ['abc'], 'Test 300');
test(getWordsInLongestSubsequence(["aaa","aab","aba","abb","baa","bab","bba","bbb"], [1,2,3,4,5,6,7,8]), ['aaa', 'aab', 'abb', 'bbb'], 'Test 301');
test(getWordsInLongestSubsequence(["zzz","zzy","zyy","yyy"], [1,2,1,2]), ['zzz', 'zzy', 'zyy', 'yyy'], 'Test 302');
test(getWordsInLongestSubsequence(["word","worm","worn","word"], [1,2,1,3]), ['word', 'worm', 'worn', 'word'], 'Test 303');
test(getWordsInLongestSubsequence(["code","mode","mroe"], [1,2,1]), ['code', 'mode'], 'Test 304');
test(getWordsInLongestSubsequence(["word","worm","worn"], [1,1,2]), ['word', 'worn'], 'Test 305');
test(getWordsInLongestSubsequence(["apple","apply","appla"], [1,1,2]), ['apple', 'appla'], 'Test 306');
test(getWordsInLongestSubsequence(["cat","bat","rat","hat"], [1,2,3,4]), ['cat', 'bat', 'rat', 'hat'], 'Test 307');
test(getWordsInLongestSubsequence(["abc","bcd","cde"], [1,1,1]), ['abc'], 'Test 308');
test(getWordsInLongestSubsequence(["cat","bat","rat","hat"], [1,1,1,2]), ['cat', 'hat'], 'Test 309');
test(getWordsInLongestSubsequence(["word","wird","wordy"], [1,2,3]), ['word', 'wird'], 'Test 310');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

