// Test: 1071. Greatest Common Divisor Of Strings
// 175 test cases from LeetCodeDataset
// Run: node test.js

const { gcdOfStrings } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1071. Greatest Common Divisor Of Strings\n");

test(gcdOfStrings("ABAB", "ABA"), , 'Test 1');
test(gcdOfStrings("ABCDEFGH", "XYZ"), , 'Test 2');
test(gcdOfStrings("ABCABC", "ABC"), ABC, 'Test 3');
test(gcdOfStrings("ABABAB", "ABA"), , 'Test 4');
test(gcdOfStrings("ABABAB", "ABAB"), AB, 'Test 5');
test(gcdOfStrings("ABCABCABC", "ABCABC"), ABC, 'Test 6');
test(gcdOfStrings("ABCD", "EFGH"), , 'Test 7');
test(gcdOfStrings("XYZXYZXYZ", "XYZXYZ"), XYZ, 'Test 8');
test(gcdOfStrings("AAAAAAAAAA", "AAAAAAAAAA"), AAAAAAAAAA, 'Test 9');
test(gcdOfStrings("GCDGCDGCD", "GCD"), GCD, 'Test 10');
test(gcdOfStrings("ABCD", "ABCD"), ABCD, 'Test 11');
test(gcdOfStrings("HELLOHELLO", "HELLO"), HELLO, 'Test 12');
test(gcdOfStrings("A", "A"), A, 'Test 13');
test(gcdOfStrings("PQRS", "PQRS"), PQRS, 'Test 14');
test(gcdOfStrings("AAAA", "AA"), AA, 'Test 15');
test(gcdOfStrings("ABCDEFG", "BCD"), , 'Test 16');
test(gcdOfStrings("LEET", "CODE"), , 'Test 17');
test(gcdOfStrings("HELLOHELLOHELLO", "HELLO"), HELLO, 'Test 18');
test(gcdOfStrings("ABCDEF", "ABC"), , 'Test 19');
test(gcdOfStrings("ABABABAB", "BABA"), , 'Test 20');
test(gcdOfStrings("AAAAAAAAA", "AAAAA"), A, 'Test 21');
test(gcdOfStrings("TATATATA", "TAT"), , 'Test 22');
test(gcdOfStrings("ABCABCABC", "ABC"), ABC, 'Test 23');
test(gcdOfStrings("ABABABAB", "ABAB"), ABAB, 'Test 24');
test(gcdOfStrings("BANANABANANABANANABANANA", "BANANABANANA"), BANANABANANA, 'Test 25');
test(gcdOfStrings("XYXYXYXY", "XYXY"), XYXY, 'Test 26');
test(gcdOfStrings("DOUBLEDOUBLEDOUBLE", "DOUBLEDOUBLE"), DOUBLE, 'Test 27');
test(gcdOfStrings("SIMILARITYSIMILARITY", "SIMILARITY"), SIMILARITY, 'Test 28');
test(gcdOfStrings("REPREPREP", "REPRE"), , 'Test 29');
test(gcdOfStrings("ABACABACABAC", "ABAC"), ABAC, 'Test 30');
test(gcdOfStrings("DOGDOGDOGDOGDOGDOG", "DOGDOGDOG"), DOGDOGDOG, 'Test 31');
test(gcdOfStrings("XYZXYZXYZXYZXYZXYZ", "XYZXYZXYZXYZ"), XYZXYZ, 'Test 32');
test(gcdOfStrings("PPPPPPPPPPPPPPPP", "PPPPPP"), PP, 'Test 33');
test(gcdOfStrings("MULTIPLEMULTIPLEMULTIPLE", "MULTIPLEMULTIPLE"), MULTIPLE, 'Test 34');
test(gcdOfStrings("MIXEDCASEMIXEDCASE", "MIXEDCASE"), MIXEDCASE, 'Test 35');
test(gcdOfStrings("XYXYXYXYXYXYXYXY", "XYXYXY"), XY, 'Test 36');
test(gcdOfStrings("ANTEANTEANTEANTEANTEANTEANTEANTEANTE", "ANTEANTEANTEANTE"), ANTE, 'Test 37');
test(gcdOfStrings("QWQWQWQWQWQW", "QWQW"), QWQW, 'Test 38');
test(gcdOfStrings("PINEAPPLEPINEAPPLEPINEAPPLEPINEAPPLE", "PINEAPPLEPINEAPPLE"), PINEAPPLEPINEAPPLE, 'Test 39');
test(gcdOfStrings("MNMNMNMN", "MNMN"), MNMN, 'Test 40');
test(gcdOfStrings("XYZXYZXYZXYZXYZ", "XYZXYZXYZ"), XYZ, 'Test 41');
test(gcdOfStrings("REPORTEPORTEPORTE", "REPORTEPORTE"), , 'Test 42');
test(gcdOfStrings("RRRRRRRRRRRR", "RRRRRR"), RRRRRR, 'Test 43');
test(gcdOfStrings("DIFFERENTLENGTHDIFFERENTLENGTH", "DIFFERENTLENGTH"), DIFFERENTLENGTH, 'Test 44');
test(gcdOfStrings("SMALLSAME", "SAME"), , 'Test 45');
test(gcdOfStrings("MIXEDUPMIXEDUP", "MIXEDUP"), MIXEDUP, 'Test 46');
test(gcdOfStrings("UPPERCASEUPPERCASEUPPERCASE", "UPPERCASEUPPERCASE"), UPPERCASE, 'Test 47');
test(gcdOfStrings("LONGSTRINGLONGSTRINGLONGSTRINGLONGSTRING", "LONGSTRINGLONGSTRING"), LONGSTRINGLONGSTRING, 'Test 48');
test(gcdOfStrings("LONGSTRINGLONGSTRINGLONGSTRING", "LONGSTRINGLONG"), , 'Test 49');
test(gcdOfStrings("SIMPLESIMPLESIMPLE", "SIMPLESIMPLE"), SIMPLE, 'Test 50');
test(gcdOfStrings("AAAAABBBB", "AAAAA"), , 'Test 51');
test(gcdOfStrings("SHORT", "VERYLONGSTRINGTHATISNOTAREPEAT"), , 'Test 52');
test(gcdOfStrings("AB", "BA"), , 'Test 53');
test(gcdOfStrings("PRIMEPRIMEPRIME", "PRIMEPRIME"), PRIME, 'Test 54');
test(gcdOfStrings("MNMNMNMNMNMN", "MNMN"), MNMN, 'Test 55');
test(gcdOfStrings("BEEBEEBEEBEEBEEBEEBEEBEE", "BEEBEEBEEBEE"), BEEBEEBEEBEE, 'Test 56');
test(gcdOfStrings("GRAPEGRAPEGRAPEGRAPEGRAPEGRAPE", "GRAPEGRAPEGRAPE"), GRAPEGRAPEGRAPE, 'Test 57');
test(gcdOfStrings("TIGERTIGERTIGERTIGERTIGERTIGER", "TIGERTIGERTIGER"), TIGERTIGERTIGER, 'Test 58');
test(gcdOfStrings("SCIENCE", "SCIENCE"), SCIENCE, 'Test 59');
test(gcdOfStrings("ABCDEFGABCDEFG", "ABCDEFG"), ABCDEFG, 'Test 60');
test(gcdOfStrings("XYZXYZXYZXYZXYZXYZXYZXYZ", "XYZXYZXYZ"), XYZ, 'Test 61');
test(gcdOfStrings("MIXEDMIXEDMIXEDMIXED", "MIXEDMIXED"), MIXEDMIXED, 'Test 62');
test(gcdOfStrings("ALMOSTSAMEALMOSTSAME", "ALMOSTSAME"), ALMOSTSAME, 'Test 63');
test(gcdOfStrings("APPLEAPPLEAPPLEAPPLEAPPLE", "APPLEAPPLEAPPLE"), APPLE, 'Test 64');
test(gcdOfStrings("MIXMIXMIXMIX", "MIXMIX"), MIXMIX, 'Test 65');
test(gcdOfStrings("MATHMATHMATHMATH", "MATH"), MATH, 'Test 66');
test(gcdOfStrings("SIMPLESIMPLESIMPLESIMPLE", "SIMPLE"), SIMPLE, 'Test 67');
test(gcdOfStrings("DUCKDUCKDUCKDUCKDUCKDUCKDUCKDUCK", "DUCKDUCKDUCKDUCK"), DUCKDUCKDUCKDUCK, 'Test 68');
test(gcdOfStrings("LONGLONGLONGLONGLONGLONG", "LONGLONGLONG"), LONGLONGLONG, 'Test 69');
test(gcdOfStrings("ZAZAZAZAZA", "ZAZA"), ZA, 'Test 70');
test(gcdOfStrings("AABAAABAAB", "AAB"), , 'Test 71');
test(gcdOfStrings("ABCDEFABCDEF", "ABCDEF"), ABCDEF, 'Test 72');
test(gcdOfStrings("PATTERNPATTERNPATTERN", "PATTERNPATTERN"), PATTERN, 'Test 73');
test(gcdOfStrings("UNIQUEUNIQUEUNIQUEUNIQUEUNIQUE", "UNIQUEUNIQUE"), UNIQUE, 'Test 74');
test(gcdOfStrings("A", ""), , 'Test 75');
test(gcdOfStrings("WOWOWOWOWOWO", "WOWOWO"), WOWOWO, 'Test 76');
test(gcdOfStrings("HELLOHELLOHELLOHELLO", "HELLOHELLOHELLO"), HELLO, 'Test 77');
test(gcdOfStrings("REPEATREPEATREPEATREPEATREPEAT", "REPEATREPEAT"), REPEAT, 'Test 78');
test(gcdOfStrings("IDENTICALIDENTICALIDENTICAL", "IDENTICALIDENTICAL"), IDENTICAL, 'Test 79');
test(gcdOfStrings("ABCDEFGABCDEFG", "DEFGABCD"), , 'Test 80');
test(gcdOfStrings("SAMESTRINGSAME", "SAME"), , 'Test 81');
test(gcdOfStrings("REPEATREPEATREPEAT", "REPEATREPEAT"), REPEAT, 'Test 82');
test(gcdOfStrings("QQQQQQQQQQ", "QQQQ"), QQ, 'Test 83');
test(gcdOfStrings("FAMILYFAMILYFAMILY", "FAMILYFAMILY"), FAMILY, 'Test 84');
test(gcdOfStrings("ABCABCABCABCABCABC", "ABCABCABC"), ABCABCABC, 'Test 85');
test(gcdOfStrings("", "A"), , 'Test 86');
test(gcdOfStrings("UNIQUEUNIQUEUNIQUEUNIQUE", "UNIQUEUNIQUE"), UNIQUEUNIQUE, 'Test 87');
test(gcdOfStrings("LONGSTRINGLONGSTRING", "LONGSTRING"), LONGSTRING, 'Test 88');
test(gcdOfStrings("UNIQUEUNIQUE", "UNIQUEUNIQUEUNIQUE"), UNIQUE, 'Test 89');
test(gcdOfStrings("MOUSEMOUSEMOUSEMOUSEMOUSEMOUSE", "MOUSEMOUSE"), MOUSEMOUSE, 'Test 90');
test(gcdOfStrings("ABABABABABAB", "ABAB"), ABAB, 'Test 91');
test(gcdOfStrings("HELLOWORLDHELLOWORLD", "HELLOWORLD"), HELLOWORLD, 'Test 92');
test(gcdOfStrings("ABCDABCD", "ABCDABCDABCD"), ABCD, 'Test 93');
test(gcdOfStrings("SAMESAMESAME", "SAME"), SAME, 'Test 94');
test(gcdOfStrings("QRSTQRSTQRST", "QRSTQRST"), QRST, 'Test 95');
test(gcdOfStrings("KARMAKARMAKARMAKARMA", "KARMAKARMA"), KARMAKARMA, 'Test 96');
test(gcdOfStrings("AAAAABAAAAAB", "AAAAAB"), AAAAAB, 'Test 97');
test(gcdOfStrings("TTT", "TTTTTTT"), T, 'Test 98');
test(gcdOfStrings("QQQQQQQQQQQQQQQQ", "QQQQ"), QQQQ, 'Test 99');
test(gcdOfStrings("AAAABBBBAAAABBBB", "AAAABBBB"), AAAABBBB, 'Test 100');
test(gcdOfStrings("QWQWQWQWQWQW", "QWQWQW"), QWQWQW, 'Test 101');
test(gcdOfStrings("PPPPPPPP", "PPPP"), PPPP, 'Test 102');
test(gcdOfStrings("SPAMSPAMSPAMSPAM", "SPAMSPAM"), SPAMSPAM, 'Test 103');
test(gcdOfStrings("PATTERNPATTERN", "PATTERN"), PATTERN, 'Test 104');
test(gcdOfStrings("XYZXYZXYZXYZXYZXYZ", "XYZXYZ"), XYZXYZ, 'Test 105');
test(gcdOfStrings("SCREENSCREENSCREENSCREEN", "SCREEN"), SCREEN, 'Test 106');
test(gcdOfStrings("PIZZAPIZZAPIZZAPIZZA", "PIZZAPIZZA"), PIZZAPIZZA, 'Test 107');
test(gcdOfStrings("ORANGEORANGEORANGEORANGEORANGEORANGEORANGEORANGE", "ORANGEORANGEORANGE"), ORANGE, 'Test 108');
test(gcdOfStrings("PRIMEPRIMEPRIMEPRIME", "PRIMEPRIME"), PRIMEPRIME, 'Test 109');
test(gcdOfStrings("REPEATREPEATREPEAT", "REPEAT"), REPEAT, 'Test 110');
test(gcdOfStrings("CODECODECODECODECODECODE", "CODECODECODE"), CODECODECODE, 'Test 111');
test(gcdOfStrings("PROJECTORPROJECTORPROJECTORPROJECTOR", "PROJECTORPROJECTOR"), PROJECTORPROJECTOR, 'Test 112');
test(gcdOfStrings("PYTHONPYTHONPYTHON", "PYTHONPYTHON"), PYTHON, 'Test 113');
test(gcdOfStrings("CCCCCCCCCCCCCC", "CCCCCCCCC"), C, 'Test 114');
test(gcdOfStrings("PQPQPQ", "PQPQPQPQPQ"), PQ, 'Test 115');
test(gcdOfStrings("DESKDESKDESKDESK", "DESK"), DESK, 'Test 116');
test(gcdOfStrings("GUITARGUITARGUITAR", "GUITAR"), GUITAR, 'Test 117');
test(gcdOfStrings("QWQWQWQWQW", "QWQWQW"), QW, 'Test 118');
test(gcdOfStrings("LONGLONGLONGLONGLONG", "LONGLONGLONG"), LONG, 'Test 119');
test(gcdOfStrings("DEVDEVDEVDEVDEV", "DEVDEV"), DEV, 'Test 120');
test(gcdOfStrings("UNIQUEUNIQUEUNIQUEUNIQUEUNIQUE", "UNIQUEUNIQUEUNIQUE"), UNIQUE, 'Test 121');
test(gcdOfStrings("TREETREETREETREE", "TREETREE"), TREETREE, 'Test 122');
test(gcdOfStrings("XYZXYZXYZXYZXYZXYZ", "XYZXYZXYZ"), XYZXYZXYZ, 'Test 123');
test(gcdOfStrings("HELLOHELLOHELLOHELLOHELLO", "HELLOHELLOHELLO"), HELLO, 'Test 124');
test(gcdOfStrings("SMALL", "SMALLSMALLSMALL"), SMALL, 'Test 125');
test(gcdOfStrings("MNMNMNMNMN", "MNMN"), MN, 'Test 126');
test(gcdOfStrings("ABCABCABCABC", "ABCABC"), ABCABC, 'Test 127');
test(gcdOfStrings("LONGERSTRINGLONGERSTRINGLONGERSTRING", "LONGERSTRINGLONGERSTRING"), LONGERSTRING, 'Test 128');
test(gcdOfStrings("PATTERNPATTERNPATTERNPATTERN", "PATTERNPATTERN"), PATTERNPATTERN, 'Test 129');
test(gcdOfStrings("HELLOHELLOHELLOHELLOHELLOHELLO", "HELLOHELLOHELLOHELLOHELLO"), HELLO, 'Test 130');
test(gcdOfStrings("DIFFERENTLENGTHS", "SOMEOTHERSTRING"), , 'Test 131');
test(gcdOfStrings("MIXEDUP", "MIXEDUPMIXEDUP"), MIXEDUP, 'Test 132');
test(gcdOfStrings("KEYBOARDKEYBOARDKEYBOARDKEYBOARD", "KEYBOARDKEYBOARD"), KEYBOARDKEYBOARD, 'Test 133');
test(gcdOfStrings("FLOWERFLOWERFLOWERFLOWER", "FLOWERFLOWER"), FLOWERFLOWER, 'Test 134');
test(gcdOfStrings("LONGSTRING", "LONGSTRINGLONGSTRING"), LONGSTRING, 'Test 135');
test(gcdOfStrings("SAMESTRINGSAMESTRINGSAMESTRING", "SAMESTRINGSAMESTRING"), SAMESTRING, 'Test 136');
test(gcdOfStrings("NONONONONONO", "NONO"), NONO, 'Test 137');
test(gcdOfStrings("ABCDABCDABCDABCD", "ABCDABCD"), ABCDABCD, 'Test 138');
test(gcdOfStrings("TESTTESTTESTTEST", "TESTTEST"), TESTTEST, 'Test 139');
test(gcdOfStrings("SAMELENGTH", "DIFFERENT"), , 'Test 140');
test(gcdOfStrings("HELLOHELLOHELLO", "HELLOHELLO"), HELLO, 'Test 141');
test(gcdOfStrings("DOGDOGDOGDOGDOG", "DOGDOG"), DOG, 'Test 142');
test(gcdOfStrings("CATCATCATCATCAT", "CATCAT"), CAT, 'Test 143');
test(gcdOfStrings("ABABABABAB", "ABAB"), AB, 'Test 144');
test(gcdOfStrings("LONGLONGLONGLONG", "LONG"), LONG, 'Test 145');
test(gcdOfStrings("COMPUTERCOMPUTERCOMPUTER", "COMPUTER"), COMPUTER, 'Test 146');
test(gcdOfStrings("RUBYRUBYRUBYRUBY", "RUBYRUBY"), RUBYRUBY, 'Test 147');
test(gcdOfStrings("BEEBEEBEEBEEBEE", "BEEBEE"), BEE, 'Test 148');
test(gcdOfStrings("ABABABABABAB", "ABABAB"), ABABAB, 'Test 149');
test(gcdOfStrings("BIGBIGBIGBIG", "BIG"), BIG, 'Test 150');
test(gcdOfStrings("APPLEAPPLEAPPLEAPPLEAPPLEAPPLE", "APPLEAPPLEAPPLE"), APPLEAPPLEAPPLE, 'Test 151');
test(gcdOfStrings("AABBCCDDEEFF", "AABBCCDD"), , 'Test 152');
test(gcdOfStrings("UVUVUVUVUVUV", "UVUVUV"), UVUVUV, 'Test 153');
test(gcdOfStrings("PPPPPPPPPP", "PPPP"), PP, 'Test 154');
test(gcdOfStrings("TESTTESTTESTTEST", "TESTTESTTEST"), TEST, 'Test 155');
test(gcdOfStrings("AABBCCDDEE", "AABBCC"), , 'Test 156');
test(gcdOfStrings("MIXMIXMIXMIXMIX", "MIXMIX"), MIX, 'Test 157');
test(gcdOfStrings("PYTHONPYTHONPYTHONPYTHON", "PYTHONPYTHON"), PYTHONPYTHON, 'Test 158');
test(gcdOfStrings("", ""), , 'Test 159');
test(gcdOfStrings("PYTHONPYTHONPYTHONPYTHONPYTHON", "PYTHONPYTHON"), PYTHON, 'Test 160');
test(gcdOfStrings("AABBCCAABBCC", "AABBCC"), AABBCC, 'Test 161');
test(gcdOfStrings("LIONLIONLIONLIONLIONLION", "LIONLIONLION"), LIONLIONLION, 'Test 162');
test(gcdOfStrings("ABCDEFGABCDEFGABCDEFG", "ABCDEFGABCDEFG"), ABCDEFG, 'Test 163');
test(gcdOfStrings("MICROPHONEMICROPHONEMICROPHONE", "MICROPHONE"), MICROPHONE, 'Test 164');
test(gcdOfStrings("ABABABABABABABAB", "ABABAB"), AB, 'Test 165');
test(gcdOfStrings("XYZXYZXYZXYZ", "XYZXYZ"), XYZXYZ, 'Test 166');
test(gcdOfStrings("HEADPHONESHEADPHONES", "HEADPHONESHEADPHONES"), HEADPHONESHEADPHONES, 'Test 167');
test(gcdOfStrings("ABCDEFGHABCDEFGHABCDEFGH", "ABCDEFGHABCDEFGH"), ABCDEFGH, 'Test 168');
test(gcdOfStrings("SPEAKERSPEAKERSPEAKERSPEAKERSPEAKER", "SPEAKERSPEAKER"), SPEAKER, 'Test 169');
test(gcdOfStrings("DIVIDEDIVIDE", "DIVIDE"), DIVIDE, 'Test 170');
test(gcdOfStrings("JSJSJSJSJSJSJS", "JSJSJSJS"), JS, 'Test 171');
test(gcdOfStrings("CATCATCATCATCATCAT", "CATCATCAT"), CATCATCAT, 'Test 172');
test(gcdOfStrings("NOTCOMMONNOTCOMMONNOTCOMMON", "NOTCOMMONNOT"), , 'Test 173');
test(gcdOfStrings("XZXZXZXZXZ", "XZXZ"), XZ, 'Test 174');
test(gcdOfStrings("DOGDOGDOGDOGDOGDOGDOGDOGDOGDOG", "DOGDOGDOGDOG"), DOGDOG, 'Test 175');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

