// Test: 1859. Sorting The Sentence
// 145 test cases from LeetCodeDataset
// Run: node test.js

const { sortSentence } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1859. Sorting The Sentence\n");

test(sortSentence("eight8 seven7 six6 five5 four4 three3 two2 one1"), one two three four five six seven eight, 'Test 1');
test(sortSentence("seven7 six6 five5 four4 three3 two2 one1"), one two three four five six seven, 'Test 2');
test(sortSentence("nine9 eight8 seven7 six6 five5 four4 three3 two2 one1"), one two three four five six seven eight nine, 'Test 3');
test(sortSentence("three3 two2 one1"), one two three, 'Test 4');
test(sortSentence("is2 sentence4 This1 a3"), This is a sentence, 'Test 5');
test(sortSentence("five5 four4 three3 two2 one1"), one two three four five, 'Test 6');
test(sortSentence("A9 B8 C7 D6 E5 F4 G3 H2 I1"), I H G F E D C B A, 'Test 7');
test(sortSentence("Myself2 Me1 I4 and3"), Me Myself and I, 'Test 8');
test(sortSentence("nine9 eight8 seven7 six6 five5 four4 three3 two2 one1 zero0"), one two three four five six seven eight nine zero, 'Test 9');
test(sortSentence("six6 five5 four4 three3 two2 one1"), one two three four five six, 'Test 10');
test(sortSentence("one1"), one, 'Test 11');
test(sortSentence("two1 one2"), two one, 'Test 12');
test(sortSentence("four4 three3 two2 one1"), one two three four, 'Test 13');
test(sortSentence("Data6 Science7 Is2 Important1 Fascinating4"), Error: list assignment index out of range, 'Test 14');
test(sortSentence("Deep2 Learning3 For1 Beginners5"), Error: list assignment index out of range, 'Test 15');
test(sortSentence("quick5 brown3 fox2 jumps9 over8 lazy4 the7 dog6 a1"), a fox brown lazy quick dog the over jumps, 'Test 16');
test(sortSentence("Wave7 Energy6"), Error: list assignment index out of range, 'Test 17');
test(sortSentence("Quick5 brown4 fox3 jumps2 over1"), over jumps fox brown Quick, 'Test 18');
test(sortSentence("big2 bigger3 biggest1"), biggest big bigger, 'Test 19');
test(sortSentence("Sustainable1 Energy"), Error: invalid literal for int[] with base 10: 'y', 'Test 20');
test(sortSentence("Python5 is4 the2 best1 language6"), Error: list assignment index out of range, 'Test 21');
test(sortSentence("order10 words9 in8 correct7 sequence6 is5 important4 for3 understanding2 this1"), this understanding for important is sequence correct in words order1, 'Test 22');
test(sortSentence("Algorithms8 are2 very3 interesting7 indeed9"), Error: list assignment index out of range, 'Test 23');
test(sortSentence("Tensor5 Flow4 PyTorch3"), Error: list assignment index out of range, 'Test 24');
test(sortSentence("Python9 Java3 C1 Cpp4 Go5 Rust8"), Error: list assignment index out of range, 'Test 25');
test(sortSentence("Artificial5 Intelligence4 Development3 Engaging2"), Error: list assignment index out of range, 'Test 26');
test(sortSentence("Hydro3 Power2"), Error: list assignment index out of range, 'Test 27');
test(sortSentence("last9 first1 middle5"), Error: list assignment index out of range, 'Test 28');
test(sortSentence("alpha9 beta8 gamma7 delta6 epsilon5"), Error: list assignment index out of range, 'Test 29');
test(sortSentence("Metaverse9"), Error: list assignment index out of range, 'Test 30');
test(sortSentence("a1 bc2 def3 ghij4 klmno5 pqrstu6 vwxyz7 abcdefg8 hijklmno9"), a bc def ghij klmno pqrstu vwxyz abcdefg hijklmno, 'Test 31');
test(sortSentence("Cybersecurity9 Challenges8"), Error: list assignment index out of range, 'Test 32');
test(sortSentence("Quantum7 Computing6"), Error: list assignment index out of range, 'Test 33');
test(sortSentence("Python7 coding6 is4 fun1 today9"), Error: list assignment index out of range, 'Test 34');
test(sortSentence("Extended4 Reality3"), Error: list assignment index out of range, 'Test 35');
test(sortSentence("Serverless7 Computing6"), Error: list assignment index out of range, 'Test 36');
test(sortSentence("Innovate8 Continuously6 To2 Be5 The1 Best9"), Error: list assignment index out of range, 'Test 37');
test(sortSentence("abc1 def2 ghi3 jkl4 mno5 pqr6 stu7 vwx8 yza9"), abc def ghi jkl mno pqr stu vwx yza, 'Test 38');
test(sortSentence("Carbon9 Footprint8"), Error: list assignment index out of range, 'Test 39');
test(sortSentence("nested10 structures9 are8 not7 supported6 in5 this4 problem3 but2 lets1 try"), Error: invalid literal for int[] with base 10: 'y', 'Test 40');
test(sortSentence("Quick5 brown4 fox3 jumps9 over2 lazy8 the1"), Error: list assignment index out of range, 'Test 41');
test(sortSentence("Data2 Science1"), Science Data, 'Test 42');
test(sortSentence("alpha10 beta9 gamma8 delta7 epsilon6 zeta5 eta4 theta3 iota2 kappa1"), kappa iota theta eta zeta epsilon delta gamma beta alpha1, 'Test 43');
test(sortSentence("Quick5 Brown4 Fox3 Jumps2 Over1"), Over Jumps Fox Brown Quick, 'Test 44');
test(sortSentence("Digital2 Transformation1"), Transformation Digital, 'Test 45');
test(sortSentence("Cryptocurrency7 Investing6"), Error: list assignment index out of range, 'Test 46');
test(sortSentence("Of6 Things5"), Error: list assignment index out of range, 'Test 47');
test(sortSentence("zebra9 yellow8 xenon7 winter6 volcano5 umbrella4 tornado3 storm2 rainbow1"), rainbow storm tornado umbrella volcano winter xenon yellow zebra, 'Test 48');
test(sortSentence("Climate5 Change4"), Error: list assignment index out of range, 'Test 49');
test(sortSentence("short1 longerWord2 evenLongerWord3"), short longerWord evenLongerWord, 'Test 50');
test(sortSentence("one9 two8 three7 four6 five5 six4 seven3 eight2 nine1"), nine eight seven six five four three two one, 'Test 51');
test(sortSentence("Ethereum5 Wallet4"), Error: list assignment index out of range, 'Test 52');
test(sortSentence("apple8 banana7 cherry6 date5 elderberry4 fig3 grape2 huckleberry1"), huckleberry grape fig elderberry date cherry banana apple, 'Test 53');
test(sortSentence("apple9 banana8 cherry7 date6 elderberry5 fig4 grape3 honeydew2 ice1"), ice honeydew grape fig elderberry date cherry banana apple, 'Test 54');
test(sortSentence("MixedCASE1 Word2 with3 DIFFERENT4 cases5"), MixedCASE Word with DIFFERENT cases, 'Test 55');
test(sortSentence("Python1 is2 great3"), Python is great, 'Test 56');
test(sortSentence("a9 b8 c7 d6 e5 f4 g3 h2 i1"), i h g f e d c b a, 'Test 57');
test(sortSentence("Virtual8 Reality7"), Error: list assignment index out of range, 'Test 58');
test(sortSentence("single1"), single, 'Test 59');
test(sortSentence("one1 two2 three3 four4 five5 six6 seven7 eight8 nine9"), one two three four five six seven eight nine, 'Test 60');
test(sortSentence("Edge9 cases8 need7 special6 handling5 and4 attention3"), Error: list assignment index out of range, 'Test 61');
test(sortSentence("DevSecOps8 Practices7"), Error: list assignment index out of range, 'Test 62');
test(sortSentence("Machine9 Learning8 Algorithms7"), Error: list assignment index out of range, 'Test 63');
test(sortSentence("Emission7 Reduction6"), Error: list assignment index out of range, 'Test 64');
test(sortSentence("reverse9 order8 words7 in6 a5 sentence4 for3 testing2 purposes1"), purposes testing for sentence a in words order reverse, 'Test 65');
test(sortSentence("Solar7 Power6"), Error: list assignment index out of range, 'Test 66');
test(sortSentence("Big5 Data4 Analytics3"), Error: list assignment index out of range, 'Test 67');
test(sortSentence("sun8 moon7 stars6 galaxy5 universe4 planets3 asteroid2 comet1"), comet asteroid planets universe galaxy stars moon sun, 'Test 68');
test(sortSentence("only1 word"), Error: invalid literal for int[] with base 10: 'd', 'Test 69');
test(sortSentence("two2 one1 three3 four4 five5 six6 seven7 eight8 nine9"), one two three four five six seven eight nine, 'Test 70');
test(sortSentence("Autonomous5 Vehicles4"), Error: list assignment index out of range, 'Test 71');
test(sortSentence("complex1 testing2 cases3 with4 multiple5 digits6 and7 shuffled8 order9"), complex testing cases with multiple digits and shuffled order, 'Test 72');
test(sortSentence("Quick5 brown4 fox1 jumps9 over3 lazy2"), Error: list assignment index out of range, 'Test 73');
test(sortSentence("Sustainability1"), Sustainability, 'Test 74');
test(sortSentence("same1 same1 same1 same1 same1"), Error: sequence item 1: expected str instance, nullType found, 'Test 75');
test(sortSentence("Robotics7"), Error: list assignment index out of range, 'Test 76');
test(sortSentence("Tidal5 Energy4"), Error: list assignment index out of range, 'Test 77');
test(sortSentence("Hard2 Work3 Makes1 Success4"), Makes Hard Work Success, 'Test 78');
test(sortSentence("Edge3 Computing2"), Error: list assignment index out of range, 'Test 79');
test(sortSentence("Fog1 Computing"), Error: invalid literal for int[] with base 10: 'g', 'Test 80');
test(sortSentence("Alibaba2 Cloud3 Is1 Amazing5"), Error: list assignment index out of range, 'Test 81');
test(sortSentence("A5 B4 C3 D2 E1 F6 G7 H8 I9"), E D C B A F G H I, 'Test 82');
test(sortSentence("Alphabetically9 Better8 Christmas7 Does6 Everyone5 Feel4 Good3 Happy2 Indeed1"), Indeed Happy Good Feel Everyone Does Christmas Better Alphabetically, 'Test 83');
test(sortSentence("sun9 moon8 star7 planet6 comet5 asteroid4 meteor3 satellite2 galaxy1"), galaxy satellite meteor asteroid comet planet star moon sun, 'Test 84');
test(sortSentence("The9 quick8 brown7 fox6 jumps5 over4 lazy3 dog2 one1"), one dog lazy over jumps fox brown quick The, 'Test 85');
test(sortSentence("handle1 edge2 cases3 like4 when5 the6 number7 of8 digits9 is9 exactly9"), Error: sequence item 9: expected str instance, nullType found, 'Test 86');
test(sortSentence("short6 longer5 very4 much3 more2 words1"), words more much very longer short, 'Test 87');
test(sortSentence("first1 second2 third3 fourth4 fifth5 sixth6 seventh7 eighth8 ninth9"), first second third fourth fifth sixth seventh eighth ninth, 'Test 88');
test(sortSentence("Two2 Words1"), Words Two, 'Test 89');
test(sortSentence("Continuous5 Deployment4 Integration3"), Error: list assignment index out of range, 'Test 90');
test(sortSentence("Understanding9 Neural8 Networks7"), Error: list assignment index out of range, 'Test 91');
test(sortSentence("Complicated1 Sorting2 becomes3 significantly4 more5 challenging6 when7 words8 overlap9"), Complicated Sorting becomes significantly more challenging when words overlap, 'Test 92');
test(sortSentence("Python10 Java9 C8 Cpp7 Rust6 Go5 Ruby4 Swift3 Kotlin2 TypeScript1"), TypeScript Kotlin Swift Ruby Go Rust Cpp C Java Python1, 'Test 93');
test(sortSentence("zZ9 yY8 xX7 wW6 vV5 uU4 tT3 sS2 rR1"), rR sS tT uU vV wW xX yY zZ, 'Test 94');
test(sortSentence("AI4 Ethics3"), Error: list assignment index out of range, 'Test 95');
test(sortSentence("Geothermal1 Energy"), Error: invalid literal for int[] with base 10: 'y', 'Test 96');
test(sortSentence("Complex9 Sentences6 with5 various4 lengths3 can2 be1"), Error: list assignment index out of range, 'Test 97');
test(sortSentence("Kubernetes8 Docker7 For2 DevOps3"), Error: list assignment index out of range, 'Test 98');
test(sortSentence("A9 lot8 of7 testing6 needs5 to4 be3 done2 always1"), always done be to needs testing of lot A, 'Test 99');
test(sortSentence("z9 y8 x7 w6 v5 u4 t3 s2 r1"), r s t u v w x y z, 'Test 100');
test(sortSentence("hello9 world8 how7 are6 you5 I4 am3"), Error: list assignment index out of range, 'Test 101');
test(sortSentence("IoT8 Internet7"), Error: list assignment index out of range, 'Test 102');
test(sortSentence("Cloud4 Native3"), Error: list assignment index out of range, 'Test 103');
test(sortSentence("random4 words7 in2 different1 order5"), Error: list assignment index out of range, 'Test 104');
test(sortSentence("Blockchain9 Technology8"), Error: list assignment index out of range, 'Test 105');
test(sortSentence("twoWords2 oneWord1"), oneWord twoWords, 'Test 106');
test(sortSentence("ab9 cd8 ef7 gh6 ij5 kl4 mn3 op2 qr1"), qr op mn kl ij gh ef cd ab, 'Test 107');
test(sortSentence("Open3 Source2 Software1"), Software Source Open, 'Test 108');
test(sortSentence("Python9 Is8 Great7 Language6"), Error: list assignment index out of range, 'Test 109');
test(sortSentence("a9 quick8 brown7 fox6 jumps5 over4 lazy3 dogs2 one1"), one dogs lazy over jumps fox brown quick a, 'Test 110');
test(sortSentence("Fossil1 Fuels"), Error: invalid literal for int[] with base 10: 's', 'Test 111');
test(sortSentence("Quick5 brown3 fox1 jumps9 over4 lazy2"), Error: list assignment index out of range, 'Test 112');
test(sortSentence("Biomass9 Energy8"), Error: list assignment index out of range, 'Test 113');
test(sortSentence("Automation6"), Error: list assignment index out of range, 'Test 114');
test(sortSentence("Global3 Warming2"), Error: list assignment index out of range, 'Test 115');
test(sortSentence("NFTs5"), Error: list assignment index out of range, 'Test 116');
test(sortSentence("Digital9 Twin8"), Error: list assignment index out of range, 'Test 117');
test(sortSentence("aA9 bB8 cC7 dD6 eE5 fF4 gG3 hH2 iI1"), iI hH gG fF eE dD cC bB aA, 'Test 118');
test(sortSentence("shuffle7 sentence6 original5 reconstruct4 and3 a2 is1"), is a and reconstruct original sentence shuffle, 'Test 119');
test(sortSentence("Microservices9 Architecture8 Design7"), Error: list assignment index out of range, 'Test 120');
test(sortSentence("shuffle9 words8 correctly7 to6 get5 the4 right3 order2 one1"), one order right the get to correctly words shuffle, 'Test 121');
test(sortSentence("5G4"), Error: list assignment index out of range, 'Test 122');
test(sortSentence("HELLO1 woRLD2"), HELLO woRLD, 'Test 123');
test(sortSentence("Short1 words2 can3 also4 be5 tricky6"), Short words can also be tricky, 'Test 124');
test(sortSentence("Renewable9 Energy8"), Error: list assignment index out of range, 'Test 125');
test(sortSentence("Python3 Java2 C1 Ruby4 Go5"), C Java Python Ruby Go, 'Test 126');
test(sortSentence("Electric3 Cars2"), Error: list assignment index out of range, 'Test 127');
test(sortSentence("mixed8 case7 word6 CASE5 Mixed4 CASE3 mixed2 CASE1"), CASE mixed CASE Mixed CASE word case mixed, 'Test 128');
test(sortSentence("Decentralized8 Finance7"), Error: list assignment index out of range, 'Test 129');
test(sortSentence("Python3 Java2 C1"), C Java Python, 'Test 130');
test(sortSentence("Quick5 brown4 fox3 jumps9 over2 lazy1 dog8"), Error: list assignment index out of range, 'Test 131');
test(sortSentence("This8 is7 a6 sample5 sentence4 with3 various2 words1"), words various with sentence sample a is This, 'Test 132');
test(sortSentence("ninja9 samurai8 katana7 wakizashi6 tanto5 yoroi4 kusarigama3 tsurugi2 ninja1"), ninja tsurugi kusarigama yoroi tanto wakizashi katana samurai ninja, 'Test 133');
test(sortSentence("This9 Sentence8 Is7 Very6 Complex5 Indeed4"), Error: list assignment index out of range, 'Test 134');
test(sortSentence("Nuclear3 Energy2"), Error: list assignment index out of range, 'Test 135');
test(sortSentence("Augmented6 Reality5"), Error: list assignment index out of range, 'Test 136');
test(sortSentence("Alibaba9 Cloud7 is3 amazing8 an2 excellent1 offering6"), Error: list assignment index out of range, 'Test 137');
test(sortSentence("quick5 brown4 fox3 jumps9 over2 lazy1 dog8"), Error: list assignment index out of range, 'Test 138');
test(sortSentence("alpha9 beta8 gamma7 delta6 epsilon5 zeta4 eta3 theta2 iota1"), iota theta eta zeta epsilon delta gamma beta alpha, 'Test 139');
test(sortSentence("zebra9 yak8 xenon7 wolf6 vulture5 unicorn4 tiger3 snake2 rabbit1"), rabbit snake tiger unicorn vulture wolf xenon yak zebra, 'Test 140');
test(sortSentence("repeated1 same2 numbers3 in4 different5 words6 should7 not8 be9 valid10"), repeated same numbers in different words should not be valid1, 'Test 141');
test(sortSentence("reverse9 order8 words7 in6 this5 shuffled4 sentence3 into2 proper1"), proper into sentence shuffled this in words order reverse, 'Test 142');
test(sortSentence("Single1"), Single, 'Test 143');
test(sortSentence("Wind5 Energy4"), Error: list assignment index out of range, 'Test 144');
test(sortSentence("Smart3 Contracts2"), Error: list assignment index out of range, 'Test 145');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

