// Test: 3120. Count The Number Of Special Characters I
// 159 test cases from LeetCodeDataset
// Run: node test.js

const { numberOfSpecialChars } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n3120. Count The Number Of Special Characters I\n");

test(numberOfSpecialChars("abc"), 0, 'Test 1');
test(numberOfSpecialChars("xyzXYZ"), 3, 'Test 2');
test(numberOfSpecialChars("aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ"), 26, 'Test 3');
test(numberOfSpecialChars("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"), 26, 'Test 4');
test(numberOfSpecialChars("aabbcc"), 0, 'Test 5');
test(numberOfSpecialChars("AABBCC"), 0, 'Test 6');
test(numberOfSpecialChars("cCcCc"), 1, 'Test 7');
test(numberOfSpecialChars("AaBbCc"), 3, 'Test 8');
test(numberOfSpecialChars("abBCab"), 1, 'Test 9');
test(numberOfSpecialChars("AbCdEfGhIjKlMnOpQrStUvWxYz"), 0, 'Test 10');
test(numberOfSpecialChars("XyZxYz"), 3, 'Test 11');
test(numberOfSpecialChars("a"), 0, 'Test 12');
test(numberOfSpecialChars("A"), 0, 'Test 13');
test(numberOfSpecialChars("aaAbcBC"), 3, 'Test 14');
test(numberOfSpecialChars("bBbB"), 1, 'Test 15');
test(numberOfSpecialChars("aA"), 1, 'Test 16');
test(numberOfSpecialChars(""), 0, 'Test 17');
test(numberOfSpecialChars("MixedCASEwithSPECIALSspecial"), 7, 'Test 18');
test(numberOfSpecialChars("nestedLoopNESTED"), 5, 'Test 19');
test(numberOfSpecialChars("kKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkKkK"), 1, 'Test 20');
test(numberOfSpecialChars("LongStringWithNoSpecials"), 3, 'Test 21');
test(numberOfSpecialChars("vVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvVvV"), 1, 'Test 22');
test(numberOfSpecialChars("abcdefABCDEF"), 6, 'Test 23');
test(numberOfSpecialChars("SpecialLettersTest"), 3, 'Test 24');
test(numberOfSpecialChars("MixedCASEwithSpecials"), 4, 'Test 25');
test(numberOfSpecialChars("UniqueSpecialsABCDabcd"), 6, 'Test 26');
test(numberOfSpecialChars("aaaaBBBBccccDDDDeeeeFFFFggggHHHHiiiiJJJjkkkkLLLLmmmmNNNNooooPPPqqqqRRRRssssTTTTuuuuVVVVwwwwXXXXyyyyZZZZ"), 1, 'Test 27');
test(numberOfSpecialChars("eEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEe"), 1, 'Test 28');
test(numberOfSpecialChars("aAbBcC"), 3, 'Test 29');
test(numberOfSpecialChars("aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA"), 1, 'Test 30');
test(numberOfSpecialChars("abcABC"), 3, 'Test 31');
test(numberOfSpecialChars("abcdefGHIJKLmnopQRstUVWxyz"), 0, 'Test 32');
test(numberOfSpecialChars("Python3.8"), 0, 'Test 33');
test(numberOfSpecialChars("aAbBC"), 2, 'Test 34');
test(numberOfSpecialChars("worldWORLD"), 5, 'Test 35');
test(numberOfSpecialChars("xylophoneXYZ"), 2, 'Test 36');
test(numberOfSpecialChars("aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ"), 26, 'Test 37');
test(numberOfSpecialChars("qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM"), 26, 'Test 38');
test(numberOfSpecialChars("nestedCASECASEnested"), 2, 'Test 39');
test(numberOfSpecialChars("aAaAaAaAaAaAaAaAaAaA"), 1, 'Test 40');
test(numberOfSpecialChars("SpecialsAllOverAaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz"), 26, 'Test 41');
test(numberOfSpecialChars("AbCdefGhIjkLmnopQrstUVwXyZ"), 0, 'Test 42');
test(numberOfSpecialChars("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"), 26, 'Test 43');
test(numberOfSpecialChars("aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA"), 1, 'Test 44');
test(numberOfSpecialChars("UPPERlower"), 2, 'Test 45');
test(numberOfSpecialChars("zZyYxXwWvVuUtTsSrRpPoOnNmMlLkKjJiIhHgGfFeEdDcCbBaA"), 25, 'Test 46');
test(numberOfSpecialChars("NoSpecial"), 0, 'Test 47');
test(numberOfSpecialChars("SpecialCharacters123"), 2, 'Test 48');
test(numberOfSpecialChars("OneSpecialA"), 1, 'Test 49');
test(numberOfSpecialChars("SingleSpeciala"), 0, 'Test 50');
test(numberOfSpecialChars("AbcDeEfGhIjKlMnOpQrStUvWxYz"), 1, 'Test 51');
test(numberOfSpecialChars("helloHELLO"), 4, 'Test 52');
test(numberOfSpecialChars("HelloWorld"), 0, 'Test 53');
test(numberOfSpecialChars("MultipleUUppercases"), 1, 'Test 54');
test(numberOfSpecialChars("wWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWwW"), 1, 'Test 55');
test(numberOfSpecialChars("yYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyYyY"), 1, 'Test 56');
test(numberOfSpecialChars("AbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYz"), 0, 'Test 57');
test(numberOfSpecialChars("TrailingSpecialsAaBbCc"), 4, 'Test 58');
test(numberOfSpecialChars("abcABCabcABCabcABC"), 3, 'Test 59');
test(numberOfSpecialChars("JustOneSpecialCharacterb"), 2, 'Test 60');
test(numberOfSpecialChars("iIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiI"), 1, 'Test 61');
test(numberOfSpecialChars("noSpecial"), 0, 'Test 62');
test(numberOfSpecialChars("NoSpecialCharacters"), 2, 'Test 63');
test(numberOfSpecialChars("SpecialCharacters"), 2, 'Test 64');
test(numberOfSpecialChars("lowerCASEuppercase"), 4, 'Test 65');
test(numberOfSpecialChars("UniqueUniqueUniqueUnique"), 1, 'Test 66');
test(numberOfSpecialChars("CASEsensitive"), 2, 'Test 67');
test(numberOfSpecialChars("OneSpecialAa"), 1, 'Test 68');
test(numberOfSpecialChars("SingleSpecialA"), 1, 'Test 69');
test(numberOfSpecialChars("jJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJjJ"), 1, 'Test 70');
test(numberOfSpecialChars("bBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbB"), 1, 'Test 71');
test(numberOfSpecialChars("aabbCCddeeffGGhhiiJJkkllMMnnooppQQrrssttuuVVwwxxyyzz"), 0, 'Test 72');
test(numberOfSpecialChars("MultipleMultipleMultiple"), 0, 'Test 73');
test(numberOfSpecialChars("ComplexMixAaBbCc123!@#AaBbCc"), 4, 'Test 74');
test(numberOfSpecialChars("TestCase"), 1, 'Test 75');
test(numberOfSpecialChars("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzAaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz"), 26, 'Test 76');
test(numberOfSpecialChars("mMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmMmM"), 1, 'Test 77');
test(numberOfSpecialChars("NestedSpecialsAaBBbbCCcc"), 4, 'Test 78');
test(numberOfSpecialChars("fFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFfFf"), 1, 'Test 79');
test(numberOfSpecialChars("lLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlL"), 1, 'Test 80');
test(numberOfSpecialChars("tTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtTtT"), 1, 'Test 81');
test(numberOfSpecialChars("abcdEFGHijKLMnopQRSTuvWXyz"), 0, 'Test 82');
test(numberOfSpecialChars("JustOneAa"), 1, 'Test 83');
test(numberOfSpecialChars("nNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnNnN"), 1, 'Test 84');
test(numberOfSpecialChars("StartingWithSpecialsAaBbCc"), 4, 'Test 85');
test(numberOfSpecialChars("uniqueUnique"), 1, 'Test 86');
test(numberOfSpecialChars("gGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgG"), 1, 'Test 87');
test(numberOfSpecialChars("xXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX"), 1, 'Test 88');
test(numberOfSpecialChars("AaAaAaAaAaBbBbBbBbCcCcCcCcDdDdDdDdEeEeEeEeFfFfFfFfGgGgGgGgHhHhHhHhIiIiIiIiJjJjJjJjKkKkKkKkLlLlLlLlMmMmMmMmNnNnNnNnOoOoOoOoPpPpPpPpQqQqQqQqRrRrRrRrSsSsSsSsTtTtTtTtUuUuUuUuVvVvVvVvWwWwWwWwXxXxXxXxYyYyYyYyZzZzZzZz"), 26, 'Test 89');
test(numberOfSpecialChars("specialCharSPECIAL"), 7, 'Test 90');
test(numberOfSpecialChars("hHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhHhH"), 1, 'Test 91');
test(numberOfSpecialChars("AlphabetSoup"), 1, 'Test 92');
test(numberOfSpecialChars("AaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAa"), 1, 'Test 93');
test(numberOfSpecialChars("RepeatRepeatREPEAT"), 4, 'Test 94');
test(numberOfSpecialChars("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"), 1, 'Test 95');
test(numberOfSpecialChars("pPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpPpP"), 1, 'Test 96');
test(numberOfSpecialChars("aA1Bb2Cc3Dd4Ee5Ff6Gg7Hh8Ii9Jj0"), 10, 'Test 97');
test(numberOfSpecialChars("specialCharacters"), 1, 'Test 98');
test(numberOfSpecialChars("sSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSsS"), 1, 'Test 99');
test(numberOfSpecialChars("aAaAaA"), 1, 'Test 100');
test(numberOfSpecialChars("JustOneZz"), 1, 'Test 101');
test(numberOfSpecialChars("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzAaBbCc"), 26, 'Test 102');
test(numberOfSpecialChars("Zebra"), 0, 'Test 103');
test(numberOfSpecialChars("EndingWithSpecialsAaBbCc"), 5, 'Test 104');
test(numberOfSpecialChars("aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZ"), 0, 'Test 105');
test(numberOfSpecialChars("bbbbbbbbBBBBBBB"), 1, 'Test 106');
test(numberOfSpecialChars("RePeAtInGChaRaCtErS"), 3, 'Test 107');
test(numberOfSpecialChars("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzABCD"), 4, 'Test 108');
test(numberOfSpecialChars("AaBbCc1234567890!@#$%^&*[]"), 3, 'Test 109');
test(numberOfSpecialChars("repeatedCHARactersCHARacters"), 3, 'Test 110');
test(numberOfSpecialChars("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzabcdefghijklmnopqrstuvwxyz"), 26, 'Test 111');
test(numberOfSpecialChars("UniqueCASE"), 2, 'Test 112');
test(numberOfSpecialChars("doubleDOUBLEtrouble"), 6, 'Test 113');
test(numberOfSpecialChars("PythonIsAwesome"), 0, 'Test 114');
test(numberOfSpecialChars("MixedCASE123"), 1, 'Test 115');
test(numberOfSpecialChars("QwErTyUiOpAsDfGhJkLzXcVbNm"), 0, 'Test 116');
test(numberOfSpecialChars("rRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrR"), 1, 'Test 117');
test(numberOfSpecialChars("abCDefGHijKLmnopQRstUVwxYZ"), 0, 'Test 118');
test(numberOfSpecialChars("abcABCdefDEFghiGHI"), 9, 'Test 119');
test(numberOfSpecialChars("pythonPYTHON"), 6, 'Test 120');
test(numberOfSpecialChars("OverlapOverlap"), 0, 'Test 121');
test(numberOfSpecialChars("aBcDeFgHiJkLmNoPqRsTuVwXyZ"), 0, 'Test 122');
test(numberOfSpecialChars("CASEcase"), 4, 'Test 123');
test(numberOfSpecialChars("testCaseTestCase"), 1, 'Test 124');
test(numberOfSpecialChars("specialCHARSareHERE"), 5, 'Test 125');
test(numberOfSpecialChars("SingleSpecialAa"), 1, 'Test 126');
test(numberOfSpecialChars("qQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQqQ"), 1, 'Test 127');
test(numberOfSpecialChars("aaBBccDDeeFFggHHiiJJkkLLmmNNooPPqqRRssTTuuVVwwXXyyZZ"), 0, 'Test 128');
test(numberOfSpecialChars("dDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd"), 1, 'Test 129');
test(numberOfSpecialChars("SsEeCcIiAaLlTtCcHaArAcCtTeErsRsS"), 8, 'Test 130');
test(numberOfSpecialChars("JustOneSpecialCharacterB"), 2, 'Test 131');
test(numberOfSpecialChars("bBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbB"), 1, 'Test 132');
test(numberOfSpecialChars("aAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAa"), 1, 'Test 133');
test(numberOfSpecialChars("NoRepeatsJustSpecialsAaBbCc"), 4, 'Test 134');
test(numberOfSpecialChars("MiXeDcAsEwItHiSmOvEs"), 4, 'Test 135');
test(numberOfSpecialChars("HelloWORLD"), 2, 'Test 136');
test(numberOfSpecialChars("SpecialCharactersTEST"), 4, 'Test 137');
test(numberOfSpecialChars("ZzYyXxWwVvUuTtSsRrQqPpOoNnMmLlKkJjIiHhGgFfEeDdCcBbAa"), 26, 'Test 138');
test(numberOfSpecialChars("oOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoOoO"), 1, 'Test 139');
test(numberOfSpecialChars("SpecialCHARacters"), 4, 'Test 140');
test(numberOfSpecialChars("zZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZzZ"), 1, 'Test 141');
test(numberOfSpecialChars("MultiplELowercases"), 2, 'Test 142');
test(numberOfSpecialChars("AabbCCddeEFFgghhIIjjKKllMMnnooppQQrrSsttUuvvWwXxyyZz"), 7, 'Test 143');
test(numberOfSpecialChars("MiXeDcAsE123"), 1, 'Test 144');
test(numberOfSpecialChars("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz"), 26, 'Test 145');
test(numberOfSpecialChars("OverlapAaBbCcAaBbCc"), 3, 'Test 146');
test(numberOfSpecialChars("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"), 0, 'Test 147');
test(numberOfSpecialChars("uniqueUnIQUE"), 4, 'Test 148');
test(numberOfSpecialChars("helloWorldHELLO"), 4, 'Test 149');
test(numberOfSpecialChars("specialSPECIAL"), 7, 'Test 150');
test(numberOfSpecialChars("PythonProgramming"), 0, 'Test 151');
test(numberOfSpecialChars("cCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCc"), 1, 'Test 152');
test(numberOfSpecialChars("uUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuUuU"), 1, 'Test 153');
test(numberOfSpecialChars("SpecialAndNormalChars123!@#"), 4, 'Test 154');
test(numberOfSpecialChars("Mississippi"), 0, 'Test 155');
test(numberOfSpecialChars("MixedCASEWithSOMEspecial"), 4, 'Test 156');
test(numberOfSpecialChars("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890"), 26, 'Test 157');
test(numberOfSpecialChars("NoSpecialHere"), 0, 'Test 158');
test(numberOfSpecialChars("aaaaaaaaaAAAAAA"), 1, 'Test 159');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

