// Test: 2515. Shortest Distance To Target String In A Circular Array
// 247 test cases from LeetCodeDataset
// Run: node test.js

const { closestTarget } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n2515. Shortest Distance To Target String In A Circular Array\n");

test(closestTarget(["abc","def","ghi"], "xyz", 1), -1, 'Test 1');
test(closestTarget(["apple","banana","cherry","date"], "banana", 2), 1, 'Test 2');
test(closestTarget(["cat","dog","bird","fish"], "cat", 3), 1, 'Test 3');
test(closestTarget(["dog","cat","bat"], "dog", 2), 1, 'Test 4');
test(closestTarget(["hello","i","am","leetcode","hello"], "hello", 1), 1, 'Test 5');
test(closestTarget(["a","a","a","a"], "a", 0), 0, 'Test 6');
test(closestTarget(["a","b","c","d"], "a", 3), 1, 'Test 7');
test(closestTarget(["a","b","leetcode"], "leetcode", 0), 1, 'Test 8');
test(closestTarget(["dog","cat","bat"], "rat", 1), -1, 'Test 9');
test(closestTarget(["one","two","three","four"], "one", 3), 1, 'Test 10');
test(closestTarget(["red","blue","green"], "yellow", 1), -1, 'Test 11');
test(closestTarget(["i","eat","leetcode"], "ate", 0), -1, 'Test 12');
test(closestTarget(["one","two","three","four","five"], "five", 3), 1, 'Test 13');
test(closestTarget(["apple","banana","cherry"], "banana", 2), 1, 'Test 14');
test(closestTarget(["z","y","x","w","v"], "v", 4), 0, 'Test 15');
test(closestTarget(["one","two","three","four","five"], "five", 0), 1, 'Test 16');
test(closestTarget(["red","blue","green"], "green", 1), 1, 'Test 17');
test(closestTarget(["abc","def","ghi"], "def", 1), 0, 'Test 18');
test(closestTarget(["red","blue","green"], "blue", 1), 0, 'Test 19');
test(closestTarget(["a","a","a","a"], "b", 0), -1, 'Test 20');
test(closestTarget(["a","a","a","a","a"], "a", 2), 0, 'Test 21');
test(closestTarget(["dog","cat","bird"], "fish", 1), -1, 'Test 22');
test(closestTarget(["sun","moon","star"], "planet", 1), -1, 'Test 23');
test(closestTarget(["a","b","c","d"], "d", 2), 1, 'Test 24');
test(closestTarget(["a","b","c","d"], "b", 2), 1, 'Test 25');
test(closestTarget(["rotate","me","around","and","around","again","rotate"], "around", 0), 2, 'Test 26');
test(closestTarget(["x","y","z","a","b","c","d","e","f","g"], "d", 0), 4, 'Test 27');
test(closestTarget(["one","two","three","four","five","six","seven","eight","nine","ten"], "five", 0), 4, 'Test 28');
test(closestTarget(["zebra","yak","xylophone","wolf","vulture"], "wolf", 1), 2, 'Test 29');
test(closestTarget(["abc","def","ghi","jkl","mno","pqr","stu","vwx","yz"], "mno", 0), 4, 'Test 30');
test(closestTarget(["a","b","c","d","e","f","g","h","i","j"], "e", 8), 4, 'Test 31');
test(closestTarget(["sun","moon","star","planet","comet","asteroid","galaxy"], "galaxy", 3), 3, 'Test 32');
test(closestTarget(["same","words","here","are","same","words"], "words", 2), 1, 'Test 33');
test(closestTarget(["one","two","three","four","five","six","seven","eight","nine","ten"], "seven", 4), 2, 'Test 34');
test(closestTarget(["hello","world","hello","world","hello","world"], "hello", 4), 0, 'Test 35');
test(closestTarget(["apple","banana","cherry","date","elderberry","fig","grape"], "date", 0), 3, 'Test 36');
test(closestTarget(["abc","def","ghi","jkl","mno","pqr","stu","vwx","yz"], "mno", 6), 2, 'Test 37');
test(closestTarget(["repeat","this","sentence","repeat","this","sentence"], "sentence", 3), 1, 'Test 38');
test(closestTarget(["search","for","this","word","in","this","circular","array"], "this", 4), 1, 'Test 39');
test(closestTarget(["single"], "single", 0), 0, 'Test 40');
test(closestTarget(["car","bus","bike","train","truck","van"], "van", 3), 2, 'Test 41');
test(closestTarget(["red","blue","green","yellow","red","blue","green","yellow"], "yellow", 2), 1, 'Test 42');
test(closestTarget(["unique","words","only","here"], "only", 1), 1, 'Test 43');
test(closestTarget(["red","blue","green","yellow","orange","purple","pink"], "purple", 1), 3, 'Test 44');
test(closestTarget(["one","two","three","four","five","six","seven","eight","nine","ten"], "one", 9), 1, 'Test 45');
test(closestTarget(["water","fire","earth","air","ice","steam","cloud"], "cloud", 3), 3, 'Test 46');
test(closestTarget(["hello","world","python","code","challenge"], "python", 3), 1, 'Test 47');
test(closestTarget(["algorithm","data","structures","algorithm","data"], "structures", 0), 2, 'Test 48');
test(closestTarget(["one","two","three","four","five","six","seven","eight","nine","ten"], "five", 8), 4, 'Test 49');
test(closestTarget(["python","java","c","cpp","ruby","swift","go"], "cpp", 5), 2, 'Test 50');
test(closestTarget(["x","y","z","x","y","z","x","y","z"], "y", 5), 1, 'Test 51');
test(closestTarget(["dog","cat","mouse","rat","elephant","giraffe","hippo"], "elephant", 2), 2, 'Test 52');
test(closestTarget(["orange","peach","plum","grape","kiwi"], "peach", 3), 2, 'Test 53');
test(closestTarget(["last","element","is","the","target"], "target", 3), 1, 'Test 54');
test(closestTarget(["cat","dog","fish","bird","elephant","antelope","hippo"], "hippo", 2), 3, 'Test 55');
test(closestTarget(["abc","def","ghi","jkl","mno","pqr","stu","vwx","yz"], "vwx", 4), 3, 'Test 56');
test(closestTarget(["loop","around","this","circular","array"], "array", 1), 2, 'Test 57');
test(closestTarget(["circular","array","test","case","example","circular"], "example", 4), 0, 'Test 58');
test(closestTarget(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t"], "p", 15), 0, 'Test 59');
test(closestTarget(["one","two","three","four","five","six","seven","eight","nine","ten"], "seven", 7), 1, 'Test 60');
test(closestTarget(["a","quick","brown","fox","jumps","over","the","lazy","dog"], "lazy", 3), 4, 'Test 61');
test(closestTarget(["a","aa","aaa","aaaa","aaaaa","aaaaaa","aaaaaaa","aaaaaaaa"], "aaaaaa", 1), 4, 'Test 62');
test(closestTarget(["one","two","three","four","five","six","seven","eight","nine","ten"], "ten", 2), 3, 'Test 63');
test(closestTarget(["sun","moon","star","planet","galaxy","universe","comet"], "moon", 4), 3, 'Test 64');
test(closestTarget(["python","java","c","c++","javascript","go","ruby"], "ruby", 3), 3, 'Test 65');
test(closestTarget(["hello","world","python","programming","hello","world"], "programming", 4), 1, 'Test 66');
test(closestTarget(["one","two","three","four","five","six","seven","eight","nine","ten"], "two", 8), 3, 'Test 67');
test(closestTarget(["hello","world","python","programming","is","fun"], "programming", 2), 1, 'Test 68');
test(closestTarget(["sun","moon","star","planet","galaxy","universe","sun","moon"], "galaxy", 6), 2, 'Test 69');
test(closestTarget(["red","blue","green","yellow","purple","orange","pink"], "pink", 6), 0, 'Test 70');
test(closestTarget(["hello","world","python","programming","hello"], "programming", 2), 1, 'Test 71');
test(closestTarget(["mango","banana","mango","banana","mango"], "banana", 0), 1, 'Test 72');
test(closestTarget(["one","two","three","four","five","six","seven","eight","nine","ten"], "four", 7), 4, 'Test 73');
test(closestTarget(["hello","world","this","is","a","circular","array"], "is", 5), 2, 'Test 74');
test(closestTarget(["ocean","lake","river","pond","creek","stream","flood","bay","harbor","gulf"], "stream", 5), 0, 'Test 75');
test(closestTarget(["dog","cat","bird","fish","dog","cat","bird","fish"], "fish", 7), 0, 'Test 76');
test(closestTarget(["banana","apple","orange","grape","banana","apple","orange","grape"], "orange", 5), 1, 'Test 77');
test(closestTarget(["longwordthatwillnotmatch","anotherlongword","yetanotherlongword","stillanotherlongword"], "nonexistent", 1), -1, 'Test 78');
test(closestTarget(["algorithm","data","structure","algorithm","data","structure"], "structure", 2), 0, 'Test 79');
test(closestTarget(["one","two","three","four","five","six","seven"], "four", 6), 3, 'Test 80');
test(closestTarget(["sun","moon","star","planet","galaxy"], "galaxy", 2), 2, 'Test 81');
test(closestTarget(["red","blue","green","yellow","purple","orange"], "blue", 5), 2, 'Test 82');
test(closestTarget(["x","y","z","a","b","c","d","e"], "d", 7), 1, 'Test 83');
test(closestTarget(["alpha","beta","gamma","delta","epsilon","zeta","eta","theta","iota","kappa"], "delta", 8), 5, 'Test 84');
test(closestTarget(["x","y","z","a","b","c","d","e","f","g"], "d", 9), 3, 'Test 85');
test(closestTarget(["x","y","z","x","y","z","x","y","z"], "y", 4), 0, 'Test 86');
test(closestTarget(["apple","banana","cherry","date","elderberry","fig","grape"], "date", 5), 2, 'Test 87');
test(closestTarget(["apple","banana","cherry","date","elderberry","fig","grape"], "banana", 6), 2, 'Test 88');
test(closestTarget(["find","the","shortest","distance","in","a","circular","array"], "distance", 5), 2, 'Test 89');
test(closestTarget(["apple","banana","cherry","date","elderberry","fig","grape"], "banana", 5), 3, 'Test 90');
test(closestTarget(["abc","def","ghi","jkl","mno","pqr","stu","vwx","yz"], "mno", 5), 1, 'Test 91');
test(closestTarget(["hello","world","python","programming","code","hello"], "code", 3), 1, 'Test 92');
test(closestTarget(["foo","bar","baz","qux","quux","corge","grault","garply","waldo","fred","plugh","xyzzy","thud"], "garply", 10), 3, 'Test 93');
test(closestTarget(["apple","banana","cherry","date","elderberry","fig","grape"], "banana", 4), 3, 'Test 94');
test(closestTarget(["abc","def","ghi","jkl","mno","pqr","stu","vwx","yz"], "mno", 7), 3, 'Test 95');
test(closestTarget(["aardvark","anteater","armadillo","baboon","badger","bat","bear","beaver","bison","boar"], "badger", 9), 5, 'Test 96');
test(closestTarget(["cat","dog","fish","bird","ant"], "ant", 2), 2, 'Test 97');
test(closestTarget(["repeat","repeat","repeat","repeat","repeat","repeat"], "repeat", 5), 0, 'Test 98');
test(closestTarget(["red","green","blue","yellow","orange","purple"], "green", 5), 2, 'Test 99');
test(closestTarget(["algorithm","data","structures","algorithm","data","structures"], "data", 3), 1, 'Test 100');
test(closestTarget(["x","y","z","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w"], "m", 10), 5, 'Test 101');
test(closestTarget(["aaa","bbb","ccc","ddd","eee","fff","ggg","hhh","iii","jjj"], "jjj", 9), 0, 'Test 102');
test(closestTarget(["longerword","stringexample","anotherexample","yetanother","finalword"], "anotherexample", 1), 1, 'Test 103');
test(closestTarget(["complex","circular","array","problem","solution"], "complex", 3), 2, 'Test 104');
test(closestTarget(["abc","def","ghi","jkl","mno","pqr","stu","vwx","yz"], "vwx", 8), 1, 'Test 105');
test(closestTarget(["loop","circle","ring","cycle","wheel","orbit","oval"], "oval", 3), 3, 'Test 106');
test(closestTarget(["apple","banana","cherry","date","elderberry","fig","grape"], "grape", 1), 2, 'Test 107');
test(closestTarget(["repeated","words","are","repeated","here","repeated"], "repeated", 2), 1, 'Test 108');
test(closestTarget(["hello","world","hello","python","world"], "python", 2), 1, 'Test 109');
test(closestTarget(["leetcode","problem","solving","leetcode","problem"], "solving", 4), 2, 'Test 110');
test(closestTarget(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"], "z", 0), 1, 'Test 111');
test(closestTarget(["sun","moon","star","planet","galaxy","universe"], "planet", 0), 3, 'Test 112');
test(closestTarget(["zebra","yak","xylophone","wolf","unicorn","tiger","snake"], "yak", 6), 2, 'Test 113');
test(closestTarget(["one","two","three","four","five","six","seven","eight","nine","ten"], "seven", 1), 5, 'Test 114');
test(closestTarget(["cat","dog","fish","bird","elephant","tiger","lion","bear"], "fish", 6), 4, 'Test 115');
test(closestTarget(["circular","array","example","circular"], "example", 2), 0, 'Test 116');
test(closestTarget(["hello","world","leetcode","python","hello"], "python", 0), 2, 'Test 117');
test(closestTarget(["car","bike","truck","motorcycle","bus","train","boat","plane"], "plane", 6), 1, 'Test 118');
test(closestTarget(["unique","words","here","only","once"], "once", 2), 2, 'Test 119');
test(closestTarget(["coding","is","fun","coding","is","great"], "great", 3), 2, 'Test 120');
test(closestTarget(["find","me","if","you","can"], "can", 3), 1, 'Test 121');
test(closestTarget(["abc","def","ghi","jkl","mno","pqr","stu","vwx","yz"], "vwx", 5), 2, 'Test 122');
test(closestTarget(["abcd","abcde","abcdef","abcdefg","abcdefgh","abcdefghi","abcdefghij"], "abcdefghij", 5), 1, 'Test 123');
test(closestTarget(["repeat","this","is","a","test","repeat"], "test", 4), 0, 'Test 124');
test(closestTarget(["sun","moon","star","planet"], "planet", 0), 1, 'Test 125');
test(closestTarget(["sun","moon","star"], "planet", 0), -1, 'Test 126');
test(closestTarget(["sun","moon","star","sky"], "star", 3), 1, 'Test 127');
test(closestTarget(["sun","moon","star","planet"], "planet", 2), 1, 'Test 128');
test(closestTarget(["find","me","in","the","list"], "list", 0), 1, 'Test 129');
test(closestTarget(["flower","grass","tree","bush"], "bush", 2), 1, 'Test 130');
test(closestTarget(["xyz","uvw","rst","qpo"], "rst", 3), 1, 'Test 131');
test(closestTarget(["unique","words","here"], "words", 1), 0, 'Test 132');
test(closestTarget(["aaa","bbb","ccc"], "aaa", 1), 1, 'Test 133');
test(closestTarget(["abc","def","ghi","jkl"], "def", 3), 2, 'Test 134');
test(closestTarget(["one","two","three","four","five"], "two", 4), 2, 'Test 135');
test(closestTarget(["up","down","left","right"], "up", 1), 1, 'Test 136');
test(closestTarget(["alpha","beta","gamma","delta","epsilon"], "beta", 3), 2, 'Test 137');
test(closestTarget(["dog","cat","mouse"], "elephant", 1), -1, 'Test 138');
test(closestTarget(["foo","bar","baz"], "foo", 1), 1, 'Test 139');
test(closestTarget(["dog","cat","bat"], "mouse", 1), -1, 'Test 140');
test(closestTarget(["sun","moon","star","sky"], "moon", 3), 2, 'Test 141');
test(closestTarget(["coding","is","fun","coding"], "fun", 1), 1, 'Test 142');
test(closestTarget(["zebra","giraffe","elephant"], "hippo", 1), -1, 'Test 143');
test(closestTarget(["red","blue","green","red"], "red", 3), 0, 'Test 144');
test(closestTarget(["one","two","three","four"], "three", 0), 2, 'Test 145');
test(closestTarget(["cat","dog","bird"], "dog", 2), 1, 'Test 146');
test(closestTarget(["cup","bottle","spoon","knife","cup"], "spoon", 4), 2, 'Test 147');
test(closestTarget(["dog","cat","bird","fish"], "elephant", 1), -1, 'Test 148');
test(closestTarget(["unique"], "unique", 0), 0, 'Test 149');
test(closestTarget(["hello","world","hello"], "world", 2), 1, 'Test 150');
test(closestTarget(["car","bike","bus","train","boat"], "plane", 1), -1, 'Test 151');
test(closestTarget(["red","green","blue","yellow"], "blue", 1), 1, 'Test 152');
test(closestTarget(["red","blue","green","yellow"], "blue", 0), 1, 'Test 153');
test(closestTarget(["one","two","three"], "four", 1), -1, 'Test 154');
test(closestTarget(["python","java","c","c++","ruby"], "java", 2), 1, 'Test 155');
test(closestTarget(["red","blue","green","yellow"], "blue", 2), 1, 'Test 156');
test(closestTarget(["xyz","uvw","rst","qpo"], "qpo", 3), 0, 'Test 157');
test(closestTarget(["sun","moon","star","planet"], "planet", 1), 2, 'Test 158');
test(closestTarget(["python","java","c++","ruby"], "python", 3), 1, 'Test 159');
test(closestTarget(["fast","slow","quick"], "quick", 1), 1, 'Test 160');
test(closestTarget(["abc","def","ghi","jkl"], "abc", 3), 1, 'Test 161');
test(closestTarget(["start","middle","end"], "end", 0), 1, 'Test 162');
test(closestTarget(["sun","moon","star"], "planet", 2), -1, 'Test 163');
test(closestTarget(["loop","start","end","loop"], "loop", 2), 1, 'Test 164');
test(closestTarget(["red","blue","green","yellow","purple"], "green", 4), 2, 'Test 165');
test(closestTarget(["car","bus","train","plane"], "train", 3), 1, 'Test 166');
test(closestTarget(["red","green","blue","yellow","black"], "red", 4), 1, 'Test 167');
test(closestTarget(["house","car","tree","road","house"], "road", 0), 2, 'Test 168');
test(closestTarget(["one","two","three","four","five"], "six", 0), -1, 'Test 169');
test(closestTarget(["zebra","giraffe","elephant","lion"], "elephant", 1), 1, 'Test 170');
test(closestTarget(["one","two","three","four"], "three", 3), 1, 'Test 171');
test(closestTarget(["car","bus","train"], "train", 2), 0, 'Test 172');
test(closestTarget(["one","two","three","four"], "one", 2), 2, 'Test 173');
test(closestTarget(["car","bike","train","bus"], "bike", 3), 2, 'Test 174');
test(closestTarget(["sun","moon","star"], "star", 1), 1, 'Test 175');
test(closestTarget(["search","this","array","for","target"], "target", 2), 2, 'Test 176');
test(closestTarget(["foo","bar","baz"], "foo", 2), 1, 'Test 177');
test(closestTarget(["a","b","c","d","e"], "a", 4), 1, 'Test 178');
test(closestTarget(["start","middle","end"], "start", 2), 1, 'Test 179');
test(closestTarget(["house","building","apartment"], "house", 1), 1, 'Test 180');
test(closestTarget(["one","two","three","four","five"], "one", 3), 2, 'Test 181');
test(closestTarget(["up","down","left","right"], "left", 3), 1, 'Test 182');
test(closestTarget(["dog","cat","bird","fish"], "dog", 3), 1, 'Test 183');
test(closestTarget(["dog","cat","bat","rat"], "rat", 3), 0, 'Test 184');
test(closestTarget(["one","two","three","four","five"], "three", 3), 1, 'Test 185');
test(closestTarget(["abc","def","ghi","jkl"], "def", 2), 1, 'Test 186');
test(closestTarget(["dog","cat","bird","fish"], "fish", 3), 0, 'Test 187');
test(closestTarget(["hello","world","hello"], "world", 0), 1, 'Test 188');
test(closestTarget(["coding","is","fun"], "fun", 2), 0, 'Test 189');
test(closestTarget(["one","two","three","four"], "five", 2), -1, 'Test 190');
test(closestTarget(["one","two","three","four","five","six"], "three", 0), 2, 'Test 191');
test(closestTarget(["one","two","three","four"], "four", 0), 1, 'Test 192');
test(closestTarget(["one","two","three","four","five"], "one", 2), 2, 'Test 193');
test(closestTarget(["dog","cat","bat","rat"], "bat", 3), 1, 'Test 194');
test(closestTarget(["sun","moon","star","planet"], "moon", 0), 1, 'Test 195');
test(closestTarget(["repeat","repeat","repeat","repeat"], "repeat", 2), 0, 'Test 196');
test(closestTarget(["unique","words","only","here"], "only", 0), 2, 'Test 197');
test(closestTarget(["dog","cat","bat"], "bat", 1), 1, 'Test 198');
test(closestTarget(["sun","moon","star","sky"], "moon", 0), 1, 'Test 199');
test(closestTarget(["python","java","c++"], "ruby", 1), -1, 'Test 200');
test(closestTarget(["cat","dog","bird","fish"], "dog", 2), 1, 'Test 201');
test(closestTarget(["sun","moon","star"], "moon", 2), 1, 'Test 202');
test(closestTarget(["red","blue","green","yellow"], "green", 0), 2, 'Test 203');
test(closestTarget(["apple","banana","cherry","date"], "banana", 3), 2, 'Test 204');
test(closestTarget(["car","bike","train"], "bus", 1), -1, 'Test 205');
test(closestTarget(["sun","moon","star","planet","galaxy"], "star", 3), 1, 'Test 206');
test(closestTarget(["red","blue","green","red"], "blue", 2), 1, 'Test 207');
test(closestTarget(["apple","banana","cherry","date","elderberry"], "banana", 3), 2, 'Test 208');
test(closestTarget(["one","two","three","four"], "five", 0), -1, 'Test 209');
test(closestTarget(["one","two","three","four","five"], "three", 0), 2, 'Test 210');
test(closestTarget(["apple","banana","cherry","date","elderberry"], "banana", 2), 1, 'Test 211');
test(closestTarget(["test","case","test"], "test", 2), 0, 'Test 212');
test(closestTarget(["foo","bar","baz","qux","quux","corge"], "qux", 5), 2, 'Test 213');
test(closestTarget(["hello","hello","hello"], "hello", 1), 0, 'Test 214');
test(closestTarget(["a","a","a","a"], "a", 2), 0, 'Test 215');
test(closestTarget(["red","blue","green"], "blue", 0), 1, 'Test 216');
test(closestTarget(["left","right","up","down"], "up", 1), 1, 'Test 217');
test(closestTarget(["zebra","yak","antelope"], "antelope", 1), 1, 'Test 218');
test(closestTarget(["a","b","c","d","e"], "d", 2), 1, 'Test 219');
test(closestTarget(["cat","dog","elephant","cat"], "elephant", 1), 1, 'Test 220');
test(closestTarget(["repeat","repeat","repeat"], "repeat", 2), 0, 'Test 221');
test(closestTarget(["north","south","east","west"], "north", 3), 1, 'Test 222');
test(closestTarget(["zebra","elephant","tiger","lion","giraffe"], "tiger", 4), 2, 'Test 223');
test(closestTarget(["loop","around","the","circular","array"], "around", 2), 1, 'Test 224');
test(closestTarget(["one","two","three","four","five"], "six", 2), -1, 'Test 225');
test(closestTarget(["sun","moon","star","planet"], "planet", 3), 0, 'Test 226');
test(closestTarget(["one","two","three","four","five"], "one", 4), 1, 'Test 227');
test(closestTarget(["test","case","test"], "test", 1), 1, 'Test 228');
test(closestTarget(["up","down","left","right"], "up", 3), 1, 'Test 229');
test(closestTarget(["unique","words","only","here"], "words", 3), 2, 'Test 230');
test(closestTarget(["repeat","repeat","repeat"], "repeat", 1), 0, 'Test 231');
test(closestTarget(["alpha","beta","gamma","delta"], "gamma", 2), 0, 'Test 232');
test(closestTarget(["sun","moon","star","planet"], "star", 3), 1, 'Test 233');
test(closestTarget(["left","right","up","down"], "up", 3), 1, 'Test 234');
test(closestTarget(["one","two","three","four"], "four", 3), 0, 'Test 235');
test(closestTarget(["z","y","x","w","v"], "x", 4), 2, 'Test 236');
test(closestTarget(["a","a","a","a","a"], "b", 0), -1, 'Test 237');
test(closestTarget(["red","green","blue"], "blue", 1), 1, 'Test 238');
test(closestTarget(["search","for","the","target"], "search", 3), 1, 'Test 239');
test(closestTarget(["car","bus","train"], "train", 1), 1, 'Test 240');
test(closestTarget(["happy","sad","mad"], "mad", 0), 1, 'Test 241');
test(closestTarget(["dog","cat","bird","fish","dog"], "fish", 0), 2, 'Test 242');
test(closestTarget(["abc","def","ghi","jkl","mno"], "ghi", 3), 1, 'Test 243');
test(closestTarget(["red","blue","green"], "blue", 2), 1, 'Test 244');
test(closestTarget(["alpha","beta","gamma","delta","epsilon"], "zeta", 2), -1, 'Test 245');
test(closestTarget(["repeat","repeat","repeat"], "repeat", 0), 0, 'Test 246');
test(closestTarget(["python","java","c","c++"], "java", 2), 1, 'Test 247');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

// Auto-mark DONE when all tests pass
if (!failed) {
  const path = require("path");
  const fs = require("fs");
  const dir = __dirname;
  const folder = path.basename(dir);
  if (!folder.startsWith("DONE-")) {
    const parent = path.dirname(dir);
    const newDir = path.join(parent, "DONE-" + folder);
    fs.renameSync(dir, newDir);
    const readme = path.join(newDir, "README.md");
    if (fs.existsSync(readme)) {
      let c = fs.readFileSync(readme, "utf-8");
      if (!c.includes("<!-- SOLVED -->")) {
        c = c.replace(/^(# .+)$/m, "$1 ✅\n<!-- SOLVED -->");
        fs.writeFileSync(readme, c);
      }
    }
    console.log("✅ DONE → " + "DONE-" + folder);
  }
}
