// Test: 32. Longest Valid Parentheses
// 135 test cases from LeetCodeDataset
// Run: node test.js

const { longestValidParentheses } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n32. Longest Valid Parentheses\n");

test(longestValidParentheses("[[][]]"), 6, 'Test 1');
test(longestValidParentheses("[]]"), 2, 'Test 2');
test(longestValidParentheses("[]][[]"), 2, 'Test 3');
test(longestValidParentheses("[[[[[[[]]]]]]]"), 14, 'Test 4');
test(longestValidParentheses("[[[]][][]][]"), 12, 'Test 5');
test(longestValidParentheses("][][[][[]]]"), 10, 'Test 6');
test(longestValidParentheses("[[][[][[][[]]]]]"), 16, 'Test 7');
test(longestValidParentheses("][][]]"), 4, 'Test 8');
test(longestValidParentheses("[][][][][][][][]"), 16, 'Test 9');
test(longestValidParentheses("[][[][[]]]"), 10, 'Test 10');
test(longestValidParentheses("[][][[]]"), 8, 'Test 11');
test(longestValidParentheses("[][[]"]), Error: Solution.longestValidParentheses[] missing 1 required positional argument: 's', 'Test 12');
test(longestValidParentheses(""), 0, 'Test 13');
test(longestValidParentheses("[[]]][]"), 4, 'Test 14');
test(longestValidParentheses("[[]]][[]]]"), 4, 'Test 15');
test(longestValidParentheses("[[]]]"), 4, 'Test 16');
test(longestValidParentheses("[[][[]]]"), 8, 'Test 17');
test(longestValidParentheses("[[[]]][[]][][]"), 14, 'Test 18');
test(longestValidParentheses("[[[]][][]]"), 10, 'Test 19');
test(longestValidParentheses("[[][[]][]][][]"), 14, 'Test 20');
test(longestValidParentheses("[][[][[][[][[][[]]]]]"), 18, 'Test 21');
test(longestValidParentheses("[[[[[[[[[[[]]]]]]]]]]]"), 22, 'Test 22');
test(longestValidParentheses("[]][][[]"), 2, 'Test 23');
test(longestValidParentheses("[][[]"), 2, 'Test 24');
test(longestValidParentheses("[[]"), 2, 'Test 25');
test(longestValidParentheses("[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]"), 72, 'Test 26');
test(longestValidParentheses("[[[[]]]][][][]"), 14, 'Test 27');
test(longestValidParentheses("[[][[[]][][]][]]"), 16, 'Test 28');
test(longestValidParentheses("[][][][][][][][][]"), 18, 'Test 29');
test(longestValidParentheses("[[[]][[[]]]"), 10, 'Test 30');
test(longestValidParentheses("[[[]]]"), 6, 'Test 31');
test(longestValidParentheses("[[]]][[][]]"), 6, 'Test 32');
test(longestValidParentheses("[][]"), 4, 'Test 33');
test(longestValidParentheses("[][][][]"), 8, 'Test 34');
test(longestValidParentheses("[][][][][][][][][][][][][][][][][][]"), 36, 'Test 35');
test(longestValidParentheses("[][][][][][][][][][][][][][][][][]"), 34, 'Test 36');
test(longestValidParentheses("[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]"), 80, 'Test 37');
test(longestValidParentheses("[[][[][[][[][[]]]]]]"), 20, 'Test 38');
test(longestValidParentheses("[][[][[]]][][]"), 14, 'Test 39');
test(longestValidParentheses("[[][[[]][][]]]"), 14, 'Test 40');
test(longestValidParentheses("[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]"), 60, 'Test 41');
test(longestValidParentheses("[[[[[]]]]][[[[[]]]]][[[[[]]]]]"), 30, 'Test 42');
test(longestValidParentheses("[[][[[[[]]]]]]"), 14, 'Test 43');
test(longestValidParentheses("[[[[[[[[[[[[[[]]]]]]]]]][]]]]]]]]]]]]]]]]]]][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]"), 60, 'Test 44');
test(longestValidParentheses("[[[]][][[]]]"), 12, 'Test 45');
test(longestValidParentheses("[[[[[[]]]]]]"), 12, 'Test 46');
test(longestValidParentheses("[[][[[]][]][]]"), 14, 'Test 47');
test(longestValidParentheses("[][[[[[[[]]]]]]][]"), 18, 'Test 48');
test(longestValidParentheses("[[[[][[][[][[][[][[][]]]]]]]]]"), 30, 'Test 49');
test(longestValidParentheses("[[[[[]]]]][[[[]]]]"), 18, 'Test 50');
test(longestValidParentheses("[[[[]]]][[[[]]]][[[[]]]][[[[]]]]"), 32, 'Test 51');
test(longestValidParentheses("[[[[[[[[[[[]]]]]]]]]]]]"), 22, 'Test 52');
test(longestValidParentheses("[][[][[[[]]][]]]"), 16, 'Test 53');
test(longestValidParentheses("[[[[[[]]]]]][[[[[[]]]]]]"), 24, 'Test 54');
test(longestValidParentheses("[][][[][[]]][[][[]]][][]"), 24, 'Test 55');
test(longestValidParentheses("[[][[][[][[][[]]]]][]]"), 22, 'Test 56');
test(longestValidParentheses("[[][]][[][]][[][]]"), 18, 'Test 57');
test(longestValidParentheses("[][][][[][[][[][[][[][]]]]]"), 20, 'Test 58');
test(longestValidParentheses("[[][[]]][[][[]]][[][[]]][[][[]]]"), 32, 'Test 59');
test(longestValidParentheses("[[[[[[[[[]]]]]]]]]"), 18, 'Test 60');
test(longestValidParentheses("[[[][][][][][]]][[[][][][][][]]]"), 32, 'Test 61');
test(longestValidParentheses("[][[[]]][][[][[]]][]"), 20, 'Test 62');
test(longestValidParentheses("[[[[[[][[][[][[][[][[][]]]]]]]]]]][][][]"), 40, 'Test 63');
test(longestValidParentheses("[[][[][[][[][[][[][[][[]]]]]]]][][]"), 34, 'Test 64');
test(longestValidParentheses("[[][[][[][[]]][]]]"), 18, 'Test 65');
test(longestValidParentheses("[][[][]][[][[]]]"), 16, 'Test 66');
test(longestValidParentheses("[[][[][[][[][[][[][[][[]]]]]]]]]]"), 32, 'Test 67');
test(longestValidParentheses("[][[][[][[][[][[][[][[][[]]][]]]]]]][][]"), 40, 'Test 68');
test(longestValidParentheses("[][[][[]]][][][]"), 16, 'Test 69');
test(longestValidParentheses("[[][[][[][[][[][[][[][[][[][[][[]]]]]]]]]]]]]]]"), 44, 'Test 70');
test(longestValidParentheses("[[[]]][[[]]]"), 12, 'Test 71');
test(longestValidParentheses("[[[][][[][]]]][][]"), 18, 'Test 72');
test(longestValidParentheses("[][[][[][[][[][[][[][[]]]]]]]]]]]]][][[][[][[]]][][][][][][][][]"), 30, 'Test 73');
test(longestValidParentheses("[[][[[]][[[]]][[[[]]]]]]"), 24, 'Test 74');
test(longestValidParentheses("[][][][][][][][][][]"), 20, 'Test 75');
test(longestValidParentheses("[[][[][[][[][[][[][[][[][[][[][[][[][]]]]]]]]]]]]]]"]), Error: Solution.longestValidParentheses[] missing 1 required positional argument: 's', 'Test 76');
test(longestValidParentheses("[[[[[[[[[]]]]]]][[][[][[][[][[][[][[]]]]]]]]][][]"), 48, 'Test 77');
test(longestValidParentheses("[[][[][[][[][[][[][[][[][[][[][[]]]]]][]]]]]]]]]"), 46, 'Test 78');
test(longestValidParentheses("[[][[][[][[][[][[][]]]]]]]"), 26, 'Test 79');
test(longestValidParentheses("[[][[][[][[][[][[]]]]]]]"), 24, 'Test 80');
test(longestValidParentheses("[[][[][[][[][[][[][[][[][[][[][[][]]]]]]]]]]][][]]"), 50, 'Test 81');
test(longestValidParentheses("[][[][[][[][[][[]]]]]]"), 22, 'Test 82');
test(longestValidParentheses("[[[[][[]]][[][[]]]]]"), 20, 'Test 83');
test(longestValidParentheses("[][[[[[]]]]][][[][[]]]"), 22, 'Test 84');
test(longestValidParentheses("[[][[[[[]]]]]]][][]"), 14, 'Test 85');
test(longestValidParentheses("[[[[[]]]]][[][[]]]"), 18, 'Test 86');
test(longestValidParentheses("[[][[][[][[][[][[]]]]][]][][]"), 28, 'Test 87');
test(longestValidParentheses("[[][[][[][[][[][[][[][[][[][[][[][[][[]]][]]]]]]]]]]]]]]]]]]]"), 54, 'Test 88');
test(longestValidParentheses("[[][[][[][[][[][[][[]]]]]]]]]]]]][][[][[][[]]]"), 28, 'Test 89');
test(longestValidParentheses("[[][[][[]]][[][[]]]]"), 20, 'Test 90');
test(longestValidParentheses("[[][[]]][[][[]]]"), 16, 'Test 91');
test(longestValidParentheses("[[[[][][[][]][][[][[]]]]]][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]"), 126, 'Test 92');
test(longestValidParentheses("[[][[][[][[][[][[][[][[][[]]]]]]]]]]"), 36, 'Test 93');
test(longestValidParentheses("[[][[]]][][[][]]"), 16, 'Test 94');
test(longestValidParentheses("[][[[[[[[[[]]]]]]]]]][][]"), 20, 'Test 95');
test(longestValidParentheses("[][[][[][[][[][[][[]]]]]][][][]"), 28, 'Test 96');
test(longestValidParentheses("[[][[][[][[][[][[][[][]]]]]]]]]"), 30, 'Test 97');
test(longestValidParentheses("[[[]][]][[][[][[][]]]]"), 22, 'Test 98');
test(longestValidParentheses("[[[]]][[[]]][[[]]][[[]]]"), 24, 'Test 99');
test(longestValidParentheses("[[[]]][][[[]]][][[[]]]"), 22, 'Test 100');
test(longestValidParentheses("[[][[][[][[][[][[][[]]]]]]]]]]]]][]"), 28, 'Test 101');
test(longestValidParentheses("[[][[]][[[]]]]"), 14, 'Test 102');
test(longestValidParentheses("[[[[[[[[[]]]]]]]]]]]]]]]"), 18, 'Test 103');
test(longestValidParentheses("[[][[][[][[][[][[][[]]]]]]]]"), 28, 'Test 104');
test(longestValidParentheses("[[][[][[][[][[][[][[]]]]]]][]]"), 30, 'Test 105');
test(longestValidParentheses("[][][[][[][[][[][]]]]]"), 22, 'Test 106');
test(longestValidParentheses("[][[]]][[][[]]]"), 8, 'Test 107');
test(longestValidParentheses("[[][[][[][[][[][[][[][[]]]]]][]]]]"), 34, 'Test 108');
test(longestValidParentheses("[[][[][[][[][[][[][[][[][[]]]]]]]]]]]]][][[][[][[]]][][][][][][][][][[][[][[]]]]"), 38, 'Test 109');
test(longestValidParentheses("[][[][[][[][[][[][[][[]]]]]]]]"), 30, 'Test 110');
test(longestValidParentheses("[[][][[]]][[[]][]]"), 18, 'Test 111');
test(longestValidParentheses("[[[[[[]]]]]][[[[][[]]][[]]][[][[]]][[][[]]][[][[]]][[][[]]]]"), 60, 'Test 112');
test(longestValidParentheses("[[][[][[][[][[][[][[]]]]]][]][][][]"), 34, 'Test 113');
test(longestValidParentheses("[][[][[][[][[][[]]]]]][][]"), 26, 'Test 114');
test(longestValidParentheses("[[[]]][[][[]]]"), 14, 'Test 115');
test(longestValidParentheses("[]][[][]][[][[][][[]]]]"), 20, 'Test 116');
test(longestValidParentheses("[[[]][]][[][[][[][[]]]]]"), 24, 'Test 117');
test(longestValidParentheses("[[[[]]][[]]][[][]]"), 18, 'Test 118');
test(longestValidParentheses("[[[]][]][[][[]]]"), 16, 'Test 119');
test(longestValidParentheses("[[][[]]][[][[]]][[][[]]]"), 24, 'Test 120');
test(longestValidParentheses("[[][[][[]]]][][][][[][[]]]"), 26, 'Test 121');
test(longestValidParentheses("[][][][][][][][][][][][]"), 24, 'Test 122');
test(longestValidParentheses("[[[[[[][[]]][[][[]]]]]][]]"), 26, 'Test 123');
test(longestValidParentheses("[][[][[][[][[][[][[][[]]]]]]]]]"), 30, 'Test 124');
test(longestValidParentheses("[[[]][[[]]][[][[]]][[]]]"), 24, 'Test 125');
test(longestValidParentheses("[][[][][[][[][]]]]"), 18, 'Test 126');
test(longestValidParentheses("[[[][[][]]]][][[[][[]]]]"), 24, 'Test 127');
test(longestValidParentheses("[[[[[]]][][][][[]]]"), 18, 'Test 128');
test(longestValidParentheses("[[[[[[[]]]]]]][[][[][[]]]]"), 26, 'Test 129');
test(longestValidParentheses("[[[[][[][[][[][]]]]]][][]]"), 26, 'Test 130');
test(longestValidParentheses("[][[][[][[][[][[][[]]]]]]"), 22, 'Test 131');
test(longestValidParentheses("[][][][][][][][][][][][][][][][][][][][]"), 40, 'Test 132');
test(longestValidParentheses("[][][][][][][][][][][][][][][]"), 30, 'Test 133');
test(longestValidParentheses("[[[[[[[]]]]]]][[][[][[][[]]]]]"), 30, 'Test 134');
test(longestValidParentheses("[[][]][[]][[][[][[][[]]]][]]"), 28, 'Test 135');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

