// Test: 1754. Largest Merge Of Two Strings
// 138 test cases from LeetCodeDataset
// Run: node test.js

const { largestMerge } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1754. Largest Merge Of Two Strings\n");

test(largestMerge("lexicographically", "largestmerge"), llexicogrargestmergeaphically, 'Test 1');
test(largestMerge("zyxw", "abcd"), zyxwabcd, 'Test 2');
test(largestMerge("abcdabcd", "zyxwzyxw"), zyxwzyxwabcdabcd, 'Test 3');
test(largestMerge("leetcode", "challenge"), leetcodechallenge, 'Test 4');
test(largestMerge("aaaab", "aaabb"), aaabbaaaab, 'Test 5');
test(largestMerge("lexicographic", "merge"), mlexiergecographic, 'Test 6');
test(largestMerge("aaaa", "bbbb"), bbbbaaaa, 'Test 7');
test(largestMerge("abcabc", "abdcaba"), abdcabcabcaba, 'Test 8');
test(largestMerge("abc", "defghijklmnopqrstuvwxyz"), defghijklmnopqrstuvwxyzabc, 'Test 9');
test(largestMerge("z", "z"), zz, 'Test 10');
test(largestMerge("hello", "world"), worlhellod, 'Test 11');
test(largestMerge("abcd", "zyxw"), zyxwabcd, 'Test 12');
test(largestMerge("leetcode", "etco"), leteetcodeco, 'Test 13');
test(largestMerge("xy", "xy"), xyxy, 'Test 14');
test(largestMerge("cabaa", "bcaaa"), cbcabaaaaa, 'Test 15');
test(largestMerge("aabbcc", "bbccdd"), bbccddaabbcc, 'Test 16');
test(largestMerge("zzz", "zzz"), zzzzzz, 'Test 17');
test(largestMerge("a", "b"), ba, 'Test 18');
test(largestMerge("aaaaa", "bbbbb"), bbbbbaaaaa, 'Test 19');
test(largestMerge("aabbcc", "abcabc"), abcabcaabbcc, 'Test 20');
test(largestMerge("xyz", "xyz"), xyzxyz, 'Test 21');
test(largestMerge("abcd", "efgh"), efghabcd, 'Test 22');
test(largestMerge("abcd", "dcba"), dcbabcda, 'Test 23');
test(largestMerge("same", "same"), ssameame, 'Test 24');
test(largestMerge("abcdabcd", "abcde"), abcdeabcdabcd, 'Test 25');
test(largestMerge("bca", "cab"), cbcaba, 'Test 26');
test(largestMerge("abcdefghijklmnopqrstuvwxyz", "zyxwvutsrqponmlkjihgfedcba"), zyxwvutsrqponmlkjihgfedcbabcdefghijklmnopqrstuvwxyza, 'Test 27');
test(largestMerge("mississippi", "missouri"), mmissourississippii, 'Test 28');
test(largestMerge("zzzzzzzz", "zzzzzzzz"), zzzzzzzzzzzzzzzz, 'Test 29');
test(largestMerge("complexity", "similarity"), similcomplexityarity, 'Test 30');
test(largestMerge("xyzzzzzzzzzzzzzzzz", "xyzzzzzzzzzzzzzz"), xyzzzzzzzzzzzzzzzzxyzzzzzzzzzzzzzz, 'Test 31');
test(largestMerge("aaaabbbbccccdddd", "aaaabbbbccccdddd"), aaaabbbbccccddddaaaabbbbccccdddd, 'Test 32');
test(largestMerge("zzzzzzz", "zzzzzzzz"), zzzzzzzzzzzzzzz, 'Test 33');
test(largestMerge("aaaaaaa", "bbbbbbb"), bbbbbbbaaaaaaa, 'Test 34');
test(largestMerge("zzzzz", "zzzz"), zzzzzzzzz, 'Test 35');
test(largestMerge("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "zzzyyxxwwvvuuttssrrqqponmlkjihgfedcbbaa"), zzzyyxxwwvvuuttssrrqqponmlkjihgfedcbbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzaa, 'Test 36');
test(largestMerge("zyxwvut", "utsrqponmlkjihgfedcba"), zyxwvuuttsrqponmlkjihgfedcba, 'Test 37');
test(largestMerge("pqrstuvwxyz", "nopqrstuvwxyz"), pqrstuvwxyznopqrstuvwxyz, 'Test 38');
test(largestMerge("zzzzzz", "zzzzzz"), zzzzzzzzzzzz, 'Test 39');
test(largestMerge("aabbccddeeff", "feebdccbaa"), feebdccbaabbccddeeffaa, 'Test 40');
test(largestMerge("cccccccc", "dddddddd"), ddddddddcccccccc, 'Test 41');
test(largestMerge("a", "z"), za, 'Test 42');
test(largestMerge("aabbcc", "aaabbb"), aabbccaaabbb, 'Test 43');
test(largestMerge("abcdxyz", "xyzabcd"), xyzabcdxyzabcd, 'Test 44');
test(largestMerge("python", "java"), pytjhonava, 'Test 45');
test(largestMerge("abcdabcdabcd", "abcabcabc"), abcdabcdabcdabcabcabc, 'Test 46');
test(largestMerge("sameprefix", "sameprefixsuffix"), ssameprefixsuffixameprefix, 'Test 47');
test(largestMerge("abcdefghij", "jihgfedcba"), jihgfedcbabcdefghija, 'Test 48');
test(largestMerge("onetwothreefour", "fivesixseveneightnine"), onfivetwothresixseveneightnineefoure, 'Test 49');
test(largestMerge("racecar", "racecar"), rracecaracecar, 'Test 50');
test(largestMerge("abcdabcdabcdabcdabcdabcd", "zyxwzyxwzyxwzyxwzyxwzyxw"), zyxwzyxwzyxwzyxwzyxwzyxwabcdabcdabcdabcdabcdabcd, 'Test 51');
test(largestMerge("xyxzyzyzyx", "zyzyzyzyxz"), zyzyzyzyxzxyxzyzyzyx, 'Test 52');
test(largestMerge("abacabadabacaba", "xyzxyzxyzxyzxyz"), xyzxyzxyzxyzxyzabacabadabacaba, 'Test 53');
test(largestMerge("xyzz", "yxzz"), yxzzxyzz, 'Test 54');
test(largestMerge("abcdabcdabcd", "zyxwzyxwzyxw"), zyxwzyxwzyxwabcdabcdabcd, 'Test 55');
test(largestMerge("aabbccddeeff", "zzzzyyyxxx"), zzzzyyyxxxaabbccddeeff, 'Test 56');
test(largestMerge("aabbccddeeff", "zzyyxxwwvvuu"), zzyyxxwwvvuuaabbccddeeff, 'Test 57');
test(largestMerge("abcdefg", "hijklmnop"), hijklmnopabcdefg, 'Test 58');
test(largestMerge("banana", "bandana"), bbandanananaa, 'Test 59');
test(largestMerge("abcdabcdabcd", "dcbaabcdabcd"), dcbabcdabcdabcdaabcdabcd, 'Test 60');
test(largestMerge("abracadabra", "alakazam"), alakazamabracadabra, 'Test 61');
test(largestMerge("aaaabbbbcccc", "bbbbaaaacccc"), bbbbaaaaccccaaaabbbbcccc, 'Test 62');
test(largestMerge("leetcode", "edocteel"), leetedocteelcode, 'Test 63');
test(largestMerge("aaaaaaaabbbbbbbbcccccccc", "ccccccccbbbbbbbbbaaaaaaa"), ccccccccbbbbbbbbbaaaaaaaabbbbbbbbccccccccaaaaaaa, 'Test 64');
test(largestMerge("abcdxyz", "zyxcba"), zyxcbabcdxyza, 'Test 65');
test(largestMerge("ababababab", "bababababa"), babababababababababa, 'Test 66');
test(largestMerge("equalequal", "equal"), equequalequalal, 'Test 67');
test(largestMerge("abcabcabc", "abcabcabc"), abcabcabcabcabcabc, 'Test 68');
test(largestMerge("zzzzzzyyyy", "yyyyzzzzzz"), zzzzzzyyyyzzzzzzyyyy, 'Test 69');
test(largestMerge("racecar", "race"), rracecarace, 'Test 70');
test(largestMerge("programming", "challenges"), progrchammingallenges, 'Test 71');
test(largestMerge("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "zyxwvutsrqponmlkjihgfedcba"), zyxwvutsrqponmlkjihgfedcbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzza, 'Test 72');
test(largestMerge("abcdxyz", "zyxwvut"), zyxwvutabcdxyz, 'Test 73');
test(largestMerge("abacaxi", "abacax"), abacaxiabacax, 'Test 74');
test(largestMerge("aaaaaabbbbb", "cccccdddddeeeee"), cccccdddddeeeeeaaaaaabbbbb, 'Test 75');
test(largestMerge("abcdefg", "zyxwvutsrqponmlkjihgfedcba"), zyxwvutsrqponmlkjihgfedcbabcdefga, 'Test 76');
test(largestMerge("samecharacters", "samecharacters"), ssamecharamecharactersacters, 'Test 77');
test(largestMerge("abababababab", "babababababa"), babababababababababababa, 'Test 78');
test(largestMerge("aaaaab", "bbbaaa"), bbbaaaaabaaa, 'Test 79');
test(largestMerge("aabbbccc", "aabbcc"), aabbccaabbbccc, 'Test 80');
test(largestMerge("zzzzz", "zzzzzz"), zzzzzzzzzzz, 'Test 81');
test(largestMerge("", "abc"), abc, 'Test 82');
test(largestMerge("abcdefghijk", "abcdefghijl"), abcdefghijlabcdefghijk, 'Test 83');
test(largestMerge("nestednested", "nested"), nnestesteednestedd, 'Test 84');
test(largestMerge("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"), bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, 'Test 85');
test(largestMerge("abcde", "edcba"), edcbabcdea, 'Test 86');
test(largestMerge("supercalifragilisticexpialidocious", "antidisestablishmentarianism"), supercantidisestalifragilisticexpialidociousablishmentarianism, 'Test 87');
test(largestMerge("xyzz", "zzxy"), zzxyzzxy, 'Test 88');
test(largestMerge("xyzz", "zzx"), zzxyzzx, 'Test 89');
test(largestMerge("aabbccddeeff", "zzzzyyyxxxwwvvuuttssrrqqppoonnmmllkkjjiihghffeeddccbbaa"), zzzzyyyxxxwwvvuuttssrrqqppoonnmmllkkjjiihghffeeddccbbaabbccddeeffaa, 'Test 90');
test(largestMerge("abababab", "babababa"), babababababababa, 'Test 91');
test(largestMerge("xylophone", "xylophon"), xyxyloplophonhone, 'Test 92');
test(largestMerge("abc", ""), abc, 'Test 93');
test(largestMerge("abcdabcdabcdabcd", "zyxwzyxwzyxwzyxw"), zyxwzyxwzyxwzyxwabcdabcdabcdabcd, 'Test 94');
test(largestMerge("zzzz", "zzzz"), zzzzzzzz, 'Test 95');
test(largestMerge("longwordone", "longwordtwo"), lonlongworgwordtwodone, 'Test 96');
test(largestMerge("aaaaaaaaaaaa", "bbbbbbbbbbba"), bbbbbbbbbbbaaaaaaaaaaaaa, 'Test 97');
test(largestMerge("abcdabcdabcd", "dcba"), dcbabcdabcdabcda, 'Test 98');
test(largestMerge("aaaabbbbcccc", "ddddccccbbbaaaa"), ddddccccbbbaaaabbbbccccaaaa, 'Test 99');
test(largestMerge("leetcode", "contest"), leetcontestcode, 'Test 100');
test(largestMerge("pneumonoultramicroscopicsilicovolcanoconiosis", "zoology"), zpoonlogyeumonoultramicroscopicsilicovolcanoconiosis, 'Test 101');
test(largestMerge("abcdabcdb", "abcdabcdb"), abcdabcdbabcdabcdb, 'Test 102');
test(largestMerge("amazing", "algorithm"), amazingalgorithm, 'Test 103');
test(largestMerge("b", "a"), ba, 'Test 104');
test(largestMerge("qwerqwerqwer", "qwertyuiop"), qwqwertyuioperqwerqwer, 'Test 105');
test(largestMerge("onesmallstring", "averylongstringwithmanycharactersandvariouslengthsandcombinations"), onesmaverylongstringwithmanycharallstringactersandvariouslengthsandcombinations, 'Test 106');
test(largestMerge("banana", "apple"), bappleanana, 'Test 107');
test(largestMerge("abcde", "fghij"), fghijabcde, 'Test 108');
test(largestMerge("zyxwvutsrqponmlkjihgfedcba", "abcdefghijklmnopqrstuvwxyz"), zyxwvutsrqponmlkjihgfedcbabcdefghijklmnopqrstuvwxyza, 'Test 109');
test(largestMerge("zzyzxzyzxzy", "xyxyxyxyxyx"), zzyzxzyzxzyxyxyxyxyxyx, 'Test 110');
test(largestMerge("aabbcc", "bbccaa"), bbccaabbccaa, 'Test 111');
test(largestMerge("appleapple", "banana"), bappleappleanana, 'Test 112');
test(largestMerge("abcdef", "fghijk"), fghijkabcdef, 'Test 113');
test(largestMerge("zzzzyyyyxxx", "zzzyyyyxx"), zzzzzzzyyyyyyyyxxxxx, 'Test 114');
test(largestMerge("aaaaaabbbb", "bbbbbaaaa"), bbbbbaaaaaabbbbaaaa, 'Test 115');
test(largestMerge("aaaaaa", "bbbbbbbb"), bbbbbbbbaaaaaa, 'Test 116');
test(largestMerge("lexicographically", "mergeable"), mlexiergecographicallyable, 'Test 117');
test(largestMerge("abcabcabc", "cbacbacba"), cbacbacbabcabcabca, 'Test 118');
test(largestMerge("samestart", "samestart"), ssamestartamestart, 'Test 119');
test(largestMerge("zzzzzzzzzz", "zzzzzzzzzz"), zzzzzzzzzzzzzzzzzzzz, 'Test 120');
test(largestMerge("abcdexyz", "zyxwvuts"), zyxwvutsabcdexyz, 'Test 121');
test(largestMerge("abcdefg", "ghijklm"), ghijklmabcdefg, 'Test 122');
test(largestMerge("longwordone", "evenlongerwordtwo"), longworevenlongerwordtwodone, 'Test 123');
test(largestMerge("aaaab", "aaabaaa"), aaabaaaabaaa, 'Test 124');
test(largestMerge("abcdabcd", "dcbaabcd"), dcbabcdabcdaabcd, 'Test 125');
test(largestMerge("pneumonoultramicroscopicsilicovolcanoconiosis", "supercalifragilisticexpialidocious"), suppneumonoultrercamicroscopicsilicovolcanoconiosisalifragilisticexpialidocious, 'Test 126');
test(largestMerge("aabbccddeeff", "aabbccddeegf"), aabbccddeegfaabbccddeeff, 'Test 127');
test(largestMerge("zyxzyxzyx", "zyxzyxzyx"), zzyyxzyxzyxzyxzyxx, 'Test 128');
test(largestMerge("overlapover", "overlap"), ovoverlerlapoverap, 'Test 129');
test(largestMerge("aebcdefghijklmnopqrstuvwxyz", "zxcvbnmlkjihgfedcbaeb"), zxcvbnmlkjihgfedcbaebcdefghijklmnopqrstuvwxyzaeb, 'Test 130');
test(largestMerge("abcdef", "fedcba"), fedcbabcdefa, 'Test 131');
test(largestMerge("aaaabbbbcccc", "ddddeeeeffff"), ddddeeeeffffaaaabbbbcccc, 'Test 132');
test(largestMerge("hellohellohello", "worldworld"), worlhellohellohellodworld, 'Test 133');
test(largestMerge("abcabcabcabc", "abcabc"), abcabcabcabcabcabc, 'Test 134');
test(largestMerge("zzzz", "zzz"), zzzzzzz, 'Test 135');
test(largestMerge("xyzzzzzzzzzzzz", "yyyyyyyyyyyyyy"), yyyyyyyyyyyyyyxyzzzzzzzzzzzz, 'Test 136');
test(largestMerge("aabaaa", "baabaa"), baabaabaaaaa, 'Test 137');
test(largestMerge("aaaaaaaaaabbbbbbbbbbcccccccccc", "zzzzzzzzzzzzzzzzzzzzzzzzzz"), zzzzzzzzzzzzzzzzzzzzzzzzzzaaaaaaaaaabbbbbbbbbbcccccccccc, 'Test 138');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

