// Test: 1668. Maximum Repeating Substring
// 154 test cases from LeetCodeDataset
// Run: node test.js

const { maxRepeating } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1668. Maximum Repeating Substring\n");

test(maxRepeating("ababc", "ac"), 0, 'Test 1');
test(maxRepeating("banana", "ana"), 1, 'Test 2');
test(maxRepeating("abcabcabc", "abc"), 3, 'Test 3');
test(maxRepeating("aaaa", "aa"), 2, 'Test 4');
test(maxRepeating("abc", "d"), 0, 'Test 5');
test(maxRepeating("ababc", "ab"), 2, 'Test 6');
test(maxRepeating("mississippi", "issi"), 1, 'Test 7');
test(maxRepeating("aaaabaaa", "aa"), 2, 'Test 8');
test(maxRepeating("ababc", "ba"), 1, 'Test 9');
test(maxRepeating("a", "a"), 1, 'Test 10');
test(maxRepeating("abcabcabc", "abcd"), 0, 'Test 11');
test(maxRepeating("hellohellohello", "llohe"), 2, 'Test 12');
test(maxRepeating("abababababab", "abab"), 3, 'Test 13');
test(maxRepeating("abababababababab", "ababab"), 2, 'Test 14');
test(maxRepeating("aabbccddeeff", "aabbcc"), 1, 'Test 15');
test(maxRepeating("ababababab", "ababab"), 1, 'Test 16');
test(maxRepeating("xyxxyxyxyxyxyxyxyxyxyx", "xyxxy"), 1, 'Test 17');
test(maxRepeating("abcabcabcabc", "abcd"), 0, 'Test 18');
test(maxRepeating("ababababab", "ab"), 5, 'Test 19');
test(maxRepeating("abcdabcdabcdabcdabcdabcdabcdabcd", "abcd"), 8, 'Test 20');
test(maxRepeating("abacabadabacaba", "dab"), 1, 'Test 21');
test(maxRepeating("abcabcabcabcabcabc", "abcabcabc"), 2, 'Test 22');
test(maxRepeating("abababababababababab", "ababab"), 3, 'Test 23');
test(maxRepeating("banana", "ban"), 1, 'Test 24');
test(maxRepeating("abcabcabcabcabc", "cab"), 4, 'Test 25');
test(maxRepeating("abacabadabacaba", "cab"), 1, 'Test 26');
test(maxRepeating("hellohellohellohello", "hello"), 4, 'Test 27');
test(maxRepeating("banana", "na"), 2, 'Test 28');
test(maxRepeating("abababababab", "baba"), 2, 'Test 29');
test(maxRepeating("ababababababababab", "ababab"), 3, 'Test 30');
test(maxRepeating("abcabcabcabcabc", "abcd"), 0, 'Test 31');
test(maxRepeating("xyzyzyzyzyzyzyzy", "zyzyzyzyzyzyzyzy"), 0, 'Test 32');
test(maxRepeating("zzzxxzzzxxzzzxx", "zzzxx"), 3, 'Test 33');
test(maxRepeating("aabbccddeeffgghhiijj", "ccdd"), 1, 'Test 34');
test(maxRepeating("xyzxyzxyzxyzxyz", "zyx"), 0, 'Test 35');
test(maxRepeating("abcabcabcabc", "cab"), 3, 'Test 36');
test(maxRepeating("ababababababababab", "bab"), 1, 'Test 37');
test(maxRepeating("bananaananabana", "ana"), 2, 'Test 38');
test(maxRepeating("aaaaabaaa", "aaaa"), 1, 'Test 39');
test(maxRepeating("abacabadabacaba", "bac"), 1, 'Test 40');
test(maxRepeating("aaaaabbbbbcccc", "abc"), 0, 'Test 41');
test(maxRepeating("aaaaaaa", "aaa"), 2, 'Test 42');
test(maxRepeating("zzzzzzzzzzzz", "zzzz"), 3, 'Test 43');
test(maxRepeating("ababababa", "aba"), 1, 'Test 44');
test(maxRepeating("abababcabababc", "ababc"), 1, 'Test 45');
test(maxRepeating("ababababababababababababababab", "abab"), 7, 'Test 46');
test(maxRepeating("aaaabaaaabaaaab", "aaab"), 1, 'Test 47');
test(maxRepeating("abababababababab", "baba"), 3, 'Test 48');
test(maxRepeating("xyzyzyzyzyzyzyzy", "zyzy"), 3, 'Test 49');
test(maxRepeating("abcabcabcabc", "abcabc"), 2, 'Test 50');
test(maxRepeating("aaaabaaaabaaaabaaaab", "aaaab"), 4, 'Test 51');
test(maxRepeating("abcabcabc", "cab"), 2, 'Test 52');
test(maxRepeating("abababababababababab", "abab"), 5, 'Test 53');
test(maxRepeating("abacabadabacaba", "abaca"), 1, 'Test 54');
test(maxRepeating("aaaaaaa", "a"), 7, 'Test 55');
test(maxRepeating("aabbccddeeff", "abc"), 0, 'Test 56');
test(maxRepeating("abcabcabcabcabcabcabc", "abca"), 1, 'Test 57');
test(maxRepeating("abcabcabcabcabc", "abcabcab"), 1, 'Test 58');
test(maxRepeating("abcdefabcdefabcdef", "defabc"), 2, 'Test 59');
test(maxRepeating("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "aabbccddeeffgghhiijjkkll"), 1, 'Test 60');
test(maxRepeating("abcdefabcdefabcdef", "abcdef"), 3, 'Test 61');
test(maxRepeating("zzzzzzzzzzzzzzzzzzzz", "zzzzzz"), 3, 'Test 62');
test(maxRepeating("xyzxyzxyzxyzxyzxyz", "xyzxyzxyz"), 2, 'Test 63');
test(maxRepeating("abababab", "ab"), 4, 'Test 64');
test(maxRepeating("abacabacabacabacabac", "abac"), 5, 'Test 65');
test(maxRepeating("aaaaab", "aaa"), 1, 'Test 66');
test(maxRepeating("aaaaaaa", "aaaa"), 1, 'Test 67');
test(maxRepeating("ababababababababababab", "babab"), 1, 'Test 68');
test(maxRepeating("abababab", "aba"), 1, 'Test 69');
test(maxRepeating("aaaaaabaaa", "aaa"), 2, 'Test 70');
test(maxRepeating("aaaaabaaaa", "aaa"), 1, 'Test 71');
test(maxRepeating("ababababab", "aba"), 1, 'Test 72');
test(maxRepeating("hellohellohellohellohello", "hellohello"), 2, 'Test 73');
test(maxRepeating("abcabcabcabcabcabcabcabcabcabc", "abcabcabc"), 3, 'Test 74');
test(maxRepeating("aabbccddeeefffggghhh", "eefffggg"), 1, 'Test 75');
test(maxRepeating("mississippi", "iss"), 2, 'Test 76');
test(maxRepeating("abacabacabac", "abac"), 3, 'Test 77');
test(maxRepeating("xyxyxyxyxyxyxyxy", "xyxyxyxyxyxyxy"), 1, 'Test 78');
test(maxRepeating("abcabcabcabcabcabcabcabc", "abcabcabc"), 2, 'Test 79');
test(maxRepeating("aabbccddeeffgghhiijj", "aabbcc"), 1, 'Test 80');
test(maxRepeating("xyxyxyxyxyxyxyxyxyxy", "xyxy"), 5, 'Test 81');
test(maxRepeating("xyxyxyxyxyxyxy", "xyxy"), 3, 'Test 82');
test(maxRepeating("zzzzzzzzzzzzzzzzzzzz", "zzzz"), 5, 'Test 83');
test(maxRepeating("mississippi", "miss"), 1, 'Test 84');
test(maxRepeating("ababababababababab", "ab"), 9, 'Test 85');
test(maxRepeating("hellohellohellohello", "hellohello"), 2, 'Test 86');
test(maxRepeating("banana", "nan"), 1, 'Test 87');
test(maxRepeating("abababaaba", "aba"), 2, 'Test 88');
test(maxRepeating("hellohellohello", "lohel"), 2, 'Test 89');
test(maxRepeating("qqqqqqqqqqqq", "qqqq"), 3, 'Test 90');
test(maxRepeating("xyxxyxyxyxyxyx", "xyxyx"), 1, 'Test 91');
test(maxRepeating("abcdabcdabcdabcd", "abcdabcd"), 2, 'Test 92');
test(maxRepeating("sequencewordsequenceword", "word"), 1, 'Test 93');
test(maxRepeating("abababa", "aba"), 1, 'Test 94');
test(maxRepeating("xyxyxyxyxyxyxyxy", "xyxy"), 4, 'Test 95');
test(maxRepeating("abcdefgabcdefgabcdefg", "abcdefg"), 3, 'Test 96');
test(maxRepeating("abababababababababababab", "abababab"), 3, 'Test 97');
test(maxRepeating("aaaabaaaabaaaabaaaab", "aaab"), 1, 'Test 98');
test(maxRepeating("ababababababababab", "abab"), 4, 'Test 99');
test(maxRepeating("abcdefghijabcdefghij", "cde"), 1, 'Test 100');
test(maxRepeating("mamamamamamama", "mama"), 3, 'Test 101');
test(maxRepeating("ababababababab", "abab"), 3, 'Test 102');
test(maxRepeating("hellohellohello", "hello"), 3, 'Test 103');
test(maxRepeating("abcabcabcabcabc", "abcabcabcabc"), 1, 'Test 104');
test(maxRepeating("xyzxyzxyzxyz", "xyz"), 4, 'Test 105');
test(maxRepeating("abcabcabcabcabcabc", "bcabc"), 1, 'Test 106');
test(maxRepeating("abababababababab", "abab"), 4, 'Test 107');
test(maxRepeating("abcdabcdabcdabcdabcdabcdabcdabcd", "dabc"), 7, 'Test 108');
test(maxRepeating("mississippiissippi", "issi"), 1, 'Test 109');
test(maxRepeating("xyzxyzxyz", "xy"), 1, 'Test 110');
test(maxRepeating("abcabcabcabcabcabcabc", "abcabcabcabcabc"), 1, 'Test 111');
test(maxRepeating("zzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzz"), 7, 'Test 112');
test(maxRepeating("abcabcabcabcabcabc", "abcabc"), 3, 'Test 113');
test(maxRepeating("abcdabcdabcdabcdabcdabcdabcdabcd", "dcba"), 0, 'Test 114');
test(maxRepeating("qwertyqwertyqwerty", "qwerty"), 3, 'Test 115');
test(maxRepeating("acacacacacac", "acac"), 3, 'Test 116');
test(maxRepeating("ababababa", "bab"), 1, 'Test 117');
test(maxRepeating("ababcabcababc", "abcab"), 1, 'Test 118');
test(maxRepeating("aaaaaaaaaa", "aaa"), 3, 'Test 119');
test(maxRepeating("aaaaaaaaaa", "aaaa"), 2, 'Test 120');
test(maxRepeating("mississippi", "sip"), 1, 'Test 121');
test(maxRepeating("aaaaaaa", "aa"), 3, 'Test 122');
test(maxRepeating("aaaaaabaaaaa", "aaaaa"), 1, 'Test 123');
test(maxRepeating("xyzxyzxyzxyz", "xyzxyz"), 2, 'Test 124');
test(maxRepeating("ababababc", "aba"), 1, 'Test 125');
test(maxRepeating("abcabcabcabcabcabc", "cab"), 5, 'Test 126');
test(maxRepeating("abacabacabacabac", "abacabac"), 2, 'Test 127');
test(maxRepeating("abcabcabcabcabc", "abcabcabc"), 1, 'Test 128');
test(maxRepeating("abcabcabcabcabc", "abcabc"), 2, 'Test 129');
test(maxRepeating("xyzxyzyzyzxzyzyzxzyzyz", "zyz"), 1, 'Test 130');
test(maxRepeating("xyzxyzxyzxyz", "zyxzyx"), 0, 'Test 131');
test(maxRepeating("xyzxyzxyzxyz", "xyzxyzxyz"), 1, 'Test 132');
test(maxRepeating("aaaaaa", "aa"), 3, 'Test 133');
test(maxRepeating("abcdabcdabcdabcdabcdabcdabcdabcd", "abcdabcdabcdabcd"), 2, 'Test 134');
test(maxRepeating("abcdabcdabcdabcd", "cdab"), 3, 'Test 135');
test(maxRepeating("zzzzzzzz", "zzzz"), 2, 'Test 136');
test(maxRepeating("abcdefgabcdefgabcdefg", "efg"), 1, 'Test 137');
test(maxRepeating("zzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzz"), 1, 'Test 138');
test(maxRepeating("abcdefgabcdefg", "abcdefg"), 2, 'Test 139');
test(maxRepeating("bananaananabananananabanananananana", "anana"), 2, 'Test 140');
test(maxRepeating("qwertyqwertyqwerty", "erty"), 1, 'Test 141');
test(maxRepeating("pqrspqrspqrspqrspqr", "pqrs"), 4, 'Test 142');
test(maxRepeating("ababababababa", "bab"), 1, 'Test 143');
test(maxRepeating("abcbabcabcbabcabc", "abcabc"), 1, 'Test 144');
test(maxRepeating("qwertyqwertyqwerty", "qwertyqwerty"), 1, 'Test 145');
test(maxRepeating("zzzzzzzzzzzz", "zzz"), 4, 'Test 146');
test(maxRepeating("zzzzzzzzzzzzzzz", "zzzz"), 3, 'Test 147');
test(maxRepeating("xyzxyzxyz", "xyz"), 3, 'Test 148');
test(maxRepeating("aabbccddeeff", "eeff"), 1, 'Test 149');
test(maxRepeating("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "mmnnooppqqrrssttuuvvwwxxyyzz"), 1, 'Test 150');
test(maxRepeating("ababababab", "abab"), 2, 'Test 151');
test(maxRepeating("xyxyxyxyxyxyxyxy", "xyxyxyxyxyxyxyxy"), 1, 'Test 152');
test(maxRepeating("abcdabcdabcdabcdabcdabcd", "abcdabcd"), 3, 'Test 153');
test(maxRepeating("qwertyqwertyqwertyqwerty", "qwertyqwerty"), 2, 'Test 154');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

