// Test: 777. Swap Adjacent In Lr String
// 257 test cases from LeetCodeDataset
// Run: node test.js

const { canTransform } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n777. Swap Adjacent In Lr String\n");

test(canTransform("XXL", "LXX"), true, 'Test 1');
test(canTransform("RXXLRXRXL", "XRLXXRRLX"), true, 'Test 2');
test(canTransform("LLR", "RRL"), false, 'Test 3');
test(canTransform("RXXL", "XRXL"), true, 'Test 4');
test(canTransform("XRXL", "LXXR"), false, 'Test 5');
test(canTransform("RL", "LR"), false, 'Test 6');
test(canTransform("RLX", "LXR"), false, 'Test 7');
test(canTransform("XXXXXLXXXX", "LXXXXXXXXX"), true, 'Test 8');
test(canTransform("XXRXXLXXXX", "XXXXRXXLXX"), false, 'Test 9');
test(canTransform("XXLXXRXXX", "XXXLXXRXX"), false, 'Test 10');
test(canTransform("RLXXXRRLL", "RXXRLXXLR"), false, 'Test 11');
test(canTransform("XXXX", "XXXX"), true, 'Test 12');
test(canTransform("LXXR", "XRXL"), false, 'Test 13');
test(canTransform("RXX", "XXR"), true, 'Test 14');
test(canTransform("XRLR", "LRXR"), false, 'Test 15');
test(canTransform("XRXRX", "XXRRX"), true, 'Test 16');
test(canTransform("LL", "RR"), false, 'Test 17');
test(canTransform("X", "L"), false, 'Test 18');
test(canTransform("LRRXXLRR", "XXLLRRRR"), false, 'Test 19');
test(canTransform("XXRXLXLRRXL", "LXXRXRXLRXR"), false, 'Test 20');
test(canTransform("RXLXLXLXXR", "XXLXLXLRXR"), false, 'Test 21');
test(canTransform("RXXRXXRXX", "XXRXXRXXR"), true, 'Test 22');
test(canTransform("RXLXLXLXRXXR", "LXRXRXRXLXXR"), false, 'Test 23');
test(canTransform("RXXLXXRXLXXL", "XRLXXXRXLXXL"), true, 'Test 24');
test(canTransform("RRXXLXXR", "RRXLXXXR"), true, 'Test 25');
test(canTransform("RRXLXXL", "XXLXXLR"), false, 'Test 26');
test(canTransform("RXLXLXLXL", "LXRXRXRXL"), false, 'Test 27');
test(canTransform("LLLLLXXXXXX", "XXXXXXXXLLL"), false, 'Test 28');
test(canTransform("RXLXRXLXX", "XRLXLXXRX"), false, 'Test 29');
test(canTransform("LXXRXXLXXLR", "XLXXRXXRLXR"), false, 'Test 30');
test(canTransform("RRRRRRXXXXX", "XXXXXRRRRRR"), true, 'Test 31');
test(canTransform("RXLXXLXXR", "XRLXXLXXR"), true, 'Test 32');
test(canTransform("LXXRXRXLR", "XXLRXRXLX"), false, 'Test 33');
test(canTransform("LXXRXRXLX", "XLXRLXXRX"), false, 'Test 34');
test(canTransform("LXXXXXXRXX", "XXLXXXXXRX"), false, 'Test 35');
test(canTransform("RXXXXL", "XXLRXX"), false, 'Test 36');
test(canTransform("LRXLRXLRXLR", "RXLRXLRXLRX"), false, 'Test 37');
test(canTransform("RRXXLXXLXXR", "XXRXLXXRXLR"), false, 'Test 38');
test(canTransform("XXLRLRXRXRX", "LLRXRXRXRXR"), false, 'Test 39');
test(canTransform("LRRXLXXR", "XLLRXRXR"), false, 'Test 40');
test(canTransform("RXXXXXXLXX", "XXXXXXLRXX"), false, 'Test 41');
test(canTransform("XLXRXLXRXLX", "LXRLXRLXRLX"), false, 'Test 42');
test(canTransform("RXRXRXRXRXR", "XRXRXRXRXRX"), false, 'Test 43');
test(canTransform("XXRXLXRLX", "XRLXXRXRX"), false, 'Test 44');
test(canTransform("RXXLXLXXRL", "XLRXRXRXLX"), false, 'Test 45');
test(canTransform("RRXLRXLXXL", "XRLXXLRXLR"), false, 'Test 46');
test(canTransform("LRRXLXXL", "XXLRXXRL"), false, 'Test 47');
test(canTransform("LRLRLRLRLRL", "RLRLRLRLRLR"), false, 'Test 48');
test(canTransform("RRRXXXXXXXL", "XXXXXXLRRRR"), false, 'Test 49');
test(canTransform("LXXLRXXLXXR", "XXRXXLXXLR"), false, 'Test 50');
test(canTransform("XXLXXLXXLXX", "LXXLXXLXXLX"), false, 'Test 51');
test(canTransform("RXXXXLRRXXL", "XXLRXRXRLXX"), false, 'Test 52');
test(canTransform("RXLXXLXXRLXX", "XLXXLXXLXXRX"), false, 'Test 53');
test(canTransform("RXXLRXRXLXXL", "XRLXXRRLXRXL"), false, 'Test 54');
test(canTransform("LXRXRXRXRLX", "XRLXRXRXLXL"), false, 'Test 55');
test(canTransform("RRXXLXXLXXR", "LLXXRXRXRXR"), false, 'Test 56');
test(canTransform("XXLXXRXR", "XLXXLXXR"), false, 'Test 57');
test(canTransform("LRXXLXXR", "LXXRXXRL"), false, 'Test 58');
test(canTransform("RLXXXXL", "XRLXXXX"), false, 'Test 59');
test(canTransform("LXXRXRXXL", "XLRXLXXRX"), false, 'Test 60');
test(canTransform("RLXXXLR", "XRLXXLR"), false, 'Test 61');
test(canTransform("RRXXLXXR", "XXRXXRRL"), false, 'Test 62');
test(canTransform("LRXRXLXRXL", "RXLXLRXLRX"), false, 'Test 63');
test(canTransform("RXXXXLXXXR", "XXLXXXRXRX"), false, 'Test 64');
test(canTransform("LXXRXRXL", "XXLXRXRX"), false, 'Test 65');
test(canTransform("XRXRXRXRXRX", "RXRXRXRXRXR"), false, 'Test 66');
test(canTransform("RXLXRXLX", "XRLXXLXR"), false, 'Test 67');
test(canTransform("XXXXLXXXXLXXX", "LXXXXXXXXXXLX"), false, 'Test 68');
test(canTransform("RXXLXXRXLXX", "XXLRXRXLXX"), false, 'Test 69');
test(canTransform("RXLRXRXL", "LXXRXXRXL"), false, 'Test 70');
test(canTransform("LXXRXRXLXX", "XXLXXRXLXR"), false, 'Test 71');
test(canTransform("RXXRXRXRX", "XXRXXRXXR"), false, 'Test 72');
test(canTransform("RRXXLXXLXXL", "XXLXRXRXLXR"), false, 'Test 73');
test(canTransform("LXLXLXLXL", "XLXLXLXLX"), false, 'Test 74');
test(canTransform("RXLXRXRXRXL", "LXRXRXRXRXL"), false, 'Test 75');
test(canTransform("XRXLXXRXL", "XXLXXRXXR"), false, 'Test 76');
test(canTransform("RRXLXRXLL", "XXRXLRXLR"), false, 'Test 77');
test(canTransform("RXLRLXXLR", "XLRLXLRXR"), false, 'Test 78');
test(canTransform("RXRXRXRXRX", "XRXRXRXRXR"), true, 'Test 79');
test(canTransform("RRXXXXLL", "LLXXXXRR"), false, 'Test 80');
test(canTransform("RXXRXRXLXX", "XXRXXRXLXR"), false, 'Test 81');
test(canTransform("XXRXXL", "LXXRXX"), false, 'Test 82');
test(canTransform("XRXLXLXLXL", "LXRXRXRXRX"), false, 'Test 83');
test(canTransform("RXLXLXLXL", "XLXLXLXLR"), false, 'Test 84');
test(canTransform("XXXXXXXXXXX", "XXXXXXXXXXX"), true, 'Test 85');
test(canTransform("RXLXXLXXR", "XXLXXRXLR"), false, 'Test 86');
test(canTransform("RXLXLXLXR", "XRLXLXLXR"), true, 'Test 87');
test(canTransform("XXLXXRXXLXXR", "XXLXXLXXRXXR"), false, 'Test 88');
test(canTransform("RXLXRRXLX", "XRLXXRXLX"), false, 'Test 89');
test(canTransform("LXXRXRXXL", "XXLRXRXLX"), false, 'Test 90');
test(canTransform("LXRXRXLXR", "XXLXLXLXR"), false, 'Test 91');
test(canTransform("RXLXLXRX", "LXRXLXXR"), false, 'Test 92');
test(canTransform("RXXXXLXRXL", "XRLXXRXLXX"), false, 'Test 93');
test(canTransform("RRXXLLRXXXR", "XXLRRLXXRXR"), false, 'Test 94');
test(canTransform("LXXLXRXLX", "XXLXXRLRX"), false, 'Test 95');
test(canTransform("XLRXLRXLRXL", "LXRLXRLXRLX"), true, 'Test 96');
test(canTransform("XRXXLXXRXL", "XRLXXRXLXX"), false, 'Test 97');
test(canTransform("XXRLRXXL", "LXXLRXXR"), false, 'Test 98');
test(canTransform("LXXRXXL", "XXLXXRXL"), false, 'Test 99');
test(canTransform("RXLXRXRXLXR", "XRLXRXRXLXR"), true, 'Test 100');
test(canTransform("LXRXRXRXLXXL", "XXLXXLXXLXXR"), false, 'Test 101');
test(canTransform("RXLXXRXLX", "XRLXXLXXR"), false, 'Test 102');
test(canTransform("XXLRRXXLXXR", "LXXLXXRXXRX"), false, 'Test 103');
test(canTransform("XXLRXXLXX", "LXXRXXLXX"), true, 'Test 104');
test(canTransform("RRXXLXXL", "XXLXXLRX"), false, 'Test 105');
test(canTransform("RXXLXXXL", "XXLXRXLX"), false, 'Test 106');
test(canTransform("LXRXRXRXL", "XXLXXRXXLR"), false, 'Test 107');
test(canTransform("RRXXLXXR", "XXRRLXXR"), true, 'Test 108');
test(canTransform("LLRRLRRRLL", "RLLLLRRRLL"), false, 'Test 109');
test(canTransform("LXXXXLXXXXR", "XXXXLXXLXXR"), false, 'Test 110');
test(canTransform("RXLXRXLXR", "XRLXRXLRX"), false, 'Test 111');
test(canTransform("LRXXLXRXXRL", "XRLXLXXRRLX"), false, 'Test 112');
test(canTransform("RXXLXXLXXR", "LXXRXXLXXR"), false, 'Test 113');
test(canTransform("RXXLRLXXRX", "XRLXXLXXRX"), false, 'Test 114');
test(canTransform("LXXXXXXRRRR", "RRRRXXXXXXL"), false, 'Test 115');
test(canTransform("LXXRXXLXX", "XLRXXLXXX"), false, 'Test 116');
test(canTransform("LXXLXXLXXL", "XXLXXLXXLX"), false, 'Test 117');
test(canTransform("LRXXLXXRL", "LXXRXXLRL"), false, 'Test 118');
test(canTransform("RXLXRXRXLXRX", "LXRXRXRXRXRX"), false, 'Test 119');
test(canTransform("XXRLXXLXXR", "LXXRXXRXXL"), false, 'Test 120');
test(canTransform("LXXLXXRXXR", "XXRXXLXXL"), false, 'Test 121');
test(canTransform("RXLXRXRXLXXL", "XLXXLXXLXXRX"), false, 'Test 122');
test(canTransform("RXRXRXRXR", "RRRRRXRXR"), false, 'Test 123');
test(canTransform("RXLXXLRXLX", "XXLXXRXRXL"), false, 'Test 124');
test(canTransform("RXLXXRXXL", "XXLRXRXLX"), false, 'Test 125');
test(canTransform("LRRRRRXXL", "XXLRRRRRR"), false, 'Test 126');
test(canTransform("LXXLXXLXXLX", "LXLXLXLXXLX"), false, 'Test 127');
test(canTransform("RXXLRXXLXXRXXL", "XXLXXRXRXLXXR"), false, 'Test 128');
test(canTransform("XXXXXXXXXX", "XXXXXXXXXX"), true, 'Test 129');
test(canTransform("RXLR", "LXRR"), false, 'Test 130');
test(canTransform("LRLR", "RLLR"), false, 'Test 131');
test(canTransform("RLXXRXLXXR", "RLXXRXLXXR"), true, 'Test 132');
test(canTransform("XXRXL", "XXLXR"), false, 'Test 133');
test(canTransform("XRXXLXL", "XRLXXXL"), true, 'Test 134');
test(canTransform("RXLXRX", "XRLXXR"), true, 'Test 135');
test(canTransform("LXXR", "LRXX"), false, 'Test 136');
test(canTransform("RLXXRXLXL", "XRLXXLRXL"), false, 'Test 137');
test(canTransform("LXXRXXL", "XXLXXRL"), false, 'Test 138');
test(canTransform("XXRXLXLXX", "XLXXXLRXX"), false, 'Test 139');
test(canTransform("RXRXRXRX", "XRXRXRXR"), true, 'Test 140');
test(canTransform("RLXXXRRXXL", "RLXXXXXRRXLX"), false, 'Test 141');
test(canTransform("RXL", "LXR"), false, 'Test 142');
test(canTransform("RXLXLXR", "XLRXRXL"), false, 'Test 143');
test(canTransform("RLXXXXXXXXXXRXXL", "XRLXXXXXXXXXXRLX"), false, 'Test 144');
test(canTransform("RLXXXRRXXL", "RLXXXRXLXL"), false, 'Test 145');
test(canTransform("RLXXXXXXL", "LXXXXXXXX"), false, 'Test 146');
test(canTransform("LXXXXLXXXX", "XXXXXXXXLL"), false, 'Test 147');
test(canTransform("RLRXXRLLXL", "RLRXRLLXXL"), false, 'Test 148');
test(canTransform("RLXXRXLX", "LXRXRXXL"), false, 'Test 149');
test(canTransform("RXLX", "XLXR"), false, 'Test 150');
test(canTransform("XRLXXRLXXX", "XXXRLXXRLX"), false, 'Test 151');
test(canTransform("LXXXRXX", "XXLXXRX"), false, 'Test 152');
test(canTransform("XXXXX", "XXXXX"), true, 'Test 153');
test(canTransform("RXLR", "LXRX"), false, 'Test 154');
test(canTransform("RXLXLXRXL", "XXRLXXLXR"), false, 'Test 155');
test(canTransform("RXXXXXLXXX", "XXXXXXLRXX"), false, 'Test 156');
test(canTransform("XXLXXRXXLX", "XXXLXXRXLX"), false, 'Test 157');
test(canTransform("RXXLRXRXLX", "XRLXXRRXLX"), true, 'Test 158');
test(canTransform("RXXXXXXXXR", "XXXXXXXXXR"), false, 'Test 159');
test(canTransform("RXXXL", "LXXXX"), false, 'Test 160');
test(canTransform("RXR", "XRX"), false, 'Test 161');
test(canTransform("LLRRLRLLRL", "LRLRLLRLRL"), false, 'Test 162');
test(canTransform("RXXLRXRXLXX", "XRLXXRRLXXX"), true, 'Test 163');
test(canTransform("RRXXLXXL", "XXRLXXLR"), false, 'Test 164');
test(canTransform("RLXX", "XLRX"), false, 'Test 165');
test(canTransform("LRLR", "LRLR"), true, 'Test 166');
test(canTransform("XXLXXRXXL", "LXXXXRXXX"), false, 'Test 167');
test(canTransform("XRXR", "RXXR"), false, 'Test 168');
test(canTransform("RXXXXXLXXXL", "XLRXXXXXXRL"), false, 'Test 169');
test(canTransform("XXLX", "LXXX"), true, 'Test 170');
test(canTransform("RLXXRXLXLX", "LRXXRXLXLX"), false, 'Test 171');
test(canTransform("LLRXXRXL", "LXXLRXRL"), false, 'Test 172');
test(canTransform("XRXRXRXXLX", "XXLRXRXLXX"), false, 'Test 173');
test(canTransform("RXXLRXRXL", "XRLXRXRXL"), true, 'Test 174');
test(canTransform("LXXXXLXXXX", "XXXXXXXXXX"), false, 'Test 175');
test(canTransform("LXXR", "XLXR"), false, 'Test 176');
test(canTransform("XXLXLXRXRXXLXXXXL", "XXXLLXXXXXXLRLXXR"), false, 'Test 177');
test(canTransform("RXXLRXRXL", "XRLXXRRXL"), true, 'Test 178');
test(canTransform("XXLXR", "LXXRX"), false, 'Test 179');
test(canTransform("XXXXXXX", "XXXXXXX"), true, 'Test 180');
test(canTransform("XXXLXXRXX", "XXLXXXXXR"), true, 'Test 181');
test(canTransform("LXXXXLXXXXL", "LXLXLXLXL"), false, 'Test 182');
test(canTransform("RXLXL", "LXRXR"), false, 'Test 183');
test(canTransform("RXXXXRXXXX", "XXXXXXXXXX"), false, 'Test 184');
test(canTransform("LRLR", "LRRL"), false, 'Test 185');
test(canTransform("RLXXXXXXLRLX", "LXXXXXXXXXRL"), false, 'Test 186');
test(canTransform("XXLXXLXX", "LXXLXXLX"), false, 'Test 187');
test(canTransform("RLXXXRXL", "XRLXXRXL"), false, 'Test 188');
test(canTransform("RXLXRXRXRX", "XRXRXRXLXR"), false, 'Test 189');
test(canTransform("RXXLRXRXLXR", "XRLXXRRLXXR"), true, 'Test 190');
test(canTransform("LLLL", "LLLL"), true, 'Test 191');
test(canTransform("LXXLXRLXXL", "XLLXRXXLXL"), false, 'Test 192');
test(canTransform("XRL", "LXR"), false, 'Test 193');
test(canTransform("RLXXL", "LXXRL"), false, 'Test 194');
test(canTransform("RRXXLXXR", "RXLXXRRX"), false, 'Test 195');
test(canTransform("RRRR", "RRRR"), true, 'Test 196');
test(canTransform("XXLXXLXXXX", "LXLXXXXXXL"), false, 'Test 197');
test(canTransform("LXXLXRXRXL", "XLLXRXXRXX"), false, 'Test 198');
test(canTransform("RXRXL", "XRLXR"), false, 'Test 199');
test(canTransform("LRXXRXLX", "LXRLXXRX"), false, 'Test 200');
test(canTransform("RXL", "XLR"), false, 'Test 201');
test(canTransform("XXLXXXXLXX", "XXLXXXXLXX"), true, 'Test 202');
test(canTransform("RXLXLXRXL", "XXRLXLXLX"), false, 'Test 203');
test(canTransform("XXRXLXLXX", "LXXRXLXXR"), false, 'Test 204');
test(canTransform("LXX", "XXL"), false, 'Test 205');
test(canTransform("RXXLRXRXL", "XRXXLXRXL"), false, 'Test 206');
test(canTransform("RXLXLXR", "LXRXLXR"), false, 'Test 207');
test(canTransform("XXXXXXXLXX", "LXXXXXXXXX"), true, 'Test 208');
test(canTransform("RXRXLXLXX", "XXRLXXLXR"), false, 'Test 209');
test(canTransform("RLXXXL", "XLRXRX"), false, 'Test 210');
test(canTransform("LXR", "XLR"), false, 'Test 211');
test(canTransform("RXRXLXL", "XRLXXLR"), false, 'Test 212');
test(canTransform("XXXXLXXXX", "LXXXXXXXX"), true, 'Test 213');
test(canTransform("LXXXXXXR", "RXXXXXXL"), false, 'Test 214');
test(canTransform("LXXLXRLXX", "XLLXRXXRX"), false, 'Test 215');
test(canTransform("RXLR", "LXXR"), false, 'Test 216');
test(canTransform("XXXXXLXXXX", "XXXXLXXXXX"), true, 'Test 217');
test(canTransform("LXXLXRXRXXL", "XLLXRRLXXXL"), false, 'Test 218');
test(canTransform("RXR", "RXR"), true, 'Test 219');
test(canTransform("RXXLXXXXXX", "XXXXXXLXXR"), false, 'Test 220');
test(canTransform("RLXXXXXRXL", "XRLXXRXLXR"), false, 'Test 221');
test(canTransform("RLXXLRXRXL", "LRXXRXLXRX"), false, 'Test 222');
test(canTransform("RRLL", "LLRR"), false, 'Test 223');
test(canTransform("LXXR", "XXLR"), false, 'Test 224');
test(canTransform("RXLXRXRXL", "XRLXXRRLX"), true, 'Test 225');
test(canTransform("LR", "LR"), true, 'Test 226');
test(canTransform("RLXXL", "XLRXL"), false, 'Test 227');
test(canTransform("XXLXXXRXX", "LXXXXXXRX"), true, 'Test 228');
test(canTransform("LXRX", "XLXR"), false, 'Test 229');
test(canTransform("LLRR", "LLRR"), true, 'Test 230');
test(canTransform("LLRXRXL", "LRXRLXL"), false, 'Test 231');
test(canTransform("LXXR", "XRLX"), false, 'Test 232');
test(canTransform("RXL", "XRL"), true, 'Test 233');
test(canTransform("XXRXL", "XRLXX"), false, 'Test 234');
test(canTransform("LXXLXRLXXL", "XLLXRXLXLX"), false, 'Test 235');
test(canTransform("RLXXRXLXR", "XRLXXLRXR"), false, 'Test 236');
test(canTransform("RXXXXXLXXXL", "XXXXXXXXLRL"), false, 'Test 237');
test(canTransform("RLXXXRRLL", "RLXXRXXLL"), false, 'Test 238');
test(canTransform("RXXLRXRXL", "XLRXXRRLX"), false, 'Test 239');
test(canTransform("XXRXXXXL", "XXXXLXXR"), false, 'Test 240');
test(canTransform("LXXL", "XLXL"), false, 'Test 241');
test(canTransform("RXXLRXRXLX", "XRLXXRXRXL"), false, 'Test 242');
test(canTransform("RXXLRXRXL", "RXXLRXRXL"), true, 'Test 243');
test(canTransform("LLXXRRLXXL", "LXRXRLXLX"), false, 'Test 244');
test(canTransform("LR", "RL"), false, 'Test 245');
test(canTransform("RLXXLRXRXL", "LRXXLXLXXR"), false, 'Test 246');
test(canTransform("XXXXXX", "XXXXXX"), true, 'Test 247');
test(canTransform("LXR", "LRX"), false, 'Test 248');
test(canTransform("XRLXXRRLX", "RXXLRXRXL"), false, 'Test 249');
test(canTransform("LXXLXRXRXL", "XLLXRXRXLX"), false, 'Test 250');
test(canTransform("XXR", "RXX"), false, 'Test 251');
test(canTransform("LLRXXRXLX", "XLLXRXXRX"), false, 'Test 252');
test(canTransform("XXRXL", "LXXRX"), false, 'Test 253');
test(canTransform("XRLXL", "LXRLX"), false, 'Test 254');
test(canTransform("XXXXXLXXXX", "XXXXXLXXXX"), true, 'Test 255');
test(canTransform("RXLR", "LRXR"), false, 'Test 256');
test(canTransform("RXRXXRXL", "XXRXLXRL"), false, 'Test 257');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

// Auto-mark DONE when all tests pass
if (!failed) {
  const path = require("path");
  const fs = require("fs");
  const dir = __dirname;
  const folder = path.basename(dir);
  if (!folder.startsWith("DONE-")) {
    const parent = path.dirname(dir);
    const newDir = path.join(parent, "DONE-" + folder);
    fs.renameSync(dir, newDir);
    const readme = path.join(newDir, "README.md");
    if (fs.existsSync(readme)) {
      let c = fs.readFileSync(readme, "utf-8");
      if (!c.includes("<!-- SOLVED -->")) {
        c = c.replace(/^(# .+)$/m, "$1 ✅\n<!-- SOLVED -->");
        fs.writeFileSync(readme, c);
      }
    }
    console.log("✅ DONE → " + "DONE-" + folder);
  }
}
