// Test: 2953. Count Complete Substrings
// 180 test cases from LeetCodeDataset
// Run: node test.js

const { countCompleteSubstrings } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n2953. Count Complete Substrings\n");

test(countCompleteSubstrings({"word": "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 1');
test(countCompleteSubstrings({"word": "abcabcabc", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 2');
test(countCompleteSubstrings({"word": "aaabbbccc", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 3');
test(countCompleteSubstrings({"word": "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "k": 5}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 4');
test(countCompleteSubstrings({"word": "igigee", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 5');
test(countCompleteSubstrings({"word": "abcdefghijklmnopqrstuvwxyz", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 6');
test(countCompleteSubstrings({"word": "zzzzzyyyxxxwwwwvvvvuuuuu", "k": 5}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 7');
test(countCompleteSubstrings({"word": "abcdefabcdefabcdef", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 8');
test(countCompleteSubstrings({"word": "aaabbbcccddd", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 9');
test(countCompleteSubstrings({"word": "mmnnnmmmnnnmmmnnn", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 10');
test(countCompleteSubstrings({"word": "abcabcabcabcabcabcabcabcabcabcabcabc", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 11');
test(countCompleteSubstrings({"word": "aaaabbbbccccddddeeeeffffgggghhhhiiiijjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 12');
test(countCompleteSubstrings({"word": "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 13');
test(countCompleteSubstrings({"word": "aaabbbcccdddeeefffggghhhhiiiijjjjkkkkllllmmmmnnnnooooppppqqqqrrrrssssttttuuuuvvvvwwwwxxxxyyyyzzzz", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 14');
test(countCompleteSubstrings({"word": "qrstuvqrstuvqrstuv", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 15');
test(countCompleteSubstrings({"word": "abcabcabcabcabc", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 16');
test(countCompleteSubstrings({"word": "mnopqrronmlkjihgfedcba", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 17');
test(countCompleteSubstrings({"word": "aabbccddeeefffggghhhhiii", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 18');
test(countCompleteSubstrings({"word": "abcdefgabcdefgabcdefg", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 19');
test(countCompleteSubstrings({"word": "abacabadabacabad", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 20');
test(countCompleteSubstrings({"word": "zzzzyyyyxxxxwwwwvvv", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 21');
test(countCompleteSubstrings({"word": "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefg", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 22');
test(countCompleteSubstrings({"word": "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 23');
test(countCompleteSubstrings({"word": "abcdefabcdefabcdefabcdefabcdefabcdef", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 24');
test(countCompleteSubstrings({"word": "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 25');
test(countCompleteSubstrings({"word": "xyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxzyzyxz", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 26');
test(countCompleteSubstrings({"word": "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 27');
test(countCompleteSubstrings({"word": "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "k": 5}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 28');
test(countCompleteSubstrings({"word": "zzzzyyyyxxxxwwwwvvvv", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 29');
test(countCompleteSubstrings({"word": "abcdefghijabcdefghij", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 30');
test(countCompleteSubstrings({"word": "aabbaabbccddeeffgg", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 31');
test(countCompleteSubstrings({"word": "abcabcabcabcabcabcabcabc", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 32');
test(countCompleteSubstrings({"word": "aabbaaabbbaaabbbaa", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 33');
test(countCompleteSubstrings({"word": "zzzzzyyyxxxwwvvvuuuttrrqqqlllkkkjjiigggfffeeedddccccbbbbaaaa", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 34');
test(countCompleteSubstrings({"word": "ppppqqqrrrssstttuuuuvvvvwwwwxxxxyyyyzzzz", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 35');
test(countCompleteSubstrings({"word": "qweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqwe", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 36');
test(countCompleteSubstrings({"word": "abcabcabcabcabcabcabcabcabcabcabcabc", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 37');
test(countCompleteSubstrings({"word": "aabbaaabbbaaa", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 38');
test(countCompleteSubstrings({"word": "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzz", "k": 5}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 39');
test(countCompleteSubstrings({"word": "aaaabbbbccccddddeeeeffff", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 40');
test(countCompleteSubstrings({"word": "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 41');
test(countCompleteSubstrings({"word": "abcabcdabcdeabcdefabcdefg", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 42');
test(countCompleteSubstrings({"word": "zzzyyxxwvwvwuvuvwuvuvwuvuvwuvuvwuvuvwuvuvwuvuvwuvuvwuvuvw", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 43');
test(countCompleteSubstrings({"word": "aaaabbbbccccdddd", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 44');
test(countCompleteSubstrings({"word": "abcabcabcabcabcabc", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 45');
test(countCompleteSubstrings({"word": "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyyxxwwvvuuttssrrqqponnmlkkjjiihhggffeeddccbbaa", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 46');
test(countCompleteSubstrings({"word": "abacabadabacaba", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 47');
test(countCompleteSubstrings({"word": "abababababababab", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 48');
test(countCompleteSubstrings({"word": "zzzaaazzzbbbzzz", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 49');
test(countCompleteSubstrings({"word": "zzzzzyyyyxxxxwwwwvvvv", "k": 5}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 50');
test(countCompleteSubstrings({"word": "abacabadabacaba", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 51');
test(countCompleteSubstrings({"word": "abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 52');
test(countCompleteSubstrings({"word": "zzzaaazzzbbbzzzccczzz", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 53');
test(countCompleteSubstrings({"word": "mnopqronmlkjihgfedcba", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 54');
test(countCompleteSubstrings({"word": "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 55');
test(countCompleteSubstrings({"word": "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 56');
test(countCompleteSubstrings({"word": "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 57');
test(countCompleteSubstrings({"word": "zzzzzzzzzzzzzzzzzzzz", "k": 5}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 58');
test(countCompleteSubstrings({"word": "xyzxyzxyzxyz", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 59');
test(countCompleteSubstrings({"word": "aabbccddeeffaabbccddeeffaabbccddeeff", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 60');
test(countCompleteSubstrings({"word": "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 61');
test(countCompleteSubstrings({"word": "abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 62');
test(countCompleteSubstrings({"word": "mnopqrspqrsmnopqrspqrsmnopqrspqrsmnopqrspqrsmnopqrspqrs", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 63');
test(countCompleteSubstrings({"word": "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "k": 5}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 64');
test(countCompleteSubstrings({"word": "abcabcabcabcabcabcabcabcabcabc", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 65');
test(countCompleteSubstrings({"word": "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 66');
test(countCompleteSubstrings({"word": "aaaabbbbccccddddeeeeffffgggghhhhiiii", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 67');
test(countCompleteSubstrings({"word": "abccbaabc", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 68');
test(countCompleteSubstrings({"word": "aaaaabbbbbaaaaa", "k": 5}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 69');
test(countCompleteSubstrings({"word": "zzzzzzzzzzzzzzzzzzzz", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 70');
test(countCompleteSubstrings({"word": "aaaabbbbccccddddeeeeffffgggg", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 71');
test(countCompleteSubstrings({"word": "xyzxyzxyzxyzxyzxyzxyz", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 72');
test(countCompleteSubstrings({"word": "mnopqrsmnopqrsmnopqrsmnopqrsmnopqr", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 73');
test(countCompleteSubstrings({"word": "abcabcabcabcabcabcabcabc", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 74');
test(countCompleteSubstrings({"word": "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 75');
test(countCompleteSubstrings({"word": "xyzzzyxx", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 76');
test(countCompleteSubstrings({"word": "qwertqwertqwertqwertqwertqwert", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 77');
test(countCompleteSubstrings({"word": "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "k": 10}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 78');
test(countCompleteSubstrings({"word": "aabbaaabbbaa", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 79');
test(countCompleteSubstrings({"word": "mnopqrstuvmnopqrstuvmnopqrstuvmnopqrs", "k": 5}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 80');
test(countCompleteSubstrings({"word": "abcdefghijklmnopqrstuvwxyza", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 81');
test(countCompleteSubstrings({"word": "abcdefabcdefabcdefabcdefabcdef", "k": 3}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 82');
test(countCompleteSubstrings({"word": "aabbaabbaabbaabbaabbaabb", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 83');
test(countCompleteSubstrings({"word": "zzzzzyyyyxxxxwwwwvvvvuuuuttttssssrrrrqqqqppppooooonnmmmlllkkkjjjiiihhhhggggffffffeeeeeeddddccccbbbbaaaa", "k": 5}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 84');
test(countCompleteSubstrings({"word": "aaaabbbbccccaaaabbbbccccaaaabbbbccccaaaabbbbcccc", "k": 4}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 85');
test(countCompleteSubstrings({"word": "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 86');
test(countCompleteSubstrings({"word": "aabbccddeeaabbccddeeaabbccddeeaabbccddeeaabbccdd", "k": 2}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 87');
test(countCompleteSubstrings({"word": "zyxwvutsrqponmlkjihgfedcba", "k": 1}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 88');
test(countCompleteSubstrings({"word": "aaaaabbbbccccdddd", "k": 5}), Error: Solution.countCompleteSubstrings[] missing 2 required positional arguments: 'word' and 'k', 'Test 89');
test(countCompleteSubstrings("xyzyxzyzxzyz", 2), 2, 'Test 90');
test(countCompleteSubstrings("mississippi", 1), 11, 'Test 91');
test(countCompleteSubstrings("zzzzzzzzz", 9), 1, 'Test 92');
test(countCompleteSubstrings("abcdefghijklmnopqrstuvwxyz", 1), 351, 'Test 93');
test(countCompleteSubstrings("ababababab", 1), 19, 'Test 94');
test(countCompleteSubstrings("ababab", 2), 3, 'Test 95');
test(countCompleteSubstrings("ababababab", 2), 7, 'Test 96');
test(countCompleteSubstrings("abcdabcdabcd", 4), 0, 'Test 97');
test(countCompleteSubstrings("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", 1), 77, 'Test 98');
test(countCompleteSubstrings("qrstuvqrstuvqrstuv", 3), 0, 'Test 99');
test(countCompleteSubstrings("mnopqrspqr", 2), 0, 'Test 100');
test(countCompleteSubstrings("zzzzzzzzz", 3), 7, 'Test 101');
test(countCompleteSubstrings("zyxwvutsrqponmlkjihgfedcba", 1), 351, 'Test 102');
test(countCompleteSubstrings("aabbccddeeffgghhii", 2), 45, 'Test 103');
test(countCompleteSubstrings("abacabadabacaba", 1), 31, 'Test 104');
test(countCompleteSubstrings("zzzzzzzzz", 2), 8, 'Test 105');
test(countCompleteSubstrings("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", 5), 46, 'Test 106');
test(countCompleteSubstrings("mnopqrsmnopqrsmnopqrsmnopqrsmnopqrsmnopqrs", 4), 0, 'Test 107');
test(countCompleteSubstrings("abcdefg", 1), 28, 'Test 108');
test(countCompleteSubstrings("abcd", 1), 10, 'Test 109');
test(countCompleteSubstrings("abcabcabcabcabc", 3), 7, 'Test 110');
test(countCompleteSubstrings("aaabbbccc", 3), 6, 'Test 111');
test(countCompleteSubstrings("abcde", 1), 15, 'Test 112');
test(countCompleteSubstrings("abababababababababababababababababababababababababababababababababa", 2), 64, 'Test 113');
test(countCompleteSubstrings("xyzxyzxyz", 3), 1, 'Test 114');
test(countCompleteSubstrings("abcabcabcabcabcabcabcabcabcabcabcabcabc", 1), 114, 'Test 115');
test(countCompleteSubstrings("zzzzzzyyyxx", 2), 10, 'Test 116');
test(countCompleteSubstrings("xyzzzzzzzzzzzzzzzzzzzzzzzzzz", 1), 31, 'Test 117');
test(countCompleteSubstrings("abcabcabcabc", 4), 1, 'Test 118');
test(countCompleteSubstrings("a", 1), 1, 'Test 119');
test(countCompleteSubstrings("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", 26), 25, 'Test 120');
test(countCompleteSubstrings("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", 5), 40, 'Test 121');
test(countCompleteSubstrings("abcabcabcabc", 3), 4, 'Test 122');
test(countCompleteSubstrings("igigee", 2), 3, 'Test 123');
test(countCompleteSubstrings("aaaaaa", 6), 1, 'Test 124');
test(countCompleteSubstrings("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc", 3), 58, 'Test 125');
test(countCompleteSubstrings("abcabcabc", 3), 1, 'Test 126');
test(countCompleteSubstrings("xxxxxxyyyyyzzzzz", 5), 7, 'Test 127');
test(countCompleteSubstrings("abcabcabcabcabcabcabc", 3), 13, 'Test 128');
test(countCompleteSubstrings("aabbaa", 2), 6, 'Test 129');
test(countCompleteSubstrings("qqqqqqqqqqqqqqqqqqqq", 5), 16, 'Test 130');
test(countCompleteSubstrings("aaaabbbbcccc", 4), 6, 'Test 131');
test(countCompleteSubstrings("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", 1), 50, 'Test 132');
test(countCompleteSubstrings("acacacacacacacacacacacacacacacacacacacacacacacacacacacacacacacacaca", 2), 64, 'Test 133');
test(countCompleteSubstrings("ababababababababababababab", 2), 23, 'Test 134');
test(countCompleteSubstrings("zzzzzz", 2), 5, 'Test 135');
test(countCompleteSubstrings("zzzzzzzzzz", 5), 6, 'Test 136');
test(countCompleteSubstrings("zzzyyyxxxwwvvuuttrrqqqppponnmmllkkjjiihhggffeeddccbbbaaa", 3), 12, 'Test 137');
test(countCompleteSubstrings("aaaabbbbccccddddeeeeffff", 4), 21, 'Test 138');
test(countCompleteSubstrings("aaaabbbbccccdddd", 4), 10, 'Test 139');
test(countCompleteSubstrings("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc", 3), 55, 'Test 140');
test(countCompleteSubstrings("abacabadabacaba", 3), 0, 'Test 141');
test(countCompleteSubstrings("mississippi", 2), 3, 'Test 142');
test(countCompleteSubstrings("aaa", 1), 3, 'Test 143');
test(countCompleteSubstrings("aabbbcccaabb", 2), 12, 'Test 144');
test(countCompleteSubstrings("abcdefghi", 1), 45, 'Test 145');
test(countCompleteSubstrings("ababababababababababababababababababababab", 2), 39, 'Test 146');
test(countCompleteSubstrings("zzzyyyxxxwwwwvvvuuutttsssrrrqqqpppoonnmmmlllkkkjjjiii", 3), 61, 'Test 147');
test(countCompleteSubstrings("aabbcc", 2), 6, 'Test 148');
test(countCompleteSubstrings("abcdefghijklmnopqrstuvwxyzzzz", 1), 354, 'Test 149');
test(countCompleteSubstrings("xyzyxzyzxzyx", 2), 3, 'Test 150');
test(countCompleteSubstrings("zzzzz", 5), 1, 'Test 151');
test(countCompleteSubstrings("abacaba", 1), 15, 'Test 152');
test(countCompleteSubstrings("aabbaabbaabbaabb", 2), 21, 'Test 153');
test(countCompleteSubstrings("abacabadabacaba", 2), 0, 'Test 154');
test(countCompleteSubstrings("abcdabcdeabcdabcde", 2), 0, 'Test 155');
test(countCompleteSubstrings("abcabcabc", 1), 24, 'Test 156');
test(countCompleteSubstrings("zzzzz", 1), 5, 'Test 157');
test(countCompleteSubstrings("mnopqr", 1), 21, 'Test 158');
test(countCompleteSubstrings("xyxxyxyxyx", 2), 6, 'Test 159');
test(countCompleteSubstrings("mnopqrsmnopqrsmnopqrsmnopqrs", 5), 0, 'Test 160');
test(countCompleteSubstrings("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", 5), 47, 'Test 161');
test(countCompleteSubstrings("qwertyuiopasdfghjklzxcvbnm", 1), 51, 'Test 162');
test(countCompleteSubstrings("abcdefghij", 1), 55, 'Test 163');
test(countCompleteSubstrings("zzzaaa", 3), 2, 'Test 164');
test(countCompleteSubstrings("qqwweerrtt", 2), 6, 'Test 165');
test(countCompleteSubstrings("abcdefghijk", 1), 66, 'Test 166');
test(countCompleteSubstrings("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", 2), 351, 'Test 167');
test(countCompleteSubstrings("abcdabcdabcd", 2), 0, 'Test 168');
test(countCompleteSubstrings("abcabcabcabcabcabcabcabcabcabc", 3), 22, 'Test 169');
test(countCompleteSubstrings("abcdefghijklmnopqrstuvwxyzaaa", 1), 354, 'Test 170');
test(countCompleteSubstrings("aaaabbbbccccaaaabbbbcccc", 4), 24, 'Test 171');
test(countCompleteSubstrings("zzzzzz", 1), 6, 'Test 172');
test(countCompleteSubstrings("abcabcabcabcabcabc", 3), 10, 'Test 173');
test(countCompleteSubstrings("abababababababababab", 2), 17, 'Test 174');
test(countCompleteSubstrings("abcdef", 1), 21, 'Test 175');
test(countCompleteSubstrings("aabbccddeeaabbccddeeaabbccddeeddeeaabbcc", 2), 57, 'Test 176');
test(countCompleteSubstrings("abcdabc", 2), 0, 'Test 177');
test(countCompleteSubstrings("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", 10), 43, 'Test 178');
test(countCompleteSubstrings("zzzyyyxxx", 3), 6, 'Test 179');
test(countCompleteSubstrings("xyzzzzzyxxyzzzzzyx", 3), 6, 'Test 180');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

