// Test: 2047. Number Of Valid Words In A Sentence
// 377 test cases from LeetCodeDataset
// Run: node test.js

const { countValidWords } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n2047. Number Of Valid Words In A Sentence\n");

test(countValidWords("no-digits123 or symbols#allowed"), 2, 'Test 1');
test(countValidWords("a.b.c"), 0, 'Test 2');
test(countValidWords("hello-world, this-is-a-test"), 1, 'Test 3');
test(countValidWords("hello-"), 0, 'Test 4');
test(countValidWords("a-"), 0, 'Test 5');
test(countValidWords("singleletter a b c d e f g"), 8, 'Test 6');
test(countValidWords("valid-words only"), 2, 'Test 7');
test(countValidWords("a"), 1, 'Test 8');
test(countValidWords("hello world! this is a test."), 6, 'Test 9');
test(countValidWords("hello-world, my.name-is Qwen"), 2, 'Test 10');
test(countValidWords("ending-with-punctuation!"), 0, 'Test 11');
test(countValidWords("invalid--double-dash"), 0, 'Test 12');
test(countValidWords("multiple   spaces   between   words"), 4, 'Test 13');
test(countValidWords("123"), 0, 'Test 14');
test(countValidWords("multiple--hyphens"), 0, 'Test 15');
test(countValidWords("valid-hyphenated-word"), 0, 'Test 16');
test(countValidWords("-invalid invalid- invalid-!"), 0, 'Test 17');
test(countValidWords("well-well, well!"), 2, 'Test 18');
test(countValidWords("singleletter"), 1, 'Test 19');
test(countValidWords("a! b. c?"), 3, 'Test 20');
test(countValidWords("hello-world"), 1, 'Test 21');
test(countValidWords("a-b-c"), 0, 'Test 22');
test(countValidWords("-world"), 0, 'Test 23');
test(countValidWords("a-b-c d-e f-g"), 2, 'Test 24');
test(countValidWords("-b"), 0, 'Test 25');
test(countValidWords("no-digits-allowed 123 456-789"), 0, 'Test 26');
test(countValidWords("alice and  bob are playing stone-game10"), 5, 'Test 27');
test(countValidWords("no-dash-here"), 0, 'Test 28');
test(countValidWords("a-b!"), 1, 'Test 29');
test(countValidWords("valid-word here!"), 2, 'Test 30');
test(countValidWords("a-b- c d"), 2, 'Test 31');
test(countValidWords("valid-word here and another-valid one!"), 5, 'Test 32');
test(countValidWords("a-b-c-d.e.f!"), 0, 'Test 33');
test(countValidWords("singleletter a b c"), 4, 'Test 34');
test(countValidWords("a-b. afad ba-c a! ."), 5, 'Test 35');
test(countValidWords("a.b-c"), 0, 'Test 36');
test(countValidWords("hello!world"), 0, 'Test 37');
test(countValidWords(","), 1, 'Test 38');
test(countValidWords("a!b"), 0, 'Test 39');
test(countValidWords("-ab cd- ef-"), 0, 'Test 40');
test(countValidWords("hello-world, my name is john-doe."), 5, 'Test 41');
test(countValidWords("!this  1-s b8d!"), 0, 'Test 42');
test(countValidWords("trailingpunctuation. comma, exclamation!"), 3, 'Test 43');
test(countValidWords("punctuation,in,middle,a-b.c"), 0, 'Test 44');
test(countValidWords("invalid-end-"), 0, 'Test 45');
test(countValidWords("-invalid start"), 1, 'Test 46');
test(countValidWords("valid-word here! and here."), 4, 'Test 47');
test(countValidWords("!"), 1, 'Test 48');
test(countValidWords("valid-word-here!"), 0, 'Test 49');
test(countValidWords("punctuation,at,end."), 0, 'Test 50');
test(countValidWords("a-b.c"), 0, 'Test 51');
test(countValidWords("cat and  dog"), 3, 'Test 52');
test(countValidWords("."), 1, 'Test 53');
test(countValidWords("-invalid-start"), 0, 'Test 54');
test(countValidWords("a.b"), 0, 'Test 55');
test(countValidWords("hello-world!"), 1, 'Test 56');
test(countValidWords("punctuation! marks, are: allowed?"), 4, 'Test 57');
test(countValidWords("punctuation.only,"), 0, 'Test 58');
test(countValidWords("valid-word- valid-word-"), 0, 'Test 59');
test(countValidWords("word-with-digit1"), 0, 'Test 60');
test(countValidWords("punctuation-after-hyphen-! invalid"), 1, 'Test 61');
test(countValidWords("word-with-digit-and-punctuation-1,"), 0, 'Test 62');
test(countValidWords("valid-word, valid-word!"), 2, 'Test 63');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word?"), 1, 'Test 64');
test(countValidWords("word-hyphenated-word- word- word. word@123"), 1, 'Test 65');
test(countValidWords("valid-word-with-hyphen-and-punctuation!"), 0, 'Test 66');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!"), 1, 'Test 67');
test(countValidWords("valid-word, invalid-word2"), 1, 'Test 68');
test(countValidWords("word-with-hyphen-and-punctuation-after-hyphen-,"), 0, 'Test 69');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@"), 1, 'Test 70');
test(countValidWords("word-with-digit-and-hyphen-1b"), 0, 'Test 71');
test(countValidWords("word-with-digit-and-hyphen-1b-"), 0, 'Test 72');
test(countValidWords("valid-word-123"), 0, 'Test 73');
test(countValidWords("word-with-punctuation,at,end."), 0, 'Test 74');
test(countValidWords("multiple---hyphens-in-a-row"), 0, 'Test 75');
test(countValidWords("word-with-hyphen-"), 0, 'Test 76');
test(countValidWords("word-with-digit-in-middle-1word"), 0, 'Test 77');
test(countValidWords("punctuation-inside-word!word"), 0, 'Test 78');
test(countValidWords("a-b-c d-e-f g-h"), 1, 'Test 79');
test(countValidWords("word-with-punctuation-and-digit1!"), 0, 'Test 80');
test(countValidWords("word-with-hyphen-and-punctuation-after-hyphen-!"), 0, 'Test 81');
test(countValidWords("-word-with-leading-hyphen"), 0, 'Test 82');
test(countValidWords("word-with-digit-and-hyphen-b--1"), 0, 'Test 83');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word@?!#abc"), 1, 'Test 84');
test(countValidWords("word-with-punctuation! word-without"), 1, 'Test 85');
test(countValidWords("word. word- word!"), 2, 'Test 86');
test(countValidWords("hyphenated-word- is valid"), 2, 'Test 87');
test(countValidWords("no-spaces"), 1, 'Test 88');
test(countValidWords("word-with-digit-and-hyphen-1-word"), 0, 'Test 89');
test(countValidWords("word! word- word. word?"), 3, 'Test 90');
test(countValidWords("hyphen-at-end-"), 0, 'Test 91');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word!"), 1, 'Test 92');
test(countValidWords("word-hyphenated-word- word- word. word-123@!"), 1, 'Test 93');
test(countValidWords("multiple---hyphens"), 0, 'Test 94');
test(countValidWords("word-with-hyphen-and-exclamation!"), 0, 'Test 95');
test(countValidWords("valid-word- valid-word!"), 1, 'Test 96');
test(countValidWords("word word, word! word."), 4, 'Test 97');
test(countValidWords("word-with-digit-and-hyphen-b--"), 0, 'Test 98');
test(countValidWords("valid-word- word-with-hyphen"), 0, 'Test 99');
test(countValidWords("word-with-digit1-and-punctuation!"), 0, 'Test 100');
test(countValidWords("punctuation-in-middle-of-word!word"), 0, 'Test 101');
test(countValidWords("word!word"), 0, 'Test 102');
test(countValidWords("singleletter singleletter! singleletter."), 3, 'Test 103');
test(countValidWords("word-with-digit-at-end1!"), 0, 'Test 104');
test(countValidWords("word-with-digit-and-hyphen-1--b"), 0, 'Test 105');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#"), 1, 'Test 106');
test(countValidWords("word-with-punctuation-and-hyphen-word-123"), 0, 'Test 107');
test(countValidWords("multiple--dashes are invalid"), 2, 'Test 108');
test(countValidWords("word-with-punctuation.at.end,invalid"), 0, 'Test 109');
test(countValidWords("word-with-digit1-and-punctuation."), 0, 'Test 110');
test(countValidWords("valid-word-with-punctuation-at-end,"), 0, 'Test 111');
test(countValidWords("single-hyphenated-word a-b"), 1, 'Test 112');
test(countValidWords("123 word- word! word?"), 2, 'Test 113');
test(countValidWords("a.b!"), 0, 'Test 114');
test(countValidWords("word-with-hyphen-and-punctuation, word-with-hyphen-and-punctuation."), 0, 'Test 115');
test(countValidWords("valid-word- valid-word- valid-word"), 1, 'Test 116');
test(countValidWords("punctuation-only! and !only-punctuation"), 2, 'Test 117');
test(countValidWords("hello-world- is not valid"), 3, 'Test 118');
test(countValidWords("word-with-valid-hyphen word-with--invalid-hyphen"), 0, 'Test 119');
test(countValidWords("valid-word valid-word- valid-word"), 2, 'Test 120');
test(countValidWords("word-with-digit-and-hyphen-and-punctuation-1-word!"), 0, 'Test 121');
test(countValidWords("invalid-1word and valid-word"), 2, 'Test 122');
test(countValidWords("word-with-punctuation,at,end!"), 0, 'Test 123');
test(countValidWords("word- word"), 1, 'Test 124');
test(countValidWords("word-with-punctuations!word-with-punctuations!word-with-punctuations."), 0, 'Test 125');
test(countValidWords("valid-ending-punctuation."), 0, 'Test 126');
test(countValidWords("word-with-punctuation,word"), 0, 'Test 127');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word@?!"), 1, 'Test 128');
test(countValidWords("word.."), 0, 'Test 129');
test(countValidWords("word-with-multiple-hyphens-and-punctuation-,"), 0, 'Test 130');
test(countValidWords("multiple-spaces   between   words"), 3, 'Test 131');
test(countValidWords("word-with-hyphen-123"), 0, 'Test 132');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word@"), 1, 'Test 133');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word-"), 1, 'Test 134');
test(countValidWords("word-with-punctuations!word-with-punctuations!word-with-punctuations!word-with-punctuations!word-with-punctuations."), 0, 'Test 135');
test(countValidWords("valid!word"), 0, 'Test 136');
test(countValidWords("word- word- valid"), 1, 'Test 137');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-123"), 1, 'Test 138');
test(countValidWords("a--b"), 0, 'Test 139');
test(countValidWords("word-hyphenated-word word- word. word?"), 2, 'Test 140');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!"), 1, 'Test 141');
test(countValidWords("word-with-digit-and-hyphen-b1"), 0, 'Test 142');
test(countValidWords("word- word! word@"), 2, 'Test 143');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word@?!#abc-def,word"), 1, 'Test 144');
test(countValidWords("word-with-hyphen- valid-word"), 1, 'Test 145');
test(countValidWords("word-with-digit-and-punctuation1-,"), 0, 'Test 146');
test(countValidWords("validwordwithmultiplepunctuations,,,"), 0, 'Test 147');
test(countValidWords("valid-word-with-hyphen-and-comma, valid."), 1, 'Test 148');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word@?!#"), 1, 'Test 149');
test(countValidWords("word,word,word"), 0, 'Test 150');
test(countValidWords("valid-word-with-punctuation-at-end!"), 0, 'Test 151');
test(countValidWords("word-hyphenated-word- word- word. word-123!"), 1, 'Test 152');
test(countValidWords("word,with,commas and.punctuations"), 0, 'Test 153');
test(countValidWords("word-hyphenated-word- word- word. word@!"), 2, 'Test 154');
test(countValidWords("word-hyphenated-word- word- word. word-123?"), 1, 'Test 155');
test(countValidWords("valid-word, valid-word. valid-word! valid-word"), 4, 'Test 156');
test(countValidWords("word-with-hyphen-and-punctuation,"), 0, 'Test 157');
test(countValidWords("word-with-space-in-word"), 0, 'Test 158');
test(countValidWords("word-with-hyphen-and-punctuation word-with-hyphen-and-punctuation-"), 0, 'Test 159');
test(countValidWords("multiple---hyphens-in-word"), 0, 'Test 160');
test(countValidWords("word,word"), 0, 'Test 161');
test(countValidWords("word-hyphenated-word- word- word. word?"), 2, 'Test 162');
test(countValidWords("123 456 789"), 0, 'Test 163');
test(countValidWords("punctuation!in!the!middle"), 0, 'Test 164');
test(countValidWords("multiple-punctuation,,"), 0, 'Test 165');
test(countValidWords("word-with-hyphen-and-digit-1"), 0, 'Test 166');
test(countValidWords("word-with-digit123"), 0, 'Test 167');
test(countValidWords("word-with-digit123 and another-word!"), 2, 'Test 168');
test(countValidWords("a!b.c"), 0, 'Test 169');
test(countValidWords("multiple-punctuation!!"), 0, 'Test 170');
test(countValidWords("word-with123-hyphen"), 0, 'Test 171');
test(countValidWords("only!only only.only only-"), 0, 'Test 172');
test(countValidWords("word1 word2- word3- word4"), 0, 'Test 173');
test(countValidWords("word-with-hyphen- word"), 1, 'Test 174');
test(countValidWords("valid-word"), 1, 'Test 175');
test(countValidWords("-word"), 0, 'Test 176');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word"), 1, 'Test 177');
test(countValidWords("word-with-1digit"), 0, 'Test 178');
test(countValidWords("word-with-punctuations,word-with-punctuations,word-with-punctuations,word-with-punctuations,word-with-punctuations!"), 0, 'Test 179');
test(countValidWords("valid-word, and invalid-word1"), 2, 'Test 180');
test(countValidWords("word-with-punctuation-in-middle.a"), 0, 'Test 181');
test(countValidWords("word-hyphenated-word- word- word. word@?"), 2, 'Test 182');
test(countValidWords("word-with-hyphen-and-period."), 0, 'Test 183');
test(countValidWords("word-with-multiple-hyphens-and-punctuation-,and valid-word!"), 1, 'Test 184');
test(countValidWords("word-with-punctuations,word-with-punctuations."), 0, 'Test 185');
test(countValidWords("valid-word followed-by-number123"), 1, 'Test 186');
test(countValidWords("single-punctuation!"), 1, 'Test 187');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@123"), 1, 'Test 188');
test(countValidWords("word word- word! word-"), 2, 'Test 189');
test(countValidWords("word-! word- word-"), 0, 'Test 190');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc123"), 1, 'Test 191');
test(countValidWords("word-with-digit-and-hyphen-and-punctuation-word-1."), 0, 'Test 192');
test(countValidWords("word-with-hyphen word-with-hyphen- word-with-hyphen"), 0, 'Test 193');
test(countValidWords("valid-word! another-valid-word?"), 1, 'Test 194');
test(countValidWords("word-with-digit-and-punctuation1,"), 0, 'Test 195');
test(countValidWords("word-with-punctuation.at-end"), 0, 'Test 196');
test(countValidWords("valid-word, invalid-word123"), 1, 'Test 197');
test(countValidWords("!valid valid. valid-"), 1, 'Test 198');
test(countValidWords("valid-word."), 1, 'Test 199');
test(countValidWords("word-with-digit-and-punctuation1-."), 0, 'Test 200');
test(countValidWords("a a-b a-b-c a-b-c-d"), 2, 'Test 201');
test(countValidWords("word-with-trailing-punctuation,"), 0, 'Test 202');
test(countValidWords("word-with-hyphen-and-punctuation-after-hyphen-."), 0, 'Test 203');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word@123"), 1, 'Test 204');
test(countValidWords("multiple   spaces"), 2, 'Test 205');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word?"), 1, 'Test 206');
test(countValidWords("multiple-punctuation.."), 0, 'Test 207');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word@?!#abc-123"), 1, 'Test 208');
test(countValidWords("word! word- word. word-"), 2, 'Test 209');
test(countValidWords("valid-word followed-by-digits123"), 1, 'Test 210');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc"), 1, 'Test 211');
test(countValidWords("word-with-digit-and-hyphen--b-1"), 0, 'Test 212');
test(countValidWords("hello-world- is-not-valid"), 0, 'Test 213');
test(countValidWords("word-with-punctuations!word-with-punctuations!"), 0, 'Test 214');
test(countValidWords("-a"), 0, 'Test 215');
test(countValidWords("nohyphens here!"), 2, 'Test 216');
test(countValidWords("word-with-punctuation-at-start!word"), 0, 'Test 217');
test(countValidWords("leading!and-trailing!punctuation!"), 0, 'Test 218');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word"), 1, 'Test 219');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def!"), 1, 'Test 220');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc"), 1, 'Test 221');
test(countValidWords("no-dashes-here but-here-are-too-many-dashes"), 0, 'Test 222');
test(countValidWords("word-hyphen- word"), 1, 'Test 223');
test(countValidWords("valid-word-with-hyphen-and-punctuation."), 0, 'Test 224');
test(countValidWords("word-with-hyphen-and-punctuation!"), 0, 'Test 225');
test(countValidWords("valid-word, valid-word. valid-word!"), 3, 'Test 226');
test(countValidWords("word-with-punctuation.at.end."), 0, 'Test 227');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word-"), 1, 'Test 228');
test(countValidWords("a!b!c"), 0, 'Test 229');
test(countValidWords("word-with-number1234 and valid-word"), 2, 'Test 230');
test(countValidWords("word,word!"), 0, 'Test 231');
test(countValidWords("word-hyphenated-word- word- word. word@"), 2, 'Test 232');
test(countValidWords("word1 word2 word3 word4"), 0, 'Test 233');
test(countValidWords("word-with-punctuation,at,end!invalid"), 0, 'Test 234');
test(countValidWords("complex-word-with-punctuation,"), 0, 'Test 235');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word@?!#abc-def!"), 1, 'Test 236');
test(countValidWords("word-with-punctuations!word-with-punctuations!word-with-punctuations!word-with-punctuations."), 0, 'Test 237');
test(countValidWords("single-letter-word a"), 1, 'Test 238');
test(countValidWords("word-with-trailing-hyphen-"), 0, 'Test 239');
test(countValidWords("punctuation.multiple"), 0, 'Test 240');
test(countValidWords("multi-hyphen-word-123"), 0, 'Test 241');
test(countValidWords("word-with-hyphen word-with-hyphen-"), 0, 'Test 242');
test(countValidWords("valid-word a valid-word- valid-word"), 3, 'Test 243');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc123"), 1, 'Test 244');
test(countValidWords("word-with-digit-and-punctuation-1."), 0, 'Test 245');
test(countValidWords("word-with-digit-and-hyphen-b-1--"), 0, 'Test 246');
test(countValidWords("word!word!"), 0, 'Test 247');
test(countValidWords("!word .word ,word"), 0, 'Test 248');
test(countValidWords("word-with-hyphen-and-punctuation- word"), 1, 'Test 249');
test(countValidWords("invalid-punctuation, invalid-punctuation! invalid-punctuation?"), 3, 'Test 250');
test(countValidWords("a.b.c.d"), 0, 'Test 251');
test(countValidWords("multi-hyphenated-word-should-fail"), 0, 'Test 252');
test(countValidWords("valid-word!"), 1, 'Test 253');
test(countValidWords("punctuation!in!middle"), 0, 'Test 254');
test(countValidWords("trailing-hyphen- invalid-hyphen-"), 0, 'Test 255');
test(countValidWords("single-letter a"), 2, 'Test 256');
test(countValidWords("word-with-digit-and-hyphen--b1"), 0, 'Test 257');
test(countValidWords("word-with-hyphen-and-period-and-comma,./"), 0, 'Test 258');
test(countValidWords("word-with-punctuations! word"), 1, 'Test 259');
test(countValidWords("word-with-2-hyphens-a-b-c"), 0, 'Test 260');
test(countValidWords("word-with--double-hyphen"), 0, 'Test 261');
test(countValidWords("a.b-c!d.e"), 0, 'Test 262');
test(countValidWords("this-is-valid-1"), 0, 'Test 263');
test(countValidWords("valid-word! valid-word!"), 2, 'Test 264');
test(countValidWords("word-with-hyphen-and-digit1-"), 0, 'Test 265');
test(countValidWords("a!b-c.d.e"), 0, 'Test 266');
test(countValidWords("a.b-c.d.e"), 0, 'Test 267');
test(countValidWords("word-with-digit-and-punctuation1-!"), 0, 'Test 268');
test(countValidWords("1word 12word word3"), 0, 'Test 269');
test(countValidWords("word-with-punctuation,word-with-punctuation, word-with-punctuation!word-with-punctuation."), 0, 'Test 270');
test(countValidWords("a!b.c-d.e"), 0, 'Test 271');
test(countValidWords("valid-word-1 valid-word-2"), 0, 'Test 272');
test(countValidWords("word!word another-word,"), 1, 'Test 273');
test(countValidWords("a.b-c.d!e"), 0, 'Test 274');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def"), 1, 'Test 275');
test(countValidWords("a-b.c.d"), 0, 'Test 276');
test(countValidWords("mid,dash"), 0, 'Test 277');
test(countValidWords("valid.word"), 0, 'Test 278');
test(countValidWords("valid-word valid-word-"), 1, 'Test 279');
test(countValidWords("word-with-punctuations,word"), 0, 'Test 280');
test(countValidWords("word-with-digit-and-punctuation1."), 0, 'Test 281');
test(countValidWords("word-with-digit-and-hyphen-word-1"), 0, 'Test 282');
test(countValidWords("word-!"), 0, 'Test 283');
test(countValidWords("word-with-hyphen-and-comma,"), 0, 'Test 284');
test(countValidWords("-hyphen-at-start"), 0, 'Test 285');
test(countValidWords("single-punctuation-mark."), 0, 'Test 286');
test(countValidWords("!invalid-start-word invalid-end-word!"), 0, 'Test 287');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def!"), 1, 'Test 288');
test(countValidWords("a-b-c-d"), 0, 'Test 289');
test(countValidWords("word-with-punctuations,word-with-punctuations,word-with-punctuations!"), 0, 'Test 290');
test(countValidWords("word-with-digit-at-end1."), 0, 'Test 291');
test(countValidWords("valid-word-!"), 0, 'Test 292');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word@?!#abc-def"), 1, 'Test 293');
test(countValidWords("multiple-hyphens-in--one-word"), 0, 'Test 294');
test(countValidWords("a valid-word- valid-word valid-word-"), 2, 'Test 295');
test(countValidWords("double--hyphen invalid"), 1, 'Test 296');
test(countValidWords("validwordwithmultiplepunctuations..."), 0, 'Test 297');
test(countValidWords("!a-b"), 0, 'Test 298');
test(countValidWords("word! word- word. word@"), 3, 'Test 299');
test(countValidWords("valid-word- valid-word valid-word"), 2, 'Test 300');
test(countValidWords("leading-hyphen invalid-hyphen"), 2, 'Test 301');
test(countValidWords("a.b.c!"), 0, 'Test 302');
test(countValidWords("invalid-word- punctuation-here."), 1, 'Test 303');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def"), 1, 'Test 304');
test(countValidWords("valid-word-here, and-this.is!ok"), 0, 'Test 305');
test(countValidWords("valid-word, valid-word."), 2, 'Test 306');
test(countValidWords("valid-word valid-word valid-word-"), 2, 'Test 307');
test(countValidWords("word-h word-hyphenated word-!"), 2, 'Test 308');
test(countValidWords("another!valid!word"), 0, 'Test 309');
test(countValidWords("word-with.punctuation"), 0, 'Test 310');
test(countValidWords("valid-word- valid-hyphenated-word"), 0, 'Test 311');
test(countValidWords("valid-word word-with-hyphen-"), 1, 'Test 312');
test(countValidWords("word-with-hyphen-and-punctuation! word-with-hyphen-and-punctuation!"), 0, 'Test 313');
test(countValidWords("single-letter a valid-word"), 3, 'Test 314');
test(countValidWords("valid-word-with-hyphen-and-punctuation,"), 0, 'Test 315');
test(countValidWords("word-with-hyphen-and-punctuation."), 0, 'Test 316');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word!"), 1, 'Test 317');
test(countValidWords("end! punctuation"), 2, 'Test 318');
test(countValidWords("word-with-digit-at-end1"), 0, 'Test 319');
test(countValidWords("hyphenated-word-"), 0, 'Test 320');
test(countValidWords("valid-word,"), 1, 'Test 321');
test(countValidWords("-word-with-hyphen"), 0, 'Test 322');
test(countValidWords("only-allowed-here"), 0, 'Test 323');
test(countValidWords("word-with-digit-in-hyphen-1-word"), 0, 'Test 324');
test(countValidWords("mixed-case Words Are Invalid"), 4, 'Test 325');
test(countValidWords("-leading-hyphen"), 0, 'Test 326');
test(countValidWords("word-with-punctuation!at!the!end"), 0, 'Test 327');
test(countValidWords("validwordwithmultiplepunctuations!!!"), 0, 'Test 328');
test(countValidWords("valid-word word-with-hyphen"), 1, 'Test 329');
test(countValidWords("word-with-digit1-and-punctuation,"), 0, 'Test 330');
test(countValidWords("word-with-hyphen123"), 0, 'Test 331');
test(countValidWords("word-with-punctuation!at!end"), 0, 'Test 332');
test(countValidWords("word-hyphenated word- word. word?"), 3, 'Test 333');
test(countValidWords("word-hyphenated-word- word- word. word-123"), 1, 'Test 334');
test(countValidWords("word-with-digit-at-end1,"), 0, 'Test 335');
test(countValidWords("word word- word! word?"), 3, 'Test 336');
test(countValidWords("valid-word,another-valid-word"), 0, 'Test 337');
test(countValidWords("trailing-punctuations,, are! invalid"), 2, 'Test 338');
test(countValidWords("word-with-punctuation!and-more"), 0, 'Test 339');
test(countValidWords("123abc and abc123 are invalid"), 3, 'Test 340');
test(countValidWords("word-with-digit-and-hyphen--b"), 0, 'Test 341');
test(countValidWords("word-with-digit-and-hyphen-b-1"), 0, 'Test 342');
test(countValidWords("valid-word! valid-word, valid-word."), 3, 'Test 343');
test(countValidWords("no-hyphens allowed"), 2, 'Test 344');
test(countValidWords("word-with-digit-and-punctuation-1!"), 0, 'Test 345');
test(countValidWords("multiple    spaces    between words"), 4, 'Test 346');
test(countValidWords("triple-hyphen---word"), 0, 'Test 347');
test(countValidWords("punctuation,,comma and space"), 2, 'Test 348');
test(countValidWords("valid-word-2!"), 0, 'Test 349');
test(countValidWords("word-with-digit1-and-hyphen-b"), 0, 'Test 350');
test(countValidWords("valid-hyphen-word word- word"), 1, 'Test 351');
test(countValidWords("word- word- word- word."), 1, 'Test 352');
test(countValidWords("word!!"), 0, 'Test 353');
test(countValidWords("trailing-hyphen-"), 0, 'Test 354');
test(countValidWords("word-hyphenated-word- word- word. word-123@"), 1, 'Test 355');
test(countValidWords("word- word- word- word"), 1, 'Test 356');
test(countValidWords("word-!!"), 0, 'Test 357');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-123"), 1, 'Test 358');
test(countValidWords("word-with-digit-and-punctuation1!"), 0, 'Test 359');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#"), 1, 'Test 360');
test(countValidWords("word-with-multiple-punctuations!!!"), 0, 'Test 361');
test(countValidWords("word-with-punctuations!."), 0, 'Test 362');
test(countValidWords("word1- word2- word3- word4-"), 0, 'Test 363');
test(countValidWords("multiple--hyphens-are!invalid"), 0, 'Test 364');
test(countValidWords("word-hyphenated-word- word- word. word-123@?!#abc-def,word@?!#abc-def,word@?!#abc123"), 1, 'Test 365');
test(countValidWords("valid-word- valid-word- valid-word-"), 0, 'Test 366');
test(countValidWords("valid-word-with-punctuation-at-end."), 0, 'Test 367');
test(countValidWords("word-with-digit-and-hyphen1-b"), 0, 'Test 368');
test(countValidWords("multi-hyphen-usage-is-not-allowed"), 0, 'Test 369');
test(countValidWords("word-with! punctuation"), 2, 'Test 370');
test(countValidWords("valid-word valid-word valid-word"), 3, 'Test 371');
test(countValidWords("valid-word-1 valid-word-2 valid-word-3"), 0, 'Test 372');
test(countValidWords("word-with-punctuations,word-with-punctuations,word-with-punctuations,word-with-punctuations!"), 0, 'Test 373');
test(countValidWords("word-with-digit-in-hyphen-word-1"), 0, 'Test 374');
test(countValidWords("word-"), 0, 'Test 375');
test(countValidWords("word-with-digit-and-hyphen-1-b"), 0, 'Test 376');
test(countValidWords("valid,word valid.word valid-word!"), 1, 'Test 377');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

