// Test: 187. Repeated Dna Sequences
// 137 test cases from LeetCodeDataset
// Run: node test.js

const { findRepeatedDnaSequences } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n187. Repeated Dna Sequences\n");

test(findRepeatedDnaSequences("ACGACGACGACGACGACG"), ['ACGACGACGA', 'CGACGACGAC', 'GACGACGACG'], 'Test 1');
test(findRepeatedDnaSequences("AAAAAAAAAAAAA"), ['AAAAAAAAAA'], 'Test 2');
test(findRepeatedDnaSequences("AAAAACCCCCAAAAACCCCCCAAAAAGGGTTT"), ['AAAAACCCCC', 'CCCCCAAAAA'], 'Test 3');
test(findRepeatedDnaSequences("CGTTGCGTTGCGTTGCGTTG"), ['CGTTGCGTTG', 'GTTGCGTTGC', 'TTGCGTTGCG', 'TGCGTTGCGT', 'GCGTTGCGTT'], 'Test 4');
test(findRepeatedDnaSequences("AAAAAAAAAATTTTTTTTTTAAAAAAAAAA"), ['AAAAAAAAAA'], 'Test 5');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 6');
test(findRepeatedDnaSequences("CGCGCGCGCGCGCGCGCGCG"), ['CGCGCGCGCG', 'GCGCGCGCGC'], 'Test 7');
test(findRepeatedDnaSequences("ACGTTTACGTTTACGTTT"), ['ACGTTTACGT', 'CGTTTACGTT', 'GTTTACGTTT'], 'Test 8');
test(findRepeatedDnaSequences("ACGACGACGACGACGACGACGACGACG"), ['ACGACGACGA', 'CGACGACGAC', 'GACGACGACG'], 'Test 9');
test(findRepeatedDnaSequences("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"), ['AAAAAAAAAA'], 'Test 10');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 11');
test(findRepeatedDnaSequences("TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"), ['TTTTTTTTTT'], 'Test 12');
test(findRepeatedDnaSequences("ACGTACGTACGTACGT"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT'], 'Test 13');
test(findRepeatedDnaSequences("ACGACGACGACGACGACGACGACGACGACG"), ['ACGACGACGA', 'CGACGACGAC', 'GACGACGACG'], 'Test 14');
test(findRepeatedDnaSequences("AAAAAAAAAAAACCCCCCCCCC"), ['AAAAAAAAAA'], 'Test 15');
test(findRepeatedDnaSequences("GGGGGGGGGGGGGGGGGGGG"), ['GGGGGGGGGG'], 'Test 16');
test(findRepeatedDnaSequences("ACGTCGTCGTCGTCGT"), ['CGTCGTCGTC', 'GTCGTCGTCG', 'TCGTCGTCGT'], 'Test 17');
test(findRepeatedDnaSequences("AAAAAAAAAAACCCCCCCCCCAAAAAAAAA"), ['AAAAAAAAAA'], 'Test 18');
test(findRepeatedDnaSequences("TTTTTTTTTTAAAAAAAAAA"), [], 'Test 19');
test(findRepeatedDnaSequences("TTAGGGTTAGGGTTAGGG"), ['TTAGGGTTAG', 'TAGGGTTAGG', 'AGGGTTAGGG'], 'Test 20');
test(findRepeatedDnaSequences("AAAAAAAAAAAGGGGGGGGGGG"), ['AAAAAAAAAA', 'GGGGGGGGGG'], 'Test 21');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGTACG"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 22');
test(findRepeatedDnaSequences("ACGACGACGACGACGACGACGACGACGACGACGACGACGACG"), ['ACGACGACGA', 'CGACGACGAC', 'GACGACGACG'], 'Test 23');
test(findRepeatedDnaSequences("AAAAAAAAAAACCCCCCCAAAAAAAAAACCCCCCCCCCCC"), ['AAAAAAAAAA', 'AAAAAAAAAC', 'AAAAAAAACC', 'AAAAAAACCC', 'AAAAAACCCC', 'AAAAACCCCC', 'AAAACCCCCC', 'AAACCCCCCC', 'CCCCCCCCCC'], 'Test 24');
test(findRepeatedDnaSequences("TTAGGGTACCTAGGGTACCTAGGGTACC"), ['TAGGGTACCT', 'AGGGTACCTA', 'GGGTACCTAG', 'GGTACCTAGG', 'GTACCTAGGG', 'TACCTAGGGT', 'ACCTAGGGTA', 'CCTAGGGTAC', 'CTAGGGTACC'], 'Test 25');
test(findRepeatedDnaSequences("ATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATAT"), ['ATATATATAT', 'TATATATATA'], 'Test 26');
test(findRepeatedDnaSequences("CCAGTTACCGGGTAAAGGGCCCTAAAGGGCCCTAAAGGGCCCTAAAGGGCCC"), ['TAAAGGGCCC', 'AAAGGGCCCT', 'AAGGGCCCTA', 'AGGGCCCTAA', 'GGGCCCTAAA', 'GGCCCTAAAG', 'GCCCTAAAGG', 'CCCTAAAGGG', 'CCTAAAGGGC', 'CTAAAGGGCC'], 'Test 27');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTA"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 28');
test(findRepeatedDnaSequences("GCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTA"), ['GCTAGCTAGC', 'CTAGCTAGCT', 'TAGCTAGCTA', 'AGCTAGCTAG'], 'Test 29');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTTACGTACGTACGTACGT"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 30');
test(findRepeatedDnaSequences("TTACGTACGTACGTACGTACGTACGTACGTAC"), ['TACGTACGTA', 'ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT'], 'Test 31');
test(findRepeatedDnaSequences("GTCAGTCAGTCAGTCAGTCAGTCAGTCAGTCAGTCA"), ['GTCAGTCAGT', 'TCAGTCAGTC', 'CAGTCAGTCA', 'AGTCAGTCAG'], 'Test 32');
test(findRepeatedDnaSequences("AAAAACCCCCAAAAAAAAAAAAACCCCCAAAA"), ['AAAAAAAAAA', 'AAAAACCCCC', 'AAAACCCCCA', 'AAACCCCCAA', 'AACCCCCAAA', 'ACCCCCAAAA'], 'Test 33');
test(findRepeatedDnaSequences("AAAAAAAAAAACCCCCCCCCCAAAAAAAAAAAACCCCCCCCCCAGGGGGGGGGG"), ['AAAAAAAAAA', 'AAAAAAAAAC', 'AAAAAAAACC', 'AAAAAAACCC', 'AAAAAACCCC', 'AAAAACCCCC', 'AAAACCCCCC', 'AAACCCCCCC', 'AACCCCCCCC', 'ACCCCCCCCC', 'CCCCCCCCCC', 'CCCCCCCCCA'], 'Test 34');
test(findRepeatedDnaSequences("AGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCT"), ['AGCTAGCTAG', 'GCTAGCTAGC', 'CTAGCTAGCT', 'TAGCTAGCTA'], 'Test 35');
test(findRepeatedDnaSequences("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"), ['GGGGGGGGGG'], 'Test 36');
test(findRepeatedDnaSequences("ACCTGACCTGACCTGACCTGACCTGACCTGACCTGACCTG"), ['ACCTGACCTG', 'CCTGACCTGA', 'CTGACCTGAC', 'TGACCTGACC', 'GACCTGACCT'], 'Test 37');
test(findRepeatedDnaSequences("GACGTGACGTGACGTGACGTGACGTGACGTGACGTGACG"), ['GACGTGACGT', 'ACGTGACGTG', 'CGTGACGTGA', 'GTGACGTGAC', 'TGACGTGACG'], 'Test 38');
test(findRepeatedDnaSequences("AACCGGTTAACCGGTTAACCGGTTAACCGGTTAACCGGTT"), ['AACCGGTTAA', 'ACCGGTTAAC', 'CCGGTTAACC', 'CGGTTAACCG', 'GGTTAACCGG', 'GTTAACCGGT', 'TTAACCGGTT', 'TAACCGGTTA'], 'Test 39');
test(findRepeatedDnaSequences("GAAAAAAAAATTTTTTTTTTAAAAAAAAAA"), [], 'Test 40');
test(findRepeatedDnaSequences("AGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCT"), ['AGCTAGCTAG', 'GCTAGCTAGC', 'CTAGCTAGCT', 'TAGCTAGCTA'], 'Test 41');
test(findRepeatedDnaSequences("AGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTA"), ['AGCTAGCTAG', 'GCTAGCTAGC', 'CTAGCTAGCT', 'TAGCTAGCTA'], 'Test 42');
test(findRepeatedDnaSequences("AAAAAGGGGGAAAAAGGGGGCCCCCATTTTTT"), ['AAAAAGGGGG'], 'Test 43');
test(findRepeatedDnaSequences("TTTTACGTTTACGTTTACGTTTACGTTTACGTTTACGTTTACGTTTACGTTTACGTTT"), ['TTTACGTTTA', 'TTACGTTTAC', 'TACGTTTACG', 'ACGTTTACGT', 'CGTTTACGTT', 'GTTTACGTTT'], 'Test 44');
test(findRepeatedDnaSequences("GGGGGGGGGGTTGGGGGGGGTTGGGGGGGGTTGGGGGG"), ['GGGGGGGGTT', 'GGGGGGGTTG', 'GGGGGGTTGG', 'GGGGGTTGGG', 'GGGGTTGGGG', 'GGGTTGGGGG', 'GGTTGGGGGG', 'GTTGGGGGGG', 'TTGGGGGGGG', 'TGGGGGGGGT'], 'Test 45');
test(findRepeatedDnaSequences("ACGACGACGACGACGACGACGACGACGACGACG"), ['ACGACGACGA', 'CGACGACGAC', 'GACGACGACG'], 'Test 46');
test(findRepeatedDnaSequences("AAAAAAAAAAGGGGGGGGGGAAAAAAAAAAGGGG"), ['AAAAAAAAAA', 'AAAAAAAAAG', 'AAAAAAAAGG', 'AAAAAAAGGG', 'AAAAAAGGGG'], 'Test 47');
test(findRepeatedDnaSequences("CCCCCCCCCCGGCCCCCCCCCCGGCCCCCCCCCCGG"), ['CCCCCCCCCC', 'CCCCCCCCCG', 'CCCCCCCCGG', 'CCCCCCCGGC', 'CCCCCCGGCC', 'CCCCCGGCCC', 'CCCCGGCCCC', 'CCCGGCCCCC', 'CCGGCCCCCC', 'CGGCCCCCCC', 'GGCCCCCCCC', 'GCCCCCCCCC'], 'Test 48');
test(findRepeatedDnaSequences("ATATATATATACGTACGTACGTACGTACGTACGT"), ['TACGTACGTA', 'ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT'], 'Test 49');
test(findRepeatedDnaSequences("GATACAGTACAGTACAGTACAGTACAGTACAGTACAGTACAGTACAGTACAGTACAGTAC"), ['TACAGTACAG', 'ACAGTACAGT', 'CAGTACAGTA', 'AGTACAGTAC', 'GTACAGTACA'], 'Test 50');
test(findRepeatedDnaSequences("TCGATCGATCGATCGATCGATCGATCGATCGA"), ['TCGATCGATC', 'CGATCGATCG', 'GATCGATCGA', 'ATCGATCGAT'], 'Test 51');
test(findRepeatedDnaSequences("ACGTACGTTACGTACGTTACGTACGTTACGTACGTTACGTACGTT"), ['ACGTACGTTA', 'CGTACGTTAC', 'GTACGTTACG', 'TACGTTACGT', 'ACGTTACGTA', 'CGTTACGTAC', 'GTTACGTACG', 'TTACGTACGT', 'TACGTACGTT'], 'Test 52');
test(findRepeatedDnaSequences("ACCGGTTTAAACCGGTTTAAACCGGTTTAA"), ['ACCGGTTTAA', 'CCGGTTTAAA', 'CGGTTTAAAC', 'GGTTTAAACC', 'GTTTAAACCG', 'TTTAAACCGG', 'TTAAACCGGT', 'TAAACCGGTT', 'AAACCGGTTT', 'AACCGGTTTA'], 'Test 53');
test(findRepeatedDnaSequences("TTTTAAAAATTTTTAAAAATTTTTAAAAATTTTTAAAAATTTTTAAAAATTTTTAAAAA"), ['TTTTAAAAAT', 'TTTAAAAATT', 'TTAAAAATTT', 'TAAAAATTTT', 'AAAAATTTTT', 'AAAATTTTTA', 'AAATTTTTAA', 'AATTTTTAAA', 'ATTTTTAAAA', 'TTTTTAAAAA'], 'Test 54');
test(findRepeatedDnaSequences("ACCGGTTTAAACCGGTTTAAACCGGTTTAAACCGGTTTAAACCGGTTTA"), ['ACCGGTTTAA', 'CCGGTTTAAA', 'CGGTTTAAAC', 'GGTTTAAACC', 'GTTTAAACCG', 'TTTAAACCGG', 'TTAAACCGGT', 'TAAACCGGTT', 'AAACCGGTTT', 'AACCGGTTTA'], 'Test 55');
test(findRepeatedDnaSequences("ACGCGTACGCGTACGCGTACGCGTACGCGTACGCGT"), ['ACGCGTACGC', 'CGCGTACGCG', 'GCGTACGCGT', 'CGTACGCGTA', 'GTACGCGTAC', 'TACGCGTACG'], 'Test 56');
test(findRepeatedDnaSequences("GAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGA"), ['GAGAGAGAGA', 'AGAGAGAGAG'], 'Test 57');
test(findRepeatedDnaSequences("ACACACACACACACACACACACACACACACAC"), ['ACACACACAC', 'CACACACACA'], 'Test 58');
test(findRepeatedDnaSequences("CGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGAT"), ['CGATCGATCG', 'GATCGATCGA', 'ATCGATCGAT', 'TCGATCGATC'], 'Test 59');
test(findRepeatedDnaSequences("AAACCGGGTTAAACCGGGTTAAACCGGGTT"), ['AAACCGGGTT', 'AACCGGGTTA', 'ACCGGGTTAA', 'CCGGGTTAAA', 'CGGGTTAAAC', 'GGGTTAAACC', 'GGTTAAACCG', 'GTTAAACCGG', 'TTAAACCGGG', 'TAAACCGGGT'], 'Test 60');
test(findRepeatedDnaSequences("TTTTTTTTTTCCTTTTTTTTCCTTTTTTTTCCTTTTTT"), ['TTTTTTTTCC', 'TTTTTTTCCT', 'TTTTTTCCTT', 'TTTTTCCTTT', 'TTTTCCTTTT', 'TTTCCTTTTT', 'TTCCTTTTTT', 'TCCTTTTTTT', 'CCTTTTTTTT', 'CTTTTTTTTC'], 'Test 61');
test(findRepeatedDnaSequences("ACACACACACACACACACACACACACACACACACACACAC"), ['ACACACACAC', 'CACACACACA'], 'Test 62');
test(findRepeatedDnaSequences("ATATATATATATATATATATATATATATATATAT"), ['ATATATATAT', 'TATATATATA'], 'Test 63');
test(findRepeatedDnaSequences("TATATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"), ['AAAAAAAAAA'], 'Test 64');
test(findRepeatedDnaSequences("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"), ['AAAAAAAAAA'], 'Test 65');
test(findRepeatedDnaSequences("TGCCTGCCTGCCTGCCTGCCTGCC"), ['TGCCTGCCTG', 'GCCTGCCTGC', 'CCTGCCTGCC', 'CTGCCTGCCT'], 'Test 66');
test(findRepeatedDnaSequences("CGTACGTAACGTACGTAACGTACGTAACGTAC"), ['CGTACGTAAC', 'GTACGTAACG', 'TACGTAACGT', 'ACGTAACGTA', 'CGTAACGTAC', 'GTAACGTACG', 'TAACGTACGT', 'AACGTACGTA', 'ACGTACGTAA'], 'Test 67');
test(findRepeatedDnaSequences("ACCGGTTTAAACCGGTTTAAACCGGTTTAAACCGGTTTAAACCGGTTTAA"), ['ACCGGTTTAA', 'CCGGTTTAAA', 'CGGTTTAAAC', 'GGTTTAAACC', 'GTTTAAACCG', 'TTTAAACCGG', 'TTAAACCGGT', 'TAAACCGGTT', 'AAACCGGTTT', 'AACCGGTTTA'], 'Test 68');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTATATATATACGTACGTAC"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 69');
test(findRepeatedDnaSequences("AAAAAAAAAAACCCCCCCCCGGGGGGGGGGTTTTTTTTTTAAAAAAAAAAACCCCCCCCCGGGGGGGGGGTTTTTTTTTT"), ['AAAAAAAAAA', 'AAAAAAAAAC', 'AAAAAAAACC', 'AAAAAAACCC', 'AAAAAACCCC', 'AAAAACCCCC', 'AAAACCCCCC', 'AAACCCCCCC', 'AACCCCCCCC', 'ACCCCCCCCC', 'CCCCCCCCCG', 'CCCCCCCCGG', 'CCCCCCCGGG', 'CCCCCCGGGG', 'CCCCCGGGGG', 'CCCCGGGGGG', 'CCCGGGGGGG', 'CCGGGGGGGG', 'CGGGGGGGGG', 'GGGGGGGGGG', 'GGGGGGGGGT', 'GGGGGGGGTT', 'GGGGGGGTTT', 'GGGGGGTTTT', 'GGGGGTTTTT', 'GGGGTTTTTT', 'GGGTTTTTTT', 'GGTTTTTTTT', 'GTTTTTTTTT', 'TTTTTTTTTT'], 'Test 70');
test(findRepeatedDnaSequences("ATATATATATATATATATATATATATATATAT"), ['ATATATATAT', 'TATATATATA'], 'Test 71');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 72');
test(findRepeatedDnaSequences("ATCGATCGATCGATCGATCGATCGATCGATCGATCG"), ['ATCGATCGAT', 'TCGATCGATC', 'CGATCGATCG', 'GATCGATCGA'], 'Test 73');
test(findRepeatedDnaSequences("AAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGG"), ['AAAAAAAAAA', 'GGGGGGGGGG'], 'Test 74');
test(findRepeatedDnaSequences("AAAAAAAAAACAAAAAAAAAACAAAAAAAAAACAAAAAAA"), ['AAAAAAAAAA', 'AAAAAAAAAC', 'AAAAAAAACA', 'AAAAAAACAA', 'AAAAAACAAA', 'AAAAACAAAA', 'AAAACAAAAA', 'AAACAAAAAA', 'AACAAAAAAA', 'ACAAAAAAAA', 'CAAAAAAAAA'], 'Test 75');
test(findRepeatedDnaSequences("AAAAAAAAAAACAAAAAAAAAAACAAAAAAAAAAAC"), ['AAAAAAAAAA', 'AAAAAAAAAC', 'AAAAAAAACA', 'AAAAAAACAA', 'AAAAAACAAA', 'AAAAACAAAA', 'AAAACAAAAA', 'AAACAAAAAA', 'AACAAAAAAA', 'ACAAAAAAAA', 'CAAAAAAAAA'], 'Test 76');
test(findRepeatedDnaSequences("AGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCT"), ['AGCTAGCTAG', 'GCTAGCTAGC', 'CTAGCTAGCT', 'TAGCTAGCTA'], 'Test 77');
test(findRepeatedDnaSequences("CCCGGGCCCGGGCCCGGGCCCGGGCCCGGGCCCGGGCCCGGG"), ['CCCGGGCCCG', 'CCGGGCCCGG', 'CGGGCCCGGG', 'GGGCCCGGGC', 'GGCCCGGGCC', 'GCCCGGGCCC'], 'Test 78');
test(findRepeatedDnaSequences("GCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTG"), ['GCTGCTGCTG', 'CTGCTGCTGC', 'TGCTGCTGCT'], 'Test 79');
test(findRepeatedDnaSequences("ATATATATATATATATATATATATATAT"), ['ATATATATAT', 'TATATATATA'], 'Test 80');
test(findRepeatedDnaSequences("ACGTTTACGTTTACGTTTACGTTTACGTTTACGTTTACGTTTACGTTTACGTTTACGTTT"), ['ACGTTTACGT', 'CGTTTACGTT', 'GTTTACGTTT', 'TTTACGTTTA', 'TTACGTTTAC', 'TACGTTTACG'], 'Test 81');
test(findRepeatedDnaSequences("GGGGGGGGGGAAAAAAAAAACCCCCCCCCCGGGGGGGGGGAAAAAAAAAACCCCCCCCCCGGGGGGGGGG"), ['GGGGGGGGGG', 'GGGGGGGGGA', 'GGGGGGGGAA', 'GGGGGGGAAA', 'GGGGGGAAAA', 'GGGGGAAAAA', 'GGGGAAAAAA', 'GGGAAAAAAA', 'GGAAAAAAAA', 'GAAAAAAAAA', 'AAAAAAAAAA', 'AAAAAAAAAC', 'AAAAAAAACC', 'AAAAAAACCC', 'AAAAAACCCC', 'AAAAACCCCC', 'AAAACCCCCC', 'AAACCCCCCC', 'AACCCCCCCC', 'ACCCCCCCCC', 'CCCCCCCCCC', 'CCCCCCCCCG', 'CCCCCCCCGG', 'CCCCCCCGGG', 'CCCCCCGGGG', 'CCCCCGGGGG', 'CCCCGGGGGG', 'CCCGGGGGGG', 'CCGGGGGGGG', 'CGGGGGGGGG'], 'Test 82');
test(findRepeatedDnaSequences("TTTTACCGGGAAAAACCGGGAAAAACCGGGAAAA"), ['ACCGGGAAAA', 'CCGGGAAAAA', 'CGGGAAAAAC', 'GGGAAAAACC', 'GGAAAAACCG', 'GAAAAACCGG', 'AAAAACCGGG', 'AAAACCGGGA', 'AAACCGGGAA', 'AACCGGGAAA'], 'Test 83');
test(findRepeatedDnaSequences("TACGTACGTACGTACGTACGTACGTACGTACG"), ['TACGTACGTA', 'ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT'], 'Test 84');
test(findRepeatedDnaSequences("AGTACAGTACAGTACAGTACAGTACAGTACAGTACAGTACAGTACAGTACAGTACAGTAC"), ['AGTACAGTAC', 'GTACAGTACA', 'TACAGTACAG', 'ACAGTACAGT', 'CAGTACAGTA'], 'Test 85');
test(findRepeatedDnaSequences("GCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTA"), ['GCTAGCTAGC', 'CTAGCTAGCT', 'TAGCTAGCTA', 'AGCTAGCTAG'], 'Test 86');
test(findRepeatedDnaSequences("TTTTTTTTTTAAAAAAAAAAAATTTTTTTTTTAAAAAAAAAAAATTTTT"), ['AAAAAAAAAA', 'TTTTTTTTTT', 'TTTTTTTTTA', 'TTTTTTTTAA', 'TTTTTTTAAA', 'TTTTTTAAAA', 'TTTTTAAAAA', 'TTTTAAAAAA', 'TTTAAAAAAA', 'TTAAAAAAAA', 'TAAAAAAAAA', 'AAAAAAAAAT', 'AAAAAAAATT', 'AAAAAAATTT', 'AAAAAATTTT', 'AAAAATTTTT'], 'Test 87');
test(findRepeatedDnaSequences("CCCCGGGGAAGGGGCCCCGGGGAAGGGGCCCCGGGGAAGGGGCCCCGGGGAAGGGG"), ['CCCCGGGGAA', 'CCCGGGGAAG', 'CCGGGGAAGG', 'CGGGGAAGGG', 'GGGGAAGGGG', 'GGGAAGGGGC', 'GGAAGGGGCC', 'GAAGGGGCCC', 'AAGGGGCCCC', 'AGGGGCCCCG', 'GGGGCCCCGG', 'GGGCCCCGGG', 'GGCCCCGGGG', 'GCCCCGGGGA'], 'Test 88');
test(findRepeatedDnaSequences("AAAAAAAAAAAAAAACCCCCCCCCCCCCCCCCCCCCCC"), ['AAAAAAAAAA', 'CCCCCCCCCC'], 'Test 89');
test(findRepeatedDnaSequences("AAAAAAAAAAAACCCCCCCCCCAAAAAAAAAAAACCCCCCCCCC"), ['AAAAAAAAAA', 'AAAAAAAAAC', 'AAAAAAAACC', 'AAAAAAACCC', 'AAAAAACCCC', 'AAAAACCCCC', 'AAAACCCCCC', 'AAACCCCCCC', 'AACCCCCCCC', 'ACCCCCCCCC', 'CCCCCCCCCC'], 'Test 90');
test(findRepeatedDnaSequences("AAAAAAAAAAAACCCCCCCCCCGGGGGGGGGGTTTTTTTTTTAAAAAAAAAAAACCCCCCCCCCGGGGGGGGGGTTTTTTTTTT"), ['AAAAAAAAAA', 'AAAAAAAAAC', 'AAAAAAAACC', 'AAAAAAACCC', 'AAAAAACCCC', 'AAAAACCCCC', 'AAAACCCCCC', 'AAACCCCCCC', 'AACCCCCCCC', 'ACCCCCCCCC', 'CCCCCCCCCC', 'CCCCCCCCCG', 'CCCCCCCCGG', 'CCCCCCCGGG', 'CCCCCCGGGG', 'CCCCCGGGGG', 'CCCCGGGGGG', 'CCCGGGGGGG', 'CCGGGGGGGG', 'CGGGGGGGGG', 'GGGGGGGGGG', 'GGGGGGGGGT', 'GGGGGGGGTT', 'GGGGGGGTTT', 'GGGGGGTTTT', 'GGGGGTTTTT', 'GGGGTTTTTT', 'GGGTTTTTTT', 'GGTTTTTTTT', 'GTTTTTTTTT', 'TTTTTTTTTT'], 'Test 91');
test(findRepeatedDnaSequences("AGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCT"), ['AGCTAGCTAG', 'GCTAGCTAGC', 'CTAGCTAGCT', 'TAGCTAGCTA'], 'Test 92');
test(findRepeatedDnaSequences("ACGTACGTTTTACGTTTTACGTTTTACGTTTT"), ['TACGTTTTAC', 'ACGTTTTACG', 'CGTTTTACGT', 'GTTTTACGTT', 'TTTTACGTTT', 'TTTACGTTTT', 'TTACGTTTTA'], 'Test 93');
test(findRepeatedDnaSequences("GAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGA"), ['GAGAGAGAGA', 'AGAGAGAGAG'], 'Test 94');
test(findRepeatedDnaSequences("ACGTCGTTTTTACGTCGTTTTTACGTCGTTTTTACGTCGTTTTT"), ['ACGTCGTTTT', 'CGTCGTTTTT', 'GTCGTTTTTA', 'TCGTTTTTAC', 'CGTTTTTACG', 'GTTTTTACGT', 'TTTTTACGTC', 'TTTTACGTCG', 'TTTACGTCGT', 'TTACGTCGTT', 'TACGTCGTTT'], 'Test 95');
test(findRepeatedDnaSequences("ACGTACGTACGTATATATATACGTACGTACGTAT"), ['TACGTACGTA', 'ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'ACGTACGTAT'], 'Test 96');
test(findRepeatedDnaSequences("TACGTACGTACGTACGTACGTACGTACGTACGTACGT"), ['TACGTACGTA', 'ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT'], 'Test 97');
test(findRepeatedDnaSequences("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"), ['AAAAAAAAAA'], 'Test 98');
test(findRepeatedDnaSequences("TTTACCGGAAAACCGGAAAACCGGAAAACCGGAAAACCGG"), ['ACCGGAAAAC', 'CCGGAAAACC', 'CGGAAAACCG', 'GGAAAACCGG', 'GAAAACCGGA', 'AAAACCGGAA', 'AAACCGGAAA', 'AACCGGAAAA'], 'Test 99');
test(findRepeatedDnaSequences("AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG"), ['AGAGAGAGAG', 'GAGAGAGAGA'], 'Test 100');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 101');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGTACGT"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 102');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGT"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 103');
test(findRepeatedDnaSequences("AAAAAAAAAAAACCCCCCCCCCAAAAAAAAAACCCCCCCCCC"), ['AAAAAAAAAA', 'AAAAAAAAAC', 'AAAAAAAACC', 'AAAAAAACCC', 'AAAAAACCCC', 'AAAAACCCCC', 'AAAACCCCCC', 'AAACCCCCCC', 'AACCCCCCCC', 'ACCCCCCCCC', 'CCCCCCCCCC'], 'Test 104');
test(findRepeatedDnaSequences("TACGTACGTACGTACGTACGTACGTACGTACGTACGTACG"), ['TACGTACGTA', 'ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT'], 'Test 105');
test(findRepeatedDnaSequences("AAAAACCCCCAAAAACCCCCAAAAACCCCCAAAAACCCCC"), ['AAAAACCCCC', 'AAAACCCCCA', 'AAACCCCCAA', 'AACCCCCAAA', 'ACCCCCAAAA', 'CCCCCAAAAA', 'CCCCAAAAAC', 'CCCAAAAACC', 'CCAAAAACCC', 'CAAAAACCCC'], 'Test 106');
test(findRepeatedDnaSequences("AAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"), ['AAAAAAAAAA', 'GGGGGGGGGG'], 'Test 107');
test(findRepeatedDnaSequences("ACGTTTACGTTTACGTTTACGTTTACGTTTACGTTTACGTTTACGTTT"), ['ACGTTTACGT', 'CGTTTACGTT', 'GTTTACGTTT', 'TTTACGTTTA', 'TTACGTTTAC', 'TACGTTTACG'], 'Test 108');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 109');
test(findRepeatedDnaSequences("ACGTTTACGTTTACGTTTACGTTTACGTTTACGTTT"), ['ACGTTTACGT', 'CGTTTACGTT', 'GTTTACGTTT', 'TTTACGTTTA', 'TTACGTTTAC', 'TACGTTTACG'], 'Test 110');
test(findRepeatedDnaSequences("TTTTTTTTTTGGGGGGGGGGTTTTTTTTTTGGGGGGGGGG"), ['TTTTTTTTTT', 'TTTTTTTTTG', 'TTTTTTTTGG', 'TTTTTTTGGG', 'TTTTTTGGGG', 'TTTTTGGGGG', 'TTTTGGGGGG', 'TTTGGGGGGG', 'TTGGGGGGGG', 'TGGGGGGGGG', 'GGGGGGGGGG'], 'Test 111');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGTACGTACGT"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 112');
test(findRepeatedDnaSequences("GCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTA"), ['GCTAGCTAGC', 'CTAGCTAGCT', 'TAGCTAGCTA', 'AGCTAGCTAG'], 'Test 113');
test(findRepeatedDnaSequences("CGTACGTACGTACGTACGTACGTACGTACGTACGTAC"), ['CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA', 'ACGTACGTAC'], 'Test 114');
test(findRepeatedDnaSequences("TATATATATATATATATATATATATATATATATATATATATATA"), ['TATATATATA', 'ATATATATAT'], 'Test 115');
test(findRepeatedDnaSequences("GTACGTACGTACGTACGTACGTACGTACGTACGTACG"), ['GTACGTACGT', 'TACGTACGTA', 'ACGTACGTAC', 'CGTACGTACG'], 'Test 116');
test(findRepeatedDnaSequences("TGACGTGACGTGACGTGACGTGACGTGACGTGACGTGAC"), ['TGACGTGACG', 'GACGTGACGT', 'ACGTGACGTG', 'CGTGACGTGA', 'GTGACGTGAC'], 'Test 117');
test(findRepeatedDnaSequences("TACGTACGTACGTACGTACGTACGTACGTACGTAC"), ['TACGTACGTA', 'ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT'], 'Test 118');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGTACGTACGTAC"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 119');
test(findRepeatedDnaSequences("TTTTTTTTTTGGGGGGGGGGAAAAAAAAAATTTTTTTTTTGGGGGGGGGG"), ['TTTTTTTTTT', 'TTTTTTTTTG', 'TTTTTTTTGG', 'TTTTTTTGGG', 'TTTTTTGGGG', 'TTTTTGGGGG', 'TTTTGGGGGG', 'TTTGGGGGGG', 'TTGGGGGGGG', 'TGGGGGGGGG', 'GGGGGGGGGG'], 'Test 120');
test(findRepeatedDnaSequences("AAAAAAAAAAAAACCCCCCCCCCCCCCCGGGGGGGGGGGGGG"), ['AAAAAAAAAA', 'CCCCCCCCCC', 'GGGGGGGGGG'], 'Test 121');
test(findRepeatedDnaSequences("ACGGTACGGTACGGTACGGTACGGTACGGTACGGTACGGT"), ['ACGGTACGGT', 'CGGTACGGTA', 'GGTACGGTAC', 'GTACGGTACG', 'TACGGTACGG'], 'Test 122');
test(findRepeatedDnaSequences("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"), ['GGGGGGGGGG'], 'Test 123');
test(findRepeatedDnaSequences("AGACGTAGACGTAGACGTAGACGTAGACGTAGACGTAG"), ['AGACGTAGAC', 'GACGTAGACG', 'ACGTAGACGT', 'CGTAGACGTA', 'GTAGACGTAG', 'TAGACGTAGA'], 'Test 124');
test(findRepeatedDnaSequences("TTTTTTTTTTAAAAAAAAAACCCCCCCCCCGGGGGGGGGGTTTTTTTTTTAAAAAAAAAACCCCCCCCCCGGGGGGGGGG"), ['TTTTTTTTTT', 'TTTTTTTTTA', 'TTTTTTTTAA', 'TTTTTTTAAA', 'TTTTTTAAAA', 'TTTTTAAAAA', 'TTTTAAAAAA', 'TTTAAAAAAA', 'TTAAAAAAAA', 'TAAAAAAAAA', 'AAAAAAAAAA', 'AAAAAAAAAC', 'AAAAAAAACC', 'AAAAAAACCC', 'AAAAAACCCC', 'AAAAACCCCC', 'AAAACCCCCC', 'AAACCCCCCC', 'AACCCCCCCC', 'ACCCCCCCCC', 'CCCCCCCCCC', 'CCCCCCCCCG', 'CCCCCCCCGG', 'CCCCCCCGGG', 'CCCCCCGGGG', 'CCCCCGGGGG', 'CCCCGGGGGG', 'CCCGGGGGGG', 'CCGGGGGGGG', 'CGGGGGGGGG', 'GGGGGGGGGG'], 'Test 125');
test(findRepeatedDnaSequences("ACGGTGACGGTGACGGTGACGGTGACGGTGACGGTG"), ['ACGGTGACGG', 'CGGTGACGGT', 'GGTGACGGTG', 'GTGACGGTGA', 'TGACGGTGAC', 'GACGGTGACG'], 'Test 126');
test(findRepeatedDnaSequences("AAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"), ['GGGGGGGGGG'], 'Test 127');
test(findRepeatedDnaSequences("ACGACGACGACGACGACGACGACGACGACGACGACGACGACGACGACGACGACGACGACGACGACG"), ['ACGACGACGA', 'CGACGACGAC', 'GACGACGACG'], 'Test 128');
test(findRepeatedDnaSequences("GCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGC"), ['GCGCGCGCGC', 'CGCGCGCGCG'], 'Test 129');
test(findRepeatedDnaSequences("ACGTTTACGTTTACGTTTACGTTTACGTTTACGTTTACGTTT"), ['ACGTTTACGT', 'CGTTTACGTT', 'GTTTACGTTT', 'TTTACGTTTA', 'TTACGTTTAC', 'TACGTTTACG'], 'Test 130');
test(findRepeatedDnaSequences("ACGAATTCCGACGAATTCCGACGAATTCCGACGAATTCCG"), ['ACGAATTCCG', 'CGAATTCCGA', 'GAATTCCGAC', 'AATTCCGACG', 'ATTCCGACGA', 'TTCCGACGAA', 'TCCGACGAAT', 'CCGACGAATT', 'CGACGAATTC', 'GACGAATTCC'], 'Test 131');
test(findRepeatedDnaSequences("GATTACAAGATTACAAGATTACAAGATTACAAGATTAC"), ['GATTACAAGA', 'ATTACAAGAT', 'TTACAAGATT', 'TACAAGATTA', 'ACAAGATTAC', 'CAAGATTACA', 'AAGATTACAA', 'AGATTACAAG'], 'Test 132');
test(findRepeatedDnaSequences("GCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTA"), ['GCTAGCTAGC', 'CTAGCTAGCT', 'TAGCTAGCTA', 'AGCTAGCTAG'], 'Test 133');
test(findRepeatedDnaSequences("ACGACGTTTTACGACGTTTTACGACGTTTT"), ['ACGACGTTTT', 'CGACGTTTTA', 'GACGTTTTAC', 'ACGTTTTACG', 'CGTTTTACGA', 'GTTTTACGAC', 'TTTTACGACG', 'TTTACGACGT', 'TTACGACGTT', 'TACGACGTTT'], 'Test 134');
test(findRepeatedDnaSequences("CCGGTTTAAAACCGGTTTAAAACCGGTTTAAAACCGGTTTAAA"), ['CCGGTTTAAA', 'CGGTTTAAAA', 'GGTTTAAAAC', 'GTTTAAAACC', 'TTTAAAACCG', 'TTAAAACCGG', 'TAAAACCGGT', 'AAAACCGGTT', 'AAACCGGTTT', 'AACCGGTTTA', 'ACCGGTTTAA'], 'Test 135');
test(findRepeatedDnaSequences("AAGGTTCCGGTTCCTTAAAGGTTCCGGTTCCT"), ['AAGGTTCCGG', 'AGGTTCCGGT', 'GGTTCCGGTT', 'GTTCCGGTTC', 'TTCCGGTTCC', 'TCCGGTTCCT'], 'Test 136');
test(findRepeatedDnaSequences("ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTT"), ['ACGTACGTAC', 'CGTACGTACG', 'GTACGTACGT', 'TACGTACGTA'], 'Test 137');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

// Auto-mark DONE when all tests pass
if (!failed) {
  const path = require("path");
  const fs = require("fs");
  const dir = __dirname;
  const folder = path.basename(dir);
  if (!folder.startsWith("DONE-")) {
    const parent = path.dirname(dir);
    const newDir = path.join(parent, "DONE-" + folder);
    fs.renameSync(dir, newDir);
    const readme = path.join(newDir, "README.md");
    if (fs.existsSync(readme)) {
      let c = fs.readFileSync(readme, "utf-8");
      if (!c.includes("<!-- SOLVED -->")) {
        c = c.replace(/^(# .+)$/m, "$1 ✅\n<!-- SOLVED -->");
        fs.writeFileSync(readme, c);
      }
    }
    console.log("✅ DONE → " + "DONE-" + folder);
  }
}
