// Test: 20. Valid Parentheses
// 149 test cases from LeetCodeDataset
// Run: node test.js

const { isValid } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n20. Valid Parentheses\n");

test(isValid("[[[[[[[]]]]]]]"), true, 'Test 1');
test(isValid("{[[]]}"), true, 'Test 2');
test(isValid("[[[[[[{{{{}}}}]]]]]]"), true, 'Test 3');
test(isValid("[{[[]]}]"), false, 'Test 4');
test(isValid("[[]]"), false, 'Test 5');
test(isValid("][][]["), false, 'Test 6');
test(isValid("[{[[{}]]}]"), true, 'Test 7');
test(isValid(""), true, 'Test 8');
test(isValid("[]"), false, 'Test 9');
test(isValid("{{{{{{}}}}}}"), true, 'Test 10');
test(isValid("{[[]]}"), false, 'Test 11');
test(isValid("[[[[[[]]]]]]"), true, 'Test 12');
test(isValid("[[{}]]"), true, 'Test 13');
test(isValid("[][]{}"), true, 'Test 14');
test(isValid("[[{}]]"), true, 'Test 15');
test(isValid("[]"), true, 'Test 16');
test(isValid("[[[{{[[]]}}]]]"), true, 'Test 17');
test(isValid("[[[]]]"), true, 'Test 18');
test(isValid("[[]]"), true, 'Test 19');
test(isValid("[{[{}]}]{[[{}]]}"), true, 'Test 20');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]][{}][][]{}[][{}][[{}]][{}][][][[{}]]"), true, 'Test 21');
test(isValid("[[[[[[[[]]]]]]]]"), true, 'Test 22');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][]"), true, 'Test 23');
test(isValid("[{[[]]}][{[[]]}][{[[]]}][{[[]]}][{[[]]}]"), true, 'Test 24');
test(isValid("[[[[]]]]"), true, 'Test 25');
test(isValid("[[{}]][{[[]]}]"), true, 'Test 26');
test(isValid("[{[[[{[[{}]][]]}]]}]"), false, 'Test 27');
test(isValid("[[]][{}][]{}"), true, 'Test 28');
test(isValid("[{[[[{}]][]]}]"), true, 'Test 29');
test(isValid("[{[[{[[{[[{[[{}]]}]]}]]}]]}]"), true, 'Test 30');
test(isValid("[{[[[{[[{}]][]]}]]}][][]{}"), false, 'Test 31');
test(isValid("[{{{{{}}}}}]"), true, 'Test 32');
test(isValid("[[[[[[]]]]]]"), true, 'Test 33');
test(isValid("[[[{}]]]"), true, 'Test 34');
test(isValid("[{[[]]}][[{[[]]}]]"), true, 'Test 35');
test(isValid("[{[[{}]]}][{[{}]}]"), true, 'Test 36');
test(isValid("[[{[[{[[{[]}]]}]]}]][{[[{[]}]]}]"), true, 'Test 37');
test(isValid("[{[[][{[[]]}]]}]"), true, 'Test 38');
test(isValid("[[[[[[[[[[[[[]]]]]]]]]]]]"), false, 'Test 39');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]"), true, 'Test 40');
test(isValid("[{[[[{}]][]]}]{[[]]}"), true, 'Test 41');
test(isValid("[{[[[{}]][]]}][]"), true, 'Test 42');
test(isValid("[{[[{[[{[[{[[{[[{}]]}]]}]]}]]}]]}]"), true, 'Test 43');
test(isValid("{}{}{}{}{}"), true, 'Test 44');
test(isValid("[[[{[[{[[]]}]]}]]]"), true, 'Test 45');
test(isValid("{[[[{[[{}]]}][]]]}"), true, 'Test 46');
test(isValid("[{[]}]"), true, 'Test 47');
test(isValid("[[[[[[[[{[[{[[{}]]}]]}][]]]]]]]"), false, 'Test 48');
test(isValid("[[[{[[{[[{[[{[]}]]}]]}]]}]]]"), true, 'Test 49');
test(isValid("[{[[{}]]}][{[[{}]]}][{[[{}]]}][{[[{}]]}]"), true, 'Test 50');
test(isValid("[{[[{[[{[[{[]}]]}]]}]]}]"), true, 'Test 51');
test(isValid("{{{{{{{{}}}}}}}}}"), false, 'Test 52');
test(isValid("[[[[[[[[[]]]]]]]]]"), true, 'Test 53');
test(isValid("{[[[[[[[[[{[[{[[{[[{[[{}]]}]]}]]}]]]]]]]]}"), false, 'Test 54');
test(isValid("{[[{[[{[[{[]}]]}]]}]]}][{[[{[[{[[{[]}]]}]]}]]}][{[[{[[{[]}]]}]]}][{[[{[[{[]}]]}]]}][{[[{[[{[]}]]}]]}][{[[{[[{[]}]]}]]}]"), false, 'Test 55');
test(isValid("[{[[][{}][{}][{}][{}]]}]"), true, 'Test 56');
test(isValid("[[[{{{[[[[]]]]}}}]]]"), true, 'Test 57');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]][{}][][]{}[][{}][[{}]][{}][][]"), true, 'Test 58');
test(isValid("[{[[{}]]}][{[[{}]]}][{[[{}]]}][{[[{}]]}][{[[{}]]}][{[[{}]]}]"), true, 'Test 59');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]]"), true, 'Test 60');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]][{}][][]{}[][{}]"), true, 'Test 61');
test(isValid("{[[[{[[{[[{[]}]]}]]}]]}][{[[{[[{[[{[]}]]}]]}]]}][{[[{[[{[]}]]}]]}][{[[{[[{[]}]]}]]}]"), false, 'Test 62');
test(isValid("{[[[[[[[[{[[{[[{}]]}]]}][]]]]]]]}"), false, 'Test 63');
test(isValid("[{[[{[[{[[{[[]]}]]}]]}]]}]"), true, 'Test 64');
test(isValid("[{[[{}][{}][{}][{}][{}][{}][{}][{}][{}][{}][{}][{}][{}][{}][{}][{}][{}][{}][{}][{}]]}]"), true, 'Test 65');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]][{}][][]{}[][{}][[{}]][{}]"), true, 'Test 66');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[]"), true, 'Test 67');
test(isValid("[{[[{[[{[[{}]]}]]}]]}]"), true, 'Test 68');
test(isValid("[[{}]{[]}]"), true, 'Test 69');
test(isValid("[[{}]][{[]}]"), true, 'Test 70');
test(isValid("[[{}]][[]]"), true, 'Test 71');
test(isValid("{[[{}]]}[[{}]]"), true, 'Test 72');
test(isValid("[[{{}}]]"), true, 'Test 73');
test(isValid("[{[[{}]]}][{[[{}]]}]"), true, 'Test 74');
test(isValid("[{[[{[[{[[]]}[]]]}[]]}[]]"), false, 'Test 75');
test(isValid("[{[[[{}]][]]}]{}"), true, 'Test 76');
test(isValid("[{[[{}]]}][{[[{}]]}][{[[{}]]}]"), true, 'Test 77');
test(isValid("{[[[]][[]]}"), false, 'Test 78');
test(isValid("[{[[{}][{}][{}][{}][{}][{}][{}][{}]]}]"), true, 'Test 79');
test(isValid("[[[]]][[{}]]"), true, 'Test 80');
test(isValid("[{[[{}]][{}]}]"), true, 'Test 81');
test(isValid("[[[[[[[[[{[[{[[{[[{[[{}]]}]]}]]}]]]]]]]]"]), Error: Solution.isValid[] missing 1 required positional argument: 's', 'Test 82');
test(isValid("[[]][{[]}]{[[]]}"), true, 'Test 83');
test(isValid("[][][][][][][][][][]"), true, 'Test 84');
test(isValid("[[[[[[[]]]]]]]{}[]"), true, 'Test 85');
test(isValid("{[[]]}{[[]]}"), true, 'Test 86');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][][]"), true, 'Test 87');
test(isValid("{[{[[{}]]}]}"), true, 'Test 88');
test(isValid("[[[{{{[[[]]]}}}]]]"), true, 'Test 89');
test(isValid("[{[[[{[[{}]][]]}]]}][][]{}{[[]][[]]}"), false, 'Test 90');
test(isValid("[[[{[[{}]]}][{[[{}]]}]][{[[{}]]}][{[[{}]]}][{[[{}]]}]"), false, 'Test 91');
test(isValid("[{[[{[[{[[]]}]]}]]}]"), false, 'Test 92');
test(isValid("{{{{{{{{}}}}}}}}"), true, 'Test 93');
test(isValid("[][][][][][][]"), true, 'Test 94');
test(isValid("[{[[]]}][{[[]]}][{[[]]}]"), true, 'Test 95');
test(isValid("{[[]][{[[]]}]}"), true, 'Test 96');
test(isValid("[{[[{[[{[[{[]}]}]]}]]}]"), false, 'Test 97');
test(isValid("[{[[{[[{}]]}]]}]"), true, 'Test 98');
test(isValid("[{[[]]}]"), true, 'Test 99');
test(isValid("[{[[[]]]}]"), true, 'Test 100');
test(isValid("[{[[]]}{[[]]}]"), true, 'Test 101');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]][{}][][]{}"), true, 'Test 102');
test(isValid("[[{}]][[[]]][{}]"), true, 'Test 103');
test(isValid("{[[[{[[{[[{[]}]]}]]}]]}][{[[{[[{[]}]]}]]}]"), false, 'Test 104');
test(isValid("[[[{[[{}]]}][]]]"), true, 'Test 105');
test(isValid("[[{}]][{[[]]}]"), true, 'Test 106');
test(isValid("[{[{[{}]}]}]"), true, 'Test 107');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]][{}]"), true, 'Test 108');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]][{}][]"), true, 'Test 109');
test(isValid("[[[[]]]]"), true, 'Test 110');
test(isValid("[{[[[{[[{}]][]]}]]}][][]{}{[[]][[]]}{[{}]}"), false, 'Test 111');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]][{}][][]{}[][{}][[{}]][{}][]"), true, 'Test 112');
test(isValid("[[[[[[[[]]]]]]"), false, 'Test 113');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]][{}][][]"), true, 'Test 114');
test(isValid("[][{}][{[[]]}]"), true, 'Test 115');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}"), true, 'Test 116');
test(isValid("{{[[[[]]]]}}"), true, 'Test 117');
test(isValid("{[[{[[{[[{[]}]]}]]}]]}][{[[{[[{[[{[]}]]}]]}]]}][{[[{[[{[]}]]}]]}][{[[{[[{[]}]]}]]}][{[[{[[{[]}]]}]]}]"), false, 'Test 118');
test(isValid("[{[[{}]]}][{}]"), true, 'Test 119');
test(isValid("[[{}]][[]]"), true, 'Test 120');
test(isValid("[{[[[{}]][]]}]{[[]][[]]}"), true, 'Test 121');
test(isValid("[{[[[{}]][]]}][]"), true, 'Test 122');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]][{}][][]{}[]"), true, 'Test 123');
test(isValid("[{[[{[[{[[{[]}]]}]]}]]}][{[[{[[{[]}]]}]]}][{[[{[[{[]}]]}]]}]"), true, 'Test 124');
test(isValid("[[[{}][{}]]]"), true, 'Test 125');
test(isValid("[[[[[{{{[[[]]]}}}]]]]]]"), false, 'Test 126');
test(isValid("[[{[[{}]]}]]"), true, 'Test 127');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}]"), true, 'Test 128');
test(isValid("[[[[{}]]]]"), true, 'Test 129');
test(isValid("[{[]}][{}][{[]}][{}]"), true, 'Test 130');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}][]{}[][][{}][[{}]][{}][][]{}[][{}][[{}]]"), true, 'Test 131');
test(isValid("[[[]]][{}]"), true, 'Test 132');
test(isValid("[[[[[[{[[{[[{}]]}]]}][]]]]]]"), true, 'Test 133');
test(isValid("[[[[[[[]]]]]]]"), true, 'Test 134');
test(isValid("[{[[{}]]}][{[[{}]]}][{[[{}]]}][{[[{}]]}][{[[{}]]}]"), true, 'Test 135');
test(isValid("[[[[[{[[{}]]}][]]]]]"), true, 'Test 136');
test(isValid("{[[]]}{[[]]}{[[]]}"), true, 'Test 137');
test(isValid("[]{}[]{}[]{}"), true, 'Test 138');
test(isValid("[[{}]][{[{}]}][{[{}]}]"), true, 'Test 139');
test(isValid("{{{{}}}}"), true, 'Test 140');
test(isValid("[{[]}]{[[]]}"), true, 'Test 141');
test(isValid("[{[[][]]}]"), true, 'Test 142');
test(isValid("[][]{}[][]{}"), true, 'Test 143');
test(isValid("[{[[]]}][{[[]]}]"), true, 'Test 144');
test(isValid("[{[[{[[{[[{[[{[]}]]}]]}]]}]]}]"), true, 'Test 145');
test(isValid("{[[]]}[{[[]]}[{[[]]}]]"), true, 'Test 146');
test(isValid("[[[{{[[[[]]]]}}]]]"), true, 'Test 147');
test(isValid("{[[[[[[{[[{[[{}]]}]]}][]]]]]]}"), true, 'Test 148');
test(isValid("[[{{[[]]}}]]"), true, 'Test 149');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

