// Test: 1750. Minimum Length Of String After Deleting Similar Ends
// 170 test cases from LeetCodeDataset
// Run: node test.js

const { minimumLength } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1750. Minimum Length Of String After Deleting Similar Ends\n");

test(minimumLength("abcba"), 1, 'Test 1');
test(minimumLength("ca"), 2, 'Test 2');
test(minimumLength("abac"), 4, 'Test 3');
test(minimumLength("aabccabba"), 3, 'Test 4');
test(minimumLength("aabbaa"), 0, 'Test 5');
test(minimumLength("aaaaa"), 0, 'Test 6');
test(minimumLength("aababbaa"), 1, 'Test 7');
test(minimumLength("cabaabac"), 0, 'Test 8');
test(minimumLength("aabbccbaa"), 0, 'Test 9');
test(minimumLength("aaa"), 0, 'Test 10');
test(minimumLength("abcabc"), 6, 'Test 11');
test(minimumLength("aabbbcccbbaa"), 0, 'Test 12');
test(minimumLength("aababa"), 1, 'Test 13');
test(minimumLength("aabcccbaa"), 0, 'Test 14');
test(minimumLength("abc"), 3, 'Test 15');
test(minimumLength("abbaccaa"), 5, 'Test 16');
test(minimumLength("aaaa"), 0, 'Test 17');
test(minimumLength("abccba"), 0, 'Test 18');
test(minimumLength("aaabaaa"), 1, 'Test 19');
test(minimumLength("aabbcc"), 6, 'Test 20');
test(minimumLength("abca"), 2, 'Test 21');
test(minimumLength("cccccc"), 0, 'Test 22');
test(minimumLength("abababababababababababababababababababababababababababababababababababababab"), 76, 'Test 23');
test(minimumLength("aabacccbaa"), 4, 'Test 24');
test(minimumLength("abacabacabacabacabacabacabacabacabacabacab"), 42, 'Test 25');
test(minimumLength("aaaabbbbccccddddeeeeffffgggghhhhiiii"), 36, 'Test 26');
test(minimumLength("aabbbcccbbbbaa"), 0, 'Test 27');
test(minimumLength("aaaabbbbccccddddeeeeffffgggghhhhiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii"), 66, 'Test 28');
test(minimumLength("ccabbbcccabbbcccabbbcc"), 18, 'Test 29');
test(minimumLength("abccbaabccbaabccbaabccba"), 0, 'Test 30');
test(minimumLength("acabacabacabacabacabacabacabacab"), 32, 'Test 31');
test(minimumLength("cccaaaaabbb"), 11, 'Test 32');
test(minimumLength("aaaabbbbccccaaaabbbbcccc"), 24, 'Test 33');
test(minimumLength("aaabbbbbbbbccccccaaa"), 14, 'Test 34');
test(minimumLength("cbabcbabcb"), 10, 'Test 35');
test(minimumLength("aaaabbbbccccddddeeeeffffgggghhhhiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii"), 76, 'Test 36');
test(minimumLength("bbbbbbaaaaa"), 11, 'Test 37');
test(minimumLength("abcabcabc"), 9, 'Test 38');
test(minimumLength("aaaabaaaabaaa"), 0, 'Test 39');
test(minimumLength("abcabcabcabc"), 12, 'Test 40');
test(minimumLength("aaaaaaaaaabbbbbbbbbccccc"), 24, 'Test 41');
test(minimumLength("aaaabbbbccccddddeeeeffffgggghhhhiiiiiiiiiiiiiiiiiiiiiiii"), 56, 'Test 42');
test(minimumLength("abccbaabcbaabccba"), 1, 'Test 43');
test(minimumLength("abacabacabaacaba"), 1, 'Test 44');
test(minimumLength("aaabaaaabbaaaabaa"), 0, 'Test 45');
test(minimumLength("abacaabacaabaca"), 13, 'Test 46');
test(minimumLength("aabbbccccdddeeeccccbbbaaa"), 6, 'Test 47');
test(minimumLength("abacbacbacbacbacba"), 14, 'Test 48');
test(minimumLength("aaaabaaaabaaaabaaa"), 1, 'Test 49');
test(minimumLength("aabccccbbaa"), 0, 'Test 50');
test(minimumLength("aaaabbbbcccc"), 12, 'Test 51');
test(minimumLength("aabccbaaab"), 10, 'Test 52');
test(minimumLength("aaabbbcccbbbbaaa"), 0, 'Test 53');
test(minimumLength("aabbccddeeffeeddccbaabbaaabcabcabc"), 34, 'Test 54');
test(minimumLength("aabbbcccbbaaaabbbcccbbaaa"), 0, 'Test 55');
test(minimumLength("aaaabbbbccccddddeeeeffffgggghhhhiiiiiiiii"), 41, 'Test 56');
test(minimumLength("abbbbaaaaabbbaaaaabbbb"), 22, 'Test 57');
test(minimumLength("cccaaaaabbbcccbaaabccbaaabccbaaabccbaa"), 38, 'Test 58');
test(minimumLength("bbbbaaaaabbbb"), 0, 'Test 59');
test(minimumLength("abccbaabccba"), 0, 'Test 60');
test(minimumLength("aaabaaaabbbaaa"), 0, 'Test 61');
test(minimumLength("aaaabbbbbbccccccdddddd"), 22, 'Test 62');
test(minimumLength("abacabacaba"), 1, 'Test 63');
test(minimumLength("aaabaaaabaaaabaaa"), 1, 'Test 64');
test(minimumLength("aabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabbaabba"), 0, 'Test 65');
test(minimumLength("abcabcabcabcabcabcabcabcabcabcabcabc"), 36, 'Test 66');
test(minimumLength("abacaba"), 1, 'Test 67');
test(minimumLength("cccbbbaaa"), 9, 'Test 68');
test(minimumLength("aaaaaaaaaabbbbbbbbbbbccccccccccdddddddddd"), 41, 'Test 69');
test(minimumLength("abcbaabcbacba"), 7, 'Test 70');
test(minimumLength("aaabaaaabba"), 0, 'Test 71');
test(minimumLength("aabbaabbaabbaabb"), 16, 'Test 72');
test(minimumLength("aaaabbbbccccddddccccdddd"), 24, 'Test 73');
test(minimumLength("abcabcabcabcabcabcabc"), 21, 'Test 74');
test(minimumLength("ccabbbccbbbbcabcabbbccabc"), 22, 'Test 75');
test(minimumLength("cccccccccccccccccccccc"), 0, 'Test 76');
test(minimumLength("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), 99, 'Test 77');
test(minimumLength("acaacacaacac"), 12, 'Test 78');
test(minimumLength("aaabbbcccbbbaaa"), 0, 'Test 79');
test(minimumLength("abcbaabcbaabcbaabcbaabcbaabcbaabcba"), 1, 'Test 80');
test(minimumLength("abccbaabccbaabccba"), 0, 'Test 81');
test(minimumLength("aaaabbbbccccddddeeeeffffgggghhhhiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii"), 71, 'Test 82');
test(minimumLength("abcabcabcabcabcabcabcabcabcabc"), 30, 'Test 83');
test(minimumLength("aabbaabbaabbaabbaabbaabbaabbaabb"), 32, 'Test 84');
test(minimumLength("aaaaabbbbbcccccaaaa"), 10, 'Test 85');
test(minimumLength("aabbbccccdddddeeecccbbbbaaa"), 8, 'Test 86');
test(minimumLength("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), 48, 'Test 87');
test(minimumLength("ababbababbababb"), 15, 'Test 88');
test(minimumLength("aabbbcccdddeeeeeeccccbbbaa"), 9, 'Test 89');
test(minimumLength("aabbccddeedccbbaa"), 0, 'Test 90');
test(minimumLength("aabbbcccbaa"), 0, 'Test 91');
test(minimumLength("acaacaaca"), 1, 'Test 92');
test(minimumLength("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), 93, 'Test 93');
test(minimumLength("aabbaaabbbaaabbbaaabbaa"), 0, 'Test 94');
test(minimumLength("accbabcbaccbacc"), 15, 'Test 95');
test(minimumLength("abcabcabcabcabcabc"), 18, 'Test 96');
test(minimumLength("abcbaabcba"), 0, 'Test 97');
test(minimumLength("aabbccbbccbbccaa"), 12, 'Test 98');
test(minimumLength("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), 0, 'Test 99');
test(minimumLength("aaaabbbcccbbbaaa"), 0, 'Test 100');
test(minimumLength("cbbccbbcc"), 0, 'Test 101');
test(minimumLength("abacbacbacbacbacbacbac"), 22, 'Test 102');
test(minimumLength("aaaaabccccbaaaa"), 0, 'Test 103');
test(minimumLength("aaaabbbbccccddddeee"), 19, 'Test 104');
test(minimumLength("aaaabbbbccccddddeeeeffffgggghhhhiiiiiiiiiiiii"), 45, 'Test 105');
test(minimumLength("ccccaaaabbbbaaaa"), 16, 'Test 106');
test(minimumLength("aaaaaaaaaabbbbbbbbbbbccccccccccddddddddddeeeeeeeeeeeeeeefffffffff"), 65, 'Test 107');
test(minimumLength("aaabbbcccbbbbaaabbbcccbbbbaaa"), 0, 'Test 108');
test(minimumLength("ababababababababababab"), 22, 'Test 109');
test(minimumLength("aaaabbbbccccccaaaabbbb"), 22, 'Test 110');
test(minimumLength("aabbaaabbbaaabbbaaabbaaa"), 0, 'Test 111');
test(minimumLength("aaaaaaaaaabbbbbbbbbbbccccccccccddddddddddeeeeeeeeeeeeeeefffffffffgggggggggghhhhhhhhhhhiiiiiiiiiii"), 97, 'Test 112');
test(minimumLength("aabbaabbccddeeffeeddccbaabbaa"), 0, 'Test 113');
test(minimumLength("abababababababababab"), 20, 'Test 114');
test(minimumLength("aaaabccccbbbbaaaa"), 0, 'Test 115');
test(minimumLength("aabbbbccccbbbbaaa"), 0, 'Test 116');
test(minimumLength("aabbccddeedccbbaaa"), 0, 'Test 117');
test(minimumLength("abacabadabacaba"), 1, 'Test 118');
test(minimumLength("aabaaabaaa"), 0, 'Test 119');
test(minimumLength("aabbccddeeeedddccbaabb"), 22, 'Test 120');
test(minimumLength("aabccccbaa"), 0, 'Test 121');
test(minimumLength("acccba"), 4, 'Test 122');
test(minimumLength("abacbacbacbacbaba"), 11, 'Test 123');
test(minimumLength("abcabcabcabcabcabcabcabcabcabcabcabcabcabc"), 42, 'Test 124');
test(minimumLength("aaaabbbaaabbbbaaaabbbaaaa"), 0, 'Test 125');
test(minimumLength("abacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabac"), 96, 'Test 126');
test(minimumLength("abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"), 90, 'Test 127');
test(minimumLength("aaabbbcccbbaaa"), 0, 'Test 128');
test(minimumLength("aabbccddeeffgg"), 14, 'Test 129');
test(minimumLength("aaaabbbbccccddddeeeeffffgggghhhhiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii"), 82, 'Test 130');
test(minimumLength("ccbaaaabbbcccbaaaabbbccc"), 0, 'Test 131');
test(minimumLength("cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"), 0, 'Test 132');
test(minimumLength("aabbaabbccddccbbbaa"), 10, 'Test 133');
test(minimumLength("cccccccccccccccccc"), 0, 'Test 134');
test(minimumLength("aaaabbaaabbbaaaa"), 0, 'Test 135');
test(minimumLength("aabbaabbaabbaabbaabb"), 20, 'Test 136');
test(minimumLength("aaaaabbbbbccccdddddccccbbbaaaaa"), 0, 'Test 137');
test(minimumLength("ababaababa"), 0, 'Test 138');
test(minimumLength("aaaaaaaaaaaaaaaaaaaaaaaaaaa"), 0, 'Test 139');
test(minimumLength("abcbaabcbaabcba"), 1, 'Test 140');
test(minimumLength("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"), 0, 'Test 141');
test(minimumLength("aabbaaccbbbaa"), 4, 'Test 142');
test(minimumLength("ccccccc"), 0, 'Test 143');
test(minimumLength("aaabbbcccdddeeecccccbbbaaa"), 6, 'Test 144');
test(minimumLength("aabbccddeeecccbbbaa"), 5, 'Test 145');
test(minimumLength("abccbaabcba"), 0, 'Test 146');
test(minimumLength("ababababab"), 10, 'Test 147');
test(minimumLength("aaaabbbbccccddddccccddddeeeeffff"), 32, 'Test 148');
test(minimumLength("aaaabbbbccccddddeeeeffffgggghhhhiiiiiiiiiiiiiiiiiiiiiiiiiiiii"), 61, 'Test 149');
test(minimumLength("ccccaaaabbbbcccc"), 8, 'Test 150');
test(minimumLength("aabbccddeedccbbaaabbccddeedccbbaa"), 0, 'Test 151');
test(minimumLength("babbacabacababb"), 1, 'Test 152');
test(minimumLength("ccccccabbbbbbbcc"), 8, 'Test 153');
test(minimumLength("abcabcabcabcabcabcabcabc"), 24, 'Test 154');
test(minimumLength("aabbaabbccbbccbbccaa"), 16, 'Test 155');
test(minimumLength("aaabbbcccbaabbbcccbaaabbb"), 25, 'Test 156');
test(minimumLength("ababa"), 1, 'Test 157');
test(minimumLength("acaabaaaca"), 1, 'Test 158');
test(minimumLength("aabbccbbccbbccbbccaa"), 16, 'Test 159');
test(minimumLength("ccccbaaaabbbcccbaaaabbbccc"), 0, 'Test 160');
test(minimumLength("aaaabbbcccdddeeecccbbbbaaaa"), 6, 'Test 161');
test(minimumLength("aaabaaabaaabaaabaaabaaabaaabaaabaaabaaabaaabaaabaaabaaabaaabaaabaaabaaab"), 72, 'Test 162');
test(minimumLength("aaaaabbbbbccccccccbbbbbbaaaaa"), 0, 'Test 163');
test(minimumLength("ccabbaacc"), 0, 'Test 164');
test(minimumLength("aaaabbbbccccddddeeeeffffgggghhhhiiiiiiiiiiiiiiiiiii"), 51, 'Test 165');
test(minimumLength("aabbccddeedccbbaaacccccccccccbbbbaaa"), 12, 'Test 166');
test(minimumLength("acbacbacbacbacba"), 14, 'Test 167');
test(minimumLength("abcabcabcabcabc"), 15, 'Test 168');
test(minimumLength("ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"), 0, 'Test 169');
test(minimumLength("caabaccaabaaccaaa"), 17, 'Test 170');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

