// Test: 1106. Parsing A Boolean Expression
// 135 test cases from LeetCodeDataset
// Run: node test.js

const { parseBoolExpr } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1106. Parsing A Boolean Expression\n");

test(parseBoolExpr("![![t]]"), true, 'Test 1');
test(parseBoolExpr("|[t,t,t]"), true, 'Test 2');
test(parseBoolExpr("|[f,f,f,t]"), true, 'Test 3');
test(parseBoolExpr("&[t,t,t,t,t,t]"), true, 'Test 4');
test(parseBoolExpr("![&[&[t,f],|[t,t]]]"), true, 'Test 5');
test(parseBoolExpr("&[|[f,t],&[t,f]]"), false, 'Test 6');
test(parseBoolExpr("![|[t,t]]"), false, 'Test 7');
test(parseBoolExpr("|[&[t,f],&[f,t]]"), false, 'Test 8');
test(parseBoolExpr("![&[f,t]]"), true, 'Test 9');
test(parseBoolExpr("|[f,t,f,t]"), true, 'Test 10');
test(parseBoolExpr("![f]"), true, 'Test 11');
test(parseBoolExpr("&[f,t]"), false, 'Test 12');
test(parseBoolExpr("&[![t],f]"), false, 'Test 13');
test(parseBoolExpr("![&[|[f],&[f,t]]]"), true, 'Test 14');
test(parseBoolExpr("&[t,|[f,f,f,t],![&[f,t]]]"), true, 'Test 15');
test(parseBoolExpr("&[t,t,t,t]"), true, 'Test 16');
test(parseBoolExpr("&[|[f]]"), false, 'Test 17');
test(parseBoolExpr("![&[|[t],|[f]],&[t,f]]"), true, 'Test 18');
test(parseBoolExpr("|[f,f,f,f,f,f]"), false, 'Test 19');
test(parseBoolExpr("t"), true, 'Test 20');
test(parseBoolExpr("|[t,f]"), true, 'Test 21');
test(parseBoolExpr("f"), false, 'Test 22');
test(parseBoolExpr("|[|[t,f],&[f,f]]"), true, 'Test 23');
test(parseBoolExpr("![t]"), false, 'Test 24');
test(parseBoolExpr("|[&[t,f],t]"), true, 'Test 25');
test(parseBoolExpr("![![![t]]]"), false, 'Test 26');
test(parseBoolExpr("|[&[f,t],|[t,f]]"), true, 'Test 27');
test(parseBoolExpr("&[|[t,f],&[f,t],|[t,t],&[f,f]]"), false, 'Test 28');
test(parseBoolExpr("|[t,f,t,f]"), true, 'Test 29');
test(parseBoolExpr("&[t,t,t]"), true, 'Test 30');
test(parseBoolExpr("&[|[t,f],|[f,t]]"), true, 'Test 31');
test(parseBoolExpr("|[f,&[t,f],|[f,f]]"), false, 'Test 32');
test(parseBoolExpr("&[|[t,f],&[f,t]]"), false, 'Test 33');
test(parseBoolExpr("|[&[t,f],|[t,t]]"), true, 'Test 34');
test(parseBoolExpr("|[f,![t],&[|[f,f],|[t,t]]]"), false, 'Test 35');
test(parseBoolExpr("&[|[|[|[t,f],f],t],![f],&[t,![f]]]"), true, 'Test 36');
test(parseBoolExpr("|[&[t,|[f,f],t],&[f,![t],t],|[t,f,f]]"), true, 'Test 37');
test(parseBoolExpr("![&[|[f,t,f],&[t,f]],|[t,t,f]]"), true, 'Test 38');
test(parseBoolExpr("&[|[t,&[f,f],t],&[f,|[t,f],t],|[&[f,t],f]]"), false, 'Test 39');
test(parseBoolExpr("|[&[t,|[f,f,f]],![|[t,t,t]],&[f,f]]"), false, 'Test 40');
test(parseBoolExpr("&[|[&[t,f],&[f,f]],&[t,![t]],f]"), false, 'Test 41');
test(parseBoolExpr("&[|[f,t],&[t,f],|[f,t],&[t,f],|[f,t],&[t,f],|[f,t],&[t,f]]"), false, 'Test 42');
test(parseBoolExpr("&[f,![t],|[&[t,![t]],|[t,f,f,t,f]],&[f,f,t,t,t,t,f,t]]"), false, 'Test 43');
test(parseBoolExpr("&[t,|[f,![t],&[t,f,t,t],|[f,f,f,f]],&[f,|[t,f,t,t,t]],![f,|[t,f,f,f,f]],&[t,t,t],t]"), false, 'Test 44');
test(parseBoolExpr("|[&[t,f],&[f,t],|[t,t],|[f,f],![t],![f],&[t,|[t,t]],|[t,&[t,f]]]"), true, 'Test 45');
test(parseBoolExpr("|[&[f,t],&[t,f],&[f,t],&[t,f],&[f,t],&[t,f],&[f,t],&[t,f]]"), false, 'Test 46');
test(parseBoolExpr("&[&[&[&[&[&[&[&[&[&[&[&[t],t],t],t],t],t],t],t],t],t],t],t],t]"), Error: list index out of range, 'Test 47');
test(parseBoolExpr("|[|[|[|[|[|[|[|[t],f],t],f],f],f],&[t,t,t,t,t,t,t,t],|[t,f,f,t,f],&[f,f,t,t,t,t,f,t],f,t]"), false, 'Test 48');
test(parseBoolExpr("|[&[t,![f]],&[f,![t]],&[t,t],![f]]"), true, 'Test 49');
test(parseBoolExpr("|[f,![t],&[t,f],![f]]"), true, 'Test 50');
test(parseBoolExpr("|[&[f,t],|[t,f],![f]]"), true, 'Test 51');
test(parseBoolExpr("![&[|[f,t],&[f,f]],|[t,t,t]]"), true, 'Test 52');
test(parseBoolExpr("&[|[f,f,t],![t],|[f,f,f],&[|[t,f],f],|[t,t,t]]"), false, 'Test 53');
test(parseBoolExpr("![&[|[t,f,f],f],|[t,t,t]]"), true, 'Test 54');
test(parseBoolExpr("&[f,![t],&[t,![f]],|[f,t]]"), false, 'Test 55');
test(parseBoolExpr("&[|[t,f],|[f,t],&[t,t],|[t,t],&[t,f],|[f,t]]"), false, 'Test 56');
test(parseBoolExpr("![&[|[f,![t],&[t,f]],![|[f,f,t]],&[t,f],|[f,t,t,t],&[t,|[f,f,f],t],&[t,f,f,t],|[t,![f],f],f,![t],&[f,t,f],|[t,f,t],f,![t],&[f,t,f],|[t,f,t],f]]"), true, 'Test 57');
test(parseBoolExpr("![&[|[&[f,t],f],f]]"), true, 'Test 58');
test(parseBoolExpr("|[f,![f],&[t,f],|[t,t,f,f],&[t,t,t,t]]"), true, 'Test 59');
test(parseBoolExpr("&[|[f,f,t],![t],|[f,t,f]]"), false, 'Test 60');
test(parseBoolExpr("![&[|[&[t,f],&[f,f]],&[t,t],f]]"), true, 'Test 61');
test(parseBoolExpr("&[f,![t],|[f,f,t],&[t,t,t]]"), false, 'Test 62');
test(parseBoolExpr("&[t,|[f,![t],&[t,f,t],|[f,f,f]],&[f,|[t,f,t,t]],![f,|[t,f]]]"), false, 'Test 63');
test(parseBoolExpr("&[|[|[|[|[|[|[f,t],f],t],t],t],t],t],t],&[f,|[t,![t],f],&[t,t,t,t,t,t]],![|[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t]]]"), Error: list index out of range, 'Test 64');
test(parseBoolExpr("![&[|[t,f],f],&[t,t,t]]"), true, 'Test 65');
test(parseBoolExpr("&[t,|[f,![t],&[t,f]],&[f,|[t,f,t]],![f]]"), false, 'Test 66');
test(parseBoolExpr("&[&[t,t],&[t,|[t,t]],&[t,|[t,|[t,t]]],&[t,|[t,|[t,|[t,t]]]]]"), true, 'Test 67');
test(parseBoolExpr("![&[|[f,t],&[t,f]],|[f,f,f,f]]"), true, 'Test 68');
test(parseBoolExpr("&[|[f,f,t],![t],|[f,f,f]]"), false, 'Test 69');
test(parseBoolExpr("&[f,|[&[f,t],f],|[t,t],![&[f,t]]]"), false, 'Test 70');
test(parseBoolExpr("![&[|[|[f,t],f],&[f,t,f,t]],|[f,f,f,f,f,t,t],&[t,t,t,t,t,t,t,t]]"), true, 'Test 71');
test(parseBoolExpr("![&[|[f,f,f],t],&[|[|[|[|[|[|[f,t],f],t],t],t],t],t],t],&[f,|[t,![t],f],&[t,t,t,t,t,t]],![|[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t]]]"), Error: list index out of range, 'Test 72');
test(parseBoolExpr("&[f,![t],|[&[t,![t]],|[t,f,f,t,f]],&[f,f,t,t,t,t],&[t,t,t,t,t,t,t,t],f]"), false, 'Test 73');
test(parseBoolExpr("&[|[|[|[f],f],t],&[t,f,t],![f]]"), false, 'Test 74');
test(parseBoolExpr("![&[|[t,f],&[f,t]],|[t,t]]"), true, 'Test 75');
test(parseBoolExpr("&[|[t,t,t],&[t,t,t],&[f,f,f],|[t,t,t],|[f,f,f]]"), false, 'Test 76');
test(parseBoolExpr("![&[![f],t],|[f,&[t,f],f],&[t,f]]"), true, 'Test 77');
test(parseBoolExpr("&[|[t,![f],&[t,f]],![|[f,f,t]],&[t,f],|[f,t,t,t]]"), false, 'Test 78');
test(parseBoolExpr("&[|[t,![f],&[f,t]],|[t,![t],&[f,f]],|[t,t]]"), true, 'Test 79');
test(parseBoolExpr("|[&[t,![t]],f,![f],t]"), true, 'Test 80');
test(parseBoolExpr("![&[&[t,t],&[f,f]],|[&[t,f],&[t,t]]]"), true, 'Test 81');
test(parseBoolExpr("&[f,|[&[f,t],f],|[t,t]]"), false, 'Test 82');
test(parseBoolExpr("|[&[t,![t]],f,![f],t,![|[&[f,t],f]]]"), true, 'Test 83');
test(parseBoolExpr("![&[f,|[&[t,f],f],&[t,t,t]]]"), true, 'Test 84');
test(parseBoolExpr("|[f,&[|[t,f],&[t,f]],|[t,f]]"), true, 'Test 85');
test(parseBoolExpr("&[t,![f],|[&[t,t],|[f,f]],&[|[t,f],f]]"), false, 'Test 86');
test(parseBoolExpr("![&[|[&[t,f],t],&[f,|[t,f,t]]],|[f,![t],&[t,f,t]],![f]]"), true, 'Test 87');
test(parseBoolExpr("&[|[t,f],&[t,f],|[t,t],|[f,f],&[t,![f]]]"), false, 'Test 88');
test(parseBoolExpr("|[|[|[f],f],f]"), false, 'Test 89');
test(parseBoolExpr("&[|[|[|[|[|[|[|[|[|[|[|[|[f,t],f],t],t],t],t],t],t],t],t],t],t],t],&[f,|[t,![t],f],&[t,t,t,t,t,t]],![|[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t]]]"), Error: list index out of range, 'Test 90');
test(parseBoolExpr("&[f,![t],&[t,![f]],|[f,t],![&[t,![t]]]]"), false, 'Test 91');
test(parseBoolExpr("|[|[|[|[|[t],f],t],f],&[t,![f]]]"), true, 'Test 92');
test(parseBoolExpr("|[|[|[|[|[|[|[|[f],f],f],f],f],f],f],f]"), false, 'Test 93');
test(parseBoolExpr("![&[|[f,f,f,t],![t],|[t,t,t]],|[f,&[t,|[f,t],&[f,f]],![f]]]"), true, 'Test 94');
test(parseBoolExpr("&[|[|[|[|[t],f],t],f],&[t,t,t,t,t,t,t,t],|[t,f,f,t,f],&[f,f,t,t,t,t,f,t],f]"), false, 'Test 95');
test(parseBoolExpr("|[f,&[|[f,f],t],&[f,|[t,f],f],![f]]"), true, 'Test 96');
test(parseBoolExpr("&[|[|[t,f],f],&[t,![f]],![|[t,f]]]"), false, 'Test 97');
test(parseBoolExpr("&[|[f,f,f],|[t,f,t],&[t,t]]"), false, 'Test 98');
test(parseBoolExpr("&[|[t,&[f,t]],|[t,|[f,f]],&[t,|[t,|[f,t]]],|[t,&[f,|[f,t]]]]"), true, 'Test 99');
test(parseBoolExpr("![|[f,&[t,|[t,f]],![t]]]"), false, 'Test 100');
test(parseBoolExpr("![&[|[|[|[|[f],t],f],t],&[t,f,t],![f],|[t,f]]]"), true, 'Test 101');
test(parseBoolExpr("![&[|[t,f],&[f,f]],![|[t,t,t,t]]]"), true, 'Test 102');
test(parseBoolExpr("&[|[f,f,t],&[f,f,f],![t],|[t,f,f,f,t],&[f,t,t,f]]"), false, 'Test 103');
test(parseBoolExpr("![&[|[&[t,|[f,t]],t],&[f,![t],t]],|[t,![f],&[f,f]]]"), true, 'Test 104');
test(parseBoolExpr("&[|[f,f,f,t],|[t,f,t,f],&[t,t,t,t]]"), true, 'Test 105');
test(parseBoolExpr("|[f,&[t,|[f,t],&[f,f]],![f]]"), true, 'Test 106');
test(parseBoolExpr("|[|[|[|[|[|[|[t],f],t],f],f],f],&[t,t,t,t,t,t,t,t],&[t,t,t,t,t,t,t,t]]"), true, 'Test 107');
test(parseBoolExpr("&[|[t,f],![f],&[t,t,t]]"), true, 'Test 108');
test(parseBoolExpr("|[t,&[|[f,f],&[t,f]],&[t,|[t,f],&[f,f]]]"), true, 'Test 109');
test(parseBoolExpr("![|[|[|[f,t],t],f],&[f,|[t,![t],f],&[t,t,t,t,t,t]]]"), true, 'Test 110');
test(parseBoolExpr("![|[&[f,t],|[t,f],&[f,f],|[t,t],&[t,f],|[f,f]]]"), false, 'Test 111');
test(parseBoolExpr("|[&[t,t,t,t],|[|[f,f],f],&[t,f,f,t,t],![t]]"), true, 'Test 112');
test(parseBoolExpr("|[&[f,t],&[t,f],|[t,t]]"), true, 'Test 113');
test(parseBoolExpr("|[|[f,f,f],&[t,t,t],![|[f,f]]]"), true, 'Test 114');
test(parseBoolExpr("&[|[t,f],&[f,|[t,f]],![t]],|[&[f,t],&[t,t]]]"), Error: list index out of range, 'Test 115');
test(parseBoolExpr("![&[|[&[f,f],t],f],|[f,|[t,f],&[f,t]]]"), true, 'Test 116');
test(parseBoolExpr("|[&[t,t,t,t],|[f,f,f,f],&[t,f,t,f]]"), true, 'Test 117');
test(parseBoolExpr("|[&[t,f,![t]],&[t,f,t],&[f,![t]],![f],t]"), true, 'Test 118');
test(parseBoolExpr("&[|[|[f,t],t],f],&[f,|[t,![t],f],&[t,t,t,t,t,t]],![|[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t]]"), false, 'Test 119');
test(parseBoolExpr("![&[t,![f],&[t,t],|[t,f],&[t,![t],&[f,f]]]]"), true, 'Test 120');
test(parseBoolExpr("![&[|[f,f],&[t,t],&[t,f]],|[t,![t],&[t,f]],&[t,t]]"), true, 'Test 121');
test(parseBoolExpr("![&[|[|[|[|[|[f],t],f],t],&[t,f,t],![f],|[t,f]],&[f,t,t,f],![t]]"), false, 'Test 122');
test(parseBoolExpr("|[&[t,f],&[t,t,t],![f],&[f,![t]]]"), true, 'Test 123');
test(parseBoolExpr("![![![![![t]]]]]"), false, 'Test 124');
test(parseBoolExpr("&[|[t,f],|[f,t],&[t,t],|[t,t],&[t,f],|[f,t],![t],![f],&[t,|[t,t]],|[t,&[t,f]],&[f,|[t,f]],|[f,|[t,f]]]"), false, 'Test 125');
test(parseBoolExpr("&[f,|[t,|[f,![t]]]]"), false, 'Test 126');
test(parseBoolExpr("|[|[|[|[|[f],f],t],&[t,f,t],![f],|[t,f]],&[f,t,t,f]]"), true, 'Test 127');
test(parseBoolExpr("![&[&[t,t],|[f,f],&[f,t]]]"), true, 'Test 128');
test(parseBoolExpr("![&[|[&[t,f],f],&[t,|[t,f]]],|[t,![f],t]]"), true, 'Test 129');
test(parseBoolExpr("![&[|[&[t,f],t],&[f,|[t,f]]],|[f,![t]]]"), true, 'Test 130');
test(parseBoolExpr("&[f,&[|[f,f,t],![t],|[f,f,f]],|[f,&[t,|[f,t],&[f,f]],![f]],![&[|[f,f,f,t],![t],|[t,t,t]],|[f,&[t,|[f,t],&[f,f]],![f]]]]"), false, 'Test 131');
test(parseBoolExpr("|[&[f,t,f],|[t,f,t],&[t,t,t,t,t]]"), true, 'Test 132');
test(parseBoolExpr("|[|[|[t,f],f],&[|[t,t],&[f,t]]],![t]"), true, 'Test 133');
test(parseBoolExpr("![|[t,![t],&[t,![f]]]]"), false, 'Test 134');
test(parseBoolExpr("![|[&[t,![t]],&[f,![f]],&[t,t],![f]]]"), false, 'Test 135');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

