// Test: 3302. Find The Lexicographically Smallest Valid Sequence
// 155 test cases from LeetCodeDataset
// Run: node test.js

const { validSequence } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n3302. Find The Lexicographically Smallest Valid Sequence\n");

test(validSequence("hello", "heo"), [0, 1, 2], 'Test 1');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "abcdefghijklmnopqrstuvwxyz"), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], 'Test 2');
test(validSequence("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "abc"), [], 'Test 3');
test(validSequence("abcde", "edcba"), [], 'Test 4');
test(validSequence("abcdefg", "bdf"), [0, 3, 5], 'Test 5');
test(validSequence("mississippi", "issi"), [0, 2, 3, 4], 'Test 6');
test(validSequence("vbcca", "abc"), [0, 1, 2], 'Test 7');
test(validSequence("leetcode", "code"), [0, 5, 6, 7], 'Test 8');
test(validSequence("bacdc", "abc"), [1, 2, 4], 'Test 9');
test(validSequence("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "aaa"), [], 'Test 10');
test(validSequence("xyz", "xy"), [0, 1], 'Test 11');
test(validSequence("abcabcabc", "abc"), [0, 1, 2], 'Test 12');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "abc"), [0, 1, 2], 'Test 13');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "aaa"), [], 'Test 14');
test(validSequence("zyxwvutsrqponmlkjihgfedcba", "xyz"), [], 'Test 15');
test(validSequence("abcdefghij", "aceg"), [0, 1, 4, 6], 'Test 16');
test(validSequence("xyzz", "xyz"), [0, 1, 2], 'Test 17');
test(validSequence("aabbccddeeff", "abcdef"), [0, 1, 4, 6, 8, 10], 'Test 18');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "zzz"), [], 'Test 19');
test(validSequence("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "zyxwvutsrqponmlkjihgfedcba"), [], 'Test 20');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "az"), [0, 1], 'Test 21');
test(validSequence("leetcode", "leet"), [0, 1, 2, 3], 'Test 22');
test(validSequence("abababababab", "aab"), [0, 1, 3], 'Test 23');
test(validSequence("zzzzzzzzzzzz", "zzz"), [0, 1, 2], 'Test 24');
test(validSequence("aaabaaa", "aaa"), [0, 1, 2], 'Test 25');
test(validSequence("aabbcc", "abc"), [0, 1, 4], 'Test 26');
test(validSequence("aaaaaa", "aaabc"), [], 'Test 27');
test(validSequence("mississippi", "sip"), [0, 1, 8], 'Test 28');
test(validSequence("zzzzz", "aaa"), [], 'Test 29');
test(validSequence("abababababababababababababababababababababababababababab", "aaa"), [0, 1, 2], 'Test 30');
test(validSequence("abc", "ab"), [0, 1], 'Test 31');
test(validSequence("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaa"), [0, 1, 2, 3, 4, 5], 'Test 32');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "zyxwvutsrqponmlkjihgfedcba"), [], 'Test 33');
test(validSequence("abababababababababab", "ababab"), [0, 1, 2, 3, 4, 5], 'Test 34');
test(validSequence("hellohellohello", "ell"), [0, 2, 3], 'Test 35');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "abcdefghijklmnopqxyz"), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 24, 25], 'Test 36');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "adgjmoqsuwy"), [0, 1, 6, 9, 12, 14, 16, 18, 20, 22, 24], 'Test 37');
test(validSequence("axxayyazz", "xyz"), [0, 4, 7], 'Test 38');
test(validSequence("abracadabra", "abra"), [0, 1, 2, 3], 'Test 39');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "qrstuvwxyzz"), [], 'Test 40');
test(validSequence("zyxzyxzyxzyxzyxzyxzyxzyxzyxzyx", "zyxzyxzyxzyx"), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 'Test 41');
test(validSequence("sequenceofcharacters", "sequence"), [0, 1, 2, 3, 4, 5, 6, 7], 'Test 42');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "zyxwvut"), [], 'Test 43');
test(validSequence("abracadabra", "acad"), [0, 1, 3, 6], 'Test 44');
test(validSequence("thequickbrownfoxjumpsoverthelazydog", "thezog"), [0, 1, 2, 3, 10, 34], 'Test 45');
test(validSequence("ababababababababab", "aba"), [0, 1, 2], 'Test 46');
test(validSequence("aababababa", "aaa"), [0, 1, 2], 'Test 47');
test(validSequence("xyzz", "zyx"), [], 'Test 48');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "xyz"), [0, 24, 25], 'Test 49');
test(validSequence("abcdexyz", "xyz"), [0, 6, 7], 'Test 50');
test(validSequence("xyzxyzxyzxyzxyzxyzxyzxyz", "xyzxyzxyz"), [0, 1, 2, 3, 4, 5, 6, 7, 8], 'Test 51');
test(validSequence("abcdefg", "aceg"), [0, 1, 4, 6], 'Test 52');
test(validSequence("axbxcxdxe", "abcde"), [0, 1, 4, 6, 8], 'Test 53');
test(validSequence("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz", "zyxwvutsrqponmlkjihgfedcba"), [], 'Test 54');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "abcde"), [0, 1, 2, 3, 4], 'Test 55');
test(validSequence("abcdefghij", "jihgfedcba"), [], 'Test 56');
test(validSequence("xyxyxyxyxy", "xyxy"), [0, 1, 2, 3], 'Test 57');
test(validSequence("aabbaabbaabbaabbaabbaabb", "aaabb"), [0, 1, 2, 3, 6], 'Test 58');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "mnopq"), [0, 13, 14, 15, 16], 'Test 59');
test(validSequence("abababababababab", "abab"), [0, 1, 2, 3], 'Test 60');
test(validSequence("abacabadabacabadabacabadabacabad", "abcabcabc"), [0, 1, 2, 4, 5, 11, 12, 13, 19], 'Test 61');
test(validSequence("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "abcdefghijklmnopqrstuvwxy"), [0, 1, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48], 'Test 62');
test(validSequence("abcdabcdabcd", "abcd"), [0, 1, 2, 3], 'Test 63');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "abcdefghijklmnop"), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], 'Test 64');
test(validSequence("abcdefghijabcdefghijabcdefghij", "abcdefghij"), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'Test 65');
test(validSequence("abacabadabacaba", "abab"), [0, 1, 2, 3], 'Test 66');
test(validSequence("aaaabbbbcccc", "abccba"), [], 'Test 67');
test(validSequence("qwertyuiopasdfghjklzxcvbnm", "qaz"), [0, 1, 19], 'Test 68');
test(validSequence("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzz"), [0, 1, 2], 'Test 69');
test(validSequence("bacdefghijklmnopqrstuvwxyz", "abcdefg"), [], 'Test 70');
test(validSequence("alibabacloud", "abcl"), [0, 1, 7, 8], 'Test 71');
test(validSequence("aaaaaaaabbbbbbbbbbcccccccccddddddeeeeeeeeeeffffffffff", "abcdefghij"), [], 'Test 72');
test(validSequence("bbaabbaabbaabbaabbaabbaabbaab", "bbabbb"), [0, 1, 2, 3, 4, 5], 'Test 73');
test(validSequence("abcdefghij", "afh"), [0, 1, 7], 'Test 74');
test(validSequence("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "abc"), [], 'Test 75');
test(validSequence("abcdexyz", "abcdef"), [0, 1, 2, 3, 4, 5], 'Test 76');
test(validSequence("banana", "an"), [0, 2], 'Test 77');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "abcdefg"), [0, 1, 2, 3, 4, 5, 6], 'Test 78');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "abcdefghijklmnopqrstu"), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'Test 79');
test(validSequence("abababababababababababababababababababababababababababababababababababababababababababababababababababababababab", "abab"), [0, 1, 2, 3], 'Test 80');
test(validSequence("zzzzyyyxxxwwwwvvvvuuuuttttssssrrrrqqqqppppooooonnnnmmmmllllkkkkjjjjiiiihhhhggggffffffeeeeeeeedddddccccbbbaaaa", "abcdefg"), [], 'Test 81');
test(validSequence("xyzzyxzyxzyxzyxzyx", "xyzzyx"), [0, 1, 2, 3, 4, 5], 'Test 82');
test(validSequence("acacacacacacacacac", "aaaa"), [0, 1, 2, 4], 'Test 83');
test(validSequence("bbaaabbbaaabbbaaabbbaa", "baaba"), [0, 1, 2, 5, 8], 'Test 84');
test(validSequence("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "abcdefghijklmnopqrstuvwxyz"), [0, 1, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50], 'Test 85');
test(validSequence("banana", "bana"), [0, 1, 2, 3], 'Test 86');
test(validSequence("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "zzzyxwvutsrqponmlkjihgfedcba"), [], 'Test 87');
test(validSequence("abbaabbaabba", "abab"), [0, 1, 2, 5], 'Test 88');
test(validSequence("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "mnopqrstuvwxyz"), [0, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50], 'Test 89');
test(validSequence("abcdabcabcabcabcabcabcabcabcabcabc", "abcde"), [0, 1, 2, 3, 4], 'Test 90');
test(validSequence("abcabcabcabcabcabcabcabcabcabc", "abcabc"), [0, 1, 2, 3, 4, 5], 'Test 91');
test(validSequence("thisisalongstring", "this"), [0, 1, 2, 3], 'Test 92');
test(validSequence("zyxwvutsrqponmlkjihgfedcba", "fedcba"), [0, 21, 22, 23, 24, 25], 'Test 93');
test(validSequence("qwertyuiopasdfghjklzxcvbnm", "qwertyuiop"), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'Test 94');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "qrstuv"), [0, 17, 18, 19, 20, 21], 'Test 95');
test(validSequence("abcdabc", "abc"), [0, 1, 2], 'Test 96');
test(validSequence("abcdabcdabcdabcd", "abca"), [0, 1, 2, 3], 'Test 97');
test(validSequence("abacabadabacaba", "abada"), [0, 1, 2, 3, 4], 'Test 98');
test(validSequence("racecar", "ace"), [0, 2, 3], 'Test 99');
test(validSequence("abcabcabcabcabcabcabc", "abcabc"), [0, 1, 2, 3, 4, 5], 'Test 100');
test(validSequence("bbaaaabaaaabbaa", "bab"), [0, 1, 6], 'Test 101');
test(validSequence("abababababababababab", "aaa"), [0, 1, 2], 'Test 102');
test(validSequence("abcdabcdabcdabcd", "abcdabcd"), [0, 1, 2, 3, 4, 5, 6, 7], 'Test 103');
test(validSequence("aaaaabbbbbcccccddddd", "abcde"), [0, 5, 10, 15, 16], 'Test 104');
test(validSequence("xyzzxyzzxyzz", "xyzxyz"), [0, 1, 2, 3, 5, 6], 'Test 105');
test(validSequence("abcdefghiklmnopqrstuvwxyz", "aikuyz"), [0, 1, 9, 19, 23, 24], 'Test 106');
test(validSequence("amazingrace", "amazing"), [0, 1, 2, 3, 4, 5, 6], 'Test 107');
test(validSequence("pythonprogramming", "python"), [0, 1, 2, 3, 4, 5], 'Test 108');
test(validSequence("aabbaabbaabbaabb", "aabb"), [0, 1, 2, 3], 'Test 109');
test(validSequence("abacabadabacabadabacabad", "abcabc"), [0, 1, 2, 4, 5, 11], 'Test 110');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "xyzabc"), [], 'Test 111');
test(validSequence("abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyz"), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], 'Test 112');
test(validSequence("acbacbacbac", "abcabc"), [0, 1, 4, 6, 8, 10], 'Test 113');
test(validSequence("abacaba", "aaa"), [0, 1, 2], 'Test 114');
test(validSequence("repeatedrepeatedrepeated", "repeated"), [0, 1, 2, 3, 4, 5, 6, 7], 'Test 115');
test(validSequence("xyzxyzxyzxyzxyzxyzxyz", "xyzxyz"), [0, 1, 2, 3, 4, 5], 'Test 116');
test(validSequence("abcdefgabcdefgabcdefgabcdefg", "abcdefg"), [0, 1, 2, 3, 4, 5, 6], 'Test 117');
test(validSequence("aaabbbcccdddeeefffggghhhiii", "abcdefghi"), [0, 1, 6, 9, 12, 15, 18, 21, 24], 'Test 118');
test(validSequence("xyzxyzxyzxyz", "xyzxyz"), [0, 1, 2, 3, 4, 5], 'Test 119');
test(validSequence("mississippi", "miss"), [0, 1, 2, 3], 'Test 120');
test(validSequence("foobartoobarfoo", "foobar"), [0, 1, 2, 3, 4, 5], 'Test 121');
test(validSequence("aabbaabbaabbaabbaabb", "aabbaab"), [0, 1, 2, 3, 4, 5, 6], 'Test 122');
test(validSequence("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzz"), [0, 1, 2, 3, 4, 5], 'Test 123');
test(validSequence("mississippi", "mis"), [0, 1, 2], 'Test 124');
test(validSequence("hellotherehellotherehellotherehellotherehellotherehellotherehellotherehellotherehellothere", "here"), [0, 1, 2, 7], 'Test 125');
test(validSequence("thisisaverylongstringthatweneedtouse", "string"), [0, 16, 17, 18, 19, 20], 'Test 126');
test(validSequence("xyzzxyzzxyzzxyzz", "zzzz"), [0, 2, 3, 6], 'Test 127');
test(validSequence("abcabcabcabcabc", "abcabc"), [0, 1, 2, 3, 4, 5], 'Test 128');
test(validSequence("hellothere", "her"), [0, 1, 2], 'Test 129');
test(validSequence("abacabadabacaba", "abc"), [0, 1, 2], 'Test 130');
test(validSequence("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "abcdefghijklmnopqrstuvw"), [0, 1, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44], 'Test 131');
test(validSequence("pneumonoultramicroscopicsilicovolcanoconiosis", "pneumo"), [0, 1, 2, 3, 4, 5], 'Test 132');
test(validSequence("baaabaaaabaaabaababaaaab", "baaba"), [0, 1, 2, 3, 5], 'Test 133');
test(validSequence("abacabadabacaba", "abaca"), [0, 1, 2, 3, 4], 'Test 134');
test(validSequence("zyxwvutsrqponmlkjihgfedcba", "abcde"), [], 'Test 135');
test(validSequence("hellohellohellohellohellohello", "hello"), [0, 1, 2, 3, 4], 'Test 136');
test(validSequence("hellohellohello", "helo"), [0, 1, 2, 3], 'Test 137');
test(validSequence("zyxwvutsrqponmlkjihgfedcba", "mnopqrstuvwxyza"), [], 'Test 138');
test(validSequence("xxxxxxxxxyyyyyyyyyzzzzzzzzz", "xyz"), [0, 1, 18], 'Test 139');
test(validSequence("zyxzyxzyxzyxzyxzyxzyxzyxzyx", "zyxzyxzyx"), [0, 1, 2, 3, 4, 5, 6, 7, 8], 'Test 140');
test(validSequence("abababab", "aba"), [0, 1, 2], 'Test 141');
test(validSequence("zyxwvutsrqponmlkjihgfedcba", "zyxwv"), [0, 1, 2, 3, 4], 'Test 142');
test(validSequence("programming", "pgm"), [0, 1, 6], 'Test 143');
test(validSequence("abacabadabacabadabacaba", "ababa"), [0, 1, 2, 3, 4], 'Test 144');
test(validSequence("zzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzz"), [0, 1, 2], 'Test 145');
test(validSequence("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz", "abcdefghijklmnopqrstuvwxyz"), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], 'Test 146');
test(validSequence("abacabadabacabadaba", "abc"), [0, 1, 2], 'Test 147');
test(validSequence("aaaabbbbccccddddeeeeffffgggg", "abcdefg"), [0, 1, 8, 12, 16, 20, 24], 'Test 148');
test(validSequence("aaaaaabbbaaaaabaaaaabbbaaa", "aabbaab"), [0, 1, 2, 6, 9, 10, 14], 'Test 149');
test(validSequence("qwertyuiopasdfghjklzxcvbnm", "qwerty"), [0, 1, 2, 3, 4, 5], 'Test 150');
test(validSequence("qwertyuiopasdfghjklzxcvbnm", "qzpm"), [0, 1, 9, 25], 'Test 151');
test(validSequence("mississippiississippi", "misis"), [0, 1, 2, 3, 5], 'Test 152');
test(validSequence("thisisaverylongstringwithsomerepeatingcharacters", "thisis"), [0, 1, 2, 3, 4, 5], 'Test 153');
test(validSequence("pppppppppppppppppp", "ppp"), [0, 1, 2], 'Test 154');
test(validSequence("abcdefghijklmnopqrstuvwxyz", "zyx"), [], 'Test 155');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

