// Test: 824. Goat Latin
// 135 test cases from LeetCodeDataset
// Run: node test.js

const { toGoatLatin } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n824. Goat Latin\n");

test(toGoatLatin("Convert this sentence"), onvertCmaa histmaaa entencesmaaaa, 'Test 1');
test(toGoatLatin("In the end"), Inmaa hetmaaa endmaaaa, 'Test 2');
test(toGoatLatin("a e i o u"), amaa emaaa imaaaa omaaaaa umaaaaaa, 'Test 3');
test(toGoatLatin("Hello world"), elloHmaa orldwmaaa, 'Test 4');
test(toGoatLatin("Python is great"), ythonPmaa ismaaa reatgmaaaa, 'Test 5');
test(toGoatLatin("This is a test"), hisTmaa ismaaa amaaaa esttmaaaaa, 'Test 6');
test(toGoatLatin("Hello World"), elloHmaa orldWmaaa, 'Test 7');
test(toGoatLatin("Goat Latin Example"), oatGmaa atinLmaaa Examplemaaaa, 'Test 8');
test(toGoatLatin("Convert this sentence to Goat Latin"), onvertCmaa histmaaa entencesmaaaa otmaaaaa oatGmaaaaaa atinLmaaaaaaa, 'Test 9');
test(toGoatLatin("The quick brown fox jumped over the lazy dog"), heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpedjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa, 'Test 10');
test(toGoatLatin("Programming is fun"), rogrammingPmaa ismaaa unfmaaaa, 'Test 11');
test(toGoatLatin("Every vowel example"), Everymaa owelvmaaa examplemaaaa, 'Test 12');
test(toGoatLatin("hello world"), ellohmaa orldwmaaa, 'Test 13');
test(toGoatLatin("Goat Latin is easy"), oatGmaa atinLmaaa ismaaaa easymaaaaa, 'Test 14');
test(toGoatLatin("Keep practicing"), eepKmaa racticingpmaaa, 'Test 15');
test(toGoatLatin("Conversion to Goat Latin"), onversionCmaa otmaaa oatGmaaaa atinLmaaaaa, 'Test 16');
test(toGoatLatin("I speak Goat Latin"), Imaa peaksmaaa oatGmaaaa atinLmaaaaa, 'Test 17');
test(toGoatLatin("Every word matters"), Everymaa ordwmaaa attersmmaaaa, 'Test 18');
test(toGoatLatin("ChatGPT is an AI language model"), hatGPTCmaa ismaaa anmaaaa AImaaaaa anguagelmaaaaaa odelmmaaaaaaa, 'Test 19');
test(toGoatLatin("A big brown dog jumps over a lazy fox"), Amaa igbmaaa rownbmaaaa ogdmaaaaa umpsjmaaaaaa overmaaaaaaa amaaaaaaaa azylmaaaaaaaaa oxfmaaaaaaaaaa, 'Test 20');
test(toGoatLatin("Quick brown fox jumps over the lazy dog"), uickQmaa rownbmaaa oxfmaaaa umpsjmaaaaa overmaaaaaa hetmaaaaaaa azylmaaaaaaaa ogdmaaaaaaaaa, 'Test 21');
test(toGoatLatin("Frogs jump joyfully in the rain"), rogsFmaa umpjmaaa oyfullyjmaaaa inmaaaaa hetmaaaaaa ainrmaaaaaaa, 'Test 22');
test(toGoatLatin("Conversion to Goat Latin should handle complex sentences properly"), onversionCmaa otmaaa oatGmaaaa atinLmaaaaa houldsmaaaaaa andlehmaaaaaaa omplexcmaaaaaaaa entencessmaaaaaaaaa roperlypmaaaaaaaaaa, 'Test 23');
test(toGoatLatin("The quick brown fox jumps over the lazy dog and runs"), heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa andmaaaaaaaaaaa unsrmaaaaaaaaaaaa, 'Test 24');
test(toGoatLatin("User experience design and usability"), Usermaa experiencemaaa esigndmaaaa andmaaaaa usabilitymaaaaaa, 'Test 25');
test(toGoatLatin("This is an interesting problem to solve"), hisTmaa ismaaa anmaaaa interestingmaaaaa roblempmaaaaaa otmaaaaaaa olvesmaaaaaaaa, 'Test 26');
test(toGoatLatin("A quick brown fox jumps over the lazy dog"), Amaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa, 'Test 27');
test(toGoatLatin("This is a simple test case for Goat Latin"), hisTmaa ismaaa amaaaa implesmaaaaa esttmaaaaaa asecmaaaaaaa orfmaaaaaaaa oatGmaaaaaaaaa atinLmaaaaaaaaaa, 'Test 28');
test(toGoatLatin("Another Example to demonstrate the Conversion"), Anothermaa Examplemaaa otmaaaa emonstratedmaaaaa hetmaaaaaa onversionCmaaaaaaa, 'Test 29');
test(toGoatLatin("Let us create more examples for testing"), etLmaa usmaaa reatecmaaaa oremmaaaaa examplesmaaaaaa orfmaaaaaaa estingtmaaaaaaaa, 'Test 30');
test(toGoatLatin("a e i o u A E I O U"), amaa emaaa imaaaa omaaaaa umaaaaaa Amaaaaaaa Emaaaaaaaa Imaaaaaaaaa Omaaaaaaaaaa Umaaaaaaaaaaa, 'Test 31');
test(toGoatLatin("Lorem ipsum dolor sit amet consectetur adipiscing elit"), oremLmaa ipsummaaa olordmaaaa itsmaaaaa ametmaaaaaa onsecteturcmaaaaaaa adipiscingmaaaaaaaa elitmaaaaaaaaa, 'Test 32');
test(toGoatLatin("Every vowel and consonant has its own rule"), Everymaa owelvmaaa andmaaaa onsonantcmaaaaa ashmaaaaaa itsmaaaaaaa ownmaaaaaaaa ulermaaaaaaaaa, 'Test 33');
test(toGoatLatin("The quick brown fox jumps over the lazy dog and plays"), heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa andmaaaaaaaaaaa layspmaaaaaaaaaaaa, 'Test 34');
test(toGoatLatin("Sphinx of black quartz judge my vow"), phinxSmaa ofmaaa lackbmaaaa uartzqmaaaaa udgejmaaaaaa ymmaaaaaaa owvmaaaaaaaa, 'Test 35');
test(toGoatLatin("Artificial intelligence is transforming the world"), Artificialmaa intelligencemaaa ismaaaa ransformingtmaaaaa hetmaaaaaa orldwmaaaaaaa, 'Test 36');
test(toGoatLatin("Gnomes gather golden grains gracefully gathering groups"), nomesGmaa athergmaaa oldengmaaaa rainsgmaaaaa racefullygmaaaaaa atheringgmaaaaaaa roupsgmaaaaaaaa, 'Test 37');
test(toGoatLatin("Natural language processing is revolutionizing technology"), aturalNmaa anguagelmaaa rocessingpmaaaa ismaaaaa evolutionizingrmaaaaaa echnologytmaaaaaaa, 'Test 38');
test(toGoatLatin("Python programming is fun"), ythonPmaa rogrammingpmaaa ismaaaa unfmaaaaa, 'Test 39');
test(toGoatLatin("The weather today is absolutely perfect"), heTmaa eatherwmaaa odaytmaaaa ismaaaaa absolutelymaaaaaa erfectpmaaaaaaa, 'Test 40');
test(toGoatLatin("Let us see how this conversion works"), etLmaa usmaaa eesmaaaa owhmaaaaa histmaaaaaa onversioncmaaaaaaa orkswmaaaaaaaa, 'Test 41');
test(toGoatLatin("Internet of Things and smart devices"), Internetmaa ofmaaa hingsTmaaaa andmaaaaa martsmaaaaaa evicesdmaaaaaaa, 'Test 42');
test(toGoatLatin("OpenAI develops advanced AI systems"), OpenAImaa evelopsdmaaa advancedmaaaa AImaaaaa ystemssmaaaaaa, 'Test 43');
test(toGoatLatin("Edge cases exercise existing expertise effectively"), Edgemaa asescmaaa exercisemaaaa existingmaaaaa expertisemaaaaaa effectivelymaaaaaaa, 'Test 44');
test(toGoatLatin("Zoologists zealously zoom into zoological zoological zones"), oologistsZmaa ealouslyzmaaa oomzmaaaa intomaaaaa oologicalzmaaaaaa oologicalzmaaaaaaa oneszmaaaaaaaa, 'Test 45');
test(toGoatLatin("Beautiful scenery and wonderful views"), eautifulBmaa cenerysmaaa andmaaaa onderfulwmaaaaa iewsvmaaaaaa, 'Test 46');
test(toGoatLatin("Mixed CASE Words Should Still Work"), ixedMmaa ASECmaaa ordsWmaaaa houldSmaaaaa tillSmaaaaaa orkWmaaaaaaa, 'Test 47');
test(toGoatLatin("Every vowel and consonant has a unique rule"), Everymaa owelvmaaa andmaaaa onsonantcmaaaaa ashmaaaaaa amaaaaaaa uniquemaaaaaaaa ulermaaaaaaaaa, 'Test 48');
test(toGoatLatin("Artificial intelligence will change our lives"), Artificialmaa intelligencemaaa illwmaaaa hangecmaaaaa ourmaaaaaa iveslmaaaaaaa, 'Test 49');
test(toGoatLatin("Testing edge cases like empty spaces in between words"), estingTmaa edgemaaa asescmaaaa ikelmaaaaa emptymaaaaaa pacessmaaaaaaa inmaaaaaaaa etweenbmaaaaaaaaa ordswmaaaaaaaaaa, 'Test 50');
test(toGoatLatin("Programming in Python is fun and challenging"), rogrammingPmaa inmaaa ythonPmaaaa ismaaaaa unfmaaaaaa andmaaaaaaa hallengingcmaaaaaaaa, 'Test 51');
test(toGoatLatin("This is a longer sentence that includes several words to ensure the solution works correctly"), hisTmaa ismaaa amaaaa ongerlmaaaaa entencesmaaaaaa hattmaaaaaaa includesmaaaaaaaa everalsmaaaaaaaaa ordswmaaaaaaaaaa otmaaaaaaaaaaa ensuremaaaaaaaaaaaa hetmaaaaaaaaaaaaa olutionsmaaaaaaaaaaaaaa orkswmaaaaaaaaaaaaaaa orrectlycmaaaaaaaaaaaaaaaa, 'Test 52');
test(toGoatLatin("This is a simple test"), hisTmaa ismaaa amaaaa implesmaaaaa esttmaaaaaa, 'Test 53');
test(toGoatLatin("Conversion to Goat Latin can be tricky"), onversionCmaa otmaaa oatGmaaaa atinLmaaaaa ancmaaaaaa ebmaaaaaaa rickytmaaaaaaaa, 'Test 54');
test(toGoatLatin("Complex sentences with various words"), omplexCmaa entencessmaaa ithwmaaaa ariousvmaaaaa ordswmaaaaaa, 'Test 55');
test(toGoatLatin("Understanding algorithms and data structures"), Understandingmaa algorithmsmaaa andmaaaa atadmaaaaa tructuressmaaaaaa, 'Test 56');
test(toGoatLatin("Goat Latin is a fun and creative language"), oatGmaa atinLmaaa ismaaaa amaaaaa unfmaaaaaa andmaaaaaaa reativecmaaaaaaaa anguagelmaaaaaaaaa, 'Test 57');
test(toGoatLatin("Consonants should move their first letter to the end"), onsonantsCmaa houldsmaaa ovemmaaaa heirtmaaaaa irstfmaaaaaa etterlmaaaaaaa otmaaaaaaaa hetmaaaaaaaaa endmaaaaaaaaaa, 'Test 58');
test(toGoatLatin("Fascinating flora frequently feed furry friends"), ascinatingFmaa lorafmaaa requentlyfmaaaa eedfmaaaaa urryfmaaaaaa riendsfmaaaaaaa, 'Test 59');
test(toGoatLatin("Keep pushing your limits and you will achieve great things"), eepKmaa ushingpmaaa ourymaaaa imitslmaaaaa andmaaaaaa ouymaaaaaaa illwmaaaaaaaa achievemaaaaaaaaa reatgmaaaaaaaaaa hingstmaaaaaaaaaaa, 'Test 60');
test(toGoatLatin("Software engineering principles"), oftwareSmaa engineeringmaaa rinciplespmaaaa, 'Test 61');
test(toGoatLatin("Every vowel must be handled"), Everymaa owelvmaaa ustmmaaaa ebmaaaaa andledhmaaaaaa, 'Test 62');
test(toGoatLatin("Testing multiple words with varied starting letters"), estingTmaa ultiplemmaaa ordswmaaaa ithwmaaaaa ariedvmaaaaaa tartingsmaaaaaaa etterslmaaaaaaaa, 'Test 63');
test(toGoatLatin("Beautiful butterflies brightly bask in blazing sunshine"), eautifulBmaa utterfliesbmaaa rightlybmaaaa askbmaaaaa inmaaaaaa lazingbmaaaaaaa unshinesmaaaaaaaa, 'Test 64');
test(toGoatLatin("The quick brown fox jumps over the lazy dog on a sunny day"), heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa onmaaaaaaaaaaa amaaaaaaaaaaaa unnysmaaaaaaaaaaaaa aydmaaaaaaaaaaaaaa, 'Test 65');
test(toGoatLatin("Machine learning is transforming the world"), achineMmaa earninglmaaa ismaaaa ransformingtmaaaaa hetmaaaaaa orldwmaaaaaaa, 'Test 66');
test(toGoatLatin("b c d f g h j k l m n p q r s t v w x y z B C D F G H J K L M N P Q R S T V W X Y Z"), bmaa cmaaa dmaaaa fmaaaaa gmaaaaaa hmaaaaaaa jmaaaaaaaa kmaaaaaaaaa lmaaaaaaaaaa mmaaaaaaaaaaa nmaaaaaaaaaaaa pmaaaaaaaaaaaaa qmaaaaaaaaaaaaaa rmaaaaaaaaaaaaaaa smaaaaaaaaaaaaaaaa tmaaaaaaaaaaaaaaaaa vmaaaaaaaaaaaaaaaaaa wmaaaaaaaaaaaaaaaaaaa xmaaaaaaaaaaaaaaaaaaaa ymaaaaaaaaaaaaaaaaaaaaa zmaaaaaaaaaaaaaaaaaaaaaa Bmaaaaaaaaaaaaaaaaaaaaaaa Cmaaaaaaaaaaaaaaaaaaaaaaaa Dmaaaaaaaaaaaaaaaaaaaaaaaaa Fmaaaaaaaaaaaaaaaaaaaaaaaaaa Gmaaaaaaaaaaaaaaaaaaaaaaaaaaa Hmaaaaaaaaaaaaaaaaaaaaaaaaaaaa Jmaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Kmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Lmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Mmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Nmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Pmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Qmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Rmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Smaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Tmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Vmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Wmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Xmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Ymaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Zmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, 'Test 67');
test(toGoatLatin("Bright vixens jump over the lazy dog"), rightBmaa ixensvmaaa umpjmaaaa overmaaaaa hetmaaaaaa azylmaaaaaaa ogdmaaaaaaaa, 'Test 68');
test(toGoatLatin("Hello world this is a test sentence"), elloHmaa orldwmaaa histmaaaa ismaaaaa amaaaaaa esttmaaaaaaa entencesmaaaaaaaa, 'Test 69');
test(toGoatLatin("Natural language processing and chatbots"), aturalNmaa anguagelmaaa rocessingpmaaaa andmaaaaa hatbotscmaaaaaa, 'Test 70');
test(toGoatLatin("Lazy dogs jump over sleeping cats"), azyLmaa ogsdmaaa umpjmaaaa overmaaaaa leepingsmaaaaaa atscmaaaaaaa, 'Test 71');
test(toGoatLatin("Computer vision and image processing"), omputerCmaa isionvmaaa andmaaaa imagemaaaaa rocessingpmaaaaaa, 'Test 72');
test(toGoatLatin("Every vowel should remain unchanged ma"), Everymaa owelvmaaa houldsmaaaa emainrmaaaaa unchangedmaaaaaa ammaaaaaaa, 'Test 73');
test(toGoatLatin("The five boxing wizards jump quickly"), heTmaa ivefmaaa oxingbmaaaa izardswmaaaaa umpjmaaaaaa uicklyqmaaaaaaa, 'Test 74');
test(toGoatLatin("Blockchain technology and cryptography"), lockchainBmaa echnologytmaaa andmaaaa ryptographycmaaaaa, 'Test 75');
test(toGoatLatin("Debugging code can be challenging"), ebuggingDmaa odecmaaa ancmaaaa ebmaaaaa hallengingcmaaaaaa, 'Test 76');
test(toGoatLatin("Python Programming Language is Fun"), ythonPmaa rogrammingPmaaa anguageLmaaaa ismaaaaa unFmaaaaaa, 'Test 77');
test(toGoatLatin("Algorithm design and analysis"), Algorithmmaa esigndmaaa andmaaaa analysismaaaaa, 'Test 78');
test(toGoatLatin("Alphabet University of Economics and Business Administration"), Alphabetmaa Universitymaaa ofmaaaa Economicsmaaaaa andmaaaaaa usinessBmaaaaaaa Administrationmaaaaaaaa, 'Test 79');
test(toGoatLatin("Continuous integration and deployment"), ontinuousCmaa integrationmaaa andmaaaa eploymentdmaaaaa, 'Test 80');
test(toGoatLatin("Beautiful scenery in nature"), eautifulBmaa cenerysmaaa inmaaaa aturenmaaaaa, 'Test 81');
test(toGoatLatin("Machine learning models are fascinating"), achineMmaa earninglmaaa odelsmmaaaa aremaaaaa ascinatingfmaaaaaa, 'Test 82');
test(toGoatLatin("Jackdaws love my big sphinx of quartz"), ackdawsJmaa ovelmaaa ymmaaaa igbmaaaaa phinxsmaaaaaa ofmaaaaaaa uartzqmaaaaaaaa, 'Test 83');
test(toGoatLatin("The brown fox jumps over a lazy dog"), heTmaa rownbmaaa oxfmaaaa umpsjmaaaaa overmaaaaaa amaaaaaaa azylmaaaaaaaa ogdmaaaaaaaaa, 'Test 84');
test(toGoatLatin("Python programming promotes productivity and problem solving"), ythonPmaa rogrammingpmaaa romotespmaaaa roductivitypmaaaaa andmaaaaaa roblempmaaaaaaa olvingsmaaaaaaaa, 'Test 85');
test(toGoatLatin("High performance computing and big data"), ighHmaa erformancepmaaa omputingcmaaaa andmaaaaa igbmaaaaaa atadmaaaaaaa, 'Test 86');
test(toGoatLatin("The quick brown fox jumps over the lazy dog quickly"), heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa uicklyqmaaaaaaaaaaa, 'Test 87');
test(toGoatLatin("The quick brown fox jumps over the lazy dog"), heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa, 'Test 88');
test(toGoatLatin("Data analysis and machine learning"), ataDmaa analysismaaa andmaaaa achinemmaaaaa earninglmaaaaaa, 'Test 89');
test(toGoatLatin("ComplexSentencesWithNoSpaces"), omplexSentencesWithNoSpacesCmaa, 'Test 90');
test(toGoatLatin("Understanding complex algorithms unravelles endless possibilities"), Understandingmaa omplexcmaaa algorithmsmaaaa unravellesmaaaaa endlessmaaaaaa ossibilitiespmaaaaaaa, 'Test 91');
test(toGoatLatin("Watch Jeopardy on NBC"), atchWmaa eopardyJmaaa onmaaaa BCNmaaaaa, 'Test 92');
test(toGoatLatin("Artificial neural networks and deep learning"), Artificialmaa euralnmaaa etworksnmaaaa andmaaaaa eepdmaaaaaa earninglmaaaaaaa, 'Test 93');
test(toGoatLatin("Data structures and algorithms"), ataDmaa tructuressmaaa andmaaaa algorithmsmaaaaa, 'Test 94');
test(toGoatLatin("Algorithms are crucial for computer science"), Algorithmsmaa aremaaa rucialcmaaaa orfmaaaaa omputercmaaaaaa ciencesmaaaaaaa, 'Test 95');
test(toGoatLatin("Consonants should also be tested"), onsonantsCmaa houldsmaaa alsomaaaa ebmaaaaa estedtmaaaaaa, 'Test 96');
test(toGoatLatin("She sells sea shells by the sea shore"), heSmaa ellssmaaa easmaaaa hellssmaaaaa ybmaaaaaa hetmaaaaaaa easmaaaaaaaa horesmaaaaaaaaa, 'Test 97');
test(toGoatLatin("abcdefghijklmnopqrstuvwxyz"), abcdefghijklmnopqrstuvwxyzmaa, 'Test 98');
test(toGoatLatin("A big black bear sat on a big black rug"), Amaa igbmaaa lackbmaaaa earbmaaaaa atsmaaaaaa onmaaaaaaa amaaaaaaaa igbmaaaaaaaaa lackbmaaaaaaaaaa ugrmaaaaaaaaaaa, 'Test 99');
test(toGoatLatin("Multiple words starting with a consonant"), ultipleMmaa ordswmaaa tartingsmaaaa ithwmaaaaa amaaaaaa onsonantcmaaaaaaa, 'Test 100');
test(toGoatLatin("How vexingly quick daft zebras jump"), owHmaa exinglyvmaaa uickqmaaaa aftdmaaaaa ebraszmaaaaaa umpjmaaaaaaa, 'Test 101');
test(toGoatLatin("SingleWord"), ingleWordSmaa, 'Test 102');
test(toGoatLatin("An example of a more complex sentence conversion"), Anmaa examplemaaa ofmaaaa amaaaaa oremmaaaaaa omplexcmaaaaaaa entencesmaaaaaaaa onversioncmaaaaaaaaa, 'Test 103');
test(toGoatLatin("Transformations are always fascinating"), ransformationsTmaa aremaaa alwaysmaaaa ascinatingfmaaaaa, 'Test 104');
test(toGoatLatin("Single"), ingleSmaa, 'Test 105');
test(toGoatLatin("bc df gh jk lm np qr st vx zy"), cbmaa fdmaaa hgmaaaa kjmaaaaa mlmaaaaaa pnmaaaaaaa rqmaaaaaaaa tsmaaaaaaaaa xvmaaaaaaaaaa yzmaaaaaaaaaaa, 'Test 106');
test(toGoatLatin("Algorithms and data structures"), Algorithmsmaa andmaaa atadmaaaa tructuressmaaaaa, 'Test 107');
test(toGoatLatin("Sometimes it rains cats and dogs"), ometimesSmaa itmaaa ainsrmaaaa atscmaaaaa andmaaaaaa ogsdmaaaaaaa, 'Test 108');
test(toGoatLatin("Understanding the rules of Goat Latin"), Understandingmaa hetmaaa ulesrmaaaa ofmaaaaa oatGmaaaaaa atinLmaaaaaaa, 'Test 109');
test(toGoatLatin("This is an elaborate test case with multiple words"), hisTmaa ismaaa anmaaaa elaboratemaaaaa esttmaaaaaa asecmaaaaaaa ithwmaaaaaaaa ultiplemmaaaaaaaaa ordswmaaaaaaaaaa, 'Test 110');
test(toGoatLatin("The early morning dew dries"), heTmaa earlymaaa orningmmaaaa ewdmaaaaa riesdmaaaaaa, 'Test 111');
test(toGoatLatin("Short long longer longest longestest"), hortSmaa onglmaaa ongerlmaaaa ongestlmaaaaa ongestestlmaaaaaa, 'Test 112');
test(toGoatLatin("Quantum computing and future technologies"), uantumQmaa omputingcmaaa andmaaaa uturefmaaaaa echnologiestmaaaaaa, 'Test 113');
test(toGoatLatin("The five boxing wizards jump quickly on this extraordinary bicycle"), heTmaa ivefmaaa oxingbmaaaa izardswmaaaaa umpjmaaaaaa uicklyqmaaaaaaa onmaaaaaaaa histmaaaaaaaaa extraordinarymaaaaaaaaaa icyclebmaaaaaaaaaaa, 'Test 114');
test(toGoatLatin("Python programming is fun and educational"), ythonPmaa rogrammingpmaaa ismaaaa unfmaaaaa andmaaaaaa educationalmaaaaaaa, 'Test 115');
test(toGoatLatin("Multiple words starting with a vowel"), ultipleMmaa ordswmaaa tartingsmaaaa ithwmaaaaa amaaaaaa owelvmaaaaaaa, 'Test 116');
test(toGoatLatin("Fuzzy wuzzy was a bear"), uzzyFmaa uzzywmaaa aswmaaaa amaaaaa earbmaaaaaa, 'Test 117');
test(toGoatLatin("Cloud computing and artificial intelligence"), loudCmaa omputingcmaaa andmaaaa artificialmaaaaa intelligencemaaaaaa, 'Test 118');
test(toGoatLatin("AEIOU aeiou UUIIOOAAEE"), AEIOUmaa aeioumaaa UUIIOOAAEEmaaaa, 'Test 119');
test(toGoatLatin("Multiple words with different starting letters"), ultipleMmaa ordswmaaa ithwmaaaa ifferentdmaaaaa tartingsmaaaaaa etterslmaaaaaaa, 'Test 120');
test(toGoatLatin("The quick brown fox jumps over the lazy dog several times"), heTmaa uickqmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa everalsmaaaaaaaaaaa imestmaaaaaaaaaaaa, 'Test 121');
test(toGoatLatin("Xylophones yield xylophonic xenon xylophonically"), ylophonesXmaa ieldymaaa ylophonicxmaaaa enonxmaaaaa ylophonicallyxmaaaaaa, 'Test 122');
test(toGoatLatin("Open source software development"), Openmaa ourcesmaaa oftwaresmaaaa evelopmentdmaaaaa, 'Test 123');
test(toGoatLatin("A rapid brown fox jumps over the lazy dog"), Amaa apidrmaaa rownbmaaaa oxfmaaaaa umpsjmaaaaaa overmaaaaaaa hetmaaaaaaaa azylmaaaaaaaaa ogdmaaaaaaaaaa, 'Test 124');
test(toGoatLatin("Quickly zigzagging through the dense forest"), uicklyQmaa igzaggingzmaaa hroughtmaaaa hetmaaaaa ensedmaaaaaa orestfmaaaaaaa, 'Test 125');
test(toGoatLatin("Programming in Python is fun"), rogrammingPmaa inmaaa ythonPmaaaa ismaaaaa unfmaaaaaa, 'Test 126');
test(toGoatLatin("An elephant and an antelope"), Anmaa elephantmaaa andmaaaa anmaaaaa antelopemaaaaaa, 'Test 127');
test(toGoatLatin("This is an exceptionally long sentence to test the robustness of the solution"), hisTmaa ismaaa anmaaaa exceptionallymaaaaa onglmaaaaaa entencesmaaaaaaa otmaaaaaaaa esttmaaaaaaaaa hetmaaaaaaaaaa obustnessrmaaaaaaaaaaa ofmaaaaaaaaaaaa hetmaaaaaaaaaaaaa olutionsmaaaaaaaaaaaaaa, 'Test 128');
test(toGoatLatin("An exquisite oriental fan"), Anmaa exquisitemaaa orientalmaaaa anfmaaaaa, 'Test 129');
test(toGoatLatin("ABCDEFGHIJKLMNOPQRSTUVWXYZ"), ABCDEFGHIJKLMNOPQRSTUVWXYZmaa, 'Test 130');
test(toGoatLatin("Virtual reality and augmented reality"), irtualVmaa ealityrmaaa andmaaaa augmentedmaaaaa ealityrmaaaaaa, 'Test 131');
test(toGoatLatin("Every vowel should be handled properly"), Everymaa owelvmaaa houldsmaaaa ebmaaaaa andledhmaaaaaa roperlypmaaaaaaa, 'Test 132');
test(toGoatLatin("A quick movement of the enemy will jeopardize five gunboats"), Amaa uickqmaaa ovementmmaaaa ofmaaaaa hetmaaaaaa enemymaaaaaaa illwmaaaaaaaa eopardizejmaaaaaaaaa ivefmaaaaaaaaaa unboatsgmaaaaaaaaaaa, 'Test 133');
test(toGoatLatin("Beautiful butterflies brightly bask in blazing sun"), eautifulBmaa utterfliesbmaaa rightlybmaaaa askbmaaaaa inmaaaaaa lazingbmaaaaaaa unsmaaaaaaaa, 'Test 134');
test(toGoatLatin("This is a test of the Goat Latin conversion tool"), hisTmaa ismaaa amaaaa esttmaaaaa ofmaaaaaa hetmaaaaaaa oatGmaaaaaaaa atinLmaaaaaaaaa onversioncmaaaaaaaaaa ooltmaaaaaaaaaaa, 'Test 135');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

