// Test: 2486. Append Characters To String To Make Subsequence
// 153 test cases from LeetCodeDataset
// Run: node test.js

const { appendCharacters } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n2486. Append Characters To String To Make Subsequence\n");

test(appendCharacters("abcdefgh", "ghijkl"), 4, 'Test 1');
test(appendCharacters("ababab", "bbba"), 1, 'Test 2');
test(appendCharacters("abcd", "xyz"), 3, 'Test 3');
test(appendCharacters("aaaa", "a"), 0, 'Test 4');
test(appendCharacters("abcd", "dbca"), 3, 'Test 5');
test(appendCharacters("aabbcc", "abc"), 0, 'Test 6');
test(appendCharacters("aaaaa", "a"), 0, 'Test 7');
test(appendCharacters("abcd", "abcde"), 1, 'Test 8');
test(appendCharacters("ababab", "bbbb"), 1, 'Test 9');
test(appendCharacters("ab", "abc"), 1, 'Test 10');
test(appendCharacters("abcdefgh", "efghij"), 2, 'Test 11');
test(appendCharacters("hello", "oleh"), 3, 'Test 12');
test(appendCharacters("abcd", ""), 0, 'Test 13');
test(appendCharacters("abcde", "a"), 0, 'Test 14');
test(appendCharacters("abcd", "abdc"), 1, 'Test 15');
test(appendCharacters("abcd", "abcd"), 0, 'Test 16');
test(appendCharacters("z", "abcde"), 5, 'Test 17');
test(appendCharacters("", "abc"), 3, 'Test 18');
test(appendCharacters("abcabc", "abc"), 0, 'Test 19');
test(appendCharacters("hello", "ole"), 2, 'Test 20');
test(appendCharacters("abcdefgh", "efgh"), 0, 'Test 21');
test(appendCharacters("a", "b"), 1, 'Test 22');
test(appendCharacters("coaching", "coding"), 4, 'Test 23');
test(appendCharacters("abc", ""), 0, 'Test 24');
test(appendCharacters("xyz", "xyza"), 1, 'Test 25');
test(appendCharacters("xyz", "xyz"), 0, 'Test 26');
test(appendCharacters("", "abcd"), 4, 'Test 27');
test(appendCharacters("abcd", "efgh"), 4, 'Test 28');
test(appendCharacters("aaaa", "aa"), 0, 'Test 29');
test(appendCharacters("complex", "cmpx"), 0, 'Test 30');
test(appendCharacters("abcabcabcabcabcabc", "abcabcabcabcabcd"), 1, 'Test 31');
test(appendCharacters("thisisaverylongstring", "thisstring"), 0, 'Test 32');
test(appendCharacters("hellothere", "lohere"), 0, 'Test 33');
test(appendCharacters("ababababab", "bababa"), 0, 'Test 34');
test(appendCharacters("xyzxyzxyzxyzxyz", "xyzyzyzyzyzyzyz"), 4, 'Test 35');
test(appendCharacters("abcdabcdabcd", "dcba"), 1, 'Test 36');
test(appendCharacters("abcabcabcabc", "abacaba"), 0, 'Test 37');
test(appendCharacters("thefastbrownfoxjumpsoverthelazydog", "quickbrownfox"), 13, 'Test 38');
test(appendCharacters("abcdefghijk", "acegik"), 0, 'Test 39');
test(appendCharacters("abcde", "cbad"), 3, 'Test 40');
test(appendCharacters("abracadabra", "bracadabr"), 0, 'Test 41');
test(appendCharacters("longstringwithvariouscharacters", "string"), 0, 'Test 42');
test(appendCharacters("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz", "zyxwvutsrqponmlkjihgfedcba"), 24, 'Test 43');
test(appendCharacters("sequence", "subsequence"), 9, 'Test 44');
test(appendCharacters("abcabcabcabc", "cccc"), 0, 'Test 45');
test(appendCharacters("longerstring", "string"), 0, 'Test 46');
test(appendCharacters("aaaabbbbcccc", "abcabc"), 3, 'Test 47');
test(appendCharacters("abcdef", "fghijk"), 5, 'Test 48');
test(appendCharacters("abcdef", "defghijk"), 5, 'Test 49');
test(appendCharacters("abcdexyz", "dezy"), 1, 'Test 50');
test(appendCharacters("xyzxyzxyz", "zyxzyxzyx"), 5, 'Test 51');
test(appendCharacters("abababababababab", "abab"), 0, 'Test 52');
test(appendCharacters("kglvkyeavnnrdq", "lky"), 0, 'Test 53');
test(appendCharacters("abcabcabcabc", "abcdabcdabcd"), 9, 'Test 54');
test(appendCharacters("abcdefghij", "hijjiklmn"), 6, 'Test 55');
test(appendCharacters("overlaplaplap", "laplaplaplap"), 3, 'Test 56');
test(appendCharacters("xyxyxyxyxy", "xyyx"), 0, 'Test 57');
test(appendCharacters("hello", "heoo"), 1, 'Test 58');
test(appendCharacters("abcde", "edcba"), 4, 'Test 59');
test(appendCharacters("randomstring", "stringrandom"), 6, 'Test 60');
test(appendCharacters("", "a"), 1, 'Test 61');
test(appendCharacters("mississippi", "pis"), 1, 'Test 62');
test(appendCharacters("abcdabcdabcd", "abcabcabc"), 0, 'Test 63');
test(appendCharacters("sequencealignment", "seqaln"), 0, 'Test 64');
test(appendCharacters("testtesttest", "testset"), 0, 'Test 65');
test(appendCharacters("mississippi", "pippi"), 3, 'Test 66');
test(appendCharacters("mississippi", "issip"), 0, 'Test 67');
test(appendCharacters("sequencealignment", "quencal"), 0, 'Test 68');
test(appendCharacters("", ""), 0, 'Test 69');
test(appendCharacters("abcdefghij", "jihgfedcba"), 9, 'Test 70');
test(appendCharacters("programming", "gram"), 0, 'Test 71');
test(appendCharacters("abcdef", "fedcba"), 5, 'Test 72');
test(appendCharacters("abcdefghijklmnopqrstuvwxyz", "xyzuvw"), 3, 'Test 73');
test(appendCharacters("abacabadabacaba", "abcd"), 0, 'Test 74');
test(appendCharacters("mississippi", "issi"), 0, 'Test 75');
test(appendCharacters("aaaaabbbbbcccccdddddeeeee", "abcde"), 0, 'Test 76');
test(appendCharacters("longstringwithrandomcharacters", "lgrmc"), 0, 'Test 77');
test(appendCharacters("zzzzzzzzzz", "abcdefghij"), 10, 'Test 78');
test(appendCharacters("patternmatching", "ternat"), 0, 'Test 79');
test(appendCharacters("aabbaabbccddeeff", "abcdeff"), 0, 'Test 80');
test(appendCharacters("abcde", "abcdeabcde"), 5, 'Test 81');
test(appendCharacters("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "abcdefghijklmnopqrstuvwxyz"), 0, 'Test 82');
test(appendCharacters("uniquecharacters", "charactersunique"), 6, 'Test 83');
test(appendCharacters("programming", "progmin"), 0, 'Test 84');
test(appendCharacters("subsequence", "subs"), 0, 'Test 85');
test(appendCharacters("hellothere", "othertimes"), 5, 'Test 86');
test(appendCharacters("aaaaaa", "aabbcc"), 4, 'Test 87');
test(appendCharacters("abcde", "efghij"), 5, 'Test 88');
test(appendCharacters("mississippi", "isip"), 0, 'Test 89');
test(appendCharacters("abcdefabcdef", "fedcbafedcba"), 10, 'Test 90');
test(appendCharacters("longerstringwithcharacters", "stringcharacters"), 0, 'Test 91');
test(appendCharacters("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "zyxwvutsrqponmlkjihgfedcba"), 25, 'Test 92');
test(appendCharacters("short", "longerstring"), 12, 'Test 93');
test(appendCharacters("abcabcabcabcabc", "abcabcabc"), 0, 'Test 94');
test(appendCharacters("abababababababab", "zzzzyyyyxxxxwwwwvvvvuuuuttttrrrrqqqqpppplllloooonnnnmmmkkkkjjjjiiiihhhhhggggggfffffeeeeeddddccccbbbbbaaaa"), 105, 'Test 95');
test(appendCharacters("overlappingcharacters", "lap"), 0, 'Test 96');
test(appendCharacters("sequence", "quen"), 0, 'Test 97');
test(appendCharacters("abcdefghij", "zzzzzzzzzz"), 10, 'Test 98');
test(appendCharacters("aaaaabbbbb", "abababab"), 6, 'Test 99');
test(appendCharacters("abcdefgh", "ihgfedcba"), 9, 'Test 100');
test(appendCharacters("thisisaverylongstring", "isaverylong"), 0, 'Test 101');
test(appendCharacters("programming", "gramming"), 0, 'Test 102');
test(appendCharacters("longeststring", "tiny"), 1, 'Test 103');
test(appendCharacters("xyz", "zyxzyxzyx"), 8, 'Test 104');
test(appendCharacters("abcdeabcdeabcde", "abcdee"), 0, 'Test 105');
test(appendCharacters("abracadabra", "acadabra"), 0, 'Test 106');
test(appendCharacters("mississippi", "ppip"), 1, 'Test 107');
test(appendCharacters("onetwothreefourfive", "owhfv"), 0, 'Test 108');
test(appendCharacters("aaaaaa", "bbbbb"), 5, 'Test 109');
test(appendCharacters("aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz", "zzzyyxwwvvuutsrrqppoonnmlkkjjiihhggffeeddccbbaa"), 45, 'Test 110');
test(appendCharacters("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaab"), 1, 'Test 111');
test(appendCharacters("abcdefghij", "hijjiklm"), 5, 'Test 112');
test(appendCharacters("example", "ample"), 0, 'Test 113');
test(appendCharacters("hello", "lelo"), 3, 'Test 114');
test(appendCharacters("abcabcabcabc", "abcabcabcabcabcabc"), 6, 'Test 115');
test(appendCharacters("characters", "char"), 0, 'Test 116');
test(appendCharacters("aaaabbbbcccc", "abc"), 0, 'Test 117');
test(appendCharacters("aaaaaaaaaa", "aaaabbbbcccc"), 8, 'Test 118');
test(appendCharacters("xyzuvw", "abcdefghijklmnopqrstuvwxyz"), 26, 'Test 119');
test(appendCharacters("xyz", "wxyzyxwxyzyx"), 12, 'Test 120');
test(appendCharacters("abcabcabcabcabc", "abcbcabcbcabcbca"), 3, 'Test 121');
test(appendCharacters("randomstring", "random"), 0, 'Test 122');
test(appendCharacters("abcdefghiklmnopqrstuvwxyz", "mnopqrstuvwxyz"), 0, 'Test 123');
test(appendCharacters("aabacadaea", "abcde"), 0, 'Test 124');
test(appendCharacters("aaaaaa", "aaaaaab"), 1, 'Test 125');
test(appendCharacters("sequence", "seq"), 0, 'Test 126');
test(appendCharacters("repeatedcharactersrepeatedcharacters", "characterscharacterscharacters"), 10, 'Test 127');
test(appendCharacters("abcdefghij", "hijjijk"), 4, 'Test 128');
test(appendCharacters("abacabadabacaba", "abcabcabc"), 1, 'Test 129');
test(appendCharacters("xyzabc", "uvwabc"), 6, 'Test 130');
test(appendCharacters("alibabacloud", "aliloud"), 0, 'Test 131');
test(appendCharacters("aaaabbbbcccc", "bbcccaaa"), 3, 'Test 132');
test(appendCharacters("aaaaabbbbbcccc", "abcabc"), 3, 'Test 133');
test(appendCharacters("hello", "olelh"), 4, 'Test 134');
test(appendCharacters("abcdefg", "agh"), 1, 'Test 135');
test(appendCharacters("abcdefghijkllkjihgfedcba", "abcdefghijkllkjihgfedcba"), 0, 'Test 136');
test(appendCharacters("overlappingoverlapping", "lapover"), 0, 'Test 137');
test(appendCharacters("a", ""), 0, 'Test 138');
test(appendCharacters("abcabcabcabcabc", "aabbaabbaabbaabb"), 9, 'Test 139');
test(appendCharacters("abcdefghijklmnopqrstuvwxyz", "zyxwvutsrqponmlkjihgfedcba"), 25, 'Test 140');
test(appendCharacters("xyzzyxzyxzyz", "xyzxyz"), 0, 'Test 141');
test(appendCharacters("hellotherehellothere", "helloothere"), 0, 'Test 142');
test(appendCharacters("abcdefghij", "hijjikl"), 4, 'Test 143');
test(appendCharacters("abacabadabacaba", "badaba"), 0, 'Test 144');
test(appendCharacters("aaabbbcccdddeeefffggghhhiiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxxyyyzzz", "zzzyyxxwwvvuuuttrrssqqppoonnmmlkkjjiihhgggfffeeeddccbbaaa"), 54, 'Test 145');
test(appendCharacters("abcdefghijklmnopqrstuvwxyz", "zyxwvut"), 6, 'Test 146');
test(appendCharacters("abcdefghij", "hijjik"), 3, 'Test 147');
test(appendCharacters("aabbccddeeffgg", "abcdefg"), 0, 'Test 148');
test(appendCharacters("qwertyuiopasdfghjklzxcvbnm", "qwertyuiopasdfghjklzxcvbnmqwertyuiop"), 10, 'Test 149');
test(appendCharacters("abcdefghij", "acegik"), 1, 'Test 150');
test(appendCharacters("racecar", "racecar"), 0, 'Test 151');
test(appendCharacters("abracadabra", "abcde"), 1, 'Test 152');
test(appendCharacters("abcdefghij", "abcdefghij"), 0, 'Test 153');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

