// Test: 1958. Check If Move Is Legal
// 74 test cases from LeetCodeDataset
// Run: node test.js

const { checkMove } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1958. Check If Move Is Legal\n");

test(checkMove([['.','W','.','.','.','.','.','.'],['.','.','W','.','.','.','.','.'],['W','.','.','W','.','.','.','.'],['.','.','W','.','.','.','.','.'],['.','W','W','W','.','.','.','.'],['.','.','W','.','.','.','.','.'],['.','.','W','.','.','.','.','.'],['.','W','.','.','.','.','.','.']], 3, 3, 'W'), false, 'Test 1');
test(checkMove([['.','W','.','.','.','.','.','.'],['.','W','.','.','.','.','.','.'],['W','.','.','W','.','.','.','.'],['.','W','W','W','.','.','.','.'],['.','W','W','W','.','.','.','.'],['.','W','W','W','.','.','.','.'],['.','W','.','.','.','.','.','.'],['W','.','.','.','.','.','.','.']], 4, 3, 'B'), false, 'Test 2');
test(checkMove({"board": [[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W",".",".",".","."],["W","B","B",".","W","W","W","B"],[".",".",".","B",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."]], "rMove": 4, "cMove": 3, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 3');
test(checkMove([['.','.','.','.','.','.','.','.'],['.','B','.','.','W','.','.','.'],['.','.','W','.','.','.','.','.'],['.','.','.','W','B','.','.','.'],['.','.','.','.','.','.','.','.'],['.','.','.','.','B','W','.','.'],['.','.','.','.','.','.','W','.'],['.','.','.','.','.','.','.','B']], 4, 4, 'W'), false, 'Test 4');
test(checkMove([['.','.','.','.','.','.','.','.'],['.','.','.','W','.','.','.','.'],['.','W','.','W','.','.','.','.'],['W','.','W','.','W','.','.','.'],['.','W','.','W','.','.','.','.'],['.','.','W','.','W','.','.','.'],['.','.','.','W','.','.','.','.'],['.','.','.','W','.','.','.','.']], 2, 2, 'B'), false, 'Test 5');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".","B",".",".","W",".",".","."],[".",".","W",".",".",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".","B","W",".","."],[".",".",".",".",".",".","W","."],[".",".",".",".",".",".",".","B"]], "rMove": 4, "cMove": 4, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 6');
test(checkMove([['.','.','.','B','.','.','.','.'],['.','.','.','W','.','.','.','.'],['.','.','.','W','.','.','.','.'],['.','.','.','W','.','.','.','.'],['W','B','B','.','W','W','W','B'],['.','.','.','B','.','.','.','.'],['.','.','.','B','.','.','.','.'],['.','.','.','W','.','.','.','.']], 4, 3, 'B'), true, 'Test 7');
test(checkMove([['.','B','.','.','.','.','.','.'],['B','B','.','.','.','.','.','.'],['.','B','.','.','.','.','.','.'],['.','B','.','.','.','.','.','.'],['.','B','.','.','.','.','.','.'],['.','B','.','.','.','.','.','.'],['.','B','.','.','.','.','.','.'],['.','B','.','.','.','.','.','.']], 4, 1, 'W'), false, 'Test 8');
test(checkMove([['.','.','.','.','.','.','.','.'],['.','.','.','.','.','.','.','.'],['.','.','.','.','.','.','.','.'],['.','.','.','W','B','.','.','.'],['.','.','.','B','W','.','.','.'],['.','.','.','B','B','.','.','.'],['.','.','.','B','W','.','.','.'],['.','.','.','W','B','.','.','.']], 3, 3, 'W'), true, 'Test 9');
test(checkMove([['.','W','.','.','.','.','.','.'],['.','W','.','.','.','.','.','.'],['W','.','.','W','.','.','.','.'],['.','W','W','W','.','.','.','.'],['.','W','W','B','.','.','.','.'],['.','W','W','W','.','.','.','.'],['.','W','.','.','.','.','.','.'],['W','.','.','.','.','.','.','.']], 4, 3, 'W'), false, 'Test 10');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","B","W","B",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 4, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 11');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","B","B",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B",".",".","."]], "rMove": 2, "cMove": 2, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 12');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".","W","W","B","B","W",".","."],[".","W","W","B","B","W",".","."],[".","W","W","B","B","W",".","."],[".","W","W","B","B","W",".","."],[".","W","W","B","B","W",".","."]], "rMove": 3, "cMove": 2, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 13');
test(checkMove({"board": [[".",".",".","B","W","W",".","."],[".",".",".","W","W","B",".","."],[".",".",".","W","W","W",".","."],[".",".",".","W","B",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","W",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 0, "cMove": 4, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 14');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".","W","B","W",".",".","."],[".",".","W","B","W",".",".","."],[".",".","W","B","W",".",".","."],[".",".","W","B","W",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 2, "cMove": 3, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 15');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".","W","W",".",".",".",".","."],[".","W","B",".",".",".",".","."],[".","W","B","B",".",".",".","."],[".","W","B","W","B",".",".","."],[".","W","B","B","W",".",".","."],[".","W","B","B","W","W",".","."],[".",".",".",".",".",".",".","."]], "rMove": 5, "cMove": 5, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 16');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".","W","B","W","B","W","B","."],[".","B","W","B","W","B","W","."],[".","W","B","W","B","W","B","."],[".","B","W","B","W","B","W","."],[".","W","B","W","B","W","B","."],[".","B","W","B","W","B","W","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 17');
test(checkMove({"board": [["W","B","W","B","W","B","W","B"],["B","W","B","W","B","W","B","W"],["W","B","W","B","W","B","W","B"],["B","W","B","W","B","W","B","W"],["W","B","W","B","W","B","W","B"],["B","W","B","W","B","W","B","W"],["W","B","W","B","W","B","W","B"],["B","W","B","W","B","W","B","W"]], "rMove": 3, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 18');
test(checkMove({"board": [[".",".",".","W",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","W","W","W",".","."],[".",".","W","B","W",".",".","."],[".",".","W","W","W",".",".","."],[".",".","W","W",".",".",".","."]], "rMove": 5, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 19');
test(checkMove({"board": [[".",".",".","B",".",".",".","."],[".",".",".",".","B",".",".","."],[".",".",".","W",".","B",".","."],[".",".","W","B","W","B",".","."],["W","B","B","W","B","W","B","B"],[".",".","W","B","W","B",".","."],[".",".",".","W",".","B",".","."],[".",".",".",".","B",".",".","."]], "rMove": 3, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 20');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".","W","W","B",".",".","."],[".",".","W","B","W",".",".","."],[".",".","W","W","B",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 2, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 21');
test(checkMove({"board": [[".",".",".","W",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","W","W","W",".","."],[".",".","W","B","W","W","B","."],[".",".","W","W","W","B","W","."],[".",".","W","W",".","B","W","B"]], "rMove": 3, "cMove": 1, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 22');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".","W","W","W",".",".","."],[".",".","W","B","W",".",".","."],[".",".","W","W","W",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 4, "cMove": 3, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 23');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 2, "cMove": 3, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 24');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".","W","B","W",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 4, "cMove": 4, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 25');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],["W","W","W","B","B","B","B","W"]], "rMove": 7, "cMove": 3, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 26');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","B","W","B",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 4, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 27');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","W","W",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","W","W",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 1, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 28');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 5, "cMove": 4, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 29');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".","W",".",".","."],[".",".",".",".",".","B",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 4, "cMove": 4, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 30');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","B","W",".",".","."],[".",".","W","W","W","W","W","."],[".",".","B","W","B","W","B","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 3, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 31');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".","B","W",".",".","."],[".",".","W","W","W","W",".","."],[".",".","B","W","B","W",".","."],[".",".","W","W","W","W",".","."],[".",".","B","W","B","W",".","."],[".",".","W","W","W","W",".","."],[".",".","B","W","B","W",".","."]], "rMove": 3, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 32');
test(checkMove({"board": [[".",".","W","B",".",".",".","."],[".",".","W","W","B",".",".","."],[".","W","W","W","B",".",".","."],[".","B","B","B","W",".",".","."],[".","W","B","W","B",".",".","."],[".",".",".","B","B","W",".","."],[".",".",".","B","B","W","W","."],[".",".",".","W","B","B","W","."]], "rMove": 2, "cMove": 2, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 33');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 7, "cMove": 7, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 34');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","W","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".","W","B","W",".","."],[".",".",".","W","W","B",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 5, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 35');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".",".",".",".",".","."]], "rMove": 5, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 36');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 4, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 37');
test(checkMove({"board": [[".",".",".","W",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","W","W","W",".","."],[".",".",".","B",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."]], "rMove": 3, "cMove": 5, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 38');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".","B","B","B","B","B",".","."],[".","B","W","W","W","B",".","."],[".","B","W","W","W","B",".","."],[".","B","W","W","W","B",".","."],[".","B","B","B","B","B",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 39');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 2, "cMove": 2, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 40');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","W","W","B",".","."],[".",".",".","W","W","W","B","."],[".",".",".","B","W","W","W","."],[".",".",".","B","B","B","W","."],[".",".",".","W","B","B","W","."],[".",".",".","W","B","W","B","."]], "rMove": 6, "cMove": 6, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 41');
test(checkMove({"board": [[".",".",".","W",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","W","W","W",".","."],[".",".","W","B","W","W",".","."],[".",".","W","W","W","B",".","."],[".",".","W","W",".","B",".","."]], "rMove": 6, "cMove": 5, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 42');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 4, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 43');
test(checkMove({"board": [[".",".",".","W",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 0, "cMove": 3, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 44');
test(checkMove({"board": [["W",".",".","B",".",".",".","W"],[".","W",".",".","B",".","W","."],[".",".","W",".",".","W",".","."],[".",".",".","W","B",".",".","."],["W","B","B",".","W","W","W","B"],[".",".",".","B",".",".",".","."],[".",".",".","B",".",".",".","."],["W",".",".","W",".",".",".","W"]], "rMove": 2, "cMove": 2, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 45');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W",".",".",".","."],["W","B","B",".","W","W","W","B"],[".",".",".","B",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."]], "rMove": 4, "cMove": 3, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 46');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","W","W",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","W","W",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 1, "cMove": 4, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 47');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 5, "cMove": 4, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 48');
test(checkMove({"board": [[".",".","W","W","B",".",".","."],[".",".","W","B","W",".",".","."],[".",".","B","W","B",".",".","."],[".",".","B","W","B",".",".","."],[".",".","W","B","W",".",".","."],[".",".","B","W","B",".",".","."],[".",".","W","B","W",".",".","."],[".",".",".","W","B",".",".","."]], "rMove": 0, "cMove": 2, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 49');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".","W","B","W",".","."]], "rMove": 6, "cMove": 4, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 50');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".","W","W","W",".",".","."],[".",".","W","B","W",".",".","."],[".",".","W","W","W",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 2, "cMove": 2, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 51');
test(checkMove({"board": [[".",".",".","W",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","W","W","W",".","."],[".",".","W","B","W","W","B","."],[".",".","W","W","W","B","W","."],[".",".","W","W",".","B","W","B"]], "rMove": 5, "cMove": 6, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 52');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 4, "cMove": 5, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 53');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".","W","B","W",".",".","."],[".",".","B","W","B",".",".","."],[".",".","W","B","W",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 4, "cMove": 2, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 54');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","W","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".","W","B","W",".","."],[".",".",".","W","W","B",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 4, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 55');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".","B","W","B","W","B","W","."],[".","W","B","W","B","W","B","."],[".","B","W","B","W","B","W","."],[".","W","B","W","B","W","B","."],[".","B","W","B","W","B","W","."],[".","W","B","W","B","W","B","."],[".",".",".",".",".",".",".","."]], "rMove": 1, "cMove": 1, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 56');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".","W","B","W","B",".","."],[".",".","B","W","B","W",".","."],[".",".","W","B","W","B",".","."],[".",".","B","W","B","W",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 4, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 57');
test(checkMove({"board": [[".",".",".","W",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","W","W","W",".","."],[".",".",".","B",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."]], "rMove": 4, "cMove": 4, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 58');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".","B","W","B","W","B","W","."],[".","W","B","W","B","W","B","."],[".","B","W","B","W","B","W","."],[".","W","B","W","B","W","B","."],[".","B","W","B","W","B","W","."],[".","W","B","W","B","W","B","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 59');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 2, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 60');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 4, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 61');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 4, "cMove": 3, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 62');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","B",".",".","."],[".",".","W","B","W","B",".","."],[".",".","B","W","B","W",".","."],[".",".","W","B","W","B",".","."],[".",".",".","W","B",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 5, "cMove": 4, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 63');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".","B",".",".","W",".",".","."],[".",".","W",".",".",".",".","."],[".",".",".","W","B",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".","B","W",".","."],[".",".",".",".",".",".","W","."],[".",".",".",".",".",".",".","B"]], "rMove": 5, "cMove": 4, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 64');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".","W","B","W",".","."],[".",".",".","B","W","B",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 5, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 65');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","B",".",".","."],[".",".","W","B","W",".",".","."],[".","W","B","B","W",".",".","."],[".","W","B","B","B","W",".","."],[".","W","B","B","B","B","W","."],[".","W","B","B","B","B","B","W"]], "rMove": 5, "cMove": 5, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 66');
test(checkMove({"board": [["B","B","B","B","B","B","B","B"],["W","W","W","W","W","W","W","B"],["W","W","W","W","W","W","W","B"],["W","W","W","W","W","W","W","B"],["W","W","W","W","W","W","W","B"],["W","W","W","W","W","W","W","B"],["W","W","W","W","W","W","W","B"],["W","W","W","W","W","W","W","B"]], "rMove": 0, "cMove": 0, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 67');
test(checkMove({"board": [[".",".",".","B",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","W","W",".","."],[".",".",".","B","W",".",".","."],[".",".",".","W","W",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 4, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 68');
test(checkMove({"board": [[".",".",".","W",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","W","W","W",".","."],[".",".",".","B",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."]], "rMove": 4, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 69');
test(checkMove({"board": [[".",".",".","W",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","W",".",".",".","."],[".",".",".","W","B","W",".","."],[".",".",".","W","W","W",".","."],[".",".","W","B",".",".",".","."],[".",".","W","W",".",".",".","."],[".",".","W","W",".",".",".","."]], "rMove": 5, "cMove": 2, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 70');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 71');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".","W","W","W","W",".",".","."],[".","W","B","B","W",".",".","."],[".","W","B","B","W",".",".","."],[".","W","B","B","W",".",".","."],[".","W","W","W","W",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 3, "cMove": 2, "color": "B"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 72');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","W","B",".",".","."],[".",".","W","B","W","B",".","."],[".","W","B","W","B","W","B","."],[".",".","W","B","W","B",".","."],[".",".",".","W","B",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 4, "cMove": 3, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 73');
test(checkMove({"board": [[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]], "rMove": 0, "cMove": 0, "color": "W"}), Error: Solution.checkMove[] missing 4 required positional arguments: 'board', 'rMove', 'cMove', and 'color', 'Test 74');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

// Auto-mark DONE when all tests pass
if (!failed) {
  const path = require("path");
  const fs = require("fs");
  const dir = __dirname;
  const folder = path.basename(dir);
  if (!folder.startsWith("DONE-")) {
    const parent = path.dirname(dir);
    const newDir = path.join(parent, "DONE-" + folder);
    fs.renameSync(dir, newDir);
    const readme = path.join(newDir, "README.md");
    if (fs.existsSync(readme)) {
      let c = fs.readFileSync(readme, "utf-8");
      if (!c.includes("<!-- SOLVED -->")) {
        c = c.replace(/^(# .+)$/m, "$1 ✅\n<!-- SOLVED -->");
        fs.writeFileSync(readme, c);
      }
    }
    console.log("✅ DONE → " + "DONE-" + folder);
  }
}
