// Test: 3292. Minimum Number Of Valid Strings To Form Target Ii
// 169 test cases from LeetCodeDataset
// Run: node test.js

const { minValidStrings } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n3292. Minimum Number Of Valid Strings To Form Target Ii\n");

test(minValidStrings(["abc"], "abcabc"), 2, 'Test 1');
test(minValidStrings(["a"], "a"), 1, 'Test 2');
test(minValidStrings(["a","aa","aaa"], "aaaaaaaa"), 3, 'Test 3');
test(minValidStrings(["xyz"], "xyz"), 1, 'Test 4');
test(minValidStrings(["a","aa","aaa"], "aaaaaaaaa"), 3, 'Test 5');
test(minValidStrings(["a"], "aaaaaaaaaa"), 10, 'Test 6');
test(minValidStrings(["abababab","ab"], "ababaababa"), 2, 'Test 7');
test(minValidStrings(["abcde"], "abcde"), 1, 'Test 8');
test(minValidStrings(["abc","aaaaa","bcdef"], "aabcdabc"), 3, 'Test 9');
test(minValidStrings(["hello","world"], "hello"), 1, 'Test 10');
test(minValidStrings(["abcd", "efgh", "ijkl"], "abcdefghij"), 3, 'Test 11');
test(minValidStrings(["abcdef"], "xyz"), -1, 'Test 12');
test(minValidStrings(["abc","abc","abc"], "abcabc"), 2, 'Test 13');
test(minValidStrings(["z", "y", "x"], "zyxzyxzyx"), 9, 'Test 14');
test(minValidStrings(["abcdef", "ghijkl"], "abcdefghijkl"), 2, 'Test 15');
test(minValidStrings(["abc", "def", "ghi"], "abcdefghi"), 3, 'Test 16');
test(minValidStrings(["hello","world"], "helloworld"), 2, 'Test 17');
test(minValidStrings(["abc","def","ghi"], "abcdef"), 2, 'Test 18');
test(minValidStrings(["a","b","c"], "abc"), 3, 'Test 19');
test(minValidStrings(["abc","def","ghi","jkl"], "abcdefghijklop"), -1, 'Test 20');
test(minValidStrings(["z"], "zzzzz"), 5, 'Test 21');
test(minValidStrings(["abcd","efgh","ijkl"], "abcdefghijklijkl"), 4, 'Test 22');
test(minValidStrings(["hello","helloo","hellooo","helloooo"], "helloooohelloooohelloooohelloooo"), 4, 'Test 23');
test(minValidStrings(["mnop","mnopqr","mnopqrst","mnopqrstu","mnopqrstuv"], "mnopqrstuvmnopqrstuvmnopqrstuvmnopqrstu"), 4, 'Test 24');
test(minValidStrings(["z", "zz", "zzz", "zzzz", "zzzzz"], "zzzzzzzzzzzzzz"), 3, 'Test 25');
test(minValidStrings(["zzzzz","zzzz","zzz","zz","z"], "zzzzzzzzzzzzzzzzzzzzzz"), 5, 'Test 26');
test(minValidStrings(["hello","world","hel","wor"], "helloworldhelloworld"), 4, 'Test 27');
test(minValidStrings(["abcd", "bcde", "cdef", "defg"], "abcdefghijklmnop"), -1, 'Test 28');
test(minValidStrings(["abcdef","bcdef","cdef","def","ef","f"], "abcdefbcdefcdef"), 3, 'Test 29');
test(minValidStrings(["xyz", "xy", "x"], "xyzxyxyxzyzyx"), -1, 'Test 30');
test(minValidStrings(["start", "startstart", "startstartstart"], "startstartstart"), 1, 'Test 31');
test(minValidStrings(["example", "sample", "exam", "ple", "samplesample"], "examplesamplesampleple"), 3, 'Test 32');
test(minValidStrings(["z", "zy", "zyx", "zyxw"], "zyxwzyxwzyxwzyxw"), 4, 'Test 33');
test(minValidStrings(["abcdef","fedcba","abc","cba","def","efd"], "abcdefcbaefdefabc"), 5, 'Test 34');
test(minValidStrings(["abcd", "efgh", "ijkl"], "abcdefghijklijk"), 4, 'Test 35');
test(minValidStrings(["aabbcc","bbaacc","ccaabb","aabbbccc","abbcccaab"], "aabbccbbcccaababbcccaab"), 5, 'Test 36');
test(minValidStrings(["xy","xyz","xyza","xyzab","xyzabc"], "xyzabcxyzabcxyzabcxyzabcxyzabc"), 5, 'Test 37');
test(minValidStrings(["a","aa","aaa","aaaa","aaaaa"], "aaaaaaaaaaaaaaaaaa"), 4, 'Test 38');
test(minValidStrings(["mnopqr","nopqr","opqr","pqr","qr","r"], "mnopqrnopqr"), 2, 'Test 39');
test(minValidStrings(["ab","bc","cd","de","ef"], "abcdefabcdefabcdef"), 9, 'Test 40');
test(minValidStrings(["quick", "brown", "fox", "jumps"], "quickbrownfoxjumpsquick"), 5, 'Test 41');
test(minValidStrings(["a", "aa", "aaa", "aaaa"], "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), 8, 'Test 42');
test(minValidStrings(["x", "xy", "xyz", "xyza"], "xyza"), 1, 'Test 43');
test(minValidStrings(["abcd","abcde","abcdef"], "abcdefabcdefabcdef"), 3, 'Test 44');
test(minValidStrings(["quick", "brown", "fox", "jumps", "over"], "quickbrownfoxjumpsoverquick"), 6, 'Test 45');
test(minValidStrings(["xyz","xyzz","zzzz","zzzzy","zzzzz"], "xyzzzzzzzzzzzzzy"), 4, 'Test 46');
test(minValidStrings(["prefix", "pre", "fix", "suffix"], "prefixsuffix"), 2, 'Test 47');
test(minValidStrings(["abc","abcabc","abcabcabc"], "abcabcabcabcabcabc"), 2, 'Test 48');
test(minValidStrings(["x","xy","xyz","xyza","xyzab"], "xyzabxyzabxyzab"), 3, 'Test 49');
test(minValidStrings(["pqr","pqrs","pqrs","pqrstu","pqrstuv"], "pqrstuvpqrstuvpqrstuvpqrstuvpqrstu"), 5, 'Test 50');
test(minValidStrings(["one","two","three","four","five"], "onetwothreefourfivetwothreefourfivefourfive"), 11, 'Test 51');
test(minValidStrings(["a", "b", "c", "d", "e"], "abcdeabcdeabcdeabcdeabcde"), 25, 'Test 52');
test(minValidStrings(["abcd", "ab", "a"], "abcdabcdabcdabcd"), 4, 'Test 53');
test(minValidStrings(["abcdefg", "hijklmn", "opqrstu", "vwxyz"], "abcdefghijklmnopqrstuvwxyzzzz"), -1, 'Test 54');
test(minValidStrings(["unique", "words", "only"], "uniquewordsonly"), 3, 'Test 55');
test(minValidStrings(["abcdefg", "abcdefgh", "abcdefghi"], "abcdefghiabcdefghiabcdefghi"), 3, 'Test 56');
test(minValidStrings(["abc", "bcd", "cde", "def"], "abcdefabcdef"), 4, 'Test 57');
test(minValidStrings(["a", "b", "c", "d", "e", "f", "g"], "abcdefg"), 7, 'Test 58');
test(minValidStrings(["abc","def","ghi","jkl","mno","pqr","stu","vwx","yz"], "mnopqrstuvwx"), 4, 'Test 59');
test(minValidStrings(["abc","def","ghi","jkl","mno","pqr"], "abcdefghijklmnopqr"), 6, 'Test 60');
test(minValidStrings(["overlap","lap","laplap","aplap"], "overlaplaplaplaplap"), 3, 'Test 61');
test(minValidStrings(["abcdef","bcdefg","cdefgh","defghi","efghij","fghijk"], "abcdefbcdefgcdefghdefghiefghijfghijk"), 6, 'Test 62');
test(minValidStrings(["prefix","suffix","pre","suf"], "prefixsuffixprefixsuffix"), 4, 'Test 63');
test(minValidStrings(["a", "b", "c", "d", "e", "f"], "fedcbafedcba"), 12, 'Test 64');
test(minValidStrings(["abc", "def", "ghi", "jkl"], "abcdefghijkla"), 5, 'Test 65');
test(minValidStrings(["xyz","xy","x"], "xyzyxzyx"), -1, 'Test 66');
test(minValidStrings(["one","two","three","four","five"], "onetwothreefourfive"), 5, 'Test 67');
test(minValidStrings(["one","onetwo","onetwothree"], "onetwothreeonetwothreeonetwothree"), 3, 'Test 68');
test(minValidStrings(["a","b","c","d","e","f","g","h","i","j"], "abcdefghijabcdefghijabcdefghij"), 30, 'Test 69');
test(minValidStrings(["abababab","bababa","ab","ba","a","b"], "ababababababababab"), 3, 'Test 70');
test(minValidStrings(["a","aa","aaa","aaaa","aaaaa","aaaaaa","aaaaaaa","aaaaaaaa","aaaaaaaaa","aaaaaaaaaa"], "aaaaaaaaaaaaaaaaaaa"), 2, 'Test 71');
test(minValidStrings(["aaaa", "aaaaa", "aaaaaa"], "aaaaaaaaaaaaaaaa"), 3, 'Test 72');
test(minValidStrings(["hello","hell","he","h"], "hellohello"), 2, 'Test 73');
test(minValidStrings(["a", "aa", "aaa", "aaaa"], "aaaaaaaaaa"), 3, 'Test 74');
test(minValidStrings(["z","zz","zzz","zzzz"], "zzzzzzzzzzzzzzzzzzzz"), 5, 'Test 75');
test(minValidStrings(["overlap", "over", "lap", "laplap"], "overlaplaplap"), 2, 'Test 76');
test(minValidStrings(["abc","bcd","cde"], "abcbcdcdedef"), -1, 'Test 77');
test(minValidStrings(["abcdefg","abcdefgh","abcdefghi"], "abcdefghiabcdefghiabcdefghi"), 3, 'Test 78');
test(minValidStrings(["aabbcc", "bbccdd", "ccddeeff"], "aabbccddeeff"), 2, 'Test 79');
test(minValidStrings(["hello", "world", "hi"], "helloworld"), 2, 'Test 80');
test(minValidStrings(["short", "longstringthatgoesonand", "onand", "and"], "longstringthatgoesonandonandonand"), 3, 'Test 81');
test(minValidStrings(["xyz", "xy", "x"], "xyzxyzz"), -1, 'Test 82');
test(minValidStrings(["aaa","aab","aac","aba","abb","abc"], "aabacbaabbac"), -1, 'Test 83');
test(minValidStrings(["aabbcc", "bbccdd", "ccddeeff"], "aabbccbbccddeeffccddeeff"), 4, 'Test 84');
test(minValidStrings(["a", "aa", "aaa", "aaaa"], "aaaaaaaaaaaaaaaaaaaaaaaaa"), 7, 'Test 85');
test(minValidStrings(["x","y","z"], "xyzxyzxyzxyzxyz"), 15, 'Test 86');
test(minValidStrings(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"], "abcdefghijklmnopqrstuvwxyz"), 26, 'Test 87');
test(minValidStrings(["word", "wordword", "wordwordword"], "wordwordwordwordwordwordwordwordwordword"), 4, 'Test 88');
test(minValidStrings(["aabb","bbaa","abab"], "aabbaabbaabbabab"), 4, 'Test 89');
test(minValidStrings(["longwordprefix","prefix","word","prefixword"], "longwordprefixprefixwordprefixwordprefix"), 4, 'Test 90');
test(minValidStrings(["a", "b", "c", "d", "e"], "abcdeabcdeabcde"), 15, 'Test 91');
test(minValidStrings(["pqrst","pqrstu","pqrstuv"], "pqrstpqrstu"), 2, 'Test 92');
test(minValidStrings(["ab", "bc", "cd"], "abcdabcdabcd"), 6, 'Test 93');
test(minValidStrings(["abc", "bcd", "cde", "def", "efg"], "abcdefg"), 3, 'Test 94');
test(minValidStrings(["aaa","aa","a"], "aaaaaaaaaaaaaaaaaaaa"), 7, 'Test 95');
test(minValidStrings(["abc","ab","a"], "ababababab"), 5, 'Test 96');
test(minValidStrings(["abc","def","ghi","jkl","mno"], "abcdefghijklmno"), 5, 'Test 97');
test(minValidStrings(["aaa", "aa", "a"], "aaaaaaaaa"), 3, 'Test 98');
test(minValidStrings(["abcd", "abcde", "abcdef"], "abcdefabcdef"), 2, 'Test 99');
test(minValidStrings(["abc", "abcd", "abcde"], "abcdeabcdabc"), 3, 'Test 100');
test(minValidStrings(["abcabcabcabcabcabcabcabcabcabc"], "abcabcabcabcabcabcabcabcabcabc"), 1, 'Test 101');
test(minValidStrings(["aaa", "bbb", "ccc"], "aaabbbccc"), 3, 'Test 102');
test(minValidStrings(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"], "abcdefghijabcdefghij"), 20, 'Test 103');
test(minValidStrings(["complex", "complexity", "complexities", "complexitytest"], "complexcomplexitycomplexitiescomplexitytest"), 4, 'Test 104');
test(minValidStrings(["abcd","dcba","ab","ba","abc","cba","abcdcba","bacd"], "abcdabcbaabcd"), 4, 'Test 105');
test(minValidStrings(["abc", "bcd", "cde"], "abcdexyz"), -1, 'Test 106');
test(minValidStrings(["overlap", "laplap", "lap"], "overlapproverlap"), -1, 'Test 107');
test(minValidStrings(["one", "two", "three"], "onetwothreeonetwothreeone"), 7, 'Test 108');
test(minValidStrings(["abcd","ab","c","d"], "ababcdabcd"), 3, 'Test 109');
test(minValidStrings(["abc", "abc", "abc"], "abcabcabc"), 3, 'Test 110');
test(minValidStrings(["abc","abcabcabc","bcdef","ghijkl"], "abcabcabcghijkl"), 2, 'Test 111');
test(minValidStrings(["a", "aa", "aaa", "aaaa"], "aaaaaaaaaaaa"), 3, 'Test 112');
test(minValidStrings(["ab","abc","abcd","abcde"], "abcdeabcdeabcde"), 3, 'Test 113');
test(minValidStrings(["abcdef","abcde","abcd","abc","ab","a"], "abcdef"), 1, 'Test 114');
test(minValidStrings(["aaa", "aaaa", "aaaaa"], "aaaaaaaaaaaa"), 3, 'Test 115');
test(minValidStrings(["quick","brown","fox","jumps","over","lazy","dog"], "quickbrownfoxjumpsoverlazydog"), 7, 'Test 116');
test(minValidStrings(["xyz","xy","x"], "xyzyzyzyzy"), -1, 'Test 117');
test(minValidStrings(["abc","bcd","cde","def"], "abcdeabcdef"), 4, 'Test 118');
test(minValidStrings(["abcd","abcde","abcdef","abcdefg"], "abcdefgabcdefg"), 2, 'Test 119');
test(minValidStrings(["abc", "abcd", "abcde"], "abcdeabcde"), 2, 'Test 120');
test(minValidStrings(["ab", "cde", "fgh"], "abcdefg"), 3, 'Test 121');
test(minValidStrings(["abc","acb","bac","bca","cab","cba"], "abcacbac"), 3, 'Test 122');
test(minValidStrings(["abc","ab","a"], "abaababababababab"), 9, 'Test 123');
test(minValidStrings(["test", "testing", "testcase", "case"], "testtestingtestcasetestcase"), 4, 'Test 124');
test(minValidStrings(["one", "two", "three"], "onetwothreeonetwothree"), 6, 'Test 125');
test(minValidStrings(["z","zz","zzz","zzzz"], "zzzzzzzzzzzzzzzzzz"), 5, 'Test 126');
test(minValidStrings(["a", "ab", "abc", "abcd", "abcde"], "abcdeabcdeabcde"), 3, 'Test 127');
test(minValidStrings(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"], "zzzzzzzzzz"), 10, 'Test 128');
test(minValidStrings(["a","aa","aaa","aaaa"], "aaaaaaaaaa"), 3, 'Test 129');
test(minValidStrings(["aaaa","bbbb","cccc","dddd","eeee"], "abcdedcba"), 9, 'Test 130');
test(minValidStrings(["longprefix","short","prefix","longerprefix","evenlongerprefix"], "longprefixlongerprefixevenlongerprefix"), 3, 'Test 131');
test(minValidStrings(["prefix", "suffix", "Infinityix", "prefixsuffix", "suffixprefix"], "prefixsuffixsuffixprefixprefix"), 3, 'Test 132');
test(minValidStrings(["abcd","bcd","cd","d"], "abcdabcdabcdabcd"), 4, 'Test 133');
test(minValidStrings(["abc","def","ghi","jkl","mno","pqr","stu","vwx","yz","abcdefghijklmnopqrstuvwxyz"], "abcdefghijklmnopqrstuvwxyz"), 1, 'Test 134');
test(minValidStrings(["same", "same", "same"], "samethatsame"), -1, 'Test 135');
test(minValidStrings(["small", "smal", "sma", "sm"], "smallsmallsmallsmall"), 4, 'Test 136');
test(minValidStrings(["abc","abcd","abcde","abcdef"], "abcdefabcdefabcdef"), 3, 'Test 137');
test(minValidStrings(["xyz","abc","def"], "xyzabcxyzdef"), 4, 'Test 138');
test(minValidStrings(["a","aa","aaa","aaaa"], "aaaaaaaa"), 2, 'Test 139');
test(minValidStrings(["a", "ab", "abc", "abcd"], "abcdabcd"), 2, 'Test 140');
test(minValidStrings(["hello", "world", "helloworld"], "helloworldhelloworld"), 2, 'Test 141');
test(minValidStrings(["aabb","bbcc","ccdd","aabbcc","bbccdd"], "aabbccdd"), 2, 'Test 142');
test(minValidStrings(["xy","yz","xyz","zxy","zyx"], "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz"), 11, 'Test 143');
test(minValidStrings(["abc","abcd","abcde","abcdef"], "abcdefabcdef"), 2, 'Test 144');
test(minValidStrings(["aaa", "aa", "a"], "aaaaaaaaaa"), 4, 'Test 145');
test(minValidStrings(["abcd", "bcde", "cdef", "defg"], "abcdabcdabcdabcd"), 4, 'Test 146');
test(minValidStrings(["abc", "abcabc", "abcabcabc"], "abcabcabcabcabc"), 2, 'Test 147');
test(minValidStrings(["one", "two", "three", "four", "five"], "onetwothreefourfiveonetwothreefourfive"), 10, 'Test 148');
test(minValidStrings(["longword", "longwo", "longw", "long"], "longwordlongwordlongword"), 3, 'Test 149');
test(minValidStrings(["a","b","c","d","e","f","g","h","i","j"], "abcdefghij"), 10, 'Test 150');
test(minValidStrings(["longword", "another", "short"], "longwordanotherlongword"), 3, 'Test 151');
test(minValidStrings(["a", "b", "c", "d", "e"], "abcde"), 5, 'Test 152');
test(minValidStrings(["abcdef","ghijkl","mnopqr","stuvwx","yz","abc","def","ghi","jkl","mno","pqr","stu","vwx","yz"], "abcdefghijklmnopqrstuvwxyzyzyz"), 7, 'Test 153');
test(minValidStrings(["abcdef", "defghi", "ghijkl"], "abcdefghijkl"), 2, 'Test 154');
test(minValidStrings(["xyz", "yz", "z"], "xyzxyzxyzxyz"), 4, 'Test 155');
test(minValidStrings(["prefix", "suffix"], "prefixprefixsuffix"), 3, 'Test 156');
test(minValidStrings(["hello","world","hell","worl"], "helloworld"), 2, 'Test 157');
test(minValidStrings(["xyz", "xy", "x"], "xyzyxyzyx"), -1, 'Test 158');
test(minValidStrings(["prefix", "pre", "fix", "word"], "prefixprefixfix"), 3, 'Test 159');
test(minValidStrings(["abcdef", "defgh", "efghi"], "abcdefghigfedcba"), -1, 'Test 160');
test(minValidStrings(["abcde","bcde","cde","de","e"], "abcdebcdecde"), 3, 'Test 161');
test(minValidStrings(["short","shor","sh","s"], "shortshortshortshortshort"), 5, 'Test 162');
test(minValidStrings(["prefix","pre","fix","fi","ix"], "prefixprefix"), 2, 'Test 163');
test(minValidStrings(["a","aa","aaa","aaaa","aaaaa"], "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), 8, 'Test 164');
test(minValidStrings(["abc","abcd","abce"], "abcdeabcde"), -1, 'Test 165');
test(minValidStrings(["abcabc", "abc", "ab"], "abcabcabcabc"), 2, 'Test 166');
test(minValidStrings(["repeated", "repeate", "repeat", "repe", "rep", "re", "r"], "repeatedrepeatedrepeatedrepeated"), 4, 'Test 167');
test(minValidStrings(["aaa","aa","a"], "aaaaaaaaaa"), 4, 'Test 168');
test(minValidStrings(["prefix", "prefi", "pref", "pre"], "prefixprefiprefpre"), 4, 'Test 169');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

