// Test: 1419. Minimum Number Of Frogs Croaking
// 197 test cases from LeetCodeDataset
// Run: node test.js

const { minNumberOfFrogs } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n1419. Minimum Number Of Frogs Croaking\n");

test(minNumberOfFrogs("croakcroakcroak"), 1, 'Test 1');
test(minNumberOfFrogs("croak"), 1, 'Test 2');
test(minNumberOfFrogs("cccrroooaaakkk"), -1, 'Test 3');
test(minNumberOfFrogs("crcoakroak"), 2, 'Test 4');
test(minNumberOfFrogs("crrcooakak"), -1, 'Test 5');
test(minNumberOfFrogs("k"), -1, 'Test 6');
test(minNumberOfFrogs("crocakroak"), 2, 'Test 7');
test(minNumberOfFrogs("ccccrrrrooooaaaakkkk"), 4, 'Test 8');
test(minNumberOfFrogs("crrrroooaaaakkk"), -1, 'Test 9');
test(minNumberOfFrogs("ccroooakk"), -1, 'Test 10');
test(minNumberOfFrogs("ccroakroak"), 2, 'Test 11');
test(minNumberOfFrogs("crrrroooookkkkaaa"), -1, 'Test 12');
test(minNumberOfFrogs("ccccrrrroooaaaaakkkkkk"), -1, 'Test 13');
test(minNumberOfFrogs("kakakakakakakakakakakakakakakakakakakakakakakakakakakakakakakakakak"), -1, 'Test 14');
test(minNumberOfFrogs("ccccroakroakroak"), -1, 'Test 15');
test(minNumberOfFrogs("kkkrrrooocccaaa"), -1, 'Test 16');
test(minNumberOfFrogs("ccccrrrroooaaaaakkkkk"), -1, 'Test 17');
test(minNumberOfFrogs("croakcrook"), -1, 'Test 18');
test(minNumberOfFrogs("crorocroakakak"), -1, 'Test 19');
test(minNumberOfFrogs("crocroak"), -1, 'Test 20');
test(minNumberOfFrogs("croakcroakcroakcroakcroakcroakcroakcroakcroakcroak"), 1, 'Test 21');
test(minNumberOfFrogs("c"), -1, 'Test 22');
test(minNumberOfFrogs("crorocakak"), -1, 'Test 23');
test(minNumberOfFrogs("ccccrrrroooaaaakkk"), -1, 'Test 24');
test(minNumberOfFrogs("kroac"), -1, 'Test 25');
test(minNumberOfFrogs("crocak"), -1, 'Test 26');
test(minNumberOfFrogs("crcroaoakk"), 2, 'Test 27');
test(minNumberOfFrogs("kraoc"), -1, 'Test 28');
test(minNumberOfFrogs("ccccrrooookkkk"), -1, 'Test 29');
test(minNumberOfFrogs(""), 0, 'Test 30');
test(minNumberOfFrogs("ccrroookkaak"), -1, 'Test 31');
test(minNumberOfFrogs("crocroakakroak"), -1, 'Test 32');
test(minNumberOfFrogs("croakcroak"), 1, 'Test 33');
test(minNumberOfFrogs("ccccrrroooookkkkaaaaaaaaaaaaaaaaa"), -1, 'Test 34');
test(minNumberOfFrogs("ccccccroooooorrrraaaaaakkkkk"), -1, 'Test 35');
test(minNumberOfFrogs("ccccrrrrrrroooooooooookkkkkkkkaaaaaaaaaacrrrrrrroooooooooookkkkkkkkaaaaaaaaa"), -1, 'Test 36');
test(minNumberOfFrogs("croakccccrrroooookkkkroak"), -1, 'Test 37');
test(minNumberOfFrogs("crocroakcrocroakcroak"), -1, 'Test 38');
test(minNumberOfFrogs("cccrroooakkkaaaa"), -1, 'Test 39');
test(minNumberOfFrogs("croakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroak"), 1, 'Test 40');
test(minNumberOfFrogs("crocakroakroakroak"), -1, 'Test 41');
test(minNumberOfFrogs("croakccroakrrrooookkkkaaaa"), -1, 'Test 42');
test(minNumberOfFrogs("ccccrrroooookkkk"), -1, 'Test 43');
test(minNumberOfFrogs("ccccrooookaaaakkkkk"), -1, 'Test 44');
test(minNumberOfFrogs("crocakcroakcroak"), -1, 'Test 45');
test(minNumberOfFrogs("croakkkkroakkkkroakkkk"), -1, 'Test 46');
test(minNumberOfFrogs("croakkkkkkkkkk"), -1, 'Test 47');
test(minNumberOfFrogs("crrrroookaaaaaakkkk"), -1, 'Test 48');
test(minNumberOfFrogs("ccccrrroooookkkkaaaa"), -1, 'Test 49');
test(minNumberOfFrogs("crcrooakakro"), -1, 'Test 50');
test(minNumberOfFrogs("crocakroakcroakcroakcroakcroak"), 2, 'Test 51');
test(minNumberOfFrogs("crocroakcroakccccrrroooookkkkaaaa"), -1, 'Test 52');
test(minNumberOfFrogs("ccccrrrooooookkkkkaaa"), -1, 'Test 53');
test(minNumberOfFrogs("ccccrrrrooooaaaakkkkccrrrrooooaaaakkkkccrrrrooooaaaakkkk"), -1, 'Test 54');
test(minNumberOfFrogs("crcrccrooaaakk"), -1, 'Test 55');
test(minNumberOfFrogs("cccrrooookkkkraaacroak"), -1, 'Test 56');
test(minNumberOfFrogs("croakccroakcroak"), -1, 'Test 57');
test(minNumberOfFrogs("ccccrrrroooookkkkaaaa"), -1, 'Test 58');
test(minNumberOfFrogs("crrroooookkkkaaaakkk"), -1, 'Test 59');
test(minNumberOfFrogs("cccrooookkkkrrrooookkkk"), -1, 'Test 60');
test(minNumberOfFrogs("crrrcroakroakroakroakroak"), -1, 'Test 61');
test(minNumberOfFrogs("croakcroakccroakcroak"), -1, 'Test 62');
test(minNumberOfFrogs("crocroakcroakcroakcroakcroakcroakcroakcroak"), -1, 'Test 63');
test(minNumberOfFrogs("crrroooookkkkkaaaakkkk"), -1, 'Test 64');
test(minNumberOfFrogs("crocroakcrocroakcrocroak"), -1, 'Test 65');
test(minNumberOfFrogs("croakkkkrooocrakcroak"), -1, 'Test 66');
test(minNumberOfFrogs("crcrooakrakok"), -1, 'Test 67');
test(minNumberOfFrogs("crocakrocakrocak"), -1, 'Test 68');
test(minNumberOfFrogs("croakcrocakcroakcrocakcrocak"), -1, 'Test 69');
test(minNumberOfFrogs("ccccrrrrooooaaaakkkkccccrrrrooooaaaakkkkccccrrrrooooaaaakkkkccccrrrrooooaaaakkkk"), 4, 'Test 70');
test(minNumberOfFrogs("croakkkkrooocrakcroakcroakcroak"), -1, 'Test 71');
test(minNumberOfFrogs("crcoakrcoak"), -1, 'Test 72');
test(minNumberOfFrogs("crrrrooooookkkkkkaaaa"), -1, 'Test 73');
test(minNumberOfFrogs("ccccroooaaaaakkkakkkakkk"), -1, 'Test 74');
test(minNumberOfFrogs("ccccroooaaaaakkkakkk"), -1, 'Test 75');
test(minNumberOfFrogs("crorocokakak"), -1, 'Test 76');
test(minNumberOfFrogs("crrrrroooookkkkaaaa"), -1, 'Test 77');
test(minNumberOfFrogs("croakcrrooakroakroakcroak"), -1, 'Test 78');
test(minNumberOfFrogs("crcrooakkaakrook"), -1, 'Test 79');
test(minNumberOfFrogs("crocakroakroakroakroakroakroakroakroakroakroak"), -1, 'Test 80');
test(minNumberOfFrogs("crcrooakrakokcrcrooakrakokcrcrooakrakok"), -1, 'Test 81');
test(minNumberOfFrogs("ccccrooookaaaakkkkkkk"), -1, 'Test 82');
test(minNumberOfFrogs("ccrrroooookkkkaaaa"), -1, 'Test 83');
test(minNumberOfFrogs("croakccrookraaaakkk"), -1, 'Test 84');
test(minNumberOfFrogs("ccccccccrrrrrroooooookkkkkkkkkkkaaaaaaaaa"), -1, 'Test 85');
test(minNumberOfFrogs("crocroakkkk"), -1, 'Test 86');
test(minNumberOfFrogs("croakrcoakcroak"), -1, 'Test 87');
test(minNumberOfFrogs("croakkkkrooocrakcroakcroak"), -1, 'Test 88');
test(minNumberOfFrogs("ccccrrrooooookkkkaaaa"), -1, 'Test 89');
test(minNumberOfFrogs("crocrocrocrocroakroakroak"), -1, 'Test 90');
test(minNumberOfFrogs("crrrroooookkkkaaaak"), -1, 'Test 91');
test(minNumberOfFrogs("croakkkkkkrrroooooooaaaaaaa"), -1, 'Test 92');
test(minNumberOfFrogs("crcoakroakcrcoakroak"), 2, 'Test 93');
test(minNumberOfFrogs("crocrocrocrocrocroakroakroakroakroak"), -1, 'Test 94');
test(minNumberOfFrogs("ccccrrroooookkkkkaaaa"), -1, 'Test 95');
test(minNumberOfFrogs("crocakroakcroakcroak"), 2, 'Test 96');
test(minNumberOfFrogs("crcrcooakokrakraokakcroakcroak"), -1, 'Test 97');
test(minNumberOfFrogs("crrrroooookkkkaaaakkkk"), -1, 'Test 98');
test(minNumberOfFrogs("ccccroooaaaakkkk"), -1, 'Test 99');
test(minNumberOfFrogs("croakkkkkkkkkkroakroakroakcroak"), -1, 'Test 100');
test(minNumberOfFrogs("ccccccroooooorrrraaaaaakkkkkkk"), -1, 'Test 101');
test(minNumberOfFrogs("crcroakroakcrcoak"), -1, 'Test 102');
test(minNumberOfFrogs("ccrrroooookkkkaaaak"), -1, 'Test 103');
test(minNumberOfFrogs("crocroakcroakcroakcroakcroakcroakcroakcroakcroak"), -1, 'Test 104');
test(minNumberOfFrogs("crcoakrcoakrcoak"), -1, 'Test 105');
test(minNumberOfFrogs("ccccrrrooookkkkaaaakkkkroakroak"), -1, 'Test 106');
test(minNumberOfFrogs("ccccccccrrrrrrrrrrroooooooooookkkkkkkkaaaaaaaa"), -1, 'Test 107');
test(minNumberOfFrogs("ccrooakrkkaocroakcraok"), -1, 'Test 108');
test(minNumberOfFrogs("crcrooakrakokcrcrooakrakok"), -1, 'Test 109');
test(minNumberOfFrogs("crorarokkorakocraok"), -1, 'Test 110');
test(minNumberOfFrogs("croakroakroakcroakroakroakroakcroakroakroak"), -1, 'Test 111');
test(minNumberOfFrogs("ccccrrroooookkkkaaaaaaaaa"), -1, 'Test 112');
test(minNumberOfFrogs("cccrroooraaakk"), -1, 'Test 113');
test(minNumberOfFrogs("crocrocrocrocroakroakroakroak"), -1, 'Test 114');
test(minNumberOfFrogs("crocroakcroakcroakcroakcroakcroakcroakcroakcroakcroak"), -1, 'Test 115');
test(minNumberOfFrogs("ccccroooraaaakkkkk"), -1, 'Test 116');
test(minNumberOfFrogs("crocroakroakcroak"), -1, 'Test 117');
test(minNumberOfFrogs("crocroakroakroakroak"), -1, 'Test 118');
test(minNumberOfFrogs("croakcroakcrorocroak"), -1, 'Test 119');
test(minNumberOfFrogs("croakcroakroakcroakcroak"), -1, 'Test 120');
test(minNumberOfFrogs("crrrrroooookkkkaaaaakkkk"), -1, 'Test 121');
test(minNumberOfFrogs("ccccroooaarrrkkk"), -1, 'Test 122');
test(minNumberOfFrogs("ccccroooaaaaakkkaaa"), -1, 'Test 123');
test(minNumberOfFrogs("crrrrrrrrroooooooooookkkkkkkkaaaaaaaaa"), -1, 'Test 124');
test(minNumberOfFrogs("croakcroakcroakcroakcroakcroakcroakcroakcroak"), 1, 'Test 125');
test(minNumberOfFrogs("ccrroooaakkccrooakaakk"), -1, 'Test 126');
test(minNumberOfFrogs("ccrrroooookkkkaaaacccrrroooookkkkaaaa"), -1, 'Test 127');
test(minNumberOfFrogs("ccccroakcroakcroakroakcroak"), -1, 'Test 128');
test(minNumberOfFrogs("crcrooakakroccrooakakro"), -1, 'Test 129');
test(minNumberOfFrogs("croakcroakroakroakroakroakroakroak"), -1, 'Test 130');
test(minNumberOfFrogs("ccroakroakroak"), -1, 'Test 131');
test(minNumberOfFrogs("crocrokakakcroakroakroak"), -1, 'Test 132');
test(minNumberOfFrogs("croakcroakcroakcroak"), 1, 'Test 133');
test(minNumberOfFrogs("ccccrrrrooooaaaakkkkccccrrrrooooaaaakkkkccccrrrrooooaaaakkkk"), 4, 'Test 134');
test(minNumberOfFrogs("ccroakccroakccroak"), -1, 'Test 135');
test(minNumberOfFrogs("ccccrrroooookkkkkk"), -1, 'Test 136');
test(minNumberOfFrogs("cccrroooookkkkaaaakkkk"), -1, 'Test 137');
test(minNumberOfFrogs("crrrroooookkkkac"), -1, 'Test 138');
test(minNumberOfFrogs("crorokokokakakc"), -1, 'Test 139');
test(minNumberOfFrogs("crocakcroakcroakcroak"), -1, 'Test 140');
test(minNumberOfFrogs("crrrooookkkkaaacrrrooookkkkaaa"), -1, 'Test 141');
test(minNumberOfFrogs("crocroakroakroakcroakcroak"), -1, 'Test 142');
test(minNumberOfFrogs("ccrroookkaaa"), -1, 'Test 143');
test(minNumberOfFrogs("crrrooookkkk"), -1, 'Test 144');
test(minNumberOfFrogs("crocrokakakcroakroak"), -1, 'Test 145');
test(minNumberOfFrogs("ccrroooaakkccrooakaakkccrroooaakk"), -1, 'Test 146');
test(minNumberOfFrogs("ccccrrroooookkkkaaaacrrroooookkkkaaaacrrroooookkkkaaa"), -1, 'Test 147');
test(minNumberOfFrogs("croakcroakcroakcroakcroakcroakcroakcroak"), 1, 'Test 148');
test(minNumberOfFrogs("croakcroakcroakcroakcroakcroakcroak"), 1, 'Test 149');
test(minNumberOfFrogs("croakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroak"), 1, 'Test 150');
test(minNumberOfFrogs("crcrrooookkkaaa"), -1, 'Test 151');
test(minNumberOfFrogs("crocroakroakroakroakcroakcroak"), -1, 'Test 152');
test(minNumberOfFrogs("crocroakcroak"), -1, 'Test 153');
test(minNumberOfFrogs("crrrcroakroakroakroakroakroak"), -1, 'Test 154');
test(minNumberOfFrogs("crrroookkkkrrroooookkkk"), -1, 'Test 155');
test(minNumberOfFrogs("crrrooookkkkaaa"), -1, 'Test 156');
test(minNumberOfFrogs("crocrokrocroakakak"), -1, 'Test 157');
test(minNumberOfFrogs("crrookkcraaacroakcroak"), -1, 'Test 158');
test(minNumberOfFrogs("crcrcooakokrakraokak"), -1, 'Test 159');
test(minNumberOfFrogs("crocroakcrocroakcrocroakcroak"), -1, 'Test 160');
test(minNumberOfFrogs("croakcroakcroakcroakccroooaakk"), -1, 'Test 161');
test(minNumberOfFrogs("ccccrrrrrrrooooooookkkkkkkaaaaaaa"), -1, 'Test 162');
test(minNumberOfFrogs("croakcroakccroaaaakkk"), -1, 'Test 163');
test(minNumberOfFrogs("crocroakroakcroakcroak"), -1, 'Test 164');
test(minNumberOfFrogs("crocroakroakcroakcroakcroak"), -1, 'Test 165');
test(minNumberOfFrogs("crocroakroakroakroakroakroakroakroakroakroakcroakcroak"), -1, 'Test 166');
test(minNumberOfFrogs("crrroooookkkkaaaakkkkkkk"), -1, 'Test 167');
test(minNumberOfFrogs("ccccrrrooookkkkaaakk"), -1, 'Test 168');
test(minNumberOfFrogs("crrcroakroakcroakroakroak"), -1, 'Test 169');
test(minNumberOfFrogs("ccccrrrrroooookkkkaaaakkkk"), -1, 'Test 170');
test(minNumberOfFrogs("ccccrrroooookkkkaaaakkkk"), -1, 'Test 171');
test(minNumberOfFrogs("ccroakcroakcroakcroakcroakcroak"), -1, 'Test 172');
test(minNumberOfFrogs("croakcrocakcroakcrocak"), -1, 'Test 173');
test(minNumberOfFrogs("ccccrrrrooooaaaakkkkccccrrrrooooaaaakkkk"), 4, 'Test 174');
test(minNumberOfFrogs("croakcroakcrcoakroakcrocroak"), -1, 'Test 175');
test(minNumberOfFrogs("crcrooakakroccrooakakroccrooakakro"), -1, 'Test 176');
test(minNumberOfFrogs("crocakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroakcroak"), -1, 'Test 177');
test(minNumberOfFrogs("crocroakroakcroakcroakcroakcroak"), -1, 'Test 178');
test(minNumberOfFrogs("croakkkcroak"), -1, 'Test 179');
test(minNumberOfFrogs("ccroakroakroakroak"), -1, 'Test 180');
test(minNumberOfFrogs("ccccrooorkkkaa"), -1, 'Test 181');
test(minNumberOfFrogs("crcrooakrakokcrcrooakrakokcrcrooakrakokcrcrooakrakok"), -1, 'Test 182');
test(minNumberOfFrogs("crcrooakrakokcrcrooakrakokcrcrooakrakokcrcrooakrakokcrcrooakrakok"), -1, 'Test 183');
test(minNumberOfFrogs("croakcroakcroakcroakcroakcroak"), 1, 'Test 184');
test(minNumberOfFrogs("cccroooraakk"), -1, 'Test 185');
test(minNumberOfFrogs("crrrooookkkkkaaa"), -1, 'Test 186');
test(minNumberOfFrogs("ccccrrrrroooookkkkaaaa"), -1, 'Test 187');
test(minNumberOfFrogs("crrroookkkkrrroooookkkkrrroooookkkk"), -1, 'Test 188');
test(minNumberOfFrogs("crocrocrocroakroakroakroak"), -1, 'Test 189');
test(minNumberOfFrogs("crocrocrocrocrocrocrocrocrocrocrocrocroak"), -1, 'Test 190');
test(minNumberOfFrogs("croakcroakcroakcroakcroak"), 1, 'Test 191');
test(minNumberOfFrogs("crrrooookkkkaaaa"), -1, 'Test 192');
test(minNumberOfFrogs("crrrrroooookkkkaaaaacrrrrroooookkkkaaaa"), -1, 'Test 193');
test(minNumberOfFrogs("ccccrrrooookkkkaaaaaaaaaa"), -1, 'Test 194');
test(minNumberOfFrogs("cccroaaakkkkroooraak"), -1, 'Test 195');
test(minNumberOfFrogs("croakcroakcrocroakroak"), -1, 'Test 196');
test(minNumberOfFrogs("crcroakroakroakroakroakroak"), -1, 'Test 197');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

