// Test: 3274. Check If Two Chessboard Squares Have The Same Color
// 154 test cases from LeetCodeDataset
// Run: node test.js

const { checkTwoChessboards } = require("./solution");

let passed = 0, failed = 0;
function test(actual, expected, label) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    console.log(`  ✗ ${label}`);
    console.log(`    Expected: ${e}`);
    console.log(`    Actual:   ${a}`);
    failed++;
  }
}

console.log("\n3274. Check If Two Chessboard Squares Have The Same Color\n");

test(checkTwoChessboards("g7", "f8"), true, 'Test 1');
test(checkTwoChessboards("a1", "c3"), true, 'Test 2');
test(checkTwoChessboards("e5", "g7"), true, 'Test 3');
test(checkTwoChessboards("b2", "d4"), true, 'Test 4');
test(checkTwoChessboards("b2", "b2"), true, 'Test 5');
test(checkTwoChessboards("g7", "h8"), true, 'Test 6');
test(checkTwoChessboards("e5", "e5"), true, 'Test 7');
test(checkTwoChessboards("g2", "h4"), false, 'Test 8');
test(checkTwoChessboards("a1", "h3"), false, 'Test 9');
test(checkTwoChessboards("h8", "f6"), true, 'Test 10');
test(checkTwoChessboards("c6", "b5"), true, 'Test 11');
test(checkTwoChessboards("c5", "e7"), true, 'Test 12');
test(checkTwoChessboards("d4", "f6"), true, 'Test 13');
test(checkTwoChessboards("h1", "a8"), true, 'Test 14');
test(checkTwoChessboards("a8", "h1"), true, 'Test 15');
test(checkTwoChessboards("c2", "e8"), true, 'Test 16');
test(checkTwoChessboards("d8", "c7"), true, 'Test 17');
test(checkTwoChessboards("d7", "b6"), false, 'Test 18');
test(checkTwoChessboards("h4", "a1"), true, 'Test 19');
test(checkTwoChessboards("f2", "e1"), true, 'Test 20');
test(checkTwoChessboards("g1", "h2"), true, 'Test 21');
test(checkTwoChessboards("c8", "d6"), false, 'Test 22');
test(checkTwoChessboards("c2", "a4"), true, 'Test 23');
test(checkTwoChessboards("f1", "c2"), true, 'Test 24');
test(checkTwoChessboards("e3", "f4"), true, 'Test 25');
test(checkTwoChessboards("d2", "f7"), false, 'Test 26');
test(checkTwoChessboards("f7", "g8"), true, 'Test 27');
test(checkTwoChessboards("g4", "h6"), false, 'Test 28');
test(checkTwoChessboards("b1", "d3"), true, 'Test 29');
test(checkTwoChessboards("c5", "a5"), true, 'Test 30');
test(checkTwoChessboards("g8", "h2"), false, 'Test 31');
test(checkTwoChessboards("b7", "c8"), true, 'Test 32');
test(checkTwoChessboards("a4", "b5"), true, 'Test 33');
test(checkTwoChessboards("e6", "f7"), true, 'Test 34');
test(checkTwoChessboards("f6", "g7"), true, 'Test 35');
test(checkTwoChessboards("b5", "a4"), true, 'Test 36');
test(checkTwoChessboards("h2", "g4"), false, 'Test 37');
test(checkTwoChessboards("a5", "c5"), true, 'Test 38');
test(checkTwoChessboards("c7", "d8"), true, 'Test 39');
test(checkTwoChessboards("c1", "d2"), true, 'Test 40');
test(checkTwoChessboards("g6", "h7"), true, 'Test 41');
test(checkTwoChessboards("a2", "b3"), true, 'Test 42');
test(checkTwoChessboards("a3", "b4"), true, 'Test 43');
test(checkTwoChessboards("b1", "c2"), true, 'Test 44');
test(checkTwoChessboards("a5", "b6"), true, 'Test 45');
test(checkTwoChessboards("a3", "c7"), true, 'Test 46');
test(checkTwoChessboards("d2", "e3"), true, 'Test 47');
test(checkTwoChessboards("h1", "e8"), true, 'Test 48');
test(checkTwoChessboards("g3", "h2"), true, 'Test 49');
test(checkTwoChessboards("h7", "g6"), true, 'Test 50');
test(checkTwoChessboards("e5", "d6"), true, 'Test 51');
test(checkTwoChessboards("d4", "e5"), true, 'Test 52');
test(checkTwoChessboards("b8", "a7"), true, 'Test 53');
test(checkTwoChessboards("c5", "e5"), true, 'Test 54');
test(checkTwoChessboards("b5", "c6"), true, 'Test 55');
test(checkTwoChessboards("b1", "h7"), true, 'Test 56');
test(checkTwoChessboards("c5", "d5"), false, 'Test 57');
test(checkTwoChessboards("c8", "d7"), true, 'Test 58');
test(checkTwoChessboards("d5", "e6"), true, 'Test 59');
test(checkTwoChessboards("f4", "g5"), true, 'Test 60');
test(checkTwoChessboards("b2", "c1"), true, 'Test 61');
test(checkTwoChessboards("d6", "b4"), true, 'Test 62');
test(checkTwoChessboards("c3", "d4"), true, 'Test 63');
test(checkTwoChessboards("g4", "h5"), true, 'Test 64');
test(checkTwoChessboards("b3", "a4"), true, 'Test 65');
test(checkTwoChessboards("e8", "f4"), false, 'Test 66');
test(checkTwoChessboards("a8", "b7"), true, 'Test 67');
test(checkTwoChessboards("d8", "b6"), true, 'Test 68');
test(checkTwoChessboards("d2", "f8"), true, 'Test 69');
test(checkTwoChessboards("f8", "e7"), true, 'Test 70');
test(checkTwoChessboards("f3", "e2"), true, 'Test 71');
test(checkTwoChessboards("a3", "e7"), true, 'Test 72');
test(checkTwoChessboards("f1", "g2"), true, 'Test 73');
test(checkTwoChessboards("b1", "g2"), true, 'Test 74');
test(checkTwoChessboards("h1", "g8"), true, 'Test 75');
test(checkTwoChessboards("g4", "c8"), true, 'Test 76');
test(checkTwoChessboards("a1", "e5"), true, 'Test 77');
test(checkTwoChessboards("a8", "b1"), true, 'Test 78');
test(checkTwoChessboards("a5", "h8"), true, 'Test 79');
test(checkTwoChessboards("h6", "g7"), true, 'Test 80');
test(checkTwoChessboards("e6", "d5"), true, 'Test 81');
test(checkTwoChessboards("e5", "c7"), true, 'Test 82');
test(checkTwoChessboards("g7", "h6"), true, 'Test 83');
test(checkTwoChessboards("a7", "c5"), true, 'Test 84');
test(checkTwoChessboards("g2", "h3"), true, 'Test 85');
test(checkTwoChessboards("d7", "e8"), true, 'Test 86');
test(checkTwoChessboards("b6", "c7"), true, 'Test 87');
test(checkTwoChessboards("a1", "b1"), false, 'Test 88');
test(checkTwoChessboards("d8", "f2"), true, 'Test 89');
test(checkTwoChessboards("a7", "b8"), true, 'Test 90');
test(checkTwoChessboards("f5", "g6"), true, 'Test 91');
test(checkTwoChessboards("e5", "f6"), true, 'Test 92');
test(checkTwoChessboards("a4", "h7"), true, 'Test 93');
test(checkTwoChessboards("d2", "c1"), true, 'Test 94');
test(checkTwoChessboards("a3", "c1"), true, 'Test 95');
test(checkTwoChessboards("h8", "g8"), false, 'Test 96');
test(checkTwoChessboards("b8", "c7"), true, 'Test 97');
test(checkTwoChessboards("f8", "g3"), true, 'Test 98');
test(checkTwoChessboards("e2", "h5"), true, 'Test 99');
test(checkTwoChessboards("a5", "a5"), true, 'Test 100');
test(checkTwoChessboards("e5", "d4"), true, 'Test 101');
test(checkTwoChessboards("d7", "e6"), true, 'Test 102');
test(checkTwoChessboards("c6", "d7"), true, 'Test 103');
test(checkTwoChessboards("e4", "f5"), true, 'Test 104');
test(checkTwoChessboards("h8", "a1"), true, 'Test 105');
test(checkTwoChessboards("g5", "h6"), true, 'Test 106');
test(checkTwoChessboards("d7", "d8"), false, 'Test 107');
test(checkTwoChessboards("c6", "e8"), true, 'Test 108');
test(checkTwoChessboards("e4", "b7"), true, 'Test 109');
test(checkTwoChessboards("e2", "f3"), true, 'Test 110');
test(checkTwoChessboards("f1", "e2"), true, 'Test 111');
test(checkTwoChessboards("f3", "a7"), false, 'Test 112');
test(checkTwoChessboards("c2", "d3"), true, 'Test 113');
test(checkTwoChessboards("g5", "f4"), true, 'Test 114');
test(checkTwoChessboards("b3", "c4"), true, 'Test 115');
test(checkTwoChessboards("f1", "e3"), false, 'Test 116');
test(checkTwoChessboards("c1", "e3"), true, 'Test 117');
test(checkTwoChessboards("f2", "g3"), true, 'Test 118');
test(checkTwoChessboards("e1", "f2"), true, 'Test 119');
test(checkTwoChessboards("a1", "b2"), true, 'Test 120');
test(checkTwoChessboards("b3", "d3"), true, 'Test 121');
test(checkTwoChessboards("b5", "d5"), true, 'Test 122');
test(checkTwoChessboards("d3", "e4"), true, 'Test 123');
test(checkTwoChessboards("c4", "e6"), true, 'Test 124');
test(checkTwoChessboards("e4", "d5"), true, 'Test 125');
test(checkTwoChessboards("d6", "e7"), true, 'Test 126');
test(checkTwoChessboards("b1", "a2"), true, 'Test 127');
test(checkTwoChessboards("h1", "g2"), true, 'Test 128');
test(checkTwoChessboards("d1", "e2"), true, 'Test 129');
test(checkTwoChessboards("c5", "d6"), true, 'Test 130');
test(checkTwoChessboards("a6", "b7"), true, 'Test 131');
test(checkTwoChessboards("f3", "g4"), true, 'Test 132');
test(checkTwoChessboards("f5", "f5"), true, 'Test 133');
test(checkTwoChessboards("d5", "f7"), true, 'Test 134');
test(checkTwoChessboards("a1", "b8"), true, 'Test 135');
test(checkTwoChessboards("b3", "e4"), true, 'Test 136');
test(checkTwoChessboards("g4", "f7"), true, 'Test 137');
test(checkTwoChessboards("e7", "d8"), true, 'Test 138');
test(checkTwoChessboards("c5", "a1"), true, 'Test 139');
test(checkTwoChessboards("e7", "f8"), true, 'Test 140');
test(checkTwoChessboards("h5", "a6"), true, 'Test 141');
test(checkTwoChessboards("d7", "f9"), true, 'Test 142');
test(checkTwoChessboards("h8", "g7"), true, 'Test 143');
test(checkTwoChessboards("g3", "h4"), true, 'Test 144');
test(checkTwoChessboards("f5", "c8"), true, 'Test 145');
test(checkTwoChessboards("b7", "d5"), true, 'Test 146');
test(checkTwoChessboards("a1", "h8"), true, 'Test 147');
test(checkTwoChessboards("d8", "e5"), true, 'Test 148');
test(checkTwoChessboards("d1", "d8"), false, 'Test 149');
test(checkTwoChessboards("b4", "c5"), true, 'Test 150');
test(checkTwoChessboards("c4", "d5"), true, 'Test 151');
test(checkTwoChessboards("h6", "b2"), true, 'Test 152');
test(checkTwoChessboards("b2", "c3"), true, 'Test 153');
test(checkTwoChessboards("h5", "g4"), true, 'Test 154');

console.log(`\nResult: ${passed}/${passed + failed} passed` + (failed ? ` (${failed} failed)` : " ✓") + "\n");
if (failed) process.exitCode = 1;

